### ISSUE TITLE
"pidof -c" error sysvinit centos/rhel

### ISSUE THREAD

**Issue by jessfraz** [moby/moby#11049]
moved from #6800 into new issue

Sysvinitscripts in CentOS/RHEL broken as they call 'pidof -c' to check process status, which uses /proc/[pid]/root to detect chroots:

```
[root@c67c75b29a6d /]# strace pidof -c logger 2>&1 | grep '/proc/[0-9]\+/root'
stat("/proc/87/root", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/proc/29/root", 0x7fffc6552060)   = -1 EACCES (Permission denied)
```

Whereas outside of Docker stat does not return error:

```
[root@prod-po-tjniivm1 ~]# strace pidof -c logger 2>&1 | grep '/proc/[0-9]\+/root'
stat("/proc/4149/root", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/proc/3749/root", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
```

pidof -c failing in the container causes the __pids_pidof() function in /etc/init.d/functions to return no pids, even if the process is running.  This breaks the status() function as well as the killproc() function.  The latter may break stop functionality of an init script.

'--cap-add SYS_PTRACE' resolves this for me on 1.2.0.

**Comment by jfrazelle** [comment]
@CCTJNII  does this look good to you

**Comment by CCTJNII** [comment]
Looks good. :thumbsup:

**Comment by md-5** [comment]
As mentioned in #6800 I feel that either SYS_PTRACE should be a default or someone needs to add a new PID CAP to the kernel and make Docker use it. Having pidof broken by default leaves very many daemons unable to work under Docker without manual intervention.

**Comment by ThomasSteinbach** [comment]
Am I happy to find at least an explanation of the _service tomcat7 start_ behavior. I tried to install and run tomcat on different versions of ubuntu containers, I installed tomcat inside a vagrant ubuntu where everything runs fine, I compared the configuration (which was obvious equal), I ran the startup script with _sh -x_ where I got to the command that fails, which slowly took my after several other investigations and google searches to this issue.

@jfrazelle Even though there is an official tomcat, why shouldn't I am be able to create my own tomcat image? I am playing around with building images by running Ansible playbooks during the build, which are much more appealilng than loads of scripts. Now I got some playbooks running inside a container started with ```--cap-add=SYS_PTRACE``` but build them with ```docker build``` because there is no such option.

After I had read all the previous comments I hear the voice that there should be no concerns by allowing _SYS_PTRACE_ by default. Shouldn't it be considered to save others the troubles I and some others had, by allowing _SYS_PTRACE_ by default? Or could it be possible to inform users, when an action (during the build) needs one of those 'caps' (I haven't fully got what caps are) so that he can at least find faster solutions on the internet?

And finally, is there a possibility to run something like
```
docker build --cap-add=SYS_PTRACE ...
```
?

**Comment by arienkock** [comment]
since there are `--ulimit` and `--cgroup-parent` and in the future other `docker run` options you might want to pass to a build command, perhaps make it more generic and add a way to pass arbitrary args?

    docker build --run-args="--cap-add=SYS_PTRACE" .

**Comment by vdemeester** [comment]
Given the activity on this issues, I'll close it as I think it's either not needed or already done. But if you think otherwise, feel free to discuss it and we'll re-open 😉

**Comment by DHager** [comment]
Funny enough, I just now came across this issue when diagnosing postfix failures from `centos:centos6.9`, and tracing it back to init-scripts which, despite running a root, do not have permission to follow symlinks for `/proc/$pid/exe`. (The cross-check fails, so they assume a PID file is invalid.)

Is the TLDR on this: "Won't fix because of security concerns, either run privileged or use different process-management techniques"?

**Comment by sjpotter** [comment]
the problem still exists for anyone wanting to use something like start-stop-daemon that checks a pid file and compares the running pid against the exec line passed to it.
