### ISSUE TITLE
Windows client crashes when run in Intellij terminal

### ISSUE THREAD

**Issue by jleskovar** [moby/moby#12506]
Not really sure if this is an Intellij issue or a Docker client issue, but when you try to run the docker command inside of a terminal in Intellij, the following error is thrown:

```
C:\Users\James\IdeaProjects\utility-meter-reader>docker
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/docker/docker/pkg/term/winconsole.WinConsoleStreams(0x382498, 0xc08200ab40, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/pkg/term/winconsole/console_windows.go:252 +0x50f
github.com/docker/docker/pkg/term.StdStreams(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/pkg/term/term_windows.go:34 +0x268
main.main()
        /go/src/github.com/docker/docker/docker/docker.go:34 +0x47

goroutine 5 [runnable]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:19
created by os/signal.init┬À1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x3c
```

To reproduce:

1) Open up Intellij (14.1.1) in Windows (7 SP1)
2) Bring up the Terminal (Alt+F12)
3) Type 'docker' and hit enter

I am using docker 1.6:

```
C:\Users\James>docker -v
Docker version 1.6.0, build 4749651
```

**Comment by jleskovar** [comment]
Git blame shows @tiborvass [worked on this](https://github.com/docker/docker/blame/master/pkg/term/winconsole/console_windows.go#L252) not long ago. Maybe he can shed some light? Cheers

**Comment by thaJeztah** [comment]
@jleskovar thanks for reporting! Out of the box, windows shell miss some features that are needed to run docker correctly. The docker binary has some code to emulate these features, depending on the terminal that it's running in (`cmd.exe`, `PowerShell`).

I'm sure that the IntellIj hasn't been added to the list of supported terminals (yet), so that's probably why it is crashing.

It *would* make a great feature, now that Jetbrains is working on adding support for Docker. So I think this should be looked in to at some point.

Thanks!

**Comment by thaJeztah** [comment]
/cc @ahmetalpbalkan Nice case! I labeled it both "bug" and "feature" because it can be seen as both. I think this should be added to the "known issues" list, and some info to the Windows docs (which shells are supported, and that other shells can cause a panic (but please report!))

With regard to IntelliJ; I know Jetbrains (the developer behind IntelliJ) is **very** supportive to open source and open in their development. They give free licenses for their products to open source, so if needed, you can ask them. They may also be interested in working together in solving this.

/cc @maartenba (for Jetbrains)

**Comment by maartenba** [comment]
Adding @hhariri

**Comment by thaJeztah** [comment]
Thanks, @maartenba I didn't know who I should ping, and your name was the first that came up in my mind :)

**Comment by hhariri** [comment]
Hi @thaJeztah. I've pinged my colleague Mikhail whom is the one that works on Docker integration. In the meantime though, if you think it might be an issue with IntelliJ I think it would be great if you could log it in our issue tracker https://youtrack.jetbrains.com/issues/IDEA

**Comment by ahmetalpbalkan** [comment]
@jleskovar thanks for reporting this. I have been looking the source code and the panic comes from the Go runtime and not the Docker code (and we have seen various issues with Go runtime on Windows which we still could not debug).

I will try to reproduce this. What version/SKU of Windows are you running? What version of IntelliJ IDEA? And if you open cmd.exe, does docker.exe work just fine there?

**Comment by jleskovar** [comment]
Hi @ahmetalpbalkan, sorry for late reply. I am using Windows 7 Ultimate, SP1 64-bit. Intellij is 14.1.1 (build 141.178). docker.exe works fine in cmd.exe and git bash

**Comment by rslobodian** [comment]
I'm having the same issue using cygwin. The strange thing is that it was working fine, and all of a sudden it stopped working.
Literally this is what happened on my cygwin terminal:
```
Slobodian:~/code $ boot2docker init --memory=4096
Slobodian:~/code $ boot2docker start
Waiting for VM and Docker daemon to start...
........................ooooooooooooo
Started.
Writing C:\Users\Slobodian\.boot2docker\certs\boot2docker-vm\ca.pem
Writing C:\Users\Slobodian\.boot2docker\certs\boot2docker-vm\cert.pem
Writing C:\Users\Slobodian\.boot2docker\certs\boot2docker-vm\key.pem

To connect the Docker client to the Docker daemon, please set:
    export DOCKER_HOST=tcp://192.168.59.103:2376
    export DOCKER_CERT_PATH='C:\Users\Slobodian\.boot2docker\certs\boot2docker-vm'
    export DOCKER_TLS_VERIFY=1

Slobodian:~/code $
Slobodian:~/code $     export DOCKER_HOST=tcp://192.168.59.103:2376
Slobodian:~/code $     export DOCKER_CERT_PATH='C:\Users\Slobodian\.boot2docker\certs\boot2docker-vm'
Slobodian:~/code $     export DOCKER_TLS_VERIFY=1
Slobodian:~/code $ boot2docker info
{
        "Name": "boot2docker-vm",
        "UUID": "775577d7-90ce-411e-9071-ed5873aeed25",
        "Iso": "C:\\Users\\Slobodian\\.boot2docker\\boot2docker.iso",
        "State": "running",
        "VRAM": 8,
        "CfgFile": "C:\\\\cygwin64\\\\home\\\\Slobodian\\\\VirtualBox VMs\\\\boot2docker-vm\\\\boot2docker-vm.vbox",
        "BaseFolder": "C:\\cygwin64\\home\\Slobodian\\VirtualBox VMs\\boot2docker-vm",
        "OSType": "",
        "Flag": 0,
        "BootOrder": null,
        "DockerPort": 0,
        "SSHPort": 2022,
        "SerialFile": "\\\\.\\pipe\\boot2docker-vm"
}Slobodian:~/code $ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAM
ES
Slobodian:~/code $ docker ps
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/docker/docker/pkg/term/winconsole.WinConsoleStreams(0x132308, 0xc08200abe0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/pkg/term/winconsole/console_windows.go:252 +0x50f
github.com/docker/docker/pkg/term.StdStreams(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/pkg/term/term_windows.go:34 +0x268
main.main()
        /go/src/github.com/docker/docker/docker/docker.go:34 +0x47

goroutine 5 [runnable]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:19
created by os/signal.init┬À1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x3c
```

as you can see above, I ran `docker ps` once, it worked fine (no containers running, I had just upped boot2docker). I was expecting that, as I had successfully executed it before (I had initially created a vm with the default 2GB of memory, I wanted to up that a bit). The second time I ran it though, it crapped out and now every time I try to run `docker <anything>` it crashes with the same message. 
After reading this thread, I saw that I can run it using cmd, and indeed it works. But cmd is awful to use.

Any chance there's a workaround I can do?
Thanks.

**Comment by KoichiSenada** [comment]
I also have this bug, started out of nowhere, suddenly.
Windows 8.1 x64

```
Windows PowerShell
(C) Корпорация Майкрософт (Microsoft Corporation), 2014. Все права защищены.

PS C:\Users\Ilia\AppData\Local\Kitematic\app-0.7.4> docker --help
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/docker/docker/pkg/term/winconsole.WinConsoleStreams(0x2c2648, 0xc082006870, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/pkg/term/winconsole/console_windows.go:252 +0x50f
github.com/docker/docker/pkg/term.StdStreams(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/pkg/term/term_windows.go:34 +0x268
main.main()
        /go/src/github.com/docker/docker/docker/docker.go:35 +0x47

goroutine 2 [runnable]:
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:90
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
        /usr/local/go/src/runtime/mgc0.go:82
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
        /usr/local/go/src/runtime/malloc.go:712
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 5 [runnable]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:19
created by os/signal.init┬╖1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x3c
PS C:\Users\Ilia\AppData\Local\Kitematic\app-0.7.4>
```

**Comment by jamime** [comment]
+1 for WebStorm/Intellij

**Comment by juvan** [comment]
I have the same problem:
Win 7 + PowerSell
 
PS C:\> docker --help
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/docker/docker/pkg/term/winconsole.WinConsoleStreams(0x142648, 0xc082008870, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/pkg/term/winconsole/console_windows.go:252 +0x50f
github.com/docker/docker/pkg/term.StdStreams(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/pkg/term/term_windows.go:34 +0x268
main.main()
        /go/src/github.com/docker/docker/docker/docker.go:35 +0x47

goroutine 5 [runnable]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:19
created by os/signal.init┬À1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x3c
PS C:\>

**Comment by rfvermut** [comment]
+1

**Comment by peteanusergiu** [comment]
+1

**Comment by djimenez** [comment]
So, like some of you I was happily using docker on windows and then randomly this error started to occur - what got weirder was when I discovered it wasn't random. When my console was maximize the error occured, when it was quarter screen size it did not. So, after a failed attempt at running gdb on windows against the docker exe, i decided to just extract the GetConsoleScreenBufferInfo pieces from console_windows.go and put it in a test go executable and see what it saw. Its a pretty obvious bug once you do that.... 

The length / capacity of the character buffer slice is specified as:
```go
buffer = make([]CHAR_INFO, screenBufferInfo.MaximumWindowSize.X*screenBufferInfo.MaximumWindowSize.Y)
```
if we look at the types of X and Y there they are SHORT which is just an alias for int16.... so the result of multiplying them is an int16... which is really easy to overflow into a negative, which is exactly what was happening when my console was maximized... and a negative lenght / capacity value is illegal when making a slice.

"test" code - only works on windows and wont' actually run on playground
https://play.golang.org/p/GSRNVYgKzi

I'm not sure this bug still exist on master since things have moved around quite a bit with windows term / console handling. Looks like you've switched to using uint16 for the structs, and  But It might be nice for people on this issue to see the reason.

**Comment by ahmetalpbalkan** [comment]
@jstarks ^ this apparently is coming from go-ansiterm. Any ideas?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale, but feel free to comment if this is still an issue.

**Comment by jleskovar-tyro** [comment]
Yikes - this is a blast from the past... Fine to close as stale
