### ISSUE TITLE
Proposal: Detecting Debian/Ubuntu forked distros

### ISSUE THREAD

**Issue by fmoliveira** [moby/moby#15765]
We've already done some work on auto detecting Ubuntu forks at #15001 , though the `-u` option isn't supported in the `lsb_release` command for some distros.

**Quote from @thaJeztah :**
"We should definitely be careful not to try and fix every version out there, especially if it's deprecated." ([source](https://github.com/docker/docker/pull/15001#issuecomment-127505683))

What if we check for `apt-get` command existence, and in case the command exists, make a suggestion to the user:

```
Unfortunately your distribution isn't officialy supported, but there's some light at the end of the tunnel. You're using the APT package manager, so, perhaps the Debian or Ubuntu repositories could work for you. Which of them do you want to try?
[x] ubuntu:trusty
[ ] debian:jessie
[ ] ubuntu:... (1 or 2 older versions)
[ ] debian:... (1 or 2 older versions)
[ ] Cancel
```

What do you think?

/cc @jfrazelle @thaJeztah @gospo @boite

**Comment by tianon** [comment]
Wouldn't it be safer to point folks to the installation documentation
instead?

**Comment by fmoliveira** [comment]
You're right @tianon , of course it's the safest thing to do. The script already point folks to the install docs.

But in the same message, it encourages users to submit pull requests to add their distros. There're dozens of Ubuntu derivatives distros out there, thus, Docker often receives new PRs with hard coded distro names.

How are we supposed to handle pull requests with hard coded distro names? Would these pull requests just get merged anyway? Or should we instruct users to talk with their distro's developer to make the upstream release detectable?

I've commented [here](https://github.com/docker/docker/pull/15743) about how some distros have done that.

**Comment by boite** [comment]
The ideal would be for the distro to support the detection of upstream. I suggest that it would be most helpful to permit hard coded distro names until support is available.

**Comment by fmoliveira** [comment]
So, what if we create a new file to put all the hard coded distros, and use it as a fallback to the `lsb_release -a -u`?

For example:

New file **docker/hack/upstream-distros**:
```
trisquel:belenos=ubuntu:trusty
linuxmint:petra=ubuntu:saucy
```

What's different from hard coding directly in the install.sh file? Instead of bloating the installation script, we'd create a file with the specific purpose of serving as a hard coded distros database. It would avoid polluting the install.sh file, making it harder to maintain, and last but no least, avoid modifying the script too often, making it easier to review and merge pull requests.

So, we just have to add a few lines to install.sh to read data from that file.

What do you think @tianon @jfrazelle @thaJeztah ?

**Comment by gospo** [comment]
@fmoliveira I shudder at the notion of a table that takes maintenance, but hopefully this isn't something that will live-on for too long, so I say go for it.  The data should not be in another file, though, if one wants to perform the curl-piped-to-sh-type installation, right?

**Comment by boite** [comment]
What about if install.sh tries to read upstream-distros and if it can't (because curl-piped-to-sh) then it can exit with the usual "can't detect" message + "please download upstream-distros and execute install.sh again". This way, the install script isn't bloated, the user knows that their distro can't be detected, but they can still install without much difficulty. A message to the effect that "please talk to your distro dev about providing upstream detection" could be shown if the distro is in upstream-distros and "please hack upstream-distros" if it isn't.

**Comment by gospo** [comment]
@boite I had a similar thought. The workflow could be as you mentioned that users are instructed to download install.sh and to facilitate installation on these 'clones' a new command line flag that was something like '--dist=debian:wheezy' where the colon-separated options are always interpreted as $lsb_dist:$dist_version.  The part I don't like about this is that install.sh is simple, with no args currently and I could imagine that some would not want to add a new flag to the command.

**Comment by gospo** [comment]
Maybe something like this:

https://github.com/gospo/docker/commit/836f82d941c414f1eef0351b82920bf014456274

**Comment by fmoliveira** [comment]
@gospo @boite 
If we're trying to make the users lives easier, we could still curl one more time to get more info, if needed. So we could curl this public table. :)

Take a look at [this proposal](https://github.com/fmoliveira/lsb-release-upstream).

The solution proposed in that repository will try to download a file which corresponds to user's distribution, and it will contain ID and version from the upstream release.

Anytime you need to add a new distribution to the database, you'd submit a pull request creating a new file to the `upstream` folder.

If this idea is appreciated, I'm fine to transfer ownership of this repository to @docker so we can have a "more trusted" database for letting an organisation with good reputation take control of it.

Of course, to avoid curling more than necessary, we'd execute this solution just in case the distribution couldn't be identified.

**Comment by jfrazelle** [comment]
what about in the echo output a note that says if you know what your distro is equivalent to you can add the apt-repo re: [sources.list linnes about the distro] then we do not have to maintain anything wrt a table mapping and if the distro wants to be known hopefully they can conform to the parsing we are already using :/
or is this too much work for the user at that point
im just unsure where the line is between us holding hands and people being able to do things themselves without the cost of us needing to review a bunch of PRs for every deb based distro under the sun

**Comment by fmoliveira** [comment]
@jfrazelle Yep, you're completely right about "when does this end". :+1: More pull requests will come, and this discussion should define how we'll handle them.

I think it's good that all deb based distros users be able to use the install script even if the distro isn't easily detectable, because it installs more than the `docker-engine` package, it setups extra kernel modules and apparmor, which are required for Docker to work. This would avoid new issues complaining Docker won't start because the required dependencies weren't installed properly, which would often happen if we tell the users to `apt-get install` manually.

The cheapest working solutions seems to reduce the suggestion from the [first comment](https://github.com/docker/docker/issues/15765#issue-102496944).

**Suggested workflow:**
* After detecting the user's distro isn't easily detectable, check if the `apt-get` command exists;
* Tell the user its distro isn't easily detectable but there's a chance for him to manually input the distribution ID and version codename for the apt repositories, the user may choose to proceed or quit the script;
* After manually inputting these info, the script will add the apt repository and follow the script usual flow, so, the extra kernel modules and apparmor will be properly setup.

**Comment by fmoliveira** [comment]
@jfrazelle Yep, you're completely right about "when does this end". :+1: More pull requests will come, and this discussion should define how we'll handle them.

But if we tell the users to add the apt-repo manually, the script still wouldn't detect the user have done that. If may be a little bit harder than just telling the user to do `apt-get install docker-engine`, because the script does more than that. It setups extra kernel modules and apparmor, which are required for Docker to work.

That's why I think it's good that all deb based distros users be able to use the install script even if the distro isn't easily detectable. This would avoid new issues complaining Docker won't start because the required dependencies weren't installed properly, which would often happen if we tell the users to `apt-get install` manually.

The cheapest working solutions seems to reduce the suggestion from the [first comment](https://github.com/docker/docker/issues/15765#issue-102496944).

**Suggested workflow:**
* After detecting the user's distro isn't easily detectable, check if the `apt-get` command exists;
* Tell the user its distro isn't easily detectable but there's a chance for him to manually input the distribution ID and version codename for the apt repositories, the user may choose to proceed or quit the script;
* After manually inputting these info, the script will add the apt repository and follow the script usual flow, so, the extra kernel modules and apparmor will be properly setup.

**Comment by jfrazelle** [comment]
Ok let me thinnk on it and I will let you know soon but yeah I think the
benefits of getting deb users to install aufs etc are worth adding them

**Comment by thaJeztah** [comment]
So here's my thoughts on this (apologies for derailing this proposal, but I think it's good to have a proper discussion on this topic);

The reason we have https://get.docker.com is to get users up and running in "no" time, so that they can play around with Docker. Let's call it "express install".

For Linux, this is https://get.docker.com, for Windows and Mac users, we have Docker Toolbox, which (to me) falls in the same category; get users started quickly.

The "express install" is *not* suitable for production; we make many assumptions, and some settings we use are just to "get it working", but really require manual configuration to be really useful (for example, the default devicemapper configuration)

I think that *even if we successfully detect the system*, we should point users to an "advanced install" section in the documentation, also *warn* users that the "express install" should be reviewed before using in production.

The advanced install section in the documentation, should cover (or link to);

- Checking prerequisites (e.g., using `/contrib/check-config.sh`)
- Pinning to a specific version of Docker
- Picking, setting up, and configuring a graph driver (e.g. Setting up aufs)
- Configuring daemon options (SysVinit, SystemD)
- Picking, and configuring a default logging-driver
- Networking options and related (e.g. Userland Proxy)

Yes; we should make it as easy as possible for people to get to "play" with Docker, but evenly (if not more) important, we should explain that Docker uses advanced techniques; making optimum use of Docker *does* require careful planning and configuration, and making informed decisions (e.g. The best graph driver for your situation).

**Comment by fmoliveira** [comment]
Fine @jfrazelle ! Whatever you think of, please let me know, I'm here ready to help on improving the script. ;)

---

Thanks a million for your thoughts @thaJeztah , I'm still a beginner Docker user and didn't know one could need so much advanced setup for tuning a production environment. That's very valuable info!

I've seen the docs in the website have got some tips for a more custom setup, but I was unable to find information about more advanced setups for use in production with the steps you've mentioned. It should be worthy mentioning these steps in the website as well, if they aren't yet. Perhaps as a new page "Tunning Setup for Production".

I would love to help with these pages, but unfortunately I don't have enough knowledge of Docker to produce these docs yet. We might create a WIP branch for these pages so we can join forces for this task.

Anyway, I've understood the idea of [get.docker.com](https://get.docker.com) to be an easy install, and I like it. This script has indeed helped a lot to get started with Docker in my Linux environment, as well as Boot2Docker has helped me a lot in Windows.

So, do you agree with my thoughts from [this comment](https://github.com/docker/docker/issues/15765#issuecomment-134345996)?

**Comment by jfrazelle** [comment]
I guess we should move forward with the mapping idk, @tianon?

**Comment by moxiegirl** [comment]
@thaJeztah I'm leery about adding "regular versus advanced install" --- our installation is pretty simple. Getting a production instance ready takes thought. How about open a PR for "Setting up a production instance with Docker" --- so we can reduce the discussion on this thread.

**Comment by fmoliveira** [comment]
@moxiegirl I agree about not adding advanced stuff to the current install, I think the idea above was only to add a reference link to let the user know that advanced configuration is needed for a production environment, and not to grow the current installer. The easy install is just perfect for everyone getting started to Docker and I agree it should remain like this. I also agree that the discussion of new advanced docs pages should be discussed in another thread.

**Comment by thaJeztah** [comment]
@moxiegirl @fmoliveira created issue https://github.com/docker/docker/issues/15946 for "advanced" install.


WRT the installer; Assisting users with getting Docker installed (if we're unable to detect) is a good goal, I'm just a bit worried if the end-result will be a properly configured installation, or a (partially) broken one.

For example, will `aufs` be installed properly, or will we (silently) fall back to `devicemapper`; does the distro have uDev sync support? We don't test all these distros, so we won't know what the end result will be.

If we're fairly certain the end-result will be a "proper" install, I'm good with adding the interactive part (probably with some warnings added), otherwise, a link to the installation docs would have my preference (instructing people how to manually perform the tasks that the installer does)

**Comment by gdm85** [comment]
Totally on topic: #9745

**Comment by LK4D4** [comment]
@thaJeztah psst

**Comment by thaJeztah** [comment]
Closing this because the installation script now lives in a separate repository; https://github.com/docker/docker-install
