### ISSUE TITLE
target chain DOCKER always inserted instead of appended

### ISSUE THREAD

**Issue by dkiser** [moby/moby#15890]
Is there a particular reason the `-A FORWARD -o docker0 -j DOCKER` line is always inserted instead of appended to the filter table FORWARD chain? If we append to the FORWARD chain in the filter table, then folks would be able to do some more customization as the below paragraph states.

I would like to be able to have a rule of mine always exist in order to handle situations where a container is bound to a local loopback IP that is reached via an IPIP tunnel.  In essence, trying to ACL based off of client IP to "vip" which is a local loopback on a host machine reached via an IPIP tunnel.  I have successfully proved out granular ACL control this way using iptables when marking passed connections in the mangle table PREROUTING and filtering on this mark in the filter table FORWARD chain (when I'm able to insert my rules in the FORWARD chain first).  When Docker restarts, it always inserts itself as the first rule in the FORWARD chain (to target the DOCKER chain) and my granular rules no longer apply, resulting in no ACL's for this particular forward flow.   

docker version: 

```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:19:43 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:19:43 UTC 2015
 OS/Arch:      linux/amd64
```

docker info:

```
Containers: 45
Images: 110
Storage Driver: devicemapper
 Pool Name: docker-253:0-52561363-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.435 GB
 Data Space Total: 107.4 GB
 Data Space Available: 105.9 GB
 Metadata Space Used: 5.976 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.7.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 24
Total Memory: 62.86 GiB
```

uname -a:

```
Linux SCRUBBED 3.10.0-229.7.2.el7.x86_64 #1 SMP Tue Jun 23 22:06:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by gdm85** [comment]
See also #7003; in [this tool I wrote](https://github.com/gdm85/docker-fw) I always remove that rule on startup (and have a dedicated ``init`` command for that), it doesn't bother me more than that as I consider it an established Docker default

**Comment by vpal** [comment]
Yes this is something that I already faced when I first tried to set up something with Docker in production.
@gdm85 I don't believe that this should be solved by external tools especially not ones that are not part of the Docker package.
It is not just the jump rule but all the other rules are unfortunately perpended instead of being appended by Docker.
Anyway this behavior can create serious security issues by for example allowing traffic outside of the host by inserting those rules and perpending other rules that are there to prevent that.

**Comment by vpal** [comment]
You can get around this actually by manually adding the rules docker would add after your rules and this way it seams docker leaves the FORWARD table untouched, but I don't think this is the right way.

**Comment by mavenugo** [comment]
@dkiser @vpal @thaJeztah as we all know managing iptables and sharing them across applications isn't easy : 
![iptables](https://cloud.githubusercontent.com/assets/5056191/13287439/f6906162-dabb-11e5-8759-c428b86ea763.gif)

The reason we use the -I is to make sure the rules managed by docker are ordered appropriately.
But if am not wrong we do it only in the chains managed by docker such as DOCKER, DOCKER-ISOLATION, etc.

We can avoid this in FORWARD chain. but we have to be very careful. cc @aboch

**Comment by vpal** [comment]
@mavenugo the insertions in the DOCKER chain are okay.
If you create the chain and a rule in it manually docker appends the rules after the manually created rule, which is I think right.
The problem is with the FORWARD chain in the filter table where the rules (see below) are inserted at the beginning of the chain:
```
Chain FORWARD (policy DROP 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination         
1       44 17675 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           
2       40 17459 ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
3       54  4769 ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0           
4        0     0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0           
```

If there are existing rules that do filtering those are not applied for traffic that comes from the docker interface because of these rules inserted at the beginning.

Maybe it would be enough to clarify in the documentation that if you create these rules (the four above rules and DOCKER chain) manually docker will not touch the FORWARD table.
Explicitly naming those rules and the described behavior would give some more confidence in this workaround and could maybe make sure that this will not break by docker inserting additional rules besides the listed four in future releases.
This would also make sure that current compatibility is not broken.

**Comment by gdm85** [comment]
@vpal I am with you on that, [docker-fw](https://github.com/gdm85/docker-fw) was created to provide some missing feature - possibly waiting for official support and at the same time showcasing a way to achieve this.

**Comment by aboch** [comment]
@dkiser @vpal @gdm85 

FYI I have a PR open https://github.com/docker/libnetwork/pull/875 which reorganizes the docker rules. Mostly moving them away from the FORWARD chain. 
In the FORWARD chain it only leaves independent jump rules (one for each bridge) which order does not matter, so we could change them to append now.

Being a delicate change, it would be great if you could take a look, give it a try and provide comments.

Thanks!

**Comment by gdm85** [comment]
@aboch as I commented there, LGTM. It would break [docker-fw](https://github.com/gdm85/docker-fw) but gladly so a better feature can be used.

**Comment by dkiser** [comment]
@vpal @gdm85 @aboch

So in the PR setup the normal INPUT chain rules in a pre-docker world would now land in in the DOCKER-EXPOSED chain correct.  Looking at the code the input interface is now the bridge instead of the output interface so in theory it doesn't shunt the initial forwarding decision.  

To confirm, if the DOCKER-EXPOSED chain is created in the filter table by the user (before docker startup) OR if custom rules are inserted during docker runtime) these will persist through docker restarts?  The use case would be "expose" acls for services are persisted. For now these would be managed by config mgmt or orchestration for example, but I could see a more native integration in the future where the expose acls travel with container runtime definitions as the containers move about cluster nodes. E.g. host expose compose, Rancher, Kube? Etc definitions tightly couple the exposed acl definitions.  Maybe a new docker firewall plugin?  I know there are vendor products now trying to manage host firewalls as well. 


@mavenugo nice Peter pic 8-)

**Comment by olafbuitelaar** [comment]
<details>

Client:
 Version:       18.02.0-ce
 API version:   1.36
 Go version:    go1.9.3
 Git commit:    fc4de44
 Built: Wed Feb  7 21:14:12 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.02.0-ce
  API version:  1.36 (minimum version 1.12)
  Go version:   go1.9.3
  Git commit:   fc4de44
  Built:        Wed Feb  7 21:17:42 2018
  OS/Arch:      linux/amd64
  Experimental: false
</details>
It appears dockers adds an second DOCKER chain in the PREROUTING table after a restart. 
Steps to reproduce; 
//Delete the standard DOCKER jump rule 
iptables -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
//Insert an modified DOCKER jump rule. In this case ext0 refers to my internet facing interface, since i don't want any internet traffic to enter docker, modify this rule.
iptables -t nat -A PREROUTING ! -i ext0 -m addrtype --dst-type LOCAL -j DOCKER
//restart docker
service docker restart

After that i've 2 DOCKER jumps in the PREROUTING TABLE:
Chain PREROUTING (policy ACCEPT 4954 packets, 299K bytes)
 pkts bytes target     prot opt in     out     source               destination
1562K   94M DOCKER-INGRESS  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
 496K   30M DOCKER     all  --  !ext0  *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
 1589 95180 DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

I would expect since the jump target for docker already exists, it would use that one instead. But apparently the interface filter causes the daemon to see this rule as not existing, and creates a new one.

**Comment by cpuguy83** [comment]
We cannot change this as it will cause breakage for existing users.
Instead we have opted to add a `DOCKER-USER` chain where you can add your own jump rules.

I'm going to close this since it is effectively solved by the `DOCKER-USER` chain, even if it's not perfectly ideal for everyone... but feel free to discuss.
Thanks all 🙇 👼
