### ISSUE TITLE
Image Graph operations are racey

### ISSUE THREAD

**Issue by cpuguy83** [moby/moby#16982]
After reviewing the code in `graph/`, it is incredibly apparent that graph operations are racey, especially delete (which is dangerous).

Note that when someone calls `docker rmi` a bunch of calls are made from the daemon to check if the image is removable, which in some cases locks/unlocks the image in the graph, and in other cases is just checking daemon side things (like containers using an image)... and then ends up calling `graph.Delete()`, which is not locking at all.

The locking/unlocking alone is racey enough, but also calling, from the daemon, `graph.Delete()` with no lock is troublesome... note that simply locking here will not fix the issue.

Note this report confirmed by multiple users: https://github.com/docker/docker/issues/928#issuecomment-146929432

Note there is also a huge todo in `daemon/image_delete.go` to move most of the work to `graph/`.
I think we can use the `retainedLayers` struct in `graph/graph.go` to handle container refs for started containers which will help with the move (so, on container start retain the layer, on stop un-retain it).

**Comment by vielmetti** [comment]
+1 for taking this up.

If you go back and read #928 you see the result of this defect. The more you use Docker, the bigger a collection of artifacts that you might want to `docker rm` or `docker rmi`, and the more likelihood that some part of this problem will trouble you.

The feature request from #928 is to implement `docker clean`, but that's not possible until this underlying issue is well addressed.

**Comment by dmcgowan** [comment]
Considering the `graph/` directory has been completely removed and the code rewritten for content addressibility, this issue should either be closed or re-evaluated from the latest code, preferably with specific examples of races.

**Comment by stevvooe** [comment]
I agree with @dmcgowan but I also agree with the sentiment of this bug. I am not sure it is actionable, as written.

Without having a serializable lock (aka lock-the-world-yo), I am not sure there is a solid way to realize this fix without adding a full ACID compliant data store. To accomplish this, we'd need to unify how docker accesses metadata. This might be the answer to the highlighted issues.

**Comment by cpuguy83** [comment]
I think the majority of the issue here comes directly out https://github.com/docker/docker/blob/master/daemon/image_delete.go where we check in the daemon if something is deletable and then go and delete the iamge, but in between someone can do things like tag the image, start a container with the image, etc.

The other part of it is the only way to delete a list of images is 1 by 1, where even if we had some lock in place, it would lock/unlock for each image.

**Comment by stevvooe** [comment]
@cpuguy83 Do you have a reproduction on this? This can't really be done correctly without a full lock on the reference store (this the low bar for a correct GC implementation). This might be a bug.

@tonistiigi @aaronlehmann Any thoughts here?

**Comment by cpuguy83** [comment]
@stevvooe https://github.com/docker/docker/issues/928#issuecomment-146929432 is a good example.

**Comment by tonistiigi** [comment]
I don't think there is much we could do in the imagestore level or if something like `imagestore.Lock(id)` would help here. 

Reference store and image store don't know about each other. You can make a reference to an ID that doesn't exist. Similarly you can delete image even if it is a parent of another image and safely delete an image if there is a container using it. All of these restrictions are daemon specific so seems the protection should be in there as well.

**Comment by stevvooe** [comment]
@cpuguy83 Part of my point is that later on in the thread, they continue on about this:

> Not only is it hugely complicated, there have been multiple bugs which cause it to delete in-use volumes out from running containers: chadoe/docker-cleanup-volumes#19

While it is easy to blame this on docker, it is reflective of the problem itself. To conduct accurate GC, you need a consistent view of the world. 

@tonistiigi 

> I don't think there is much we could do in the imagestore level or if something like imagestore.Lock(id) would help here.

@tonistiigi I agree that this would not work and, in fact, this model contributes to some of the race conditions present in Docker GC. The reason being here that roots can exist in either of the reference or image store.

The right approach is to lock all stores, resolve all "roots", walk for reachability, issue deletes then unlock all stores. The other approach is to have a versioned store. Pick a snapshot version, walk from roots, lock all stores, walk from modifications from snapshot to head, issue deletes, then unlock all stores. This is similar to [Go's new garbage collector](https://docs.google.com/document/d/16Y4IsnNRCN43Mx0NZc5YXZLovrHvvLhK_h0KN8woTO4/edit). The key here is capturing the differences between the heap walk and the changes issued during that walk.

If you would like to see more of my ramblings on GC, checkout the [Registry ROADMAP](https://github.com/docker/distribution/blob/master/ROADMAP.md#deletes). Most of that is related to the registry storage drivers, but the problem is identical and the constraints are the same.

**Comment by LK4D4** [comment]
@cpuguy83 is this still issue?

**Comment by cpuguy83** [comment]
Yes, I think this is still an issue.
There is not a good correlation of refs to images from outside the image store (e.g., containers).

**Comment by AkihiroSuda** [comment]
still issue?

**Comment by cpuguy83** [comment]
Yes, no changes here other than "some day we will be on containerd".

**Comment by cpuguy83** [comment]
Actually I think this is much less a problem today than it used to be just because of the way the layer store works.
Let's close this.
