### ISSUE TITLE
Support wildcards for commands which take multiple containers/images (rm/rmi/...)

### ISSUE THREAD

**Issue by tmds** [moby/moby#17237]
These commands support specifying multiple containers/images. It would be handy if they accepted a wildcard pattern.
e.g.:

```
docker stop *
docker rm *
docker rmi *
```

**Comment by cpuguy83** [comment]
This won't work because the shell will receive the `*` and expand it before docker cli does.

**Comment by thaJeztah** [comment]
Unfortunately, @cpuguy83 is right here, so I don't think we'll be able to implement this, something like below will work probably do the job, and you can create an alias for that in your shell;

```bash
# stop all running containers
docker stop $(docker ps -q)

# remove all containers
docker rm $(docker ps -aq)

# remove all image
docker rmi $(docker images -q)
```

**Comment by tmds** [comment]
Most shells will have a way of providing arguments to a program without expansion. And some shells don't do expansion.
e.g.
```
docker stop '*'
docker rm '*'
docker rmi '*'
```
\* is used as an example, it could contain a more specific pattern
e.g.
```
docker stop `webserver*`
```

**Comment by huikang** [comment]
Is there any play to support this feature? - Hui

**Comment by thaJeztah** [comment]
No, this is not something that is currently being worked on

**Comment by OlivierCuyp** [comment]
For now the only solution is then something like this:

```bash
docker rmi $(docker images | grep test | awk "{print \$3}")
```

**Comment by montanaflynn** [comment]
You can also use piping into [`xargs`](http://linux.die.net/man/1/xargs) which is helpful to do things like this:

```
# Stats for all running containers
docker ps -q | xargs docker stats

# Remove all stopped containers
'docker ps -a -q | xargs docker rm
```

**Comment by thaJeztah** [comment]
To get stats for all running containers in docker 1.10 and above, simply run `docker stats` (see https://github.com/docker/docker/pull/16742)

**Comment by kujiy** [comment]
Remove all containers by container_name.

```
docker ps -a | grep <CONTAINER_NAME> | awk '{print $1}'  | xargs docker rm
```

**Comment by jgroom33** [comment]
docker images | grep <IMAGE_NAME> | awk '{print $1}' | xargs docker rmi

**Comment by thaJeztah** [comment]
@jgroom33 @kujiy you can also use the built-in filter options for that; for example


    docker rm $(docker ps --filter name=foobar)

**Comment by CanRau** [comment]
just to clarify for some curious people.. --filter accepts wildcards so
```
docker rm -f $(docker ps -aq --filter name=foo*)
```
does a great job..could be made into a custom function in your .bashrc, .zshrc etc..

**Comment by cpuguy83** [comment]
@CanRau I don't think that wildcard is doing what you think it is.
That is still expanded by the shell and not docker.

**Comment by CanRau** [comment]
hm interesting..at least for me it worked and using it with `name=docker*` it deleted 4 containers starting with docker_ and one with dockerized, maybe zsh expanded intelligently?

**Comment by mpitt** [comment]
@CanRau @cpuguy83 generally, the shell will expand _if it finds at least one match_, so `foo*` might work or not based on the contents of the current working directory

**Comment by CanRau** [comment]
@mpitt ah okay, good to know, thanks for clarification 👍

**Comment by tmds** [comment]
I :heart: podman's `-a` flag on `rmi` https://github.com/containers/libpod/blob/master/docs/podman-rmi.1.md
To remove all containers and images I can simply:
```
podman rmi -fa
```

**Comment by thaJeztah** [comment]
`docker system prune -a` (or `docker container/image/volume prune`) provide that

**Comment by OlivierCuyp** [comment]
@thaJeztah I experienced system hanging with `docker system prune -a` ...

**Comment by thaJeztah** [comment]
It may take a while to run if there's a large amount of things to clean, and doesn't report progress until things have been actually removed (which is something that should be improved)

**Comment by tmds** [comment]
@thaJeztah feel free to close this.

**Comment by thaJeztah** [comment]
Yes, let's close, because using wildcards won't work (if the shell expands them https://github.com/moby/moby/issues/17237#issuecomment-150065745), and there's quite some alternatives mentioned in comments above.

**Comment by koenlek** [comment]
I'm surprised this gets closed. I often find myself in the need to cleanup images/containers/volumes/etc. The `prune` subcommand is somewhat dangerous as people often don't understand the pruning conditions well, so  irreversible overpruning is a serious risk, definitely still with `--dry-run` not being implemented (#30623).

My use case: I have all kinds of images, often with a bunch over versions of images as different tags. Let's say I want to do some cleanup and I know I can get rid of all my ros images because I don't use them anymore. I would like to `docker rmi osrf/ros:*`. As far as I know, there is no way for this in the "quite some alternatives mentioned in comments above.", right?

Then about the wildcards the following arguments is brought up:

> because using wildcards won't work (if the shell expands them #17237 (comment))

There is a very common solution for this. If you want a wildcard to expand on the shell side (against files in current working directory), you leave it unquoted, if you want to expand it on the command side, you add quotes. I find myself doing the latter very often. A common example in my daily workflow:

```sh
find . -name "*.sh" # finds all files ending in .sh recursively from current directory
find . -name *.sh # if current directory contains a .sh (e.g. script.sh) file, the wildcard expands against that and find wil operate on that as the -name argument (e.g. find . -name script.sh). if it doesn't contain a .sh file, it ends up doing the same as the first command.
# hence: best practice with find: always protect wildcards with quotes!
```

There are many commands in which I *always* protect the wildcards with quotes, to avoid unintended expansion against files in current working directory.

Please reconsider implementing wildcards for matching image/container/volume/etc names, or help me find a good alternative that covers my example `docker rmi osrf/ros:*` workflow. Thanks!

**Comment by thaJeztah** [comment]
I think the `reference` filter should allow you to match `osrf/ros:*`; does this work to list those?

```bash
docker image ls --filter reference=osrf/ros
```

**Comment by koenlek** [comment]
Great! That works well. For anyone else interested: to remove all images starting with e.g. osrf/ros:kinetic, I can run:

```sh
docker rmi $(docker image ls --filter reference="osrf/ros:kinetic*" -q)
```

**Comment by ssbarnea** [comment]
I still hope to see this implemented natively so we do not have to rely on subshells.

**Comment by cpuguy83** [comment]
@ssbarnea 

1. As you typed it, this would never work since `*` is expanded by the shell which reinforces the point.
2. You can pipe to `docker rm` if you use `xargs`.. but why is this form better than a sub-shell?
3. You can use `docker container prune` with a filter to get this. Is name supported? I'm not sure off the top of my head.
