### ISSUE TITLE
docs: describe how to install specific versions of docker (yum/dnf/apt)

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#17935]
Being able to install a specific version of docker is a recurring question (see for example https://github.com/docker/docker/issues/9697, https://github.com/docker/docker/issues/13191, https://github.com/docker/docker/issues/13822, https://github.com/docker/docker/issues/15581, https://github.com/docker/docker/issues/15586, https://github.com/docker/docker/issues/15947)

We currently describe how to download a specific (static) binary on http://docs.docker.com/engine/installation/binaries/, but don't provide that information on how to do this using apt, yum, or dnf.

While this may be "general knowledge" on working with package managers, it would be a nice addition to explain users how to do this (and how to "pin" to a specific major/minor version)

for example, on ubuntu

``` bash
apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
mkdir -p /etc/apt/sources.list.d
echo deb https://apt.dockerproject.org/repo3 ubuntu-trusty main > /etc/apt/sources.list.d/docker.list
apt-get update;
apt-get install -y -q docker-engine=1.x.x~
```

**Comment by HackToday** [comment]
@thaJeztah  from http://docs.docker.com/engine/installation/fedora/

it seems have related how to configure repos, so for users he just know run 
sudo yum install docker-** specific version is ok. it seems not need extra docs for that.

What do you think the above link information ? take feodora for example

**Comment by thaJeztah** [comment]
@HackToday the extra docs could simply be an extra section / heading on that page explaining how to install a specific version (and an example). We get questions about how to install specific versions, so I think it'd make sense.

@moxiegirl any thoughts on this?

**Comment by moxiegirl** [comment]
@thaJeztah I agree having article about installing a specific version might be smart.  I don't know if we need to add it to each installation doc.  It might make more sense to have a single article that covers the how to for the different types of installation.

**Comment by bgaillard** [comment]
Hi, this is also very important for us mostly because we use Docker In Docker in our CI servers (http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci). 

In our case our Jenkins CI server is installed inside a Docker container, then it run builds inside other Docker containers...

Sometime we rebuild our Jenkins Docker container (to upgrade Jenkins) and encounter the error  `client is newer than server (client API version: 1.20, server API version: 1.19)` often.

Because we use an Amazon EC2 machine we have the `yum` package manager but I did not found any indications to install a specific Docker version with `yum`. 

So to install a specific version of Docker on our Amazon EC2 machine we manually download the Docker binaries (don't know if its the right way to do this, anyway **perhaps this procedure could be useful for the article / guide** ...).

```
# First stop all running containers and remove them
cd /home/ec2-user 
docker stop $(docker ps -a -q) 
docker rm $(docker ps -a -q) 
sudo service docker stop 

# Gets the Docker version we want
wget https://get.docker.com/builds/Linux/x86_64/1.8.2 

# Rename the currently Docker executable (would be useful if strange errors are encountered)
mv /usr/bin/docker /user/bin/docker-old 

# Install new version
mv docker-1.8.2 /usr/bin 
mv /usr/bin/docker-1.8.2 /usr/bin/docker 
chmod +x /usr/bin/docker 

# Then restart your Docker containers (in our case we use Docker Composer)
docker-compose up -d
```

**Comment by moxiegirl** [comment]
@bgaillard The client version mismatch is pretty common. It sounds more like your use case is downgrading an existing version rather than simply installing a a specific version.  The use case would serve as a good "why would you use an older version of Docker" guidance in an article on installing a specific version.

**Comment by bgaillard** [comment]
@moxiegirl 

> It sounds more like your use case is downgrading an existing version rather than simply installing a a specific version.

Yes, in fact in our case it was the opposite :-), upgrading the Docker version on our host Amazon EC2 machine because it seems yum packages on Amazon EC2 are not totally up to date (and we did'nt wanted to downgrade packages in our Jenkins container).

> "why would you use an older version of Docker" 

Agree, it appears that installing a specific Docker version respond to several needs.

**Comment by LK4D4** [comment]
@thaJeztah Was this fixed?

**Comment by jcmcken** [comment]
Any update on this?

Is it difficult to simply keep the old artifacts available for download somewhere, and make it simple to retrieve in a stable fashion? Many products which build on Docker require specific versions (e.g. Kubernetes, Rancher)

**Comment by thaJeztah** [comment]
This issue was addressed in the documentation. For example, from the installation docs for Ubuntu; https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-docker-ce-1


>    On production systems, you should install a specific version of Docker CE
>    instead of always using the latest. This output is truncated. List the
>    available versions.
>
>    ```bash
>    $ apt-cache madison docker-ce
>
>    docker-ce | 17.09.0~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages
>    ```
>
>    The contents of the list depend upon which repositories are enabled. Choose
>    a specific version to install. The second column is the version string. The
>    third column is the repository name, which indicates which repository the
>    package is from and by extension its stability level. To install a specific
>    version, append the version string to the package name and separate them by
>    an equals sign (`=`):
>
>    ```bash
>    $ sudo apt-get install docker-ce=<VERSION>
>    ```
>
>    The Docker daemon starts automatically.
