### ISSUE TITLE
`docker-compose` on Windows Server 2016 [TP4] requires `net: default` or `net: none`

### ISSUE THREAD

**Issue by powersplay** [moby/moby#18099]
docker-compose up gives ERROR: invalid --net and aborts on Windows Server 2016 Technical Preview 4 Build 10575 unless net: default or net: none is specified in docker-compose.yml

PS C:\Users\Administrator\compose> ..\docker-compose-Windows-x86_64.exe up -d
Recreating 7780fb51c7_7780fb51c7_7780fb51c7_7780fb51c7_compose_Wocker_1
ERROR: invalid --net:
Inserting net: default or net: none in docker-compose.yml is required to avoid this error.

Seems to come from engine:  https://github.com/docker/docker/blob/d4c4557b1af794c4d7e4a9833b20119c0a4c091c/runconfig/hostconfig_windows.go#L67

@dnephin

**Comment by thaJeztah** [comment]
Are you able to reproduce this with just docker, or only when used with docker-compose?

**Comment by powersplay** [comment]
`docker run` behaves normally and does not require --net.   I've just confirmed this again with this version (below).

PS C:\Users\Administrator\compose> docker-compose version
docker-compose version: 1.5.0rc1
docker-py version: 1.5.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1j 15 Oct 2014

PS C:\Users\Administrator\compose> docker-compose up
Creating compose_iis_1
invalid --net:
PS C:\Users\Administrator\compose> docker version
Client:

 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   54733ab
 Built:        Mon Nov 30 19:27:57 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   54733ab
 Built:        Mon Nov 30 19:27:57 UTC 2015
 OS/Arch:      windows/amd64

**Comment by thaJeztah** [comment]
perhaps docker-py 1.6 resolves this, it was just tagged but no release notes yet; https://github.com/docker/docker-py/releases/tag/1.6.0

**Comment by dnephin** [comment]
@thaJeztah I think there are potentially a few problems here:

1. the error message is incorrect for anyone using the API. The API really shouldn't have any knowledge of, or make assumptions about, cli params. It should return a json response with the fields that are incorrect, missing or conflicting, and the client should format an appropriate error
2. From https://github.com/docker/compose/issues/2375 it sounds like the docker cli sets a default net. If `net` is now a required parameter, I think the error should indicate that. Although I don't think it used to be a required parameter, and probably doesn't need to be (since it defaults to `bridge` by the client).
3. This isn't an issue with the linux engine, so is probably an inconsistency with the windows engine.

**Comment by thaJeztah** [comment]
Thanks @dnephin, I saw you commented on 1. in the PR that created that, w.r.t. 2. I agree that ideally, defaults should be set server-side; overall we don't require people to send properties that have a default.

**Comment by StefanScherer** [comment]
Still the same with current docker-compose on a TP4.

```
C:\> docker-compose version
docker-compose version 1.6.0, build cdb920a
docker-py version: 1.7.0
CPython version: 2.7.11
OpenSSL version: OpenSSL 1.0.2d 9 Jul 2015
```

**Comment by jhowardmsft** [comment]
@powersplay Is this still an issue? It sounds (only half read) like a docker compose issue rather than docker engine. If so, can you open an issue against docker compose instead? Thanks.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
