### ISSUE TITLE
docker COPY overwrite symlinks

### ISSUE THREAD

**Issue by thall** [moby/moby#18501]
Description of problem:
Docker COPY doesn't follow container symbolic links. Instead it overwrites them with directories which i find very counter intuitive.

`docker version`:
Docker version 1.8.3, build f4bf5c7-dirty

`docker info`:
Containers: 61
Images: 449
Storage Driver: devicemapper
 Pool Name: docker-254:0-2498838-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 13.76 GB
 Data Space Total: 107.4 GB
 Data Space Available: 20.55 GB
 Metadata Space Used: 22.81 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.125 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.102 (2015-07-07)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.2-2-ARCH
Operating System: Arch Linux
CPUs: 4
Total Memory: 15.59 GiB
Name: arch
ID: NJ2O:77O4:LUDQ:2PK7:LNXC:RHTR:QWYH:R4OD:JPDK:FKDF:PCZT:3EC4

`uname -a`:
Linux thallarch 4.1.2-2-ARCH #1 SMP PREEMPT Wed Jul 15 08:30:32 UTC 2015 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
physical

How reproducible:
Always

Steps to Reproduce:
**Dockerfile**:

```
FROM busybox
RUN ln -s /etc /data                                                                                                
RUN ls -al /data                                                                                                    
COPY files/ /                                                                                                       
RUN ls -al /data
```

**Context**:

```
$ tree files/
files/
└── data
    └── a.conf
```

Actual Results:

```
Sending build context to Docker daemon 3.584 kB
Step 0 : FROM busybox
 ---> c51f86c28340
Step 1 : RUN ln -s /etc /data
 ---> Running in c20c020d54b3
 ---> f415d6e84f06
Removing intermediate container c20c020d54b3
Step 2 : RUN ls -al /data
 ---> Running in 57a5eb1e7dd1
lrwxrwxrwx    1 root     root             4 Dec  8 15:28 /data -> /etc
 ---> 0834fda2dec1
Removing intermediate container 57a5eb1e7dd1
Step 3 : COPY files/ /
 ---> 394bcc0e94e9
Removing intermediate container 82e7b5ab6b7a
Step 4 : RUN ls -al /data
 ---> Running in 0e236575b130
total 8
drwxr-xr-x    2 root     root          4096 Dec  8 15:16 .
drwxr-xr-x   13 root     root          4096 Dec  8 15:28 ..
-rw-r--r--    1 root     root             0 Dec  7 15:21 a.conf
```

Expected Results:
That docker doesn't overwrite the symbolic link _data_ with a new directory, and instead follow it.
The expected result would be that _a.conf_ exists in _/etc/a.conf_

Additional info:

**Comment by tonistiigi** [comment]
Following symlinks in subdirectories doesn't sound like a good idea. Regular `cp` gives you a `can not overwrite non-directory with a directory` error in this case. I think we can consider producing an error also.

**Comment by thaJeztah** [comment]
agree on producing an error, sounds like the right approach here

**Comment by thall** [comment]
Can also agree on an error message should be produced.

**Comment by LK4D4** [comment]
looks like still a valid issue

**Comment by thaJeztah** [comment]
ping @duglin perhaps you have thoughts on this as well

**Comment by duglin** [comment]
I wonder if it wouldn't be better to drop down to the native `cp` command to do the copy so that we let the OS determine what to do in situations like this - after all, whatever `cp` does is probably what people would expect anyway.  Plus, then we don't need to try to duplicate its logic.

Although, one problem with this might be that, I think:
`COPY dir /tmp/`
will copy the contents of `dir` into `/tmp/` and not `dir` itself, which is just weird IMO and unexpected.  And as much as I would love to fix this 'bug', I suspect its a pretty big breaking change for people.

However, :-), what we could do is this:
- create a new `CP` command that does a `sh -c cp ...` under the covers  (wrapped in 'sh' to get wildcard support. Does this require 'sh', and 'cp' to be in the container? If so, perhaps we can use them from the host but not sure if that's possible - maybe mount then in???)
- supports `--user`, `--group`,  `--decompress`
- deprecate `COPY` and `ADD`

this would get us down to just **one** copy-like command that has the exact semantics people would expected.

Or just add a `--normal

**Comment by alokawi** [comment]
I faced this issue today -
`RUN cp file1 libs/`
`RUN cp file2 libs/`
above two commands should bring `file1` & `file2` in `libs` directory but only `file2` was present(seems like directory was overwritten)

After hours of retries, I changed it to below - 
`RUN cp file1 libs/ && cp file2 libs/`
to make it work. could be linked to this issue here?

Docker version - 
> $ docker --version
> Docker version 1.12.1, build 23cf638
> $ docker-compose --version
> docker-compose version 1.8.0, build f3628c7
