### ISSUE TITLE
(Eventually) Enable content trust by default, or allow enabling it system-wide

### ISSUE THREAD

**Issue by mtrmac** [moby/moby#19128]
As discussed in #15790, it is too easy to run Docker without content trust enabled.

https://github.com/docker/docker/issues/15790#issuecomment-134296126 suggests that this may eventually be fixed simply by flipping the default value of the `--disable-content-trust` option. If that never happens (or until it happens?), it would be useful to support a system-wide configuration option enabling content trust (forcibly, or just unless the user explicitly disables this?).

(No, this is not a new discovery, but AFAICS there is no issue open for tracking this at the moment, and this wording is more specific to what needs to happen than #15790.)

**Comment by endophage** [comment]
What is envisioned for this that isn't covered by setting `DOCKER_CONTENT_TRUST=1` in `/etc/environment` (or equivalent locations on OSX/Windows)?

**Comment by mtrmac** [comment]
That would technically work, but storing per-application configuration in such a machine-wide shared resource (one which costs memory per every process, even!) is pretty unexpected, at least on Linux. (My `/etc/environment` is currently empty, but there are hundreds of config files within `/etc`).

With something like #16654 and daemon-*only* signature verification¹, this could become moot because OSes already have a way to pass options when starting the daemon. OTOH if in-CLI signature verification remains, a config file would be more useful than `/etc/environment`—and especially to implement more policy like https://github.com/docker/notary/issues/395, a config file is pretty unavoidable.

---
¹  Note that #16654 does not actually propose daemon-*only*, dropping the in-CLI verification.

**Comment by endophage** [comment]
There seem to be a lot of ideas getting crossed here. By "system-wide" I understood you to mean "for all users".

If you meant it to mean "for all applications", I think this in not achievable. We have no meaningful control over what applications outside the docker suite name their variables and as such, I completely expect for trust to be enabled/disabled (system wide, per user, or per invocation) on a per application basis.

I also expect each application to have their own unique trust configuration, rather than trying to crowbar many applications into a single configuration file.

`/etc/environment` was just a suggestion as its a pre-existing location. A system wide docker trust configuration file would also be acceptable, but would require the more complicated work of configuration merging, or it would have to have a mutually exclusive set of configurable parameters vs a per user configuration file.

**Comment by mtrmac** [comment]
The “for all applications” aspect is #16654. This issue is primarily “for all users of the current CLI-only implementation”..

There is some overlap (and why I was confusing, I think), in that we can now introduce a system-wide config file to be used by the CLI-only clients, and later use the same config file for the in-daemon enforcement of #16654—using the same policy for both CLI and the daemon, and just adding a “daemon enforces this” boolean (or perhaps not even this boolean).

Thinking about merging and users’ ability to override configuration done by root is unavoidable—the `/etc/environment` mechanism just implicitly imposes a specific merging/overriding semantics. FWIW I am not too worried about users opting out of trust verification like this—that’s what #16654 is for (and *that* also implicitly imposes a merging/overriding semantics).

**Comment by endophage** [comment]
Ok, I thought it had been brought up somewhere but I don't see it. I think #16654 will be addressed by plans to create a notary authz plugin that can run with the daemon. 

Merging variables that have been set individually is easy. It's merging a system level config file with a user level config file that has real difficulties, the biggest on being whether absence of a parameter in the user level file means "use the system value" or "use the application defaults (i.e. unset the config)". We can work out implementation later and I guess most applications just handle it by not merging config so maybe we just do that.

**Comment by LK4D4** [comment]
ping @endophage 
any updates here?

**Comment by endophage** [comment]
No recent progress. Also I think https://github.com/docker/docker/issues/25852 is probably a blocker on enabling content trust by default.
