### ISSUE TITLE
[feature-request] docker-compose pull with constraint on swarm cluster

### ISSUE THREAD

**Issue by winggundamth** [moby/moby#19785]
From https://github.com/docker/swarm/issues/1692
I want docker-compose pull command to support pull with constraint on swarm cluster.
Swarm contributor said it's limitation of Docker Engine so I create issue here.

For example

``` bash
$ docker info
Containers: 29
Images: 56
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 3
 pre-01: pre-01:2376
  └ Status: Healthy
  └ Containers: 4
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 2.044 GiB
  └ Labels: preproduction=true, executiondriver=native-0.2, kernelversion=3.19.0-47-generic, operatingsystem=Ubuntu 14.04.3 LTS, provider=generic, storagedriver=overlay
 prd-01: prd-01:2376
  └ Status: Healthy
  └ Containers: 5
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 8.179 GiB
  └ Labels: production=true, executiondriver=native-0.2, kernelversion=3.19.0-47-generic, operatingsystem=Ubuntu 14.04.3 LTS, provider=generic, storagedriver=overlay
 prd-02: prd-02:2376
  └ Status: Healthy
  └ Containers: 4
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 8.179 GiB
  └ Labels: production=true, executiondriver=native-0.2, kernelversion=3.19.0-47-generic, operatingsystem=Ubuntu 14.04.3 LTS, provider=generic, storagedriver=overlay

$ cat docker-compose.yml
nginx:
    image: nginx
    environment:
        - "constraint:label==production=true"
```

It should pull to host by only specific constraint label

``` bash
$ docker-compose pull
Pulling nginx (nginx:latest)...
prd-01: Pulling nginx:latest... : downloaded
prd-02: Pulling nginx:latest... : downloaded
```

**Comment by thaJeztah** [comment]
IIUC, basically this would mean that constraints can be passed to `docker pull` (and implicitly, `docker run`), to tell Swarm which nodes the image should be pulled on?

**Comment by winggundamth** [comment]
@theJeztah Correct

**Comment by robsweet** [comment]
+1 on this request.  My use case:

I've got Docker hosts tagged by environment and role due to networking and security constraints.  These hosts are all in one swarm.  I don't want to waste a bunch of disk space pulling an image for Role 1 onto the host for Role 2.  Similarly, there's no reason to pull an RC image to a host labeled for the Production environment as RCs are never deployed to Production.

**Comment by ahromis** [comment]
+1 for this.  Would be nice to have more control over which nodes pull down the images.

**Comment by vaclavnemec** [comment]
+1 that would be very useful feature.

**Comment by chanwit** [comment]
Thank you @thaJeztah for pointing me to this.
`swarm` now entering production and starting to be widely adopted.

Currently `swarm's docker pull` pulls an image to the *whole* cluster.
Eagerly pulling a large amount of images onto a production cluster is a not that good experience, especially on a large cluster from Asia.

Trying to solve this, I propose changes that abuse `pull` for Swarm using `@`.
But if `docker` client can support at least `docker pull -e` similar to `docker run`, this selective image pulling feature can be easily implemented in `swarm`.

For example,

`docker pull -e constraint:region==us nginx`

will help us pull  the `nginx` image only onto Engines labelled with `region==us`.

**Comment by npcode** [comment]
+1. Sometimes one of swarm hosts can't pull images. In such case I want exclude the host.

**Comment by kyhavlov** [comment]
+1 this would be extremely helpful

**Comment by kyhavlov** [comment]
I submitted a PR to swarm here to pass constraints on pull: docker/swarm#2302. I'm not sure what, if anything, I'd need to add to docker/docker to go along with that. I'm willing to do the work and submit a PR, just not sure how to proceed.

**Comment by kyhavlov** [comment]
How does this change for 1.12? This didn't get added to docker engine yet as of rc2; is this being worked on or should I submit a PR to here/swarmkit?

**Comment by cpuguy83** [comment]
@kyhavlov 1.12's swarm mode is very different.
`docker service create` is an async action which performs all the tasks required to get the desired state to actual state. `pull` happens only on the node that the task is scheduled to.

TMK, compose does not have knowledge of a `docker service`

**Comment by kyhavlov** [comment]
@cpuguy83 I wasn't really thinking of the issue in terms of compose, just the ability to specify constraints when doing an image pull. Having to pull every image used onto every host in the swarm really sucks for big production clusters. Now that the swarm clustering is built into docker engine, it seems like we could add that feature here.

**Comment by cpuguy83** [comment]
@kyhavlov But swarm mode does not pull on every node, only where the task is scheduled.

**Comment by kyhavlov** [comment]
@cpuguy83 That's assuming you use the service feature, which is extremely new (and not necessarily how I want to manage services/containers/images). The specific case I'd use this for is with [Terraform](https://github.com/hashicorp/terraform), which just wants to manage images and containers on the hosts as resources. For that to work best, it needs to be able to limit which hosts an image is pulled to (and deleted from).

**Comment by cpuguy83** [comment]
I'm not sure that this is the correct way to go.
If there is support for some sort of constraint, then why pull at all?

Just like the docker CLI client initiates a pull when the image is not found on a node, the swarm API can handle the case.

**Comment by kyhavlov** [comment]
@cpuguy83 Can you clarify what you mean? Are you saying this functionality isn't needed at all, or just that it belongs somewhere besides docker/docker? If so, where?

**Comment by cpuguy83** [comment]
@kyhavlov Here is the current flow of the docker CLI

1. POST /containers/create -> image not found
2. POST /images/create
3. POST /containers/create

I'm saying instead of swarm sending 'image not found' to the client, which then calls pull, intercept the error and instruct the node to pull the image directly.

I would indeed expect `docker pull` to pull everywhere as you are hitting the cluster, it's not a node command. However when you create a container (or build an image) this is sent to a node and swarm knows which node, so it can instruct the node to make the pull rather than relying on the Docker CLI to initiate the pull, which happens across the cluster.

**Comment by robsweet** [comment]
You're ignoring the use case where I want to pull the image in preparation of a deployment, rather than to deploy it right now. 

Also, I would assume that the current create behavior was written that way for a reason. There are lots of potential edge cases to changing that behavior. Adding constraints to pull would allow for the use cases described in this thread without changing existing behavior.

**Comment by kyhavlov** [comment]
That's kind of what I was getting at, @robsweet; it's clunky in some cases (like with Terraform) to only be able to pull the image as a side effect of starting the container.

**Comment by cpuguy83** [comment]
@robsweet The create behavior is that way because it helps make things simple. Letting swarm handle the error case instead of the client is quite similar (Swarm being the client of the engine).

**Comment by schmunk42** [comment]
Another we issue we face with this is that we can't really do auto-redeployments with `:latest`, since we need to run `docker-compose pull` beforehand, otherwise we won't get the latest image.

> Just like the docker CLI client initiates a pull when the image is not found on a node, the swarm daemon can handle the case rather than ending back to the client.

@cpuguy83 I tried this with docker-compose, see [gist](https://gist.github.com/schmunk42/578134fbb5762e68330d2a6950b1998b), but `docker-compose` does not work the way you described. It always calls `docker pull` whether you run `up` or `run`.

Although, if you do a `docker run`, the image gets pulled to a node and you can run a subsequent `docker-compose up` after that, but that's kinda defeating the purpose of `docker-compose` :(

**Comment by cpuguy83** [comment]
@schmunk42 I don't see where I said compose acts one way or another.

If you need to do re-deploys with an updated image, why are you using a static image tag? This could easily be a content-addressable ID.

**Comment by schmunk42** [comment]
@cpuguy83 Right, you didn't mention docker-compose, but this issue is about docker-compose. 

And I was thinking from your comment that docker-compose would be acting like the Docker CLI, if used right. But not even with `docker-compose run` it acts like `docker run` - I'd have expected that, and also for `docker-compose up`.

Currently the only way to get an image on just one node is the `docker run` workflow you mentioned, which is pretty unintuitive, IMHO.

> If you need to do re-deploys with an updated image, why are you using a static image tag? This could easily be a content-addressable ID

We're using this during development until we reach beta stage. If the CI is green an image get's pushed and a redeploy is triggered. How would an ID help us, regarding we only want an image on the node which runs the image in the end?

**Comment by thaJeztah** [comment]
classic swarm was deprecated, and compose is a separate project

Let me close this ticket for now, as it looks like it went stale.
