### ISSUE TITLE
docker volumes docs out of date

### ISSUE THREAD

**Issue by cpuguy83** [moby/moby#20465]
The documentation for docker volumes (found here: https://docs.docker.com/engine/userguide/containers/dockervolumes/) is woefully out of date.

Since docker 1.9 includes top-level `volume` subcommands, and support for volume plugins, this documentation should be updated to reflect these new features.
It should also de-emphasize data-only containers as these are no longer considered a recommended pattern.

**Comment by AriaFallah** [comment]
In the mean time, where can I learn about the `docker volume` command and how to use it?

**Comment by mabraham** [comment]
@AriaFallah https://docs.docker.com/engine/tutorials/dockervolumes/ does document at least some of the functionality of `docker volume`

**Comment by EugenMayer** [comment]
At least this section needs to be updated i guess https://docs.docker.com/engine/tutorials/dockervolumes/#/creating-and-mounting-a-data-volume-container ... please notice that this already leads to issues / misconceptions like http://stackoverflow.com/questions/39013222/data-container-with-named-or-anonymous-volumes-conceptual-problems-discuss .. it would be great to get this fixed

**Comment by chernals** [comment]
Reviving this issue as I believe the present doc is quite misleading. It took me a while to understand the present-day situation.

**Comment by pmatts** [comment]
I'm just picking up docker for the first time. The first thing I wanted to learn was best practices for data persistence.  Finally, after being misled by dockers own documentation, I realise named volumes are the new standard. I took a lot of energy to learn that. I consider myself lucky I learned it at all. I will continue to learn despite dockers own misleading documentation. I could take some time considering all the second opinions I am now inclined to seek.

**Comment by EugenMayer** [comment]
@pmatts and most probably your current understanding is already outdated considering what we have now like bind mounts into name volumes using docker create and things like that.

Being active on stack and also providing https://github.com/EugenMayer/docker-sync i regularly deal with users not being able to understand how volume ought to work - especially named volumes are completely missed - it repeats and again and again - e.g. since i just tell people no use a named volume in docker-sync, they stuck on this generally.

So i really find this issue more and more urgent, since the point is, you get far first without understanding named-volumes, so there are (bad) alternatives some might choose first and build upon it. So its not like people will force to find the solution, they will go with the first solution kind works - which makes it even worse later on.

**Comment by NicolasWebDev** [comment]
Is there any news on that front?

Is there an official documentation on named volumes somewhere?

**Comment by cpuguy83** [comment]
This is now updated https://docs.docker.com/engine/admin/volumes/
Thanks @mstanleyjones!
