### ISSUE TITLE
Docker containers link should fail in different networks

### ISSUE THREAD

**Issue by wenchma** [moby/moby#21080]
Docker embedded DNS server gives wrong address for link-alias between default network and user-defined network.

Steps to reproduce:

```
root@201bffb8991f:/go/src/github.com/docker/docker# docker network create custom
d63dc618c472753ef56f9b37af7dbebf54116576ad0300ccba0fa67f4ed4aba2

root@201bffb8991f:/go/src/github.com/docker/docker# docker run -itd --name container1 busybox sh
78e7fb3b1e0849431687d67509daca75527b230ee0fbbc645c877b71db33532c

root@201bffb8991f:/go/src/github.com/docker/docker# docker run -itd --name container2 --net custom --link=container1:app busybox sh
921734a88630c0263d525616299ac823b8a5d1789060dc17d87310c0c2f32d60
root@201bffb8991f:/go/src/github.com/docker/docker# docker exec container2 ping -c 4 app
PING app (127.0.53.53): 56 data bytes
64 bytes from 127.0.53.53: seq=0 ttl=64 time=0.069 ms
64 bytes from 127.0.53.53: seq=1 ttl=64 time=0.066 ms
64 bytes from 127.0.53.53: seq=2 ttl=64 time=0.083 ms
64 bytes from 127.0.53.53: seq=3 ttl=64 time=0.064 ms

--- app ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 0.064/0.070/0.083 ms
root@201bffb8991f:/go/src/github.com/docker/docker# docker exec container2 ping -c 4 container1
ping: bad address 'container1'
```

Result expected:  cannot ping app
Result received:  can ping app, but with a strange IP address.

 `docker version`:

```
Client:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.5.2
 Git commit:   408badb-unsupported
 Built:        Wed Mar  2 05:07:22 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.5.2
 Git commit:   408badb-unsupported
 Built:        Wed Mar  2 05:07:22 2016
 OS/Arch:      linux/amd64
```

`docker info`:

```
Containers: 17
 Running: 1
 Paused: 0
 Stopped: 16
Images: 65
Server Version: 1.11.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 107
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-18-generic
Operating System: Ubuntu 14.04.3 LTS (containerized)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.797 GiB
Name: 201bffb8991f
ID: ZYWC:3ONA:L3P3:XFZM:TXHN:PMUM:F6TN:IMUA:CS6X:O52R:YRYZ:WGCG
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 15
 Goroutines: 30
 System Time: 2016-03-10T07:18:04.859808255Z
 EventsListeners: 0
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

**Comment by sanimej** [comment]
@wenchma This has nothing to do with the --link between containers on a custom network and default network.

I see the same behavior with a container on a user defined network without --link config..
```
vagrant@net-1:~$ docker run -it --rm --name container2 --net docker sanimej/ubuntu bash
root@4d345e6784c5:/# ping app
PING app (127.0.53.53) 56(84) bytes of data.
64 bytes from 127.0.53.53: icmp_seq=1 ttl=64 time=0.023 ms
64 bytes from 127.0.53.53: icmp_seq=2 ttl=64 time=0.082 ms
^C
--- app ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1003ms
rtt min/avg/max/mdev = 0.023/0.052/0.082/0.030 ms
root@4d345e6784c5:/# 
```
Docker embedded DNS server can only resolve the names in the domain of docker networks to which the source container is connected to. In this case since it can't resolve the name it will be forwarded to the external resolver you have configured. In my case its 75.75.75.75; it looks like there are conflicting IPs for an unqualified name `app`. The special IP 127.0.53.53 is used to indicate that there is an IP collision for the name.

```
root@4d345e6784c5:/# dig -t TXT app +short
"Your DNS configuration needs immediate attention see https://icann.org/namecollision"
root@4d345e6784c5:/# 
```
If you have a container with the name app or have setup a link alias app to another container in the same network it should work ok.

**Comment by wenchma** [comment]
@sanimej  what a coincidence  to choose `app` as alias name.  very appreciate your detailed explanation, it's all right as you said, about name collision, but it goes to anther issue:
IMO, this `--link` operation should throw error like : 

    docker: Error response from daemon: Cannot link to /container1, as container2 does not belong to the default network.

or

    docker: Error response from daemon: Cannot link to /container1, as container1 does not belong to the user-defined network.

**Comment by wenchma** [comment]
@sanimej my understanding,  we can only link containers within the same network, if the source container and target container are in different networks, the link should fail, no matter default network or user-defined networks. right ?

**Comment by sanimej** [comment]
@wenchma Yes, you can only link containers that are on the same network. The difference though is, in legacy mode (containers connected to default docker0 bridge) link checks if the target container is already running. But this strict dependency creates problems if you are trying to bring up the parent and child containers at the same time because the order is not known in advance.

To avoid this issue, --link for containers on user defined networks doesn't mandate that the target container is already running. Its by design to address the above mentioned use case. That is the reason why you are able to link to a non-existing container (`container1` in your case)

**Comment by wenchma** [comment]
@sanimej you are right, :+1: ,  now I changed the title to report another issue, please have a review at my fixing #21115

**Comment by neersighted** [comment]
Closing as likely stale.
