### ISSUE TITLE
EXPOSE and publish need to behave similarly with IPv4 and IPv6 [Security design failure]

### ISSUE THREAD

**Issue by ghost** [moby/moby#21951]
Right now, the following appears to be the current situation given docker's current state of implementation:

**When using IPv4:**
_(EDIT: Apparently an INCORRECT statement: Only ports EXPOSE'd are reachable by any other containers. This means random small programs inadvertently opening ports in a container aren't much of a problem. - Correction: EXPOSE only adds metadata, and ports are reachable anyway if you really want to even when not exposed)_
Only ports -p/--publish'd are reachable by the outside world. This means any containers having unsecured plain text and possibly password-lacking backends that is not EXPOSE'd is safely protected and cannot be reached directly in the outside world.

**When enabling IPv6 support:**
Suddenly, any sort of `[::0]` listen on any container is immediately reachable from everywhere in the world. (correct me if this is wrong. I hadn't had the chance to test this myself because of IPv6 configuration problems by my hosting provider, so I've had to rely on information provided by other docker users and developers. If I'm putting a factually incorrect statement out with this I'm sorry and I'll be happy to immediately retract this ticket)

---

This behavior difference is **absolutely insane**. It **needs** to be changed. You are asking for users to get into trouble.

To make a more constructive remark: one solution would be to introduce an explicit `docker run` switch to make a container with _opt-in_ behavior globally reachable, and in absence of the switches docker should default to writing ip table rules to drop all incoming connections to any containers' global IPv6 addresses for non-published ports.

**Comment by robbertkl** [comment]
I've created [docker-ipv6nat](https://github.com/robbertkl/docker-ipv6nat) to address this issue. It makes Docker IPv6 behave just like IPv4; give containers non-routable IPv6 addresses, use published ports to open up services to the outside world, get correct IPv6 source addresses within your containers. It all works just as you know/expect from IPv4.

Just a practical solution until Docker will have proper support for IPv6 with published ports.

**Comment by JonasT** [comment]
This issue would be resolved if #25407 was implemented (IPv6 NAT as an option) and if the IPv6 documentation for docker made sufficient effort to point out that the user should choose NAT if they want to retain the old security behavior without manual tweaking, and otherwise they are expected to delve deeper into manual iptable rules and other ways to customize their setup.

**Comment by thaJeztah** [comment]
Some note;

> Only ports EXPOSE'd are reachable by any other containers. This means random small programs inadvertently opening ports in a container aren't much of a problem.

This is not true; `EXPOSE` (and `--expose`) actually do not make a difference on the container-container network; any container on the same network can connect to any port of the container; the `EXPOSE` instruction only sets the metadata on the container (so that, for example `-P`, `--publish-all` knows which ports to publish)

**Comment by JonasT** [comment]
@thaJeztah thanks for the correction, I updated the text. The problem remains nevertheless, since the obvious main issue is that any random port listened on is reachable from the internet with IPv6, and with IPv4 a publish is needed to make it reachable from anywhere outside.

**Comment by thaJeztah** [comment]
@JonasT I know, it's not the direct issue at hand here :smile:

**Comment by mpalmer** [comment]
There is absolutely no reason to go using IPv6 NAT to make this happen.  A simple stateful IPv6 firewall would do just as well.

**Comment by JonasT** [comment]
@mpalmer yes but that wouldn't fix `-p` (publish). Of course it would still be a lot better than nothing, so if that is what the docker team went for it would still be an improvement, and for sure it would address the security problem. But maybe at least an alternative option for a full IPv6 NAT would be a good idea even just to possibly retain the semantics of `-p`/publish if the user wants them.

**Comment by mpalmer** [comment]
Publish is a dodgy hack needed only because IPv4 doesn't have enough address space.  It is not necessary for any reason in a sane IPv6 deployment.

**Comment by JonasT** [comment]
@mpalmer I disagree completely! Publish is absolutely essential for microservices deployment to make up multiple ports on the same IP address without different domains/hosts needed. If you just have clear independent containers for each service this is not needed, but if you make up services of larger amount of containers this can be necessary.

**Comment by jorhett** [comment]
@JonasT I think Matt's point is that you wouldn't need to put multiple ports on the same IP if IPv4 space wasn't so restricted. IPv6 frees that up and you stop thinking in the old compress/hide methodology.

I think a v6-routing design would be fine, but we'd need to do some work so that stacks and compose functionality between v4/v6 are consistent. I also think this adds a new need for dynamic DNS and routing table updates for most environments.

So a functional v6 routed solution would be:
- Documentation the v4 NAT with v6 routing design
- Providing interfaces or documentation to handle dynamic DNS updates
- Providing documentation for dynamic routing protocols/announcement
- Adjusting the "publish" functionality for IPv6 to alter ip6tables/etc same as v4

This really isn't going to work for most devs or people without control of their infrastructure. I think there's two ways around it:

1. v6 nat for perceived simplicity/consistency (even if horrible) as per docker-ipv6nat

2. configure v4 interfaces on a routed network with --publish and put v6 interfaces on a bridged network, with --publish altering the ip6tables to allow the traffic

**Comment by JonasT** [comment]
@jorhett yes, and my point is that you still can't point a single domain/host to two different domains with IPv6! So if you have a service with multiple ports that is split up into multiple containers, you *need* NAT or some other sort of forwarding.

**Comment by jorhett** [comment]
@JonasT you need to step back one level from your use case. What possible use case is there to put different ports on the same address with IPv6? That need has disappeared.

If you want to proxy connections, you use a proxy :)  Frankly, it makes perfect sense for docker to say "this isn't part of docker, you can use a proxy of your own choosing for this need"-- which is what they've said. They only implemented the v4 proxy because they had to, and they'd rather get out of that business.

**Comment by JonasT** [comment]
> What possible use case is there to put different ports on the same address with IPv6? That need has disappeared.

I'm not convinced of that, although I agree it might not be super common.

Anyway, even if you take that away there's still the developer use case of getting a simple environment running on a laptop or small test server without custom routing that **just works**. IPv4 only will soon no longer be a "just works" scenario due to the exhaustion of addresses.

I agree with all you folks that in an ideal world there is no IPv6 NAT needed. However, I am very convinced that there are still valid use cases and therefore it is worth having it as **an option**.

**Comment by robbertkl** [comment]
> The whole reason to use a new protocol is because it gives you new features and benefits.

No. Lots of people/companies (me included) don't give a damn about the added IPv6 features, but are simply forced to provide IPv6 access to their services because "pretty soon" that's the only way a subset of their customers can reach them.

**Comment by mpalmer** [comment]
IPv6-enabled proxy on the edge, keep all your internal stuff on IPv4.  Done.  Works for AWS, it can work for you.

**Comment by JonasT** [comment]
@mpalmer and how is that supposed to work for people just firing up docker on their laptop to test a small deployment?

**Comment by mpalmer** [comment]
You don't get to have it both ways: either you need IPv6, in which case you use IPv6, or you don't need IPv6, in which case you use IPv4.  Trying to use IPv6 like it's IPv4 is pointless -- you have a protocol that behaves like IPv4 already -- IT'S CALLED IPv4!

**Comment by JonasT** [comment]
@mpalmer I don't know why we are having this discussion. It should be obvious that IPv4 is being faded out, no? It isn't that unreasonable to assume that at some point not that far into the future be useless ,at least if you want to connect to the internet. For some odd reason you seem to assume people only enable IPv6 for different features, but some of us just want services to remain reachable in a changing world.

Anyway, we're going in circles so it's probably best if I stop.

**Comment by akerouanton** [comment]
It seems the original intent of this issue was to ask for NAT66. This was added in v20.10 through the `ip6tables` daemon flag.

Nonetheless, I recognize a few comments suggesting to improve `--publish` semantics to make it either a port mapping option (ie. NAT config), or an ACL mechanism (ie. for 'only-routed' networks) are very valid. We're currently considering implementing such improvement, but I don't think this specific issue is the right place to track and discuss that.

So let me close this one, but feel free to continue the discussion.
