### ISSUE TITLE
Please provide i386 Debian packages

### ISSUE THREAD

**Issue by paulmenzel** [moby/moby#22290]
Currently, Debian packages are only provided for amd64 (#22288).

It’d be awesome if packages for i386 would be also provided.

**Comment by thaJeztah** [comment]
Unfortunately, the daemon requires a 64-bit OS (on any distro), only the *client* is able to run on 32 bit systems. Even if the daemon was able to run on 32-bit, there are no (official) images on Docker Hub that run on 32-bit systems, so it wouldn't be very useful.

**Comment by paulmenzel** [comment]
Debian (proper) provides [Docker packages for both architectures](http://packages.debian.org/docker.io).

What is the reason, that the daemon requires a 64 bit OS?

**Comment by thaJeztah** [comment]
afaik, historically it requires some 64-bit libraries. But also portability; having a 32-bit docker daemon would make it impossible to run images built for 64-bit, and break the user expectation of "build once, run anywhere". Providing all official images both as 32 and 64 bit is not a small effort, and most recent installations (both bare-metal and in the cloud) are 64-bit. There are some people that build their own 32-bit capable version of docker, but it's really experimental. Some discussion can be found here; https://github.com/docker/docker/issues/136, https://github.com/docker/docker/issues/611, https://github.com/docker/docker/issues/7513, https://github.com/tianon/docker-brew-ubuntu-core/issues/28

I'll close this issue, because it's not on our roadmap currently, but feel free to continue the discussion

**Comment by bgraves** [comment]
I know I'm hacking, but I thought I would drop a comment here just to see if I can get any more information from other crazy people.  Otherwise feel free to ignore.

I'm running i686 Gentoo.  Ideally docker would run on this system. I grabbed docker and containerd from github.

In the containerd repo I ran 

`$ ./hack/vendors.sh`
 
With the clean line commented out.  I also added the line:

`clone git github.com/docker/containerd 0e9e24c6470321f134ab2484f921e2c3c9382022`

Idk, make looks in the vendors directory for containerd.

Then I ran:

`$ make`

That "successfully" built...in the bin directory.  I added that to my PATH.

For docker (of course all the mandatory kernel stuff) and then:

`$ export DOCKER_BUILDTAGS='exclude_graphdriver_btrfs exclude_graphdriver_devicemapper'`

`$ AUTO_GOPATH=1 ./hack/make.sh`

This built some binaries under bundles (for example):

`bundles/latest/binary-client/docker`

I added that to my PATH.

I can actually start a daemon with:

`$ docker daemon --containerd unix:///var/run/docker/libcontainerd/docker-containerd.sock -D`

Why the --containerd?  It defaults to some legacy format, at least the commit I'm using.

Then...I'm stuck running, for example:

`$ docker version`

. . .it hangs.

Docker daemon version:
Docker version 1.12.0-dev, build 1e9b235

Docker client version (if daemon is not running):
Client:
Version:      1.12.0-dev
API version:  1.24
Go version:   go1.4.2
Git commit:   1e9b235
Built:        Sun Apr 24 16:10:24 2016
OS/Arch:      linux/386
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

**Comment by paulmenzel** [comment]
@bgraves, I think this warrants a separate issue. Thank you for testing.

**Comment by paulmenzel** [comment]
@thaJeztah, thank you for the response. I think with an appropriate warning at the start of Docker or so, this shouldn’t be an issue.

For developers, there are some using a mix of machines. Some are older and only support 32-bit, so the main system needs to be 32-bit, despite most of the development machines support 64-bit.

(In my case it’s a Lenovo X60 and T60 supporting [coreboot](https://www.coreboot.org/).)

**Comment by bgraves** [comment]
@paulmenzel I don't think it should be an issue at all in my case...I'm clearly doing something docker has chosen (somewhat understandably) not to support.  ;-)  Thanks for the reply!

**Comment by cpuguy83** [comment]
We cannot provide binaries for platforms we do not support.
There is no support for any platform other than Linux+x86-64.

**Comment by justincormack** [comment]
We are actually providing daemon binaries for non supported platforms at present on master https://master.dockerproject.org/ eg ppc64le, s390x both have dockerd (not sure when this changed), and there have been requests for arm too, and we have merged patches for building debs for armhf in #18176 so I think a patch for building debs for i686 could possibly be accepted if someone were to contribute one. There may be an issue about the existence of official images for i686 though. I think someone will have to contribute this though, as it is a very unusual platform now, and there are no good reasons to use it that I know of, so there might be some pushback.

**Comment by AkihiroSuda** [comment]
It is 2020 now and this seems closable.
