### ISSUE TITLE
[1.10+] Image Layer "container_config.Cmd" Format Change

### ISSUE THREAD

**Issue by tianon** [moby/moby#22436]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.11.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.17-gentoo
Operating System: Alpine Linux v3.3 (containerized)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.14 GiB
Name: 16f4367dd1c4
ID: R3AA:MSLS:P53W:RPDZ:JVFB:CUJV:KGF4:TFXZ:HFSM:SZXY:6MJ6:UWBA
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Steps to reproduce the issue:**
1. build an image with `MAINTAINER`, `COPY`, `CMD` (or similar non-`RUN` commands)
2. push the image to a registry
3. inspect the manifest (specifically, `.history[].v1Compatibility | fromjson`)

**Describe the results you received:**

``` json
  "container_config": {
    "Cmd": [
      "/bin/sh -c #(nop) ADD file:9a7009973be82c34ab6e18180f08fdc4c2f039806226ce7a48ba9361efe4804b in /"
    ]
  }
```

**Describe the results you expected:**

``` json
  "container_config": {
    "Cmd": [
      "/bin/sh",
      "-c",
      "#(nop) ADD file:9a7009973be82c34ab6e18180f08fdc4c2f039806226ce7a48ba9361efe4804b in /"
    ]
  }
```

(as in 1.9 and previous)

This gets even more fun when "build args" are used, since they're stored with a strange pipe-prefixed format that's only really parseable in the array syntax (so the "smashed string" version really screws parsing up there).

Here's an example of how "build args" exhibit themselves when pushed via 1.9:

``` json
[
  "|6",
  "a=1",
  "b=2",
  "c=3",
  "d=4",
  "e=a b c",
  "f=a b \" c",
  "/bin/sh",
  "-c",
  "echo hi"
]
```

**Comment by thaJeztah** [comment]
ping @aaronlehmann @tonistiigi PTAL

**Comment by tianon** [comment]
Here's an example of build args going through 1.10+:
```json
[
  "|4 a=1 b=2 c=3 d=4 /bin/sh -c echo $a $b $c $d"
]
```

**Comment by aaronlehmann** [comment]
Yeah, these do get flattened as part of the changes to the image format in 1.10: https://github.com/docker/docker/blob/master/image/image.go#L110

**Comment by tonistiigi** [comment]
Just that I understand this properly, this is purely a change in the config that is invisible and without side-effects to the user? Do I understand correctly that this only happens when you push an image with `v1.10+` and then pull it with `<v1.10` and view the intermediate configs. These configurations are generated from the `v1.10` history chain and should lack a lot of fields(and should essentially be not runnable).

**Comment by tianon** [comment]
Is there another place I could be grabbing this "build chain" information when I'm inspecting an image in a registry?  I'm not looking for a runnable layer necessarily, but getting information about the chain of the build is a really useful debugging tool.

What's seeming strange about this particular case is that it's still surfaced as an array in the metadata, but the "array" granularity is lost (and so the ability to parse the value in a sane manner programatically is as well).

**Comment by tonistiigi** [comment]
@tianon If you look at the image config in `v2.3+` registry(or just `cat /var/lib/docker/image/<driver>/imagedb/content/sha256/<id>` after build), this is the whole data that is pushed. It contains a history array with items for every Dockerfile command https://gist.github.com/aaronlehmann/b42a2eaf633fc949f93b#history . The key that holds the command data is just a string, not an array there(this is causing the problem you are seeing). All other structures are generated from this config for compatibility with older formats.

**Comment by tianon** [comment]
Oh, I see :cry:

**Comment by tianon** [comment]
Here's a particularly troubling example that I can't possibly parse after this "squashing" is performed (due to the formatting of the resulting string):
```dockerfile
ARG a=1
ARG e="a b c"
ARG f="a b \" c"

RUN ["echo", "$a"]
```
Which becomes:
```
|3 a=1 e=a b c f=a b " c echo $a
```

Could we at least do something like shell quoting on the `ARG` values?

Additionally, lines like `ARG a=b` turn into `/bin/sh -c #(nop) ARG a=b`, which is not terribly nice to look at.  IMO it'd be interesting to convert all of these into mostly-valid `Dockerfile` instructions, ie, `RUN echo hi`, `ARG a=b`, `|1 a="b c d" RUN echo $a`, etc.

**Comment by tianon** [comment]
I've been building up the tags of `tianon/build-args` to be examples of how these get converted from `Dockerfile` to manifest in various Docker engine versions at https://hub.docker.com/r/tianon/build-args/tags/.  I'm thinking of adding `master` there as well.

**Comment by tianon** [comment]
`ENTRYPOINT` appears to gain some additional characters too: `ENTRYPOINT &{["/gzserver_entrypoint.sh"]}` vs `ENTRYPOINT ["/gzserver_entrypoint.sh"]`

`CMD` is similar, but not as pronounced for some reason: `CMD ["sh" "-c" "echo $test"]` vs `CMD ["sh", "-c", "echo $test"]`

**Comment by tonistiigi** [comment]
@tianon 
For every command in Dockerfile, Docker makes up a `containerConfig.Cmd` string. This is only used for build cache, versions `<1.10` also used it for `docker history`. Usually, these strings are made up with only uniqueness in mind. If you have better ideas, I think they could be updated as their only effect could be invalidating build cache. Of course, we don't know if anyone uses the format for their own tools like you do.

From `v1.10`, `history.CreatedBy` is used instead in `docker history`. Because it has no meaning for the build cache, this does not need to match with `containerConfig.Cmd` at all. For example all the `#(nop)` prefixes could be skipped in there. Only other place it is still used is when `v1.10+` config(v1.1) needs to be converted to `<v1.10` config(v1.0 spec), for this every history item is converted to its own config with `containerConfig.Cmd`. So as long as we can provide a somewhat meaningful fallback we could change the history values quite freely. But I think the `CreatedBy` value in history array should only be a textual note, something that describes to the user what happened in this step. If we want to add some truly machine readable structures we should consider adding a new field to history object, not sure if it is worth the extra space though.

How/where did you get the `ENTRYPOINT &{["/gzserver_entrypoint.sh"]}` output?

**Comment by yosifkit** [comment]
It is definitely useful to be able to recreate the lines of the Dockerfile from the image metadata like [this tool](https://github.com/vbatts/docker-utils/blob/master/dockerfile/dockerfile.go) by the amazing @vbatts.  I can think of at least two services (besides our own usage within the Official Images documentation) that rely on this useful metadata: imagelayers.io and Docker's own Nautilus security scanning.

Here are two links showing the failures:
- https://imagelayers.io/?images=tianon%2Fbuild-args:master,gazebo:gzserver4,tianon%2Fbuild-args:1.9.1,solr:6.0.0,tianon%2Fbuild-args:1.10.3,tianon%2Fbuild-args:1.11.1 (note that it appears imagelayers.io strips `[` and `]`)
- https://hub.docker.com/r/library/gazebo/tags/libgazebo4/  (nautilus requires you to be logged in to view)

It seems the funky `ENTRYPOINT` happens when built and pushed by `1.9.1` regardless of whether it did a round trip through `1.10+` (ie, the `&{}` funky output no longer occurs when built on 1.10+ and we get that `["a" "b" "c"]` comma-less output as would be more expected given how `CMD` renders).

**Comment by tonistiigi** [comment]
@tianon Can you propose(or just PR) a syntax that you wish to be saved in the history object instead. 

My only requirements are that:
- when used inside `v1Compatibilty` config it should not change the current behavior of running intermediate images. But we don't have to use same string in there, we just need to be able to convert between `history` and `v1Compatibility`
- It still allows us to implement build cache in backwards compatible way. So if we compare 2 commands, even if they are generated by different versions, we can make an optimistic assumption that they came from the same command.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
