### ISSUE TITLE
Docker Installation failed on RHEL7 Workstations using  Docker Installation Script

### ISSUE THREAD

**Issue by hemanth-avs** [moby/moby#22649]
Installation of Docker failing on some RHEL Workstations.

Instructions followed from https://docs.docker.com/engine/installation/linux/rhel/

Received the following error message message
Script Execution : curl -fsSL https://get.docker.com/ | sh
## Error Message:

Either your platform is not easily detectable, is not supported by this
      installer script (yet - PRs welcome! [hack/install.sh]), or does not yet have
      a package for Docker.  Please visit the following URL for more detailed
      installation instructions:
## Root Cause:

Linux Standard Base distribution variable in script ( https://get.docker.com/ ) is evaluated to "RedHatEnterpriseWorkstation" in some RHEL workstations.

lsb_dist="$(lsb_release -si)"

RedHatEnterpriseWorkstation condition is not properly handled in platform detection check

**Comment by thaJeztah** [comment]
Thanks for reporting! Note that, in general, the manual installation procedure is the recommended approach; the install script is on a "best effort" base and, in case of the devicemapper storage driver, does not configure the driver for "production" use (which is a manual procedure: https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#configure-direct-lvm-mode-for-production)

Perhaps we can improve the detection for this case though

**Comment by rkgade** [comment]
Hi @thaJeztah ,

I have a similar query, however, I am installing through YUM.
**OS:** RHEL 7.2 
**DockerEngine**:Docker version 1.11.2-cs3, build c81a77d

Once installed, I configured docker to use device mapper.
I have created couple PVs. Created a VG and two LVs as specified at 
https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#configure-direct-lvm-mode-for-production

However, after setting up UCP and DTR on two specific nodes( docker cs engine on both nodes configured as above ) , worked fine until first reboot. 

After reboot, LVMs created above using the mentioned procedures were not available.
They were not available because they were not mounted.
However, if I mount a give a mount directory in docker.service --storage-opt option, the error saying "Error initializing graphriver Open: <directory where LV is mounted> is a directory."


**FOR OS:**
             mounting is required to identify storage upon reboots
**FOR DOCKER:**
            docker is not accepting mounted location. If used devicemapper approach as mentioned above, storage is not persistent across reboots.

**NOTE:** Storage is from SAN. All drives ( including OS ) are from SAN.
**NOTE:** Please find attached the log file which has all the steps executed. Tried hard to remove typos.

Kindly help here as it's a production box.

[docker.txt](https://github.com/docker/docker/files/304405/docker.txt)

**Comment by thaJeztah** [comment]
@rkgade could you contact support@docker.com, that's the proper channel to get support for Docker DataCenter; the GitHub issue tracker is not really intended for that. If you think there's a bug, please open a new issue, because your issue does not look related to the issue that's discussed here

**Comment by rkgade** [comment]
Hi @thaJeztah , 
Sure. Thank you.

**Comment by cnmcavoy** [comment]
Confirming this is still a valid issue. It looks like there is a [specific workaround for `RedhatEnterpriseServer`](https://github.com/docker/docker/blob/b06f25496d803efa2177cd7e89d660f37b295a19/hack/install.sh#L291) as the lsb_release string, but not `RedhatEnterpriseWorkstation`. I'd suggest that both strings be tested, or maybe just check that the string starts with `redhat`.

**Comment by thaJeztah** [comment]
@cnmcavoy looks like an easy fix; are you interested in opening a pull request to accept both `RedhatEnterpriseWorkstation` and `RedhatEnterpriseServer` ?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
