### ISSUE TITLE
Add "image untag" event

### ISSUE THREAD

**Issue by docwhat** [moby/moby#23174]
Currently, there is no event for the "untag" event.

An example.  Given the following commands:

```
$ docker pull busybox:latest
$ docker tag busybox:latest fish:bloop
$ docker rmi fish:bloop
```

Then I get the following events:
1. image pull
2. image tag
3. _Nothing..._ I expected an image untag event.

The use-case for this is for [docker-gc](https://github.com/docwhat/docker-gc) which could pro-actively remove records for any tags that are deleted.  It's an optimization, since it'll do the right thing on its own eventually.

**Comment by thaJeztah** [comment]
I think it would make sense to have this

ping @calavera wdyt?

**Comment by calavera** [comment]
yes. Event all the things!

**Comment by calavera** [comment]
Actually, now that I look at it, there might be some kind of issue, because that event already exists:

https://github.com/docker/docker/blob/ad8d0c9a8bd93a23c745efe1aac0a0692aeefa91/man/docker-events.1.md#description

https://github.com/docker/docker/blob/7d7d8fa752d343a084164717d7089cd47f0cacc7/integration-cli/docker_cli_events_unix_test.go#L329

It might not be fired in certain conditions.

**Comment by vdemeester** [comment]
On current master, I cannot reproduce, I do have the `untag` event.
@docwhat could you try on 1.12.0-rc2, I think it's in there :angel:

**Comment by docwhat** [comment]
Yes. `docker events --filter=event=untag ` works.
