### ISSUE TITLE
[1.12.0-RCx] Review consistency of API reference with the code

### ISSUE THREAD

**Issue by icecrime** [moby/moby#23597]
Review consistency of API reference with the code on the new endpoints:
- Node endpoints
- Service endpoints
- Swarm endpoints

**Comment by icecrime** [comment]
Ping @sfsmithcha: are you available to take a pass a this?

**Comment by thaJeztah** [comment]
also see https://github.com/docker/docker/issues/25153

**Comment by RobbieClarken** [comment]
I believe the documentation for configuring service endpoints through [`/services/create`](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/create-a-service) is incorrect. The docs refer to specifying the following in the posted json:

```
Endpoint – Properties that can be configured to access and load balance a service.
    Spec –
        Mode – The mode of resolution to use for internal load balancing between
               tasks (vip or dnsrr).
        Ports – Exposed ports that this service is accessible on from the outside,
                in the form of: "Ports": { "<port>/<tcp|udp>: {}" }
    VirtualIPs
```

This doesn't match the example request on that page which has an "EndpointSpec" key instead of "Endpoint" in the json:

```
POST /services/create HTTP/1.1
Content-Type: application/json

[...]

"EndpointSpec": {
  "Ports": [
    {
      "Protocol": "tcp",
      "PublishedPort": 8080,
      "TargetPort": 80
    }
  ]
},
```

I'm not sure if it is possible to configure the service endpoints using an object under an "Endpoint" key rather than "EndpointSpec" (I've tried various forms without success). It would be nice to get this clarified because the development code in [docker-py is posting data using "Endpoint"](https://github.com/docker/docker-py/blob/24bfb99e05d57a7a098a81fb86ea7b93cff62661/docker/api/service.py#L30) which may not work.

**Comment by manast** [comment]
@RobbieClarken I just verified that in order to specify the endpoint you need to use the same format as the example, i.e. ```EndpointSpec```, the documented alternative ```Endpoint: { Spec: ...}``` does not work, its just ignored.

**Comment by thaJeztah** [comment]
opened a PR to fix that part of the docs https://github.com/docker/docker/pull/26634

**Comment by thaJeztah** [comment]
I think it's in a better shape now, but there will still be some parts that need checking; in the meantime, I don't think we need this ticket for tracking, so let me close this one.
