### ISSUE TITLE
`docker node update` should allow renaming a node and setting labels

### ISSUE THREAD

**Issue by jlhawn** [moby/moby#23937]
**Output of `docker version`:** docker 1.12-rc2

This is more of a feature request than a bug report. Node labels are very important when it comes to setting constraints for where you want services to run in the cluster but currently there's no way of doing it. I have found that I am able to change the name of a node and modify labels using the API - this is just a matter of adding support to the Docker CLI.

**Comment by jlhawn** [comment]
cc @vieux @dongluochen @dperny

**Comment by rsippl** [comment]
I suppose you're using the (undocumented?) POST nodes/.../update API. Weirdly enough, that fails for me, I keep getting an _invalid Role: ""_ error:

$ curl 'http://server.docker:2375/nodes/dhh10x30lpz3jsu5mhbjn4dys/update?version=42' -X POST --data '{"Spec":{"Role":"worker"}}'
{"message":"invalid Role: \"\""}

Any idea what I'm doing wrong? No matter what I pass as a role, the docker daemon thinks it's an empty string.

**Comment by jlhawn** [comment]
@rsippl That is indeed strange. I wonder if it's just `curl`. The `--data` option submits the data as `Content-Type: application/x-www-form-urlencoded`. Try the command again with `--data-binary` and set `--header 'Content-Type: application/json'`

**Comment by rsippl** [comment]
It works this way:

`curl 'http://server.docker:2375/nodes/35mesypynmey27p17ulkhias1/update?version=10' -X POST --data '{"Role":"manager","Membership":"accepted","Availability":"active"}'`

i.e. you need to pass just the Spec object, and you're not allowed to omit any of the three attributes (otherwise you get e.g. an "invalid Availability" error). BTW, it works both with `--data` and `--data-binary`.

**Comment by Richard-Mathie** [comment]
How do you update the node labels with that, `docker node update --label-add` didn't make it into RC4, despite it being in the orchestration docs, and I would like to test this.

I have tried 

```
sudo curl --unix-socket /var/run/docker.sock \
    http:/nodes/<node_id>/update?version=10 -X POST \
    --data '{"Role":"worker","Membership":"accepted","Availability":"active","Annotations":{"Labels": {"network":"public"}}}'
```
but i get
```
{"message":"rpc error: code = 2 desc = update out of sequence"}
```
Any ideas? Thanks

**Comment by rsippl** [comment]
"update out of sequence" means that version=10 is wrong, you need to pass the current value for version. That said, I haven't tried to update the labels...

**Comment by Richard-Mathie** [comment]
issue should be closed as `docker node update` allows you to add and remove labels now

**Comment by thaJeztah** [comment]
Ah, yes, labels can be updated since docker 1.12 (implemented through https://github.com/moby/moby/pull/24397)

Node _names_ are base on the hostname of the node, and cannot be set, so changing that would involve separating the name from the hostname, which would be a bigger change (and need discussion).

Let's close this one for now
