### ISSUE TITLE
[1.12rc3] No backwards-compatible way to force-tag images?

### ISSUE THREAD

**Issue by chriskuehl** [moby/moby#24494]
1.12rc3 hard-dropped the `-f` flag from `docker tag` (#23090). There now appears to be no way to force-tag images in a way that is compatible with older Docker versions (before 1.10, only 5 months old).

This works on 1.12rc3, fails on versions before 1.10 (e.g. 1.9.1):
1. `docker tag <some-image> my-test`
2. `docker tag <some-other-image> my-test`

Fails on 1.12rc3, works on versions before it:
1. `docker tag -f <some-image> my-test`
2. `docker tag -f <some-other-image> my-test`

The only way we can safely stop using the `-f` flag is if we can assume all of our hosts are using Docker 1.10 or newer.

Please consider leaving the deprecated flag in-place for 1.12 final. 1.10 was only released 5 months ago. Dropping the flag is not only going to break a lot of places that use `-f` for tagging, but means we can't deploy 1.12 at all until we've upgraded all of our hundreds of hosts running Docker to at least 1.10 (some of which are out of our control; for example, Travis and CircleCI are both still on Docker 1.8.2).

**Comment by thaJeztah** [comment]
Thanks for reporting @chriskuehl; wondering; you mention that some of your hosts are updated, and some not, so you probably don't make use (yet) of newer features (introduced in newer versions). Would using an old "client" solve your use-case? i.e. update the daemons, but still use an older client, so that you can keep using the `-f` flag for now?

In general; we decided on a two-release deprecation policy; do you think that's too short of a time for users to adopt?

**Comment by chriskuehl** [comment]
@thaJeztah yes, we're not using a lot of new features yet (mostly just upgrading for the stability improvements). In this case, we're hoping to use overlay2 from 1.12 since we've found it performs significantly [better than aufs](https://github.com/chriskuehl/docker-storage-benchmark) for some of our workloads.

I don't know much about the Docker project itself, but for something that's a critical piece of a lot of  production infrastructure, I think it's worth being a little lenient in deprecating things when they're not really adding significant technical debt to Docker itself. Especially since Docker is moving quickly, upgrading hundreds of production hosts to newer versions of Docker can take a lot of time and planning. Unfortunately a lot of people are still on Docker pre-1.10 (even things like Travis/Circle).

**Comment by thaJeztah** [comment]
@chriskuehl thanks; running a 1.12 daemon on `overlay2`, and using a (e.g.) 1.10 *client* should still work, as the storage driver is defined as a daemon option.

Perhaps we could consider to use a default 3 release cycle (roughly 6~7 months) instead of 2 for the deprecation policy. Could you open a separate issue for that?

**Comment by dfarrell07** [comment]
FYI, Packer's docker-tag post-processor is breaking because of this. https://github.com/mitchellh/packer/issues/3771

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.
