### ISSUE TITLE
`Experimental: true` is misleading

### ISSUE THREAD

**Issue by tiborvass** [moby/moby#25183]
The experimental channel of docker distributes a version of docker based off of the regular release channel, but with additional _experimental_ features. Only those features are experimental, not the rest.

I am not sure what the best solution would be, all I know is that it is getting confusing.

cc @icecrime

**Comment by thaJeztah** [comment]
"experimental features: enabled"? 
"experimental: enabled"?

**Comment by AkihiroSuda** [comment]
"experimental features enabled: true"?

**Comment by icecrime** [comment]
Ping @sfsmithcha: do you know if this is explained anywhere in the docs, and if the wording is appropriate?

**Comment by allencloud** [comment]
feel misleading, too.

**Comment by sfsmithcha** [comment]
@icecrime , don't think this is covered in the docs. especially since, up until v1.12.0rc1 experimental features didn't get any documentation. We should definitely include a mention of it in the docs. Currently when you search "experimental" (yay! docs search) it only returns hits for the experimental advisory.

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.
