### ISSUE TITLE
docker daemon does not set PR_SET_CHILD_SUBREAPER, causing containers to be reaped by init when containerd crashes

### ISSUE THREAD

**Issue by cinchurge** [moby/moby#25575]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:11:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:11:07 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 11
 Running: 1
 Paused: 0
 Stopped: 10
Images: 1
Server Version: 1.11.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.18.38
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 125.8 GiB
Name: xxxxxxxxxx
ID: 2CN4:XXBL:OB7T:2C3I:2IKH:5MUC:EWDS:EHQO:ZN4R:IIPP:L4EL:P6BW
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical box

**Steps to reproduce the issue:**
1. Start container: `sudo docker run -t -i ubuntu /bin/bash`
2. Find pid of containerd: `$ ps -ef | grep containerd`

```
root      69439   1132  0 00:05 ?        00:00:00 docker-containerd -l /var/run/docker/libcontainerd/docker-containerd.sock --runtime docker-runc
root      72292  69439  0 00:07 ?        00:00:00 docker-containerd-shim df86fbeea607ee45fb352b3535646378dcd95add83e3dd31b8e9ca0e36a3683e /var/run/docker/libcontainerd/df86fbeea607ee45fb352b3535646378dcd95add83e3dd31b8e9ca0e36a3683e docker-runc
echung    73794  66909  0 00:07 pts/3    00:00:00 grep containerd
```
1. Kill containerd: `$ sudo kill -9 69439`
2. docker-containerd-shim is reparented to init: `$ ps -ef | grep shim`

```
root      72292      1  0 00:07 ?        00:00:00 docker-containerd-shim df86fbeea607ee45fb352b3535646378dcd95add83e3dd31b8e9ca0e36a3683e /var/run/docker/libcontainerd/df86fbeea607ee45fb352b3535646378dcd95add83e3dd31b8e9ca0e36a3683e docker-runc
echung    73835  66909  0 00:07 pts/3    00:00:00 grep shim
```

**Describe the results you expected:**
the container should be reparented to the docker daemon

**Additional information you deem important (e.g. issue happens only occasionally):**
we've seen on some machines where after the container is reparented to init, docker ps no longer lists that container, so users aren't able to remove it or stop it.

**Comment by cpuguy83** [comment]
Parenting of the container process should not have an effect on what is displayed in `docker ps`.
Docker has it's own internal state for containers which operates independently of containerd, though it does rely on events from containerd to notify about state changes.

ContainerD being a child process of docker is only really because docker starts containerd automatically if it's not already started. The shim process exists to specifically stay alive and attached to a container when containerd goes down so that it can re-attach to the process.

Docker is also not actually starting containers and is not really a subreaper, so shouldn't be setting subreaper.

Im curious what problem you are running into with this.
Note that `docker ps` only shows running containers, `docker ps -a` shows stopped containers.

ping @mlaventure b/c I could be totally off here.

**Comment by mlaventure** [comment]
@cpuguy83 is correct in his description.

The container itself is technically the child of `containerd-shim` (which does use `PR_SET_CHILD_SUBREAPER`).

I can not reproduce your issue of `docker ps` not listing running containers after having killed `containerd`.

On restart, `containerd` "reconnects" to all running container and as such should provide an accurate list of running containers to the daemon.

Do you get any error message from the log regarding the containers that disappear from `ps`?

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.
