### ISSUE TITLE
Manpage and cli reference discussion / consistencies

### ISSUE THREAD

**Issue by vdemeester** [moby/moby#25615]
Current man pages are not all consistent in term of content, placement and sections. There is also a lot of _duplication_ between man pages and cli reference documentation as they are maintained separately. This issues is there to discuss on those subjects and follow evolutions of our generation process.

The main goals are the following and take most of the inspiration from `git` man pages and reference documentation :
- Have consistent man page across commands.
- Have cli reference documentation be in sync (or the same) as man page (just a web page for it).
- Have (or not) man pages generated from source (part of it or all of them).
### Man page style guide

We currently don't have any style guide for man pages, i.e. what information to put where and in what order. As code style guide, we might want to define a _man page style guide_ document that would define what makes a good man page for `docker` commands. This is related to #16219.

That could look something like :

```
## NAME

command - short description of the command

## SYNOPSIS

command --with --some --flags --and [OPTIONS] …

##  DESCRIPTION

A description is more detailed than what's in the NAME section, explaining more in depth what the command does (but that's all)

## OPTIONS

-a --all

Flags descriptions …

## ADDITIONAL SECTION 1

Additional section are possible. An example would be `FILTERING` and `FORMATTING` for the `docker-ps` command, or something about the reference format for command that allow us to set them (like `docker-commit`, `docker-tag`, …).

## ADDITIONAL SECTION 2

No limit in the number of section though 👼

## EXAMPLES

Here, we just gives example on how to do this on that ; this is not where we explain how to filter container (it's done in its own section), just a working example of it.

## ENVIRONMENT AND CONFIGURATION VARIABLES

If there is any environment variable or configuration (in the client/daemon config file) related to the command, we'll talk about it here ; like `ImagesFormat` for `docker-images` formatting.

## SEE ALSO

```
### Man page and cli ref doc maintainability

Maintaining separately man pages and cli reference documentation is error prone, it's easy to forget some flags or description somewhere. It's related to #19088. The basic idea would be to generate man pages and cli reference documentation from the same source.

Given that we are trying to generate man page from the code (at least partially), we should also study a way to generate cli reference documentation at the same time — shouldn't be difficult to convert markdown/man page to hmtl 👼.
#23825 introduced a way to generate man page directly from code — from a small subset of command right now, but goal is to do that for all commands.

Current limitations / questions are the following (making the assumption that cli reference documentation is generated from the same source) :
- Cobra does not seems to allow add any custom section (it only supports `EXAMPLE`).  It's possible to add `## Some Section` in the description part, but this would make the `OPTIONS` section be really far down in the man pages (which can be fine :angel:).
- It makes "documentation" PR's becomes more difficult; to make changes to this part of the documentation now requires contributors to touch the actual code.
- Should we keep around some part of the man pages/documentation in markdown files (that would be merge with generated content from cobra) ?

/cc @thaJeztah @dnephin @icecrime

**Comment by dnephin** [comment]
> The basic idea would be to generate man pages and cli reference documentation from the same source.

+1

> we should also study a way to generate cli reference documentation at the same time

Cobra supports generating markdown documents from source: https://github.com/spf13/cobra/blob/master/doc/md_docs.md

> Cobra does not seems to allow add any custom section (it only supports EXAMPLE)

You can add arbitrary markdown to the description section. So we can really add any sections we want, they would just appear after the description, but I think this is pretty standard for man pages.

> It makes "documentation" PR's becomes more difficult;

Is it really more difficult? Contributors only need to edit a raw string block, it's not like they have to deal with any syntax. And this is only for reference documentation.  Narrative documentation is still just in markdown files.

**Comment by vdemeester** [comment]
> Is it really more difficult? Contributors only need to edit a raw string block, it's not like they have to deal with any syntax. And this is only for reference documentation. Narrative documentation is still just in markdown files. 

Yeah probably :stuck_out_tongue_closed_eyes:. Another *side-effect* is that a PR with only "documentation fixes" on manpage/cli ref would trigger the whole long build (with all tests) — but meh :angel:.

**Comment by thaJeztah** [comment]
> Is it really more difficult?

I think it is more difficult; for documentation, I can simply run `make docs` to check the output (so changing a reference documentation would require a compile of Docker, and building the docs). How do we handle highlighting (back-tics, GitHub flavor code blocks / fences) in the string block?

**Comment by dnephin** [comment]
> so changing a reference documentation would require a compile of Docker, and building the docs

Not true, you just run `make manpages`. It doesn't build the docker binary, just the docsgen binary. We can make this a dependency of the `docs` target, so you can still just run `make docs`, and have it work.

> How do we handle highlighting (back-tics, GitHub flavor code blocks / fences) in the string block?

You don't. It's not going to be displayed on github. We don't do this in the current markdown docs either.

**Comment by thaJeztah** [comment]
> We don't do this in the current markdown docs either.

We do, actually, so if the same generated code is used for the docs reference, we should have a solution for that.

**Comment by dnephin** [comment]
So we do, I was mistaken. I guess the language hinting is just ignored when converting to a man page?

I guess one option for dealing with this would be to provide the description as a separate markdown document.  In the "generate man pages" script we can open the markdown file and set the `Long` field with the contents from the file.

That would allow us to keep the cobra generation and also make it easier to add backticks to the description.

**Comment by sfsmithcha** [comment]
cc: @joaofnfernandes

**Comment by joaofnfernandes** [comment]
This is really an awesome initiative. I'm managing the docs for Docker Trusted Registry, and we're already doing something very similar to this.

I got a bit confused about about what you mean by `cli reference documentation`, so let me recap what we have today, to ensure we're all in the same page.
As an example, today if you want to learn how `docker run`, you have 3 options:
* `man docker run`
* `docker run --help`
*  Read the [commandline/run.md file](https://github.com/docker/docker/blob/master/docs/reference/commandline/run.md) at docs.docker.com or github.

As a side note, `docker run` has 4th page [reference/run.md](https://github.com/docker/docker/blob/master/docs/reference/run.md) that you can read at docs.docker.com or github. We can ignore this page, since the information here should be merged to any of the other 3 pages.

### The problem
These three pages are maintained by hand, and are independent of one another.
This leads to 2 problems:
* Documentation is outdated and doesn't reflect the code's current behavior
* You can get conflicting information between the 3 sources of information

### 	vdemeester proposed solution

We should definitely generate reference documentation from the code. If we decide that the output of running `man docker run` and `docker run --help` should be the same, then why just not kill one of them?

Looking at git for inspiration, it seems that running `man git commit` or `git commit --help` has the same behavior with the same content. It always opens the man page for that command.
They also generate html with the same content and look and feel, and [make it available online](https://git-scm.com/docs/git-commit).

My only concern with using a similar approach is ensuring we have good docs for platforms that don't support man. Currently Docker Toolbox on a Mac doesn't install any man pages for Docker. I'm also not sure what's the current behavior on Docker for Mac and Docker for Windows.

If we don't have a good solution for all the platforms where you can install Docker, I would prefer to kill the man pages, and migrate that information to `--help`. Even if the output is long, you can grep it, or pipe to a pager.

### Reference vs user guides
Also I feel that the core of this discussion is not so much to do with man pages or specific formats, but creating guidelines for:
* Reference docs - used by experienced users for getting "in the moment/in context" help.
* User guides - used by anyone to learn about a feature, or how to execute a workflow

For the `docker run` example, I think we're trying to cram too much information in a single place because we're not making any distinction between reference docs and user guides.
Since there is no clear guideline we end up spreading information everywhere, just to ensure users can find what they need.

**Comment by sfsmithcha** [comment]
cc: @mstanleyjones

**Comment by vdemeester** [comment]
I don't think it's relevant anymore (and if it still is, it's not on the correct repository)
