### ISSUE TITLE
Docker can't access internal network/private systems out of the box on Ubuntu

### ISSUE THREAD

**Issue by davethegr8** [moby/moby#25636]
Earlier today, I ran into a problem accessing internal systems (example: redacted.lan) from inside containers on Ubuntu 16 and 14. (For detailed analysis, see: http://stackoverflow.com/questions/38902786/docker-container-cant-find-domain-on-private-network/38902944) I installed Ubuntu 14 from a fresh iso, and installed docker following the instructions from https://docs.docker.com/engine/installation/linux/ubuntulinux/. When my containers were running, they were not able to access (ping/nslookup/and so on) any internal systems due to not having the correct nameservers.

It turns out that Ubuntu uses a dnsmasq server running on `127.0.1.1` by default, which when docker starts up is filtered out. Then, having no nameservers, docker applies the defaults of 8.8.8.8 and 8.8.4.4, meaning that any internal services that would otherwise be findable are no longer so.

The "solution" I was able to figure out was to disable dnsmasq in `/etc/NetworkManager/NetworkManager.conf` however it seems more like a hack than a fix. I'm opening the issue to - at the very least - help others be aware of this situation.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
$ docker info
Containers: 6
 Running: 3
 Paused: 0
 Stopped: 3
Images: 29
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 59
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 13.63 GiB
Name: redacted
ID: ASR7:FL5O:GMYV:35B2:25H2:4XAY:YPCX:G3UU:4DPH:PNBB:K2Z3:4MQH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu 14.04.4, 16.04

**Steps to reproduce the issue:**
1. Install a fresh copy of Ubuntu 14 
2. Install Docker
3. Start a container that accesses some private service not normally available by public DNS

**Describe the results you received:**

The container cannot access the private services

**Describe the results you expected:**

The container should be able to access the private services.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
If the resolver is using a localhost / loop back address then, indeed it cannot be used with the default bridge network (as trying to access localhost (or `127.0.1.1`) inside the container would be connecting to localhost inside the container).

For custom networks, that should work, because in that case, docker's embedded DNS server is used, which forwards requests from inside the container to the DNS server configured on the host.

All that said, if the internal services you're trying to connect to are also running on localhost, then it's not automatically possible for the container to connect to those (again, because it has its own networking namespace and localhost inside the container means; inside the container)


Let me close this ticket for now, as it looks like it went stale, and I don't think there's a bug here
