### ISSUE TITLE
Created several replicated services at once all stuck in "Preparing", can't rm them

### ISSUE THREAD

**Issue by slithernix** [moby/moby#25685]
**Output of `docker version`:**

```
[aws:~/docker-config/aws/bin] > docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 17
 Running: 4
 Paused: 0
 Stopped: 13
Images: 5
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 159
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: active
 NodeID: 604usrztaln0j420mkfuar2o2
 Is Manager: true
 ClusterID: 0in8wb1uz0t212nm2oiv4si2p
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot interval: 10000
  Heartbeat tick: 1
  Election tick: 3
 Dispatcher:
  Heartbeat period: 5 seconds
 CA configuration:
  Expiry duration: 3 months
 Node Address: 172.31.5.126
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-34-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.675 GiB
Name: larryland.alpha
ID: AOOM:42GB:UCOA:JRWN:MA6Q:ZPUT:XDSS:33DO:2CTV:A7TN:7Q24:XKN5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=amazonec2
Insecure Registries:
 127.0.0.0/8
```

**Steps to reproduce the issue:**
1. Create 7 replicated (10 replicas) services at once with options shown below
2. 
3.

**Describe the results you received:**

I created 7 services all similar to this (with different port mappings and image names of course):

```
docker service create \
  -p 8025:3000 \
  --with-registry-auth \
  --network=service_overlay \
  --replicas 10 \
  --restart-condition any \
  --name servicename \
  ${reporoot}/servicename:testing testing
```

And it shows none of the replicas up on any service (docker service ls). Now, some of these images do indeed have issues I need to fix but at least one of the services actually started, which can be seen if I run docker ps I can see the containers, yet replicas show 0/10 for that service. So then I had a look at docker service ps, and it shows that all the services are stuck in "Preparing".

So then I tried to remove the services and start working on adding them by hand instead of quick succession with a script, and I can't even get docker service rm to work, I get this:

```
[aws:~/docker-config/aws/bin] > docker service rm Servicename
Error response from daemon: rpc error: code = 4 desc = context deadline exceeded
**Describe the results you expected:**
```

**Comment by stychos** [comment]
Issuing same errors on random swarm managers and workers.

Docker version:
`Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64`

Docker info:
`Containers: 9
 Running: 9
 Paused: 0
 Stopped: 0
Images: 42
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 55
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: active
 NodeID: 6sip04yxxlw4eo2c7ngixdvkt
 Is Manager: true
 ClusterID: 8db2unr5tw2t5796bfcgrzvyj
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.0.1
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-57-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.63 GiB
Name: 5225.localdomain
ID: FBWS:USFC:NICI:IFPZ:GYA7:UKI7:V7SR:O5XQ:D7WO:ZIKH:T5AY:MFDE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 registry:5000
 127.0.0.0/8`

Also sometimes already running services get strange network errors － they can not connect to the node they are running on (but can access other services or outside internet).

Restarting "stucked" nodes docker daemons helps, but it is very bad solution because each my node provide hundreds of services.

**Comment by thaJeztah** [comment]
@stychos more information would really be welcome; error-logs of the daemons if they provide some information, error messages from the services, etc.

**Comment by stychos** [comment]
@theJestah big thanks for your patience and your help, I think it was my own fault for now － I tried to set up additional rules on the firewall and stucked with this unexpected behaviour. Think that my restrictive INPUT chain broke something within the Swarm intercommunication, node statuses was good, but services was not deploying on the nodes at all. Now with empty firewall rules and after Docker restart all seems to be work. Sorry for inconvenience.
Anyway, if I will stuck with this again, I will provide as much information as I can get.

**Comment by thaJeztah** [comment]
Thanks!

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
