### ISSUE TITLE
Swarm scheduling/constraints thoughts

### ISSUE THREAD

**Issue by kibs** [moby/moby#25922]
First off, I am danish, so my english may not be perfect :)

I have been setting up and running a 1.12 swarm in production the last two weeks or so. So far the experience has been really good, and besides some network issues, which seems solved by 1.12.1, it has been running smoothly.

I have been gathering some thoughts on what would help my scenario for scheduling containers on the correct host, and I would like to share those, so you can have at least one kind of real world usage, and take that into account when planning new features.

I am running a swarm of 4 nodes, 2 nodes have a label "frontend" set to "true", and 2 nodes have a label "backend" set to "true"

I am splitting my services based on if they are hit by clients, eg. rails/drupal using label frontent. And worker services like sidekiq, cron, nodejs workers using the label "backend"

For most frontend services i usually run them with replicas 2 in replicated mode, some frontend services have more replicas, so it will use more CPU cores on each node.

For most backend services i usually run them with replicas 1 in replicated mode, as it is okay if they are down for a period and doesn't perform a lot of work. But i do have some workers where I run them with eg. 4 replicas to utilize more CPU cores on the nodes.

This setup gives me a few problems. When i close a node, for upgrading or if they break, the other nodes pick up the missing replicas, and I end up exhausting the remaining nodes with too many containers. I then have to manually scale all the services up/down, which can be tricky and cumbersome, because i have many small services running.

As I see it, solutions for this could be

1) allow constraints with global mode (i think this works, but will show up as allocated), and also set the replicas count for each node, so I can set it up to always run eg. 2 replicas on all available "backend" nodes, no more or no less.

2) allow setting a max replicas number per node, when running in replicated mode. This will ensure that I don't exhaust the single node. But also lets me scale up a node when one node is down.

One last thing that is missing very much, is some kind of manual rebalance command, using docker scale can be a bit cumbersome when you have many resources.

**Comment by thaJeztah** [comment]
Thanks for the suggestions; there are multiple features suggested in this issue (which can make it difficult to track); looking for duplicates, I found:


- https://github.com/moby/moby/issues/26259 and https://github.com/moby/moby/issues/32054 for "max replicas (per node)"
-  https://github.com/moby/moby/issues/24469 and https://github.com/moby/moby/issues/24103 about "automatic" and "manually" rebalancing services
- for constraints on global services; these should now work; IIRC, there were some issues in earlier 1.12.x versions, but those should be addressed in later versions of docker (here's some existing issues around that https://github.com/moby/moby/issues/29724, https://github.com/moby/moby/issues/29384, https://github.com/moby/moby/issues/27464)


Let me close this issue, because I think all topics are covered by other issues, but feel free to comment here, and to participate in the issues I linked 👍
