### ISSUE TITLE
Nested bind mounts create empty directory on the host

### ISSUE THREAD

**Issue by jordanlewis** [moby/moby#26051]
**Issue Description**:
When using bind mounts that are nested on the container side, Docker erroneously creates empty directories that match the nested structure on the host side.

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 34
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null overlay bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: X63G:YAIL:6A3B:CAIG:RY7T:YD5J:56WM:OAJ3:MJ27:YSN4:6G5D:ZVJJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 30
 System Time: 2016-08-26T01:01:01.833759981Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: jordanlewis
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker for Mac, OS X El Capitan

**Steps to reproduce the issue:**
1. `mkdir -p /tmp/foo /tmp/bar`
2. `docker run --rm --volume="/tmp/foo:/foo" --volume="/tmp/bar:/foo/bar" ubuntu true`
3. `ls -la /tmp/foo`

**Describe the results you received:**
There is an empty directory named `bar` on the host in `/tmp/foo`.

**Describe the results you expected:**
`/tmp/foo` and `/tmp/bar` remain empty and untouched on the host.

**Additional information you deem important (e.g. issue happens only occasionally):**
This happens as well on Linux, but the erroneously created directory is also owned by root.

**Comment by cpuguy83** [comment]
What are you expecting to have happen here?

**Comment by cpuguy83** [comment]
btw, this happens because volumes are mounted in lexicographic order, so `/foo` is mounted, then `/foo/bar` is mounted. Since `/tmp/foo` is already mounted onto `/foo` by the time `/tmp/bar` is being mounted onto `/foo/bar`, the directory gets created in the bind instead of in the container rootfs.

**Comment by jordanlewis** [comment]
I'm expecting that the second bind doesn't create a directory on the host - `/tmp/foo/bar` should never be created.

Writing to `/foo/bar` in the container correctly writes to `/tmp/bar`. Why should `/tmp/foo/bar` be created at all?

**Comment by cpuguy83** [comment]
IIRC the container dir side is handled by runc. I wonder if runc could do a 2-phase approach... create all necessary dirs, then do the mounts.

**Comment by thaJeztah** [comment]
ping @mlaventure ^^

**Comment by iraklisg** [comment]
@jordanlewis you are making a good point here...
> Why should /tmp/foo/bar be created at all? 

@cpuguy83 IMHO the "2-phase approach" you are proposing seems pretty reasonable

**Comment by michaelbaudino** [comment]
I'm hit by this unexpected (from me, at least) behaviour too: I see some `root`-owned `node_modules` directories appearing in my codebase on host (mounted in container as `/app`) because I also mount `/app/node_modules` as a Docker volume.

To clarify, my `docker-compose.yml` contains (significant chunks only):

```yaml
volumes:
  node_modules: { driver: local }
services:
  my_app:
    volumes:
      - .:/app
      - node_modules:/app/node_modules
```

… so that NPM dependencies are persisted on a Docker volume.

After some research, it seems that Linux bind mounts (that power Docker volumes, even on MacOS when using HyperKit, afaiu) can only be created between 2 **existing** directories. This restriction can be seen in action on my regular Ubuntu desktop (I guess it behaves the same on pretty much all Linux distributions):

```shell
$ rm -rf /tmp/{src,dst}                                 # clean up any existing directories
$ mkdir -p /tmp/src                                     # create the source mount point
$ sudo mount --bind /tmp/{src,dst}                      # try to mount on a non-existing path
mount: mount point /tmp/dst does not exist              # huho, it fails :-/
$ sudo mkdir /tmp/dst                                   # create the destination mount point, then
$ sudo mount --bind /tmp/{src,dst}                      # try to mount again 
$ echo "Hello world!" > /tmp/src/hello                  # no error, let's create a file in the source directory to be sure
$ diff -s /tmp/{src,dst}/hello                          # check if the file is the same in the destination directory
Files /tmp/src/hello and /tmp/dst/hello are identical   # Yup, bind mount succeeded, for sure!
```

So I guess (I have zero knowledge of the Docker/Moby codebase, so it's only guesses) that the Docker engine first creates a directory to be used as destination mountpoint before mounting `/app/node_modules` (in your example @jordanlewis, that would be "before mounting `/tmp/bar` on `/foo/bar`").

This operation is very probably performed as `root` (since bind mounts are restricted to `root`, iiuc), thus resulting on a wild `root`-owned `node_modules` folder appearing in my codebase :sob: 

Could someone with higher knowledge than me confirm this? cc @cpuguy83 @thaJeztah

Also, can this be fixed or worked around? (I'm a bit pessimistic about that :disappointed:)

**Comment by michaelbaudino** [comment]
After a very quick and un-educated search around the codebase, this may be where the destination mount point is created:

https://github.com/moby/moby/blob/867a10aadeb56a508fb7ceeee21ab1ef45a506a6/volume/local/local.go#L159-L162

:thinking:

**Comment by cpuguy83** [comment]
@michaelbaudino The dir is created there, however when a container is created that uses that volume, if the volume is empty and the container dir it is being mounted to is not empty, docker will fill the volume with the data in that dir, and chown it to the uid/gid of that user.

**Comment by michaelbaudino** [comment]
OK, thanks for the precision @cpuguy83 :+1: I think people in this thread (including me) did not expect to see the destination mount point being created on host (and owned by `root`). Is that something that can be changed? Or just something we're going to have to live with?

**Comment by michaelbaudino** [comment]
OK, thanks for the precision @cpuguy83 :+1: I think people in this thread (including me) did not expect to see the destination mount point being created on host (and owned by `root`). Is that something that can be changed? Or just something we're going to have to live with?

**Comment by cpuguy83** [comment]
@michaelbaudino In your example, you are creating a bind mount to `/app`, and then a volume to `/app/node_modules`, therefore the volume dir for `/app/node_modules` would end up being bind mounted to `/app`, which itself is bind mounted to the host.

If it didn't work this way then the volume for `/app/node_modules` wouldn't be able to exist in the container because the bind mount for `/app` would mask it.

**Comment by michaelbaudino** [comment]
Right, thanks for the clarification again, @cpuguy83, I totally understand what's going on there :+1:

I guess I was just hoping (and other people in this thread too, maybe) that we could "mount a volume **as** `/app/node_modules`" (like in "it is seen as `/app/node_modules` in the filesystem") instead of "mount a volume **in** `/app/node_modules`" (that requires an existing `/app/node_modules`).

But that's just not how it works :man_shrugging: 

This issue could now be closed, fmpov, but since I'm not the OP, I'll let @jordanlewis do it, maybe :smiley:

**Comment by kwisatz** [comment]
It's odd, but I feel like this behavior has only changed recently, although this ticket is from 2016.
We always bind-mounted directories inside of other previously bind-mounted directories and never saw empty directories being created for those "inner" bind-mounts. Now suddenly this is happening all over the place?

**Comment by drzraf** [comment]
host$ mkdir test && touch test/native.txt
host$ mkdir storage && touch storage/non-native.txt
Create a docker volume "`foo`" (`driver: local, o: bind, device: *test*, type: fs`)

# Test 1:
```
host$ docker run -ti  -v foo:/tmp/guest alpine ls -la /tmp/guest
native.txt
```
# Test 2:
```
host$ mkdir test/submount && mount -o bind storage test/submount
host$ docker run -ti  -v foo:/tmp/guest alpine ls -laR /tmp/guest
submount/
native.txt
```

One would expect test 2 to to show "submount/non-native.txt" (considering the bind-mount in the host) instead of an empty directory. But that's forgetting about: [`Volumes use rprivate bind propagation, and bind propagation is not configurable for volumes.`](https://docs.docker.com/storage/volumes/)

# Propagation

According to https://docs.docker.com/storage/bind-mounts/#configure-bind-propagation, using `rshared` is possible.

# Test 3:
```
host$ docker run -ti  -v foo:/tmp/guest:rshared alpine ls -laR /tmp/guest
invalid mount config for type "volume": field BindOptions must not be specified
```

Although documentation says:
> Bind propagation refers to whether or not mounts created within a given bind-mount or **named volume**

# Test 4:
Using anonymous volumes:
```
host$ docker run -ti  -v test:/tmp/guest:rshared alpine ls -laR /tmp/guest
submount/non-native.txt
native.txt
```

**There is clearly an issue about named-volume not accepting bind-propagation (bindOption) field** even though documentation about bind-propagation mention them explicitly.

**Comment by cpuguy83** [comment]
The documentation is wrong.
Propagation settings are not supported on named volumes.

The part that you picked out is at odds even with the paragraph before it that mentions it is for binds only.

**Comment by hugochinchilla** [comment]
any plans to address this issue?

**Comment by thaJeztah** [comment]
I don't think there's anything to fix here, other than the mention of "named volumes" in the mount propagation docs (I just opened a pull request to fix that; https://github.com/docker/docker.github.io/pull/15725)

When mounting files or directories on Linux, a "mount point" is needed for the destination; basically, this means that if you want to mount directory `/foo/` to destination `/bar/`, then a directory must exist at `/bar` (the destination). The same applies when you want to bind-mount a _file_ (in which case the mount-point must be a file). The mount-point doesn't need to have any content (empty directory, or empty file is sufficient), but must exist.


Let me write down an example / explanation; to illustrate this (straight linux, without "docker").

```bash
mkdir example
cd example

# create a "host-directory" that is to be mounted inside the container, with a file and a directory inside it
mkdir host-directory
echo 'I am a file' > host-directory/file.txt
mkdir host-directory/subdirectory

# create the container's "filesystem"
mkdir container

# mount host-directory into the container (this is the equivalent
# of `-v /path/to/host-directory:/path-in-container`)
mount -t none -o bind host-directory container/path-in-container
```

This fails, because there's no mount-point for the mount inside the container, and an error is shown (`mount: container/path-in-container: mount point is not a directory.`). So the mount-point has to be created first before we  mount;

```bash
mkdir container/path-in-container

# try the mount again, and this time it works
mount -t none -o bind host-directory container/path-in-container
```

After this, the mounted files now show up inside the container

```bash
ls -l container/path-in-container/
# total 8
# -rw-r--r-- 1 root root   12 Sep 23 11:07 file.txt
# drwxr-xr-x 2 root root 4096 Sep 23 11:14 subdirectory
```

The file and directory shown above are the _same_ as the one inside `host-directory`, but now shown from the mount. Any changes made in `container/path-in-container/` will also show up in `host-directory` and vice-versa;

```bash
mkdir container/path-in-container/another-subdirectory

ls -l container/path-in-container/
# total 12
# drwxr-xr-x 2 root root 4096 Sep 23 11:17 another-subdirectory
# -rw-r--r-- 1 root root   12 Sep 23 11:07 file.txt
# drwxr-xr-x 2 root root 4096 Sep 23 11:14 subdirectory

ls -l host-directory/
# total 12
# drwxr-xr-x 2 root root 4096 Sep 23 11:17 another-subdirectory
# -rw-r--r-- 1 root root   12 Sep 23 11:07 file.txt
# drwxr-xr-x 2 root root 4096 Sep 23 11:14 subdirectory
```

So, combining that knowledge with the case where the `node_modules` volume is mounted at `app/node_modules` (`path-in-container/node_modules/` in the example here);

```bash
# say, this is the (empty) `node_modules` volume to mount
mkdir node_modules_volume

# which is to be mounted at container/path-in-container/node_modules
# so a mountpoint must be created if it doesn't exist
mkdir -p container/path-in-container/node_modules

# and then mounted in the container
mount -t none -o bind node_modules_volume container/path-in-container/node_modules
```

After this; the `node_modules` that's mounted shows up inside the container;

```bash
ls -l container/path-in-container/
# total 16
# drwxr-xr-x 2 root root 4096 Sep 23 11:17 another-subdirectory
# -rw-r--r-- 1 root root   12 Sep 23 11:07 file.txt
# drwxr-xr-x 2 root root 4096 Sep 23 12:57 node_modules
# drwxr-xr-x 2 root root 4096 Sep 23 11:14 subdirectory
```

And files can be stored inside it;

```bash
echo "I am a node_module file" > container/path-in-container/node_modules/some_module_file.txt

ls -l container/path-in-container/node_modules/
# total 4
# -rw-r--r-- 1 root root 24 Sep 23 12:59 some_module_file.txt
```

Which will be stored inside the volume:

```bash
ls -l node_modules_volume
# total 4
# -rw-r--r-- 1 root root 24 Sep 23 12:59 some_module_file.txt
```

But the _mount point_ (empty directory that was created), will show up in the "outer" bind-mount;

```bash
ls -l host-directory/
# total 16
# drwxr-xr-x 2 root root 4096 Sep 23 11:17 another-subdirectory
# -rw-r--r-- 1 root root   12 Sep 23 11:07 file.txt
# drwxr-xr-x 2 root root 4096 Sep 23 12:57 node_modules
# drwxr-xr-x 2 root root 4096 Sep 23 11:14 subdirectory


ls -l host-directory/node_modules/
# total 0
```

**Comment by thaJeztah** [comment]
Let me close this ticket because of the above, but feel free to continue the conversation

**Comment by drzraf** [comment]
Could you please read again my previous comment about bind-mount / mount-propagation impossibility (for named volume)?

If no workaround exist, then it's a bug that should be resolved rather than closed.

**Comment by thaJeztah** [comment]
Mount propagation is not supported for named volumes, only for bind-mounts (from that documentation);

> Bind propagation defaults to `rprivate` for both bind mounts and volumes. It is only configurable for bind mounts, and only on Linux host machines.

The "or named volume" part in the second paragraph shouldn't have been there https://github.com/moby/moby/issues/26051#issuecomment-739115798 (and what I removed in https://github.com/docker/docker.github.io/pull/15725)

In either case, it would be a separate issue from the one originally reported in this ticket, which was about the empty directories being created (which are the mount-points I described in my example)

**Comment by hugochinchilla** [comment]
Thanks for all the replies
