### ISSUE TITLE
Galera cluster with docker swarm mode(ver. 1.12)

### ISSUE THREAD

**Issue by Spectrik** [moby/moby#26568]
Hello,

I want to deploy galera cluster on 3 physical nodes and i want to use docker's native clustering(new swarm mode)

When i run the service like:
`docker service --create  --replicas 3 ... galera_image`

I get 3 containers running that image. That is OK. Problem is that i do not know how to configure the cluster i mean what do i put in the list of nodes?(next line)

wsrep_cluster_address=gcomm://IP1, IP2, IP3.

Because when i create service, containers gets **_random_** IP from network's range. I also cant use internal DNS hostname because that resolves to one Virtual IP and i need 3 IPs

I got idea to create three services. Each of them would be galera_cluster node and then i could use hostnames in cluster configuration. But that's awkard.

Is there another solution? Or workaround? Or anything? :)

Thank you for your help.

Docker version: 

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64
```

Docker info:

```
Containers: 6
 Running: 3
 Paused: 0
 Stopped: 3
Images: 17
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 44
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay host bridge
Swarm: active
 NodeID: cmgj06kbylciqb7r805gtokuz
 Is Manager: true
 ClusterID: 0rxc8xabgifxogfax00yghtur
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.30.0.0
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.769 GiB
Name: test0.ho.xeb.is
ID: ZNQM:NPWJ:ONE2:O74W:QAY3:GC3G:XK2L:O3XR:VWWD:SG7A:JF4G:DCPZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8
```

**Comment by cpuguy83** [comment]
Not really a good way to run clustered applications as a single replicated service.
I suspect in the future we'll have DNS records for something like `<slot num>.<service name>` or a way to discover all IP's in the network.

I know we have an issue tracking this, but can't seem to find atm.

**Comment by Richard-Mathie** [comment]
you can get all IPs on the network with a dns lookup
`nslookup tasks.myservice`
see: https://github.com/docker/docker/blob/master/docs/swarm/networking.md#use-swarm-mode-service-discovery

**Comment by niau** [comment]
@Spectrik you can follow the path towards the 3 separate services. In this case it will work with replication factor of one and then build the cluster between them. In the end it looks like the replicas solution is more for services that don't share too much state between each other which is not exactly what you are looking for. 

To do so you will obviously need also a separate overlay network in which your services has to be added. For more information on why you can check that ticket #26542. 

Since you might need the hostname to be static again you are not the only one with such request so you can actually build a package for yourself based on that pull request https://github.com/docker/docker/pull/25437 or simply wait for the feature to become part of the master or a new release. 

If you do so you can do the following. 

```docker network create --driver overlay galera_net_1```

Then 

```for I in `seq 1 3`; do docker service create --network galera_net **--hostname galera$I** --name galera$I --hostname galera$I -p 3306$I:3306/tcp galera; done ```

Finally from each of the containers no matter where they will go you will be able to do so 

nslookup galera$I will resolve you the permanent VIP of the service

telnet galera$I 3306 will connect you to the right galera cluster node and this will be permanent no matter where the swarm will spawn your container.  

I think the rest will be easy. Also you can easily scale up and down your galera cluster by adding or removing swarm services.

**Comment by Spectrik** [comment]
@niau thank you for this great answer.

**Comment by niau** [comment]
@Spectrik always glad to help.

**Comment by colinmollenhour** [comment]
I'm working on a Galera managed as a single service here: https://github.com/colinmollenhour/mariadb-galera-swarm

I don't have it running just yet but the idea is to create a "seed" service and then create the regular service which joins the seed and then remove the seed and replace it with a regular node. Inspired by the Kontena mariadb example.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
