### ISSUE TITLE
Roadmap for `docker deploy` and Bundles

### ISSUE THREAD

**Issue by mgoelzer** [moby/moby#26876]
## Bundles

Bundles are a multi-image redistributable format that describe multi-container distributed applications (or stacks) running on Docker.  A bundle is akin to a “multi-image image,” and deploying it gives rise to a “stack” consisting of several communicating microservices.  Conceptually, this is analogous to Docker images today:

|  | Human-editable Description | Binary Artifact | Running Instantiation |
| --- | --- | --- | --- |
| Bundle | `docker-compose.yml` | Bundle | Stack |
| Image | Dockerfile | Image | Container |

In June 2016, Docker announced Distributed Application Bundle (DAB) files, a predecessor to bundles, as part of Docker 1.12.  DAB is the file format used internally to represent bundles.

This issue outlines the roadmap for bundles, the file formats involved, how they relate to one another, how bundles relate to existing multi-container tools like Docker Compose and how the CLI/API will be affected.
## Docker 1.12 Concepts:  Swarm Mode, Bundles and `docker deploy`

**Engine swarm mode orchestration (Docker services).**  Since Docker 1.12, Engine has supported built-in container orchestration through the addition of Docker Services (`docker service` and related subcommands).  A Service in Docker is a replicated set of 1 or more identical containers.  Loosely speaking, a Service in Docker models the concept of a “microservice” within a larger application.

**Bundles.**  A bundle can be generated from a Compose v2 file.  The bundle itself is a redistributable binary format, and in the future `docker-compose` will be just one possible build tool.  When a bundle is deployed to a cluster, its running instantiation is called a stack.

**`docker deploy`.**  This subcommand is used in 1.12 to deploy a Distributed Application Bundle (DAB, or simply bundle) file.
## Roadmap:  Compose files, Bundle files, Daemon-side Bundles and `docker stacks`

As of Docker 1.12, [`docker-compose`](http://github.com/docker/compose) is currently the tool used to create bundle files.  A bundle file is generated from a Compose v2 file using `docker-compose bundle [-f docker-compose.yml]`.  It is then deployed using the `docker deploy` subcommand:  `docker deploy --file mystack.dab`.  A more complete description of this 1.12 functionality is available [here](https://github.com/docker/docker/blob/master/experimental/docker-stacks-and-bundles.md).

In Docker 1.13/1.14, our intention is to shift away from using `docker-compose` to generate bundles.  Instead, the `docker` CLI itself will generate bundles from Compose v2 input files using a new `docker bundle` subcommand.  Example:

`docker bundle build [-f COMPOSE_FILE] -t BUNDLE`

In addition, Docker will move toward a system in which bundles are stored and managed internally by the Engine rather than as user-managed `.dab` files.  For instance, the user will be able to push and pull bundles:

```
docker bundle push BUNDLE                   (see below)
docker bundle pull BUNDLE                   (see below)
```

Other `docker bundle` commands like `bundle ls`, `bundle tag` and `bundle rm` will allow the user to manage these daemon-side bundles.

Deployment and management of running stacks will be done using the top level `docker stack` subcommand (which already existed in 1.12 and will be extended in 1.13/1.14).  Deployment of a bundle to instantiate a stack will be done using `docker stack deploy`; `docker deploy` will be aliased to this command for backward compatibility.  For management, existing commands such as `docker stack ps`, `docker stack inspect` and `docker stack rm` will be available to view and manipulate running stacks.
## Example Workflows

Running a stack from a Compose file

```
docker bundle build [-f COMPOSE_FILE] -t BUNDLE
docker stack deploy [-c STACK_CONFIG] BUNDLE STACK
```

Running a stack from a registry

```
docker stack deploy [-c STACK_CONFIG] BUNDLE STACK
```

**Comment by thaJeztah** [comment]
Thanks @mgoelzer. Perhaps we should add this to the ROADMAP.md (I think that was mentioned elsewhere); https://github.com/docker/docker/blob/master/ROADMAP.md. wdyt?

**Comment by mgoelzer** [comment]
@thaJeztah Yes, I want to update `ROADMAP.md` more broadly.  I think I should aim to move this issue's content into an updated `ROADMAP.md` and then close out this issue in favor of `ROADMAP.md`

**Comment by nathanleclaire** [comment]
Thanks Mike for the detailed summary.  Got a couple questions:

1. So I understand that one of the goals of DAB is to prevent environment-specific configuration from leaking into descriptions of "stacks", but inevitably you will have to set this somehow -- how?

2. DAB is attempting to solve portability problems but it is relying on a remote registry to do so.  _Relying on a remote registry is itself something which cannot be safely done portably_.  Each network has its own configuration and idiosyncrasies.  Corporate firewall / proxy / VPN and more is common and _will_ break DAB.  Is "it's portable if your network is configured wide open" really portable? 

2. Have you considered that mixing in Compose V2 to all of this might end up causing more trouble than it solves?  I know it's tempting ("there are so many existing Compose files"), but how many of those existing applications can _actually_ be translated into bundle files without a ton of work?  (And if you have to re-work your Compose YAML significantly to shoehorn it into DAB, what are we gaining here vs. creating a new spec altogether?)

  Consider a beginning user's journey with Compose.  It [_almost always_ starts and ends with environment-specific config](https://docs.docker.com/compose/gettingstarted/#/step-3-define-services) and, in my experience, this extremely rapidly becomes habit for users writing Compose files.  If you want to take this very simple Compose file and turn it into a DAB you run into problems almost immediately.
    1. `build` key doesn't work, only `image`.  OK, I guess [these 32,000](https://github.com/search?utf8=%E2%9C%93&q=filename%3Adocker-compose.yml+build&type=Code&ref=searchresults) Docker Compose files cannot be translated to DAB without modification?  So, at least [roughly 50% of existing Docker Compose files on GitHub](https://github.com/search?utf8=%E2%9C%93&q=filename%3Adocker-compose.yml&type=Code&ref=searchresults) will not translate to DAB without modification.
    2. `volumes` are ignored (and [~39,000 / 60000 total Compose files on GitHub](https://github.com/search?utf8=%E2%9C%93&q=filename%3Adocker-compose.yml+volumes&type=Code&ref=searchresults) seem to reference `volumes`!).  So what do we win by using Compose for this?  Huge swaths of Compose files will not work out of the box.
    3.  Looks like in the generated DAB a `network` is added in?  How exactly is that portable?  It's not safe to assume that `docker network` setup looks the same everywhere... There might not be a bridge, there might be overlays configured a particular way by an administrator, there might be specific plugins the user wants, and so on.
4.  Why _not_ just have a Compose V3 file which maps directly to `docker service` flags and related mounts, etc.?  That'd be very easy to reason about (almost direct translation) and it's the simplest possible thing, so why not?  Personally I'm chomping at the bit to just get __a YAML file which maps almost directly to `docker service` `create`/`update`__.  The current proposal, instead of focusing on simplicity, adds at least 2 or 3 more steps into the process.  (Either this, or a new "schema file" defining [the types and arguments for a stack create](https://glyph.twistedmatrix.com/2016/08/defcontainer.html) and a file per-environment to define those arguments).
5. As for the content addressability aspect, shouldn't operators who want that run images with [Docker content trust](https://docs.docker.com/engine/security/trust/content_trust/#/image-tags-and-content-trust) enabled?  Why force content addressability in the deployment spec layer?  Without actual cryptographic identity verification, what does having these image content hashes in a JSON file win us?  Wouldn't mucking with a plaintext JSON file be comparatively pretty easy for a motivated attacker?

The current DAB method does have some interesting properties, however I have a hard time imagining myself selling this to a potential user: "DAB is great!  To use it, just write a Compose file, and then immediately translate that Compose file to a new format, since the Compose file format is not supported.  Oh, you have one already? Nice, it'll still need to be modified heavily to be translatable to DAB ...  Oh, and make sure your images are pushed first.  That's important, gotta have the images pushed, can't experiment with this technology locally at all.  And also you are going to have to define volumes and networks somehow after the fact anyway."

**Comment by mgoelzer** [comment]
Ping @dnephin

**Comment by dnephin** [comment]
>  So I understand that one of the goals of DAB is to prevent environment-specific configuration from leaking into descriptions of "stacks", but inevitably you will have to set this somehow -- how?

Currently by doing `docker service update`, which I don't think is a good way of doing it. I personally think we need a second format for including all the non-portable stuff. This second "settings" file wouldn't be distributed from a registry, but would be managed by the local operator. We could have tooling to create a default "settings" file based on hints provided from a bundle. #26748 is an issue for this.

>  Is "it's portable if your network is configured wide open" really portable?

This is fixed by our work to move bundles to be an "internally managed" object of the engine. The image layers referenced from a bundle must be on the same registry as the bundle manifest, so if you can fetch the bundle, you can fetch all the layers required to run the services in the bundle.

> Have you considered that mixing in Compose V2 to all of this might end up causing more trouble than it solves?

Yes. I agree with many of your points. I personally think that eventually we need a more appropriate "source" format, but right now that format is Compose v2, and creating 3 formats all at once seems like a bad idea.  For now we're focusing on the bundle format. Once that's stabilised we can look at improving the source format , and making it more appropriate for translation into a bundle.

> what are we gaining here vs. creating a new spec altogether?

Time to get the source format right. If we build it all at once there are too many things in motion for anyone to make use of it.

> Looks like in the generated DAB a network is added in? How exactly is that portable?

It just uses the default network driver configured by the engine. I believe all networks should provide the same things to containers. 

> Why not just have a Compose V3 file which maps directly to docker service flags and related mounts, etc.? 

I wouldn't be surprised if that's what we end up with. Right now Compose does not work with swarm mode, so it wouldn't make sense to create a format that doesn't work with the tool that reads it.

> As for the content addressability aspect, 

You lost me with this one, but I think the idea is that the bundle itself will be signed, you don't have to worry about  signing the individual images within it.

> The current DAB method does have some interesting properties, however I have a hard time imagining myself selling this to a potential user

Yes, that's why they are experimental. They still need work to be more useful. Some of that work will be done for 1.13. Most of that work needs to be completed before it can leave experimental.

**Comment by nathanleclaire** [comment]
> I wouldn't be surprised if that's what we end up with. Right now Compose does not work with swarm mode, so it wouldn't make sense to create a format that doesn't work with the tool that reads it.

To be clear, I wasn't suggesting that we have Compose read in the "V3" files, but rather a new YAML format similar to the existing stuff that `docker` CLI itself reads in and translates directly to `service create` and/or `update`.

> You lost me with this one, but I think the idea is that the bundle itself will be signed, you don't have to worry about signing the individual images within it.

Why would DAB would take this responsibility though?  Why would a tool for orchestrating containers/tasks concern itself with image provenance?  And what exactly is a bundle in this context?  The images themselves ? The DAB file?

> It just uses the default network driver configured by the engine. I believe all networks should provide the same things to containers.

What about things like network IPAM config (https://docs.docker.com/compose/compose-file/#/ipam)?  And plugins?  If networks are bundled that (plugin) will be yet another dependency that the bundle will need present in order to be executable right?

**Comment by mgoelzer** [comment]
@nathanleclaire 

1, 3 and 4.  I agree with you.  I too think we need a Compose-like YAML format for docker services.  However, bundles are trying to solve a somewhat different problem, which is _how do you define a multi-tier application in an abstract enough way that it is consistently portable across environments?_ 

2.  But don't you think the concept of "portability" implies that you've successfully obtained the bundle already?  It will always be the case that if you cannot obtain some artifact (dab, jar, whatever) then you cannot run it in that environment.

5.  Good point.  The hash here should never be used for cryptographic verification because it's not a signature.  The hash ensures reproducibility of the bundle -- e.g., `redis:latest` may be different in different environments but `redis:latest@sha256:1234567890abcdef` is unambiguous in all environments.  

But for DCT, you'd want signatures on both the bundle manifest and the images so that you can revoke them independently.  For example, if an image signature gets revoked, the bundle as a whole should not run, even though the sha256 hash will still be correct.

3. (iii) I agree the abstraction sometimes gets leaky around networks, especially for enterprise configurations.  Ideally, a container network is just some software-defined abstraction that can be realized on top of any properly configured environment.  In practice, this is not the case because some network drivers want to do things like make container IP allocation decisions based on what physical node they are running on.  This is a challenge for portability in general.

**Comment by nathanleclaire** [comment]
> 1, 3 and 4) I agree with you. I too think we need a Compose-like YAML format for docker services. However, bundles are trying to solve a somewhat different problem, which is how do you define a multi-tier application in an abstract enough way that it is consistently portable across environments?

I think that maybe where it needs to head is that the "bundle" file defines a "schema" which the running end needs to "invoke" with the correct parameters.  Dan I think kind of hints at this in one of his comments, and it would fit in with the Glyph article I linked's line of thinking (["A Container is a Function Call"](https://glyph.twistedmatrix.com/2016/08/defcontainer.html)).

I just haven't seen anything in the current bundle spec indicating things like "this container must have a volume mounted in at `/foo`".  Not saying it's not planned, just don't see any of that kind of detail today so far.  And sketching out blueprints how these kinds of things might work or look like always unearths nasty little corner cases that weren't considered in the original vision.

> But don't you think the concept of "portability" implies that you've successfully obtained the bundle already? It will always be the case that if you cannot obtain some artifact (dab, jar, whatever) then you cannot run it in that environment. 

So will users be able to obtain _just_ a bundle artifact and execute it independent of distributing the bundles and/or their images via registry?  i.e., will there be a registry-free workflow possible like there is for Docker images (`docker save`/`docker load`).  Because the bundle idea seems inherent coupled to Engine internals and to the registry today.

> The hash ensures reproducibility of the bundle -- e.g., redis:latest may be different in different environments but redis@sha256:1234567890abcdef is unambiguous in all environments

Maybe a little nitpicky, but wouldn't this be better solved by immutable image tags? Sure, `redis@sha256:1234567890abcdef` might tell me as an operator that I'm unable to obtain the exact image I'm intended to run.  But how does that help me?  Think about git tags, for instance.  Which is more useful: Me handing you `e18a9193d49de4a45ba4b1b6379cad7775481cd2` and telling you that's the docker/machine revision you want, or me telling you that you want the `v0.8.2` tag?

> In practice, this is not the case because some network drivers want to do things like make container IP allocation decisions based on what physical node they are running on. This is a challenge for portability in general.

Right, so how will bundle solve it?

Thanks for your commentary and willingness to answer questions @dnephin @mgoelzer !!

**Comment by techninja1008** [comment]
Any progress?

**Comment by cpuguy83** [comment]
@techninja1008 deploy from compose files is in 1.13-experimental.

**Comment by techninja1008** [comment]
@cpuguy83 Sorry, where can I find this?

**Comment by cpuguy83** [comment]
@techninja1008 I believe docs are still pending for this, but you can get the 1.13 RC from test.docker.com.

**Comment by dexterbt1** [comment]
I think the ideas and design decisions put forward by @nathanleclaire are worth exploring:

1. a "schema"for "invoking" or setting up the whole stack in a environment. Is this like "rancher-compose" territory?
2. volume mounts, other edge cases
3. registry-free / independent artifact. I would wish this to be easily versioned and managed in git, or something like what redspread.com are doing. 
4. tags instead of hashes

**Comment by frjaraur** [comment]
We need volumes in application bundle format and we are now in the strange situation where we can not deploy applications to swarm clusters (swarm mode) using docker-compose (multihost needed) and neither application bundle (volumes needed). What can we use to deploy applications now?

**Comment by thaJeztah** [comment]
@frjaraur you may be interested in the stack deploy docker-compose support, which will be in docker 1.13 (release candidates are currently available for testing); see this PR; https://github.com/docker/docker/pull/27998, and documentation https://github.com/docker/docker.github.io/pull/716

**Comment by frjaraur** [comment]
@thaJeztah Many Thanks I will take a look because volumes are a MUST in our environment.

**Comment by frjaraur** [comment]
Am I missing something? I have tried this compose file..
version: "3"

services:
  # load balancer
  lb:
    image: hopla/mentorsday-lab:simplestlb
    environment:
      - APPLICATION_ALIAS=simplestapp
      - APPLICATION_PORT=3000
    networks:
      simplestdemo:
          aliases:
          - simplestlb
    ports:
      - 8080:80

  db:
    image: hopla/mentorsday-lab:simplestdb
    environment:
        - "POSTGRES_PASSWORD=changeme"
    networks:
       simplestdemo:
        aliases:
          - simplestdb
    volumes:
      - PGDATA:/var/lib/postgresql/data"

  app:
    image: hopla/mentorsday-lab:simplestapp
    environment:
      - dbhost=simplestdb
      - dbname=demo
      - dbuser=demo
      - dbpasswd=d3m0
    networks:
       simplestdemo:
        aliases:
          - simplestapp
    depends_on:
      - lb
      - db

networks:
  simplestdemo:

volumes:
  PGDATA:
    driver: local

Doesn't have any problem during deploying..

ubuntu@swarmnode1:/tmp$ docker stack deploy -c test.yml test
Creating network test_simplestdemo
Creating network test_default
Creating service test_lb
Creating service test_db
Creating service test_app

I watch for DB service and its volume...

ubuntu@swarmnode1:/tmp$ docker stack ps test
NAME                     IMAGE                             NODE        DESIRED STATE  CURRENT STATE               ERROR  PORTS
test_app.1.et0c3v5i2d09  hopla/mentorsday-lab:simplestapp  swarmnode1  Running        Running about a minute ago         
test_db.1.3s524fw4d2rn   hopla/mentorsday-lab:simplestdb   swarmnode2  Running        Running 10 seconds ago             
test_lb.1.qpp80aaygehd   hopla/mentorsday-lab:simplestlb   swarmnode3  Running        Running about a minute ago       

As task is deployed on node2, I went there but there isn't anything on volume assigned directory??

ubuntu@swarmnode2:~$ docker volume ls 
DRIVER              VOLUME NAME
local               test_PGDATA
ubuntu@swarmnode2:~$ docker volume inspect test_PGDATA
[
    {
        "Driver": "local",
        "Labels": {
            "com.docker.stack.namespace": "test"
        },
        "Mountpoint": "/var/lib/docker/volumes/test_PGDATA/_data",
        "Name": "test_PGDATA",
        "Options": {},
        "Scope": "local"
    }
]


root@swarmnode2:~# ls -lart /var/lib/docker/volumes/test_PGDATA/_data/
total 8
drwxr-xr-x 3 root root 4096 Dec 13 12:48 ..
drwxr-xr-x 2 root root 4096 Dec 13 12:48 .


Am I doing something wrong here or volumes aren't working as expected?
Many Thanks,

**Comment by thaJeztah** [comment]
@frjaraur I think there's a typo in your docker-compose file, as I see a missing quote before `PGDATA`;

``
    volumes:
      - PGDATA:/var/lib/postgresql/data"
``` 

I tried to reproduce your issue with a minimum version of your example;

```yaml
version: "3"

services:
  db:
    image: postgres
    environment:
        - "POSTGRES_PASSWORD=changeme"
    volumes:
      - "PGDATA:/var/lib/postgresql/data"

volumes:
  PGDATA:
    driver: local
```

```bash
docker stack deploy -c docker-compose.yml test


docker run --rm -v test_PGDATA:/foo alpine ls -la /foo
total 128
drwx------   19 999      root          4096 Dec 13 12:47 .
drwxr-xr-x   25 root     root          4096 Dec 13 12:50 ..
-rw-------    1 999      ping             4 Dec 13 12:47 PG_VERSION
drwx------    5 999      ping          4096 Dec 13 12:47 base
drwx------    2 999      ping          4096 Dec 13 12:48 global
drwx------    2 999      ping          4096 Dec 13 12:47 pg_clog
drwx------    2 999      ping          4096 Dec 13 12:47 pg_commit_ts
drwx------    2 999      ping          4096 Dec 13 12:47 pg_dynshmem
-rw-------    1 999      ping          4490 Dec 13 12:47 pg_hba.conf
-rw-------    1 999      ping          1636 Dec 13 12:47 pg_ident.conf
drwx------    4 999      ping          4096 Dec 13 12:47 pg_logical
drwx------    4 999      ping          4096 Dec 13 12:47 pg_multixact
drwx------    2 999      ping          4096 Dec 13 12:47 pg_notify
drwx------    2 999      ping          4096 Dec 13 12:47 pg_replslot
drwx------    2 999      ping          4096 Dec 13 12:47 pg_serial
drwx------    2 999      ping          4096 Dec 13 12:47 pg_snapshots
drwx------    2 999      ping          4096 Dec 13 12:47 pg_stat
drwx------    2 999      ping          4096 Dec 13 12:49 pg_stat_tmp
drwx------    2 999      ping          4096 Dec 13 12:47 pg_subtrans
drwx------    2 999      ping          4096 Dec 13 12:47 pg_tblspc
drwx------    2 999      ping          4096 Dec 13 12:47 pg_twophase
drwx------    3 999      ping          4096 Dec 13 12:47 pg_xlog
-rw-------    1 999      ping            88 Dec 13 12:47 postgresql.auto.conf
-rw-------    1 999      ping         22233 Dec 13 12:47 postgresql.conf
-rw-------    1 999      ping            37 Dec 13 12:47 postmaster.opts
-rw-------    1 999      ping            85 Dec 13 12:47 postmaster.pid
```

**Comment by thaJeztah** [comment]
Having said that, it's strange that no error was produced that the YAML was invalid. Doing a quick check on http://www.yamllint.com, showed that it may be interpreted as this;

<img width="502" alt="screen shot 2016-12-13 at 13 55 01" src="https://cloud.githubusercontent.com/assets/1804568/21141121/c753e286-c13b-11e6-919f-9ea601c560e3.png">

**Comment by frjaraur** [comment]
@thaJeztah You are right, Thanks!!. No errors found but there was an error on YAML (missing "). It's working fine.

**Comment by Yajo** [comment]
The lack of support for `build` is a little bit confusing. What am I supposed to do if I need to build the image?

I guess right now I need 2 `docker-compose.yaml` v3 files and do that in 3 steps:

1. Build images from `build.yaml`.
2. Push them to a registry.
3. Deploy from `deploy.yaml`, where I use the images from that registry.

I understand images should be pinned, but this duplicity is not much friendly. At least with DAB it was Docker compose who generated the 2nd file...

Isn't it easier that Swarm nodes get ability to share images?

I mean, if I deploy a compose file with built services, it could:

1. Build the image as you normally would do.
3. Tag it as *internal* somehow.
2. Deploy the stack in any node.
3. If the node doesn't have the image locally available and knows it's a *internal* one, instead of asking a registry for it, it asks to a manager node.
4. The manager node searches for the image across the Swarm managers and tells the worker which manager has the image it wants.
5. The worker asks for the image to the manager that has it.
6. The manager gives the image to the worker.
7. Worker deploys.

This would be really easy from the developer perspective and would allow moving to Swarm without the hassle of setting up a registry, build and push automations, etc.

**Comment by teohhanhui** [comment]
It can be achieved from the same `docker-compose.yml` (or `docker-stack.yml`; naming...). You can specify both `build` and `image` keys for your services. `docker stack deploy` just ignores the `build` key so there's no harm there.

Steps:

1. `docker-compose build`
2. `docker-compose push` or `docker push`
3. `docker stack deploy`

Of course, if you want to pin to specific hashes, just make a copy of the `docker-compose.yml` and update the `image` keys?

**Comment by Yajo** [comment]
Oh interesting solution, I did not know about it.

It helps, but I still think https://github.com/docker/docker/issues/26876#issuecomment-290896964 would be better, with less manual steps and more straightforward.

**Comment by composer22** [comment]
Docker stack deploy is working like a charm in 17+ and I love it.  But this roadmap is not only old, but doesn't address a path to deployment of stacks through the API. Even if dockerd needs to shell out as a solution, there should be an API hook somewhere in there so the deployment of stacks doesn't have to be performed by some outside service or user having to SSH into the box to run CLI to perform this same function. Let's get real here or at least propose or suggest another way to perform this. Else the feature is not very useful as a production solution.

**Comment by saulshanabrook** [comment]
To make what @composer22 concrete, to deploy a docker stack from Travis CI, you have to SSH into your manager node, like this: https://github.com/vfarcic/docker-flow-cron/blob/1988f134fcc863b0832561121c1428f76f35db83/.travis.yml#L31-L32

**Comment by cpuguy83** [comment]
@saulshanabrook Why? Why would having it on the API make it so you don't have to SSH?

**Comment by saulshanabrook** [comment]
@cpuguy83 Yeah I wouldn't have to SSH and store SSH keys in the CI.  Also, I wouldn't have to copy over the `docker-compose.yml` file to the swarm master and store it somewhere temporarily.

**Comment by cpuguy83** [comment]
@saulshanabrook But why would this be the case? All you need is a docker client.

**Comment by cpuguy83** [comment]
What I'm getting at is, why do you have to SSH to deploy a stack but not to `docker service create`, or `docker run`?

**Comment by saulshanabrook** [comment]
I see what you mean. I hadn't considered it in the context of those other commands. I am not using them in my current workflow, so I don't have an opinion on whether it makes sense to put them on the API. I just got this working the other day, so maybe it is premature for me to make suggestions on what could improve the workflow. I will keep playing with my setup and see what comes up.

**Comment by cpuguy83** [comment]
@saulshanabrook My main point is, everything that is done by the docker client is on the API. `stack deploy` is a client-side feature that calls out to the network, services, and volume APIs for you.

**Comment by saulshanabrook** [comment]
@cpuguy83 So are you saying that if I want to run `stack deploy` in Travis CI, without SSH, I could connect to the docker host remotely with `docker -H ...`?

**Comment by kinghuang** [comment]
@saulshanabrook Yes, that's exactly how it works. There's no reason to ever SSH into a Docker node, manager or not. I typically set the `DOCKER_HOST` environment variable in my CI jobs along with tls keys as appropriate to deploy to remote Docker hosts.

**Comment by AkihiroSuda** [comment]
Any update about `docker bundle pull`?

**Comment by danielwray** [comment]
Hi,

Due to the stack management being on the client side is the recommended approach for stack deployment to replicate the multiple calls to service, network, volume creation and group them all via a namespace label when creating a management service to perform this type of 'micro-service' deployment using the SDK's / Docker API's?

Does Docker manage the state of services under a stack without having the YAML file on disk i.e. can a YAML file be pulled down, a stack deployed, and then the file removed?

**Comment by BretFisher** [comment]
See the `docker stack deploy` help for info on streaming file input into the command, that way you can deploy a stack through a ssh one-liner: https://docs.docker.com/engine/reference/commandline/stack_deploy/

**Comment by KylePreuss** [comment]
@cpuguy83 I believe the main benefit of supporting docker stack commands through the API is to simplify deploying application stacks from API clients. I'd like to use the [Docker.DotNet](https://github.com/Microsoft/Docker.DotNet) package to do a stack deploy on a swarm manager from a remote C# application. The alternative is to either do all the volume, network, container creation manually using the API (huge step backwards,) require Docker to be installed on the machine running the C# application and then spawn a shell for running the appropriate commands, or to SSH into the swarm manager and run the commands (but then you have to get the compose file over as well...) IMO this really limits the usefulness of the API.

When working with a swam running in-house (air-gapped,) what is the best way to deploy an application stack via a user application running on a machine without Docker installed?

**Comment by cpuguy83** [comment]
@KylePreuss Why is making the API requests a step backwards? This is what the docker CLI does.

I'm not really arguing against this, but right now it's just not possible to do this in a consistent way, which to me is a pre-requisite for adding it as an API endpoint.

Swarmkit (the underlying orchestrator that swarm mode is built upon) does not really offer a way to do this right now. We would either need a first class object in swarmkit for stacks (not likely to happen) or some support for custom objects/controllers (equivalent to Kubernetes CRD).

**Comment by KylePreuss** [comment]
@cpuguy83 I meant to imply that one of the reasons compose and swarm mode came about (I think,) was to simplify the deployment of multi-service apps (as well as a bunch of other stuff like improved scalability). Once you reach a handful of containers, volumes, networks, etc. in your app the deployment is complex enough that creating a bunch of scripts or executing a dozen commands or so to spin it up is unwieldy.

A step backwards is not the best metaphor; It's more like continuing on a path when a clearer, easier path can be seen but you are unable to take it. Simplicity is gained through use of the stack commands but they aren't available through the API. I understand there isn't a clear-cut, consistent way of making this possible (thank you for your explanation!)

For some additional background, my envisioned use case (until I saw the stack commands weren't supported,) included an end-user application dynamically generating a compose file and then deploying it to a swarm on the network. Since this compose file could be logged and viewed later and the number of API calls would be drastically reduced, my thinking was that it would be easy to debug/re-deploy the generated application stack and a lot simpler to deploy it programatically.

**Comment by jlafourc** [comment]
Hi @KylePreuss,

We achieved to implement the use case you describe by using portainer which offers an api to deploy stacks. 

But after reading those comments, I'm starting to think it's a bit artificial (but useful) . In fact, I realize I'd love implementations of docker stack deploy in multiple languages/clients

Julien

**Comment by cjdcordeiro** [comment]
Hi guys, based on @cpuguy83 comment above and on this ticket's age, is it safe to assume this functionality will not be there anytime soon? or maybe it won't be there at all?

**Comment by AkihiroSuda** [comment]
IIUC this proposal is now succeeded by CNAB and docker-app, and we can safely close this issue?
https://cnab.io/
https://github.com/docker/app
