### ISSUE TITLE
Changing the location of a private registry requires changing ALL dockerfiles

### ISSUE THREAD

**Issue by rodlogic** [moby/moby#27354]
See this #7203.

Fine: so don't break the global namespace but give us some way of addressing this. At this point I need to go in to all branches in all repos and change the FROM localhost.

I don't care if I need to be able to use an ARG variable (I don't think that works) or have a catch all identifier such as 'private' or 'local', I just want to be able to change the location of a private registry in one place.

**Comment by justincormack** [comment]
Please be a bit more explicit about what your requirements are and what kind of solution might work.

**Comment by jkubrynski** [comment]
This issue is a really serious problem. Including fully qualified registry URL in image names makes no sense. The problem is not only when you want to change location of a private registry but also when you want to use more than one registry (for example for staging and production usage). It'll great if docker will support option to add registry for a particular image prefix. For example I can have `company_name/base` image that will be pulled from `myregistry.company.com:5000` as well as from `myregistry.company.io:443`. Currently it won't work. There was great option in redhat's version of Docker `--add-registry` which helped in building such environments.

**Comment by dmp42** [comment]
> Including fully qualified registry URL in image names makes no sense.

At this point this is the only way to guarantee that your build is reproducible. If you break that, then your images are no longer portable or guaranteed to work in other people environments.

Yes, for now naming and transport are bound together.
It's the same situation with other packaging systems that enforce a unique namespace btw.

RedHat `--add-registry` is a poor solution that breaks that fundamental expectation.

Nevertheless, if you really, really need to have separate staging and prod registries, then I assume your base image differs between the two environments? Then why would they have to bear the same name?

Different behaviors depending on the environment is certainly desirable, but I would strongly suggest using environment variables for that, or if you really, really, really need one image to build from different bases using the same name, abuse DNS.

Hope that helps.

**Comment by dmp42** [comment]
@rodlogic if you move a node, or golang package from one place to another, you have to change your source code (or package.json file) to reflect that, right?

**Comment by jkubrynski** [comment]
@dmp42 Image is the same, but environments are separated. To be honest I don't know any other system where you use DNS to find packages. Maybe RedHat's solution is poor, but it's the only one I know which allows you to use Docker on Enterprise scale. Please take a look at RPM or Maven packaging. They are widely used for years and there are no problems you're talking about. And there is totally no DNS involved. In Maven you are using groupId + artifactId. If I decide to replace let's say `centos` with my own `centos` without adding any prefix like `mycompany/centos` then it's my problem. I don't see any pros of closing useful way of using custom images in a company, just because you're trying to achieve something that many users and many creators of packaging systems is not important.

**Comment by dmp42** [comment]
Thanks for the feedback @jkubrynski 

There are several examples of package managers that binds dependencies to their "location" (npm packages and golang imports come to mind). Furthermore, docker distribution mechanism supports mirroring (allowing you to fetch images from a local cache instead of from the hub). 

This is not to discard your concerns, just to highlight that this is not something unusual.

Back to your use case, I would certainly like to hear more about what *exactly* is different between your staging and prod environment, as their may be a simpler way to achieve this.

So, can you elaborate a bit on *what* differs? is this (db) credentials? configuration?

**Comment by jkubrynski** [comment]
The images are the same. The problem is that due to compliance reasons stage and production must be totally isolated - that means no shared runtime dependencies. So we need two separate docker registries - one for stage and second for production. For maven it's simple - you just install artifact into both repositories. For Docker it's impossible, because `FROM` statement in Dockerfile must include full URL of the registry. With RedHat's fork it's solvable by including particular registry with `-add-registry` option. That's not so unique use-case in enterprise-scale deployments.

Generally, in my opinion, you're making image distribution really not flexible and hard to use when trying to solve the consistency problem which doesn't exist. It would be really great to have some option to add registry for some image prefix. Even some hardcoded prefix like `private/MY_IMAGE_NAME`

**Comment by dmp42** [comment]
> that means no shared runtime dependencies

Not to nitpick, but a base image used to build your image FROM is a *build time* dependency IMHO, not a *runtime* one (not to say this invalidates your use case).

> Generally, in my opinion, you're making image distribution really not flexible and hard to use when trying to solve the consistency problem which doesn't exist.

I understand your use-case.

But you shouldn't discard consistency as a non-existent problem just because you don't care (others do, and others may not be interested by *your* use-case - we just have to make it work for everybody).

> [use case and npm equivalent]

So, what's wrong with registry mirror? https://docs.docker.com/registry/recipes/mirror/

This will do exactly what you are asking for: using the same `FROM` statement, but fetch content from a local server.

Have you tried it?

If you need more info on that (beyond the docs), the best way to start a discussion is probably on irc #docker-distribution.

Let me know if that helps.

**Comment by jkubrynski** [comment]
> Not to nitpick, but a base image used to build your image FROM is a build time dependency IMHO, not a runtime one (not to say this invalidates your use case).

As you know `FROM` statement is inside the code repository so it makes sense to keep only one version here.

> But you shouldn't discard consistency as a non-existent problem just because you don't care (others do, and others may not be interested by your use-case - we just have to make it work for everybody).

Users won't run into consistency problems while they use Docker Hub - it's not possible. When you decide to use private registry and you want to deploy your version of centos image you're doing it consciously. But even this can be simply solved by using docker.io as the highest priority registry. That's why I mean there is no consistency problem in adding custom registers on a daemon level.

> So, what's wrong with registry mirror? https://docs.docker.com/registry/recipes/mirror/

As I understand mirror just caches images from parent registry. That will mean runtime dependency, because parent registry should be accessible from stage as well as from production.

**Comment by dmp42** [comment]
> As I understand mirror just caches images from parent registry.

It's first and foremost a daemon flag, that let you do exactly what you are asking for here: ability to have image "bar/baz" be fetched from a different place than what DNS resolve to.

> That will mean runtime dependency, because parent registry should be accessible from stage as well as from production.

It's up to you how you "put" content in your local mirror. HTTP caching is the model implemented by the open source registry *as a courtesy*, but nothing prevents you from pushing content there manually or otherwise and have it served by a whatever flat out http server (or registry).

My point being exactly: the option you want *does exist in the docker engine right now*, and the workflow you describe should be possible very easily, thanks to that registry mirror option.

Here is a twelve lines, very gross way to do it:

```
# Fresh install, pull the registry image from the hub
docker pull registry:2

# Edit your docker daemon opts flag to read:
# DOCKER_OPTS="--registry-mirror=http://localhost:5000"
# Restart docker

# Start your local registry
docker run -d -p 5000:5000 --name registry registry:2

# Tag whatever image and push it to your local registry to preseed it
docker tag registry:2 localhost:5000/dmp42/foobarbazblah
docker push localhost:5000/dmp42/foobarbazblah

# Now, enjoy magic pull using a global name, without anything touching the hub (I expect it to work as well with FROM)
docker pull dmp42/foobarbazblah
```

Obviously move that registry somewhere else in your network, and replace localhost:5000 (when pushing content there) by whatever the actual local domain name and port is.

Let me know if that helps.

**Comment by jkubrynski** [comment]
Thanks for the information. I'm not sure if I understand correctly. Do I need to run `registry` container on each host I want to pull the image?

**Comment by dmp42** [comment]
@jkubrynski you can do it either way - but technically, you just need one registry per environment (just replace `localhost:5000` by `mystaginglocaldomain.com` everywhere in my example).

**Comment by dmp42** [comment]
@rodlogic can you confirm as well that this workflow solves your use case so that we can close this?

**Comment by jkubrynski** [comment]
@dmp42 I've tried your solution and maybe I'm doing something wrong, but even when I add `--mirror-registry` option it looks Docker is using docker.io index, which doesn't contain my image. Should `--mirror-registry` affect also index or just image download?

**Comment by dmp42** [comment]
@jkubrynski can you clarify? eg: by "indexing" == is this about search?

**Comment by jkubrynski** [comment]
@dmp42 It means that even after adding `--mirror-registry` docker shows information that it cannot find the image in docker.io

**Comment by dmp42** [comment]
@jkubrynski did you restart the daemon after adding the mirror (*daemon*) flag? can you curl your registry from that host?

After that, to further debug this, I would need the exact commands you ran, the output of `docker info` and your docker *daemon* logs (preferably in debug mode `-D`).

**Comment by jkubrynski** [comment]
Yes. I've added the flag and I see it's in proper place, when I run `ps |grep docker`:
```/usr/bin/dockerd --storage-driver=overlay --registry-mirror=https://MY_REGISTRY_URL```

However in `docker info` I see:
```
Server Version: 1.12.3
Kernel Version: 3.10.0-327.18.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
Registry: https://index.docker.io/v1/
```

Registry is accessible because I can properly use docker pull with full url

**Comment by jkubrynski** [comment]
@dmp42 Any ideas?

**Comment by philippe-granet** [comment]
https://docs.docker.com/registry/recipes/mirror/#/gotcha

> It’s currently not possible to mirror another private registry. Only the central Hub can be mirrored.

**Comment by jkubrynski** [comment]
So - are you going to provide this feature somehow?

**Comment by jkubrynski** [comment]
@dmp42 Any chances to solve this issue? Or just provide a walkaround?

**Comment by dmp42** [comment]
@jkubrynski https://github.com/docker/docker/issues/27354#issuecomment-259231239

Please provide debug logs if you need more help on this.
The instructions I provided work out of the box in a clean environment.

**Comment by jkubrynski** [comment]
@dmp42 What exactly do you need? I'm adding `--registry-mirror` parameter to my docker daemon and when I invoke `docker info` I see `Registry: https://index.docker.io/v1/`

Do you have different behaviour?

**Comment by htc2u** [comment]
Yes I need but what should I do ya??

发自我的 iPhone

**Comment by htc2u** [comment]
May I know where can find the debug log and what step I need to do I would like to follow instruction

发自我的 iPhone

**Comment by runcom** [comment]
I would still love something like this _as an option_. I fully agree with @dmp42 on consistency but still, people needs something like this.

**Comment by dmp42** [comment]
@jkubrynski did you follow the instructions in https://github.com/docker/docker/issues/27354#issuecomment-257752452

If yes, is this working for you as described? If it's not, can you please:

 * copy the exact steps you have been doing
 * provide your docker daemon logs (in debug)

Thanks.

**Comment by duglin** [comment]
```
ARG registry=docker.io
FROM ${registry}/busybox
```
plus
`docker build --build-arg myregistry.io .`
or
`docker build .`
should do it I think.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
