### ISSUE TITLE
awslogs: add support for selecting group/stream from label instead of name

### ISSUE THREAD

**Issue by jamiethermo** [moby/moby#27362]
Current implementation of cloudwatchlogs allows selecting the stream name from either the container ID or a daemon parameter. It would be tremendously useful if we could select the stream name from a label on the container if it exists, and failing with the current solution for default. I'd like to specify the name of the label in the docker daemon.

**Comment by jamiethermo** [comment]
#dibs

**Comment by samuelkarp** [comment]
@thaJeztah Thanks for pinging me!

@jamiethermo The log driver allows selecting the stream name from the container ID, a log-opt specified on the daemon, or a log-opt specified as part of `docker run` (i.e., you can explicitly specify the stream name when you launch the container).  https://github.com/docker/docker/pull/25633 is a pull request adding the feature of specifying the stream name from a template instead of just statically; it might be worthwhile ensuring that a label can be referenced from the template if you're interested specifically in labels.

**Comment by thaJeztah** [comment]
@samuelkarp @jamiethermo https://github.com/docker/docker/pull/27707 was merged, does that satisfy this feature request?

**Comment by samuelkarp** [comment]
@thaJeztah It doesn't look like #27707 supports reading from a label in the template, so I'm not sure.  @jamiethermo, what's the use-case that you want to satisfy by using the label?

**Comment by jamiethermo** [comment]
I wanted to have a sensible default but also allow users of my cluster to optionally  specify a different name for their stream. If it uses the tag substitution engine that's already in the codebase then it should work.

Jamie

**Comment by samuelkarp** [comment]
@jamiethermo It does use the existing tag substitution already in the codebase, so it sounds like this is resolved for you.

**Comment by jamiethermo** [comment]
I hesitate to say yes till I've looked at the code, but sounds like it.

**Comment by samuelkarp** [comment]
@jamiethermo You can see the code here: https://github.com/docker/docker/pull/27707

**Comment by jamiethermo** [comment]
Only thing I'd say is that it would ideally strip any ':' or '*' characters from the log stream name. They are illegal characters, and my users (cough, not me of course) sometimes aren't aware of that or forget.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
