### ISSUE TITLE
Docker swarm mode not work if swarm nodes are on different subnet?

### ISSUE THREAD

**Issue by raymondsze** [moby/moby#27536]
**Description**
I am new to docker. I simulate the swarm mode environment with docker-machine.
In the following scripts, the --virtualbox-hostonly-cidr is used to ensure the ip address of the 4 machines. This issue can be solved by removing the --virtualbox-hostonly-cidr, but I would like to ask why the nslookup mongors1n1, mongors1n2, mongors1n3 not works?  

**Steps to reproduce the issue:**

```
docker-machine create -d virtualbox  --virtualbox-hostonly-cidr "192.168.100.1/24" manager1
docker-machine create -d virtualbox  --virtualbox-hostonly-cidr "192.168.101.1/24" worker1
docker-machine create -d virtualbox  --virtualbox-hostonly-cidr "192.168.102.1/24" worker2
docker-machine create -d virtualbox  --virtualbox-hostonly-cidr "192.168.103.1/24" worker3
// go to each vm using docker ssh
manager1:
docker swarm init --advertise-addr 192.168.100.100
worker1:
docker swarm join \
    --token SWMTKN-1-3pu6hszjas19xyp7ghgosyx9k8atbfcr8p2is99znpy26u2lkl-1awxwuwd3z9j1z3puu7rcgdbx \
    192.168.100.100:2377
worker2:
docker swarm join \
    --token SWMTKN-1-3pu6hszjas19xyp7ghgosyx9k8atbfcr8p2is99znpy26u2lkl-1awxwuwd3z9j1z3puu7rcgdbx \
    192.168.100.100:2377
worker3:
docker swarm join \
    --token SWMTKN-1-3pu6hszjas19xyp7ghgosyx9k8atbfcr8p2is99znpy26u2lkl-1awxwuwd3z9j1z3puu7rcgdbx \
    192.168.100.100:2377

manager1:
docker network create --driver overlay mongo

docker service create --network mongo --name mongors1n1 --constraint 'node.hostname=worker1' mongo:3.2 --replSet "rs1"
docker service create --network mongo --name mongors1n2 --constraint 'node.hostname=worker2' mongo:3.2 --replSet "rs1"
docker service create --network mongo --name mongors1n3 --constraint 'node.hostname=worker3' mongo:3.2 --replSet "rs1"
docker service create --network mongo --name busybox --constraint 'node.hostname=manager1' busybox

// grab the container name or id for busybox
docker ps
docker exec -it busybox.1.ad21312dseqwjk23 /bin/sh
nslookup busybox
// the following cannot resolved...
nslookup mongors1n1
nslookup mongors1n2
nslookup mongors1n3
```

**Describe the results you received:**
nslookup mongors1n1, mongors1n2, mongors1n3 fail.

**Describe the results you expected:**
Should able to nslookup mongors1n1, mongors1n2, mongors1n3

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
1.12.1

```
```

**Output of `docker info`:**

```
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by Richard-Mathie** [comment]
I might be seeing a similar issue in 1.13 RC2 which i was not seeing in:

 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   a6a38f8
 Built:        Wed Oct 26 07:36:45 2016
 OS/Arch:      linux/amd64

TBH though I am not sure this is due to the subnet. The syncing of DNS state between nodes seems a bit flaky in general, and never got it to work in 1.12.0, so i moved to one of the dev builds of 1.13 which had a lib networking patch for these issues mixed in. Now the RC's are out I was hoping to switch to those, as they should be more stable, things worked locally but alas no when rolling this out, I ended up with a whole load of containers which couldn't see each other, so i had to roll back.

Will investigate further whether i can reproduce with virtualbox

**Comment by aboch** [comment]
@raymondsze Are you still having this issue ? The cluster formation and functioning only needs the nodes to be able to route traffic to each other and the tcp/udp ports specified in the swarm mode documentation to be open on each node. Obviously you are hitting some other issue. 
As a starting point you may want to check if each service task container on that network can ping the other tasks. Also provide the docker info o/p.


@Richard-Mathie Please provide more information about your use case. Also, which libnetwork patch you need. I want to check because it could be one of those we ported to the 1.12.x branch and you may better try an image from that branch (https://github.com/docker/docker/pull/29187)

**Comment by shouze** [comment]
Hi guys, @thaJeztah all I can confirme is that there's an issue related to virtualbox & overlay networks for machines on distinct subnets.

It's even the case with docker 17.06.

If virtual box machines are on distinct subnets, then docker can't establish the right peers list in created overlay networks. This results that services running on distinct hosts can't ping each other.

**Comment by EliSnow** [comment]
Also experiencing this with 17.10.

**Comment by tvergilio** [comment]
I am experiencing this issue too. When a service running on one of the workers try to look up a service running on a different worker by name, I get the following error: 
```
java.net.UnknownHostException: jobmanager: Name or service not known
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
```
See this issue: https://stackoverflow.com/questions/47045887/flink-running-on-docker-swarm-cant-resolve-jobmanager-if-machines-are-in-differ

**Comment by trajano** [comment]
I just used Terraform in AWS to set up my own docker swarm with subnets across availability zones.  Seems to work fine at least with 18.03.1.  Is this still an issue?

**Comment by Richard-Mathie** [comment]
no This issue seemed to disappear from 17.12 ish onward
#close

**Comment by dazinator** [comment]
#close

**Comment by thaJeztah** [comment]
Yeah, let's close this one.
