### ISSUE TITLE
error pulling image configuration 

### ISSUE THREAD

**Issue by eliassal** [moby/moby#27911]
I have a fresh new win2K16 with containers enabled as well as hyper-v is turned on. Whenever I tru to issue the tes cmmand as indicated to test (firewal disabled, no proxy.....)
docker pull microsoft/windowsservercore:10.0.14393.321
I get
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/
93/93a9c37b36d03323f7b8fdd7f0302f7e487a0e8b31ccd8e689c40a404d2f1ea9/data?Expires=1477932342&Signature=N2NdygkaXM6YfVCvXm
TpzD1vDn6k-P50sruyKW21-iVgVdMNwwLUGS0vN2E2ocHrBXowghRgtWX214AcQ5TWo7AqfufXTfsMU9s3TLQV8ed9-dFAXjC5QMImgTmC8Ef0NsQ26s6E
tgiWxvm6XJqV8txihfUO46BOuN-n3Lyfs_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 52.85.221.56:443: i/o timeout
Thanks

error pulling image configuration 

**Steps to reproduce the issue:**
1. docker pull microsoft/windowsservercore:10.0.14393.321
2.
3.

error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/
93/93a9c37b36d03323f7b8fdd7f0302f7e487a0e8b31ccd8e689c40a404d2f1ea9/data?Expires=1477932342&Signature=N2NdygkaXM6YfVCvXm
TpzD1vDn6k-P50sruyKW21-iVgVdMNwwLUGS0vN2E2ocHrBXowghRgtWX214AcQ5TWo7AqfufXTfsMU9s3TLQV8ed9-dFAXjC5QMImgTmC8Ef0NsQ26s6E
tgiWxvm6XJqV8txihfUO46BOuN-n3Lyfs_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 52.85.221.56:443: i/o timeout

I expexted a container to ve created

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.351.amd64fre.rs1_release_inmarket.161014-1755)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 2 GiB
Name: ProdWebServer
ID: EAFQ:W3YV:HIXM:GWRN:WFJK:6TCQ:HEKP:AX6O:CESU:BQ2G:QLEP:OL3O
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by eliassal** [comment]
Sorry, HYper-V is not enabled, my bad, I saw at the instruction that we don²'t need HYper-V if we want to work with windows containers. Is it correct or should I turn on Hyper-V?

**Comment by PatrickLang** [comment]
Hyper-V is optional if you're running Windows Server 2016

It looks like you're hitting a network failure. Can you try again and add proxy settings if they're needed in your environment?
```none
dial tcp 52.85.221.56:443: i/o timeout
```

**Comment by eliassal** [comment]
Sorry, is this a windows or docker command, and when and where I shoiuld run it?
Thanks

**Comment by eliassal** [comment]
Patrick, I just want to confirm that network is working fine on the machine, I can browse internet, I can ping any site

ping altern.org

Pinging altern.org [80.67.174.90] with 32 bytes of data:
Reply from 80.67.174.90: bytes=32 time=7ms TTL=57
Reply from 80.67.174.90: bytes=32 time=7ms TTL=57
Reply from 80.67.174.90: bytes=32 time=9ms TTL=57
Reply from 80.67.174.90: bytes=32 time=7ms TTL=57

Ping statistics for 80.67.174.90:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 7ms, Maximum = 9ms, Average = 7ms

**Comment by kallie-b** [comment]
@PatrickLang @eliassal 

Patrick, to keep you in the loop, I just finished a live debugging session with eliassal to figure out [this issue](https://github.com/docker/for-win/issues/196). We were able to fix the issue he was having with external connectivity from his container endpoints (he had the "bridge=none" option enabled, which was causing his containers not to connect to the default nat network)--so he seems to have no issues with connectivity from his host or from inside containers--but he is still having issues pulling container images from one of his VM container hosts. Vikrant walked him through a fair amount of troubleshooting to figure out whether or not this problem is network-related, but from what we can tell it isn't a networking issue. 

Let me know if I can do anything from here to help get this resolved :)

**Comment by eliassal** [comment]
Hi Kali,

 

1st of all, I would like to thank you for the efforts you have put in this blog, very interesting and useful, I followed instructions, it worked like a charm when browsing using container IP but not the host IP, however, I have a couple of questions:

 

1 - In the db dockerfile, last line indicates a cmd command 

CMD powershell ./start -sa_password %sa_password% -attach_dbs \"%attach_dbs%\" -Verbose

 

I can imagine that "start" is a powershell file which needs 2 arguments, where does it come? Is it already there in the image container, 2nd attach_dbs "[]" where does it get its value in the process?

 

2nd, I changed ports as follows in the docker-compose.yml, as I have something else running on the 80 port)



 

I can browse, from container HOST the blogengine web site using the container IP as follows 

http://172.24.163.161/Blogengine/

but when I do http://localhost:81/Blogengine/ or http://192.168.1.5:81/Blogengine it does not go through and get 404 error. (192.168.1.5 is my host container IP)

I did a netstat on the container host “netstat -an”, cann’t see port 81 listening.

Here is the output of Docker ps

 



 

I understand from the blog that “The ‘ports’ option is analogous to using the ‘-p’ argument in a ‘docker run’ command, and specifies HOST:CONTAINER” so am I doing something wrong?

 

3rd, I tried to connect to the sql container using the attach as follows

docker attach aspnetblogapplication_db_1

 

It never attached to the container. I tried a couple of times, waited for around 20 minutes without success attaching to db container.

Then I tried to use the exec as follows

docker exec -i aspnetblogapplication_db_1 cmd

 

It was successful and was able to get into the container. So why the attach does not work in this case? I managed to investigate the the start.ps1 file and it seems that it does nothing as the attach_dbs "[]" is empty, only starts sql express, am I correct? 

 

Also, as a side note, the 2 images are huge compared to what I used to have when working with other platforms.

 



 

Thanks for your help

 

Salam

**Comment by eliassal** [comment]
Hi Patrick, any feedback on this #27911

 

 

In any case, I have absloutly no networking issues and still getting

 

error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/
ba/baa5d63471ead618ff91ddfacf1e2c81bf0612bfeb1daf00eb0843a41fbfade3/data?Expires=1481548220&Signature=HRXUxPCUYw7OjjB0ep
oFCHFwthLK7B4cAzMFBOiKgkQOmr4~RBbltQSwgB4Xho~sK2VakeIvH9gyMf7b4IdpucBMgzttbcI3TP1TQ-335-DfsAn7QYvWB8eLAhfkYDg-86UmeTkYel
fbp4etV5QVC69tkWPA4QpCJwAZC591bCY_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 54.192.129.107:443: i/o timeout

 

whatever command I use

 

In one of your responses you indicated 

 

It looks like you're hitting a network failure. Can you try again and add proxy settings if they're needed in your environment?

dial tcp 52.85.221.56:443: i/o timeout

I am not sure of what/how is needed to be done.

 

Thanks in advancefor your help

 

Salam

**Comment by kallie-b** [comment]
@eliassal -- I apologize, I forgot about your questions here regarding my blog post! (I do my best to track questions/issues, but never hesitate to ping me again if you're not getting an answer. Especially for anything that is blocking you...)

I'm glad that the blog post was useful to you! As for the issues you ran into:

-"start" is indeed a powershell file that you need for the database service. It is already in the SQL 2014 Express container image.
-The sa_password and attach_dbs environment variables are the arguments to the start script, and they're set in the [db dockerfile](https://github.com/Microsoft/Virtualization-Documentation/blob/live/windows-container-samples/ASP-NET-Blog-Application/db/Dockerfile). You should be able to change the values as you please.
-As a side note, I visited the docker hub to take a look at the [SQL image that the sample uses](https://hub.docker.com/r/microsoft/mssql-server-2014-express-windows/), and realized that it's now deprecated. However, you should be able to use the [current image ](https://hub.docker.com/r/microsoft/mssql-server-windows-express/)without significant changes to the blog sample (you'll of course need to change the db dockerfile to use the new image as the base image (i.e. you'll have to change FROM microsoft/mssql-server-2014-express-windows to FROM microsoft/mssql-server-windows-express in the db dockerfile). I'll try to make time to try this myself soon.

-As far as your port changes, I think your questions must be missing pictures or something because I can't quite follow some of your references. But from my understanding you changed the compose file to be a HOST:CONTAINER port mapping like this:
`services:
 web:
  build: ./web
  ports:
   - "81:80"
  depends_on:
   - db
  tty:
    true
 db:
  build: ./db
  expose:
   - "1433"
  tty:
    true`
-Does the mapping you're trying to make work if you use the "manual" -p option? 
`
docker run -it --name "db" -p 1433:1433 <db container image>
docker run -it -p 80:80 <web container image>`


- From my understanding (I'll double check on this) the "docker attach" command isn't supported on Windows. And from what I can tell it isn't meant to be used in this context anyway. Are you trying to manually start the services and use a docker command to allow the web service to communicate to the db service? In the sample this should automatically work. As I described in the post, the service names as defined in the compose file will be registered with Service Discovery, and the web.config file for the web application contains a connection string that is configured to attach to the database using the "db" service name.
-Does that help with this? I'm a bit unclear on what you're trying to achieve so let me know if I haven't answered your question.

-And thanks for the feedback on the length of the images. I'll keep that in mind but I'm not sure exactly why it would be... I believe they both originate from the WindowsServerCore image, which is fairly large. And I know that the web service includes quite a few source files for the BlogApplication service...


Hope that helps!
--Kallie

**Comment by PatrickLang** [comment]
Is your [Docker forum post](https://forums.docker.com/t/docker-not-working-on-win2k16/26081) referring to the same issue with `docker pull` ?

Do all of your machines fail `docker pull Microsoft/windowsservercore` with the same error, or just some of them?

It sounds like something is still blocking the large download from cloudfront.net

**Comment by eliassal** [comment]
It is only from this machine, I docker on win 10, docker for windows running on win 10 as well, in the smae network and working like a charm. Sometimes, on the the 1st one, I get "Authentication required..." when pulling images.

**Comment by PatrickLang** [comment]
I think it's probably best to finish out the troubleshooting over on the forum thread. Is it alright if we close this since it isn't a doc issue?

**Comment by thaJeztah** [comment]
Let me go ahead and close this 👍

**Comment by eliassal** [comment]
Hi, why? It is not resolved neither here nor on the forum
