### ISSUE TITLE
swarm cluster can't be created again

### ISSUE THREAD

**Issue by lixiaobing1** [moby/moby#27925]
when we test a swarm cluster with three manager no worker, and restart the three manager node at the same time, the swarm cluster can't be created again.

**Comment by thaJeztah** [comment]
Do you have logs that show more info? Can you provide more information about your setup?

**Comment by lixiaobing10051267** [comment]
how can I get more logs as far as possible, thanks :)

**Comment by daviddyball** [comment]
Hi @lixiaobing10051267, you can enable more verbose logging by changing the contents of `/etc/docker/daemon.json` and making sure the following option is present in the JSON dictionary:

```
{
    "log-level": "debug"
}
```

Then restart your docker daemon.

On a side-note, once you have quorum in a swarm cluster (e.g. 2 or more nodes), you will be unable to restart all of them at the same time because, when each comes back online, they won't be able to vote on who is the master and who's data is correct. This is usually the case in all clustered software and is not specific to docker. You need to make sure that at least `N`-1 of your nodes are always available in order for the cluster to survive.

Because your cluster is dead, you will need to forcibly make all nodes leave the swarm and then re-create the swarm again. You will also have lost all your service definitions, as they are stored in the cluster-state.

**Comment by thaJeztah** [comment]
> Then restart your docker daemon.

Enabling/disabling debugging is possible without restarting the daemon, you can send a `SIGHUP` to the daemon, and it should reload the configuration from daemon.json
