### ISSUE TITLE
Docker networking fails if container not kept running

### ISSUE THREAD

**Issue by gregath** [moby/moby#27950]
**Description**

Immediately after restarting docker I'm able to access the internet from the container. If I don't keep a container running however, starting a container and attempting to access the internet will fail. Once the failure occurs it stays failed until the next docker restart. This is reproducible every time. The network failure doesn't occur if I start a container in the success state and keep it running the whole time. 'ip route', 'iptables -L', and 'docker network inspect bridge' are identical in both the success and failed states. This issue was previously reported as a comment in issue 13381.

**Steps to reproduce the issue:**
1. sudo systemctl restart docker.service
2. Repeatedly run containers that access the internet
3. After about a dozen runs internet access fails

**Describe the results you received:**

```
$ docker run --rm busybox wget http://216.58.219.228
Connecting to 216.58.219.228 (216.58.219.228:80)
Connecting to www.google.com (216.58.192.164:80)
index.html 100% |*******************************| 10432 0:00:00 ETA
$ docker run --rm busybox wget http://216.58.219.228
Connecting to 216.58.219.228 (216.58.219.228:80)
Connecting to www.google.com (216.58.192.164:80)
index.html 100% |*******************************| 10422 0:00:00 ETA
$ docker run --rm busybox wget http://216.58.219.228
Connecting to 216.58.219.228 (216.58.219.228:80)
wget: can't connect to remote host (216.58.219.228): No route to host
```

**Describe the results you expected:**

Networking continues to work.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:39:14 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:39:14 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 303
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 534
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.677 GiB
Name: ELITE
ID: CJVG:KA6M:6ZKQ:Z4VS:CR73:MEWT:FLEH:5EF2:AX2I:BH7J:IF3Y:BP6A
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
Log of container with network failure
Jul 06 13:47:01 kernel: aufs au_opts_verify:1570:docker[21760]: dirperm1 breaks the protection by the permission bits on the lower branch
Jul 06 13:47:02 kernel: aufs au_opts_verify:1570:docker[21760]: dirperm1 breaks the protection by the permission bits on the lower branch
Jul 06 13:47:02 kernel: aufs au_opts_verify:1570:docker[21545]: dirperm1 breaks the protection by the permission bits on the lower branch
Jul 06 13:47:02 NetworkManager[667]: (vethf44825d): device is virtual, marking as unmanaged
Jul 06 13:47:02 kernel: device veth370000a entered promiscuous mode
Jul 06 13:47:02 kernel: IPv6: ADDRCONF(NETDEV_UP): veth370000a: link is not ready
Jul 06 13:47:02 NetworkManager[667]: (vethf44825d): carrier is OFF
Jul 06 13:47:02 NetworkManager[667]: (vethf44825d): new Veth device (driver: 'unknown' ifindex: 582)
Jul 06 13:47:02 NetworkManager[667]: (vethf44825d): exported as /org/freedesktop/NetworkManager/Devices/870
Jul 06 13:47:02 NetworkManager[667]: (veth370000a): device is virtual, marking as unmanaged
Jul 06 13:47:02 NetworkManager[667]: (veth370000a): carrier is OFF
Jul 06 13:47:02 NetworkManager[667]: (veth370000a): new Veth device (driver: 'unknown' ifindex: 583)
Jul 06 13:47:02 NetworkManager[667]: (veth370000a): exported as /org/freedesktop/NetworkManager/Devices/871
Jul 06 13:47:02 NetworkManager[667]: (veth370000a): device state change: unmanaged -> unavailable (reason 'connection-assumed') [10 20 41]
Jul 06 13:47:02 NetworkManager[667]: (docker0): bridge port veth370000a was attached
Jul 06 13:47:02 NetworkManager[667]: (veth370000a): enslaved to docker0
Jul 06 13:47:02 NetworkManager[667]: (veth370000a): device state change: unavailable -> disconnected (reason 'connection-assumed') [20 30 41]
Jul 06 13:47:02 NetworkManager[667]: Activation (veth370000a) starting connection 'veth370000a'
Jul 06 13:47:02 NetworkManager[667]: Activation (veth370000a) Stage 1 of 5 (Device Prepare) scheduled...
Jul 06 13:47:02 NetworkManager[667]: devices added (path: /sys/devices/virtual/net/vethf44825d, iface: vethf44825d)
Jul 06 13:47:02 NetworkManager[667]: device added (path: /sys/devices/virtual/net/vethf44825d, iface: vethf44825d): no ifupdown configuration found.
Jul 06 13:47:02 NetworkManager[667]: devices added (path: /sys/devices/virtual/net/veth370000a, iface: veth370000a)
Jul 06 13:47:02 NetworkManager[667]: device added (path: /sys/devices/virtual/net/veth370000a, iface: veth370000a): no ifupdown configuration found.
Jul 06 13:47:02 NetworkManager[667]: Activation (veth370000a) Stage 1 of 5 (Device Prepare) started...
Jul 06 13:47:02 NetworkManager[667]: (veth370000a): device state change: disconnected -> prepare (reason 'none') [30 40 0]
Jul 06 13:47:02 NetworkManager[667]: Activation (veth370000a) Stage 2 of 5 (Device Configure) scheduled...
Jul 06 13:47:02 NetworkManager[667]: Activation (veth370000a) Stage 1 of 5 (Device Prepare) complete.
Jul 06 13:47:02 NetworkManager[667]: Activation (veth370000a) Stage 2 of 5 (Device Configure) starting...
Jul 06 13:47:02 NetworkManager[667]: (veth370000a): device state change: prepare -> config (reason 'none') [40 50 0]
Jul 06 13:47:02 NetworkManager[667]: Activation (veth370000a) Stage 2 of 5 (Device Configure) successful.
Jul 06 13:47:02 NetworkManager[667]: Activation (veth370000a) Stage 3 of 5 (IP Configure Start) scheduled.
Jul 06 13:47:02 NetworkManager[667]: Activation (veth370000a) Stage 2 of 5 (Device Configure) complete.
Jul 06 13:47:02 NetworkManager[667]: Activation (veth370000a) Stage 3 of 5 (IP Configure Start) started...
Jul 06 13:47:02 NetworkManager[667]: (veth370000a): device state change: config -> ip-config (reason 'none') [50 70 0]
Jul 06 13:47:02 NetworkManager[667]: Activation (veth370000a) Stage 3 of 5 (IP Configure Start) complete.
Jul 06 13:47:02 NetworkManager[667]: (veth370000a): device state change: ip-config -> secondaries (reason 'none') [70 90 0]
Jul 06 13:47:02 NetworkManager[667]: (veth370000a): device state change: secondaries -> activated (reason 'none') [90 100 0]
Jul 06 13:47:02 NetworkManager[667]: Activation (veth370000a) successful, device activated.
Jul 06 13:47:02 dbus[689]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service'
Jul 06 13:47:02 dbus[689]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Jul 06 13:47:02 nm-dispatcher[23880]: Dispatching action 'up' for veth370000a
Jul 06 13:47:02 ntpdate[23922]: the NTP socket is in use, exiting
Jul 06 13:47:02 sshd[664]: Received SIGHUP; restarting.
Jul 06 13:47:02 sshd[664]: Server listening on 0.0.0.0 port 22.
Jul 06 13:47:02 sshd[664]: Server listening on :: port 22.
Jul 06 13:47:02 avahi-daemon[688]: Withdrawing workstation service for vethf44825d.
Jul 06 13:47:02 NetworkManager[667]: devices removed (path: /sys/devices/virtual/net/vethf44825d, iface: vethf44825d)
Jul 06 13:47:02 NetworkManager[667]: (veth370000a): link connected
Jul 06 13:47:02 NetworkManager[667]: (docker0): link connected
Jul 06 13:47:02 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth370000a: link becomes ready
Jul 06 13:47:02 kernel: docker0: port 1(veth370000a) entered forwarding state
Jul 06 13:47:02 kernel: docker0: port 1(veth370000a) entered forwarding state
Jul 06 13:47:02 docker[21542]: time="2016-07-06T13:47:02-05:00" level=error msg="containerd: notify OOM events" error="open memory.oom_control: no such file or directory"
Jul 06 13:47:03 avahi-daemon[688]: Joining mDNS multicast group on interface veth370000a.IPv6 with address fe80::fcd1:2cff:fe1f:65c6.
Jul 06 13:47:03 avahi-daemon[688]: New relevant interface veth370000a.IPv6 for mDNS.
Jul 06 13:47:03 avahi-daemon[688]: Registering new address record for fe80::fcd1:2cff:fe1f:65c6 on veth370000a.*.
Jul 06 13:47:05 ntpd[735]: Listen normally on 51 veth370000a fe80::fcd1:2cff:fe1f:65c6 UDP 123
Jul 06 13:47:05 ntpd[735]: peers refreshed
Jul 06 13:47:05 NetworkManager[667]: (vethf44825d): device is virtual, marking as unmanaged
Jul 06 13:47:05 NetworkManager[667]: (vethf44825d): carrier is OFF
Jul 06 13:47:05 NetworkManager[667]: (vethf44825d): new Veth device (driver: 'unknown' ifindex: 582)
Jul 06 13:47:05 NetworkManager[667]: (vethf44825d): exported as /org/freedesktop/NetworkManager/Devices/872
Jul 06 13:47:05 kernel: docker0: port 1(veth370000a) entered disabled state
Jul 06 13:47:06 NetworkManager[667]: (veth370000a): link disconnected (deferring action for 4 seconds)
Jul 06 13:47:06 NetworkManager[667]: devices added (path: /sys/devices/virtual/net/vethf44825d, iface: vethf44825d)
Jul 06 13:47:06 NetworkManager[667]: device added (path: /sys/devices/virtual/net/vethf44825d, iface: vethf44825d): no ifupdown configuration found.
Jul 06 13:47:06 avahi-daemon[688]: Interface veth370000a.IPv6 no longer relevant for mDNS.
Jul 06 13:47:06 avahi-daemon[688]: Leaving mDNS multicast group on interface veth370000a.IPv6 with address fe80::fcd1:2cff:fe1f:65c6.
Jul 06 13:47:06 avahi-daemon[688]: Withdrawing address record for fe80::fcd1:2cff:fe1f:65c6 on veth370000a.
Jul 06 13:47:06 avahi-daemon[688]: Withdrawing workstation service for vethf44825d.
Jul 06 13:47:06 avahi-daemon[688]: Withdrawing workstation service for veth370000a.
Jul 06 13:47:06 kernel: docker0: port 1(veth370000a) entered disabled state
Jul 06 13:47:06 kernel: device veth370000a left promiscuous mode
Jul 06 13:47:06 kernel: docker0: port 1(veth370000a) entered disabled state
Jul 06 13:47:06 NetworkManager[667]: devices removed (path: /sys/devices/virtual/net/vethf44825d, iface: vethf44825d)
Jul 06 13:47:06 NetworkManager[667]: devices removed (path: /sys/devices/virtual/net/veth370000a, iface: veth370000a)
Jul 06 13:47:06 NetworkManager[667]: (veth370000a): device state change: activated -> unmanaged (reason 'removed') [100 10 36]
Jul 06 13:47:06 NetworkManager[667]: (veth370000a): deactivating device (reason 'removed') [36]
Jul 06 13:47:06 NetworkManager[667]: (docker0): failed to detach bridge port veth370000a
Jul 06 13:47:06 NetworkManager[667]: nm_device_get_iface: assertion 'self != NULL' failed
Jul 06 13:47:06 NetworkManager[667]: (veth370000a): released from master (null)
Jul 06 13:47:06 NetworkManager[667]: (docker0): link disconnected (deferring action for 4 seconds)
Jul 06 13:47:06 nm-dispatcher[23880]: Dispatching action 'down' for veth370000a
Jul 06 13:47:08 ntpd[735]: Deleting interface #51 veth370000a, fe80::fcd1:2cff:fe1f:65c6#123, interface stats: received=0, sent=0, dropped=0, active_time=3 secs
Jul 06 13:47:08 ntpd[735]: peers refreshed
Jul 06 13:47:10 NetworkManager[667]: (docker0): link disconnected (calling deferred action)
```

**Comment by aboch** [comment]
Thanks @gregath freproduction steps.

I am not able to reproduce. 

Given you can reproduce, once the containers can no longer reach the internet, can you run 
`docker run --rm busybox route -n`
to make sure the default gw is set inside the container.

If it is fine, can you capture in your container's nw namespace the ICMP packets just to make sure the cause for the wget responding like that is not coming from outside.
- Get the netns path from `docker inspect <your container> | grep SandboxKey`
- Get into the container netns: `nsenter --net=<path>`
- Capture the icmp packets `tcpdump -i eth0 -p icmp -v`
- Run the wget test

**Comment by amitkumarj441** [comment]
@gregath You'll only need to restart the docker daemon and I think everything should be fine:
`$ sudo service docker restart  
docker stop/waiting
docker start/running, process 26999

$ docker run ubuntu ping google.com   
PING google.com (173.194.124.2) 56(84) bytes of data.
64 bytes from 173.194.124.2: icmp_seq=1 ttl=55 time=11.4 ms
64 bytes from 173.194.124.2: icmp_seq=2 ttl=55 time=11.2 ms
...` 

Another Solution: 

Apart from this, I simultaneously analyzed the traffic generated in `wlan0` and `docker0` interface while issuing ping google.com from inside the container. In the `docker0` traffic no response from `8.8.8.8` was received (as expected), but something weird happened in the `wlan0` traffic. It was forwarding the container's DNS request to both the public-DNS servers, but instead of a proper response the interface got flooded by malformed packets.

Try this:

amit@amit-HP-Pavilion-g4-Notebook-PC:~$ sudo tcpdump -ni docker0
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on docker0, link-type EN10MB (Ethernet), capture size 65535 bytes
17:31:18.927299 IP 172.17.0.2.53724 > 8.8.8.8.53: 9371+ A? google.com. (28)
17:31:23.932620 IP 172.17.0.2.47207 > 8.8.4.4.53: 9371+ A? google.com. (28)
17:31:23.938285 ARP, Request who-has 172.17.0.1 tell 172.17.0.2, length 28
17:31:23.938338 ARP, Reply 172.17.0.1 is-at 02:42:53:96:8f:9e, length 28
17:31:28.934345 IP 172.17.0.2.53724 > 8.8.8.8.53: 9371+ A? google.com. (28)
17:31:33.939625 IP 172.17.0.2.47207 > 8.8.4.4.53: 9371+ A? google.com. (28)
17:31:38.945046 IP 172.17.0.2.40407 > 8.8.8.8.53: 16090+ A? google.com.anu.edu.au. (39)
17:31:43.950322 IP 172.17.0.2.52317 > 8.8.4.4.53: 16090+ A? google.com.anu.edu.au. (39)
17:31:48.952601 IP 172.17.0.2.40407 > 8.8.8.8.53: 16090+ A? google.com.anu.edu.au. (39)
17:31:53.957837 IP 172.17.0.2.52317 > 8.8.4.4.53: 16090+ A? google.com.anu.edu.au. (39)

amit@amit-HP-Pavilion-g4-Notebook-PC:~$ sudo tcpdump -ni wlan0
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on wlan0, link-type EN10MB (Ethernet), capture size 65535 bytes
17:31:18.927366 IP 130.56.238.99.53724 > 8.8.8.8.53: 9371+ A? google.com. (28)
17:31:23.932693 IP 130.56.238.99.47207 > 8.8.4.4.53: 9371+ A? google.com. (28)
17:31:28.934421 IP 130.56.238.99.53724 > 8.8.8.8.53: 9371+ A? google.com. (28)
17:31:33.939696 IP 130.56.238.99.47207 > 8.8.4.4.53: 9371+ A? google.com. (28)
17:31:37.815413 00:24:13:12:84:00 Unknown SSAP 0x16 > 80:ea:96:42:58:6d IP Information, send seq 0, rcv seq 16, Flags [Command], length 1450
17:31:37.815430 00:24:13:12:84:00 Unknown SSAP 0x16 > 80:ea:96:42:58:6d IP Information, send seq 0, rcv seq 16, Flags [Command], length 1450
17:31:37.815437 00:24:13:12:84:00 Unknown SSAP 0x16 > 80:ea:96:42:58:6d Unknown DSAP 0x08 Information, send seq 0, rcv seq 16, Flags [Command], length 1450
17:31:37.815441 00:24:13:12:84:00 Unknown SSAP 0x16 > 80:ea:96:42:58:6d Unknown DSAP 0x08 Information, send seq 0, rcv seq 16, Flags [Command], length 1242
17:31:37.815446 00:24:13:12:84:00 Unknown SSAP 0x16 > 80:ea:96:42:58:6d Unknown DSAP 0x0a Information, send seq 0, rcv seq 16, Flags [Command], length 1450
17:31:37.815450 00:24:13:12:84:00 Unknown SSAP 0x16 > 80:ea:96:42:58:6d Unknown DSAP 0x0a Information, send seq 0, rcv seq 16, Flags [Command], length 1450
17:31:37.815453 00:24:13:12:84:00 Unknown SSAP 0x16 > 80:ea:96:42:58:6d Unknown DSAP 0x0c Information, send seq 0, rcv seq 16, Flags [Command], length 674
17:31:37.815457 00:24:13:12:84:00 Unknown SSAP 0x16 > 80:ea:96:42:58:6d Unknown DSAP 0x0c Information, send seq 0, rcv seq 16, Flags [Command], length 1450
17:31:37.815462 00:24:13:12:84:00 Unknown SSAP 0x16 > 80:ea:96:42:58:6d ProWay NM Information, send seq 0, rcv seq 16, Flags [Command], length 483
17:31:37.815465 00:24:13:12:84:00 Unknown SSAP 0x16 > 80:ea:96:42:58:6d ProWay NM Information, send seq 0, rcv seq 16, Flags [Command], length 1450
17:31:37.815469 00:24:13:12:84:00 Unknown SSAP 0x16 > 80:ea:96:42:58:6d Unknown DSAP 0x10 Information, send seq 0, rcv seq 16, Flags [Command], length 1450
17:31:37.815473 00:24:13:12:84:00 Unknown SSAP 0x16 > 80:ea:96:42:58:6d Unknown DSAP 0x10 Information, send seq 0, rcv seq 16, Flags [Command], length 1450
17:31:37.815478 00:24:13:12:84:00 Unknown SSAP 0x16 > 80:ea:96:42:58:6d Unknown DSAP 0x12 Information, send seq 0, rcv seq 16, Flags [Command], length 1450
17:31:37.815482 00:24:13:12:84:00 Unknown SSAP 0x16 > 80:ea:96:42:58:6d Unknown DSAP 0x12 Information, send seq 0, rcv seq 16, Flags [Command], length 1450
17:31:37.815486 00:24:13:12:84:00 Unknown SSAP 0x16 > 80:ea:96:42:58:6d Unknown DSAP 0x14 Information, send seq 0, rcv seq 16, Flags [Command], length 1450
17:31:37.815490 00:24:13:12:84:00 Unknown SSAP 0x16 > 80:ea:96:42:58:6d Unknown DSAP 0x14 Information, send seq 0, rcv seq 16, Flags [Command], length 1450
17:31:37.818044 00:24:13:12:84:00 > 80:ea:96:42:58:6d Unknown DSAP 0x16 Information, send seq 0, rcv seq 16, Flags [Command], length 1450
17:31:37.818062 00:24:13:12:84:00 > 80:ea:96:42:58:6d Unknown DSAP 0x16 Information, send seq 0, rcv seq 16, Flags [Command], length 1450
17:31:37.818070 00:24:13:12:84:00 Unknown SSAP 0x16 > 80:ea:96:42:58:6d Unknown DSAP 0x18 Information, send seq 0, rcv seq 16, Flags [Command], length 1450
17:31:37.818075 00:24:13:12:84:00 Unknown SSAP 0x16 > 80:ea:96:42:58:6d Unknown DSAP 0x18 Information, send seq 0, rcv seq 16, Flags [Command], length 1450
... (1000+ more lines of the same thing)

**Comment by gregath** [comment]
The output of the write command was the same in both the networking and no networking cases:
 ```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.17.0.1      0.0.0.0         UG    0      0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 eth0
```
For the tcpdump test, no packets were captured either before or after the failure.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
