### ISSUE TITLE
Docker v1.12 can not change hostname by env variable $HOSTNAME

### ISSUE THREAD

**Issue by crossz** [moby/moby#28149]
**Description**
With previous docker versions, the command of "hostname" and "echo $HOSTNAME" returned same thing, after I changed it by sending an env variable into the image.

Why I use this is that I want to insert a new host into /etc/hosts by invoking hostname or $HOSTNAME. So my service/app inside this docker can get the 'real' IP address or the one I assigned, while not the docker internal one.

In the previous docker versions, I can change the hostname by assign env variable HOSTNAME, this will change the hostname correspondingly. But now, with docker version 1.12. This kind of linux action doesn't work in that linux behavior.

**Steps to reproduce the issue:**
1. prepare Dockerfile and docker-compose.yml
compose like this:
```
version: '2'

services:
  test:
    build: .
    extra_hosts:
        thisservice: "192.168.1.7"
    environment:
      - HOSTNAME=thisservice
    image: dockerv1.12-test
```

inside the docker container, `cat /etc/hosts` looks like this:

```
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
192.168.1.7	thisservice
172.28.0.2	80260fa6667f
```

2. exec into the container by: docker-compose exec test sh, run commands and check output:
```
$ hostname
80260fa6667f

$ echo $HOSTNAME
thisservice
```

3.

**Describe the results you received:**
From docker v1.12, the hostname command and $HOSTNAME are different.

**Describe the results you expected:**
the hostname command and $HOSTNAME should be same. So that I can make those services in this container can easily pick the ip corresponding to the hostname.

**Additional information you deem important (e.g. issue happens only occasionally):**

In the above case, the service in the container will have no idea about the IP I assigned but go for the docker internal IP. This is not what I want. And not correct behavior in my opinion.

**Output of `docker version`:**
version 1.12.1
```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by ripcurld00d** [comment]
@crossz 
IIRC the `--hostname` option sets the container's hostname.

```shell
$ docker run -it --hostname myhostname fedora bash
[root@myhostname /]# cat /etc/hosts     
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.2      myhostname
[root@myhostname /]# cat /etc/hostname
myhostname
```

**Comment by justincormack** [comment]
I don't think Docker has ever done this. Perhaps `compose` did? cc @shin- any ideas?

**Comment by crossz** [comment]
@justincormack I tried on both Ubuntu 16.04 and Centos 7.2; Before I upgrade docker v1.10, both distro worked as expected. Both went 'wrong' after upgrade docker to v1.12.1 and v1.12.3.

My services, similar to those registered on zookeeper regisitry, have to find the hostname and get its ip address. Previously all good by the way I showed above. But after upgrade to v1.12, hostname (coomand) aslways points to docker internal IP. This is not what I want.

**Comment by crossz** [comment]
@ripcurld00d I did not mean how to assign hostname (when container created). They way I described is to pass a customized hostname and corresponding IP, which are different from that automatically created, i.e. container id as hostname and container internal ip.

**Comment by crossz** [comment]
In another words, How to make the external host IP address assigned to container hostname?

**Comment by nbet** [comment]
i hava the same problem. how to set hostname when build docker image?

**Comment by thaJeztah** [comment]
@justincormack @crossz looks like something _did_ change between docker 1.10, and 1.11, although I'm not sure if setting `$HOSTNAME` _should_ set `hostname`, so possibly it was a bugfix;

```bash
yum remove -y docker-engine
yum install -y docker-engine-1.10.3-1.el7.centos.x86_64
systemctl start docker

docker run -it --rm --add-host "thisservice:192.168.1.7" -e HOSTNAME=thisservice alpine sh -c "echo \$HOSTNAME && hostname"
thisservice
thisservice
```

Switching to 1.11.2;

```bash
yum remove -y docker-engine
yum install -y docker-engine-1.11.2-1.el7.centos.x86_64
systemctl start docker

docker run -it --rm --add-host "thisservice:192.168.1.7" -e HOSTNAME=thisservice alpine sh -c "echo \$HOSTNAME && hostname"
thisservice
c855297c6608
```

However, setting `--hostname` works;

```bash
docker run -it --rm --add-host "thisservice:192.168.1.7" -e HOSTNAME=thisservice --hostname thisservice alpine sh -c "echo \$HOSTNAME && hostname"
thisservice
thisservice
```

**Comment by thaJeztah** [comment]
> My services, similar to those registered on zookeeper regisitry, have to find
the hostname and get its ip address. Previously all good by the way I showed
above. But after upgrade to v1.12, hostname (coomand) aslways points to docker
internal IP. This is not what I want.

So _hostname_ is the hostname of the _container_. The IP-address of the
container _is_ the IP address on the internal Docker network; as far as I can
see, docker is working correct here.


However, for your use case, you want to publish the IP address that the container
is _externally_ _reachable_ on in the zookeeper registry. This IP address is different from the
container's IP-address, and can be even different from the host's IP adress
(for example, if there is a proxy in front of the host, or  in Swarm mode, where
a service is reachable on _any_ node in the swarm).

For swarm-mode itself, we added an `--advertise-addr` option, for a similar reason;
the IP address that a node is reachable on may not be known to the host (if
it's accessible through a proxy only).

I think there's a number of solutions here;

1. Don't have your service use the _hostname_ to register the service. Have an extra parameter, to pass (e.g.) the FQDN of the host that it's _running_ on.
2. If the service only has to be reachable by other services (and not publicly on the internet), _don't_ `-p` / `--publish` it's ports. Other containers on the private docker network _can_ reach the service by it's name.
3. Run the container in `--network=host` so that the container runs in the hosts's
  network stack, and hostname of the container matches the hostname of the host.

Option 1. or 2. is probably the best solution (depending on your use case), as it matches what you're trying to achieve; publishing a service's _externally_ reachable IP-address.
