### ISSUE TITLE
[UX] Guidelines for short/long syntax flags

### ISSUE THREAD

**Issue by icecrime** [moby/moby#28527]
# Problem statement

Docker 1.12.0 and 1.13.0 introduce new syntaxes for:

- Mount specifications (`docker run --mount` and `docker service create --mount`)
- Port specifications (`docker service create --port`)
- Secret specifications (`docker service create --secret`)

This raises several questions regarding consistency:

1. What are the guidelines in terms of short syntax ("porcelain") versus long syntax ("plumbing")?
2. How many flags should be exposed: one for porcelain and one for plumbing, or a single one with two possible syntaxes?
3. Where those flags overlap, do they use the same naming scheme for long syntax option names?

## Current state

<table>
  <tbody>
    <tr>
      <th colspan="2">Area</th>
      <th>Mounts</th>
      <th>Ports</th>
      <th>Secrets</th>
    </tr>
    <tr>
      <th align="left" rowspan="2">Syntax</th>
      <th align="left">Short</th>
      <td><a href="https://docs.docker.com/engine/reference/run/#/volume-shared-filesystems"><code>/src:/dest:rw</code></a></td>
      </td>
      <td><a href="https://github.com/docker/docker/pull/27917#issuecomment-258556920"><code>80:8080/tcp</code></a></td>
      <td><code>secret_name</code></td>
    </tr>
<tr>
      <th align="left">Long</th>
      <td><a href="https://docs.docker.com/engine/reference/run/#/volume-shared-filesystems"><code>src=/src,dst=/dest,readonly=true</code></a></td>
      <td><code>target=80,published=8080,protocol=tcp</code></td>
      <td><code>source=secret_name,target=alias</code></td>
</tr>
    <tr>
      <th align="left" rowspan="2">Flags</th>
      <th align="left">Short</th>
      <td><code>-v, --volume</code></td>
      <td><code>-p, --publish</code></td>
      <td><code>--secret</code></td>
    </tr>
<tr>
      <th align="left">Long</th>
      <td><code>--mount</code></td>
      <td><code>--port</code></td>
      <td><code>--secret</code></td>
</tr>
    <tr>
      <th align="left" colspan="2">Named options</th>
      <td>
<ul>
<li>type</li>
<li>src, source</li>
<li>dst, destination, target</li>
<li>readonly, ro</li>
<li>bind-propagation</li>
<li>volume-driver</li>
<li>volume-label</li>
<li>volume-nocopy</li>
<li>volume-opt</li>
</ul>
</td>
<td>
<ul>
<li>target</li>
<li>published</li>
<li>protocol</li>
<li>mode</li>
</ul>
</td>
<td>

<ul>
<li>source</li>
<li>target</li>
<li>uid</li>
<li>gid</li>
<li>mode</li>
</ul>
</td>
    </tr>
</tbody>
</table>

What we can see from the table above is that:

- Some areas have a same flag support the short and long syntax.
- Some areas have overlapping named options, but not necessarily the same short versions.
- Some areas have overlapping named options, but not necessarily the same semantic (*to be verified*).

# Proposal

*The proposal is to ~burn it all~ homogenize according to well defined guidelines that we can reuse in the future for every feature with the same requirement. What follows is an attempt at defining such guidelines.*

All features which require both a rich way to express complex things in a non-ambiguous manner, while preserving a nice "porcelain" syntax for the 80% use case should:

1. Use the same flag for both the short and long syntax.
2. The long syntax should be a **comma separated** list of **`arg=value`** specifications (e.g., `arg1=val1,arg2=val2`).
3. The short syntax should be a separated list of values (**NOTE:** separator TBD, although `--publish` and `--volume` use `:` today), which defines positional arguments that map directly to an expanded long term equivalent. For example, given the order `arg1`, `arg2`, `arg3`, the short syntax `val1:val2` is equivalent to the long form `arg1=val1,arg2=val2`. This is inspired by the way Python function invocation syntax deals with optional and keyword-only arguments.
4. Wherever possible, consistency of named arguments in the long form across different features should be enforced, including in any short term aliases that those named arguments can take.

# What it means for 1.13.0

If we agree to move forward with this, then we need to review the current set of flags and act accordingly:

- [x] The newly introduced `--port` flag should likely disappear in favor of `--publish`, ensuring that the short form maps cleanly to the long form. #28943
- [x] We know that the `-v` syntax is likely already too overloaded to map cleanly to the long-syntax equivalent introduced by mount, and we might need to drop support for `--mount` in `run` until we can figure this out.
- [ ] We need to reconcile named arguments in secrets with those in mounts (especially with regard to the aliases that `source` supports in mounts).

# References

- #26825 - Add `--mount` flag to `docker create` and `docker run`
- #27794 - Add secret management
- #27917 - Add support for host port `PublishMode` in services using the `--port` option in docker service create

Ping @joaofnfernandes @aluzzardi @thaJeztah @mstanleyjones @vieux @dhiltgen @ehazlett @dnephin :cactus:

**Comment by dnephin** [comment]
My 2 cents:

* the old flags are not porcelain they are legacy
* a flag should not support two formats. That is really confusing, and leads to hacky code that branches on the presence of a specific character, which is brittle and error prone.
* the old positional and comma separated formats should be deprecated and removed. At the time they may have been sufficient, but at this point they are just don't work. Volumes are completely broken for windows paths (because they include colons), and ports have become complex enough that trying to encode all the details in the old format isn't really possible.  Trying to remember the order for the positional arguments is also a waste of time. It's better to have the fields as part of the format. If it's too verbose we can support shorter aliases for the field names. 
* supporting two different formats for the same feature is confusing. We should have a single format that can encode all the required information (the new CSV format).

We don't have to remove the old format right away, but we should add deprecation warnings for them to direct people to the new format.

I think in the end very few people actually want to type out the CLI flags by hand. Even with the old "short version" flags many `docker run` lines are sufficiently long that users will write it into a bash script or some other build tool.  Everyone pretty quickly moves to some way to automate these lines, so there's no reason to waste effort on trying to make them easy to type.

**Comment by aluzzardi** [comment]
> the old flags are not porcelain they are legacy

I think they are porcelain. It's much more pleasant to type `-p 8080` or `-v foo:/bar` rather than the full fledged CSV syntax.

> a flag should not support two formats

I thought so too, but now I'm actually liking it, especially in the context of compose. I wanted to get your thoughts on that:

```yml
web:
  ports:
    - 80:8080
    - port: 81
      target: 8081
      mode: host
```

It seems quite common in yml to have an item that can either be a string or a map when needing more advanced options (e.g. circi ci, travis, ...)

That would map very nicely to the CLI supporting both syntaxes.

Whatever we do, we have to do that in compose as well - if we deprecate one syntax, then we deprecate it from compose as well.

Also - it's kinda infuriating to have `-p` mean something and `--port` something else

**Comment by dnephin** [comment]
`-p 8080` vs `--port target=8080`
`-v foo:/bar` vs `--mount name=foo,dest=/bar`

It's not so much longer, and it's a lot more clear what it's doing.

I don't like it for the Compose file either. It's weird having a list with two completely different types.

**Comment by aluzzardi** [comment]
Humans don't do CSV well and we'll never deprecate `-p 8080:80` so we'll have to support both forever - `-p` and `--port` will always have a different syntax.

Also, the same goes for compose - if we go ahead with the current plan, then we need to update compose ASAP.

**Comment by RRAlex** [comment]
on a side note, in 1.13.0-rc1:
`docker service create --help` will show `--port`, but you still have to use `--publish`.

**Comment by thaJeztah** [comment]
> I think in the end very few people actually want to type out the CLI
> flags by hand. Even with the old "short version" flags many docker run
> lines are sufficiently long that users will write it into a bash script
> or some other build tool.

I have been thinking about that as well. We may be biased, because during
development and testing of docker, we are quickly spinning up containers
and services all the time. I don't think that reflects the use case
of using docker in "production"; for that you _should_ think about
every option to set; determin the correct values for your use case.

Trying to come up with a practical example, I made a list of options that
(I think) should be present on any service (unless you don't care about
containers running out of control);

Minimum things to set;

- a name
- memory constraint
- cpu constraints
- image
- network
- port (source + target)
- restart condition
- image

Likely;

- registry-auth
- replicas

Also likely?

- memory-reservation / cpu-reservation ?
- update settings for swarm

For example:

    docker service create \
      --name=frontend \
      --limit-memory=500m \
      --limit-cpu=0.5 \
      --network=project-net \
      -p=80:80 \
      --restart-condition=any \
      myimage

And,including "likely"

    docker service create \
      --name=frontend \
      --limit-memory=500m \
      --limit-cpu=0.5 \
      --network=project-net \
      -p=80:80 \
      --restart-condition=any \
      --registry-auth \
      --replicas=2 \
      myimage

That's a lot to type, and not something you'll do "by head", so in most
cases this will be written down in a document, put in a script or
docker-compose.yml

> a flag should not support two formats. That is really confusing

I agree on this. It may also complicate documentation, and completion
scripts (but we can try to come up with solutions).

> the old positional and comma separated formats should be deprecated
> and removed. At the time they were introduced they may have been
> sufficient, but at this point they are just don't work.

It "depends". We carried on too long with the positional format, and
cramped too many options in there. I can see the format being useful
(although mainly for `docker run` / dev), but only for the "simple"
cases;

  - `-p 8080:80`
  - `-v myvolume:/somewhere`

The format becomes unuseful fast when adding other options are added (host
IP address, port-ranges, protocol for `-p`, mount-options, bind-mounts
for `-v`).

The `-v` format for _services_ becomes extra problematic, because
we don't want host directories to be automatically created for bind-
mounts (think of `-v /user/home/nginx.conf:/etc/nginx/conf.d/default.conf`
leading to an empty directory being created).

So _if_ we add the "porcelain" flags, we can only add a "dumbed down"
version, which will be confusing as all knowledge users gathered
on `docker run` does not apply to `docker service`.

> Volumes are completely broken for windows paths 
Don't forget Linux paths that contain colons, think of registry
certificates (`/user/home/certificates:/etc/docker/certs.d/myregistry.local:5000:ro`)

> It's kinda infuriating to have -p mean something and --port something else

The reason we have `-p` is for compatibility with `docker run`. People
are used to that flag, so we kept it. It points out that we should be
even more conservative adding shorthand flags.

> Also, the same goes for compose - if we go ahead with the current
plan, then we need to update compose ASAP.

Since the compose file format is versioned, I would not be against this.

**Comment by icecrime** [comment]
We had another conversation with maintainers on this topic, here are the conclusions.

## On short syntax (porcelain versus legacy)

- We want to keep non-CSV syntax to cover the 80% use-case.
- We want the non-CSV syntax to be cleanly layered on top of the long syntax (that is: anything that the short syntax does can be expressed in an equivalent long form).
- The current "historical" non-CSV syntax in the Docker CLI (`-p`, `-v`) got _too_ overloaded, and cover way more than the typical use-cases: we will need to clean those up.

## On one flag versus two flags

- If we choose to go with two flags, we need to make it obvious that they are related (for example, `--port` and `--publish` are poor choices because they don't seem obviously connected).
- From a docker-compose.yml perspective, and assuming that section names map directly to flags, a single flag is better as we can scope both short syntax and long syntax under a same section (e.g., `ports:`).
- As a result, we will go with a single flag: anything that matches `\w+=\w+(,\w+=\w+)*` will be parsed as the long syntax, and the rest as the short syntax.

## How do we fix the current state on master?

- **Secrets:** accept `src` as a short name for the `source` argument.
- **Ports:** remove `--port` and have `--publish` support the long syntax
- **Mounts:** deprecate `--mount` (maybe remove it from `run` immediately) and have `--volume` support the long syntax.

**Comment by icecrime** [comment]
Cc @AkihiroSuda about the impact on `--mount` (sorry for the bad surprise :disappointed:).

**Comment by AkihiroSuda** [comment]
OK, I'll open a PR to remove run --mount

**Comment by AkihiroSuda** [comment]
@icecrime

Since 1.13 already shipped, can we close this issue, and open a new issue for the "long" version of `--publish` and `--volume`? (or can we just rename this issue and change the milestone?)

**Comment by justincormack** [comment]
I would rename, it has useful discussion.

**Comment by thaJeztah** [comment]
Yes, renamed it, because we still need additional changes to complete this proposal

**Comment by AkihiroSuda** [comment]
@icecrime 
Opened #30397 for the long-syntax version of `--volume`. PTAL.

**Comment by stevvooe** [comment]
Removing `--mount` is a huge step back.

**Comment by AkihiroSuda** [comment]
@stevvooe 

WDYT about reviving `docker run --mount`?
If we do so, WDYT about:

 * Should we declare deprecation of `docker run --volume`? But we should never remove it in actual, because it has been widely used.
 * Should we support short-syntax mount? e.g. `docker run --volume /foo:/bar`. But we should not support it for `docker service` (because it would require implementing  `--volume-driver`)
 * Should we define a short-hand flag for `--mount`? e.g. `-M` (`-m` is used for `--memory`)

**Comment by stevvooe** [comment]
> Should we declare deprecation of docker run --volume? But we should never remove it in actual, because it has been widely used.

No, just leave it alone.

> Should we support short-syntax mount? e.g. docker run --mount /foo:/bar. But we should not support it for docker service (because it would require implementing --volume-driver)

No, just leave it alone.

> Should we define a short-hand flag for --mount? e.g. -M (-m is used for --memory)

No, just leave it alone.

I think we are making this way more complicated than it has to be. Just leave the broken volume flag as it is today and add `--mount` to `docker run`, as I thought we had done.

**Comment by AkihiroSuda** [comment]
@icecrime PTAL?

**Comment by icecrime** [comment]
I don't know how to respond as the proposal was gunned down not with an alternative solution, but with the suggestion that we do nothing.

Please tell me how you disagree with the problem statement above, and if not, how to solve it in a better way than previously suggested.

**Comment by stevvooe** [comment]
@icecrime I'm sorry if my point was confusing.

Mostly, the objection was that this was used as impetus for removing the well-structured `--mount` flag on `docker run` and overloading the `--volume` flag instead. I don't see how the `--mount` flag prevents or affects any part of this plan. It is a well-structured, low-level, direct representation of a mount, which exists in both the container and service API. The syntax has proven effective and we now employ it other areas, like `--secret`. The `--mount` flag is almost the archetype for this proposal.

What we have to recognize is that these more complex flags are the direct result of the complexity of using a command line flag to configure first-class relationships between entities in our system. To be specific, the problem being solved here is being able to configure the use of a specific resource, such as a secret, volume or network. Classically, we have avoided this with cute syntaxes, such `-v` or `-p`, but when you start looking at production use cases, this approach breaks down. In yaml or json, expressing such relationships is very straightforward because we can declare the entire relationship as a discrete object.

In general, I am in favor of the proposal for introducing a porcelain layer backed by hard data structures. It makes the easy things easy and the hard things possible. However, I am opposed to excessive overloading of command line flags. It makes the code complicated and the UI hard to use. While I understand that we'd like to minimize the addition of new flags, there are cases where adhering to this too tightly may yield a substandard result.

**Comment by icecrime** [comment]
@stevvooe My concerns are:

- We made the decision for `--port` and `--secret` which are now following the guidelines above, which means that short and long syntax are two alternatives syntax of the same flags. Do we already want to make an exception here?
- How do we expect a user to understand that `--mount` is somehow the "advanced" syntax underlying `--volume`? We went over this already when we decided on this issue, and the outcome was that there's no good way (I don't think anybody would be happy with `--volume-adv` or `--volume-ex`).
- The whole point of coming up with guidelines is to stop having those arguments over and over again, but this is only beneficial if we agree that inconsistencies in the CLI are problematic in the first place. We are not making this way more complicated than it has to be, we're making a complicated decision once so we don't have to do this every month.

**Comment by AkihiroSuda** [comment]
@icecrime @stevvooe
WDYT about having both `--mount (SHORT|LONG)` and `--volume (SHORT|LONG)`? (`SHORT` is only for `docker run`)

Pros:
- consistent with the guideline
- can avoid the `--volume type=bind,src=this-is-not-volume-but-cli-says-this-is-volume,dst=..` issue. Although such weird flag is still valid, we can "suggest" people to use `--mount type=bind,src=..` instead

Cons:
- user can still get confused about having both `--mount` and `--volume`. Maybe we should declare deprecation of `--volume` and hide it from `--help`.

**Comment by icecrime** [comment]
@AkihiroSuda That could work. Actually I think the most important is for `--mount` to support both the short and long syntax, and I'm ok if we want to "abandon" `--volume` in its current state.

**Comment by stevvooe** [comment]
> Actually I think the most important is for --mount to support both the short and long syntax

Why is this so important? This is like the least important problem with docker.

The only thing that could work is `<src>,`<dst>`, but that limits the ability to do short types. It also limits the ability to have volumes have the same names as possible mount types: `bind,<src>,<dst>`.

Either way, we cannot bring the short syntax to `--volume`. It will not work. It is a technical impossibility.

**Comment by AkihiroSuda** [comment]
@icecrime @stevvooe

How about:

mode | `--volume SHORT` | `--volume LONG` | `--mount SHORT` | `--mount LONG`
--- | --- | --- | --- | ---
`docker run` | :white_check_mark: (as-is) | :no_entry_sign: | :heavy_exclamation_mark: (prints warning to suggest using `--mount LONG`) | :white_check_mark:
`docker service` | :no_entry_sign: | :no_entry_sign: | :no_entry_sign: |  :white_check_mark: (as-is)

:heavy_exclamation_mark:  differs from my previous proposal https://github.com/docker/docker/issues/28527#issuecomment-278226293

**Comment by AkihiroSuda** [comment]
cc @dnephin ( related: https://github.com/docker/docker/pull/30597 )

**Comment by thaJeztah** [comment]
We discussed in the maintainers meeting, and think that after all, just adding the `--mount` flag (with the advanced syntax) to `docker run` is the way to go.

@AkihiroSuda @vdemeester one of you wanting to pick this up again?

We may need a warning that `--volume-driver` does not apply to `--mount`, only to `--volume`

**Comment by AkihiroSuda** [comment]
:tada:

#dibs (unless @vdemeester started working on it )

**Comment by AkihiroSuda** [comment]
opened https://github.com/docker/docker/pull/32251

**Comment by AkihiroSuda** [comment]
This is closable now, right?

**Comment by vdemeester** [comment]
I think so
