### ISSUE TITLE
With --userland-proxy=false, dockerd listens on exposed ports (instead of docker-proxy)

### ISSUE THREAD

**Issue by peterthomassen** [moby/moby#28589]
**Description**

I assign IPv6 addresses directly to my docker containers and don't want anything docker-related to be available on the host IPv6 address.

By default, `docker-proxy` listens on the host IPv6 address to deal with traffic coming in on exposed ports (each with a different process). I therefore added `--userland-proxy=false` to the `dockerd` systemd configuration.

It turns out that the main `dockerd` process now listens on the exposed ports instead. While I was not able to establish a connection on these ports (I tried an SSL connection on port 443, with no success), this is still a bug, as it exposes information on the host IPv6 address unnecessarily (nmap can tell that something is listening on these ports).

Furthermore, while I was not able to establish a connection on these ports (I tried an SSL connection on port 443, with no success), I was wondering a few things:

- Why does `dockerd` listen on exposed ports when `--userland-proxy=false` is set?
- What sort of communication can be done with `dockerd` through these ports? Is any form of remote control possible?

**Steps to reproduce the issue:**
1. use a host with IPv6 address
2. expose a port from a container
3. set `--userland-proxy=false`

**Describe the results you received:**
`dockerd` listening on exposed port on host IPv6 address

**Describe the results you expected:**
nothing listening on exposed port on host IPv6 address

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 166
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 151
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-47-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.736 GiB
Name: cluster.dev.desec.io
ID: BITY:LMNY:JHQD:64NW:DVT5:HUBG:BQAR:KMGI:UK53:7JUC:T7XI:YNQH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by aboch** [comment]
Yes, if `--userland-proxy=false` portmapper will spawn a `dummyProxy` which will bind to the port.
I believe this was done so to book the port for not being bound by some other service on the host.

The comment at https://github.com/docker/docker/blob/v1.12.3/vendor/src/github.com/docker/libnetwork/portmapper/proxy.go#L103 seems to support this theory.

**Comment by peterthomassen** [comment]
Hm. I'm not sure if I follow the reasoning behind this.

Why would one want to prevent another service binding to this port? In my setup, each container has its own IPv6 address, and is exposed fully (up to container-specific firewall rules). IPv4 exposure is done via IP forwarding on the host. None if this needs any binding on the host IPv4 or IPv6 address.

To me, this seems like a messy solution. And, as I said, it leads to information exposure on an additional IP address (namely, the host IPv6 address because ports on this IP address do not look "closed" to the outside [you don't get connection refused when attempting a connection], whereas it would be sufficient to make things available on the container IPv6 address only).

**Comment by justincormack** [comment]
Why are you publishing the ports if you don't want them exposed? If you just leave ipv6 ports on bridge networks is that not sufficient without publishing them?

**Comment by peterthomassen** [comment]
@justincormack, I am publishing ports to make services visible on the host IPv4 address. For IPv6, I would like to use direct routing to the container IPv6, without getting the host IPv6 address involved at all.

There is no need to do anything docker-related with the host IPv6 address in this case.

**Comment by justincormack** [comment]
Ah I think I see what is happening.

Does it help if you explicitly publish the ports to an ipv4 address, ie `docker run -p 192.168.1.34:80:80` say, replace with an actual external IPv4 address? This should not publish to ipv6, and not to dual stack, seems to work for me. Using `0.0.0.0` or the default of empty seems to listen on `[::]` dual stack, which is why you get a connection.

The Go listening behaviour seems hard to control, see https://github.com/golang/go/issues/9334

**Comment by peterthomassen** [comment]
When I do this, the IPv6 listening indeed goes away. However, `dockerd` then shows up listening on the IPv4 address, according to `netstat -tpln`.

Why is this? I thought the routing is done via forwarding to my bridge (this is also what `iptables` tells me.) Why can't we just get rid of any `dockerd` or `docker-proxy` stuff listening on any of these ports when `--userland-proxy=false` is set?

**Comment by alexandru-lazarev** [comment]
After update to 20.10.06 issue happened again on CentOS 7.9 with ipv6 disabled (I really do not need it) - any ideea how to fix it?

----
root@AlexL:~ # docker run -e POSTGRES_PASSWORD=password -p 5432:5432 postgres:12.4
docker: Error response from daemon: driver failed programming external connectivity on endpoint sleepy_wilson (4c360a7cf5c62a8ee4199ebe623b20154e12a8b9902c796bf7009a3e742bb1ab): Error starting userland proxy: listen tcp6 [::]:5432: socket: address family not supported by protocol.
ERRO[0000] error waiting for container: context canceled 
----

**Comment by vincentbernat** [comment]
This dummy proxy is triggering other issues like intercepting traffic it should not and establishing conntrack entries it should not. Why would it be Docker's job to ensure the port is free?

**Comment by polarathene** [comment]
I think this can be closed?:
- UDP issues have been resolved.
- Port publishing should be done if you're going to bind it anyway.
  - If you don't need it for IPv6, then be specific and bind only to IPv4 on the host.
  - Your host can access a services ports via IP directly if necessary, instead of binding to another IP.

---

> Why would it be Docker's job to ensure the port is free?

Isn't that the point of `-p` / published ports feature? That the container is intended to reserve that port on the bridged interface? Avoids some less obvious race conditions that way? (_if more than one service tries to bind_)

The related UDP concern and PR may have been resolved. The UDP issues cited by your PR have been referenced as part of [this fix](https://github.com/moby/moby/pull/44742) that should be available with v23 of Docker Engine onwards.

- If you have dual-stack setup, the IPv4 external interface for NAT is at risk of published port conflict, which'd presumably limit your IPv6 port usage too?
- Is there value in GUA addresses for the containers vs matching the private IPv4 subnet NAT behaviour for IPv6 with ULA + `ip6tables: true`? If IPv4 / dual-stack is going to constrain you, it seems it'd be simpler that way and more consistent. Mixing in GUA addresses is more fragile in my experience with Docker, especially if the host environment changes (_firewall used, network management gotchas such as with NDP, etc_).

**Comment by akerouanton** [comment]
@polarathene provided a compelling explanation of why the dummy proxy is listening on the host, and how the code evolved to reach this state.

As the OP's issue come from a misunderstanding of how dockerd publishes port, I think we can safely close this one. Nonetheless, we need to improve our docs to better state what happens (and why) when a port is published by dockerd, whether the userland proxy is enabled or not. docker/docs#17312 looks to be the proper place to discuss that.
