### ISSUE TITLE
Whether docker 1.12 swarm automatically updates the latest image for running services?

### ISSUE THREAD

**Issue by ghostplant** [moby/moby#28796]
I noticed that when I created a new service using `docker swarm create`, the engine will try pulling the latest images even if the expected image is already contained in local `docker images`.

So my question is that once the service is running already with a certain scale number (such as scale=3), and then I push new latest image to registry, whether the engine automatically pull the latest image and restart the running services  serveral hours later?

Actually, I don't want it to automatically do updating when service is running.

**Comment by thaJeztah** [comment]
No, docker will not _automatically_ pull an updated image if it's pushed to the registry. If you want to setup an automated CI/CD pipeline, here's some blogs about [Docker Cloud]( https://blog.docker.com/2016/04/cicd-with-docker-cloud/), and the [auto-redeploy](https://docs.docker.com/docker-cloud/apps/auto-redeploy/) function.

Docker 1.12  automatically perform a "pull" on the node that a service's tasks are scheduled on when a service is _created_, _updated_, or _scaled_. This makes sure that the containers use the latest version of the specified image/tag.

However, this can also mean that if new tasks / container are created for a service, the new containers run a more recent version of the image than existing containers. This can happen, for example, when the service is scaled, or if a node is taken down for maintenance and the container is rescheduled on another node.

Since you want to be in full control of _what_ version of an image is running for your services (i.e., the _exact_ version of the image that you ran your tests on before deploying to production), it's best to use a [digest  / immutable identifier](https://docs.docker.com/engine/reference/commandline/pull/#/pull-an-image-by-digest-immutable-identifier) for your services, so;

```
docker service create --name web nginx:alpine@sha256:5c6be3514a00db611371806c5aeb510dfd285a4b8261c6e5c3323387e396b66b
```

Instead of 

```
docker service create --name web nginx:alpine
```

Using a digest makes sure that;

- you know _exactly_ what's running in the service, and the containers are running the same version of the image you used in testing.
- every instance of the service runs the _same_ version of the image
- you can roll back to a previous version of the image, even if the tag was overwritten (e.g. you can use previous versions of `myimage:latest` if `:latest` was updated to a newer version)
- nodes don't have to _pull_ the image if the image with the specified digest is already in the local cache

Docker 1.13 automatically detects if a digest is specified as the image for a service, and if not, automatically resolves the digest, and "pins" the service to that digest. This makes it easier to use, and can be useful if your own images stick to a strict tagging scheme (i.e., if you _never_ overwrite an existing tag). For full control though, specifying the digest when deploying/updating the service is the recommended approach.

**Comment by ghostplant** [comment]
Thanks. One more case, services might be restarted if new machine joins into an existing cluster, which will also trigger image update.

**Comment by thaJeztah** [comment]
Not by default; swarm mode will _not_ automatically re-balance existing services if a new node joins. There's no need to if services are running correctly. For a discussion on that, see https://github.com/docker/docker/issues/24103

**Comment by ghostplant** [comment]
I use default version from Ubuntu apt. When I am using a single-node swarm and create a service with scale=5. After all containers finish started and I join a new machine, I found some containers crashed and then recovered.

**Comment by thaJeztah** [comment]
> After all containers finish started and I join a new machine, I found some containers crashed and then recovered.

Please open an issue for that if you are able to reproduce, because joining a machine should not affect the swarm. If possible, try to collect logs from both the existing nodes and the node that joined. Also, would be worth knowing how you added the new node (was it a "fresh" ubuntu machine, or perhaps a clone/copy of an existing node in the swarm). I seem to recall cloning nodes (e.g. VM snapshots) could cause issues in "classic" swarm, but I haven't checked if they cause issues with swarm _mode_ as well.

**Comment by mstanleyjones** [comment]
@thaJeztah the docs for this are improved in https://github.com/docker/docker.github.io/pull/531 where we talk about the ability to update the service to use a new version of an image explicitly. Do you think it would be OK to hold off on doing more docs work until 1.13 is released?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
