### ISSUE TITLE
Docker application is not accessible from host.

### ISSUE THREAD

**Issue by peeyar** [moby/moby#29122]
I have a nodejs docker service running inside an amazon Linux Ec2 instance. My nodejs application is exposing port 5000. So I tried to map the host port to container port using the following command.
    sudo docker run -p hostip:5000:5000 mynodeapp
I can see that application is running and Node app is listening on port 5000 in container.

But when I tried to access with http://hostip:5000/  it is not working..

Can some tell me what I am missing here..?

Thanks 
Raj

**Comment by thaJeztah** [comment]
Could you provide the information that was requested in the template (https://github.com/docker/docker/blob/master/.github/ISSUE_TEMPLATE.md); at least `docker version` and `docker info`

Also, please provide a way to reproduce, not using a custom image, because we won't have access to that image. For example `docker run -d -p hostip:8000:80 nginx`. Is your nodejs application listening on all IP-addresses, or only listening on 127.0.0.1 ?

**Comment by thaJeztah** [comment]
closing; this one went stale
