### ISSUE TITLE
Docker and Firewalls such as IPTables

### ISSUE THREAD

**Issue by lenovouser** [moby/moby#29312]
I've had a very bad experience with Docker and Firewalls. I want to e.g. be able to control which IP addresses can connect to certain ports. At some point I noticed that the Firewall was being circumvented by Docker by adding IPTables rules.
After some searching I found that `--iptables=false` supposedly fixes that, so I added it to my Docker Daemon options. Then I noticed that this breaks two things:

1. The containers don't have internet access themselves anymore. ( #28811, #28241 )
2. The IP Addresses connecting always are always from the `docker0` network, which breaks rate limiting etc. ( #7540 )

Someone then did recommend using `--userland-proxy=false` without `--iptables=false` (Can't find the source anymore, I believe it also was in a GitHub issue here) which I tried - it breaks IPv6 ( #15840 ) without fixing the port problem.

Overall this has been a very painful process for me since about one year, for other people since 2014  ( #4737 ) with no clear fix in sight. There seems to be some progress made with dropping the need to modify IPTables altogether ( #23022  / https://github.com/docker/libnetwork/pull/1379 ), but even though the PR is there nothing is happening / seems to be merged which is similar to what happened with IPv6 support in `-p` which also has been a issue since 2015 ( #11518 ) and had a fix available since start of this year ( #20315 )

So my question is:

How do you run Docker with IPTables / UFW and:

 - Being able to control the access to certain ports opened by Docker with UFW
 - Letting the containers themselves access the internet
 - Proxy the correct IP addresses into the container
 - Not breaking IPv6 **and** also proxying the correct IPv6 addresses into the container

E.g. something like being able to set `--iptables=true` only on certain containers would already help a lot even though the issue with IPv6 and correct IP addresses would still persist.

> I know there are issues for everything I mentioned - that's why I linked them, this issue is more for showing the greater picture of how you can't fix anything related to networking without breaking something else - which is something I think the developers might not realize based on e.g. how slow fixes are merged. I am of course not expecting you to merge the PR's without reviewing / checking, but if you look at the PR's I mentioned - there isn't even progress being made by commenting, asking for changes or reviewing for several months.

Cheers,

Silas

**Comment by cpuguy83** [comment]
I too would like to see a fix.

We should allow people to insert rules above the docker chain, but we always put our chain on top.
And of course now we have this situation where there's probably tons and tons of people relying on the existing configuration and suddenly appending instead of pre-pending will end up breaking production systems.

Maybe we can have users provide a template for where our chains are inserted?

**Comment by aboch** [comment]
For providing external reachability to the containers somebody has to do the address/port translation. Docker uses iptables for this. If you turn it off, then you need to supply that functionality yourself. I would not consider this an issue, this is by design.

In regards to the filter `FORWARD` chain, the reason why the rules that jump to `DOCKER` and `DOCKER-ISOLATION` chains are inserted instead of appended, is because they must be consulted before any other docker related rules (that are also present in the `FORWARD` chain) that do ACCEPT the packet (ex. ICC rules). 

If we move all the docker related rules away from the base `FORWARD` chain, let's say we put them in a specific user chain, then we no longer need to prepend those jump rules. Sometime back I pushed a change for this, but it did not get much traction.
This would also allow us to reserve a docker chain for the user to insert his rules, a chain which docker would not never flush or modify. This was also requested by few users.

In some other github issue (which I cannot find now), somebody suggested that docker could add its rules after a specific comment marked rule. User would create a no-op rule with a specific comment, docker would look for it, for its index, and add its rules after that index. I still need to check if that would work in all cases.

Rearding `--iptables`, besides user would expect this to be a daemon wide flag, in reality it only affects bridge driver iptables rules (as most of the daemon networking flags). This should probably be changed. @mavenugo was also suggesting to change this flag from binary true/false to more granular one where user can decide, as an example, that docker only touches the filter table and not the nat table.

iptables is a tool used by docker to provide isolation among its bridge networks/containers and to provide external host connectivity to containers. Providing `--iptables` control at per-container level is out of the scope IMO. That would fall under network policy discussion, which goal is to first to define a proper abstraction. The implementation of it could be iptables or anything else. We should not approach this starting from the bottom, the iptables detail.

Using ipvs for nating will not remove the need for iptables, as we still need them for providing networks/containers isolation. 

We are aware of Docker iptables not playing well with other firewalls, and we are exploring solutions for the most common problems.

**Comment by raarts** [comment]
I would really have appreciated knowing from the docs that docker does not play well with 'other firewalls'. Would have saved me a lot of time. Is it prudent to create a doc issue for it, or is that already in the works?

**Comment by thaJeztah** [comment]
@raarts not sure if there's an issue, but feel free to open one to capture this; https://github.com/docker/docker.github.io/issues

**Comment by raarts** [comment]
Alright, did just that: https://github.com/docker/docker.github.io/issues/1132

**Comment by kbhaines** [comment]
I'm been grappling for a few days with this now, trying to secure port 443 (running on an nginx container) to a range of IP addresses. No matter what I've tried, Docker insists on having its rules first in the FORWARD chain.

Given Docker appends an ACCEPT rule in the DOCKER chain for each open port, could we have an option to jump to a specified chain instead; e.g. Docker currently does:

    -A DOCKER -d 172.17.0.2/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 443 -j ACCEPT

but instead could do:

    -A DOCKER -d 172.17.0.2/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 443 -j MY-CHAIN

MY-CHAIN could then do further filtering and ACCEPT/DROP as necessary.

**Comment by wenjianhn** [comment]
@lenovouser I have sent a pull request to fix this issue.

https://github.com/docker/libnetwork/pull/1675

**Comment by originsmike** [comment]
Looking forward to this fix!

In the meantime, here's the only workaround/hack I've been able to find: drop disallowed NEW connections in the *mangle PREROUTING table/chain. Docker doesn't touch that, and it's the only spot that's after conntrack and before *nat PREROUTING where Docker puts its DNAT rules.

This works if your machines have a separate public interface (which you want to lock down) and private interface (which is presumably within some VLAN security zone and doesn't need to be locked down as tight).

Something like this, to open ports 22 and 8080:

```
iptables -t mangle -I PREROUTING -i $public_interface -p tcp -m conntrack --ctstate NEW -j HIDEFWD
iptables -t mangle -A HIDEFWD -p tcp -m tcp --dport 22 -j RETURN
iptables -t mangle -A HIDEFWD -p tcp -m tcp --dport 8080 -j RETURN
iptables -t mangle -A HIDEFWD -j DROP
```

A side effect of using this terrible hack is that you no longer need *filter INPUT rules, since packets with a local destination also traverse *mangle PREROUTING.

**Comment by dm17** [comment]
It would be great if a project like this were blessed by the Docker team as "verified as good security practice for basic configurations," or similar:
https://github.com/chaifeng/ufw-docker

Generally it still seems running a firewall on the host is the best idea, rather than in a container, which is suggested by some. But what if a system is rebooted and docker & UFW/iptables don't come up in the same order as before? There are several cases that I would have to spend some time thinking through before I feel that I'm covered properly using docker + iptables.

**Comment by akerouanton** [comment]
I created a discussion about what's going on with custom iptables rules (whether created through ufw or manually) and what we can do to improve that. It's available here:

- https://github.com/moby/moby/discussions/45524
