### ISSUE TITLE
Feature request:  Named Logs

### ISSUE THREAD

**Issue by jrmoserbaltimore** [moby/moby#29604]
**Description**

Docker can collect logs, but only as _primary_ and _error_ logs.  It would be nice to be able to collect more logs, especially from child worker processes.

For example:  `php-fpm` emits its own main log on `stdout`; while its children try to open an `access.log` and `error.log`.  That's three separate logs; docker can't collect them separately.

It would be nice if Docker allowed an option to name a log file, at which Docker will create a named pipe.  For example:  `/var/log/nginx/error.log` could be specified, and Docker would create an `error.log` named pipe which it then recognizes as that file.

By naming these logs, it would be possible to pull that specific log via docker, or to inform log drivers that a particular log is in use.  At the very least, it becomes possible to collect additional logs, and to read them by calling `docker logs --name LOGALIAS MYCONTAINER`.

**Comment by AkihiroSuda** [comment]
I like this idea, but how can we implement for Windows?
IIUC due to the limitation of Windows NPFS, named pipes can be only created under `\\.\pipe`, and some apps does not accept such a string as a valid file path.
Although we can use regular files instead, but it does not seem work well with large files that need to be rotated.


So, I'd like to suggest a workaround by redirecting {access, error.log} to some syslog container.
i.e.

 * nginx container --> syslog container (https://nginx.org/en/docs/syslog.html)
 * syslog container --> docker logger

**Comment by AkihiroSuda** [comment]
Another idea is to implement a built-in syslog server which is accessible from a container via a network, but I wonder it is too much

**Comment by cpuguy83** [comment]
@AkihiroSuda We've definitely talked about the syslog approach in the past.

**Comment by AkihiroSuda** [comment]
@docker/core-containerd-maintainers 
I think this feature is worth considering as a feature of containerd, although I'm unsure how it would work on Windows

(related: https://github.com/docker/containerd/issues/603)

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
