### ISSUE TITLE
Proposal:  image combine and image patch 

### ISSUE THREAD

**Issue by coolljt0725** [moby/moby#29649]
In some scenario, a service is developed by several teams. For example, the os team develop the base image, the platform team develop the platform image base on the base image, and the app team develop the app image base on the platform image, so the final image release to the user is `app<-platform<-base ` .  The issue is if there is some CVE or bug in the base and have to release a new base image to fix these, all the `platform` image and `app` image have to rebuild and release a new image.   The platform team and app team are not quite happy about this,  they want to decouple from the base image's release and release their image only if there is some changes in their own developed software.   They provide two approach: 

* 1  image combine
They suggest the os team release a base image, the platform release platform image, and the app team release the app image, all the image only contain the stuff developed by themselves without the base image, and the end user combine these image to an final image.  For example, os team release `base1`, platform team release `jvm1`,  app team release `app1`, the end user use something like `docker combine base1 jvm1 app1` and this create a `base1-jvm1-app1` image.  after some days, a CVE occur in `base1`, so the os team release `base2`, then the end user use `docker combine base2 jvm1 app1` to create a `base2-jvm1-app1` image.
 
* 2  image patch
If the base image release a patch, the end user get the patch use something like `docker patch` or other tools to apply the patch to the image and create a new image.  
This is similar to https://github.com/SUSE/zypper-docker

This  break the immutable infrastructure philosophy a little bit,  I want some feedback from the community and see if these are acceptable, or there is some other better solution, or convince they not to do this because this is not the future.

**Comment by AkihiroSuda** [comment]
I'd like to see the details of the proposed scenario. 
What does the OS team do? i.e. Why do you need a dedicated OS team, rather than just using official OS images (such as `alpine`, `ubuntu`, `centos`..)

**Comment by coolljt0725** [comment]
@AkihiroSuda  The OS team customize and maintain a OS base on the official OS.  And even using official OS, we still need to update the OS or patch the OS regularly to fix CVE or bug.

**Comment by thaJeztah** [comment]
This feels overly complicated, and basically comes down to the "app" team taking responsibility for both the "os" image _and_ the "platform" image.
What you're describing is that the "app" team is forking the "platform" image, and produces their own custom version. If that's the intent, why not use the Dockerfile of the "platform" team, and build their own version?

It sounds a bit "odd", because the "app" team is now building on top of an "os + platform" combination that was never tested, verified, or produced by the platform team.

If a team is not interested in updates from another team, they should "pin" their base image to a specific version. This can be done either by "convention" (i.e. the "os" team can use SemVer for image tags), or by using an [immutable identifier / digest](https://docs.docker.com/engine/reference/commandline/pull/#/pull-an-image-by-digest-immutable-identifier).

Of course, this would not solve the problem of the "app" team needing an update to the "os" image that is not yet made available by the platform team; if that's the need, the "app" team should build their own version of the "platform" image.


> we still need to update the OS or patch the OS regularly to fix CVE or bug.

If the "platform" team decides to ignore CVE's that sounds like an organizational problem (i.e., isn't the "platform" team responsible for providing a secure image to the teams building on top?)

I am not even sure how "patching" would work; take this very basic situation, but there are so many situations that would go horribly wrong;

OS:1

    echo "config-foo: bar" > /fileA && echo "OS-1" > /fileB

Platform:1

    echo "config-bar: baz" >>  /fileA

App:1

    cat /fileA
    
    config-foo: bar
    config-bar: baz


Now, OS releases an update

OS:1.1

    echo "config-foo: bar-newvalue" > /fileA && echo "OS-1.1" > /fileB


App-team switches to combination "OS:1.1" + "Platform:1", and ends up with..

    cat /fileA && cat /fileB
    
    config-foo: bar
    config-bar: baz
    OS-1.1


(Note that you can do this with `docker save`, swap layers, and `docker load`)

**Comment by coolljt0725** [comment]
@thaJeztah 
> If that's the intent, why not use the Dockerfile of the "platform" team, and build their own version?

We have suggest them to use the Dockerfile, but the problem is releasing a Dockerfile needs to release all the dependency (source code, binary, config etc..) for Dockerfile to build the image, releasing an image is much more convenient. 

>If a team is not interested in updates from another team, they should "pin" their base image to a specific version. This can be done either by "convention" (i.e. the "os" team can use SemVer for image tags), or by using an immutable identifier / digest.

Actually, the intent is not to "pin" their base image,  is to replace the base image more flexible. The `app1` can run on `base1`, and once `base1` goes to `base1.1`, we can replace `base1` with `base1.1` without rebuilding `app1`.

>but there are so many situations that would go horribly wrong;

This does a problem we also point out, it's rely on the user to ensure the compatibility. If `base1` goes to `base1.1`, the app team should test the app is compatible with `base1.1` and decide whether to release a new `app 1.1` or not.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
