### ISSUE TITLE
Docker does not propagate errors from runc during early initialization

### ISSUE THREAD

**Issue by Keno** [moby/moby#29669]
If runc decides to bail early in nsexec.c, this information is not properly reported back to the user, leading to a somewhat inscrutable error message. In particular, if any of these https://github.com/opencontainers/runc/blob/34f23cb99c30040e2ca82442eeb22d15a757f78d/libcontainer/nsenter/nsexec.c#L721-L731 checks fail, the error is not propagated anywhere, instead causing an error like:

```
ERRO[0016] containerd: start container                   error=oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:252: getting pipe fds for pid 131 caused \"readlink /proc/131/fd/0: permission denied\""
 id=4edeb4c668cc53404486853710fe5b3b6356503c2b104939b08048c55f2c355b
```

This is because the runc process died and became a zombie, so its fds are no longer available for reading. It would be good to pass the actual error from runc through that caused it to exit.

(I hope this is the right place to file this issue, please let me know if it isn't)

**Comment by mlaventure** [comment]
The error message we report is actually the one we get from `runc` itself.

The error you seem to show is not due to the process being dead or it would/should have been reported via a message containing `running exec setns process for init` also if the process had died, it would have been a `not found` type of error.

In your case, it's a permission denied, which is a bit puzzling

**Comment by Keno** [comment]
When processes die (but before their are reaped) their /proc entries get chowned to root, which causes the EPERM on the fd directory.

**Comment by mlaventure** [comment]
@Keno if it had died, the wait done before should have return an error though as part of the call to `execSetns()` if I'm not mistaken.

**Comment by Keno** [comment]
Not sure, I don't really speak Go, but I suspect, you may be waiting for `"runc:[0:PARENT]"` or `"runc:[1:CHILD]"` to finish, which it does successfully, but not `"runc:[2:CHILD]"`. That's a guess though. If

**Comment by mlaventure** [comment]
Hum, yes I guess the 2nd child could have died indeed. I think in this case, the log would only appear in the `runc`'s `log.json` file.

The issue is that this file would be deleted automatically by `containerd` since the start operation failed. I guess we could check for this in `containerd` if that's actually what's happening

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
