### ISSUE TITLE
Error response from daemon: Driver devicemapper failed to remove root filesystem d65f94bb142caa189d372b0faf92985b75a451ad82a17d6f9b40288dc98d1b17: Device is busy

### ISSUE THREAD

**Issue by zopyx** [moby/moby#29942]
I have the following script to restart a docker container via cron:

```
docker pull zopyx/plone-50-demo
docker kill plone-50-demo
docker rm plone-50-demo
docker rmi plone-50-demo
docker run --restart=always -d -p 127.0.0.1:12021:8080 --name plone-50-demo zopyx/plone-50-demo 
```

This fails pretty often with

```
[docker@vmd16513 ~]$ docker rm plone-50-demo
Error response from daemon: Driver devicemapper failed to remove root filesystem d65f94bb142caa189d372b0faf92985b75a451ad82a17d6f9b40288dc98d1b17: Device is Busy

```

The only solution is to restart the Docker service.

**
```
[docker@vmd16513 ~]$ docker version
Client:
 Version:         1.12.5
 API version:     1.24
 Package version: docker-common-1.12.5-3.git079fbe3.fc25.x86_64
 Go version:      go1.7.4
 Git commit:      079fbe3/1.12.5
 Built:           Thu Dec 22 16:19:13 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.5
 API version:     1.24
 Package version: docker-common-1.12.5-3.git079fbe3.fc25.x86_64
 Go version:      go1.7.4
 Git commit:      079fbe3/1.12.5
 Built:           Thu Dec 22 16:19:13 2016
 OS/Arch:         linux/amd64
[docker@vmd16513 ~]$ docker info
Containers: 5
 Running: 3
 Paused: 0
 Stopped: 2
Images: 5
Server Version: 1.12.5
Storage Driver: devicemapper
 Pool Name: docker-8:2-1074779972-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 12.07 GB
 Data Space Total: 107.4 GB
 Data Space Available: 95.3 GB
 Metadata Space Used: 16.24 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.131 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.136 (2016-11-05)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: oci runc
Default Runtime: oci
Security Options: seccomp
Kernel Version: 4.8.15-300.fc25.x86_64
Operating System: Fedora 25 (Server Edition)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 6
Total Memory: 23.55 GiB
Name: vmd16513.contabo.host
ID: TMBJ:KNSY:TYUM:XQBE:MABF:4ZH3:BHKE:QMFY:OTIL:HZYV:UNGT:ONR7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Registries: docker.io (secure)
```

**Comment by thaJeztah** [comment]
Are you running other containers that bind-mount directories perhaps? There's a troubleshooting section on this; https://docs.docker.com/engine/admin/troubleshooting_volume_errors/#/error-unable-to-remove-filesystem, but there are many possible reasons for a process to keep a mount busy.

**Comment by zopyx** [comment]
I am not working with volumes, nothing related to /var/lib/docker. There only three containers running on the box, nothing special nothings, no custom docker configuration.

**Comment by thaJeztah** [comment]
It would be worth trying to find out _what_ process is keeping the device busy. Possibly one of the other issues reporting these errors [give some pointers](https://github.com/docker/docker/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20%22device%20is%20busy%22). Unfortunately, there's no "single" answer for this, as there's many reasons this may occur, so it may be worth trying to get extra information.

**Comment by marcelmfs** [comment]
I'm also seeing this error with docker 1.12.5 using driver overlay2.

**Comment by cpuguy83** [comment]
The reason you'd get such an error is because the mount has leaked into another namespace or the filesystem contains mounts which exist in other namespaces.

We're working on a better model for handling mounts all the way down the stack. Ideally, IMO, docker wouldn't be changing any mounts in it's own namespace and instead pass down a clean mount namespace to runc, but this is not supported by runc right now. In addition I believe runc also does some mounting in whatever namespace it happens to be initiated from.

In the meantime you could either configure the systemd unit file (if you are using systemd) with `MountFlags=slave` or, even better `MountFlags=private`.
If you are not using systemd, you can start docker with `unshare -m dockerd <docker opts>`.
Some issues that may come up when doing this:
Either way, this will create a new mountspace when starting up docker.

- You will not be able to use a **containerized** volume plugin
- You must let docker manage containerd (which it does by default, but can be configured otherwise) since containerd (and runc) must run in the docker daemon's mount namespace.


That said, I would not generally expect such an issue in a fresh daemon that's not using any volumes or bind mounts @zopyx.
I have seen some issues with `containerd-shim` getting stuck and holding a reference to a mount which could be the case here.
If you have any of these processes running (should be 1 per running container) it might be helpful to grab the output from `/proc/<pid>/mountinfo` in order to see if any are holding a reference to a mount using this devicemapper device.

**Comment by marcelmfs** [comment]
Does the assumption on troubleshooting `/proc/<pid>/mountinfo` also applies to other drivers or that's specific to devicemapper? Thanks for the troubleshoot advice though!

**Comment by cpuguy83** [comment]
@marcelmfs All drivers.

**Comment by marcelmfs** [comment]
Cheers! :smile:

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale, and devicemapper was removed
