### ISSUE TITLE
Support for named single-file volumes

### ISSUE THREAD

**Issue by JensPiegsa** [moby/moby#30310]
Single-file Docker volumes are great to replace / insert configuration files.

But the current implementation has some major limitations:

1. you cannot replace the container without the file at place. (this makes the container dependant on the structure of the host fs).
2. two containers cannot share the same file.
3. a single-file volume is not listed as a volume.

Use cases for single-file volumes cannot be transformed into use cases with folder-based volumes without forcing the application to restructure their file system.

**Comment by justincormack** [comment]
Single file mounts are a feature that only exists on Linux, and are not available on other Unix platforms or on Windows, so I am not sure if adding this is a generic feature is a good idea.

Can you not use symlinks to have the same effect for configuration files? Build the container with a symlink pointing at `/config/.../config-file` and then mount a config volume in `/config`?

**Comment by JensPiegsa** [comment]
Ok, I was not aware of the plattform-specific limitations of this feature.

Working with symlinks like shown indeed solves the problem from the perspective of the image author.

From the user perspective this cannot be achieved for images that are not designed in this way. A lot of public Docker images therefore loose their flexibility in terms of advanced configuration. Apart from the comfort Docker provides, it just feels odd that switching one config file requires a whole new Docker image.

**Comment by Illydth** [comment]
I'll leave a comment here:

MySQL (Or pretty much any DB)
NginX (Or pretty much any web front end)
Jenkins (And pretty much any other CI/CD Pipeline Application)

The list goes on and on and on of use cases where you need to be able to configure the application running within the docker container without creating 100's of copies of that same docker container.  

In my Fortune 500 org we have about 100 Apache Containers running with slightly different config files for each customer (hard separation requirements by the customers require we don't run multiple customers in the same apache instance as Virtual Hosts).

I cannot move these to swarm / volume drivers to take advantage of orchestration / container failover without building a hundred or so one-off containers and then coding an entire stop/start infrastructure (that has to be modified each time a new customer onboards) for them.

This is one of the most simple/basic tasks with single server docker.

**Comment by justincormack** [comment]
Can you use docker config for this use case?

https://docs.docker.com/engine/swarm/configs/

**Comment by Illydth** [comment]
@justincormack Yea, so just to loop back around on this (apologies for the thread necro) Docker Config should (and in my case does) fix the use case for single file "volume" (bind) mounts.  

Not sure how I missed that little feature but it does fix all the use cases in my prior message.

Thanks for the direction on this.

**Comment by thaJeztah** [comment]
Yes, I think we should close this issue now that we have both configs and secrets for services. In addition, we added the `--mount` option for `docker run` (already existed for `docker service create`), which will produce an error if the source file/directory doesn't exist, instead of silently ignoring and creating a directory on the host.

Closing this issue, but feel free to discuss.

**Comment by masaeedu** [comment]
@thaJeztah You support neither subpaths of folder-based named volumes (#32582), nor single-file named volumes (#30310), nor mounting of volumes from the filesystem where a docker client binary is invoked (out of the box anyway). As a result it's impossible to put a file in a named volume and then simply mount that single file into a target location adjacent to other, non-volume files. Could you please fix whichever of #32582 and #30310 is easiest to fix?

I can't use host volumes because they basically reduce a shared docker host to SPOF filesystem-wise, which defeats the point of containerization.

**Comment by replaysMike** [comment]
+1 for wishing this was a supported scenario today.
