### ISSUE TITLE
Docker container exit code has unexpected value when program aborts

### ISSUE THREAD

**Issue by delcypher** [moby/moby#30593]
**Description**

When running a simple C program inside a container that calls the C standard library `abort()` function I expected the reported exit code of the container to be 134 (following bash's convention of making the exit code be `128` + 6 (SIGABRT) see http://tldp.org/LDP/abs/html/exitcodes.html ). Instead Docker reports that the container exits with exit code 139 (If bash's convention was being followed that exit code would imply SIGSEGV).

I'm not sure if this is a bug or not because I don't know what Docker's convention is for handling the exit codes of processes that terminated due to a signal being sent.

To be honest rather than relying on the exit code it would be more useful to me if the status of a docker container reported if the main process was killed and if so which signal killed it.

**Steps to reproduce the issue:**
1. Compile a simple C program to call abort

```c
#include <stdlib.h>
int main() {
  abort();
}
```

```
gcc -static abort.c -o abort
```

2. Run the binary inside a container

```
docker run --name="foobar" -ti -v `pwd`/abort:/tmp/abort ubuntu:14.04 /tmp/abort
```

3. Inspect the exit code

```
docker inspect -f '{{.State.ExitCode }}' foobar
139
```

**Describe the results you received:**

Reported exit code is `139`

**Describe the results you expected:**

I expected the exit code to be `134`.

**Additional information you deem important (e.g. issue happens only occasionally):**

If I run this the program like I get the exit code I expect

```
$ docker run --name="foobar" -ti -v `pwd`/abort:/tmp/abort ubuntu:14.04 /bin/bash -c '/tmp/abort; exit $?'
/bin/bash: line 1:     6 Aborted                 (core dumped) /tmp/abort
$ docker inspect -f '{{.State.ExitCode }}' foobar 
134
```

**Output of `docker version`:**

```
docker --version
Docker version 1.12.6, build 78d18021ec
```

**Output of `docker info`:**

```
$ docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 102
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host null bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.8.13-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.708 GiB
Name: dan-sputnik
ID: <redacted>
Docker Root Dir: /home/dan/docker
Debug Mode (client): false
Debug Mode (server): false
Username: delcypher
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by tonistiigi** [comment]
@mlaventure Do you know what is causing the difference?

**Comment by mlaventure** [comment]
Hum, `containerd-shim` is the one providing the exit status, normally it should return `128 + SignalNR`. I'll check what we get back from `Wait4`

**Comment by mlaventure** [comment]
We actually are  receiving `11` as the termination signal from `Wait4`. It may be something to do with the way `runc` starts the process

**Comment by thaJeztah** [comment]
@delcypher @mlaventure is this still an issue in the current release?

**Comment by mlaventure** [comment]
Still is, it's something to do with runc though, never had the time to dig deeper.

**Comment by f-squirrel** [comment]
Hi folks,
I have looked into this issue and I want to share the results of my investigation, which turned out to be quite intriguing.

The contained application has PID 1, which means that the Linux kernel treats it as a standalone init process for this namespace. The Linux kernel handles signals differently for the init process than it does for other processes. Signal handlers are not automatically registered for this process, meaning that signals will not take effect by default.
Since the contained application does not have user-defined signal handlers and the kernel does not register the default ones, the SIGABRT signal sent by the abort function is not handled at all.
In this situation, [abort](https://github.com/bminor/glibc/blob/master/stdlib/abort.c#L107) tries to kill the application by executing a forbidden asm instruction "HLT". As a result, the CPU sets the GPF interruption and the kernel kills the contained application with `SIGSEGV`, which leads to the exit code 139. Docker just sets its exit code accordingly.

The easiest way to make the contained application to have the default signal handlers is to run docker with the flag [--init](https://docs.docker.com/engine/reference/run/#specify-an-init-process).

For an expanded explanation on how signals are handled in a docker container, I have provided a detailed answer with visual examples in my [article](https://ddanilov.me/how-signals-are-handled-in-a-docker-container).

**Comment by cpuguy83** [comment]
@f-squirrel Wow thanks for investigating this old issue.

Totally makes sense.
Also confirmed locally this is the case.

**Comment by thaJeztah** [comment]
Perhaps we should expand the description in https://github.com/docker/cli/blob/v20.10.2/docs/reference/run.md#foreground and/or link to that post. Currently it mentions;

> **Note**
>
> A process running as PID 1 inside a container is treated specially by Linux:
> it ignores any signal with the default action. As a result, the process will
> not terminate on `SIGINT` or `SIGTERM` unless it is coded to do so.

Contributions welcome if someone is interested.
