### ISSUE TITLE
[Feature Request] Running a command automatically in a container while stopping/killing it 

### ISSUE THREAD

**Issue by reallysaurabh** [moby/moby#30625]
**Description**
I am running a server (let say it's name is XYZ) inside a container. I can access it on my host machine on an ip. 

So, when I run an image in order to make a new container with a -P tag, it runs the image and assigns a port to it and it works perfectly.

Now, when I am stopping the container, it stops the container but not the server running in it. So, the problem is, when I start the container again, it runs the CMD as expected and shows a message that the server XYZ is already running and the container exits. So, I can't access the server again.

What I am looking for is a way to automatically run a command to stop the server (the command to stop server is ./server.stop) when I stop/kill a container.

**Comment by AkihiroSuda** [comment]
> Now, when I am stopping the container, it stops the container but not the server running in it. 

Please elaborate?

**Comment by Saurabh3012** [comment]
I have a software which I am running on an ubuntu:16.04 image inside a container. In my dockerfile, I have mentioned CMD ./server.start. This command starts the server. Now, while running I map this server to a port and able to access it when I create this container and it runs for the first time. These steps work fine.

![image](https://cloud.githubusercontent.com/assets/5724473/22504152/006b5fb4-e89b-11e6-83c5-95d3f4dd0914.png)

Now, when I kill the container, the server stops working in my host machine, and the container is stopped. this is also fine.

But, when I start the same container again, it gives me that the XYZ server is already running and stops the container and hence, I can't access my software server at assigned port. And since, the container does not start, I can't my console to the container. 

So, I need to stop the running server before I stop/kill the container. For this, the command is, let say,  "./server.stop" and I want it to run automatically when I use docker stop/kill command.

Am I clear now?

**Comment by cpuguy83** [comment]
You should not use "docker kill" unless you are going to specify a custom signal.
"docker kill" does a "kill -9".

Docker sends a signal to the process in the container. It's the duty of that process to handle the signal properly for itself. If it needs to run a cleanup script, that's great but it would need to be in the signal handler of the container process.

**Comment by Saurabh3012** [comment]
The problem is not yet clear, I guess.

I have a server running on an ubuntu image running in a container. When I stop the container the server does not stop.

So, when I start the container again it shows the server is already running and stops the container automatically. I want it to remain started when I start it again but it exits.

**Comment by AkihiroSuda** [comment]
> When I stop the container the server does not stop.

Do you hit the issue with official images?

I guess the issue is on your "Technology Platform" side.
I guess the container and all the processes (your "server") within it are stopped, but "Technology Platform" fails to detect the "server" is "stopped".

**Comment by thaJeztah** [comment]
@Saurabh3012 if the process in the container (your "server") does not respond to `docker stop`, or you manually `docker kill` the container, the "server" does not do a clean shutdown. The server is stopped, but may not clean up files. For example, apache will refuse to start if the [`run/apache2/apache2.pid` file exists](http://stackoverflow.com/questions/28654076/docker-container-wont-start-because-an-existing-pid-file). In that case it will show an error that apache is "already running", but it's not. 

Have a look at the official Apache docker image, which has an entrypoint script exactly for that; https://github.com/docker-library/httpd/blob/a5ab6fb434c13a3578a2e7e6ce2cf30d66c625bc/2.2/httpd-foreground#L1-L7

**Comment by thaJeztah** [comment]
closing, as this went stale and is really old now
