### ISSUE TITLE
docker daemon startup stuck with live-restore enabled and some processes in 'uninterruptible sleep' state

### ISSUE THREAD

**Issue by piontec** [moby/moby#31007]
**Description**
After failed upgrade from 1.12.6-cs8 to 1.13.1-cs1 (issue here: https://github.com/docker/docker/issues/31005), we tried to rollback to 1.12.6-cs8 again. This failed - dockerd couldn't start.

The last message in logs was, after it it was stuck:
```
Feb 13 14:54:09 ip-10-69-11-89 dockerd[121011]: time="2017-02-13T14:54:09.698063977Z" level=warning msg="containerd: 291eb612627c5472db8c0bc0d69e7c09a19f1f6e61214449e4f753a2be05ef07:init shim died, killing associated process"
```
We have live-restore enabled and we started to suspect that docker daemon can't run "container restore" on some containers. We found out we got 4 processes on the host, which are stuck in "uninterruptible sleep" (aka "D") state. These 4 processes were called "supervisord", "supervisord", "minit" and "bootstrap.sh"so  they all looked like typical primary processes of containers we're using (PID 1 in the container's namespace). These processes were all stuck on the same syscall "zap_pid_ns_processes":
```
# cat /proc/123558/wchan ; echo
zap_pid_ns_processes
# cat /proc/126411/wchan ; echo
zap_pid_ns_processes
# cat /proc/61025/wchan ; echo
zap_pid_ns_processes
# cat /proc/10853/wchan ; echo
zap_pid_ns_processes
```
We needed to restart our production host to recover this situation.

**Steps to reproduce the issue:**
1. It's hard to repeat this, as it seems to require processes stuck in "D" state.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
Docker 1.12.6-cs8 was used, but didn't start.

**Output of `docker info`:**
Since docker daemon didn't start, I don't have one. We used docker 1.12.6-cs8, live-restore and debug were enabled. There were about 300 containers running.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
On AWS, x1.32xlarge instance on Ubuntu 16.04. We should have debug level logs for this time period.

**Comment by mlaventure** [comment]
being stuck on `zap_pid_ns_processes` probably mean that some descendants of that namespace haven't been killed / reparented yet. Which in that case should only be execs.

Does those container have healthchecks? If so are any of those still alive?

**Comment by piontec** [comment]
Yes, probably; we have some containers, that have healthchecks and we got sometimes thousands (and steadily growing) ExecIDs associated with such container. See also https://github.com/docker/docker/issues/31614

**Comment by mlaventure** [comment]
@piontec were you able to verify if those process where actually alive?

**Comment by piontec** [comment]
@mlaventure Which processes do you mean? The processes in question were all in "D", waiting for `zap_pid_ns_processes`.  AFAIR (but I really can't be sure) processes from health checks were also stuck, and the ones in `zap_pid_ns_process` were their parents.

**Comment by mlaventure** [comment]
@piontec I was referring to the healthcheck processes yet.

Do you have their kernel thread stacks? Wondering what they are stuck on.

**Comment by matiaslespiau** [comment]
Hi @mlaventure, AFAIK @piontec reports are similar to what @adaiguoguo shared in #19895: http://keepfoolish.com/sys/docker-kill-issue.html

**Comment by adaiguoguo** [comment]
@matiaslespiau Sorry,I have changed my url.http://keepfoolish.com/kernel/docker-kill-issue.html

**Comment by thiagoalves** [comment]
@mlaventure I have found a way to reproduce the `zap_pid_ns_processes` kernel call issue with processes in "D" state.

It is possible to reproduce it on a AWS host with Ubuntu 16.04.2 and latest docker-ee versions (17.03.1-ee3 and 17.03.2-ee4)

Test steps:

- Run 300 test containers
```
for i in {1..300}; do docker run -d -it --restart=always --name poc_$i talves/health_poc; done
```
- Stop the containers
```
docker kill -s TERM $(docker ps -q)
docker stop $(docker ps -q)
```
- Start the containers
```
- docker start $(docker ps -aq)
```
- Check if there are processes in "D" state
```
ps -eo uid,pid,ppid,state,wchan:32,cmd | awk '$4 ~ "D" {print $5}' | sort | uniq -c
```
- Repeat the stop / start procedure above for a few times and check the processes again

**Comment by thiagoalves** [comment]
@mlaventure @cpuguy83 

I could confirm that this issue was fixed by http://patchwork.kernel.org/patch/9724743/ and will be available in linux kernel 4.12, which will be released in mid July. However I expect an Ubuntu official kernel with this patch only in version 16.04.4, which will be released in February 2018.

I can also confirm that this issue happens on both `aufs` and `overlay2`.

The issue can be fixed by a [mainline kernel](http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.12-rc5/), but it doesn't offer support for `aufs`. So I could only test `overlay2` and was able to reproduce the error on kernel 4.4, but not on 4.12

I also compiled [aufs-kernel](https://github.com/sfjro/aufs4-linux/tree/aufs4.x-rcN) and was able to run docker with `aufs` on 4.12. I was also able to fix the bug with the new version.

Unfortunately all our production hosts use `aufs`, as it seems to be the most stable and reliable storage driver.

We can't afford waiting for that long, since this issue is causing us many outages in production environments. Our only viable option so far is to use the compiled kernel in our hosts when version 4.12 is released.

We would prefer to use an official kernel from ubuntu though. However the mainline kernel doesn't support `aufs` and it doesn't have a `linux-image-extra` package.

We had another idea: backport this change (which is rather small) to a version that ubuntu is willing to support (e.g: 4.8 or 4.10) and have it released through their official apt repo on Aug 3 (16.04.3). We are not sure how feasible is this one - but if fixing this bug is important to docker, maybe you guys could work together with canonical to speed this up.

We are also interested in other possible solutions you may come up with.

Thanks in advance

**Comment by thaJeztah** [comment]
Let me /cc @sforshee here, but the first step would be to open a ticket / request with canonical

**Comment by sforshee** [comment]
That patch has made it back to the xenial 4.4 kernel from upstream stable, currently in -proposed (4.4.0-80.101). The xenial hwe kernels we don't have stable updates from upstream anymore, but we can still pull in the patch.

We will need a bug report in launchpad for all changes to stable releases, so please file a bug at this link:

https://bugs.launchpad.net/ubuntu/+source/linux/+filebug

Then point me to the bug and I'll get the fix queued up.

**Comment by thiagoalves** [comment]
@sforshee Please check https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1698264

Thanks for the support!

**Comment by thiagoalves** [comment]
@mlaventure @cpuguy83 @thaJeztah @sforshee The new linux-aws-1022 kernel solves the issue - we don't have processes stuck in D state anymore.

However a few docker containers are still hanged - but they are locked in a zombie (Z) state and the kernel stack shows the "exit" call on the top.

The main symptom is that we cannot remove the container. We suspect that killing the container shim and restarting the daemon removes it, but I will confirm and come back here

**Comment by thaJeztah** [comment]
thanks for the update!

**Comment by thiagoalvessilva** [comment]
I believe this one can be closed

**Comment by thaJeztah** [comment]
yeah, let's close
