### ISSUE TITLE
CpusetCpus not properly applied when Kernel isolcpus is set

### ISSUE THREAD

**Issue by RalfJung** [moby/moby#31086]
**Description**
We would like most of our CPU cores to be used exclusively by certain docker containers.
However, once we set the kernel `isolcpus` parameter to ensure certain cores are not used at all unless explicitly specified, the containers all use only a single CPU.

**Steps to reproduce the issue:**
1. Set the isolcpus parameter to `0-17,20-37` so that only CPUs 18,19,38,39 are used by most processes.
2. For the relevant Docker containers, we have set `"CpusetCpus": "0-5,20-25"` (that's from the output of `docker inspect`).
3. Start a multi-core job (`make -j12`) in the container.

**Describe the results you received:**

The job uses only CPU 0. The other 11 CPUs reserved for this container are not used at all.

**Describe the results you expected:**

All 12 CPUs should be used by the container.

**Additional information you deem important (e.g. issue happens only occasionally):**

If we do not set `isolcpus`, docker behaves as expected. However, in this case, other system processes (and docker management itself) could be using cores that we want to reserve exclusively for a particular container.

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:36:34 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:36:34 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 6
 Running: 1
 Paused: 0
 Stopped: 5
Images: 2
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Kernel Version: 4.4.41.1.amd64-smp
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 125.7 GiB
Name: coop
ID: QMDB:3GOA:BPZZ:YKGA:4AFQ:255M:PJ3H:O5SX:V45L:Y3RH:7PBB:D6ZL
Docker Root Dir: /local/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is a CI machine, so the docker containers are all created and managed by gitlab-ci-multi-runner.

**Comment by RalfJung** [comment]
Here's the full `docker inspect` for one of the affected containers:
```
[
    {
        "Id": "5bdfb3a1df2efb49f92ae6d051eb491c7f847dce9a3c5c49846d980928a9d678",
        "Created": "2017-02-16T14:04:25.456405769Z",
        "Path": "sh",
        "Args": [
            "-c",
            "if [ -x /usr/local/bin/bash ]; then\n\texec /usr/local/bin/bash \nelif [ -x /usr/bin/bash ]; then\n\texec /usr/bin/bash \nelif [ -x /bin/bash ]; then\n\texec /bin/bash \nelif [ -x /usr/local/bin/sh ]; then\n\texec /usr/local/bin/sh \nelif [ -x /usr/bin/sh ]; then\n\texec /usr/bin/sh \nelif [ -x /bin/sh ]; then\n\texec /bin/sh \nelse\n\techo shell not found\n\texit 1\nfi\n\n"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 33067,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-02-16T14:04:37.966904499Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:c4561626674efe1ed4555663823ba38cf53b920641c740bd8036567dd2d86712",
        "ResolvConfPath": "/local/docker/containers/5bdfb3a1df2efb49f92ae6d051eb491c7f847dce9a3c5c49846d980928a9d678/resolv.conf",
        "HostnamePath": "/local/docker/containers/5bdfb3a1df2efb49f92ae6d051eb491c7f847dce9a3c5c49846d980928a9d678/hostname",
        "HostsPath": "/local/docker/containers/5bdfb3a1df2efb49f92ae6d051eb491c7f847dce9a3c5c49846d980928a9d678/hosts",
        "LogPath": "/local/docker/containers/5bdfb3a1df2efb49f92ae6d051eb491c7f847dce9a3c5c49846d980928a9d678/5bdfb3a1df2efb49f92ae6d051eb491c7f847dce9a3c5c49846d980928a9d678-json.log",
        "Name": "/runner-aa21fae1-project-118-concurrent-0-build",
        "RestartCount": 0,
        "Driver": "overlay2",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [
                "543ff5472d4c6a71d62736179b778f72f753b0c72e3be23cffe2e416e4b6d078",
                "70f762560854fd1ff54127cd5297a8363792b3eea47d2b799bd46791e5cfda77"
            ],
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "12-17,32-37",
            "CpusetMems": "",
            "Devices": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Name": "overlay2",
            "Data": {
                "LowerDir": "/local/docker/overlay2/2352a0d9e59fe639e6fe4799aafd756a07e07cae6bd4355e15a3c5586800a2ef-init/diff:/local/docker/overlay2/68f7a49440769ea76e7b3f937069c26e7c23e698eae1b4a55c587ce5c826a630/diff:/local/docker/overlay2/365c889a262c6f03c77d9487a1e8d71632e08f4eb86ca6119361683d03e71e97/diff:/local/docker/overlay2/0543da64bc278c4d644a05ad94747e56307a8dc97e4a2d43b25ac1d49a2a9adc/diff",
                "MergedDir": "/local/docker/overlay2/2352a0d9e59fe639e6fe4799aafd756a07e07cae6bd4355e15a3c5586800a2ef/merged",
                "UpperDir": "/local/docker/overlay2/2352a0d9e59fe639e6fe4799aafd756a07e07cae6bd4355e15a3c5586800a2ef/diff",
                "WorkDir": "/local/docker/overlay2/2352a0d9e59fe639e6fe4799aafd756a07e07cae6bd4355e15a3c5586800a2ef/work"
            }
        },
        "Mounts": [
            {
                "Name": "4903d91ccaf7d96e08e10974ef39860c47e376f8594efb477307630052d3157e",
                "Source": "/local/docker/volumes/4903d91ccaf7d96e08e10974ef39860c47e376f8594efb477307630052d3157e/_data",
                "Destination": "/builds/FP",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Name": "f78ca8c167f7894b1ca9fda76021381ac31142748f0ade758e5ab429d109bc15",
                "Source": "/local/docker/volumes/f78ca8c167f7894b1ca9fda76021381ac31142748f0ade758e5ab429d109bc15/_data",
                "Destination": "/cache",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "runner-aa21fae1-project-118-concurrent-0",
            "Domainname": "",
            "User": "ci",
            "AttachStdin": true,
            "AttachStdout": true,
            "AttachStderr": true,
            "Tty": false,
            "OpenStdin": true,
            "StdinOnce": true,
            "Env": [
                <REDACTED>
            ],
            "Cmd": [
                "sh",
                "-c",
                "if [ -x /usr/local/bin/bash ]; then\n\texec /usr/local/bin/bash \nelif [ -x /usr/bin/bash ]; then\n\texec /usr/bin/bash \nelif [ -x /bin/bash ]; then\n\texec /bin/bash \nelif [ -x /usr/local/bin/sh ]; then\n\texec /usr/local/bin/sh \nelif [ -x /usr/bin/sh ]; then\n\texec /usr/bin/sh \nelif [ -x /bin/sh ]; then\n\texec /bin/sh \nelse\n\techo shell not found\n\texit 1\nfi\n\n"
            ],
            "Image": "sha256:c4561626674efe1ed4555663823ba38cf53b920641c740bd8036567dd2d86712",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.gitlab.gitlab-runner.build.before_sha": "0e86bc6d08adea502aa7ef46b2100676153ca974",
                "com.gitlab.gitlab-runner.build.id": "2649",
                "com.gitlab.gitlab-runner.build.ref_name": "ci",
                "com.gitlab.gitlab-runner.build.sha": "0e86bc6d08adea502aa7ef46b2100676153ca974",
                "com.gitlab.gitlab-runner.project.id": "118",
                "com.gitlab.gitlab-runner.runner.id": "aa21fae1",
                "com.gitlab.gitlab-runner.runner.local_id": "0",
                "com.gitlab.gitlab-runner.type": "build"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "705a9da8e65fe71aafcba90c9583e3891e61c79bc0a74a0d57b94600fb5c1c2b",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/705a9da8e65f",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "44cba30f8834baf9982574556e55b5457fa85e8c48bbd5d797055fd27b9e62b4",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "afbb214e9f8654a511c12afcce3a4fce35e3948d9a2073d5ce0e6d2497ed1ba5",
                    "EndpointID": "44cba30f8834baf9982574556e55b5457fa85e8c48bbd5d797055fd27b9e62b4",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02"
                }
            }
        }
    }
]
```

**Comment by RalfJung** [comment]
Actually docker may not be at fault here, it seems like isolcpus is pretty much broken... also see <https://serverfault.com/questions/573025/taskset-not-working-over-a-range-of-cores-in-isolcpus>.

**Comment by neomantra** [comment]
I think this is a real issue.   It is also covered here: https://github.com/snabbco/snabb/issues/476

The `dockerd` daemon itself and `docker-containerd` is running according to isolcpu rules.  Docker is properly pinning cores when `-c` is used.   But when `-c` is not being used, the CPU affinity of the new container is indeed all the cores.  I'm starting to look deeper at why...

**Comment by thaJeztah** [comment]
@RalfJung @neomantra looking at the above, this doesn't look like a docker issue, but an issue in the kernel. Do you think it's worth documenting this?

**Comment by neomantra** [comment]
I'm still diving through Docker (moby) and runc sources to understand what's going on.  I'm not convinced that it is a kernel issue.  I have tried on kernel 3.2 and 3.4 and have the same issue, also Docker 1.12 through the latest.

I DO think that if it is intentional, then it should be more clearly documented.  I learned the hard way that this is the behavior and from Googling I see I'm not the only one. 

It also doesn't make sense -- why should  Docker run default-assign a CPU affinity that is different from the kernel's? 

As you've closed this, I will open a new issue with more specific steps to reproduce and some understanding of what's up.

**Comment by RalfJung** [comment]
I think this is not a Docker issue at all. isolcpus seems pretty much broken to me. We are using systemd's `CPUAffinity` now instead.

**Comment by delcypher** [comment]
@RalfJung Thanks for reporting this. I had a very frustrating hour trying to figure out what was happening until I found your report.

It does seem like this actually a kernel issue the [server fault issue you link to](https://serverfault.com/questions/573025/taskset-not-working-over-a-range-of-cores-in-isolcpus). I've confirmed this behaviour when running outside of docker and using the `taskset` command. Only one of the pinned CPUs gets used even if multiple cpus are available.

The page you linked to noted that changing the scheduler from `SCHED_OTHER` to `SCHED_RR` (using the `chrt` command) works around the issue. It's not really ideal though.

I presume your systemd solution is to set CPUAffinity of the init process as [documented here](https://www.freedesktop.org/software/systemd/man/systemd-system.conf.html)?

@neomantra 
> As you've closed this, I will open a new issue with more specific steps to reproduce and some understanding of what's up.

Did you ever create the new issue you mentioned above?

@thaJeztah 
> @RalfJung @neomantra looking at the above, this doesn't look like a docker issue, but an issue in the kernel. Do you think it's worth documenting this?

Yes I think this should be documented. I wasted a bit of time playing with the `--cpus`, `--cpu-quota`, `--cpu-period` which don't help in this situation.

**Comment by RalfJung** [comment]
> I presume your systemd solution is to set CPUAffinity of the init process as documented here?

Correct. This is inherited by all the other processes.

**Comment by neomantra** [comment]
@delcypher My issue is different from @RalfJung.  I have no problem with `isolcpus` -- I've been using it for half a decade on Ubuntu 12.04 and 16.04 without issue.  That doesn't mean there isn't a problem as outlined in the issue, just I don't experience it.   I have experimented with `CpuAffinity` on my `systemd` systems (16.04) and the behavior is identical to an `isolcpus` setup.

I bet that the issue I'm having affect's your setups... and that's that running containers *WITHOUT*  an explicit `--cpuset-cpus` will run the container on *ALL CPUs*, not on the cpuset specified with `CpuAffinity` or `isolcpus`.   You can verify this by running a container and then diving the process hierarchy and looking at its taskset.

I'm also am now convinced that this is not a bug, but just poorly documented.  Fundamentally, how can moby know whether you affinitized CPUs because you want containers to run there or because you don't want containers to run there.   This [libvirt discussion](https://www.redhat.com/archives/libvir-list/2015-July/msg00136.html) in the context of VMs fixed my thinking:
```
From the libvirt POV, we can't tell whether the admin set isolcpus
because they want to reserve those CPUs only for VMs, or because
they want to stop VMs using those CPUs by default. As such libvirt
does not try to interpret isolcpus at all, it leaves it upto a
higher level app to decide on this policy.
```

**Comment by delcypher** [comment]
@neomantra 

> I bet that the issue I'm having affect's your setups... and that's that running containers WITHOUT an explicit --cpuset-cpus will run the container on ALL CPUs, not on the cpuset specified with CpuAffinity or isolcpus. You can verify this by running a container and then diving the process hierarchy and looking at its taskset.

I was using a rather old version of Docker 1.12 and I have since upgraded to `17.06.0-ce` and have switched to the systemd approach of setting `CpuAffinity`. For the older version of Docker when I was using `isolcpus` I did not experience all cpus being given to containers despite them being isolated.

With my new set up (Docker `17.06.0-ce` and using systemd's `CpuAffinity`) I see the behaviour you mention. With no `--cpuset-cpus` arguments the docker container is using all cpus and `CpuAffinity` is effectively being ignored.

For my current set up I'm always setting `--cpuset-cpus` which is why I've not experienced your problem before with the newer Docker version.

> I'm also am now convinced that this is not a bug, but just poorly documented. Fundamentally, how can moby know whether you affinitized CPUs because you want containers to run there or because you don't want containers to run there. This libvirt discussion in the context of VMs fixed my thinking:

For **your issue** (cpu affinity set external to docker being ignored with `--cpus-setcpus` is not passed), yes I agree this is an issue of documentation. However docker could make things easier by providing a daemon option which controls the set of cpus that can be used for containers (by default this would be all).

For the **original** issue (when using `isolcpus` and `--cpuset-cpus` only one processor will be used even if pinned to multiple cpus) as noted previously this seems like a kernel bug because it can be reproduced outside of Docker (I'm using Ubuntu 16.04 too by the way). Using systemd's `CpuAffinity` option seems to be a sensible workaround. We could provide documentation here too.

So in both cases I think we should document the current behaviour and the recommended workarounds.

**Comment by neomantra** [comment]
@delcypher So I use `isolcpus` because I have latency-sensitive workloads that I want to run there (either containerized or not).  Out-of-the-box, simple docker runs can interrupt these workloads (which of course one learns the hard way and by Murphy's Law happens at exactly the wrong moment).

Here's how I address it...

1) Write a systemd / upstart unit that creates a cgroup at boot.  I use Ansible and different machines have different CPUs isolated, hence the template arguments below.  In my case, I make it so that it is the inverse of my `isolcpus` (e.g. if isolating cores 1,3 of 4, I set this to 0,2).  I also control the memory nodes here.
```
	mkdir -p /sys/fs/cgroup/cpuset/dockercg
	/bin/echo "{{ dockercg_cpus }}" > /sys/fs/cgroup/cpuset/dockercg/cpuset.cpus
	/bin/echo "{{ dockercg_mems }}" > /sys/fs/cgroup/cpuset/dockercg/cpuset.mems
```

2) Assign this cgroup in Docker's `daemon.json`. Now plain `docker run`s will stay off the isolated cores:
```
{ "cgroup-parent" : "dockercg" }
```

3) Now when I `docker run` with `--cpuset-cpus=<isolated-cores>`, I need to also add `--cgroup-parent=""` because the new default cgroup prevents access to those isolated cores.
```
docker run --cgroup-parent="" --cpuset-cpus=1,3 ...
```

**Comment by numberZero** [comment]
> Fundamentally, how can moby know whether you affinitized CPUs because you want containers to run there or because you don't want containers to run there. This libvirt discussion in the context of VMs fixed my thinking:
> > From the libvirt POV, we can't tell whether the admin set isolcpus
because they want to reserve those CPUs only for VMs, or because
they want to stop VMs using those CPUs by default. As such libvirt
does not try to interpret isolcpus at all, **it leaves it upto a
higher level app to decide on this policy.**

So why doesn’t Docker leave it to the higher level? Why does it reset affinity instead of inheriting it by default like all the other services on the system? This way, it’s broken regardless of were CPUs isolated for or against containers. Even worse, container threads that happened to run on an isolated CPU *don’t migrate from it*, neither their children do.
