### ISSUE TITLE
docker-engine-selinux-17.03 conflicts with container-selinux-2.10.el7 on RHEL7.3

### ISSUE THREAD

**Issue by mlcooper** [moby/moby#31651]
When doing a `yum install docker-engine-1.13.1-1.el7.centos`, it installs the dependency `docker-engine-selinux-17.03.0.ce-1.el7.centos`.  

Afterwards, when I do a `yum install container-selinux-2.10-1.el7.noarch`, which is built from https://github.com/projectatomic/container-selinux/tree/RHEL-1.12, I get an error:
```
Error: docker-engine-selinux conflicts with container-selinux-2.10-1.el7.noarch
```
The maintainers of this projectatomic repo that releases `container-selinux` say this is a bug in `docker-engine-selinux` and that this should go away and just `container-selinux` should be used.  

**Please see full details here:**
https://github.com/projectatomic/container-selinux/issues/35

**Steps to reproduce the issue:**
1.  Build `container-selinux-2.10-1.el7.noarch` from https://github.com/projectatomic/container-selinux/tree/RHEL-1.12 with the .spec file here:  https://src.fedoraproject.org/cgit/rpms/container-selinux.git/tree/container-selinux.spec . Change line 9 to the latest commit id on RHEL-1.12 branch, then run `spectool -g container-selinux.spec`
2.  Install docker-engine-1.13.1 on a RHEL7.3 box
3.  Install `container-selinux-2.10-1.el7.noarch`

**Describe the results you received:**
You will receive the error:
```
Error: docker-engine-selinux conflicts with container-selinux-2.10-1.el7.noarch
```
**Describe the results you expected:**
Expected `container-selinux-2.10-1.el7.noarch` to install without error

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
Attempting to install `docker-engine-1.13.1-1.el7.centos` which pulls `docker-engine-selinux-17.03.0.ce-1.el7.centos`

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This is all being done on RHEL 7.3 VM's running in OpenStack or VMware.

**Comment by cpuguy83** [comment]
`docker-engine-selinux` does not mark container-selinux as conflicting, it's the other way around.
Also yes they do conflict since they have duplicate entries.

**Comment by mlcooper** [comment]
@cpuguy83 In either order that you install `docker-engine`/`docker-engine-selinux` and `container-linux` the conflict error above occurs.

The maintainers of the `container-selinux` repo maintain that the root cause here is a bug in `docker-engine-selinux`, which they feel should go away and just `container-selinux` should be used.

**Comment by mlcooper** [comment]
@cpuguy83 this issue feels similar to https://github.com/docker/docker/issues/31556

I'm blocked from using `container-selinux` on RHEL7.3, and the projectatomic maintainers say it's a bug in docker-engine-selinux.  Do you have any suggestion of how to move forward?

**Comment by cpuguy83** [comment]
@mlcooper Thanks for reporting. Just FYI, the docker packages have not changed at all in this regard.

@rhatdan Can we please have some collaboration here rather than throwing stuff across the fence.
The selinux packages on rhel/centos have included breaking changes on multiple minor release versions now.

Happy to use container-selinux here, but we recently tried to do this (with docker-selinux at the time) and it didn't work because the packages were too outdated (#29114), so it seems like no matter what we'll have to upstream the repo and provide our own (conflicting) packages.

As it is `container-selinux` is not useful as something to build on top of. I would expect that docker packages provides things like setting labels on docker installed binaries but to rely on something like container-selinux to provide the low-level types for containers to use, currently (previously???) provided by the `selinux-policy` package.

Please let me know how you'd like us to proceed in handling these packaging issues.

**Comment by andrewhsu** [comment]
@rhatdan I wouldn't mind taking another stab at #29114 to get it working if you have suggestions

**Comment by rhatdan** [comment]
If docker-engine-selinux needs addiitonal allow rules to what is provided to the current container-selinux then it should install policy without defining types defined in the base container-selinux

policy_module(docker-engine, 1.0)
gen_require(`
          type container_runtime_t;
          type container_t;
          type container_file_t;
')

allow container_t TARGET_T:process connecto;
...

We will never be able to coordinate both packages creating the same types.

**Comment by cpuguy83** [comment]
What if container-selinux specifically conflicts with known conflicting versions of `docker-engine-selinux`, and `docker-engine-selinux` only provides the diff for what it needs for a given release.

To that end if `container-selinux` is going to carry definitions specific to docker, `docker-engine-selinux` can really be a meta package like `Requires: docker-selinux-policy >= 1.13` (just as an example), and we can supply the diff package with `Provides: docker-selinux-policy = 1.13`, then `container-selinux` can specify the version of `docker-selinux-policy` it provides as well.

*note, really not an rpm expert and this is just a general idea.

**Comment by rhatdan** [comment]
container-selinux is a package in the distribution, it will not refer to a package outside of the distribution.
If container-selinux conflicts with docker-engine-selinux then docker-engine-selinux should have a 
confilicts container-selinux in its spec file to prevent it from being installed.

container-selinux contains paths specific to docker but is also used to enforce rules on other container runtimes including, ocid/cri-o, runc, rkt, lxc, systemd-nspawn.

Bottom line this should be little case when docker-engine-selinux has rules that conflict with container-selinux, unless their are rules that docker-engine does not like.  Since you can always add allow rules, the only case where docker-engine-selinux would not want container-selinux would be if it thought it was too loose of a policy.

If people find rules that are missing from container-selinux,  they should open pull requests for the container-selinux policy to get the rules added, then in a future release they will show up in the distribution.

My fear is that someone who does not understand SELinux starts adding rules to containers that make them insecure, just to make the containers run.  They should be reviewed just like any other security modification.

**Comment by unidev007** [comment]
I am an end user, I have a Centos7 with all latest updates and tried to install docker-ce and got this error 

![image](https://cloud.githubusercontent.com/assets/26779699/24787603/2f159cca-1b1e-11e7-80b4-ea45e0b21eb3.png)

When will this issue be resolved ? Any ETA ?

**Comment by cpuguy83** [comment]
Opened #32437 to attempt to resolve this

**Comment by dtmistry** [comment]
Not sure if this is related, but I'm getting the below error when trying to install the 17.06 on Centos

```
Resolving Dependencies
--> Running transaction check
---> Package docker-ce.x86_64 0:17.06.0.ce-1.el7.centos will be installed
--> Processing Dependency: container-selinux >= 2.9 for package: docker-ce-17.06.0.ce-1.el7.centos.x86_64
--> Finished Dependency Resolution
Error: Package: docker-ce-17.06.0.ce-1.el7.centos.x86_64 (docker-ce-stable)
           Requires: container-selinux >= 2.9
 You could try using --skip-broken to work around the problem
```

**Comment by cpuguy83** [comment]
@dtmistry You need to enable the "extras" repo, which is typically already enabled on centos.
`yum-repo-manager --enable extras`

Closing this issue since it's resolved with 17.06, which now depends on container-selinux instead of providing a separate package.

**Comment by dtmistry** [comment]
Thanks @cpuguy83. I did not realize we had a custom repo as [extras]

**Comment by DMEvanCT** [comment]
yum remove docker-ce-selinux
wget ftp://ftp.icm.edu.pl/vol/rzm6/linux-centos-vault/7.3.1611/extras/x86_64/Packages/container-selinux-2.9-4.el7.noarch.rpm
rpm -Uvh container-selinux-2.9-4.el7.noarch.rpm
yum install docker-ce
