### ISSUE TITLE
Client attempts to validate secret target using "filepath"

### ISSUE THREAD

**Issue by aaronlehmann** [moby/moby#31897]
https://github.com/docker/docker/blob/950658bbb63480de254a166bdeaef1fc8b8fe644/opts/secret.go#L56-L59

I don't think this will work correctly on a Windows client talking to a Linux engine, or vice versa.

cc @dnephin @ehazlett

**Comment by dnephin** [comment]
I think you're right. It should probably be handled by the engine

**Comment by aaronlehmann** [comment]
I don't think handling it in the engine would be correct either. The engine might be running on a different platform from the one where the service will ultimately be deployed.

IIRC there is also a similar validation check in the swarmkit manager, which would also need to be fixed.

I don't believe we support secrets on Windows at the moment, but once we do this will become an issue.

cc @johnstep @nishanttotla

**Comment by johnstep** [comment]
Agreed, and the same secret can be used for different services, making it difficult to validate during secret creation since it can be (valid on one platform, and invalid on another. While late, maybe it makes sense to validate the target during service creation.

However, this brings up an interesting issue if we do add support for paths. The path will be (probably, maybe not always) platform-specific while the secret is not. I guess late verification works here too.

Secrets are not supported on Windows yet, but are coming.

**Comment by aaronlehmann** [comment]
These paths are actually part of the service definition, rather than being part of a secret. If we know what platforms a service may run on, we'll be able to validate the paths.

**Comment by johnstep** [comment]
Ah, right, makes sense.

**Comment by thaJeztah** [comment]
If multiarch images are taken into account we won't even know until the task lands somewhere; can we come up with some sensible restrictions for target (starting with `a-zA-Z0-9._-`)?

**Comment by nishanttotla** [comment]
@thaJeztah I'm working on adding support to extract platform information about the service at the client side. Having that available before the service gets created might help?

**Comment by thaJeztah** [comment]
@nishanttotla https://github.com/docker/docker/issues/31348 would probably help; still, if we don't allow paths, I'd not be against limiting the accepted characters (we don't need `my-cute-🐱-secret`)

**Comment by aaronlehmann** [comment]
This was fixed when secrets targets were extended to allow full paths. Closing.
