### ISSUE TITLE
[RFC] Should we block old daemons trying to join a swarm cluster?

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#31998]
Opening this as a separate discussion, after reading https://github.com/docker/docker/pull/31714#issuecomment-288278321

The docker CLI, and API has backwards-compatibility;

- the API is versioned, so an old CLI talking to a "new" daemon will use the API version that matches the CLI
- likewise, if a new CLI connects to an older daemon, it will downgrade to the API version supported by that daemon, and not use features that are not supported by that daemon.

However, a swarm cluster may be a different beast; how do we deal with old daemons trying to join a "new" cluster, e.g., a  Docker 17.03 node trying to join a Swarm cluster that consists of Docker 17.06 nodes?

- Should the whole cluster downgrade to features only supported by the all nodes in the cluster?
- What if the cluster already uses features that are not supported by the client trying to join?

These scenarios also apply when _upgrading_ a swarm; during the upgrade, not all nodes may be on the latest version; should we disable new features during that time? Is there already a mechanism in place to take this into account?

FWIW, we should not "block" old daemons,  but we need to find a solution if daemons have conflicting features

ping @docker/core-swarmkit-maintainers

**Comment by aaronlehmann** [comment]
> However, a swarm cluster may be a different beast; how do we deal with old daemons trying to join a "new" cluster, e.g., a Docker 17.03 node trying to join a Swarm cluster that consists of Docker 17.06 nodes?

We need to support mixed-version clusters - otherwise upgrading to a new version would involve downtime. So I don't see anything inherently wrong with nodes joining the cluster using an older version. We need to handle the mixed version case anyway.

> Should the whole cluster downgrade to features only supported by the all nodes in the cluster?

In most cases, I don't think this is desirable or necessary. For example, if a worker that doesn't support secrets joins a cluster with services that have secrets set up, it's not a good reason to block secrets from working anywhere else. But it gets more complicated when you're talking about outdated managers, or scenarios like removing the ingress network.

> These scenarios also apply when upgrading a swarm; during the upgrade, not all nodes may be on the latest version; should we disable new features during that time?

Ideally yes

> Is there already a mechanism in place to take this into account?

Not yet

**Comment by thaJeztah** [comment]
> it's not a good reason to block secrets from working anywhere else.

Yes, that may be a good example; what happens if a node joins that doesn't support secrets, and a task gets rescheduled (landing on such a node)?

**Comment by aaronlehmann** [comment]
> Yes, that may be a good example; what happens if a node joins that doesn't support secrets, and a task gets rescheduled (landing on such a node)?

Currently, the task will run on that node, but not have access to any secrets.

I think it's acceptable for new features like secrets not to work on nodes which are running a version that predates the feature. Our general policy so far has been that you need to finish upgrading all your nodes before using new features. But there are definitely things we can do to make this more foolproof.

**Comment by mavenugo** [comment]
@aluzzardi fyi. this is tracking the discussion we had f2f. can you pls share your views ?

**Comment by stevvooe** [comment]
I'm surprised this is even being considered. :scream: 

> Currently, the task will run on that node, but not have access to any secrets.

Should such tasks be rejected by the node?

**Comment by aaronlehmann** [comment]
> I'm surprised this is even being considered.

Are you surprised that backward compatibility is being considered, or that one of the possibilities under discussion is preventing outdated nodes from joining the cluster after features that they don't support are already in use? Can you elaborate on your concerns?

> Shouldn't such tasks be rejected by the node?

If the node is running a version that predates secrets, it has no way of knowing that it should reject a task that uses secrets.

**Comment by stevvooe** [comment]
> Are you surprised that backward compatibility is being considered, or that one of the possibilities under discussion is preventing outdated nodes from joining the cluster after features that they don't support are already in use? Can you elaborate on your concerns?

I'm surprised that we'd consider blocking older daemons from joining the swarm cluster.

**Comment by aaronlehmann** [comment]
> I'm surprised that we'd consider blocking older daemons from joining the swarm cluster.

I think I agree in general. This issue was raised in the context of having some kind of feature flags that are gated on all nodes in the cluster supporting the feature. For example, in this world you wouldn't be allowed to replace the ingress network until you've upgraded to a version which supports this feature, because doing so causes problems for versions that predate the feature. The question that comes up is what to do if a new node, running an older version, joins the cluster after the cluster had previously converged on a version new enough to allow flipping the flag on. One of the simpler possibilities, which I believe @thaJeztah proposed as a straw man, is to block older versions if admitting that node to the cluster would force us to turn off features we've already exposed. While it would be nice to find something more elegant, this sounds like a reasonable option to me if we can't come up with a better approach that's practical.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
