### ISSUE TITLE
removing and recreating a directory in a single layer silently fails

### ISSUE THREAD

**Issue by ComaVN** [moby/moby#32354]
**Description**

When repeatedly recreating directories in a `Dockerfile`, the contents of the directory don't actually disappear.

**Steps to reproduce the issue:**
See my [PoC](https://github.com/ComaVN/docker-dir-bug)

**Describe the results you received:**
The `/bar/foo` file exists in the built image

**Describe the results you expected:**
The `/bar/foo` file should not exist in the built image

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 119
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 144
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-71-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.5 GiB
Name: roeldell
ID: P53E:VO4J:EMBM:PUEV:ZCI4:DBOS:42BL:BYYF:4YHE:QHYW:3SNE:75SR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Dell XPS 15
```
$ cat /etc/issue
Ubuntu 16.04.2 LTS \n \l
```

**Comment by thaJeztah** [comment]
I suspect this is due to the way aufs and layered filesystems work;

Removing a directory puts a "whiteout" file in the filesystem that indicates the directory is "removed" in that layer. Creating a new directory at the same location on it's hand, removes the "whiteout" file, thus revealing again what was there.

I'm not sure this can be fixed (there may be other issues tracking this), but we may need to document this.

I see you're on a recent (4.x) kernel; kernels 4.x support the `overlay2` graph driver, which may be well worth considering. You can use that graph driver either by removing the `linux-image-extra` package (in which case docker automatically skips `aufs` and picks `overlay2`, or by explicitly setting the `overlay2` graph driver in [your /etc/docker/daemon.json configuration file](https://docs.docker.com/engine/reference/commandline/dockerd/#linux-configuration-file);

```json
{"storage-driver": "overlay2"}
```

(and restarting the daemon)

/cc @dmcgowan @tonistiigi in case I mis-interpreted this issue

**Comment by dmcgowan** [comment]
I am not aware of any such issue in aufs today. In the example provided AUFS should create an opaque directory marker which keeps any files in previous layers from showing up.

**Comment by ComaVN** [comment]
I can confirm that setting the storage driver to overlay2 fixes the issue for me.

**Comment by thaJeztah** [comment]
The AuFS storage driver has been deprecated and has been removed from our code base (https://github.com/moby/moby/pull/45342) for the upcoming v24.0.0 release, so we're closing tickets related to AuFS
