### ISSUE TITLE
[deprecation] Make service create|update -d=false the default

### ISSUE THREAD

**Issue by aluzzardi** [moby/moby#32369]
In https://github.com/docker/docker/pull/31144 we added support for `-d` and concluded that it should **eventually** default to `false`, however in order not to break the behavior we temporarily defaulted to `-d=true` and added a warning.

This issue is to keep track of:
- Making `-d=false` the default
- Removing the warning

It should be marked `P1` and milestoned with the proper release.

Are we thinking `17.09`?

@thaJeztah What's your opinion? Once we figure this out, would you mind creating the appropriate milestone and setting it to this issue?

I think in the future in order to properly handle deprecation, we should probably have milestones for the next 12 months or so and create P1 issues in advance so we never forget at release time.

/cc @aaronlehmann @vieux

**Comment by thaJeztah** [comment]
I think we came to changing the behaviour after one release yes, so 17.09 sounds good to me. There was still discussion about providing a `~/.docker/config.json` option to override the default (so that users can either switch early, or use the "asynchronous" option also in future versions if desired); would that still be something to consider?

If we're ok with changing the default in 17.09, we should add it to https://github.com/docker/docker/blob/master/docs/deprecated.md
