### ISSUE TITLE
Daemon shutdown delayed by "broadcasting node event"

### ISSUE THREAD

**Issue by aaronlehmann** [moby/moby#32446]
When I shut down the daemon with `^C`, there is a 5 second pause, and then I get an error message "timed out broadcasting node event".

```
DEBU[0056] start clean shutdown of cluster resources...
ERRO[0061] failed to send node leave: timed out broadcasting node event
```

This seems to be new on master in the last day or so. I think it's caused by #32283 

cc @aboch

**Comment by aboch** [comment]
I think have seen this message or similar even before.

This is likely to happen because now we do the proper thing on graceful shutdown trying to inform the other nodes in the network DB this node is leaving the cluster. Before this information would have been derived via the the timeout mechanism by the other nodes.

For now that log is harmless as things are working as before (message was not delivered even before).
But I will look into it whether we can do things better and relay it.

**Comment by aaronlehmann** [comment]
I'm seeing it in a single-node cluster.
