### ISSUE TITLE
Every time I run docker build command, the docker daemon doesn't stops downloading.

### ISSUE THREAD

**Issue by securient** [moby/moby#32543]
**Description**

**Steps to reproduce the issue:**
1. Create a Dockerfile with following commands
FROM ubuntu:latest
MAINTAINER Vinod Tiwari "xxxxxx@gmail.com"

RUN wget downloads.sourceforge.net/xxxxxx/xxxxx_4.1.2-3_all.deb
RUN apt-get update
RUN dpkg -i xxxxxxx_4.1.2-3_all.deb

2. now run the following command in the same directory where your Dockerfile is
docker build -t "test:mydocker"
 
3. The docker daemon keeps downloading the image and doesn't stop. Below is the output of the command.

**Describe the results you received:**
```
ERRO[0382] Tar: Can't stat file /Users/vtiwari to tar: lstat /Users/vtiwari/Library/Caches/Google/Chrome/Default/Cache/f_01826b: no such file or directory 
ERRO[0382] Tar: Can't stat file /Users/vtiwari to tar: lstat /Users/vtiwari/Library/Caches/Google/Chrome/Default/Cache/f_01826c: no such file or directory 
ERRO[0411] Can't add file /Users/vtiwari/Library/Caches/com.tinyspeck.slackmacgap.ShipIt/ShipIt_stderr.log to tar: archive/tar: write too long 
^Cnding build context to Docker daemon 56.24 GBB
```
**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 17.03.1-ce, build c6d412e
```

**Output of `docker info`:**

```
lmvtiwari055602:~ vtiwari$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.13-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: 7UYE:WAVA:KMAQ:O37I:MOL7:C3XB:GRTY:YA4D:BNMB:GVSW:ALEJ:VK5C
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 30
 Goroutines: 42
 System Time: 2017-04-12T03:03:30.316646346Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by unclejack** [comment]
This isn't a bug. This is expected behavior. If I create a Dockerfile in /Users/unclejack and run `docker build` in /Users/unclejack, everything found in /Users/unclejack/ will be sent as a context to the Docker daemon.

If I've got 50+ GB of data in my home directory, this will get sent to the Docker daemon.

This can be fixed easily by putting the Dockerfile in a new directory (e.g. /Users/unclejack/myproject/) and running `docker build` there.

This isn't a bug or error.

Please keep in mind this issue tracker is meant to be used for tracking bugs, feature requests and pull requests. This isn't meant to be a general support forum.

https://forums.docker.com/ should be used for general support issues. Please post there to get help with specific applications. The documentation found at https://docs.docker.com should also be useful when getting started.

I'll close this issue now. Please feel free to comment. There's no need to open another issue.
