### ISSUE TITLE
drive mapping seperator same character as drive letter (colon)

### ISSUE THREAD

**Issue by kalliz** [moby/moby#32553]
Hey all,

found a couple of issue regarding mapping and UNC, but not what I';m looking for, maybe anyone any ideas on what to do.
the storage mapping format is as such c:\hostdrive:c:\containerdrive, which is unfortunate as it uses the colon for drive letter and also as seperator. 
Some software that do not support have issues with that. As an example VMware vRealize Automation (I believe also VMware Admiral is affected), when i enter:
hostdrive           d:\hostdrive
containerdrive   c:\containerdrive

it is parsed incorrectly and I end up with 
host drive           d
containerdrive    hostdrive

it takes the first : as a seperator. I'll go and file a bugfix with VMware, however there might also be other software affected from it.
I've tried ignoring the drive letter, but windows docker insists to have it. 

are there possibilities to create workarounds? 
 - if drive letter is ommited, assume c:\ 
 - allow to provide as such d\hostfolder (if first part is single letter, no colon, assume this to be drive letter ...)

etc

nothing worked for me. Thanks a million for response/ideas

**Comment by friism** [comment]
One possible workaround would be to not use software that mangles strings, and just use Docker directly. Does the software you're using with Docker not have a notion of escape characters? For example, `d\:\\hostdrive`

**Comment by kalliz** [comment]
:-) I tried that with any amount of escapes in front t of the colon. Once there is one it cuts. I escalated a case to VMware, I agree the limitation is on their side. I rather wonder how docker on windows parses it? Does it simply assume there have to be 3 colons and middle one is seperator? Not ideal either.

Ill update here for reference in case someone has the same problem

**Comment by thaJeztah** [comment]
The `-v <host-path>:<container-path>` notation was created long before Windows support was added, and is indeed cause for a lot of headaches (even more so given that additional options can be passed, like `:ro` for read-only).

Docker services (`docker service create`), and `docker run` since docker 17.05 also have the `--mount` flag; this flag uses a different format, which is not ambiguous, and makes parsing easier (see  https://github.com/moby/moby/pull/32251)

This particular issue really looks like something in the VMWare software you're using, and not something we can fix here, so I'll close this issue, but feel free to continue the conversation.
