### ISSUE TITLE
can not kill container with stdout redirected after daemon restart

### ISSUE THREAD

**Issue by x1022as** [moby/moby#32640]
**Description**

after restarting docker daemon(with --live-restore flag), failed to kill container, whose stdout of init pid has been redirected to /dev/null.

**Steps to reproduce the issue:**
1. compile a binary to redirect its stdout/stderr to /dev/null, and do nothing but sleeping:
```
int main(int argc, char *argv[])
{
    int devNull = open("/dev/null", O_RDWR);
    if(devNull == -1){
        fprintf(stderr,"Error in open('/dev/null',0)\n");
        exit(EXIT_FAILURE);
    }

    int dup2Result = dup2(devNull, STDOUT_FILENO);
    if(dup2Result == -1) {
        fprintf(stderr,"Error in dup2(devNull, STDOUT_FILENO)\n");
        exit(EXIT_FAILURE);
    }

    sleep(1000);
}
```
2. build an image with this binary, and run a container with this binary as init process
```
$ cat Dockerfile 
FROM ubuntu:latest

COPY rd /usr/bin/rd
RUN chmod +x /usr/bin/rd
$ docker build -t test:test .
$ docker run -d test:test --name rdtest /usr/bin/rd
```
3. restart docker daemon
4. docker kill rdtest

**Describe the results you received:**
docker kill blocked forever

**Describe the results you expected:**
docker kill return successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-dev
 API version:  1.30
 Go version:   go1.7.5
 Git commit:   41f4c3c
 Built:        Sat Apr 15 09:57:04 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-dev
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   41f4c3c
 Built:        Sat Apr 15 09:57:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

This issue is imported from this PR:  https://github.com/docker/docker/pull/30140 , which remove the timeout of fifo open.

ping @mlaventure

**Comment by coolljt0725** [comment]
ping @tonistiigi  @crosbymichael

**Comment by mlaventure** [comment]
@x1022as I had a look, and reverting the PR is not the correct way to go IMHO.

I would recommend using `--init` as a work around

For reference the issue is as follow:
 - Since the process dup its stdout/stderr to `/dev/null` the `io.Copy` within the shim returns almost immediately closing the fifo in the process
 - when `dockerd` reconnects to the fifo, there's noone waiting on the otherside, hence the engine hangs forever waiting for the fifos to be closed.

I've made a PR on containerd to offer a solution without `--init` (see https://github.com/containerd/containerd/pull/764)

**Comment by x1022as** [comment]
tks, @mlaventure  will try this later.

**Comment by thaJeztah** [comment]
@x1022as is this ready to close?

**Comment by coolljt0725** [comment]
we have tried https://github.com/containerd/containerd/pull/764 and it fix out problem, I think we can close this.
