### ISSUE TITLE
[Debian stretch] armhf missing from APT repository 

### ISSUE THREAD

**Issue by bamarni** [moby/moby#32665]
The [Get Docker for Debian](https://docs.docker.com/engine/installation/linux/debian/) page states that `Docker CE is supported on both x86_64 and armhf architectures for Jessie and Stretch`.

However armhf seems only available for jessie at the moment. Is it a mistake from the doc or should it actually exist for stretch too?

**Comment by thaJeztah** [comment]
Thanks for reporting (and apologies for the delayed response) Packages were added for stretch/armhf since docker 17.06; possibly the docs were updated before the release was done.

Packages are now available though; https://download.docker.com/linux/debian/dists/stretch/pool/stable/armhf/, so let me close this issue, but feel free to continue the  conversation
