### ISSUE TITLE
build docker and got /usr/bin/ld cannot find -ldevmapper error

### ISSUE THREAD

**Issue by ofly** [moby/moby#32734]
**Description**
I build docker on my centos 7 desktop following the instructiong https://docs.docker.com/opensource/project/set-up-dev-env/#task-2-start-a-development-container
and I got the error message:
```
Failed to fetch http://ppa.launchpad.net/zfs-native/stable/ubuntu/dists/trusty/main/binary-amd64/Packages  Hash Sum mismatch
```
this problem has been issued at https://github.com/moby/moby/issues/30264, and seems not been solved.

Then, I try to build docker manually, following the Dockerfile:
```sh
$ cat contrib/builder/rpm/amd64/fedora-25/Dockerfile
#
# THIS FILE IS AUTOGENERATED; SEE "contrib/builder/rpm/amd64/generate.sh"!
#

FROM fedora:25

RUN dnf -y upgrade
RUN dnf install -y @development-tools fedora-packager
RUN dnf install -y btrfs-progs-devel device-mapper-devel glibc-static libseccomp-devel libselinux-devel libtool-ltdl-devel pkgconfig selinux-policy selinux-policy-devel sqlite-devel systemd-devel tar git cmake vim-common

ENV GO_VERSION 1.7.4
RUN curl -fSL "https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz" | tar xzC /usr/local
ENV PATH $PATH:/usr/local/go/bin

ENV AUTO_GOPATH 1

ENV DOCKER_BUILDTAGS pkcs11 seccomp selinux
ENV RUNC_BUILDTAGS seccomp selinux
```
on my **fedora25 virtual meachine**.

I have config GO environment well:
```sh
$ go version
go version go1.8 linux/amd64
```

**Steps to reproduce the issue:**

0. mkdir -p docker/src/github.com/docker
1. cd docker/src/github.com/docker
2. git clone https://github.com/docker/docker.git
3. cd docker
4. sh hack/make.sh binary

**Describe the results you received:**

build binary-client ok, but get error when build binary-daemon. error message:

```
/usr/bin/ld: cannot find -ldevmapper
```

libdevmapper are installed:
```sh
$ rpm -qa | grep dev | grep map
device-mapper-devel-1.02.136-3.fc25.x86_64
device-mapper-1.02.136-3.fc25.x86_64
device-mapper-libs-1.02.136-3.fc25.x86_64
```
ld config well:
```sh
$ ld -v | grep devmapper
$ ldconfig -v | grep devmapper
ldconfig: Can't stat /libx32: No such file or directory
ldconfig: Path `/usr/lib' given more than once
ldconfig: Path `/usr/lib64' given more than once
ldconfig: Can't stat /usr/libx32: No such file or directory
	libdevmapper.so.1.02 -> libdevmapper.so.1.02
```
and file /usr/lib64/libdevmapper.so is ok:
```sh
$  ll /usr/lib64/libdevmapper.so
lrwxrwxrwx. 1 root root 31 April  20 13:03 /usr/lib64/libdevmapper.so -> /usr/lib64/libdevmapper.so.1.02
```

I really don't know how to build docker now, can anyone help me?

**Comment by RokaFogtaCsukaFarka** [comment]
I have quite the same issue, regarding libdevmapper.

I am running Docker on Ubuntu 16.04 LTS and having installed Docker I cannot run any image.

`docker version`
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64

I have libdevmapper.so.1.02.1, and as I see the program looks for libdevmapper.so.1.02 and I do not know where.

Please provide information where I can configure Docker.

**Comment by zhoubofsy** [comment]
same issue

**Comment by drubanov** [comment]
I had the same problem.  It goes away if you change the line 

EXTLDFLAGS_STATIC='-static'

to

EXTLDFLAGS_STATIC=''

in hack/make.sh file.  I am on Debian-derived rather than an "rpm" distribution.  The problem is that
binary libdevmapper package only ships with the shared (".so") library.  And that doesn't work too well 
when trying to build a static dockerd image.  

If you want to see what's going on, change the line (in the same file) 

ORIG_BUILDFLAGS=( -tags.....

to

ORIG_BUILDFLAGS=( -x -tags.....

to see all the steps taken by the Go build process.  

Alternatively (and that's what I plan on doing), build the dynamically-linked binary (by removing '-static' as above), and then run ldd on the resuling binary.  This will tell you which of the libraries are used by the built image and you can make sure that you have all the static versions of these libs.  Then put the '-static' back in, and build the statically-linked executable.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
