### ISSUE TITLE
Splunk Logging Driver should support the /raw endpoint for sending logs to Splunk

### ISSUE THREAD

**Issue by hyfather** [moby/moby#32747]
**Description**

Currently, the Splunk Logging Driver sends events to Splunk's `services/collector/event/1.0` endpoint. While this endpoint is great for ingesting well formed structured JSON logs, it doesn't allow for traditional plaintext events to be "transformed" while being ingested. Splunk transformations typically run regexes for index-time field extractions, scrub the data, etc.

Luckily, Splunk now supports the `services/collector/raw/1.0` endpoint which runs the incoming data through the typing pipeline that can run these index-time transformations on the incoming data.

I don't suppose Splunk had the raw endpoint when the logging driver first came out, but now that it does, it would be helpful to support it via an optional argument. Something along the lines of  `--log-opt splunk-endpoint=event|raw` could parametrize the [underlying](https://github.com/moby/moby/blob/v1.13.1/daemon/logger/splunk/splunk.go#L569) URL construction.

I'll be happy to put up a pull request if this proposal sounds sensible!

Tagging Denis @outcoldman & Glenn @glennblock here since they worked on the original logging driver.

**Additional Information**

[Splunk docs for the /raw endpoint
](http://docs.splunk.com/Documentation/Splunk/latest/RESTREF/RESTinput#services.2Fcollector.2Fraw)
[Splunk docs for the /event endpoint
](http://docs.splunk.com/Documentation/Splunk/latest/RESTREF/RESTinput#services.2Fcollector)

**Comment by outcoldman** [comment]
@hyfather I believe it is already implemented, you can do that with `splunk-format=raw`, it does not use `raw` endpoint, but I believe it will give you exactly what you want. See examples below https://docs.docker.com/engine/admin/logging/splunk/

/cc @mchene

**Comment by glennblock** [comment]
I agree with @outcoldman, there's not much to gain by using raw. The same
level of extractions will work whether you use the splunk-format=raw or
send to the raw endpoint. The main difference is that if you send to the
raw endpoint, the payload can be pure text vs JSON, but in this case it
doesn't matter, because if you choose raw, it will just send the raw text
as "event" and result in the same.

Using the raw endpoint itself would make sense IF you were able to send
loose lines in chunks across multiple requests and have line breaking rules
run to break it appropriately into events. However, the raw endpoint does
not work that way. A single request to raw will be broken into one or more
events, and you cannot span an event across multiple requests.

The log driver sends each line as an event, thus there is no real benefit
from a line-breaking perspective if you go to the raw endpoint.

**Comment by hyfather** [comment]
Thanks for weighing in @outcoldman, @glennblock.
There is some discrepancy in the Splunk API docs about what sort of Splunk transforms run when events are coming in via the `/events` endpoint vs the `/raw` endpoint. I'll work with someone to make it more clear in the docs.
Meanwhile, I'll close this issue -- thanks again!

**Comment by glennblock** [comment]
Cool. The one big difference is with the JSON endpoint, breaking rules don't run. But as I said because we're sending events line by line in either case anyway, that doesn't really buy anything here.

FWIW I do think it would be great if HEC RAW allowed you to just send raw chunks and buffered them up and then ran the breaking rules similar to the way other inputs work, but that is non-trivial to make happen.

**Comment by hyfather** [comment]
> FWIW I do think it would be great if HEC RAW allowed you to just send raw chunks and buffered them up and then ran the breaking rules similar to the way other inputs work, but that is non-trivial to make happen.

Yes, this would be helpful. We now have a native golang S2S client implementation that we are using in production. What are your thoughts on this logging driver supporting S2S in addition to HTTP to support these sort of use cases?

**Comment by glennblock** [comment]
Do you mean S2S directly over TCP, or using the S2S payload format over HTTP?

**Comment by hyfather** [comment]
S2S directly over TCP, with S2S channels and S2S ACKs.

**Comment by glennblock** [comment]
How would you see the token playing in with that model? Would S2S allow us to add extra in the payload for the token? 

My big question if if it is a full S2S implementation is how much the existing HEC infra will buy you. @itay / @outcoldman would be best to ask.

**Comment by outcoldman** [comment]
I believe S2S is not documented.

**Comment by glennblock** [comment]
@outcoldman very good point.
