### ISSUE TITLE
What is latest stable version for Windows 2016>

### ISSUE THREAD

**Issue by artisticcheese** [moby/moby#32765]
I see from release notes that latest stable version for windows is `v17.04.0-ce` while pulling info from DockerMsftProvider shows latest as `17.03.1.-ee`. Why the discrepancy?

**Comment by cpuguy83** [comment]
Stable is always the quarterly release. Currently the latest "stable" is 17.03.1.
Monthly releases are part part of the "edge" channel, which would be 17.04, and if you are in the beta channel it's 17.05-rc1.

If you could it would be helpful to ask these kinds of questions on the community forums (forums.docker.com) or on the community slack since we want to keep the issue tracker free of these kinds of questions.

Closing since this now since it's not really an issue, but feel free to discuss further.
Thanks!

**Comment by friism** [comment]
Only Docker Enterprise Edition is officially available for Windows Server 2016. Docker Enterprise Edition is released quarterly and 17.03 is the most recent release. Details here: https://blog.docker.com/2017/03/docker-enterprise-edition/

Docker Community Edition is available for Windows 10 (most easily installed with Docker for Windows). If you want to try new Docker features on Windows Server 2016 (without support), you can also install Docker CE there using the manual installation instructions: https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/configure-docker-daemon
