### ISSUE TITLE
Question about docker.sock availability in plugin (v2)

### ISSUE THREAD

**Issue by brb** [moby/moby#32815]
**Description**

I'm developing the Weave Net plugin (v2) for Docker.

The plugin initialization which happens before the plugin socket becomes ready relies on Docker API (e.g. to list swarm nodes) which we access via bind mounted `docker.sock`.

Unfortunately, after a restart of `dockerd`, `dockerd` tries to restore enabled plugins first, and only afterwards starts listening on `docker.sock`. Having combined the ordering with this check  https://github.com/moby/moby/commit/1b41b7a4f4c824bbfdb1acac3e8c8505e0fdb84f#diff-187b5307d5863a8646c577efe2fe605eR105, the plugin cannot be restored after the restart.

The question is whether our reliance on `docker.sock` being available before starting the plugin is fundamentally broken? If so, we cannot expect `docker.sock` to be ready before we start listening on the plugin socket which complicates the plugin implementation.

**Comment by cpuguy83** [comment]
Yes, it's definitely broken, especially consider that the daemon may go down while the plugin stays running (`--live-restore` mode).
In this case, not only will the socket become unavailable, but most likely invalid after the daemon comes back.

We need a better model for providing access to the docker API.

**Comment by brb** [comment]
Thanks.

> We need a better model for providing access to the docker API (in containers).

Is there any issue to track?

**Comment by cpuguy83** [comment]
@brb Probably? But this is as good as any.

I believe the sec team wants to make sure that if we start providing a means of gaining access to the socket (other than bind-mounting the "real" docker socket) into a container that the access can be scoped to only what is needed for the particular case.

See this related work around metrics scraping inside plugins: https://github.com/moby/moby/pull/32874
It's a much simpler case since the endpoint is read-only and specific to metrics, but likely the same idea for API access.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
