### ISSUE TITLE
Feature Request: Swarm service `placement constraint` based on available memory

### ISSUE THREAD

**Issue by hughmp** [moby/moby#32844]
Some applications require a specific amount of available memory otherwise they will not start and, therefore, the container is terminated. (e.g. elasticsearch which requires 4GB of available memory)

In my `swarm` I have some `workers` which do not have the required available memory. In order to try and reduce the chance of a container starting on a node which doesn't have enough memory I create a `placement constraint` which either points to a host which I know has enough capacity or is tagged as such by using a `label`.

The only way I've discovered to automatically prevent a service starting a container, with specific memory requirements, on a node which doesn't have enough capacity, is to dynamically assign the labels based on available memory. This can be done by using some kind of scheduled script on each host or in a container which has access to the host.

I'm wondering if there is a better way to achieve what I've described without the overhead of an additional scheduler or is this a valid feature request?

Thanks!

**Comment by cpuguy83** [comment]
Does `--reserve-memory` work for you?

**Comment by Vanuan** [comment]
So, does this automatically choose a node with minimum available memory greater than specified?
```
    deploy:
      resources:
        reservations:
          memory: 1G
```

**Comment by Vanuan** [comment]
Apparently it's undocumented option:

https://github.com/moby/moby/pull/32631/files

**Comment by thaJeztah** [comment]
> Apparently --reserve-memory is a new undocumented option:

The feature is documented in the [manage a swarm](https://docs.docker.com/v1.13/engine/swarm/services/#reserving-memory-or-number-of-cpus-for-a-service) section, and has been around since swarm mode was introduced, but only the flag itself was documented in the reference section.

> The doc suggests to look for the docker run counterpart

@Vanuan can you open an issue in the documentation issue tracker (https://github.com/docker/docker.github.io/issues) for that? I think it's better to refer to the service create section after the PR you linked to is merged


I'll go ahead and close this issue, because this feature exists, but feel free to continue the conversation

**Comment by Vanuan** [comment]
https://github.com/docker/docker.github.io/pull/3217

**Comment by Vanuan** [comment]
Sorry, apparently there are 2 locations for docs. Didn't know which one is to be fixed.

**Comment by thaJeztah** [comment]
Yes, CLI reference docs are in this repository (but may move to https://github.com/docker/cli at some point), and other docs are in the docker.gihub.io repository.

Thanks for opening that issue!
