### ISSUE TITLE
No direct way to bake in hardening options into the image

### ISSUE THREAD

**Issue by rhonnava** [moby/moby#32942]
I am trying to run a docker hardened container with limited attack surface, by specifying several docker run parameters. 

Here are a few options:
1. --security-opt="apparmor=PROFILE"
2. --security-opt="seccomp=profile.json"
3. --security-opt="no-new-privileges" 
4. --sysctl=net.core.somaxconn=1024
5. --sysctl=net.ipv4.tcp_syncookies=1
6. --sysctl=net.ipv4.tcp_max_syn_backlog="2048" 
7. -m 300M --memory-swap 1G

I am thinking of a lot more parameters, which will be too cumbersome to specify each time I launch the container. 

I can think of a few ways to do it:
1. Wrap this docker run command in a bash script, so all the parameters are contained in it.
2. Write a script to set the sysctl variables in a bash script again and invoke the script at container startup using ENTRYPOINT, in the Dockerfile of the container. But I will still need to specify parameters like the memory limits, seccomp profile, etc at run time.

Is there a standard way to bake all this into the image at build time, so as to build and publish a hardened image?

**Comment by cpuguy83** [comment]
These cannot be set on the image because, for the most part, they are host dependent.

You can set the default seccomp profile and `no-new-privileges` at the daemon level.

**Comment by thaJeztah** [comment]
This is not supported indeed, however, there's some discussion about options to add a "profile" to images using "entitlements"; see https://github.com/moby/moby/issues/32801

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍
