### ISSUE TITLE
Proposal: add a restart condition on node failure

### ISSUE THREAD

**Issue by fermayo** [moby/moby#32979]
At the moment, there are three options for restart condition: `none`, `on-failure`, `any`.

If I want to make sure that my task executes just once (regardless of the exit code), I would choose `none` for that. But if while it's running the underlying node fails, the task won't be rescheduled. The proposal is to add a new condition, i.e. `on-node-failure` (or similar) that reschedules the task only if it's shutdown because of external causes to the task (like a node failure).

cc @aluzzardi @dongluochen @aaronlehmann

**Comment by aaronlehmann** [comment]
If you don't care about the exit code, can you just wrap the entrypoint in a script that ends with `exit 0`? Then you could use `on-failure`, and in practice this should only trigger with node failures (or other failure modes that don't involve the task exiting normally).

**Comment by fermayo** [comment]
@aaronlehmann I do care about the exit code ;)

**Comment by dongluochen** [comment]
There are 2 cases of `node-failure`. 
1. Node down due to infrastructure failure, e.g., power failure, network failure. In this case Swarm managers receive node `Down` notification while task remains in `running` state. 
2. Node down from dockerd stop, or node shutdown/restart gracefully. According to https://github.com/moby/moby/pull/31664, Dockerd should stop the containers first. Swarm managers would receive task `Failed` notification **before** node `Down` notification. 

@fermayo According to your criteria, a `failed` task should not be restarted, so Swarm would not reschedule the task for case 2. This may defeat your purpose.

**Comment by fermayo** [comment]
@dongluochen do you agree that a task failing because it suddenly exited on its own is a different case from a task that exited because it was forced to be shutdown by another process sending it a signal? If so, we cannot just treat them both as `Failed`.

**Comment by dongluochen** [comment]
@fermayo I agree they are different. If we want to react differently, we will need to find a way to differentiate them.

**Comment by dongluochen** [comment]
I think graceful node shutdown should be like this. 
1. The node sends a `shutdown` notification to manager.
2. Leader marks the node to a new `going-down` state so tasks can be rescheduled elsewhere. 
3. The node continues to shutdown. 
4. `going-down` state is replaced by `down` state. The rest is like the same like today.
