### ISSUE TITLE
docker managed plugin config needs a way to specify "--privileged"

### ISSUE THREAD

**Issue by taherv** [moby/moby#33010]
**Description**

What is the guidance on running privileged plugins ?
I know we can give specific capabilities to managed plugin via config.json, but what are my options if I need to port a legacy plugin (which was running --privileged) to managed plugin ?

**Comment by cpuguy83** [comment]
@taherv You'll have to evaluate what your plugin is using.
The equivelent of `--privileged` is not planned to be added for plugins.

What does your plugin do?

Closing since this is not really an issue.
#plugins on the Docker community Slack might be a better place to discuss (or even #general since it's not exactly plugin specific).

Thanks.
