### ISSUE TITLE
iptables=false, how to bind the published port to specific ethX in overlay

### ISSUE THREAD

**Issue by ghost** [moby/moby#33030]
When using Overlay network, there will be at least 2 interfaces in docker container. One connects to docker_gwbridge and the other connects to br0. e.g. 172.18.0.2 on eth0 and 10.0.0.2 on eth1.

In containers, I bind the service to eth1:10000, And I use --iptables=false. -p 10000:10000 to startup docker.

However,  docker-proxy just forward host port 10000 to 172.18.0.2:10000.

Is there any way to set docker-proxy to  forward port to 10.0.0.2:10000 in containers?

**Comment by cpuguy83** [comment]
Does `-p 10.0.0.2:10000` work?

**Comment by Yanfeng-Wang** [comment]
@cpuguy83 eth0 and eth1 are interfaces inside containers. In other words, I want to use the args like -p HostIP:HostPort:ContainerIP:ContainerPort(-p HostIP:10001:10.0.0.2:10001),  but it seems port fowarding only has three formats, HostIP:HostPort:ContainerPort, HostIP::ContainerPort, HostPort:ContainerPort.

**Comment by cpuguy83** [comment]
Tying it to a particular container IP is pretty rough since these are not stable... and I suspect even the interfaces are necessarily stable either.
How come you can't listen on all interfaces?

**Comment by wyfeng001** [comment]
Perhaps services in different containers need to communicate with each other via sockets, so they need to listen on the specified overlay IP:Port.  Then he need to publish the IP:Port to host.

**Comment by cpuguy83** [comment]
@wyfeng001 This is essentially what networks are for. Two services or containers share a neteork, they can communicate.

**Comment by wyfeng001** [comment]
Yeah, they are in the same subnet. I  want to deploy a distributed Hadoop cluster into docker on different hosts. I set some  env vars liks fs.default.name to  hdfs://Master:9000. Master  is the IP addr from overlay subnet. Slave docker on other hosts can communicate with  Master because they are in the same overlay network, however how can I publish the MasterIP:Port to hosts so that I can access the service  from outside  hosts' network instead of entering containers? @cpuguy83

**Comment by thaJeztah** [comment]
closing because this went stale and the original reporter's account is removed
