### ISSUE TITLE
can't start container，when native.cgroupdriver=cgroupfs 

### ISSUE THREAD

**Issue by foxwang** [moby/moby#33224]
cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 

yum install docker-io

native.cgroupdriver=cgroupfs 

[root@localhost docker]# docker run -itd docker.io/centos:6 /bin/bash
098baa8e3c19eb11e18d4e24289770019075088687f87b671e3ec7d56accb01f
/usr/bin/docker-current: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: \\\"\"\n".

cat  /usr/lib/systemd/system/docker.service
[Unit]
Description=Docker Application Container Engine
Documentation=http://docs.docker.com
After=network.target
Wants=docker-storage-setup.service
Requires=docker-cleanup.timer

[Service]
Type=notify
NotifyAccess=all
EnvironmentFile=-/etc/sysconfig/docker
EnvironmentFile=-/etc/sysconfig/docker-storage
EnvironmentFile=-/etc/sysconfig/docker-network
Environment=GOTRACEBACK=crash
Environment=DOCKER_HTTP_HOST_COMPAT=1
Environment=PATH=/usr/libexec/docker:/usr/bin:/usr/sbin
ExecStart=/usr/bin/dockerd-current \
          --add-runtime docker-runc=/usr/libexec/docker/docker-runc-current \
          --default-runtime=docker-runc \
          --userland-proxy-path=/usr/libexec/docker/docker-proxy-current \
          $OPTIONS \
          $DOCKER_STORAGE_OPTIONS \
          $DOCKER_NETWORK_OPTIONS \
          $ADD_REGISTRY \
          $BLOCK_REGISTRY \
          $INSECURE_REGISTRY
ExecReload=/bin/kill -s HUP $MAINPID
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
TimeoutStartSec=0
Restart=on-abnormal
MountFlags=slave

[Install]
WantedBy=multi-user.target

**Comment by thaJeztah** [comment]
The `docker-io` package is the Red Hat fork of Docker 1.12 (which is EOL and no longer maintained), and not an official build, so unfortunately we won't be able to help with that. Also make sure that your system is fully up to date; CentOS uses a "rolling release" model, which means that version 7.2.x became end of life when CentOS 7.3 was released.

I recommend updating your system, and installing the official docker packages for CentOS, using the instructions in the documentation https://docs.docker.com/engine/installation/linux/centos/

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because of the above, but feel free to continue the conversation 👍
