### ISSUE TITLE
Wrong node status when stopping manager node

### ISSUE THREAD

**Issue by aczarnecki** [moby/moby#33251]
**Description**

When working with 2 AZ on AWS I encounter a strange bug/error. Namely when stopping one of the manager node "Manager Status" changed to Unreachable but the "Status" of the node remained Ready.
- I'm using Docker in the swarm mode.
- This was deployed via "docker stack deploy"
- Deployment mode was global with placement restriction.
- Manager nodes reside in 2 different AZ.
- When stopping worker nodes everything works fine.

```
ID                           HOSTNAME         STATUS  AVAILABILITY  MANAGER STATUS
7jhxcyxaywi2ee6g6b4gqb1l2    ip-10-10-35-107  Down    Active
8as9eygbb1pf1n8kozpbeff6f    ip-10-10-30-96   Ready   Active
napuzx4c53aehuua6l9t9iryr    ip-10-10-5-150   Ready   Active        Unreachable
oh5o6gz6fkwvqacaogb6fqsz1 *  ip-10-10-0-195   Ready   Active        Leader
```
It wouldn't be much of a error if not for the fact that the containers which were running on that node also stayed in the running status.

Output after stopping the machine:
```
ID            NAME                                   IMAGE      NODE             DESIRED STATE  CURRENT STATE         ERROR                             
sq2or0zwb6qk  is_registry.napuzx4c53aehuua6l9t9iryr  registry:2 ip-10-10-5-150   Running  Running 9 minutes ago  
kqd6uz90qrzl  is_proxy.napuzx4c53aehuua6l9t9iryr     haproxy    ip-10-10-5-150   Running  Running about a minute ago
```

Additionally when restarting the node Docker reported that the containers failed and started new ones.

```
ID            NAME                                   IMAGE      NODE             DESIRED STATE  CURRENT STATE         ERROR                             
oy9nidmzzd2s  is_registry.napuzx4c53aehuua6l9t9iryr  registry:2 ip-10-10-5-150   Running  Running 9 minutes ago  
0jzqock3k796  is_proxy.napuzx4c53aehuua6l9t9iryr     haproxy    ip-10-10-5-150   Running  Running about a minute ago
kqd6uz90qrzl  is_proxy.napuzx4c53aehuua6l9t9iryr     haproxy    ip-10-10-5-150   Shutdown Failed 9 minutes ago        "task: non-zero exit (0): No such container: is_proxy"
sq2or0zwb6qk  is_registry.napuzx4c53aehuua6l9t9iryr  registry:2 ip-10-10-5-150   Shutdown Failed 9 minutes ago        "task: non-zero exit (0): No such container: is_proxy"

```

**Steps to reproduce the issue:**
1. Create 2 manager nodes.
2. Take one manager down (shutting down the machine)
3. Check the node and stack status.

**Describe the results you received:**
Wrong node and container status.

**Describe the results you expected:**
Right node and container status.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:36:56 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:36:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: oh5o6gz6fkwvqacaogb6fqsz1
 Is Manager: true
 ClusterID: w5x6m47p2xeof0rjp8iqctwal
 Managers: 2
 Nodes: 8
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.10.0.195
 Manager Addresses:
  10.10.0.195:2377
  10.10.5.150:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.36-8-default
Operating System: openSUSE Leap 42.2
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.951 GiB
Name: ip-10-10-0-195
ID: LIZB:FREV:3DEJ:6YE5:7RSY:KV4G:CBQB:QSQH:HWLK:A3HF:UE4W:ZWTM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS, Docker Stack

**Comment by thaJeztah** [comment]
This is expected with these steps;

- Create 2 manager nodes.
- Take one manager down (shutting down the machine)

Swarm mode uses a ["raft" consensus algorithm](https://raft.github.io) for the cluster store. Consensus is reached if a _majority_ of the managers agree on a change. In other words, more than _half_ of the managers need to agree for any change made to the swarm state ("is a container running"? "is the service created?").

- For a single manager, that means 51% or more of 1 manager, so 1 manager needs to agree
- For _two_ managers, 51% or more of 2 manager, so 2 managers need to agree

Effectively, if you take down 1 manager in a 2-manager setup, you loose control over your cluster. In this state, the remaining manager can no longer control the cluster, nor can it update the information ("It looks like the container is down, but I need the other manager to confirm, meanwhile, we assume the last state is correct - the container is running")

Never run a cluster with 2 managers as it _doubles_ the chance you lose control (with two managers, chances are twice as big that a manager fails). Use a _single_ manager if you don't need fault-tolerance, or 3, 5 or 7 managers if you do. Keep in mind that more managers does not bring better performance (actually, the contrary, because the managers need to communicate and reach consensus on every decision).

Read the documentation here for more information: [Add manager nodes for fault tolerance](https://docs.docker.com/engine/swarm/admin_guide/#add-manager-nodes-for-fault-tolerance), and [Raft consensus in swarm mode](https://docs.docker.com/engine/swarm/raft/)

I'm closing this issue, because this does not appear to be a bug, but feel free to continue the conversation 👍
