### ISSUE TITLE
state struct contain isRunning AND paused bools

### ISSUE THREAD

**Issue by yastij** [moby/moby#33294]
**Description**

in `moby/container/state.go` we have a struct that handles containers state, it looks like this : 
``` go
type State struct {
	sync.Mutex
	// FIXME: Why do we have both paused and running if a
	// container cannot be paused and running at the same time?
	Running           bool
	Paused            bool
	Restarting        bool
	OOMKilled         bool
	RemovalInProgress bool // Not need for this to be persistent on disk.
	Dead              bool
	Pid               int
	ExitCodeValue     int    `json:"ExitCode"`
	ErrorMsg          string `json:"Error"` // contains last known error when starting the container
	StartedAt         time.Time
	FinishedAt        time.Time
	Health            *Health

	waitStop   chan struct{}
	waitRemove chan struct{}
}
```
this is a bit misleading as we need to always update the two bools in order to avoid any inconsistant behaviour.
the state is embed in : 
```go
type CommonContainer struct {
	StreamConfig *stream.Config
	// embed for Container to support states directly.
	*State          `json:"State"` // Needed for Engine API version <= 1.11
          .....
     }
```
as states the comments to ensure compatibility with versions <= 1.11, i think we can refactor without breaking much of it.

**Comment by thaJeztah** [comment]
The comment there looks to be wrong; let me open a pull request to remove the `FIXME`, and describe why there's two fields.

The status is actually the _reverse_ because a container cannot be _stopped_ and _paused_ at the same time;

```bash
$ docker stop foo
foo

$ docker pause foo
Error response from daemon: Container c9c3899b024d136b1c05e8e91290e84541f982bb938e053d3edee510d3eb3957 is not running
```

From the [`docker container pause` command line reference](https://github.com/moby/moby/blob/52df69f00d966904ba230dc2e3a0646cc52b7688/docs/reference/commandline/pause.md):

> The `docker pause` command suspends all processes in the specified containers.
> On Linux, this uses the cgroups freezer. Traditionally, when suspending a process
> the `SIGSTOP` signal is used, which is observable by the process being suspended.
> With the cgroups freezer the process is unaware, and unable to capture,
> that it is being suspended, and subsequently resumed. On Windows, only Hyper-V
> containers can be paused.
>
> See the
[cgroups freezer documentation](https://www.kernel.org/doc/Documentation/cgroup-v1/freezer-subsystem.txt) for further details.

(If I recall correctly) the cgroups freezer can only be used to pause ("freeze") a running process. Since this is confusing, the `Status` field was added, containing a string presentation of the current state (see https://github.com/moby/moby/pull/15023), also see https://github.com/moby/moby/issues/13579 which has some discussion on this topic.


As said; let me open a pull request to;

- Fix the comment, and remove the TODO/FIXME
- Add a recommendation to the API docs to indicate that the `Status` string is recommended to be used to get the status of a container, instead of checking the individual booleans
