### ISSUE TITLE
[feature] repo mirror

### ISSUE THREAD

**Issue by blacktop** [moby/moby#33390]
It would be really cool if there was a feature to create a docker image/container that would act as a auto-magical repo mirror. 

I have watched ubuntu update/install the same packages for hours and hours ..... and hours 😴 

It would also help alleviate peeps hitting the ubuntu mirrors etc

Could work like this:

```bash
$ docker mirror create ubuntu
```

```bash
$ docker build --mirror ubuntu -t awesomesauce .
```

I ❤️ docker

kthxbye

**Comment by cpuguy83** [comment]
Thanks for the request.
I don't think this is the job of Docker, however you can do this pretty easily with Docker.
There are a couple of ways to do it:

Start up an apt_mirror (see https://apt-mirror.github.io/) container with the name `deb.debian.org` and then run another container in the same network then it would just transparently use the mirror (Since the debian image defaults to use `deb.debian.org`).

You could also do the same as above, but change the name to something else, this will require you to update the debian image to use the custom name.

You can also use apt-cacher-ng to do this, which acts as a proxy to some mirror, this requires changing the apt client config to use the proxy, or change the mirror URL's to the proper URL for apt-cacher-ng (`<dns name>:<port>/<real mirror URL>`)
