### ISSUE TITLE
Clarifying the purpose of the Go API?

### ISSUE THREAD

**Issue by LeoTindall** [moby/moby#33452]
I've been using the Docker Go API for a while and I've found that it's practically undocumented. Most of the "documentation" I've learned from is combing through docker/cli looking at how that tool uses the API.

In addition, the response to issues like #28269 seem to imply that this API is intended only for internal use.

If the API is not meant to be used by outside developers, that needs to be documented somewhere, so that other developers can build an API that is usable and well-documented, and if it's not, some time should probably be put into making its documentation better and avoiding compilation-breaking vendoring issues. 

This is something I'd be more than happy to help with, by the way; I just want to know if it's even supposed to be an external API before I do work on it.

**Comment by cpuguy83** [comment]
@LeoTindall The client package is indeed intended for external use as well as internal.

Issues with vendoring are not something we can really fix outside of moving the client package to it's own repo, which is undesirable.
All go packages have to deal with this, sadly.

As for documentation, there is some example style docs in the actual docker docs here: https://docs.docker.com/engine/api/

Otherwise I'd recommend using godoc: https://godoc.org/github.com/moby/moby/client which could indeed use some extra love

**Comment by LeoTindall** [comment]
Thanks for the clarification!

I've been going through the Godoc and it serves as a good reference for struct bodies and function signatures but there is little to go on with regard to function. Expect PRs in that vein! 😄

**Comment by cpuguy83** [comment]
Thanks!
