### ISSUE TITLE
docker swarm join manager after removing seems to be stuck

### ISSUE THREAD

**Issue by lanmingle** [moby/moby#33574]
node 1 is manager
node 2 is worker
node 3 is worker
node 4 is manager

node 2 / 3 join  node 1 
node 4 join  node 1 

node 4 --force

shutdown node 4

node 1 

``` bash
ID                           HOSTNAME     STATUS  AVAILABILITY  MANAGER STATUS
4e1nne6ksu29f6bnymqavhzlc *  rdmlocal001  Ready   Active        Leader
lzfbb7koyg0u5qz8kaw2bhur8    rdslocal002  Ready   Active
n03s59er2v799j3j0jn33etzn    rdmlocal002  Ready   Active        Unreachable
xudt7c0hob22kvb9naw0uoej2    rdslocal001  Ready   Active
```
docker node rm n03s59er2v799j3j0jn33etzn
Error response from daemon: rpc error: code = 4 desc = context deadline exceeded

seems to be stuck ... slowly slowly ( 很慢很慢 )

add ..

reboot 

docker node ls

Error response from daemon: rpc error: code = 4 desc = context deadline exceeded

docker service ls

docker service lsError response from daemon: rpc error: code = 4 desc = context deadline exceeded

docker system info

wait ... wait ... wait ... 

docker infoContainers: 12
 Running: 8
 Paused: 0
 Stopped: 4
Images: 13
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: pending
 NodeID: 4e1nne6ksu29f6bnymqavhzlc
 Error: rpc error: code = 4 desc = context deadline exceeded
 Is Manager: true
 ClusterID:
 Managers: 0
 Nodes: 0
 Orchestration:
  Task History Retention Limit: 0
 Raft:
  Snapshot Interval: 0
  Heartbeat Tick: 0
  Election Tick: 0
 Dispatcher:
  Heartbeat Period: Less than a second
 CA Configuration:
  Expiry Duration: Less than a second
 Node Address: 192.168.1.253
 Manager Addresses:
  0.0.0.0:2377
  192.168.1.250:2377
  192.168.1.253:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.21.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.702 GiB
Name: rdmlocal001
ID: UB2D:BGBE:J3U7:FXTV:ZROA:TCCD:5POA:EEU7:CYX3:JR5K:OWSN:U4YL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
Live Restore Enabled: false

**Comment by thaJeztah** [comment]
This is expected with these steps;

- Create 2 manager nodes.
- Take one manager down (shutting down the machine), or `--force` leaving it (as the other manager is not aware of the manager leaving)

Swarm mode uses a ["raft" consensus algorithm](https://raft.github.io) for the cluster store. Consensus is reached if a _majority_ of the managers agree on a change. In other words, more than _half_ of the managers need to agree for any change made to the swarm state ("is a container running"? "is the service created?").

- For a single manager, that means 51% or more of 1 manager, so 1 manager needs to agree
- For _two_ managers, 51% or more of 2 manager, so 2 managers need to agree

Effectively, if you take down 1 manager in a 2-manager setup, you loose control over your cluster. In this state, the remaining manager can no longer control the cluster, nor can it update the information, or allow another manager to join (it needs consensus for that as well).

To remove a manager from the cluster, first _demote_ the manager (`docker swarm demote ..`), then remove the manager from the cluster. If you lost control over the cluster, you can re-initialize the swarm using `docker swarm init --force-new-cluster`.

Never run a cluster with 2 managers as it _doubles_ the chance you lose control (with two managers, chances are twice as big that a manager fails). Use a _single_ manager if you don't need fault-tolerance, or 3, 5 or 7 managers if you do. Keep in mind that more managers does not bring better performance (actually, the contrary, because the managers need to communicate and reach consensus on every decision).

Read the documentation here for more information: [Add manager nodes for fault tolerance](https://docs.docker.com/v1.13/engine/swarm/admin_guide/#add-manager-nodes-for-fault-tolerance), and [Raft consensus in swarm mode](https://docs.docker.com/v1.13/engine/swarm/raft/)

I'm closing this issue, because this does not appear to be a bug, but feel free to continue the conversation 👍
