### ISSUE TITLE
container timezone

### ISSUE THREAD

**Issue by wookietreiber** [moby/moby#3359]
As I experience it, containers use their internal timezone, not the timezone of their host OS.

I currently work around this issue by providing a [start script](https://github.com/wookietreiber/dockerfiles/blob/master/ganglia/start.sh) that takes a typezone parameter which is applied when the container gets started. This I set then in my [systemd service file](https://github.com/wookietreiber/dockerfiles/blob/master/ganglia/ganglia-full-stateless.service). However, to do this for every container (the script part), seems redundant and, considering this might be a rather common problem (at least if you are not in the timezone your container uses by default), I would very much like this being done via a `docker run` command line option:

```
docker run -timezone Europe/Berlin ...
```

with the default being the timezone of the host OS, i.e. evaluating `readlink -f /etc/localtime`.

Or, is there another way to do this?

**Comment by alvin664** [comment]
Hi albers,

Tried to use your approach in Dockerfile:

RUN sudo echo America/New_York > /etc/timezone && sudo dpkg-reconfigure --frontend noninteractive tzdata

But got error: cannot create /etc/timezone: Permission denied

How did you solve this problem?

**Comment by alvin664** [comment]
Never mind. I had to add "USER root" before setting the timezone. And it is working afterward.

**Comment by albers** [comment]
I already suspected this because you `sudo`ed the commands. Sorry, but I could no respond earlier. Glad to hear the issue is solved.

**Comment by frntn** [comment]
@alvin664 
If you are root, you don't need sudo anymore
If you want to stay with your non root user and use sudo instead :

```bash
RUN echo America/New_York | sudo tee /etc/timezone && sudo dpkg-reconfigure --frontend noninteractive tzdata
```

**Comment by naoko** [comment]
this worked beautifully. thank you so much

**Comment by conanca** [comment]
docker machine in centos7.1 don't have /etc/localtime

**Comment by dilbertside** [comment]
# Java related with busybox (previous comments do not work with barebone OS)
## no volume or with volume
`echo 'public class Main { public static void main(String[] args) { System.out.println("ZonedDateTime:");System.out.println(java.time.ZonedDateTime.now().toString());System.out.println("LocalTime:");System.out.println(java.time.LocalTime.now().toString()); } }' > Main.java`
`date ; docker run --rm -v /etc/localtime:/etc/localtime -v "$(pwd)":/mnt --workdir /mnt frolvlad/alpine-oraclejdk8:slim sh -c "javac Main.java && java Main"`

output is :
Thu Aug 11 **15:35:02 WIB 2016**
ZonedDateTime:
2016-08-11T**08:35:02.576Z[GMT]**
LocalTime:
**08:35:02.590**

## with following Dockerfile
```
FROM frolvlad/alpine-oraclejdk8:slim
RUN apk add --update --no-cache tzdata && \
    ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && \
    echo "Asia/Jakarta" > /etc/timezone && \
    date && \
    rm -fr /tmp/* /var/cache/apk/*

WORKDIR /tmp
RUN echo 'public class Main { public static void main(String[] args) { System.out.println("ZonedDateTime:");System.out.println(java.time.ZonedDateTime.now().toString());System.out.println("LocalTime:");System.out.println(java.time.LocalTime.now().toString()); } }' > Main.java
RUN javac Main.java && java Main
```
how to run `docker build .` 

output is: 


ZonedDateTime:
2016-08-11T**16:34:16.189+07:00[Asia/Jakarta]**
LocalTime:
**16:34:16.189**

**Comment by efaruk** [comment]
What about windowscore when we use Set-TimeZone in the container its changing both container and host machine timezones!? I guess not isolated enough?

**Comment by assertnotnull** [comment]
Facing this problem on 2 containers one MySQL and another unrelated Sentry. Why it isn't default? Because from what I see, it's like just better to always set -v /etc/localtime ... since as programmer, almost all actions are timestamped (web log, db timestamp..) and even introduced an error in one of my native app speaking to a containerized database.

**Comment by rogersillito** [comment]
In windowsservercore I'm unable to Set-Timezone within my dockerfile; I get Access is denied even having switched to user ContainerAdministrator.

**Comment by GreatTeacherBasshead** [comment]
@rogersillito I have the same issue. Have you found the reason or a workaround?

**Comment by dilbertside** [comment]
Few years since I first found a suitable solution for **Java**, what I proposed once may be obsolete while working.

In the interval, some solutions came as suitable too.
Using Google JIB for example
line 346 in 
https://github.com/dilbertside/spring-mvc-start-archetype/blob/master/src/main/resources/archetype-resources/pom.xml 
using `<TZ>Asia/Jakarta</TZ>` worked on one project

I stress that by setting an environment variable in Dockerfile such as
 `ENV TZ="Asia/Jakarta"`
the **JVM** read it at initialization, other language runtime may have the same mechanism as **Java** (meaning reading OS environment properties and setting default **JVM** values from them)
I will soon try to modify https://gitlab.com/net1/openjdk11-alpine/blob/master/Dockerfile to illustrate that point

**Comment by metawops** [comment]
I also need help with this issue. 😞 
My host is a Raspberry Pi 400 with Raspbian (buster) running the latest Portainer container. The Raspi has the correct date and time and timezone.
Both my nginx and my letsencrypt-nginx-proxy-companion containers have a date of January 1st, 1970. 😞 

I tried the TZ env variable – to no avail.
I tried both bind volume mappings, `/etc/localtime` and `/etc/timezone` – doesn't help either.
I don't know how/where to put the `RUN echo ...` command into the Portainer GUI? (Sorry, just started with Docker & Portainer.)
Also, when I go into the Console of the nginx container I can see that the `sudo` command is not found, so that commandline wouldn't work.

**Comment by tianon** [comment]
@metawops you're hitting something more like https://github.com/moby/moby/issues/40734 -- make sure you're on Docker 20.10.10+ and have libseccomp version 2.4.2+ (which you might have to get from backports or update your system to bullseye)

**Comment by metawops** [comment]
> @metawops you're hitting something more like #40734 -- make sure you're on Docker 20.10.10+ and have libseccomp version 2.4.2+ (which you might have to get from backports or update your system to bullseye)

Thx, @tianon. On the Raspi I'm running Docker 20.10.12 and I have no idea what `libseccomp` is or what it is used for. `sudo apt info libseccomp` gives no info. I'll definitely not upgrade to bullseye as it is still currently not recommended and comes with loads of potential other problems, apparently. 🤷‍♂️ Cannot afford to break the system.

Is it really that hard to have a container the same date & time as the host??? Unbelievable.

**Comment by tianon** [comment]
The issue you're running into is that the system call to request the system time is being blocked by libseccomp.  The exact package name is `libseccomp2`, and I imagine you're probably currently running 2.3.x, which unfortunately does not support the newer system calls necessary for the (newer) container you're trying to run.

It's honestly harder to have a Linux container that _doesn't_ have the same date & time as the host, since the time namespace in the kernel is still experimental, and the issue you're having only presents the way it does because of the aforementioned security filtering -- you'll find that it's not that the container has it's own sense of what date/time it is, but that it will appear to always be fixed at a very specific second at the unix epoch (because it's literally failing to ask the kernel what time it is entirely), and unfortunately the only available _fix_ is to update the appropriate packages on the host.

A workaround (which I don't recommend) would be to use something like `--security-opt seccomp=unconfined` which will just disable that security feature entirely.

**Comment by metawops** [comment]
Thanks again, @tianon, that helped a lot with understanding the issue! There seems to be a "backport" for buster of this lib in versions > 2.3 [here](https://packages.debian.org/buster-backports/libseccomp-dev) – but I have no idea whether it's safe to install such a version and how to do it. 🤷‍♂️

**Comment by metawops** [comment]
Wow. Problem solved! I added the buster backports to my sources.list and installed the libseccomp2-2.5.1-1~bpo10+1 armhf package. Restarted the containers and now they have the same date & time as my underlying Raspi host. 😊 
Thanks again, @tianon, for the help!
