### ISSUE TITLE
docker events - show events since timestamp

### ISSUE THREAD

**Issue by yaakov-berkovitch** [moby/moby#33593]
I'm running docker 17.05.0-ce on centos.
I'm using docker events with the since / until options.
My problem is that it seems that the event buffer is not enough huge and so events are not returned by docker events on burst of events (dropped from the buffer).

So, I would like to ask if there is way to customize the events buffer. Also is the buffer size  (if there is such "buffer") configured to hold a fix number of events or a certain interval of time ?

**Comment by thaJeztah** [comment]
No this is currently not possible, see https://github.com/moby/moby/issues/30502#issuecomment-275686051 and the discussion on https://github.com/moby/moby/issues/22917

Please subscribe to the linked issue to keep informed on updates, or participate in the discussion over there. I'll close this issue so that the discussion doesn't diverge
