### ISSUE TITLE
security-opt in Dockerfile

### ISSUE THREAD

**Issue by sujjit1991** [moby/moby#33595]
I am trying to add "security-opt" option in docker build file (Dockerfile), do we have any INSTRUCTION for that?

 I am using the stack.Yaml file in docker swarm to deploy the services which doesn't support the security-opt feature in the swarm, if I want to use the AppArmor and seccomp profiles in the swarm, is there any way to use it?

**Comment by thaJeztah** [comment]
Security options are runtime settings, and cannot be baked into an image. There is a current proposal to add this as a feature, but the design is still being discussed (for example; these options should not be automatically applied, because setting security options may mean: give _more_ permissions to an image than the default). See the discussion here; https://github.com/moby/moby/issues/32801

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍
