### ISSUE TITLE
docker manager node throwing rpc error

### ISSUE THREAD

**Issue by chaitu0292** [moby/moby#33631]
ours is a cluster of 11 machines and we have 3 manager nodes.Till date it used to work fine but due to unkown reasons machines got rebooted and docker engine didnt start on reboot.
So manually started. 
After that when i execute **docker node ls** its throwing the below error
_Error response from daemon: rpc error: code = 4 desc = context deadline exceeded_ 

What is this error?which caused this?which reason?

Environment:
centos 7
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64
Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by thaJeztah** [comment]
This error can have various causes (see https://github.com/moby/moby/issues?utf8=✓&q=is%3Aissue%20%22context%20deadline%20exceeded%22 for existing issues mentioning this error). The error itself is quite generic, and could mean that the manager was not able to communicate with other managers in the cluster. From _just_ the error, it's not easy to discover why it fails to communicate (it can be either a bad network connection, other managers did not properly re-join the cluster, therefore you lost quorum, or it could be if (e.g.) managers did not have a static IP-address, and the IP-address changed - which is currently not supported).

We have an issue to improve the error message, and provide more information about the specific reason for the error (where possible); see https://github.com/moby/moby/issues/29987, and https://github.com/moby/moby/issues/29367


Please keep in mind that the GitHub issue tracker is not a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is a support question, but feel free to comment after I closed.
