### ISSUE TITLE
docker ps hang  on occasion

### ISSUE THREAD

**Issue by qiuyu2014** [moby/moby#33664]
# Description
docker ps hang on occasion, only restart host can help.
# Steps to reproduce the issue

- Use docker with Kubernetes

- docker ps hang on occasion

# Describe the results you received
1. docker ps hang
2. systemctl status docker.service 
the docker state is: active (running)
3. kubectl get nodes 
the node status is:  Ready
4. kubectl can not operate pod in that node
# Describe the results you expected
Hanging command
# Additional information you deem important (e.g. issue happens only occasionally)
## Output of `docker version
`Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:23:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:23:59 2016
 OS/Arch:      linux/amd64
`
## Output of `docker info`:
docker info hang

## Additional environment details (AWS, VirtualBox, physical, etc.):
physical
centos: 7.3
kubernetes: 1.5

**Comment by thaJeztah** [comment]
Docker 1.12 reached end of life quite a while ago; there have been fixes in this area; are you still having this issue on the current release?

If you can't update to a newer version; make sure to install the 1.12.6 patch release, because it fixes a CVE that allowed processes to obtain host access; (CVE-2016-9962)

If you _are_ able to reproduce on a newer version, be sure to check logs and additional information you can find, otherwise there's not a lot to investigate.

I'm closing this issue for now, but feel free to continue the conversation
