### ISSUE TITLE
Entrypoint: files are not created on docker restart

### ISSUE THREAD

**Issue by sergik** [moby/moby#33768]
**Description**
I have a container with docker file like this:

```dockerfile
FROM node:boron-alpine
...

ENTRYPOINT ["/entrypoint.sh"]
```

And _entrypoint.sh_ like this:
```bash
echo -e "Host ${GIT_HOST}\n HostName ${GIT_HOST}\n IdentityFile ${SSH_KEY_PATH}/${SSH_KEY_NAME}\n" > /home/node/.ssh/config

run some app
```

In fact it adds some repo to known to skip validation. It creates a file in file system on entrypoint.

**Steps to reproduce the issue:**
1. Run container which creates file in file system in ENTRYPOINT
2. Check file - file created
2. Restart docker

**Describe the results you received:**
Container restarted, file in the file system is missing.

**Describe the results you expected:**
Container restarted, file in the file system exist.

**Comment by lewisdaly** [comment]
Actually I think you'll find this is the expected behaviour.

Can you list the commands you used to "Restart docker"? Does this mean restart the docker container? Or the Docker daemon itself?

Docker will persist any files created in the Dockerfile, but anything created after that point (such as any files created in your entrypoint) will not be persisted. So if you are recreating a container that is already running, your entrypoint script will not be run again, and the file will not exist.

You can use docker volumes to manage and persist data within containers: https://docs.docker.com/engine/tutorials/dockervolumes/#add-a-data-volume

**Comment by sergik** [comment]
I am restarting docker daemon. Thanks for reply.

**Comment by thaJeztah** [comment]
I'm not able to reproduce this issue:

Create a clean directory for the reproduction steps:

```bash
mkdir repro-33768 && cd repro-33768
```

Create an entrypoint script that creates a file with content "hello world"

```bash
cat > entrypoint.sh <<"EOF"
#!/bin/sh
echo -e "hello world" > /home/node/.ssh/config
exec "$@"
EOF
```

Build an image that uses the entrypoint script for `ENTRYPOINT`:

```bash
docker build -t repro-33768 . -f-<<EOF
FROM alpine
COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh && mkdir -p /home/node/.ssh/
ENTRYPOINT ["/entrypoint.sh"]
CMD ["sh"]
EOF
```

Start a container from that image (using a restart policy so that it's started again after the daemon is restarted):

```bash
docker run -dit --restart=always --name repro-33768 repro-33768
```

Verify that the file is there by showing its content:

```bash
docker exec repro-33768 cat /home/node/.ssh/config
hello world
```

Restart the daemon


Verify that the file is still there:

```bash
docker exec repro-33768 cat /home/node/.ssh/config
hello world
```


As far as I can see, this is all functioning as expected; do you have a minimal reproduction case to show what problem you see?

Also provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
