### ISSUE TITLE
awslogs drive should not prevent container from starting on failure to connect to AWS CloudWatch Logs endpoint

### ISSUE THREAD

**Issue by gkramm** [moby/moby#33803]
Docker Version: Docker version 17.05.0-ce
it can be the case that AWS CloudWatch Logs are un reachable.  In that case when you try to start a container it should simple throw an error and continue.  I'd much rather have loss of logs than having my service not start.

 steps
1.  null route your connection to logs.us-west-2.amazonaws.com (it's hard to actually take the real AWS cloud watch logs offline)
2. 

```
 docker -D run --log-driver=awslogs \
              --log-opt awslogs-region=us-west-2 \
              --log-opt awslogs-group=myLogGroup \
              --log-opt awslogs-create-group=true \
              busybox
```

```
DEBU[0000] [hijack] End of stdout
docker: Error response from daemon: failed to initialize logging driver: RequestError: send request failed
caused by: Post https://logs.us-west-2.amazonaws.com/: dial tcp 127.0.10.10:443: getsockopt: connection refused.
ERRO[0000] error getting events from daemon: net/http: request canceled
```

**Comment by cpuguy83** [comment]
If you use `--log-opt mode=non-blocking` this should allow the container to start up. It will buffer the logs up to ~ 1MB by default and then start dropping. You can also specify a custom buffer size with `--log-opt max-buffer-size=<size string>`

**Comment by gkramm** [comment]
I seem to be missing somting


[kramg003@ip-10-153-198-202 ~] grep logs.us-west-2.amazonaws.com /etc/hosts
127.0.20.1 logs.us-west-2.amazonaws.com
[kramg003@ip-10-153-198-202 ~]
``` 
              docker -D  run  \
           --log-opt mode=non-blocking \
           --log-driver=awslogs \
           --log-opt awslogs-region=us-west-2 \
           --log-opt awslogs-group=myLogGroup \
           --log-opt awslogs-create-group=true \
           busybox
```
```
DEBU[0000] [hijack] End of stdout
docker: Error response from daemon: failed to initialize logging driver: RequestError: send request failed
caused by: Post https://logs.us-west-2.amazonaws.com/: dial tcp 127.0.20.1:443: getsockopt: connection refused.
ERRO[0000] error getting events from daemon: net/http: request canceled
```
[kramg003@ip-10-153-198-202 ~] docker -v
Docker version 17.05.0-ce, build 89658be
[kramg003@ip-10-153-198-202 ~]

**Comment by thaJeztah** [comment]
@gkramm be sure to check if your _daemon_ is running 17.05 as well. I was not able to reproduce the issue; this was on 17.06, but I don't think anything changed for that option since 17.04

**Comment by gkramm** [comment]
@thaJeztah first thanks for adding labels to this issue. it makes it look so much better



```
[kramg003@ip-10-153-198-251 ~] /usr/bin/dockerd -v
Docker version 17.05.0-ce, build 89658be
```
AND
```
[kramg003@ip-10-153-198-251 ~] docker -v
Docker version 17.05.0-ce, build 89658be
```

to show I'm 'blocking' calls to AWS cloudwatch logs
```
[kramg003@ip-10-153-198-251 ~] grep log /etc/hosts
127.0.20.1 logs.us-west-2.amazonaws.com
```

```
docker -D  run   --log-opt mode=non-blocking  --log-driver=awslogs  --log-opt awslogs-region=us-west-2  --log-opt awslogs-group=myLogGroup  --log-opt awslogs-create-group=true  busybox
DEBU[0000] [hijack] End of stdout
docker: Error response from daemon: failed to initialize logging driver: RequestError: send request failed
caused by: Post https://logs.us-west-2.amazonaws.com/: dial tcp 127.0.20.1:443: getsockopt: connection refused.
```

**Comment by cpuguy83** [comment]
Yeah, I'm sure we're initializing the logger first and erroring out in cases where it can't connect.

**Comment by thaJeztah** [comment]
Discussing with @cpuguy83 on Slack; possibly if `--log-opt mode=non-blocking` is set, a retry-loop can be used so that the container will still start.

However, there's a risk that the configuration is invalid, or the connection will never be established, in which case it will just _keep_ retrying, and all logs would be lost (the user may be unaware of this, which could be bad).

**Comment by danielroop** [comment]
Bumping this thread since The “hard thing to do” of bringing down cloud watch happened today in AWS east.

In addition to startup being a problem we saw that a running system eventually crashed.  We are still digging into why but it seems it is related to the driver blocking causing a backup in the application.  This resulted in an inability to autoscale (because new containers couldn’t connect to Cloudwatch) and existing containers eventually crashed because the amount of volume was too great with the blocking logging calls.

Couple Questions:
1. What is the version of docker we need to upgrade to, to have `mode=non-blocking`? 17.04?
2. When the buffer gets filled (if it is blocking) will writes to stdout in the containerized application block?  Is that the behavior that is expected?
3. Is this in the awslogs plugin or in the log driver system?

**Comment by thaJeztah** [comment]
The "non blocking" mode was added in https://github.com/moby/moby/pull/28762, which is in Docker 17.04 and up. Docker 17.04 was an edge release though; the first "stable" release was 17.06 (the community edition of that is now EOL, but enterprise edition is still supported).

**Comment by PeterRJones** [comment]
We experienced similar symptoms to @danielroop with the recent AWS us-east-1 outage of CloudWatch. I had forgotten about the `--log-opt mode=non-blocking` setting. The AWS outage was ~ 3 hours, so a setting like this becomes really critical during an outage that long. Th

**Comment by cpuguy83** [comment]
@senese This is entirely dependent on the driver.
For fluentd there is an option `fluentd-async`: https://docs.docker.com/config/containers/logging/fluentd/#usage

**Comment by senese** [comment]
@cpuguy83 I was looking in the documentation and the option was defined in the logging driver page, not per logging driver page.

Although I tried your suggestion and it worked perfectly. Thank you so much!
