### ISSUE TITLE
macOS Docker Image Size At First Run

### ISSUE THREAD

**Issue by loretoparisi** [moby/moby#33848]
At very first docker startup, my docker image has been created, and keep growing up to **2,2-2,4GB**.
I do not have any container built, and no image downloaded or layer.

```
ls -lh /Users/loretoparisi/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 
-rw-r--r--@ 1 loretoparisi  staff   2,3G 27 Giu 17:35 /Users/loretoparisi/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2
```

I have `Version 17.03.1-ce-mac12 (17661)`

What's the reason of this size?

**Comment by thaJeztah** [comment]
This question is specific to Docker for Mac, can you reopen in that repository? (https://github.com/docker/for-mac)

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue here, but feel free to continue the conversation 👍

**Comment by loretoparisi** [comment]
@thaJeztah moved to mac https://github.com/docker/for-mac/issues/1782

**Comment by thaJeztah** [comment]
Thanks!
