### ISSUE TITLE
[Proposal] Add docker engine upgrade document in swarm mode cluster

### ISSUE THREAD

**Issue by BSWANG** [moby/moby#33869]
**Description**

Since docker `17.06.0-ce` have been released. How to upgrade swarm mode cluster' docker engine? Upgrade starting from worker or manager? And how to ensure the cluster `raft` store state.

**Comment by thaJeztah** [comment]
Yes, this is something that needs more documentation; I see there's an issue tracking this in the docs repository https://github.com/docker/docker.github.io/issues/2439, perhaps you can add a comment there?

The recommended approach is to first upgrade manager nodes (one at a time, so that you don't loose quorum); after manager nodes are upgraded, upgrade your worker nodes.

Depending on your situation, you may want to drain nodes before upgrading (`docker node update --availability=drain ..`), which will stop the tasks on that node, and re-deploy them to another node in the cluster (assuming there's enough resources to deploy the tasks elsewhere). After upgrading, you can make the node available again (`--availability=active`)

I'll close the issue here, because https://github.com/docker/docker.github.io/issues/2439 is tracking this, and this is a documentation issue, but feel free to comment after I closed
