### ISSUE TITLE
Volume mounts in windows does not work   : Unrecognized input header: 52

### ISSUE THREAD

**Issue by wilson45890** [moby/moby#33861]
I'm trying to share C Drive . I have got an error
Log :
[SambaShare ][Error ] Unable to mount C drive: Unrecognized input header: 52

Or when I did :  docker run hello-world
I have got the same error. Unrecognized input header: 52

window 10
Docker version 17.03.1-ce

Any advice on this would be helpful. Thanks in advance

**Comment by thaJeztah** [comment]
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this looks like a support question, but feel free to comment after I closed
