### ISSUE TITLE
where is tag 17.06.0-ce?

### ISSUE THREAD

**Issue by dotNetDR** [moby/moby#33894]
Can i see commit id 02c1d87?

```
# docker --version 
Docker version 17.06.0-ce, build 02c1d87
```

**Comment by vdemeester** [comment]
@dotNetDR `moby/moby` is not `docker-ce`, it's the `base` of `docker-ce`. As written [here](https://github.com/moby/moby/issues/33874#issuecomment-311934519) : `docker` releases now happens in `docker/docker-ce` repository : https://github.com/docker/docker-ce/releases — thus, the commit is on `docker-ce` repository, not here.

**Comment by ndegory** [comment]
slightly off topic, @vdemeester what is the story for vendoring? I have a dependency on the go API (still github.com/docker/docker/client and github.com/docker/docker/api/types, leading here), and up to 17.05.0-ce there was a tag we could rely on. Having to resort to commit ids in the vendor.conf instead of well identified tags will quickly become an issue. Today I'm not sure how to reference the stable Docker API.

**Comment by Zalgo2462** [comment]
Necro'ing this thread because I am in the boat as @ndegory. 

Any suggestions? Thinking about using https://github.com/docker/docker-ce/tree/master/components/engine/client as the go package url.
