### ISSUE TITLE
How to access environment variables, which were declared in env_file?

### ISSUE THREAD

**Issue by butterflyinfly** [moby/moby#33983]
Hello to Everyone,

Could you please help me with the following?

I'm running database in docker and do not want to set POSTGRES_USER and POSTGRES_PASSWORD as env variables for security reasons. That's why I put those values into the env file, something like:
$ cat /home/env.conf
POSTGRES_DB=blabla
POSTGRES_USER=blabla
POSTGRES_PASSWORD=blabla

And I pass the location of this file via marathon(but it doesn't matter, I can pass it via docker run --env_file /path/to/file/with/env/var)

When I login into the docker with database, I can't see user and password while running env command. And that's what I tried to do. But before putting env variables into the file, I used to get them by calling  os.environ, for example, os.environ.has_key("POSTGRES_USER") and so on. Currently this way doesn't work. Of course, I can get those values  by  searching at env_file, but I do believe that there is a much easier way to do it. 

So the questions - is there a way to get env variables, which were passed to docker by --env_file?

Thanks

**Comment by thaJeztah** [comment]
You may want to check your commands as well, because the flag is named `--env-file`, not `--env_file`.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because of the above, but feel free to continue the conversation 👍
