### ISSUE TITLE
Docker push fails with "file integrity checksum failed" seemingly at random

### ISSUE THREAD

**Issue by ColinChartier** [moby/moby#33991]
Docker save and docker push both fail for some images seemingly at random with "file integrity checksum failed"

I use a custom-made tool to build a bunch of docker images at once, and on basically every docker version I've used (CE 17.06.0, 1.12.1, 1.12.6, 1.11.1), I get an error where some of the built images can't be pushed or saved with the message `file integrity checksum failed for "services/base_server/lib/apt/libgtk2.0/libasan2_5.4.0-6ubuntu1~16.04.4_amd64.deb"` or equivalent (always a `.deb` file, but that might just be because the majority of files are `.deb`)

**Steps to reproduce the issue:**
I can't give repro steps outside of a single computer, the build system seems to work everywhere else.

**Describe the results you received:**
 `file integrity checksum failed for "services/base_server/lib/apt/libgtk2.0/libasan2_5.4.0-6ubuntu1~16.04.4_amd64.deb"`

**Additional information you deem important (e.g. issue happens only occasionally):**
I've tried overlay2 and aufs, so this doesn't seem to be a graph driver bug.  Others at my company also don't get this bug (with the same environment, OS, and docker version)

I tried upgrading my kernel, then my entire OS (ubuntu 14.04 to ubuntu 16.04) and multiple docker versions, but I might just be cursed.

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 6
 Running: 4
 Paused: 0
 Stopped: 2
Images: 427
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 421
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.0-58-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 62.85GiB
ID: 46HT:IF2S:6OKV:J7K3:VQUG:ZZTN:PPC6:ZJFR:HRO2:P5FR:3WN5:PFVC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by ColinChartier** [comment]
Fixed: This was because one of my ram sticks was bad, and a single bit swap was happening on operations with a lot of writes.

I'm not going to close this because I think a (try a memory check) message would save a lot of headache if this ever happens again.

**Comment by thaJeztah** [comment]
Good to hear you resolved the issue.

I don't think we should add such a message; it's possible the checksum failed for other reasons (such as disk failure); mentioning just one possible cause (and doing a completely wild guess) may send users in the wrong direction.

I'll close this issue, but let me know if you feel strongly about adding more information to the error message.

**Comment by RoshanJeewantha** [comment]
Hi,

I was having something similar when using docker push. 

> file integrity checksum failed for "lib/systemd/systemd-logind"

My image was over 100 MB and using Docker Version 17.06.2-ce-win27.

To fix that I had to increase the allocated memory for Docker engine. Go to Docker settings > Advanced.

Regards,
RJ

**Comment by glyph** [comment]
I've also encountered this issue, using Docker for Mac:

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true
```

(with Experimental being both `true` and `false`).

Following @RoshanJeewantha's advice to increase the RAM allocated to the docker VM seems to have resolved the issue.  Is the OOM killer nuking things during the build process?  This is the only thing I can think of.  (Extensive hardware tests indicate that the machines I'm running Docker on most definitely do not have bad RAM.)

**Comment by jamshid** [comment]
I don't what caused this in my case, don't think it's bad or insufficient memory. One of my base images just had a bad layer or checksum I guess, but it has otherwise been working fine. 

I noticed the error because a push to a registry (even different registries) was failing for a particular image, always at the same layer, so I tried to just `save` the image and that also showed the error:
```
$ docker save -o /tmp/badrtjar.tar badrtjar:gateway-build
Error response from daemon: file integrity checksum failed for "usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-5.b12.el7_4.x86_64/jre/lib/rt.jar"
```
I tagged the bad image, created on Docker for Mac Edge Version 17.12.0-ce-mac45 (21669). Maybe there's some way to diagnose the problem?

Anyway I forced a rebuild of the base image to workaround this weird kinda disturbing problem. I'm worried there is a bug, that it's more than "bad hardware". Seems to turn up often e.g. https://forums.docker.com/t/file-integrity-checksum-failed-on-docker-save/14715/10.

**Comment by thaJeztah** [comment]
@jamshid may be worth reporting in the Docker for Mac issue tracker if you haven't done so yet; https://github.com/docker/for-mac/issues

**Comment by chicofilho** [comment]
Had exactly the same problema. It worked after I deleted the images and rebuilt

**Comment by doudouOUC** [comment]
I also met this poblem. if anyone have answers , please tell me.

**Comment by ankitshah009** [comment]
Facing a similar problem and unable to solve the problem using the solutions provided in this thread. 
Please inform on how to resolve this problem. Rebuilding is not an option as it took me days to reach this stage with the docker image.

**Comment by lithium-li** [comment]
`docker system prune -a`  solved the problem

**Comment by donghl** [comment]
docker system prune -a

**Comment by jacobtomlinson** [comment]
Also having this issue. Seems to fail on a layer which is 3GB. I have allocated 6GB of RAM and already run `docker system prune -a`. Still no luck!

**Comment by thaJeztah** [comment]
@jacobtomlinson could you open a new ticket with details about your setup?

**Comment by vedrusss** [comment]
I wasn't able to find the solution how to increase memory for docker engine in ubuntu 16.04 (no gui provided).
docker system prune -a      looked very tricky to me, I knew it'll remove ALL my containers and images.
Having no another decisions what to do I tried it, lost my images. Downloaded new ones, build new ones and...
it helped: after 5-8 mins wait I've got my saved image :)

**Comment by jecsham-icte** [comment]
Rebuild the image is a good solution.

**Comment by wuchuxiong** [comment]
Face the same issue on Docker CE 19.03.5 at random.
Loading the image into docker runtime with command "docker load -i image.tgz", it shows images are loaded successfully and the return code is 0. But if I push a image which is loaded with previous command to the registry, the issue happens. If I try to save the image from docker runtime with command "docker save -o /tmp/myimage.tar <myrepo/myorname/image:tag>, I got the same error.

My workaround is clean the memory cache with “sync; echo 3 > /proc/sys/vm/drop_caches”
delete the image and reload it again.

**Comment by calvincramer** [comment]
The other possible solutions about 'bad ram sticks' seem _extremely_ unlikely to be the actually problem, and did not pass the smell test.
Also, the solution for Windows / Mac about increasing amount of memory available to the docker engine VM didn't apply to unix based systems.
I was experiencing this on Ubuntu 18, and the solution from @chicofilho and @senor-artemisio solved the issue. Specifically I removed all the base images and all my old images, and did a `docker build ... --no-cache`. 
Then I verified the issue is not longer present with a docker save, from @jamshid's comment: `docker save -o /tmp/myImage.tar myImage:latest`

**Comment by calvincramer** [comment]
Also, I solved this issue using `docker system prune -a`. This issue definitely makes me lose faith in docker as a reliable tool. I thought an image is an image is an image, as long as the image id is the same. Apparently not though.

If anyone figures out how to reproduce this issue (starting from a working system), or figures out the root cause of this, please share. The only way I have seen this issue is after a enough days of building images, running containers, pruning old images and containers, eventually this issue pops up.

**Comment by michielbdejong** [comment]
In my case with Docker version 20.10.11 on MacOS I first encountered some error about a readonly filesystem (I use an external USB stick for storage), and after a reboot I ran into the "file integrity checksum failed" issue on `docker push`. 
So maybe it was caused by the earlier failure to write to disk?
After `docker system prune -a` and newly `docker build`, the `docker push` was finally successful. Thanks for that tip!

**Comment by calvincramer** [comment]
Readonly file system should not matter. Checksum algorithms are read only. AFAIK docker uses sha256 to checksum layers... probably with more hidden complexity, don't have time to check right now.
Checksum on readonly file system:
```sh
mkdir -p /tmp/foo
echo "asdf" > /tmp/foo/a.txt
sudo mkdir -p /media/test
sudo mount --bind --options ro /tmp/foo /media/test
md5sum /media/test/a.txt    # 2b00042f7481c7b056c4b410d28f33cf
sha256sum /media/test/a.txt    # d1bc8d3ba4afc7e109612cb73acbdddac052c93025aa1f82942edabb7deb82a1
sudo umount /media/test
```

**Comment by calvincramer** [comment]
Not sure if this the right source but https://github.com/moby/moby/blob/master/vendor/github.com/vbatts/tar-split/tar/asm/assemble.go#L89 shows CRC checksum (what the standard `cksum` linux binary uses) being used. Still need to find a way to reproduce this issue, so if anyone find it that would be very helpful!

**Comment by NayanVerma10** [comment]
I was facing this issue while pushing the images.

I build and pushed the same image from a different machine, which worked just fine. Then subsequent pushes were working fine from the original machine

**Comment by Symbolk** [comment]
> `docker system prune -a` solved the problem

Use with caution! This is like rm -rf .....

**Comment by thaJeztah** [comment]
> Readonly file system should not matter. Checksum algorithms are read only. 

Read only file system can be due to an issue with the file system itself (e.g., you ran out of disk space), in which case the operating system puts it in read only mode for recovery.

The checksum failures could be a result of that (disk ran out of space, and files were partially written).

Note that on Docker Desktop, images are stored within a VM, so "out of space" in that case would be out of space _within the VM_, not necessarily the machine as a whole

**Comment by mjasawat** [comment]
I am still getting below error. 

#docker save -o ansible_awx2.tar ansible/awx
Error response from daemon: file integrity checksum failed for "var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/ui_next/build/static/media/logo-header.svg"

**Comment by Manojjasawat** [comment]
I used it "docker system prune -a" but still i am facing this issue.
Could you please help me? 
 
#docker save -o ansible_awx2.tar ansible/awx
Error response from daemon: file integrity checksum failed for "var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/ui_next/build/static/media/logo-header.svg"

**Comment by akselerando** [comment]
I just had the same issue on Ubuntu 22, Docker version 27.4.1, build b9d17ea. `docker system prune -a` solved the issue for me aswell.
