### ISSUE TITLE
Docker containers are likely paused randomly

### ISSUE THREAD

**Issue by Vespira** [moby/moby#34009]
Hi,

I'm not really sure of what is implied in this issue, so I lay it down here. If someone experienced something similar to the problem i'll describe, it would be awesome to share me your infos/solution.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
I've installed few CoreOS hosts being managed by Rancher & Kubernetes, to deploy Dockerized apps environments.

So each VM have a docker installed, and it can happen on any host that one day, Docker pauses, and the containers will not being woke up until I execute a "docker ps".

Other info: when I do a docker info while the issue is occuring, it restart containers, but I see all of these in state "stopped".

It then retrieve me that the container is up less than a second ago: 
<img width="484" alt="dockerpsbug" src="https://user-images.githubusercontent.com/2392574/27958290-a8e7aa38-6322-11e7-8aee-2b711fc3c1db.PNG">

I usually start my container like this :
` docker run -d --restart=always`
Or it's rancher which manage it.

I'm not sure of where the probleme is located, so I'm trying Docker-level, at first. Does anybody can help me ? Thanks a lot !

**Steps to reproduce the issue:**
It's kind of erratic, sometimes it takes days, or even weeks.

**Describe the results you received:**
No response from container

**Describe the results you expected:**
Container returning a response to an external request

**Additional information you deem important:**
Issue is appearing sometimes, days or weeks after having "unpaused" manually the containers execution

**Output of `docker version`:**

Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.5
 Git commit:   a82d35e
 Built:        Thu Jul  6 01:03:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.5
 Git commit:   a82d35e
 Built:        Thu Jul  6 01:03:25 2017
 OS/Arch:      linux/amd64

**Output of `docker info`:**

Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host overlay bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp selinux
Kernel Version: 4.11.9-coreos
Operating System: Container Linux by CoreOS 1409.6.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.863 GiB
Name: vm-dnldbb1-dev
ID: TBAR:5BKM:RANQ:GFWQ:3MPW:JIPE:MYHS:XNIU:IIMX:SEVK:MGY6:7JOP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**

All Docker instances runnig on VM
`uname -a `:
Linux vm-dnldbb1-dev 4.11.9-coreos #1 SMP Thu Jul 6 00:54:42 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2698 v3 @ 2.30GHz GenuineIntel GNU/Linux

**Comment by thaJeztah** [comment]
I think there's too many moving parts here to say anything useful; I'll leave some thoughts;

- have you checked logs for the daemon ?
- have you checked logs of the container that was stopped; perhaps it shows the reason it stopped
- did coreos recently perform an auto-update?

in addition;

- Docker 1.12.6 is an old release, and no longer maintained
- The version of Docker shipping with CoreOS is built and packaged by CoreOS, and contains modifications from a Vanilla Docker version We cannot provide support for the CoreOS packages.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because there's not enough information to go on, and the version of docker that's installed is not maintained here, but feel free to continue the conversation 👍

**Comment by Vespira** [comment]
Thanks for taking time to provide me some useful infos. I forgot to paste
logs here, but containers logs doesnt show something weird, im only seeing
common app log and no hint on why it stopped. (I'll paste it here when the
issue will show up again)

I already tried a question on stackoverflow (not this one though), but as
its a vast issue and not so much people play on the docker tag I had quite
an empty thread.

Anyway, i'll keep in mind to update docker soon, and maybe checks how
docker service is instancied (already tried a nohup to detach processus
from session, even if it seems to come from somewhere else).

Have a nice WE,
Alex

Le 8 juil. 2017 10:40, "Sebastiaan van Stijn" <notifications@github.com> a
écrit :

**Comment by Vespira** [comment]
Hi there, only to give some precision over my issue here : 

In the Docker technical logs, I have a line : 

> Jul 20 04:27:37 vm-rancher-dev systemd[1]: Stopping Docker Application Container Engine...
> Jul 20 04:27:37 vm-rancher-dev dockerd[895]: time="2017-07-20T04:27:37.598041080Z" level=info msg="Processing signal 'terminated'"

I was thinking it could be something sending a SIGTERM to the dockerd process, something like .... OOMKiller for example.

I'll update Docker right now on our Rancher platform and see if it act differently.
