### ISSUE TITLE
Native Docker on Windows Server 2012

### ISSUE THREAD

**Issue by FrankTheCodeMonkey** [moby/moby#34042]
**Description**

Supporting Docker natively on Windows Server 2012 without having to use Docker Toolbox as virtualization.

**Describe the results you received:**

The WS 2012 server we intended to install Docker is already a VM itself, thus nested virtualization isn't feasible in this scenario. Are there any workarounds that does not involve virtualization? Or moreover, alternatives to Docker that supports WS 2012.

**Describe the results you expected:**

N/A.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Windows Server 2012 VM.

**Comment by cpuguy83** [comment]
Server 2012 does not have the required functionality for containerisation.
I know there are some companies out there that provide some sort of container-like thing for older Windows versions... I don't recall the products/companies off the top of my head.

Closing since this isn't really a moby issue.
Thanks!

**Comment by FrankTheCodeMonkey** [comment]
Hey thanks for the reply. I actually came across this repo because of issue #11680.
