### ISSUE TITLE
Cannot sudo if userns-remap=default is set in dockerd 

### ISSUE THREAD

**Issue by karlgrz** [moby/moby#34064]
Minimal Dockerfile used to reproduce:

```
FROM alpine:3.6 
RUN apk update && apk add --no-cache sudo
```

And my docker drop-in:

```
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd --userns-remap=default
```

Then run this docker run command:

```
$ docker run -it --rm --name test --userns host test sudo -u nobody
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
```

This is expected result, as root user (which currently owns the sudo binary) is remapped. In my case, here's the output of the ownership of top level at /:

```
$ docker run -it --rm --name test --userns host test ls -ltrah
total 60
drwxrwxrwt    2 165536   165536      4.0K Jun 25 17:52 tmp
drwxr-xr-x    2 165536   165536      4.0K Jun 25 17:52 srv
drwxr-xr-x    2 165536   165536      4.0K Jun 25 17:52 sbin
drwxr-xr-x    2 165536   165536      4.0K Jun 25 17:52 run
drwx------    2 165536   165536      4.0K Jun 25 17:52 root
drwxr-xr-x    2 165536   165536      4.0K Jun 25 17:52 mnt
drwxr-xr-x    5 165536   165536      4.0K Jun 25 17:52 media
drwxr-xr-x    2 165536   165536      4.0K Jun 25 17:52 home
drwxr-xr-x    2 165536   165536      4.0K Jun 25 17:52 bin
dr-xr-xr-x   13 root     root           0 Jul 11 21:56 sys
drwxr-xr-x   15 165536   165536      4.0K Jul 11 22:36 var
drwxr-xr-x   10 165536   165536      4.0K Jul 11 22:36 usr
drwxr-xr-x    6 165536   165536      4.0K Jul 11 22:36 lib
drwxr-xr-x   16 165536   165536      4.0K Jul 11 22:42 etc
-rwxr-xr-x    1 165536   165536         0 Jul 11 22:42 .dockerenv
drwxr-xr-x   28 165536   165536      4.0K Jul 11 22:42 ..
drwxr-xr-x   28 165536   165536      4.0K Jul 11 22:42 .
dr-xr-xr-x  362 root     root           0 Jul 11 22:42 proc
drwxr-xr-x    5 root     root         360 Jul 11 22:42 dev
```

This makes sense to me, since I'm still running as root in the container, despite it being remapped to a different host user.

What's the best practice here for running a service in this container as another user? Before user namespacing was implemented, we just ran the service as nobody user in the container, and that worked ok. How do I sudo to an unprivileged user if the sudo binary cannot be executed? 

Workaround hack is to run this in my container after it starts:

```
apk del sudo && apk update && apk add sudo
```

Then sudo has the correct permissions (owned by root.root in the container) and I can run my script as expected. 

I understand that sudo is probably not the best idea now with user namespacing, but what's the best way to go about this? 

(also, my apologies if this is the wrong place for this inquiry...feel free to close it and let me know where to go, thanks!)

**Comment by thaJeztah** [comment]
I'm having  bit of trouble understanding your use case;

- `--userns-remap=default` enables user namespaces, and remaps users inside the container (`root` inside container == unprivileged user outside
- when enabling this option, container's filesystems are also owned by the remapped user (so files owned by `root` are owned by the "remapped root" (`165536:165536`) in your case
- you start the container with `--userns=host`, which disables remapping for the container's user, so `root` inside the container == `root` on the host; as a result `root` is no longer owner of files created by the remapped root
- however, you're trying to run a process as unprivileged user

Instead of disabling userns for that container, why not _enable_ it, and run `sudo -u nobody`? This should make you switch from "remapped root" to "remapped nobody"

Alternatively, start the container with `-u <uid>:<gid>` to run as a different user

Perhaps `gosu` would work, but I haven't tried; https://github.com/tianon/gosu

**Comment by karlgrz** [comment]
@thaJeztah hey, thanks for the quick response! 

Yes, I think this is PEBKAC and me not fully having a grasp around the user namespace functionality. I think I need to better align the file system permissions with the remapped user and that should resolve what's happening here. 

Closing, thanks!

**Comment by jandsu** [comment]
@thaJeztah, sorry to comment on this old closed issue, but I was just caught by this behaviour as well...

Please let me try and clarify what is puzzling me:

You write

    when enabling this option, container's filesystems are also owned by the remapped user (so files owned by root are owned by the "remapped root" (165536:165536) in your case

so far so good

    you start the container with --userns=host, which disables remapping for the container's user, so root inside the container == root on the host; as a result root is no longer owner of files created by the remapped root

This is where you lose me: if I use the `--userns=host`, I expect that for this container, it simply discards the effect of having started the daemon with a mapping. So I expect that the 1st quote above become not applicable: *when enabling this option* ==> no, I do not wish to enable this option for this container, so why create its filesystem withe the remapped user??

To me, this breaks the expectation of a user who turns off the flag for a given container: he does not expect his root user not to own the filesystem, does he, let alone sudo, there are other processes who check for file ownership.

Any clarification would be welcome.

**Comment by thaJeztah** [comment]
@jandsu Unfortunately, user mapping per-container is not currently possible, so there are limitations in the `--userns=host` option. There was some discussion on the pull request that implemented this option, where the maintainers had to choose between "not adding the option", or "adding the option, with the knowledge there are limitations"; see https://github.com/moby/moby/pull/20111#issuecomment-181909631

This means that, although user remapping is not enabled for containers (`--userns=host`), ownership of the the containers filesystem (because the read-only (image) layers are shared between containers) will still be remapped. Support for per-container user-mapping might arrive in the future, but depends on some features in the Linux kernel (see https://github.com/moby/moby/issues/28593)

I notice that this limitation is not mentioned in the documentation about user namespaces, and should be added there; https://docs.docker.com/engine/security/userns-remap/#disable-namespace-remapping-for-a-container

Perhaps you could [open an issue in the documentation issue tracker](https://github.com/docker/docker.github.io/issues/new?body=File:%20[engine/security/userns-remap.md](https://docs.docker.com/engine/security/userns-remap/)) (or a pull request) for that?

**Comment by jandsu** [comment]
Thanks @thaJeztah! It's too bad for us, but at least I understand now ;)
