### ISSUE TITLE
docker attach hangs for silent container

### ISSUE THREAD

**Issue by tmp6154** [moby/moby#34214]
**Description**

docker attach hangs for container that doesn't produce any output.

**Steps to reproduce the issue:**
1. Create and run a silent container.

$ sudo docker run -d busybox sleep 1000
689efdd1c04f4075e9ef2cb46c549a060851dce50de7b9509cc956418350d946

2. Attach to it.

$ sudo docker attach 689efdd1

**Describe the results you received:**

After executing above command, attach would be hanged. It doesn't react to SIGINT by Ctrl+C, it doesn't react to SIGTERM. It will stay hanged until it's killed.

**Describe the results you expected:**

Command not hanged.

**Additional information you deem important (e.g. issue happens only occasionally):**

100% reproducible under Archlinux, Fedora and CentOS.

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   3dfb8343
 Built:        Sat Jul  8 20:56:41 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87617
 Built:        Sat Jul  8 22:56:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 3
Server Version: 17.06.0-ce
Storage Driver: devicemapper
 Pool Name: docker-8:35-5768183-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 454.7MB
 Data Space Total: 107.4GB
 Data Space Available: 38.87GB
 Metadata Space Used: 1.253MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.146GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.141 (2017-06-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.11.9-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.58GiB
Name: vostrosablin
ID: 4I2G:JS5T:B5Q7:B7DM:UISX:RF2D:PSBC:TP4L:STHX:J5K7:RVDR:RKOM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Hardware workstation.

**Comment by thaJeztah** [comment]
This is expected, because there's no TTY or STDIN attached to the container, so signals are not sent to the container, nor is docker listening to keyboard shortcuts. In addition, a process running as PID1 (i.e. as container's main process) may act different than when running as "not" the primary process. PID1 is "special" (as it's usually the computer's main process, therefore should _never_ be terminated as that would reboot the system); see https://docs.docker.com/engine/reference/run/#foreground

> **Note**: A process running as PID 1 inside a container is treated specially by Linux: it ignores any signal with the default action. So, the process will not terminate on `SIGINT` or `SIGTERM` unless it is coded to do so.

In this case, PID1 is the shell, which does not forward signals, therefore the process won't terminate if you send `CTRL-C`.

Try one of the following;

Run the container with both `-i` (keep `STDIN` open), and `-t` (attach a `TTY`);

```bash
$ docker run -dit busybox sleep 1000
7344318913b6ad7d9933a031bbde7264e9f03554c89ff4654b3baaba9fe21b66

$ docker attach 7344318913b6ad7d9933a031bbde7264e9f03554c89ff4654b3baaba9fe21b66
```

Press `CTRL-p, CTRL-q` to _detach_ from the container;

```bash
^p^q
read escape sequence
```

The container will still be running, you just _detached_

Run the container with just a TTY attached;

```bash
$ docker run -dt busybox sleep 1000
85cdbf34c8c2274a5a7cbd7d0705b20a1967ea93386bdb2bbc9cd74c0d980f55
```

Attach to the container, and press `CTRL-c`; there's a TTY attached now, so docker is able to receive these signals. Given that there's no `-i` (`STDIN`) attached to the _container_, the container won't receive the `CTRL-c`, but instead the docker CLI receives this signal, and terminates;

```bash
$ docker attach 85cdbf34c8c2274a5a7cbd7d0705b20a1967ea93386bdb2bbc9cd74c0d980f55
^C
```

docker cli terminates, and you return to your shell. The container is still running, and can be stopped using `docker stop <container id>` or `docker kill <container id>`

I don't think there's a bug here, so I'll close this issue, but feel free to continue the conversation
