### ISSUE TITLE
Cannot ADD tgz from URL without decompression

### ISSUE THREAD

**Issue by ergoithz** [moby/moby#34243]
Docker command **ADD** now extract archives retrieved from URLs (version version 17.06.0-ce, arch build 3dfb8343), and due COPY not supporting URLs, this should be considered a regression of issue #4391

My workaround for envconsul.
```
ENV ENVCONSUL_VERSION 0.6.2
ADD \
  https://releases.hashicorp.com/envconsul/${ENVCONSUL_VERSION}/envconsul_${ENVCONSUL_VERSION}_linux_amd64.tgz \
  /tmp/envconsul.tgz

RUN set -x \
    && if [ -f "/tmp/envconsul.tgz/envconsul" ]; then \
        cp /tmp/envconsul.tgz/envconsul /usr/bin/envconsul; \
    else \
        tar -xf /tmp/envconsul.tgz -C /usr/bin envconsul; \
    fi 
```

**Comment by thaJeztah** [comment]
This is a known issue, and has been resolved already on master, and will be fixed in the upcoming 17.06.1 patch release.

This issue is mentioned in the release notes; https://github.com/docker/docker-ce/releases/tag/v17.06.0-ce

> NOTE: Docker 17.06.0 has an [issue](https://github.com/moby/moby/issues/33849) in the image builder causing a change in the behavior of the ADD instruction of Dockerfile when referencing a remote .tar.gz file. The issue will be [fixed](https://github.com/moby/moby/pull/33851) in Docker 17.06.1.


I'm closing this issue because this is a duplicate of https://github.com/moby/moby/issues/33849, and has been fixed by https://github.com/moby/moby/pull/33851, which will be included in docker 17.06.1

Thanks for reporting though! And feel free to continue the conversation; just closing this for housekeeping 😅
