### ISSUE TITLE
Global service does not have "replicas"

### ISSUE THREAD

**Issue by dvohra** [moby/moby#34251]
A Swarm mode `global `service does not have replicas, but the term for a global service is "tasks".  But the `REPLICAS` column is displayed even for a `global` service with `docker service ls` command. And, the documentation also refers to `global `service tasks as replicas. "Replicas" is for tasks that are replicated.

**Comment by dvohra** [comment]
Also reopening https://github.com/docker/swarmkit/issues/887

**Comment by aaronlehmann** [comment]
This is a CLI issue and belongs at https://github.com/docker/cli/issues. The code in the swarmkit repository doesn't implement `docker service ls`.

Since `docker service ls` displays both global and replicated service, I think it makes sense to have a replicas column, even though it's only applicable to replicated services.

If you want to continue the discussion or suggest alternatives, please open an issue at https://github.com/docker/cli/issues.
