### ISSUE TITLE
Unable to start mysql service inside container unless I touch files first

### ISSUE THREAD

**Issue by ljfranklin** [moby/moby#34390]
**Description**

I have a simple Debian docker image that installs mysql-service. When I try to start the service inside the container, it fails to start. However, if I *touch* all the existing files under `/var/lib/mysql/mysql/`, it starts as expected. This bug is not present on my Ubuntu 16.04 laptop, but we do see it on our OSX workstations and our CI system (Concourse CI, Linux hosts with runC containers). An Ubuntu base image also shows the same problem.

**Steps to reproduce the issue:**

Dockerfile:
```
FROM debian:jessie

RUN echo 'mysql-server mysql-server/root_password password password' | debconf-set-selections \
    && echo 'mysql-server mysql-server/root_password_again password password' | debconf-set-selections \
    && apt-get update \
    && apt-get -y install mysql-server
```

Failure case:
```
docker build -t mysql-fails .
docker run -it mysql-fails /bin/bash -c 'service mysql start'
[FAIL] Starting MySQL database server: mysqld . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . failed!
```

But if you `touch` some files, it works:

```
docker build -t mysql-fails .
docker run -it mysql-fails /bin/bash -c 'find /var/lib/mysql/mysql -exec touch -c -a {} + && service mysql start'
[ ok ] Starting MySQL database server: mysqld ..
[info] Checking for tables which need an upgrade, are corrupt or were
not closed cleanly..
```

Why would changing the access time of the files have any effect?

Additional mysql logs can be seen here: https://gist.github.com/ljfranklin/4a28740fbdfd86b896529f70be254768.

**OSX Docker versions (has issue):**

```
$ docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

```
$ docker info
Containers: 90
 Running: 0
 Paused: 0
 Stopped: 90
Images: 82
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.36-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: 7R5E:YF5Q:LQY5:MQVZ:ZM7Z:M4UP:VZXD:QKSZ:F4ZI:HCIT:PBJ2:OIZL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 20
 Goroutines: 38
 System Time: 2017-08-03T15:50:18.950075628Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

However, the same version on a Linux host works as expected:

```
$ docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
$ docker info
Containers: 31
 Running: 0
 Paused: 0
 Stopped: 31
Images: 61
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 151
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-87-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.681GiB
Name: lyle-XPS-13-9360
ID: 65SN:4OEY:GBTC:YP7U:LSNC:6SLQ:3I2R:IZYS:2DK5:O25S:3CAM:EG4E
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: cfcapidocker
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

Appreciate the help!

**Comment by thaJeztah** [comment]
I suspect this may be related to the storage driver in use (`overlay2` vs `aufs`); databases generally don't like to run on a layered / union filesystem, and possibly aufs "just" works, and overlay2 is taking it too far.

The downside of installing services (such as MySQL) with `.deb` packages is that they will _start_ the service after installation, which generally isn't what you want in a Dockerfile (as each `RUN` is a new container, so even if the service starts, it will not be running in the next `RUN`).

Your steps to create the files upfront makes MySQL skip initializing the database, thus prevent the problem of it running on an the layered/union filesystem.

The official MySQL image takes a similar approach (and removes the files afterwards, so that actual initialization takes place the first time the image is _run_ intead of during `docker build`); https://github.com/docker-library/mysql/blob/0590e4efd2b31ec794383f084d419dea9bc752c4/5.7/Dockerfile#L49-L61


To test/verify if this is indeed the cause (overlay vs aufs), you can configure one of the Linux machines to use the overlay2 driver, and see if it also fails. (This requires the Linux machine to be running a 4.x kernel)

To do this;

Assuming you don't have a `daemon.json` file yet (as the steps below will overwrite the existing one);

```bash
mkdir -p /etc/docker

echo '{"storage-driver":"overlay2"}' > /etc/docker/daemon.json

systemctl restart docker.service
```

If you're seeing the same problem as on the Docker for Mac machines, that would confirm that it's related to MySQL not able to use overlay/overlay2 as a filesystem for its data-storage


To switch back to `aufs`, either change that configuration file to use `aufs` instead of `overlay2`, or;


- stop the service `systemctl stop docker.service`
- remove the `/etc/docker/daemon.json` file (or remove the `"storage-driver"` option from it)
- remove the `/var/lib/docker/overlay2` directory
- start the service `systemctl start docker.service`


Overlay2 is going to be the default driver for most platforms (aufs is no longer supported on some distros, and overlay2 is fast, and part of the kernel, not an optional kernel plugin).

Given that `touch`-ing those files (or using the approach that the official MySQL image uses) is resolving both the issue of MySQL initializing the database during build (not desirable), and the issue of this failing, I think it's the best approach.

**Comment by ljfranklin** [comment]
Thanks @thaJeztah, switching to `overlay2` on Linux does exhibit the same issue. I'll look more into delaying the DB setup process until the container has already start like the official mysql image does.

Just one point of curiosity, when I said I touched the `/var/lib/mysql/mysql` files I didn't actually create any new files. I just changed the access time of the files that were already there. I'm not familiar with overlay file systems, but why does slightly modifying the files make them readable by the mysql process?

**Comment by thaJeztah** [comment]
>  I didn't actually create any new files

Oh, hm I see I've actually may have been misreading part of the problem; it doesn't occur at build time, but actually at runtime.

I'm not _deep_ into the technology, but what happens, is that `touch`-ing the files copies them to the writable layer. 

Looking at your example; it's really important (in general) to use a volume for paths that are written to, and data that should be persisting beyond the container's lifecycle.

The copy-on-write (CoW) / layered filesystems of containers _do_ have an overhead. For small, infrequent writes, that's not an issue, but for databases, the performance penalty (besides the side-effect as you noticed here) should not be ignored.

In this case, running

```
docker run -it -v /var/lib/mysql mysql-fails /bin/bash -c 'service mysql start'
```

probably makes it work in both `aufs` and `overlay2`. the above example uses an "anonymous" volume (which is not ideal if you want the data to persist after the container is removed), so something like below is probably more realistic;

```bash
docker volume create my-data
docker run -it -v my-data:/var/lib/mysql mysql-fails /bin/bash -c 'service mysql start'
```

Note that containers are not VM's; generally `service xx start` is not needed for containers; think of them as "sandboxed processes" instead of "VM"'s; if you look at the official image again, you'll see that after initialization is done, the `mysqld` process is started directly https://github.com/docker-library/mysql/blob/0590e4efd2b31ec794383f084d419dea9bc752c4/5.7/docker-entrypoint.sh#L203
(which makes it the container's main process).

Is there a reason you're building your own MySQL image, instead of using the official one?

**Comment by ljfranklin** [comment]
@thaJeztah yeah, my example was just a snippet from a larger image. I'm trying to build a dockerfile to run ruby unit tests in CI and those tests need a database. We're currently using the Ruby base image. Definitely agree our image is doing too much and not following best practices (e.g. multiple processes per container), but since it only runs in CI performance and persistence aren't really a factor.

Think I've got enough to give it another try. Thanks for the help!

**Comment by thaJeztah** [comment]
Great! Good luck!
