### ISSUE TITLE
Docker.service can not start

### ISSUE THREAD

**Issue by Vladyslav93** [moby/moby#34421]
---------------------------------------------------
GENERAL SUPPORT INFORMATION
---------------------------------------------------
Hello, everyone. I got the problem with docker. I am using:
docker --version: Docker version 17.06.0-ce, build 02c1d87
uname -a: Linux var-som-mx7 4.1.15-224575-g0cefc03-dirty #1 SMP PREEMPT Wed Jul 19 12:49:01 CEST 2017 armv7l GNU/Linux

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

When I wanna start service docker, I got the error:

`â— docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled)
   Active: failed (Result: start-limit) since Mon 2017-08-07 10:41:02 UTC; 3min 25s ago
     Docs: https://docs.docker.com
  Process: 1042 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 1042 (code=exited, status=1/FAILURE)

Aug 07 10:41:02 var-som-mx7 systemd[1]: Failed to start Docker Application Container Engine.
Aug 07 10:41:02 var-som-mx7 systemd[1]: Unit docker.service entered failed state.
Aug 07 10:41:02 var-som-mx7 systemd[1]: Starting Docker Application Container Engine...
Aug 07 10:41:02 var-som-mx7 systemd[1]: docker.service holdoff time over, scheduling restart.
Aug 07 10:41:02 var-som-mx7 systemd[1]: Stopping Docker Application Container Engine...
Aug 07 10:41:02 var-som-mx7 systemd[1]: Starting Docker Application Container Engine...
Aug 07 10:41:02 var-som-mx7 systemd[1]: docker.service start request repeated too quickly, refusing to start.
Aug 07 10:41:02 var-som-mx7 systemd[1]: Failed to start Docker Application Container Engine.
Aug 07 10:41:02 var-som-mx7 systemd[1]: Unit docker.service entered failed state.`

The main error as I think that it is: dockerd[483]: Error starting daemon: Devices cgroup isn't mounte

Is someone have the same? PLease help me.

**Comment by thaJeztah** [comment]
From the information you provided you're running docker on an arm platform (`armv7l`) and a custom kernel `4.1.15-224575-g0cefc03-dirty`; make sure to verify you installed a package that matches your architecture.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is a support question, but feel free to continue the conversation
