### ISSUE TITLE
Documentation/Howto build and use built artefacts

### ISSUE THREAD

**Issue by anhilde** [moby/moby#34431]
Hi,

where is the explanation how to deal with this source tree? If I run make, I see at the end of the log:

---> Making bundle: binary (in bundles/1.12.6/binary)
Building: bundles/1.12.6/binary-client/docker-1.12.6
Created binary: bundles/1.12.6/binary-client/docker-1.12.6
Building: bundles/1.12.6/binary-daemon/dockerd-1.12.6
Created binary: bundles/1.12.6/binary-daemon/dockerd-1.12.6
Building: bundles/1.12.6/binary-daemon/docker-proxy-1.12.6
Created binary: bundles/1.12.6/binary-daemon/docker-proxy-1.12.6
Copying nested executables into bundles/1.12.6/binary-daemon

Where are the build results located? I cannot find them in the source tree under bundles nor is there a container which contains them. I also fail to find any documentation how to modify/build/test/run changes. Can you point me in the right direction for this information? I also checked the moby homepage without any success. Maybe adding the needed link to the readme would be good to avoid such questions on here.

Thanks and best Regards,

André

**Comment by anhilde** [comment]
Hi,

I meanwhile found what I need here: https://docs.docker.com/opensource/project/set-up-dev-env/
It would be good to have that linked in the readme I guess, but perhaps others have an easier time finding this information then me.

Best Regards,

André

**Comment by thaJeztah** [comment]
Thanks for reporting, and sorry to hear you had trouble finding that documentation. The contributing guide is actually linked from [`CONTRIBUTING.md`](https://github.com/moby/moby/blob/master/CONTRIBUTING.md), which I think is the correct location for this. Additional changes due to the introduction of the Moby project are tracked through https://github.com/moby/moby/issues/32863 

I'm closing this issue, because of the above, but feel free to continue the conversation 👍
