### ISSUE TITLE
Passing ContainerIDFile parameter in ContainerCreate hostconfig its not writing container id.

### ISSUE THREAD

**Issue by rajksbth** [moby/moby#34436]
While passing `ContainerIDFile` in `ContainerCreate hostconfig` option its not writing container id to the given path. Docker inspect also showing the ContainerIDFile parameter.

I am passing the same as below.
`ContainerIDFile: "/tmp/controller.cid"`

**Comment by cpuguy83** [comment]
Can you please provide all the details requested by the issue template?

**Comment by thaJeztah** [comment]
The containerid file is a client-side feature; see https://github.com/docker/cli/blob/d844c487d4092b0803d8753441ffb8dbc7b731a0/cli/command/container/create.go#L161-L168

I'm not sure why it's included in the API as well, possibly to allow inspecting the container and know where to find the file that was written (I'd be in favor of deprecating that field).

Closing this issue, because I don't think there's a bug, but comment if I misunderstood or if you need more information
