### ISSUE TITLE
`docker build --cgroup-parent=/foo` doesn't work

### ISSUE THREAD

**Issue by colinfang** [moby/moby#34469]
Docker version 17.05

`--cgroup-parent` only works in `docker run`, not in `docker build`

My dockerfile

```
FROM ubuntu:16.04`
```

```bash
docker build -t my_test --cgroup-parent=/foo
docker run -it my_test cat /proc/self/cgroup

...
2:memory:/docker/f0d6c251b55ac04d5f83473d93d4fb1184c94894f133f7568a8b9657adeaf413
1:name=systemd:/docker/f0d6c251b55ac04d5f83473d93d4fb1184c94894f133f7568a8b9657adeaf413
```

```bash
docker run -it --cgroup-parent=/bar my_test cat /proc/self/cgroup
...
2:memory:/bar/bc2132fec04b3968deb6360f65e8867c25c58a6abdfc7e648f7f2898363fd436
1:name=systemd:/bar/bc2132fec04b3968deb6360f65e8867c25c58a6abdfc7e648f7f2898363fd436
```

**Comment by thaJeztah** [comment]
The `--cgroup-parent` is used _during_ build, not something that's preserved in the image. `--cgroup-parent` is a _runtime_ option. When building an image, each `RUN` instruction is executed in  a temporary container, and the result committed to an image.

When you specify `--cgroup-parent` on build, that option is used for the temporary containers used to execute the `RUN` instruction.

I don't see there's a bug at hand here, so I'll go ahead and close this issue, but feel free to continue the conversation in case I misunderstood your report

**Comment by joeynovak** [comment]
I think the problem here is the help documentation.  Currently it says:

"--cgroup-parent string    Optional parent cgroup for the container" . 

I had the same problem as colinfang.  I'm a total noob to docker, and assumed this meant that the image would have this preserved.  Can it be changed to:

"--cgroup-parent string    Optional parent cgroup for the build container" . 
or
"--cgroup-parent string    Optional parent cgroup for the build" . 

This would also give us noobs some context that a build happens inside a container (I didn't know until reading this issue).

Thanks!
