### ISSUE TITLE
Using --mount instead of -v complains about invalid characters in local volume name

### ISSUE THREAD

**Issue by martinmine** [moby/moby#34532]
**Description**
Following the documentation on using [binded volumes](https://docs.docker.com/engine/admin/volumes/bind-mounts/#start-a-container-with-a-bind-mount), using --mount instead of -v does not allow / in the source path and gives me the error: 
```
docker: Error response from daemon: create /home/martinmine/Documents/target: "/home/martinmine/Documents/target" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
```
Running  `docker run -d -it --name devtest -v $(pwd)/target:/app nginx:latest` works fine and mounts the `target` directory just find. However, running `docker run -d -it --name devtest --mount source=$(pwd)/target,target=/app nginx:latest` gives me the error above.

**Steps to reproduce the issue:**
1. `mkdir target`
2. `docker run -d -it --name devtest --mount source=$(pwd)/target,target=/app nginx:lates`

**Describe the results you received:**

See error message above.

**Describe the results you expected:**

I expect the same behavior as with the -v option, [as the documentation states](https://docs.docker.com/engine/admin/volumes/bind-mounts/#start-a-container-with-a-bind-mount).

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 17.05.0-ce, build 89658be
```

**Output of `docker info`:**

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 22
Server Version: 17.05.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.10.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 28.6GiB
Name: xxxxxxxxxxx
ID: 6OYY:KN5X:OBD3:SOUB:7CXB:5RL4:XUOZ:7ZEJ:CIOB:U6ZZ:PLYF:6P2X
Docker Root Dir: /mnt/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Happens on both a virtual machine through Openstack (CentOS7), and on my laptop (Fedora).

**Comment by thaJeztah** [comment]
Thanks for reporting; I see there is an option missing in the examples in the documentation.

The `-v` / `--volume` flag handles both _volumes_ and _bind mounts_. In your case you're using a bind mount (you're mounting a directory from the host into the container). The `-v` flag automatically (attempts to) determine if you are trying to use a volume or a bind-mount, so this works "automatically", but the detection is quite "hit and miss", and reason for the `--mount` flag coming to existence.

To do the same with the `--mount` flag, you need to tell it if you want to use a volume or a bind-mount through the `type` option. The default is `type=volume`, and a volume's name cannot contain colons (`:`) or slashes/backslashes (which is what the error is about).

To bind-mount a directory, use `type=bind`. Your example will then look like this (wrapped for readability):

```bash
docker run -d -it \
  --name devtest \
  --mount type=bind,source=$(pwd)/target,target=/app \
  nginx:latest
```

One thing to be aware of is that unlike the `-v` flag, the `--mount` flag will not automatically create the path on the host if it doesn't exist, so the following produces an error if "some-non-existing-directory" does not exist:

```
--mount type=bind,source=C:\some-non-existing-directory,target=/app
```

Not creating the host path is by design; the auto-creation of host paths is reason for a lot of "bug" reports, because when docker create's the path if it's missing, it won't know if you intended to bind-mount a _directory_ or a _file_. If you intended a _file_, and the file does not exist on the host, docker would create a directory, which would result in an error. Take the following example;

```
-v /my-configuration-file.ini:/app/config.ini
```

If `my-configuration-file.ini` does not exist, docker creates a _directory_ named  "my-configuration-file.ini". This may look like an obvious mistake (as "human"), but from a "technical" perspective, there's no way to determine what the user's intent was. To remove the "guessing", the `--mount` flag is more strict, and requires you to create the file (or directory) on the host before being able to mount it.


Thanks again for reporting. I'm working on a pull request right now to fix the documentation 👍

**Comment by thaJeztah** [comment]
Opened a pull request; https://github.com/docker/docker.github.io/pull/4217

**Comment by martinmine** [comment]
Thanks a lot @thaJeztah!
