### ISSUE TITLE
docker: Error response from daemon: failed to create endpoint postgres on network bridge: failed to add the host (veth4ea851e) <=> sandbox (vethcd53b3f) pair interfaces: operation not supported.

### ISSUE THREAD

**Issue by esatterwhite** [moby/moby#34575]
Containers - new or existing crash immediately 
docker: Error response from daemon: failed to create endpoint postgres on network bridge: failed to add the host (vethc285ba8) <=> sandbox (veth9156c12) pair interfaces: operation not supported.

**Steps to reproduce the issue:**
```
docker run -d --name=postgres -e POSTGRES_PASSWORD=abc123 -e POSTGRES_USER=esatterwhite -e POSTGRES_DB=allstar postgres:9.6
```

The same error occurs for any image. It is also happening for previously created containers prior to updating from `17.0.5`

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   3dfb8343
 Built:        Wed Jul 26 18:03:33 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87617
 Built:        Wed Jul 26 20:03:39 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.40-1-MANJARO
Operating System: Manjaro Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 31.43GiB
Name: cyclops
ID: ABFE:3ELS:HKMU:ZCY6:FKNK:NKGG:X6UA:6YBK:QK7I:2WFC:WFYB:4D37
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
 - virtual box 5.126
- Linux 4.9.40-1-MANJARO(ARCH) #1 SMP PREEMPT Fri Jul 28 09:24:52 UTC 2017 x86_64 GNU/Linux

**Comment by esatterwhite** [comment]
to be clear, docker is unusable in this state. I can not create a new container.
I tried uninstalling / reinstalling docker. Still get this error and still can't use docker.

**Comment by cpuguy83** [comment]
> operation not supported

This error message is coming from the kernel.
It seems like the kernel may be misconfigured.
Did something else other than just docker change when upgrading?
Can you enable debug logging on the daemon and track the full log that leads to this?

Note that Manjaro (and it's parent Arch) are not supported distros either.

**Comment by esatterwhite** [comment]
Just needed a reboot.

**Comment by beac0n** [comment]
> Just needed a reboot.

And how can I fix this without reboot?

**Comment by 123leechm** [comment]
> > Just needed a reboot.
> 
> And how can I fix this without reboot?

Maybe use check-config.sh to check kernel
https://github.com/coreos/docker/blob/master/contrib/check-config.sh

**Comment by adamacosta** [comment]
For the next person this happens to, it's because Arch (and downstream variants) deletes the old kernel on disk whenever it ugprades. The kernel in memory can still do a lot, but any operation that requires loading a module that isn't already loaded won't work because the paths on disk will have changed. It's a good idea to reboot immediately any time the kernel is upgraded, but pacman won't do that for you automatically. See https://bbs.archlinux.org/viewtopic.php?id=141095. This has nothing to do with Docker. It's just a difference between Arch and distros like the Debian variants more designed for long-term continuous running without reboots that keep old kernels around so you can keep using them even after installing a new one.

**Comment by AbdeltwabMF** [comment]
For me, I figured out it was because of some kernel updates.

**Comment by grandchild** [comment]
If you really can't reboot, then on Arch you can downgrade to the running kernel package (assuming you haven't cleared your caches yet) with:

```
sudo pacman -U /var/cache/pacman/pkg/linux-{,headers-}$(uname -r | sed s/-/./)-x86_64.pkg.tar.zst
```
Beware that this may not be the exact commandline for you, since you may have:
- a different kernel package in use
- a different architecture (i.e. not `x86_64`)
- `sed` not installed
- additional packages that depend on the linux kernel package version (most notably graphics drivers).

Caveat fabricator!

**Comment by djokhar05** [comment]
I just needed a reboot on my end
