### ISSUE TITLE
Ubuntu artful is not a valid repository

### ISSUE THREAD

**Issue by Qix-** [moby/moby#34577]
Trying to install `docker-ce`, I added the repository and tried to update:

```console
$ sudo add-apt-repository \
  "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) \
  stable"

$ sudo apt update
Hit:1 http://us.archive.ubuntu.com/ubuntu artful InRelease
Ign:2 https://download.docker.com/linux/ubuntu artful InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu artful-updates InRelease
Hit:4 http://security.ubuntu.com/ubuntu artful-security InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu artful-backports InRelease
Err:6 https://download.docker.com/linux/ubuntu artful Release
  404  Not Found [IP: 54.192.143.94 443]
Reading package lists... Done
E: The repository 'https://download.docker.com/linux/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Upon visiting https://download.docker.com/linux/ubuntu/dists/, it doesn't appear `artful` has any releases yet.

Is there an ETA on this? Am I safe to use old repositories?

**Comment by Qix-** [comment]
FWIW temporary workaround is to downgrade the repository to `zesty` (`sudo vim /etc/apt/sources.list`). Binaries appear to work just fine, but I'd rather not do this.

**Comment by cpuguy83** [comment]
We don't typically support new releases until they are final, and after we release a new major version (ie, non-patch release).
However with all the packaging changes with docker-ce I'm not sure if there's some new policy to how this is handled. Notably, we need an official `artful` ubuntu docker image to build from.

Since this isn't really a moby/moby issue, but rather a Docker for Linux I'm going to close this and request that you file an issue on github.com/docker/for-linux.

Thanks!
