### ISSUE TITLE
Builder complains that "COPY requires at least two arguments" when two technically exists with the --from flag

### ISSUE THREAD

**Issue by rcjsuen** [moby/moby#34598]
**Description**
The Docker builder will complain that `COPY` needs two arguments even though two has been specified. This can be reproduced by using the `--from` multi-stage build flag along with a source folder.

**Steps to reproduce the issue:**
1. Create this Dockerfile.
```Dockerfile
FROM alpine AS test
FROM scratch
COPY --from=test .
```
2. Build the Dockerfile.
```
$ docker build .
```

**Describe the results you received:**
```
$ docker build .
Sending build context to Docker daemon  86.15MB
Step 1/3 : FROM alpine AS test
latest: Pulling from library/alpine
88286f41530e: Pull complete
Digest: sha256:1072e499f3f655a032e88542330cf75b02e7bdf673278f701d7ba61629ee3ebe
Status: Downloaded newer image for alpine:latest
 ---> 7328f6f8b418
Step 2/3 : FROM scratch
 --->
Step 3/3 : COPY --from=test .
COPY requires at least two arguments
```

**Describe the results you expected:**
Perhaps a less misleading error message given that I technically do indeed have two arguments to my `COPY` instruction.

**Output of `docker version`:**
Tested in a PWD instance.
```
$ docker version
Client:
 Version:      17.06.1-ce-rc1
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   77b4dce
 Built:        Fri Jul 14 07:32:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce-rc1
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   77b4dce
 Built:        Fri Jul 14 07:33:35 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.06.1-ce-rc1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1031-aws
Operating System: Alpine Linux v3.6 (containerized)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 60GiB
Name: node1
ID: XJLX:XIAU:L3DM:S62V:WEPY:562P:G6FW:XH54:QSON:SSL5:WVFC:PMQV
Docker Root Dir: /graph
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 26
 System Time: 2017-08-22T19:12:54.4959394Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.1
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by cpuguy83** [comment]
Do you have a better suggestion for the wording?

**Comment by tonistiigi** [comment]
This is the same message that cli gives. A flag is not an argument.

```
 # docker run --name=foo
"docker run" requires at least 1 argument(s).
```

**Comment by rcjsuen** [comment]
> Do you have a better suggestion for the wording?

You could perhaps say something like "COPY requires both a source and a destination".

> A flag is not an argument.

Yes, I assumed that was the case but thought I'd ask anyway. I'm okay with closing this if the Moby team doesn't consider this a big deal.

**Comment by dm17** [comment]
I'm hitting this issue for multistage builds...
@tonistiigi I see you also wrote an article related to multistage builds for Docker... I don't understand how COPY is supposed to work for multistage - and the docker docs aren't helping. 

I have a Dockerfile like the following:
COPY --from=nodebaseimg src dest
CMD npm run build

What is src and dest in this case... COPY should just be copying the work done in Dockerfile-nodebaseimg. I want to do this because nodebaseimg is common for many of my Dockerfiles, so I figured it should be its own stage - and each Dockerfile just copies the base image, then the latest code. 

To ask the question more clearly: in the case that you're using multistage ( and then COPY --from= ), what should be copied from src to dest. What is the path of the src and what is the path of the dest?

Thanks a bunch!

**Comment by thaJeztah** [comment]
@dm17 `src` is the directory or file you want to copy from the `--from` stage (or image). For example, `src` directory could be an `output` directory, in which the stage has written a compiled binary.

If you want multiple stages to be based on the same base stage, there's no need to use the `COPY --from`, but instead use that stage as `FROM` for those.


```Dockerfile
FROM node AS nodebaseimg
RUN echo "do some steps that are common between stages"
RUN echo "do some more common steps"


FROM nodebaseimg AS stage-foo
RUN echo "do things for stage-foo"

FROM nodebaseimg AS stage-bar
RUN echo "do things for stage-bar"
```

**Comment by dm17** [comment]
@thaJeztah Thank you; very helpful. Still having some unexpected trouble that wasn't there when I had one stage and one Dockerfile. Now I have 2 stages and 2 Dockerfiles (because stage2 is common for many). It seems that node_modules doesn't exist for stage2 or something? Maybe this is obvious to you:

Stage1 Dockerfile:
FROM node:10.16.0-alpine AS nodebaseimg
WORKDIR /nodebaseimg
COPY package.json /nodebaseimg
RUN apk --no-cache --update --virtual build-dependencies add \
    python \
    make \
    g++ \
    && npm install \
    && apk del build-dependencies

So I build that, then I build this:
Stage2 Dockerfile:
FROM nodebaseimg:latest AS stage2-app
COPY . /nodebaseimg
CMD npm run build && npm run dev 

Then I'm getting file not found errors when I start containers (like "Local package.json exists, but node_modules missing")... But the single stage Dockerfile did the same thing, so I don't understand why yet...
