### ISSUE TITLE
LCOW: Design and direction, API & CLI changes discussion

### ISSUE THREAD

**Issue by lowenna** [moby/moby#34617]
This replaces https://github.com/moby/moby/issues/33854 as a discussion doc about the final design of Linux Containers on Windows (LCOW). Specifically it refers to design changes concerning:

- Daemon stores (and re-coalescing tag and image stores) 
- API and CLI changes
- The definition of "Platform"
- Dockerfile FROM statement
- Roadmap to full multi-arch support (out of scope of LCOW, but taking acount of)
- Optional improvements

The doc is at https://docs.google.com/document/d/1XTnznDI6ArLlRAUaGbXXD9BjR_6zSfOPCVJPQ-2osVc/edit#. Please add your comments to the doc for discussion, and LGTM (or not) below after review :)

The document is based on conversations at Docker Inc in SF on 8/16 and 8/17 where this was thrashed out between myself, @jstarks, @patricklang @darrenstahlmsft, @tonistiigi, @dmcgowan, @johnstep, @mlaventure, @stevvooe, @vieux, @friism and others, and ensuring it aligns to containerd. Now opening up for wider community discussion.

FYI to @thaJeztah, @crosbymichael, @simonferquel, @dnephin.

**Comment by dnephin** [comment]
Thanks, this SGTM. A couple comments and a question:

This is more about implementation, but I'd like to see the following

1. `Platform` should be a type not a string (as it's implemented now). The API parameter should be validated immediately after it's read from the http request and if valid converted into a `Platform` type. Everything that accepts a platform argument should accept the `Platform` type and can safely assumes it's been validated, and contains a non-zero value (the default value has already been applied). 

2. The CLI should hide the `--platform` flag when it's connecting to any daemon that doesn't support multi-platform. This is similar to how we handle experimental features, and features that exist in a newer version of the API (API downgrading).  The daemon should return a `Is-Multi-Platform` header on `_ping` so the cli can hide these flags.

Something that is not covered by the doc. On build, what happens if both a `FROM --platform` and a platform API param are used? Does the API param override the from platform?

**Comment by jhowardmsft** [comment]
@dnephin Thanks for reviewing. Yes, that's fine for implementation. 

For your question, on build, the explicit dockerfile `FROM` is the master. The API parameter is only used when `FROM` isn't explicit. I *think* we need it to be that way around.

**Comment by mlaventure** [comment]
SGTM too.

- I agree with @dnephin, I'd rather `Platform` be passed as part of the structured data sent to the endpoint than as a string in the url's query.
- I agree with @jhowardmsft that the `--platform` in the `Dockerfile` should have precedence over the one passed by the `API`. For multiple stage build where not all `FROM` have a platform, maybe the builder should error out, but that's out of scope for LCOW.

Thanks for writing the doc!

**Comment by jhowardmsft** [comment]
@dnephin - for the "Is-Multi-Platform" part, PTAL at https://github.com/Microsoft/docker/commit/40ca3781f995a8f1374159ef0a5714b58e9e4f1d. I haven't put a PR in yet. I think it would be more flexible if the daemon returned a list of supported platforms - that allows a client to determine whether there's multi-platform support or not as a little more generic. WDYT?

To my knowledge, there's not really a structured HTTP header, but it looks like a comma-separated list is the most common way of returning multiple values in a string.

**Comment by jhowardmsft** [comment]
@dnephin. Cool, thanks. I'll put a PR in shortly.

**Comment by jhowardmsft** [comment]
@mlaventure @dnephin 

> Platform should be a type not a string (as it's implemented now). The API parameter should be validated immediately after it's read from the http request and if valid converted into a Platform type. Everything that accepts a platform argument should accept the Platform type and can safely assumes it's been validated, and contains a non-zero value (the default value has already been applied).

> I agree with @dnephin, I'd rather Platform be passed as part of the structured data sent to the endpoint than as a string in the url's query.

I've added a comment to the doc to this effect, but not done the full set of updates to it yet. I propose we use an HTTP header `X-Requested-Platform` which is an optional JSON encoded structure from the OCI image-spec `Platform` in the API - https://github.com/opencontainers/image-spec/blob/master/specs-go/v1/descriptor.go#L45-L64

**Comment by jhowardmsft** [comment]
> I agree with @jhowardmsft that the --platform in the Dockerfile should have precedence over the one passed by the API. For multiple stage build where not all FROM have a platform, maybe the builder should error out, but that's out of scope for LCOW.

Doc updated to reflect this.
