### ISSUE TITLE
Docker-compose to offer stack-global environment variables

### ISSUE THREAD

**Issue by 1605200517** [moby/moby#34631]
This is a feature request.

Enable per-stack global environment variables to be injected to all containers of a stack.
Example: DNS hosts e.g. proxy or name of a specific environment.

**Comment by cpuguy83** [comment]
I think this would be solved quite nicely by https://github.com/docker/cli/pull/452
Rather than setting some global value, you can use yaml anchors to define common objects to inject in at various points.

In any case, I'm going to close this here because moby/moby doesn't deal with `stack` at all. This is all handled in the CLI.
