### ISSUE TITLE
Add Quota Support to VFS Driver

### ISSUE THREAD

**Issue by sargun** [moby/moby#34702]
**Description**
Before I go about implementing anything, I'd like to get some folks opinion on how to implement VFS Driver improvements. The following two issues frustrate me:

1. The VFS driver does not support filesystem quota
2. The VFS driver does a naive copy, which doesn't take advantage of techniques like zero-copy, and reflinks. 

As a solution, I propose the following:

- [ ] We adopt the techniques that I've added to the overlay driver in https://github.com/moby/moby/pull/34670. This gracefully degrades, and allows the user to take advantage of reflinks (FICLONE), zerocopy (copy_file_range / splice), and then only falls back to a naive copy. Although there is still an O(N) cost for layer setup in the ideal case, N for the number of files is likely not a great number. Naive tests show that copying ubuntu:latest using these techniques can be done in 600 milliseconds.
- [ ] We adopt the projectquota code, after the improvements laid out in https://github.com/moby/moby/issues/34701

Agree? Disagree?
CC: @cpuguy83 @dmcgowan

**Comment by dmcgowan** [comment]
I agree with making improvements to VFS to take advantage of cloning, we have already done this in the containerd naive driver. I still found that benchmarks showed the naive approach is very slow, additionally it still has issues related to inode usage even if the space is more efficient.

As for quotas, this is tricky as the quota should only apply to the writable container filesystem. Since VFS copies the entire content of an image into the container's writable filesystem, you either have to bump the quota to account for this or risk filling up your quota just from the image content. In the first case the quota is not really being respected as running a larger image would give the container more quota, and the second is not reasonable. Is there a median here that could make quota on VFS more usable? Also make sure that any new development work done here is considered for containerd, which will eventually deprecate the graph drivers.

**Comment by sargun** [comment]
I agree, that the quota should only apply to the writeable layer. This also means that the dstDir needs to be marked with a given project ID before the VFS driver starts to explode files into that directory. I think that project maintenance can be generalized across overlay, overlay2, and VFS with project quotas, by simply marking, and maintaining the R/W layer. I think the graph driver should be responsible to abstract the underlying quota implementation.

As far as contributing this to containerd -- I think that's a really good idea, as I can see myself using containerd shortly. I'd prefer if containerd and CRI-O were able to work with a common layer for storage like containers/image, or containers/storage, but I understand that there are concerns about the libraries being too tightly coupled.

You're right, the current VFS driver is very slow. Using splice (copy_file_range on ext4) is faster by anywhere from 5-30% (typically leaning closer to 5), but it's still pretty terrible. At least the testing I've done with XFS + reflink=1 has shown a lot of promise. I've done a test that takes about 600 milliseconds with ioclone for ubuntu:latest (think cp --reflink, but more optimized for our use case). If we keep an index, we can do a bread-first traversal, and get even faster than that. 

If we assume that everyone is eventually moving to a CoW based world (ZFS, XFS BtrFS), with "standard" APIs, I think the VFS approach has real promise. 

I think it's best we include the image in the quota, as that's what happens today with our underlying implementation, and it seems to be more pessimistic. That way we don't have to do the fiemap dance to determine whether or not the underlying filesystem is sharing extents. I also believe that the quota should be set _after_ extraction, and not prior.

**Comment by thaJeztah** [comment]
Looks like this was implemented in https://github.com/moby/moby/pull/35231
