### ISSUE TITLE
Add option to specify a port for containers being waited on

### ISSUE THREAD

**Issue by garvincasimir** [moby/moby#34733]
In my own containers and others I have seen that rely on a db/backend container in compose, we specify depends_on to wait till that container is started before our app container starts. As is stated in the documentation, docker does not wait for the container to initialize to move to the next dependency. I propose taking things a step further by adding the ability to wait for a specified port to open on the db/backend service before starting the app container which specifies depends_on.

Take my compose file for example: https://github.com/garvincasimir/csharp-datatables-parser/blob/master/docker-compose-test.yaml.

I would add ports 1433 and 3306 to the depends_on config so docker can do what this file is doing:
https://github.com/garvincasimir/csharp-datatables-parser/blob/master/test/DatatablesParser.Tests/test-runner.sh

If this functionality existed, my Entrypoint would simply be *dotnet test* and there would be no need for a shell script.
https://github.com/garvincasimir/csharp-datatables-parser/blob/master/Dockerfile-test

I originally created this issue in the [Compose repo](https://github.com/docker/compose/issues/5121#issuecomment-327287878) but was asked to created it here.

**Comment by thaJeztah** [comment]
Just checking for a port to be available is in many cases insufficient (the port may be up, but the database may not be ready to accept connections, e.g., it may be busy initialising the database on first run).

Because there is no generic way to check for this (what is "ready" differs for each use case), the `HEALTHCHECK` feature was implemented; see https://docs.docker.com/compose/compose-file/#healthcheck

However; only checking if a connection is available on _deploying_ your stack is just _part_ of the problem: services can be unavailable at any point of your stack's lifecycle (servers can go down, databases can fail, networks can fail due to external factors). For that reason, your application should be designed to be resilient against failures; if a dependency is not available, the application should take action (retry the connection, or any action that's required).

The `depends_on` option is not supported for Swarm services (`docker stack deploy`); partly because of the above (i.e., dependency checking is not only a thing to take into account when deploying a stack, but also after that), but also because it doesn't scale: it's possible there's a complex dependency graph between services; attempting to take that graph into account in a big deployment just doesn't scale.

There is an existing discussion on this topic here: https://github.com/moby/moby/issues/31333. To prevent the discussion from diverging, I'm closing this issue; feel free to participate in the issue I linked to 👍
