### ISSUE TITLE
Error response from daemon: removal of container f3ceb7dee8a6 is already in progress

### ISSUE THREAD

**Issue by ZhiqinYang** [moby/moby#34877]
docker version:
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:36:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.13.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:36:45 2017
 OS/Arch:      linux/amd64
 Experimental: false

how can I solve this problem! 
I run docker rm it says: 
Error response from daemon: removal of container f3ceb7dee8a6 is already in progress

i run cadvisor  in dockers ! then when i found it's used 10G mem, i delete it with k8s cmd ,then i can't rm it

**Comment by thaJeztah** [comment]
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is a support request, but feel free to continue the conversation 👍
