### ISSUE TITLE
No up to date release of moby on github

### ISSUE THREAD

**Issue by platy** [moby/moby#34940]
[Docker CE release notes](https://docs.docker.com/release-notes/docker-ce/) list **17.07-ce** as the latest version 
[The VERSION file in the moby repo in master](https://github.com/moby/moby/blob/master/VERSION) has the version currently as only **17.06.0-dev** 
[The largest tag / release semantically in github](https://github.com/moby/moby/releases
) is **v17.05.0-ce**

Was it forgotten to tag the last 2 versions? 17.07 includes API changes - and to use them in the go client we need a tag in github.

**Comment by thaJeztah** [comment]
This repository is for the Moby core ("engine"), which is one of the components used in Docker. This repository currently does not do releases, but if you're looking for the Docker CE releases, you can find those now in the https://github.com/docker/docker-ce repository, where you'll find the tags associated with the releases; https://github.com/docker/docker-ce/releases

I'm closing this issue, because I think this answers your question, but feel free to continue the conversation

**Comment by platy** [comment]
Ok, thanks for the quick response. 
Is that the repository we should be using for the docker sdk in golang?

Where we currently do:
```
import "github.com/docker/docker/api/types"
```
We should change to:
```
import "github.com/docker/docker-ce/components/engine/api/types"
```

**Comment by thaJeztah** [comment]
That's currently a bit complicated, and is being worked on; you can find more information on that in this issue; https://github.com/moby/moby/issues/33989

**Comment by platy** [comment]
Thank you for the direction
