### ISSUE TITLE
docker build limit io disk

### ISSUE THREAD

**Issue by sztwiorok** [moby/moby#35012]
Would there be any way to limit the disk IO for `docker build` ?
Something like we have in `docker run`

```
--device-read-bps Limit read rate from a device 
--device-write-bps Limit write rate to a device
--device-read-iops Limit read rate (IO per second) to a device  
--device-write-iops	Limit write rate (IO per second) to a device 
```

**Comment by thaJeztah** [comment]
Limiting disk i/o is not currently supported on `docker build`. Could you describe your use-case a bit more?

In general (not just for build), I wonder if a more generic "limit" option is possible; w.r.t. the `--device-*` options are not really portable because they apply to a specific device (which may differ from host to host), and including the Windows variations for this (`--io-maxbandwidth`, `--io-maxiops`), there are now _six_ possible options to configure.

**Comment by terasa** [comment]
We have lots of heavy builds at the same time on one server, we want to limit every build to eliminate situations where one docker build consumes all resources

there are limits for CPU and Memory but we can't limit disk IO right now

**Comment by sztwiorok** [comment]
We have lots of heavy builds at the same time on one server, we want to limit every build to eliminate situations where one docker build consumes all resources

there are limits for CPU and Memory but we can't limit disk IO right now

**Comment by y2kpr** [comment]
Hi there, I am planning to work on this issue. I am a computer science student at UT Austin and I am working on this as part of my final project for a class. I will be working with a teammate (@bealerj2260) on this and we have about a month to work on this. 

I have never contributed to the moby repo but I get a basic sense of what needs to get done for this issue. I will look into how to limit disk I/O in a more generic way as @thaJeztah mentioned and propose what we will do within a week.

Since I am a newbie to this repo, I would appreciate any guidance on the best way to approach this.

**Comment by thaJeztah** [comment]
@y2kpr given that this is builder related, you may want to reach out to @tonistiigi to discuss this option.  If you haven't done so yet, I recommend joining the docker community slack, where you can find most maintainers (theres a `#moby-project` channel there

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
