### ISSUE TITLE
macOS Containers Disk space does not decrease

### ISSUE THREAD

**Issue by loretoparisi** [moby/moby#35020]
The docker disk does not get reduced when deleting old images.
Before and after removing tens of images, the docker container file size is stuck to
```
 62G	./com.docker.driver.amd64-linux
```

I have tried `docker system prune -a` but it did not worked so I manually had to

```
rm -rf ~/Library/Containers/com.docker.docker/Data/*
```

This issue is referenced in https://github.com/docker/for-mac/issues/371#issuecomment-248404423.

**Comment by thaJeztah** [comment]
This is a docker for mac issue due to the way sparse files work on macOS; improvements were made to periodically shrink the file when space is cleaned up inside the image, but cleanup is not instantly (which is what you may be seeing).

See https://github.com/docker/for-mac/issues/371#issuecomment-249533736, https://github.com/docker/for-mac/issues/371#issuecomment-315385246

This repository is for the "engine" running inside Docker for Mac, and the code responsible for the docker disk used in Docker for Mac is not maintained here, so I'm closing this issue because there's nothing that can be done in this repository

**Comment by loretoparisi** [comment]
@thaJeztah thanks it makes sense.
