### ISSUE TITLE
Daemon config reloading fails and recovers without config file

### ISSUE THREAD

**Issue by dsheets** [moby/moby#35114]
**Description**

When one sends `SIGHUP` to `dockerd` and the daemon's config file (usually `/etc/docker/daemon.json`) does not exist, an error is emitted to the logs and the reload does not occur.

**Steps to reproduce the issue:**
1. Start `dockerd` without a config file (config 0)
2. Create `/etc/docker/daemon.json` and populate it with some new configuration
3. Send `SIGHUP` to `dockerd` and notice the new configuration is picked up (config 1)
4. Delete `/etc/docker/daemon.json`
5. Send `SIGHUP` to `dockerd` and notice that the configuration does not change (config 1)

**Describe the results you received:**

Missing config file is allowed when starting daemon but not when reloading configuration.

**Describe the results you expected:**

Missing config file is allowed when starting daemon and when reloading configuration.

Edit: occurs in Docker 17.06, Docker 17.09, etc.

**Comment by ripcurld0** [comment]
calling #dib

**Comment by ripcurld0** [comment]
So you prefer it to be a warning and not an error?

**Comment by thaJeztah** [comment]
I noticed a while back that it always prints a warning if no daemon.json was found; there's no reason to print a warning (or error) of the file is not there, because the configuration file is fully optional.

Refusing to reload the configuration is a bug that should be fixed.

One case that we may want to consider errorkng for is  if a custom configuration file is specified, and not found (`--config-file=/foo/bar.json`). In that case, the user explicitly asked for that file to be loaded, and failing to load it is (IMO) an error.
