### ISSUE TITLE
Docker Top --format '{{json .}}' ?

### ISSUE THREAD

**Issue by muhahacz** [moby/moby#35137]
Is possible to implement json output to Docker Top command? 
P.S. I know about http:/localhost/containers/${container_id}/top API endpoint
Thanks

**Comment by thaJeztah** [comment]
The `docker top` command is quite a legacy command; basically, the command shells out to the `ps` command on the host (on Linux - the `docker top` command is not supported on Windows). As a result, the output, and possible columns returned are not well-defined. Plans are to replace this functionality with Prometheus metrics in future (see https://github.com/moby/moby/issues/27307), and development for that is ongoing in the 1.x version of the containerd project (docker currently uses the 0.2 branch of containerd)

For the reasons above, it was left out of the list in https://github.com/moby/moby/issues/30431, and there are currently no plans to add this.

I'm closing this issue because of the above, but if you feel strongly about this, and have a particular use-case that would require this feature (and cannot be solved through the API), feel free to open an issue in the https://github.com/docker/cli repository, which is where the docker cli lives (and where this   would have to be implemented)
