### ISSUE TITLE
Docker service create - "could not accessed on a registry to record its digest"

### ISSUE THREAD

**Issue by juberjj** [moby/moby#35187]
I've created a simple MongoDb image which is stored locally. I'm playing around with Docker Swarm, so when creating the service I get the following message.

> image mongodb-base:latest could not be accessed on a registry to record
> its digest. Each node will access mongodb-base:latest independently,
> possibly leading to different nodes running different
> versions of the image.
> 
> n33gb320lnowb0s9fnbsyupmi
> Since --detach=false was not specified, tasks will be created in the background.
> In a future release, --detach=false will become the default.

Even though I get the message above the service create the task and I can see the replica up and running. I don't think the message is an expected bahaviour.

When I'm spinning the same service above with --mount option as I'd like to bind it to a local folder it gives the same message including the task id but the replica never starts.

> Client:
>  Version:      17.09.0-ce
>  API version:  1.32
>  Go version:   go1.8.3
>  Git commit:   afdb6d4
>  Built:        Tue Sep 26 22:40:09 2017
>  OS/Arch:      darwin/amd64
> 
> Server:
>  Version:      17.09.0-ce
>  API version:  1.32 (minimum version 1.12)
>  Go version:   go1.8.3
>  Git commit:   afdb6d4
>  Built:        Tue Sep 26 22:45:38 2017
>  OS/Arch:      linux/amd64
>  Experimental: false
> 
>

**Comment by mikegcoleman** [comment]
On a multi-node swarm cluster you may need the same image on every node. What the message is saying is that since that image cannot be found on a registry somewhere, there is no way to reliably ensure that the image will be the same on all the nodes in your cluster. 

If you're working with a local image on a single node, it's not a big deal, and you can ignore it. 

However, if you moved into an environment where you have multiple nodes, there would be no way for Swarm to ensure the MongoDB images you created were exactly the same across all your nodes unless there was a single source of truth for those images (which would be a registry). 

I'm not sure why you're service isn't starting with the mount. Can you post your `docker service create` commands (or docker-compose files).

**Comment by juberjj** [comment]
Many thanks for the explanation @mikegcoleman it does make sense alright.

Here's the comand

docker service create --name mongodb --mount type=bind,source=/projects/docker/mongodb/data,destination=/data/db -p 27017:27017 mongodb-base

**Comment by thaJeztah** [comment]
When using swarm services, the host path you're mounting must exist before the service is created (docker doesn't create the path), so the service will fail to be deployed if the path is not existing on the node it lands on.

Using a volume instead may be a solution for production, or make sure the files are part of the image you're deploying (based on the name of the path, I assume these local source files used during development?)

**Comment by juberjj** [comment]
Hey @thaJeztah right on, the path does exists and you're also correct the source files are supposed to be shared during development phase. I'll be doing some further investigations on this. I have a different machine with Fedora as a main OS and I managed to have the tasks spun up.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
