### ISSUE TITLE
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:35914->[::1]:53: read: connection refused

### ISSUE THREAD

**Issue by dhrubajyotiborah** [moby/moby#35202]
**Description**

**Steps to reproduce the issue:**
1. docker run hellow-world
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Debian stretch,

**Comment by cpuguy83** [comment]
Please take the time to fill out the requested information.

In any case, this looks like a DNS issue on your system as docker is not able to perform the DNS lookup. Please check your DNS settings.

Closing since there is no info to go on here and is not likely to be an issue with docker itself.
In the future it may be easier to get support for issues like this on #docker on freeenode or on the community slack channel.

Thanks!
