### ISSUE TITLE
COPY fails if source not in current directory

### ISSUE THREAD

**Issue by ganeshbms** [moby/moby#35234]
Docker version: Docker version **17.09.0-ce, build afdb6d4**

Steps to reproduce:

step 1: Create a docker file with below content

                 # This is Docker file to create a hello world image

                 FROM centos:6.6
                 RUN yum -y install vim
                 RUN yum -y install java-1.8.0-openjdk
                 RUN mkdir /opt/Grizzly
                 COPY /home/ganeshbms/tomcat/apache-tomcat-8.0.33 /opt/Grizzly/
                 CMD sh /opt/Grizzly/bin/startup.sh

step 2: Try to build image using below command
             sudo docker build -t dockspace/helloworld:0.3 .
Above step fails with below error:
Sending build context to Docker daemon  47.69MB
Step 1/6 : FROM centos:6.6
 ---> 21edfae4b8fd
Step 2/6 : RUN yum -y install vim
 ---> Using cache
 ---> 0b58668ed99e
Step 3/6 : RUN yum -y install java-1.8.0-openjdk
 ---> Using cache
 ---> 4d3a251309c0
Step 4/6 : RUN mkdir /opt/Grizzly
 ---> Using cache
 ---> 9df148dbc3f6
Step 5/6 : COPY /home/ganeshbms//tomcat/apache-tomcat-8.0.33 /opt/Grizzly/
**COPY failed: stat /var/lib/docker/tmp/docker-builder708467694/home/ganeshbms/tomcat/apache-tomcat-8.0.33: no such file or directory**

Note:
1) COPY works fine if I place apache-tomcat-8.0.33 directory in the current working directory .. 
2) Raising this new issue as per the comment at #27134 .. This could be duplicate issue.

Please let me know if any further info required.

Thanks

**Comment by fntlnz** [comment]
@ganeshbms copy is relative to the contect of the build context.
When you run
```
docker build someimage:latest .
```
 the dot stands for "take everything from the current folder.
 So if you need to put something in a container with the `COPY` or `ADD` by taking it from the filesystem make sure that it's in the build context.

Be aware that this doesn't mean that you put in the build context the whole `/`, since the context needs to be sent to the docker daemon.

Read here: https://docs.docker.com/engine/reference/builder/#copy

**Comment by fntlnz** [comment]
Closing this since it's not an issue, but feel free to discuss.
