### ISSUE TITLE
Obtaining basic information about an image appears to not work on official hub.docker.com API without authorization token

### ISSUE THREAD

**Issue by JonasT** [moby/moby#35258]
According to the following section  https://docs.docker.com/registry/spec/api/#manifest , it sounds like the following URL should work:

https://hub.docker.com/v2/library/ubuntu/manifests/latest

However, this gives 404. The only obvious difference to what a browser would do is the `Authorization` header mentioned in the docs.

From this I conclude that the header appears to be mandatory for this type of request. (If this is not the case, this ticket is probably invalid)

This would very bad for testing out the basic API functionality for this in the browser, and since the information is public on the website anyway it doesn't really make much sense from a security standpoint either. If you are worried about denial of service issues, I recommend more aggressive rate limiting without an authorization header rather than blocking it entirely.

**Comment by thaJeztah** [comment]
Those docs refer to the open source registry API specs, not Docker Hub. Although docker hub uses those specs for the registry, which authentication method is used, or which endpoints require authentication can vary between implementations (such as Docker Hub);

https://docs.docker.com/registry/spec/api/#scope

> While authentication and authorization support will influence this specification, details of the protocol will be left to a future specification. Relevant header definitions and error codes are present to provide an indication of what a client may encounter.

This is really a question for Docker Hub, not the Moby project that's maintained here; you can try opening an issue in https://github.com/docker/hub-feedback, or sending an e-mail to support@docker.com 

I'll close this issue here, because of the above, but feel free to comment after that

**Comment by JonasT** [comment]
Thanks for the info! I filed a ticket here: https://github.com/docker/hub-feedback/issues/1216
