### ISSUE TITLE
Cannot get HTTP status code from docker daemon when build image

### ISSUE THREAD

**Issue by crystaldust** [moby/moby#35275]
Hi, I'm using github.com/moby/moby/client lib in my project. When I call the ImageBuild method, no error occurred but the build fails. Since the ImageBuild only returns the HTTP response body, I can't get the status when calling the method, would it be possible to return the status code for more detailed controls from the caller?
 
https://github.com/moby/moby/blob/7848b8beb9d38a98a78b75f78e05f8d2255f9dfe/client/image_build.go#L50

**Comment by thaJeztah** [comment]
If the build fails, doesn't it return an error here; https://github.com/moby/moby/blob/7848b8beb9d38a98a78b75f78e05f8d2255f9dfe/client/image_build.go#L44 ?

**Comment by ripcurld0** [comment]
@crystaldust can you provide the code and more details what you're doing: executed commands, configuration of Docker/Moby?

Thanks.

**Comment by cpuguy83** [comment]
You need to read the response body to get errors.
Example from the docker CLI:
```
	err = jsonmessage.DisplayJSONMessagesStream(response.Body, buildBuff, dockerCli.Out().FD(), dockerCli.Out().IsTerminal(), aux)
	if err != nil {
		if jerr, ok := err.(*jsonmessage.JSONError); ok {
			// If no error code is set, default to 1
			if jerr.Code == 0 {
				jerr.Code = 1
			}
			if options.quiet {
				fmt.Fprintf(dockerCli.Err(), "%s%s", progBuff, buildBuff)
			}
			return cli.StatusError{Status: jerr.Message, StatusCode: jerr.Code}
		}
		return err
	}
```

This is because the first bit of data that is sent to the client also triggers the HTTP status code.
If the server knows before it's sent any data to the client, it can set the status code, otherwise it will wind up with `200 OK`.
So instead we multiplex the build output on the response body with an error stream (for errors), an output stream (for build progress, container output, etc), and an aux stream (random other things that need to be sent).

**Comment by ripcurld0** [comment]
Closing this. @cpuguy83 answers this very well.
