### ISSUE TITLE
Service of app hangs random in swarm mode

### ISSUE THREAD

**Issue by jeeffy** [moby/moby#35339]
I use 
```
docker service create -d \
	-p 8080:8080 \
	--mount type=bind,source=/etc/localtime,target=/etc/localtime \
	--mount type=bind,source=/etc/timezone,target=/etc/timezone \
	--mount type=bind,source=/home/test/docker/manager,target=/root \
	--network test-network \
	--workdir /root \
	--name test-manager \
	--replicas 2 \
	--limit-cpu 2 \
	--limit-memory 4G \
	java:8 java -Dspring.profiles.active=$PROFILE -jar -Xms512m -Xmx4096m /root/target/test-manager.jar
```
to create a service, test service with `curl 192.168.1.47:8080/info`, sometimes, the service cannot be accessiable.
Output of docker info:
```
Containers: 4
 Running: 3
 Paused: 0
 Stopped: 1
Images: 25
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 102
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: tdc32kn0n6bwcz32ljvprcmq0
 Is Manager: true
 ClusterID: hdyakushxu1c6rsk2cml7b0l3
 Managers: 2
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 192.168.2.47
 Manager Addresses:
  192.168.2.47:2377
  192.168.2.48:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-92-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.78GiB
Name: ubuntu-qgsp01
ID: RP4U:E3PW:AU5R:BLD2:2QDL:DA25:GY2P:YV67:IR2F:GEBZ:XVX3:XC72
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://20agqwyc.mirror.aliyuncs.com/
Live Restore Enabled: false
```

**Comment by jeeffy** [comment]
Sometimes the service is accessible completely, sometimes the service is accessible about 50% rate

**Comment by thaJeztah** [comment]
There's not a lot of information to go on in your report; some things;

- Keep in mind that others don't have access to your source files (e.g. don't have access to `/home/test/docker/manager/target/test-manager.jar`)
- Is the `/home/test/docker/manager` directory present on _every_ node in your swarm? Keep in mind that mounting directories is done from the host where the daemon runs, not from your local machine
- You are running an outdated version of Docker (17.06.0-ce); try updating to a current version (17.09 or 17.10), or if you need to stay on the 17.06 release, make sure you're running the latest patch release of 17.06 (currently 17.06.2)
- Not related to this issue, but you're running in a 2-manager setup; this is highly discouraged as it _doubles_ the chance you loose quorum, and doesn't provide HA (see [Administer and maintain a swarm of Docker Engines](https://docs.docker.com/engine/swarm/admin_guide/#add-manager-nodes-for-fault-tolerance))

If 50% of the requests is not working, it's possible that overlay networking is not functional; a likely cause for this is that make sure that all required ports are open for communication between the nodes; https://docs.docker.com/engine/swarm/swarm-tutorial/#the-ip-address-of-the-manager-machine

> The following ports must be available. On some systems, these ports are open by default.
> 
> - TCP port 2377 for cluster management communications
> - TCP and UDP port 7946 for communication among nodes
> - UDP port 4789 for overlay network traffic
>
> If you are planning on creating an overlay network with encryption (`--opt encrypted`), you will also need to ensure ip `protocol 50` (ESP) traffic is allowed.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is a support question, but feel free to continue the conversation
