### ISSUE TITLE
How make docker host respond on port 5555 in docker

### ISSUE THREAD

**Issue by daixiang0** [moby/moby#35378]
I want to enable hosts setting in container but failed.
Here is my daemon.json
```
{
"hosts": ["unix:///var/run/docker.sock", "tcp://0.0.0.0:5555"],
"live-restore": true,
"insecure-registries": ["172.17.0.6:9980"]
}
```
My docker info in container as below:
```
[root@5cae7be526b4 /]# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.09.0-ce
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: CentOS Linux 7 (Core) (containerized)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 31.26GiB
Name: 5cae7be526b4
ID: N3Y4:VTIJ:WCHK:AQL3:MU3F:DNHE:BIXO:7ISI:4D4V:Q4IG:VYIT:FOH3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```
Host setting can work at host, but i do not found docs about how to enable it in container.

**Comment by thaJeztah** [comment]
This should work the same as outside a container;


```bash
$ mkdir -p /etc/docker

$ echo '{"hosts": ["unix:///var/run/docker.sock", "tcp://0.0.0.0:5555"]}' > /etc/docker/daemon.json

$ dockerd --debug
DEBU[2017-11-02T09:19:53.383759325Z] Listener created for HTTP on unix (/var/run/docker.sock)
WARN[2017-11-02T09:19:53.383973918Z] [!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]
DEBU[2017-11-02T09:19:53.384351929Z] Listener created for HTTP on tcp (0.0.0.0:5555)
INFO[2017-11-02T09:19:53.386531338Z] libcontainerd: started new docker-containerd process  pid=337
......
```

However (from your other issue ) since you are starting docker using systemd, be sure to check if the systemd unit doesn't also have a `-H` option set. Use `systemctl cat docker.service` to check the service configuration, and to check if there's already a `-H` option set.

Also, when running docker inside a container, make sure to use a volume for the docker storage directory, otherwise you won't be able to use storage-drivers other than `vfs`, which will give you very bad performance.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation
