### ISSUE TITLE
Request: Swarm Mode 17.10-ce: Cannot allocate memory

### ISSUE THREAD

**Issue by lukeescude** [moby/moby#35469]
**Description**
Periodically, a worker node will freeze up, causing all containers (and all processes, even outside of Docker, like SSH or NFS or whatever) to freeze. No data in or out of the server.

When this occurs, the Swarm Managers think the worker node is Reachable and Available, so no failover occurs, even though the containers are all frozen.

I realize this is a unique issue, with not a lot of info to go on, but it would be ideal if Docker nodes had some kind of heartbeat or something, with a new socket connection every 5 minutes or whatever, so a failover in this scenario can occur.

**Steps to reproduce the issue:**
Unknown at this point.

**Describe the results you received:**
Freeze-up of all containers and processes running in the containers, and no failover (they were not rescheduled on other worker nodes).

**Describe the results you expected:**
I would expect a service rescheduling to occur, and for Docker to mark the node as defunct.

**Additional information you deem important (e.g. issue happens only occasionally):**
Definitely happens only occasionally.

**Output of `docker version`:**

Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:04:05 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:05:38 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Output of `docker info`:**

Containers: 9
 Running: 9
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 17.10.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: azvr9pw15lmu54anqvwizin29
 Is Manager: false
 Node Address: 206.126.62.133
 Manager Addresses:
  104.225.15.205:2377
  104.225.15.206:2377
  104.225.15.207:2377
  174.138.58.217:2377
  206.126.62.146:2377
  206.126.62.162:2377
  206.126.62.168:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.51GiB
Name: dallas-worker3.primevox.net
ID: 245F:PSPE:24RH:CO57:BTYK:22U3:6B6R:OXHF:WK3A:P4LM:GCQR:566W
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CentOS x64, VMWare ESXi environment spread across 2 datacenters.

**Comment by thaJeztah** [comment]
> but it would be ideal if Docker nodes had some kind of heartbeat or something

If you look from a manager node, you'll see that there's such a mechanism;

```
Managers: 3
Nodes: 20
Orchestration:
Task History Retention Limit: 1
Raft:
Snapshot Interval: 10000
Number of Old Snapshots to Retain: 0
Heartbeat Tick: 1
Election Tick: 3
Dispatcher:
Heartbeat Period: 5 seconds
CA Configuration:
Expiry Duration: 3 months
```

- What do the daemon, and system logs show?
- What does the cluster look like when viewed from a manager?
- I see you're using a very high number of managers; be aware that more managers means lower performance (due to the raft algorithm requiring every manager to interact in decisions) if your managers are spread over datacenters, connection speed, latency, and stability of the networks between managers is especially important.

**Comment by lukeescude** [comment]
Somehow the heartbeats must still be working, even though the node is frozen.

The logs are full of the following message:
Nov 11 13:59:29 irving-worker3 dockerd: time="2017-11-11T13:59:29.831116418Z" level=warning msg="failed to retrieve docker-runc version: fork/exec /usr/bin/docker-runc: cannot allocate memory"

Manager shows that all nodes, even the affected one, is Ready and Active.

If we implemented container Health Checks, would that help with failover? I would imagine Docker would just try to spin the container back up on the exact same node, despite there being an issue with it.

Latency is less than 10ms nearly 99% of the time, which is nice.

**Comment by thaJeztah** [comment]
I see you're running the overlay storage driver; what you're seeing may be due to the host running out of inodes, which is a known side effect of the overlay driver. It can be worked around, but requires reformatting the drive (see https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/)

You can check inode usage with `df -i`

If you're running CentOS 7.4, the overlay2 storage driver is a better choice; it has the same advantages as overlay, but doesn't have the high inode usage problem.

overlay2 requires kernel 4.x, but was backported to the Red Hat/CentOS 3.10 kernels; docker won't be able to detect that, so by default overlay2 is not used on a 3.10 kernel. 

To enable overlay2 on a CentOS machine; the kernel version check must be overridden; set the storage option `overlay2.override_kernel_check`. The `daemon.json` would look something like this:

```json
{
  "storage-driver": "overlay2",
  "storage-opts": [
    "overlay2.override_kernel_check=true"
  ]
}
```

See the [daemon configuration file](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file) section in the `dockerd` CLI reference 

Before switching, you may have to cleanup the existing docker install / images / `/var/lin/docker` to free up inodes (if you're wiping `/var/lib/docker`, be sure to remove the node from the swarm, so that you can re-join the swarm later on)

**Comment by lukeescude** [comment]
Great recommendation, we will look into this ASAP.

Is it possible that a rogue process with out-of-control threads (tens of thousands of threads, infinitely increasing) could cause this type of failure? (Curiosity question).

**Comment by thaJeztah** [comment]
Yes, definitely possible

Without more inside into what you're running into the containers, and how they are configured, hard to tell though.

You can limit the number of allowed processes in the container (see https://github.com/moby/moby/pull/18697, and https://github.com/opencontainers/runc/pull/58), but the CentOS kernels are way too old for that (don't know if they attempted to backport)

**Comment by lukeescude** [comment]
Currently all of our worker nodes are functioning and using 1% inodes. We'll still move to overlay2, but I am not sure if this is actually the issue.

What OS do you recommend that is more geared towards containers/swarm? Sounds like CentOS might not be ideal.

We're running pretty intensive applications - Lots of UDP and TCP sockets being used, almost entirely network-based. No file storage, no HTTP requests, just a lot of data and streams.

**Comment by thaJeztah** [comment]
@lukeescude are you still running into this issue?

**Comment by thaJeztah** [comment]
closing, as this one went stale
