### ISSUE TITLE
Elastic Beanstalk Requires Deprecated/Hard to Find Docker Version.

### ISSUE THREAD

**Issue by patientplatypus** [moby/moby#35485]
When I try and use elastic beanstalk from the command line (ie `eb create project`) I got the following error. 

```
Select a platform version.
1) Docker 17.03.2-ce
2) Docker 1.12.6
3) Docker 1.11.2
4) Docker 1.9.1
5) Docker 1.7.1
6) Docker 1.6.2
7) Docker 1.5.0
(default is 1): 1
Note: Elastic Beanstalk now supports AWS CodeCommit; a fully-managed source control service. To learn more, see Docs: https://aws.amazon.com/codecommit/
Do you wish to continue with CodeCommit? (y/N) (default is n): n
Do you want to set up SSH for your instances?
(Y/n): y

Select a keypair.
1) patientplatypus
2) phoenixvuenewsly
3) [ Create new KeyPair ]
(default is 2): 1
patientplatypus:~/Documents/newsly_project:11:56:37$eb create newsly_project_production
ERROR: Platform Docker 17.03.2-ce does not appear to be valid
patientplatypus:~/Documents/newsly_project:11:57:44$docker --version
Docker version 17.09.0-ce, build afdb6d4
```

I thought the above seemed understandable enough, at first. I have version 17.09.0-ce of Docker, but I need version 17.03.2-ce. It would seem reasonable that AWS would be a few versions behind the latest version of Docker if nothing else than to double check system integration and security.

However, when it came time to find version 17.03.2-ce I found it almost impossible. https://github.com/moby/moby/releases points me to 17.03.02-ce as a direct link on the downloads page, which again downloads the wrong version. I tried downloading the link to the static binaries, however that was very confusing. This page https://docs.docker.com/engine/installation/linux/docker-ce/binaries/#next-steps says that in order to get the static binaries to compile I should run the command ` sudo cp docker/docker /usr/local/bin/`, however nowhere in that static binary folder is there a folder labeled docker. 

Meanwhile this page https://docs.docker.com/docker-for-mac/release-notes/#docker-community-edition-17090-ce-mac32-2017-10-02-stable, goes from release *Docker Community Edition 17.03.1-ce-mac12, 2017-05-12 (stable)* to release *Docker Community Edition 17.06.0-ce-mac18, 2017-06-28 (stable)*. Not only does this skip the one release I have, but it seems to have versions that are *ahead* of the most recent release at https://github.com/moby/moby/releases.

I'm very very confused. It should not be as difficult as this to get the currently stable version of Docker that runs with AWS. Can someone let me know how to resolve this issue?

I've opened a StackOverflow question here: https://stackoverflow.com/questions/47275270/elastic-beanstalk-requires-deprecated-hard-to-find-docker-version

**Comment by thaJeztah** [comment]
Installation instructions for old version of Docker can be found in the documentation archives; for example here's the installation instructions for Docker 17.03 on Ubuntu; https://docs.docker.com/v17.03/engine/installation/linux/ubuntu/, however, even the current installation instructions should work, if you specify the exact version to install; see the section , which mentions;

> On production systems, you should install a specific version of Docker CE instead of always using the latest. This output is truncated. List the available versions.
> ```bash
> $ apt-cache madison docker-ce
> 
> docker-ce | 17.09.0~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages
> ```
> The contents of the list depend upon which repositories are enabled. Choose a specific version to install. The second column is the version string. The third column is the repository name, which indicates which repository the package is from and by extension its stability level. To install a specific version, append the version string to the package name and separate them by an equals sign (=):
> ```bash
> sudo apt-get install docker-ce=<VERSION>
> ```


> however nowhere in that static binary folder is there a folder labeled docker

Downloading the static binaries from https://download.docker.com/linux/static/stable/x86_64/docker-17.03.2-ce.tgz does give me all the binaries;

<img width="241" alt="screen shot 2017-11-14 at 16 56 57" src="https://user-images.githubusercontent.com/1804568/32789751-e4d4c120-c95c-11e7-8a1c-8da76f9bced5.png">

> but it seems to have versions that are ahead of the most recent release at https://github.com/moby/moby/releases.

Correct, moby is not docker with the [introduction of the moby project](https://blog.docker.com/2017/04/introducing-the-moby-project/), the Moby _project_ and Docker _product_ are separate; Docker community edition is built from the https://github.com/docker/docker-ce repository.

> I'm very very confused. It should not be as difficult as this to get the currently stable version of Docker that runs with AWS. Can someone let me know how to resolve this issue?

Docker 17.09 is the current stable version of Docker CE; however, it looks like Amazon put a restriction on their tool that does not allow using the tool with current versions.

None of the versions listed by elastic beanstalk above are current releases (all of those have reached EOL, and are no longer maintained, or supported).

I suggest opening a ticket with Amazon, because this is an issue in their software, not something. I don't think there's much that can be done here (I do hope that my answers above help though)

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
