### ISSUE TITLE
Overlayfs(overlay2) cause error when starting mysql on the image with mysql installed.

### ISSUE THREAD

**Issue by yoshiokatsuneo** [moby/moby#35503]
**Description**
On overlayfs, when I install mysql, commit the image, and start mysql on the image, then I failed to run the mysql.

No problem on aufs.
No problem if I install the mysql and start the mysql, on the same container.

**Steps to reproduce the issue:**
1. Start ubuntu container
2. Install mysql
3. Commit the container to a Docker image.
4. Start another container using the Docker image created on 3.
5. Start mysql

Failed example on "overlay2" storage driver. (using Docker for Mac)

```
~$ docker info|grep Storage
Storage Driver: overlay2
~$ uname -a
Darwin MacBookPro-TY.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64
~$ docker run -i -t ubuntu /bin/bash
root@54583c00d29b:/# apt-get update
root@54583c00d29b:/# cat /etc/os-release |grep VERSION=
VERSION="16.04.3 LTS (Xenial Xerus)"
root@54583c00d29b:/# apt-get install mysql-server
root@54583c00d29b:/# service mysql start
 * Starting MySQL database server mysqld                                                                          No directory, logging in with HOME=/
[ OK ]

~$ docker commit 54583c00d29b my-mysql-ubuntu 
~$ docker run --rm -i -t my-mysql-ubuntu
root@e7d54edee7be:/# service mysql start
 * Starting MySQL database server mysqld                                        No directory, logging in with HOME=/
[fail]
root@e7d54edee7be:/# cat /var/log/mysql/error.log 
...
2017-11-15T06:44:22.074918Z 0 [Note] Server socket created on IP: '127.0.0.1'.
2017-11-15T06:44:22.103486Z 0 [Note] InnoDB: Buffer pool(s) load completed at 171115  6:44:22
2017-11-15T06:44:22.141481Z 0 [ERROR] Fatal error: Can't open and lock privilege tables: Table storage engine for 'user' doesn't have this option
2017-11-15T06:44:22.141672Z 0 [ERROR] Aborting
...
```

There is no error if I changed the storage driver to aufs like below.

/etc/docker/daemon.json :

```
{
  "storage-driver" : "aufs",
  "debug" : true,
  "experimental" : true
}
```

**Describe the results you received:**
Failed to start my sql with error message:

```
2017-11-15T06:44:22.141481Z 0 [ERROR] Fatal error: Can't open and lock privilege tables: Table storage engine for 'user' doesn't have this option
```

**Describe the results you expected:**
Starting mysql.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
~$ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true

```

**Output of `docker info`:**

```
Containers: 26
 Running: 1
 Paused: 0
 Stopped: 25
Images: 253
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: TYQA:VD3S:BPO2:QA5V:YVIM:HPA4:24IL:OMJL:MPIV:5GJG:J45I:MPIZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 24
 Goroutines: 34
 System Time: 2017-11-15T07:09:26.72660759Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by AkihiroSuda** [comment]
This is known issue
https://github.com/docker/for-linux/issues/72

**Comment by thaJeztah** [comment]
Yes, it's known that overlayfs only supports a subset of the POSIX standard (also see https://github.com/docker/for-linux/issues/72#issuecomment-319904698, thanks Akihiro)

Generally, stateful data should not be stored in the container's filesystem but in a volume. Not only does that allow you to upgrade containers without loosing your data (which is even more relevant when running those containers as part of a service, because updating a service will replace containers with a new one), it also has a _big_ impact on performance, as writing in the container's filesystem will add the overhead of copy-on-write filesystem that's used in containers.

See the "volumes" section in the documentation for more information; https://docs.docker.com/engine/admin/volumes/, and the "Where to Store Data" section of the official MySQL image on Docker Hub https://hub.docker.com/_/mysql/

If your goal is to run a MySQL container, I would definitely recommend looking at the official MySQL images, in which mysql is setup for running in a container, and which also allow you to initialise new instances from a backup using the  `/docker-entrypoint-initdb.d` (see the "Initializing a fresh instance" section in the MySQL readme on Docker Hub)

I'm closing this issue because there are other issues tracking this problem, but feel free to comment after I closed
