### ISSUE TITLE
Windows NAT networking is broken with multiple containers on 1709

### ISSUE THREAD

**Issue by sesmith177** [moby/moby#35535]
**Description**

When multiple containers are started on the same host using the NAT network to map ports, deleting one of the containers prevents traffic from being routed to the other containers through their exposed ports

**Steps to reproduce the issue:**

```
$localIP = <local ip address>

$c1=(docker run -d -p 40000:8080 microsoft/windowsservercore:1709 powershell -command '$l =
 [system.net.sockets.tcplistener]8080; $l.Start(); sleep(10000)')

test-netconnection -computername $localIP -port 40000 # succeeds

$c2=(docker run -d -p 41111:8080 microsoft/windowsservercore:1709 powershell -command '$l =
 [system.net.sockets.tcplistener]8080; $l.Start(); sleep(10000)')

docker stop $c1
docker rm $c1

test-netconnection -computername $localIP -port 41111 # fails
docker stop $c2
docker rm $c2
```

**Describe the results you received:**

Unable to send traffic through the exposed port to `$c2`

**Describe the results you expected:**

Able to send traffic  through the exposed port to `$c2`

**Output of `docker version`:**

```
Client:
 Version:      master-dockerproject-2017-11-06
 API version:  1.34
 Go version:   go1.8.5
 Git commit:   e2ada66
 Built:        Mon Nov  6 23:49:05 2017
 OS/Arch:      windows/amd64

Server:
 Version:      master-dockerproject-2017-11-06
 API version:  1.35 (minimum version 1.24)
 Go version:   go1.8.5
 Git commit:   b00b1b1
 Built:        Mon Nov  6 23:53:01 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: master-dockerproject-2017-11-06
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows Server Standard
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 4GiB
Name: VAGRANT-R4G63OV
ID: N3AK:PNFC:7GOM:E7AP:KEYA:KL7F:A5IC:ECWH:JOFH:PAYO:ZI6D:PYYN
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by dineshgovindasamy** [comment]
@sesmith177 I was able to repro the issue locally and looking into it. This issue only happens if we haven't created a session ever for the first time for the container u r targeting  and you delete any container. as part of cleaning up we have a bug where we are deleting the unused mappings. 

if in ur example if you do the following it works.

$localIP = <local ip address>

$c1=(docker run -d -p 40000:8080 microsoft/windowsservercore:1709 powershell -command '$l =
 [system.net.sockets.tcplistener]8080; $l.Start(); sleep(10000)')

test-netconnection -computername $localIP -port 40000 # succeeds

$c2=(docker run -d -p 41111:8080 microsoft/windowsservercore:1709 powershell -command '$l =
 [system.net.sockets.tcplistener]8080; $l.Start(); sleep(10000)')

<new step> test-netconnection -computername $localIP -port 41111 #succeeds

docker stop $c1
docker rm $c1

<this works> test-netconnection -computername $localIP -port 41111 # succeeds
docker stop $c2
docker rm $c2

**Comment by sesmith177** [comment]
@dineshgovindasamy Is there a powershell command or something similar that can be used to display the mappings?

**Comment by dineshgovindasamy** [comment]
@sesmith177 

Yes there is.
Get-HNSNetwork | convertto-json -Depth 20 =>  will return you the network information.
Get-HnsEndpoint | convertto-json -Depth 20 => Will return you the Endpoint information, including static mapping.

**Comment by mhoran** [comment]
It looks like this issue has been resolved in [KB4074588](https://support.microsoft.com/en-us/help/4074588/windows-10-update-kb4074588).

![screenshot at 2018-02-13 15-50-17](https://user-images.githubusercontent.com/5330/36173134-f4741188-10d5-11e8-9567-7ada8c3096a6.png)

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
