### ISSUE TITLE
Docker hv-sock proxy (vsudd) is not reachable

### ISSUE THREAD

**Issue by zappbrannigan34** [moby/moby#35569]
I have a windows server 2016 gui with latest updates on vsphere vm. Docker not work
https://pastebin.com/wSKG4z0U

**Comment by friism** [comment]
On Windows Server, please install Docker Enterprise edition: https://docs.docker.com/engine/installation/windows/docker-ee/

**Comment by thaJeztah** [comment]
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is a support question, but feel free to continue the conversation

**Comment by zappbrannigan34** [comment]
docker ee is free?

**Comment by thaJeztah** [comment]
For Microsoft Windows Server 2016, Docker EE basic is included with your license for Windows Server;

From https://store.docker.com/editions/enterprise/docker-ee-server-windows:

> Docker EE for Windows Server is available at no additional cost to all Windows Server 2016 customers. Technical support is aligned to the Microsoft support entitlement and provided by Microsoft.

And installation instruction:
https://docs.docker.com/engine/installation/windows/docker-ee/

Support is handled through Microsoft support

**Comment by zappbrannigan34** [comment]
Thanks
