### ISSUE TITLE
Security: Nonroot use a  non privileged container to elevate privileges

### ISSUE THREAD

**Issue by keloyang** [moby/moby#35598]
In a non privileged container, it can set suid for some app, as a result , nonroot in the host can use the app to elevate privileges.
## reproduce
run a non privileged container:
```
[root@localhost seccomp]# docker run --rm -ti -v /bin/ls:/home/ls -w /home  busybox ash          
/home # chmod 4777 ls
/home # 
```
another terminal, nonroot can list the files in /root.
```
# In the host, not in the container.
[hello@localhost ~]$ id
uid=1000(hello) gid=1000(hello) groups=1000(hello) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
[hello@localhost ~]$ ls /root
anaconda-ks.cfg  autofs-5.0.7-56.el7.src.rpm  dirty 
```

## Why?
A root user in a non privileged container is a really root user who just drop some capabilities and is restricted to use some system calls and others. Currently chmod syscall is not restricted, so it can set suid  for some app and nonroot can use it to  elevate privileges.

## How can we deal with it ?
We can use seccomp to restrict the parameter of chmod and make chmod can change general file mode(such ass 0777)， but not suid(like 4000). In consideration of some user want to set suid in a container, so I add sys_admin capability to remove this restriction, just like clone.
https://github.com/moby/moby/pull/35583 for details.

## About the compatibility
I f we restricte a  non privileged container to set suid and build a docker image, "RUN set suid operation" is not allowed, so I add sys_admin to docker build command to avoid break the build with "RUN set suid operation" .

**Comment by justincormack** [comment]
This doesnt make much sense, as images can contain suid files already. If you dont want suid files to do anything, run your containers with "no new privileges".

**Comment by justincormack** [comment]
I still don't understand the rationale, you need to explain it betetr. The root user can set things suid, but can also just run things as root too. If you don't want ability to use suid, you can use your custom seccomp profile from the PR (but this will break some uses of build) or you can use the no_new_privileges option, or just run as an unprivileged user.

**Comment by keloyang** [comment]
@justincormack thanks for your reply, I'm sorry I didn't make it clear. I add  the " In the host, not in the container" in the reproduce section. In a non privileged container, it can set suid for some app, as a result , **nonroot in the host** can use the app to elevate privileges.

**Comment by thaJeztah** [comment]
Following the discussion on this issue, and on the pull request, I suggest we close this issue. Having access to the docker API provides you root access on the host; this is known, and described in the  [docker daemon attack vector](https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface) section in the documentation.

The difference in this case is that the attack is not "direct", but "prepares" a possible attack at a later stage. The security risk is the same though; instead of preparing an attack (by setting `suid`), someone with access to the docker API could just as well directly cause damage on the host (simply running `docker run -v /:/host busybox sh -c 'rm -rf /host'` allows you to while the host).

Using a bind-mount explicitly grants the container full access to those files on the host, and one should expect that, in doing so, the container is able to make modifications (including setting `suid`).

**Comment by thaJeztah** [comment]
Closing, after discussing with @justincormack, but feel free to comment after I closed 👍
