### ISSUE TITLE
RFC: Report free/used/total space in /var/lib/docker for all storage plugins

### ISSUE THREAD

**Issue by xvello** [moby/moby#35629]
**Description**

When using the `devicemapper` storage plugin, free/used/total disk space is exposed via the `info` endpoint. The Datadog agent supports extracting these values and reporting `docker.data.*` gauges so our users can monitor it easily.

From my investigation, this is the only storage plugin to expose these metrics, as others are filesystem-backed and a simple `df` on the host gives the information. Unfortunately, `mnt` namespacing makes it impossible to do it from our `docker-dd-agent` container without intrusive bind-mounts.

**Describe the results you received:**

Free space available to docker is only monitorable if using the `devicemapper` plugin.

**Describe the results you expected:**

Free space available to docker is monitorable for every storage plugin.

**How should we implement that?**

We are willing to contribute code to enable that in future versions, this issue is to open the discussion on how that should be done.

#### 1. Assume `/` metrics in the container == `/var/lib/docker` metrics on the host

Although that is true for standard use cases with the `overlay2` storage plugin, I think that's pretty fragile.

#### 2. Patch every plugin to expose these metrics in `docker info`

We could add the same "Data space *" info lines [as in devicemapper](https://github.com/moby/moby/blob/05ad14fc1bc5626895a419a991fcf8932eb91d27/daemon/graphdriver/devmapper/driver.go#L76-L78) to all drivers. It is probably factorable in a single common function for all filesystem-backed storage plugins.

#### 3. Add the information to `docker system df`

It is pretty counter-intuitive `docker system df` is the equivalent of `du` and not `df`. We could add another section to this payload with the free/used/total stats for `/var/lib/docker`, or even for every subfolder if storing them in different partitions is supported.

What do you think?

**Comment by xvello** [comment]
@thaJeztah sorry for the ping, this issue has not been triaged. Do you know who could move the discussion forward?

Thanks!

**Comment by thaJeztah** [comment]
I'm personally a bit unsure if this goes beyond the daemon's scope; monitoring host resources is not something new, and not specific to docker, so I wonder if this belongs in the daemon.

The "device mapper" case is a bit different, because (when using loop-lvm), the device mapper devices are created by docker, and the sizes reported are part of that configuration.

I know use-cases where separate mounts/devices are used for some directories inside `/var/lib/docker`; what size/space should be reported in that situation?

I'll add this issue for discussion in the next maintainers meeting (which will probably take place next week, after new year), and get some more input.

**Comment by xvello** [comment]
Thanks for the input @thaJeztah ,

Indeed, mounting several filesystems is a legit deployment case, this is why I added choice number 3: add it to the `df` endpoint. It currently lists the total used space for images/volumes/containers, we could add the free space available for these types. Depending on their deployment, users could then either avg (same fs) or sum it (different fs).

**Comment by thaJeztah** [comment]
We discussed this in the maintainers meeting, and we're still worried that this goes beyond the responsibility of the daemon. In addition, we want to be careful adding new features to the graphdrivers, because at some point more of this functionality will be moved to containerd, and the daemon will be using that.

So, for now, we don't think we should add this (but things can change in future)

**Comment by xvello** [comment]
Thanks for following-up on the topic! We will investigate other ways to make it as easy as possible for users.

**Comment by thaJeztah** [comment]
Keep us posted; if you run into issues, or want to discuss further, don't hesitate to join the `#moby-project` channel on the Docker Community slack, or the `#containerd` channel to discuss if things are needed in containerd.
