### ISSUE TITLE
moby and docker-ce

### ISSUE THREAD

**Issue by yangxingwu** [moby/moby#35655]
hi, team

I really want to know how to build docker-ce from moby

since **docker** rename to **moby**, and move **containerd** and **runc** to other repositories

It's somehow confused

**Comment by AkihiroSuda** [comment]
Just do `make` in this repo and you can get `dockerd`, `docker-containerd`, and `docker-runc`.

**Comment by thaJeztah** [comment]
This repository contains the "engine" component for Docker CE. Together with the Docker CLI (which is in https://github.com/docker/cli), you'll get Docker CE.

The repository that's used to build Docker CE can be found at https://github.com/docker/docker-ce (you'll find branches for each release, as well as tags) 

Scripts for building packages can be found in the "packaging" component in that repository, for example, for the 17.09 branch; https://github.com/docker/docker-ce/tree/17.09/components/packaging

I'll close this issue because I think the question is answered, but feel free to continue the conversation
