### ISSUE TITLE
LCOW: chmod permission denied in a volume

### ISSUE THREAD

**Issue by AlekseyMartynov** [moby/moby#35665]
Using https://github.com/linuxkit/lcow#setup
Server Version: `master-dockerproject-2017-11-30`

```
docker run --rm -v temp1:/temp1 alpine sh -c "cd /temp1 && touch a && chmod +x a"

chmod: a: Permission denied
```

Real-world use case is `npm i` in a volume:

```
docker run --rm -v temp1:/temp1 node:8 sh -c "cd /temp1 && npm i leftpad"

npm ERR! path /temp1/node_modules/leftpad/package.json.2479725784
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall chmod
npm ERR! Error: EACCES: permission denied, chmod '/temp1/node_modules/leftpad/package.json.2479725784'
```

**Comment by los93sol** [comment]
Having the same issue using LCOW.  Did you find a workaround?  I'm also confused if this is an issue with Moby or LinuxKit....

**Comment by wtigotw** [comment]
chmod is a pretty common command to run. Many of the utilities I run in containers rely on the use of it. For example, I can't run syncthing in an lcow container because both the configuration and synchronized data directories use chmod. I can live with the configuration being in the container instead of a volume, but realistically since both are stateful they should be in volumes.

The same behavior exists for named and bound volumes.

**Comment by cocowalla** [comment]
I really wonder about the usefulness of LCOW without `chown` and `chmod` - a *lot* of containers use these. Switching back to Linux containers, again...

**Comment by thaJeztah** [comment]
Possibly related: https://github.com/moby/moby/issues/36531

LCOW is still an experimental feature, and not yet feature-complete. Unfortunately there's still many things left to implement (either in the Moby code, or in Windows).

**Comment by mtudor** [comment]
I have also switched back to Linux containers, but LCOW is very promising and I for one am very positive about what the future holds for containers on windows...  @thaJeztah I also saw that issue so I'm sure you're right that it's related - I think it's probably wait and see on both issues...

**Comment by Andy2244** [comment]
@cocowalla Yes, tested this a few days ago with latest windows 10 and docker 18.05, just to find the same problem with the 9p filesystem i had at the inception of LCOW a year ago, file locking does not work, so nearly every container i use wont work. 

I also watched some dockercon videos specifically talking about LCOW and while they note that LCOW is "incomplete" and shares code with WSL, there is hardly any mention on file locking, which seems to-be one of the major missing features. I also can not find any information on the possibility or timeline to fix those issues.

I guess we will have to test this every few months and hope the MS dev actually tries to get a mysql or sqlite container to work in LCOW.

**Comment by syedhassaanahmed** [comment]
Same problem booting up `neo4j` image on latest LCOW build. Any update on this issue?

**Comment by los93sol** [comment]
Any updates?  Using server 1809 and docker 18.09.3 with lcow and still having issues with several containers.  I would have expected someone to pick this up after it's been an issue for a few years.  LCOW is basically pointless at this stage until this is fixed.

**Comment by jhowardmsft** [comment]
@los93sol The nature of OSS is that people have their day jobs and other priorities too....

**Comment by cocowalla** [comment]
@jhowardmsft some of the maintainers work at Docker Inc, so this _is_ their day job....

I can see why there is frustration here, and TBH I don't know what the point was of releasing LCOW with a known limitation that effectively renders it useless.

**Comment by jhowardmsft** [comment]
Remember that LCOW is an experimental feature. In reality what you're asking for here is incredibly difficult if you think about it for a moment. You're mounting an NTFS volume from the host into a Linux host. NTFS doesn't support Unix-style permissions natively. Chmod should work though on the containers scratch space as this is native ext4.

**Comment by cocowalla** [comment]
@jhowardmsft I never said it was easy :smile:  My point is that it's really dissapointing that LCOW is still 'experimental' so long after release. It would be _great_ to be able to run Linux Docker containers on Windows without the need and overhead of a Linux VM, and that's what LCOW promised but leaves unfulfilled without support for chown/chmod/chattr.

**Comment by los93sol** [comment]
@jhowardmsft I understand it is a technical challenge and how OSS works/operates, but let's be honest for a minute here.  Microsoft has touted Docker as the way forward since Build 2016.  I understand experimental and all that, but in this case you can find several issues across various GH pages where MS employees point the finger at Docker, then Docker back at MS.  At some point the finger pointing has to stop and a decision about who/which repo should assume ownership of the resolution will have to occur before anyone can even begin working on a proper fix.

**Comment by Iristyle** [comment]
I believe that this should work fine on RS5 builds now, i.e. for Postgres - see https://github.com/docker/for-win/issues/445#issuecomment-480549220

**Comment by Andy2244** [comment]
This seem to work with the latest docker/lcow versions:
```
Docker version master-dockerproject-2019-06-05, build c02f389c
Kernel Version: 10.0 18362 (18362.1.amd64fre.19h1_release.190318-1202)
Operating System: Windows 10 Pro Version 1903 (OS Build 18362.145)
4.19.27-linuxkit
```

`docker run --rm -v temp1:/temp1 alpine sh -c "cd /temp1 && touch a && chmod +x a"`
No error's

```
docker run -it --rm -v temp1:/temp1 alpine sh
ls -1l /temp1/a
-rwxr-xr-x    1 root     root             0 Jun  6 12:22 /temp1/a
```

**Comment by thaJeztah** [comment]
@AlekseyMartynov is this resolved for you?

**Comment by cocowalla** [comment]
@thaJeztah does Windows and/or LCOW now support chown/chmod/chattr and friends?

**Comment by thaJeztah** [comment]
Don't know; many of these are dependent on the platform (Windows/Windows kernel); I don't personally run on Windows

**Comment by jhowardmsft** [comment]
Windows native LCOW (not Docker for Windows using moby VM) on RS5:

```
PS C:\vol> echo foo > file.txt
PS C:\vol> docker run -it --rm -v c:\vol:/test alpine /bin/sh
/ # ls -l /test
total 0
-rwxrwxrwx    1 root     root            12 Jun  6 20:40 file.txt
/ # chmod 755 /test/file.txt
/ # ls -l /test
total 0
-rwxr-xr-x    1 root     root            12 Jun  6 20:40 file.txt
/ # adduser john
Changing password for john
New password:
Retype password:
passwd: password for john changed by root
/ # chown john /test/file.txt
/ # ls -l /test
total 0
-rwxr-xr-x    1 john     root            12 Jun  6 20:40 file.txt
/ # cat /test/file.txt
 �f o o
 / #
PS C:\vol> docker run -it --rm -v c:\vol:/test alpine /bin/sh
/ # ls -l /test
total 0
-rwxr-xr-x    1 1000     root            12 Jun  6 20:40 file.txt
/ #
PS C:\vol>
```

**Comment by cocowalla** [comment]
Hmm, I don't see anything in the Windows 10 RS5 release notes about improved LCOW/Docker/9p support. Have you come across anything from Microsoft about this?

After being burned by trying LCOW on previous occasions (failure basically means a time-consuming reinstall of Docker), I'm *extremely* reluctant to spend the time trying again unless I'm more or less guaranteed success :smile:

**Comment by jhowardmsft** [comment]
The platform is improving all the time through releases. Remember though that LCOW is still an experimental feature... (the native one, not moby VM in D4W)

**Comment by cocowalla** [comment]
Yes, I commented as much around a year ago in this thread :relaxed:

It would be kind of nice for this aging, experimental feature to finally gain support for chattr et al so it was actually usable tho... :weary:  I've said it before, but I just don't get the *point* of releasing LCOW when it essentially can't actually run Linux containers.

**Comment by Andy2244** [comment]
Yeah its kinda sad, my org. issue docker/for-win#1385 from Dec 5, 2017 is still relevant, since i need working locking support, which lcow/9p still misses. The reason is that many of my containers use sqlite in WAL mode as data storage or to store config data.
While we have the lcow EPIC moby/moby#33850, getting updates on fixes regarding its 9P implementation is kinda hard. All i could find was this [linux-containers](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/linux-containers#bind-mounts) which is already over a year old.

I did wait for over 2 years for working LCOW, yet i have no clue if its 9P problems will ever be fully fixed, its literally useless to me if locking is not working or other features that break advanced containers. So i would like to see specific 9P related updates posted on the LCOW EPIC, with updates on what is being worked on and whats supposed to work, so i can judge when to restest stuff, instead of randomly grab the latest stuff and experiment with it.

**Comment by thaJeztah** [comment]
Closing this issue, because the experimental LCOW feature has been deprecated and removed in Docker 23.0 and up;

- https://github.com/docker/cli/pull/2798
- https://github.com/moby/moby/issues/39533
- https://github.com/docker/cli/pull/3223
