### ISSUE TITLE
 docker ps no response

### ISSUE THREAD

**Issue by xingxing9688** [moby/moby#35704]
docker  version   1.13.1  
centos  7.2   3.10.514

**Comment by cpuguy83** [comment]
@xingxing9688 Please upgrade to a newer version of docker, 1.13.1 is nearly a year old and out of support, and many issues with deadlocks are resolved.

Closing since there is no info to go on here, and the report is against a very out of date version of Docker, but feel free to comment.
Thanks! 🙇 👼
