### ISSUE TITLE
Additional explanation of security risks when downloading the convenience script "at runtime"

### ISSUE THREAD

**Issue by CodingSpiderFox** [moby/moby#35701]
The documentation says

"Always examine scripts downloaded from the internet before running them locally." (https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-using-the-convenience-script)

What I would like to have next to this warning message is a link to some documentation about which security risks I can run into when I do not examine the script. Which attack vectors exist, etc.

**Comment by thaJeztah** [comment]
It's a general recommendation; google for ["don't curl sh"](https://www.google.nl/search?q=dont+curl+sh&ie=UTF-8&oe=UTF-8&hl=en-nl&client=safari), and you'll find many articles, e.g. 

- https://sysdig.com/blog/friends-dont-let-friends-curl-bash/
- https://www.djm.org.uk/posts/protect-yourself-from-non-obvious-dangers-curl-url-pipe-sh/
- https://www.idontplaydarts.com/2016/04/detecting-curl-pipe-bash-server-side/

**Comment by thaJeztah** [comment]
I'm not sure additional documentation is needed for this, but if you think it's needed, could you open an issue in the documentation issue tracker instead? https://github.com/docker/docker.github.io/issues

I'll close this issue because the documentation is not in this repository, but feel free to discuss

**Comment by CodingSpiderFox** [comment]
https://github.com/docker/docker.github.io/issues/5478
