### ISSUE TITLE
docker fails to start. possibly systemd or pid-control related

### ISSUE THREAD

**Issue by l0rb** [moby/moby#35730]
**Description**
The docker service fails to start. It seems to hang in an endless startup loop. Error messages look systemd/pid-controller related. See below for exact messages

**Steps to reproduce the issue:**
1. start docker service

**Output of `docker version`:**
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:09 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
[no output, command hangs forever]
```
**Found in `/var/log/messages`:**
This message keeps popping up about every 5 minutes.
```
kernel: [  743.772608] cgroup: fork rejected by pids controller in /system.slice/docker.service
```

**Output of `systemctl -b -u docker`:***
```
Dec 07 09:06:04 systemd[1]: Starting Docker Application Container Engine...
Dec 07 09:06:04 dockerd[865]: time="2017-12-07T09:06:04.278568958+01:00" level=info msg="libcontainerd: new containerd process, pid: 877"
Dec 07 09:06:05 dockerd[865]: time="2017-12-07T09:06:05.966849762+01:00" level=info msg="[graphdriver] using prior storage driver: overlay2"
Dec 07 09:06:11 dockerd[865]: time="2017-12-07T09:06:11.524161284+01:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Dec 07 09:06:11 dockerd[865]: time="2017-12-07T09:06:11.524619166+01:00" level=warning msg="Your kernel does not support swap memory limit"
Dec 07 09:06:11 dockerd[865]: time="2017-12-07T09:06:11.524727383+01:00" level=warning msg="Your kernel does not support cgroup rt period"
Dec 07 09:06:11 dockerd[865]: time="2017-12-07T09:06:11.524749240+01:00" level=warning msg="Your kernel does not support cgroup rt runtime"
Dec 07 09:06:11 dockerd[865]: time="2017-12-07T09:06:11.525556139+01:00" level=info msg="Loading containers: start."
Dec 07 09:12:10 dockerd[865]: runtime/cgo: pthread_create failed: Resource temporarily unavailable
Dec 07 09:12:10 dockerd[865]: SIGABRT: abort
Dec 07 09:12:10 dockerd[865]: PC=0x7f3bdddb3fcf m=2 sigcode=18446744073709551610
Dec 07 09:12:10 dockerd[865]: goroutine 0 [idle]:
Dec 07 09:12:10 dockerd[865]: goroutine 1 [semacquire]:
Dec 07 09:12:10 dockerd[865]: sync.runtime_Semacquire(0xc439d8c5bc)
Dec 07 09:12:10 dockerd[865]:         /usr/local/go/src/runtime/sema.go:47 +0x34
Dec 07 09:12:10 dockerd[865]: sync.(*WaitGroup).Wait(0xc439d8c5b0)
Dec 07 09:12:10 dockerd[865]:         /usr/local/go/src/sync/waitgroup.go:131 +0x7a
Dec 07 09:12:10 dockerd[865]: github.com/docker/docker/daemon.(*Daemon).restore(0xc420322400, 0x272ae60, 0xc420322400)
Dec 07 09:12:10 dockerd[865]:         /go/src/github.com/docker/docker/daemon/daemon.go:297 +0x71f
Dec 07 09:12:10 dockerd[865]: github.com/docker/docker/daemon.NewDaemon(0xc420099200, 0x2752620, 0xc4200154a0, 0x273de60, 0xc4201248f0, 0xc42011a4b0, 0x0, 0x0, 0x0)
Dec 07 09:12:10 dockerd[865]:         /go/src/github.com/docker/docker/daemon/daemon.go:809 +0x2866
Dec 07 09:12:10 dockerd[865]: main.(*DaemonCli).start(0xc420195f50, 0xc42012ae00, 0x0, 0x0)
Dec 07 09:12:10 dockerd[865]:         /go/src/github.com/docker/docker/cmd/dockerd/daemon.go:223 +0x11ea
Dec 07 09:12:10 dockerd[865]: main.runDaemon(0xc42012ae00, 0xc4201a4900, 0x0)
Dec 07 09:12:10 dockerd[865]:         /go/src/github.com/docker/docker/cmd/dockerd/docker.go:78 +0x76
Dec 07 09:12:10 dockerd[865]: main.newDaemonCommand.func1(0xc420094480, 0xc4201147a0, 0x0, 0x2, 0x0, 0x0)
Dec 07 09:12:10 dockerd[865]:         /go/src/github.com/docker/docker/cmd/dockerd/docker.go:29 +0x5b
Dec 07 09:12:10 dockerd[865]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc420094480, 0xc420010250, 0x2, 0x2, 0xc420094480, 0xc420010250)
Dec 07 09:12:10 dockerd[865]:         /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:646 +0x44e
Dec 07 09:12:10 dockerd[865]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420094480, 0x1873c60, 0x1, 0xc4200150f0)
Dec 07 09:12:10 dockerd[865]:         /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:742 +0x349
Dec 07 09:12:10 dockerd[865]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420094480, 0xc4200150f0, 0x0)
Dec 07 09:12:10 dockerd[865]:         /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:695 +0x2b
Dec 07 09:12:10 dockerd[865]: main.main()
Dec 07 09:12:10 dockerd[865]:         /go/src/github.com/docker/docker/cmd/dockerd/docker.go:105 +0xe6
Dec 07 09:12:10 dockerd[865]: goroutine 17 [syscall, 6 minutes, locked to thread]:
Dec 07 09:12:10 dockerd[865]: runtime.goexit()
Dec 07 09:12:10 dockerd[865]:         /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1
Dec 07 09:12:10 dockerd[865]: goroutine 18 [syscall, 6 minutes]:
Dec 07 09:12:10 dockerd[865]: os/signal.signal_recv(0x72df0b)
Dec 07 09:12:10 dockerd[865]:         /usr/local/go/src/runtime/sigqueue.go:116 +0x104
Dec 07 09:12:10 dockerd[865]: os/signal.loop()
Dec 07 09:12:10 dockerd[865]:         /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
Dec 07 09:12:10 dockerd[865]: created by os/signal.init.1
Dec 07 09:12:10 dockerd[865]:         /usr/local/go/src/os/signal/signal_unix.go:28 +0x41
Dec 07 09:12:10 dockerd[865]: goroutine 458 [syscall]:
Dec 07 09:12:10 dockerd[865]: syscall.Syscall(0x4a, 0x14b0, 0x0, 0x0, 0x0, 0x6, 0xc42001f368)
[... and thousands more of this until ...]
Dec 07 09:24:31 systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Dec 07 09:24:31 systemd[1]: Stopped Docker Application Container Engine.
Dec 07 09:24:31 systemd[1]: Starting Docker Application Container Engine...
[... the same thousands again and again ...]
```

**Comment by l0rb** [comment]
Update: It does not fail with version `17.03.0-ce`, so for now a possible workaround is to downgrade

**Comment by thaJeztah** [comment]
What platform/distro are you running on? Do you have any specific daemon options set (either as flags (through the systemd unit-file, or a `daemon.json` configuration file)?

Currently there's not a lot of information to go on, so perhaps you can provide more information.

**Comment by l0rb** [comment]
I do not have access to the machine in question until Monday, so for now all I can provide in information is that it is running Debian 9 and no specific daemon options set.

**Comment by decryptedchaos** [comment]
i can confirm this also appears to be happening on my debian 9 cluster.  

No reproduction path it happened seemingly after an upgrade

Although my error trace is different it may be unrelated  but since this is a new issue i figured it may be related.  

~# dpkg --configure docker-ce

D000001: ensure_diversions: new, (re)loading
D000001: process queue pkg docker-ce:amd64 queue.len 0 progress 1, try 1
D000040: checking dependencies of docker-ce:amd64 (- <none>)
D000400:   checking group ...
D000400:     checking possibility  -> iptables
D000400:       checking non-provided pkg iptables:amd64
D000400:       is installed, ok and found
D000400:     found 3
D000400:   found 3 matched 0 possfixbytrig -
D000400:   checking group ...
D000400:     checking possibility  -> init-system-helpers
D000400:       checking non-provided pkg init-system-helpers:all
D000400:       is installed, ok and found
D000400:     found 3
D000400:   found 3 matched 0 possfixbytrig -
D000400:   checking group ...
D000400:     checking possibility  -> libapparmor1
D000400:       checking non-provided pkg libapparmor1:amd64
D000400:       is installed, ok and found
D000400:     found 3
D000400:   found 3 matched 0 possfixbytrig -
D000400:   checking group ...
D000400:     checking possibility  -> libc6
D000400:       checking non-provided pkg libc6:amd64
D000400:       is installed, ok and found
D000400:     found 3
D000400:   found 3 matched 0 possfixbytrig -
D000400:   checking group ...
D000400:     checking possibility  -> libdevmapper1.02.1
D000400:       checking non-provided pkg libdevmapper1.02.1:amd64
D000400:       is installed, ok and found
D000400:     found 3
D000400:   found 3 matched 0 possfixbytrig -
D000400:   checking group ...
D000400:     checking possibility  -> libltdl7
D000400:       checking non-provided pkg libltdl7:amd64
D000400:       is installed, ok and found
D000400:     found 3
D000400:   found 3 matched 0 possfixbytrig -
D000400:   checking group ...
D000400:     checking possibility  -> libseccomp2
D000400:       checking non-provided pkg libseccomp2:amd64
D000400:       is installed, ok and found
D000400:     found 3
D000400:   found 3 matched 0 possfixbytrig -
D000400:   checking group ...
D000400:     checking possibility  -> libsystemd0
D000400:       checking non-provided pkg libsystemd0:amd64
D000400:       is installed, ok and found
D000400:     found 3
D000400:   found 3 matched 0 possfixbytrig -
D000040: ok 2 msgs >><<
D000040:     checking Breaks
Setting up docker-ce (17.09.1~ce-0~debian) ...
D000002: fork/exec /var/lib/dpkg/info/docker-ce.postinst ( configure 17.09.0~ce-0~debian )
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sat 2017-12-09 11:24:02 EST; 17ms ago
     Docs: https://docs.docker.com
 Main PID: 7694 (code=exited, status=2)

Dec 09 11:24:02 node01-docker-phx.fluidservers.net dockerd[7694]:         /usr/local/go/src/syscall/syscall_linux.go:51 +0x50
Dec 09 11:24:02 node01-docker-phx.fluidservers.net dockerd[7694]: os.OpenFile(0xc42b944300, 0x78, 0xc2, 0xc400000180, 0x78, 0xc436c5cfe0, 0x1c)
Dec 09 11:24:02 node01-docker-phx.fluidservers.net dockerd[7694]:         /usr/local/go/src/os/file_unix.go:97 +0x80
Dec 09 11:24:02 node01-docker-phx.fluidservers.net dockerd[7694]: io/ioutil.TempFile(0xc42b877030, 0x5b, 0xc437f2cbf0, 0x13, 0xe, 0xc437f2cbf0, 0x13)
Dec 09 11:24:02 node01-docker-phx.fluidservers.net dockerd[7694]:         /usr/local/go/src/io/ioutil/tempfile.go:55 +0x14d
Dec 09 11:24:02 node01-docker-phx.fluidservers.net dockerd[7694]: github.com/docker/docker/pkg/ioutils.NewAtomicFileWriter(0xc42b877030, 0x6a, 0x180, 0x0, 0x0, 0x0, 0x0)
Dec 09 11:24:02 node01-docker-phx.fluidservers.net dockerd[7694]:         /go/src/github.com/docker/docker/pkg/ioutils/fswriters.go:14 +0xe8
Dec 09 11:24:02 node01-docker-phx.fluidservers.net dockerd[7694]: github.com/docker/docker/container.(*Container).toDisk(0xc42588f8c0, 0x0, 0x0, 0x0)
Dec 09 11:24:02 node01-docker-phx.fluidservers.net dockerd[7694]:         /go/src/github.com/docker/docker/container/container.go:171 +0xcb
Dec 09 11:24:02 node01-docker-phx.fluidservers.net systemd[1]: docker.service: Failed with result 'exit-code'.
Dec 09 11:24:02 node01-docker-phx.fluidservers.net dockerd[7694]: github.com/docker/docker/container.(*Container).CheckpointTo(0xc42588f8c0, 0x2752160, 0xc420114190, 0x0, 0x0)
Dec 09 11:24:02 node01-docker-phx.fluidservers.net dockerd[7694]:         /go/src/github.com/docker/docker/container/container.go:196 +0x2b
Dec 09 11:24:02 node01-docker-phx.fluidservers.net dockerd[7694]: github.com/docker/docker/daemon.(*Daemon).checkpointAndSave(0xc420488200, 0xc42588f8c0, 0x0, 0x0)
dpkg: error processing package docker-ce (--configure):
 subprocess installed post-installation script returned error exit status 1
D000001: ensure_diversions: same, skipping
Errors were encountered while processing:
 docker-ce

**Comment by l0rb** [comment]
Output of `uname -a`:
```
Linux hostname 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
```
What other information could help debug this regression?

**Comment by thaJeztah** [comment]
@l0rb the "restore" messages come from this part in the source; https://github.com/docker/docker-ce/blob/17.09/components/engine/daemon/daemon.go#L215-L295

- what version were you running before upgrading docker?
- do you have live-restore enabled?

Do you have more information about your setup (number of containers present (both running and stopped), storage driver in use, backing filesystem?))

**Comment by thaJeztah** [comment]
You mention you see thousands of those `restore` messages; there should be one per container (hence my interest in number of containers present on that machine).

What's `/proc/sys/kernel/threads-max` set to on that machine?

**Comment by l0rb** [comment]
Requested information:

- number of containers: ~ 13000
- running containers: ~ 10
- `/proc/sys/kernel/threads-max`: 62224
- storage driver: overlay2
- backing filesystem: extfs
- live-restore: Probably not? Never heard of this and don't know how to check.
- version before upgrade: not sure, most likely 17.06~ce

**Comment by thaJeztah** [comment]
Hm, so I suspect what's happening is that the code Inreferred to performs a migration of the container configuration on disk; it attempts to do so for all 13000 containers, but gets limited by the kernel, resulting in that migration to not complete.

Cleaning up stopped containers could help

**Comment by l0rb** [comment]
Cleaning out stopped containers did fix the problem.

**Comment by thaJeztah** [comment]
closing, as this one went stale
