### ISSUE TITLE
lost connection between containers on different nodes

### ISSUE THREAD

**Issue by ronag** [moby/moby#35742]
Currently running a swarm on some bare-metal hosts on a bare-metal network. Everything has been running fine for a while, when (seemingly for no obvious reason) two containers on two different nodes (silently) weren’t able to communicate with each other anymore. The only thing I can find divergent in any logs is from dmesg on Node A, that had a container not being able to communicate with another container on Node B, (repeatedly):

```
[Thu Dec  7 18:32:16 2017] net_ratelimit: 45 callbacks suppressed
[Thu Dec  7 18:32:16 2017] vxlan: non-ECT from 10.112.182.4 with TOS=0x2
[Thu Dec  7 18:33:09 2017] vxlan: non-ECT from 10.112.182.4 with TOS=0x2
[Thu Dec  7 18:33:09 2017] vxlan: non-ECT from 10.112.182.4 with TOS=0x2
[Thu Dec  7 18:38:21 2017] vxlan: non-ECT from 10.112.182.4 with TOS=0x2
[Thu Dec  7 18:39:02 2017] vxlan: non-ECT from 10.112.182.4 with TOS=0x2
[Thu Dec  7 18:39:14 2017] vxlan: non-ECT from 10.112.182.4 with TOS=0x2
[Thu Dec  7 18:39:56 2017] vxlan: non-ECT from 10.112.182.4 with TOS=0x2
[Thu Dec  7 18:39:56 2017] vxlan: non-ECT from 10.112.182.4 with TOS=0x2
```

However, 10.112.182.4 is not Node B, it’s yet another host in the swarm, Node C.

Is it possible that this, although it concerns Node A and C, has anything to do with communication failing between containers on Node A and B?

The fix was to kill the containers and have swarm start a new ones... However, that is not good enough for a production setup.

Not being particularly familiar with the lower levels of vxlan, can anyone shed a light on what it means?

Docker version 17.05.0-ce, build v17.05.0-ce
Linux version 4.4.52

**Comment by thaJeztah** [comment]
Note that Docker 17.05 is an edge (monthly) release and has reached end of life in June; if you're running in production, I'd definitely recommend to use the "stable" channel (which is maintained for four months) or Docker EE (with 12 (18?) months of support).

Keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

Since this is a support question, Im closing this issue, but feel free to discuss
