### ISSUE TITLE
COPY --chown does not modify owner for all created directories

### ISSUE THREAD

**Issue by kerhong** [moby/moby#35783]
**Description**

When using `COPY --chown` to copy multi-level directory the owner is not changed for first levels.

**Steps to reproduce the issue:**
1. Setup the multi-level directory we will be copying `mkdir -p ./a/b/c && touch ./a/b/c/d.txt`
2. create a Dockerfile:
```Dockerfile
FROM alpine:3.7

RUN adduser -D -u 1000 -g 'www' www
RUN mkdir /test

COPY --chown=www:www a/b/c/ /test/a/b/c/

CMD [ "ls", "-l", "/test", "/test/a", "/test/a/b", "/test/a/b/c" ]
```
3. Run the container `docker run --rm $(docker build -q .)`

**Describe the results you received:**
```
$ docker run --rm $(docker build -q .)
/test:
total 4
drwxr-xr-x    3 root     root          4096 Dec 13 09:51 a

/test/a:
total 4
drwxr-xr-x    3 root     root          4096 Dec 13 09:51 b

/test/a/b:
total 4
drwxr-xr-x    3 www      www           4096 Dec 13 09:51 c

/test/a/b/c:
total 4
drwxrwxr-x    2 www      www           4096 Dec 13 09:51 d.txt
```

**Describe the results you expected:**
I expected `/test/a` and `/test/a/b` to be owned by www:www instead of root:root

**Output of `docker version`:**
```
$ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 106
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-42-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 15.41GiB
Name: irrelevant
ID: VJ4J:2HCN:RMJ5:XEC2:7ULY:4TAK:O7EH:L6GY:LJJG:MGXM:JVWX:7LFN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by thaJeztah** [comment]
This is expected; what's happening is this; the `COPY` instruction below:

```
COPY --chown=www:www a/b/c/ /test/a/b/c/
```

Basically says:

"Copy the file or directory `c`, located at `/a/b` in the source image to `/a/b` in the target image, and `chown` the copied directory."

The `COPY` command also checks if the target path in the container exists, and if not, create it, before copying.

So in your example, the `COPY` instruction;

- checks if the target path (`/a/b/`) exists in the container/image (which isn't the case)
- the path `/a/b/` is created (`COPY` by default creates content as user `0:0` / `root:root`), so directory `/a/` and `/a/b/` are created as `root:root`
- the directory `c` (and its content) is copied to `/a/b/`
- the director `c` (and its content) is `chown`-ed to `www:www`


Docker won't recursively `chown` the full parent path, because this may be an existing path. If you need that path to be owned by `www:www`, make sure to create it upfront, and giving it the correct permissions instead of relying on `COPY` to create the path.

**Comment by kerhong** [comment]
Thank you, will create the required directories before copying as you suggested.
