### ISSUE TITLE
docker ps hang on Centos7 with version 1.13.1

### ISSUE THREAD

**Issue by krmayankk** [moby/moby#35839]
[daemon.txt](https://github.com/moby/moby/files/1573597/daemon.txt)
```
docker version
Client:
 Version:      1.13.1-cs2
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   ad32da7
 Built:        Thu Feb 23 16:40:08 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1-cs2
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   ad32da7
 Built:        Thu Feb 23 16:40:08 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
goroutine and daemon-data 

[goroutine-stacks-2017-12-19T021945Z.log](https://github.com/moby/moby/files/1573586/goroutine-stacks-2017-12-19T021945Z.log)
[goroutine-stacks-2017-12-19T022016Z.log](https://github.com/moby/moby/files/1573587/goroutine-stacks-2017-12-19T022016Z.log)

docker ps hangs
docker ps -n 16 doesnt hang
docker info and docker version works
docker-containerd is still running

Please let us know how to resolve this. We are seeing this issue on multiple hosts

**Comment by thaJeztah** [comment]
Looks like you're running the CS (commercially supported) version of Docker; the community edition for Docker 1.13 has reached end of life (and is no longer maintained); if you have an active subscription for Docker CS, can you contact customer support?

I'll have to close the issue here, because this issue tracker is for the open source project, not for support for the commercial products, but feel free to continue the conversation
