### ISSUE TITLE
Moby website problems

### ISSUE THREAD

**Issue by philippeboyd** [moby/moby#35878]
So I want to test out Moby by going on http://play-with-moby.com and when I want to Build/Run, nothing works.

![capture d ecran 2017-12-26 a 15 26 17](https://user-images.githubusercontent.com/3239656/34364177-4476e936-ea51-11e7-9eb2-fa227b8389de.png)

And going on https://mobyproject.org/community or https://mobyproject.org/projects results in `Failed to contact the origin.`

![capture d ecran 2017-12-26 a 15 26 27](https://user-images.githubusercontent.com/3239656/34364178-483ece62-ea51-11e7-8664-0ccbc81859bb.png)

**Comment by krichter722** [comment]
This looks like a failed squid proxy server response. Do you access the the address through squid?

**Comment by ripcurld0** [comment]
@thaJeztah it looks like related to Moby but I can't find the source code in this repository nor in any repository under [Moby](https://github.com/moby).

**Comment by thaJeztah** [comment]
@ripcurld0 the website repository is here; https://github.com/moby/mobywebsite, and an issue was opened about the 403 errors here; https://github.com/moby/mobywebsite/issues/36

I asked @chanezon and @amirmc to have a look (but possibly they haven't seen yet due to the Holidays)

Let me close the issue here, because https://github.com/moby/mobywebsite/issues/36 exists to track it in the website repository, but feel free to continue the conversation 👍

**Comment by dungeonmaster18** [comment]
hey @philippeboyd http://play-with-moby.com has some problems I have notified @marcosnils as he manages pwd, pwm, pwk. He will fix it soon. Thanks for raising the issue.

**Comment by marcosnils** [comment]
@philippeboyd @dungeonmaster18 PWM should be fixed now. Please give it a try and let me know how it goes.
