### ISSUE TITLE
compose file format changes/syntax for kubernates targeted orchestration?

### ISSUE THREAD

**Issue by bitsofinfo** [moby/moby#35916]
Are there any docs covering what elements of compose syntax are or are not supported when targeting kubernates as the orchestration engine?

https://docs.docker.com/docker-for-mac/kubernetes/

**Comment by thaJeztah** [comment]
No, there's no documentation yet for all features that are/are not (yet) supported. Kubernetes support in the CLI is still a preview/experimental feature, and will evolve further over time. Let me close this one because this issue tracker is not really intended as a support forum, and https://github.com/moby/moby/issues/35915 is still open.
