### ISSUE TITLE
How to build a  secure docker image registry?

### ISSUE THREAD

**Issue by zjxpsetp** [moby/moby#35951]
We want to build a secure docker image registry. Which means we don't need to add "--insecure-registry" in /etc/default/docker. And we don't need to import ssl certificate in our system in advance.

So we will apply a domain name, and will sign our ssl certificate with "Symantec Secure Site Pro" or "DigiCert", that is enough?

**Comment by thaJeztah** [comment]
Any valid certificate will do; you can use "let's encrypt" (https://docs.docker.com/registry/configuration/#tls).

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to comment

**Comment by zjxpsetp** [comment]
Thanks so much. I will close this issue
