### ISSUE TITLE
dockerd: http: Accept error: accept unix /var/run/docker.sock: accept4: too many open files; retrying in 1s 

### ISSUE THREAD

**Issue by AndrewYang2046** [moby/moby#35961]
my docker always the following questions. please help me, thanks.

Jan  9 04:10:28 docker01 dockerd: http: Accept error: accept unix /var/run/docker.sock: accept4: too many open files; retrying in 1s
Jan  9 04:10:29 docker01 dockerd: http: Accept error: accept unix /var/run/docker.sock: accept4: too many open files; retrying in 1s
Jan  9 04:10:30 docker01 dockerd: http: Accept error: accept unix /var/run/docker.sock: accept4: too many open files; retrying in 1s
Jan  9 04:10:31 docker01 dockerd: http: Accept error: accept unix /var/run/docker.sock: accept4: too many open files; retrying in 1s
Jan  9 04:10:32 docker01 dockerd: http: Accept error: accept unix /var/run/docker.sock: accept4: too many open files; retrying in 1s
Jan  9 04:10:33 docker01 dockerd: http: Accept error: accept unix /var/run/docker.sock: accept4: too many open files; retrying in 1s
Jan  9 04:10:34 docker01 dockerd: http: Accept error: accept unix /var/run/docker.sock: accept4: too many open files; retrying in 1s
Jan  9 04:10:35 docker01 dockerd: http: Accept error: accept unix /var/run/docker.sock: accept4: too many open files; retrying in 1s
Jan  9 04:10:36 docker01 dockerd: http: Accept error: accept unix /var/run/docker.sock: accept4: too many open files; retrying in 1s
Jan  9 04:10:37 docker01 dockerd: http: Accept error: accept unix /var/run/docker.sock: accept4: too many open files; retrying in 1s
Jan  9 04:10:38 docker01 dockerd: http: Accept error: accept unix /var/run/docker.sock: accept4: too many open files; retrying in 1s

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

**Comment by AndrewYang2046** [comment]
Sorry, this is my docker information,  when this problem,  docker pid fd is 65535,  " ls -l /proc/{docker-pid}/fd |wc -l ", now, I try to upgrade the kernel.

# docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64
 Experimental: false

# docker info 
Containers: 59
 Running: 59
 Paused: 0
 Stopped: 0
Images: 185
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 62.52 GiB
Name: comsrv01
ID: 3X6D:U2LE:RS64:KZNY:L5D7:AYNC:DE7E:MJOD:5S2F:55HJ:MJLP:47KZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 registry.sandpay.com.cn
 127.0.0.0/8
Live Restore Enabled: true

**Comment by thaJeztah** [comment]
How is the docker daemon started? Is it started through `systemd`? Have you customized the default systemd unit file?


When started through systemd, limits are set to `infinity`; https://github.com/moby/moby/blob/dfa4e77d8202f5c682056b59be3111eccddfb09a/contrib/init/systemd/docker.service.rpm#L14-L21. When properly set, limits for the `dockerd` process should look something like;

```bash
cat /proc/$(pidof dockerd)/limits

Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        unlimited            unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             unlimited            unlimited            processes 
Max open files            1048576              1048576              files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       3896                 3896                 signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us        
```


However, you're running a version of Docker that has reached end of life in April of last year, and is no longer maintained. Many fixes have found their way into the code base since, so may resolve your problem.
If you cannot upgrade your docker version, at least be sure to update to the latest patch release for 17.03 (which is [Docker CE 17.03.2](https://github.com/moby/moby/releases/tag/v17.03.2-ce)

Also note that you're using an obsolete version of CentOS (and kernel); CentOS uses a rolling release model, which means that when CentOS 7.2 was released, CentOS 7.1 became obsolete. Docker only is able to support the current version of CentOS (which is 7.4 at this time of writing); see the [installation docs](https://docs.docker.com/engine/installation/linux/docker-ce/centos/#prerequisites);

> To install Docker CE, you need a maintained version of CentOS 7. Archived versions aren’t supported or tested.


The `overlay` storage driver is known to consume a [lot of inodes](https://docs.docker.com/v17.09/engine/userguide/storagedriver/overlayfs-driver/#overlayfs-and-docker-performance), not sure if it's related to this issue, but if you update to a more recent version of CentOS (and kernel), I'd recommend switching o the `overlay2` storage driver, which does not have this problem.


Closing this issue, because both the version of CentOS and Docker are no longer supported, but feel free to continue the conversation.

There's also a number of old issues that mention this error, and could provide information that can be of help;  https://github.com/moby/moby/issues?utf8=✓&q=is%3Aissue+%22too+many+open+files%22+

**Comment by AndrewYang2046** [comment]
@thaJeztah  thanks.

**Comment by jmf0526** [comment]
> Sorry, this is my docker information, when this problem, docker pid fd is 65535, " ls -l /proc/{docker-pid}/fd |wc -l ", now, I try to upgrade the kernel.

> When properly set, limits for the dockerd process should look something like;
> cat /proc/$(pidof dockerd)/limits
> Limit                     Soft Limit           Hard Limit           Units     
> Max open files            1048576              1048576              files     

@blackysy Hi, I'm hitting the same problem, did the max open files limit 65535 (cat /proc/$(pidof dockerd)/limits)  get exceeded in your case? How did you change that limit to 1048576?
