### ISSUE TITLE
my docker icon lost it's eyes

### ISSUE THREAD

**Issue by godcong** [moby/moby#35971]
**Description**

**Steps to reproduce the issue:**
1. install the newest docker
 (Version 17.12.0-ce-win46 (15048)
Channel: stable
0ac7325)
2. start docker

**Describe the results you received:**
the docker status icon on the lower right corner, it's eyes not found

**Describe the results you expected:**
the docker status icon on the lower right corner, saw it's eyes

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true

**Additional environment details (AWS, VirtualBox, physical, etc.):**
window 10 prefessional

**Comment by thaJeztah** [comment]
Yes! I missed the eye as well, but this was a deliberate change made my the design team 😕 

Given that this is an issue specific to Docker for Windows (and Docker for Mac), could you open an issue in the Docker for Windows issue tracker? (perhaps they can convince the design team to add back the eye :smile:); https://github.com/docker/for-win/issues

I'll close the issue here, because the Docker for Windows packages are not maintained in this repository, but feel free to continue the conversation

**Comment by godcong** [comment]
ok
