### ISSUE TITLE
--device not work well when start container with --privileged option

### ISSUE THREAD

**Issue by wenlxie** [moby/moby#35991]
## Description
When I try to run container with command: 
`docker run -it --device=/dev/sdc4:/dev/xvdc --privileged ubuntu /bin/bash`

There is supposed to have device /dev/xvdc inside the container, but I just saw device /dev/sdc4.

When I removed the `--privileged` option,I  can find device `/dev/xvdc`  exists.

## Steps to reproduce the issue
Run container with `--device` and `--privileged` option

## Describe the results you expected
When run container with option `--device` and `--privileged` option,  can see the specified device inside the container

*Docker version*
`1.12.6`

**Comment by thaJeztah** [comment]
Hm, yes, this is because when running with `--privileged`, _all_ devices from the host are available inside the container; https://github.com/moby/moby/blob/f70c715be01f5d5f4a8be4ab1b2c6e1464b478a7/daemon/oci_linux.go#L93-L106


Whereas when running non-privileged, only some devices _plus_ the custom `--device` devices are made available; https://github.com/moby/moby/blob/f70c715be01f5d5f4a8be4ab1b2c6e1464b478a7/daemon/oci_linux.go#L108-L150

Not entirely sure what's best in this case; either produce an error (because you'd already have access to the device you're mapping), or append the custom mapping to the list of devices (but that would mean the device is available _twice_ inside the container; once under it's original name, and once under the custom name.


ping @kolyshkin @justincormack wdyt?

**Comment by justincormack** [comment]
I think it may be best to error in this case.

Do you really need `--privileged`? It may be enough to just use `--cap-add sys_admin` for most things you would want to do with that device.

**Comment by wenlxie** [comment]
@thaJeztah @justincormack 
Thanks for the reply.

@thaJeztah 
For k8s, the host device is abstracted as a `PersistentVolume`,  users  don't know the host device name,  they only know the custom mapping  device name. So when they want to start a  `--priviledged` container, the custom mapping device name missed will make the users doesn't know where to get the host device name.  

> Do you really need --privileged? It may be enough to just use --cap-add sys_admin for most things you would want to do with that device.

@justincormack  Now I use `--cap-add sys_admin` to avoid this issue.
But since we support `--privileged ` option, is it better to have a mapping device name ?

**Comment by thaJeztah** [comment]
Discussing in the maintainers meeting, and while `--privileged` allows you to do the mapping inside the container, we do agree this is not consistent, so we think this should be fixed, and apply the user mapping also when running `--privileged`.

**Comment by wenlxie** [comment]
@thaJeztah Thanks for your reply. 
It is a good news for me that you guys think this is an issue and will fix it.

**Comment by thaJeztah** [comment]
There's nobody working on it yet, so contributions are welcome 😅

**Comment by wenlxie** [comment]
@thaJeztah I can take this.

**Comment by thaJeztah** [comment]
Excellent! Don't think GitHub allows me to "assign" you, but I'll add a "claimed" label :smile:

**Comment by wenlxie** [comment]
PR: https://github.com/moby/moby/pull/36258
