### ISSUE TITLE
Bind mount symlinks not resolved when authorization plugin called

### ISSUE THREAD

**Issue by tsandall** [moby/moby#36020]
Users of authorization plugins want to be able to restrict host paths that can be mounted into containers, however, if a malicious user has host-level access, they can create symlinks to restricted paths and then bind mount the symlink path into the container (which lets them bypass authorization checks.)

Examples:
- https://github.com/open-policy-agent/opa-docker-authz/issues/10
- https://github.com/open-policy-agent/opa-docker-authz/issues/5

**Comment by justincormack** [comment]
This is an issue where all the following apply
(a) A non root user has local access to the Docker host
(b) authz allows any bind mounts
(c) authz allows the user to run containers as root, or (weaker escalations) other users/groups to their own
(d) authz allows bind mounts to paths where the local user has write access

The general recommendations for locking down a system would be not to do (a) or (b) at all, and just to run containers with remote access, and not to allow bind mounts. Bind mounts are necessarily non portable as they depend on host configuration, and substantially reduce the containment of a container by exposing parts of the host filesystem.

In general, if you were to allow both of these, I would recommend (c) only letting the user run containers as their own uid and gid. This means that they can only read files in the container that they can anyway read outside the container, so additional bind mounts are then not an escalation.

It should in general I think also be safe to allow bind mounts the user has no write access to, with a restricted set of paths, even if you allow running as root or another user. However I would generally recommend using volumes (with appropriate filtering of the options, as the local driver can also do bind mounts) in this case anyway rather than bind mounts.

So the question is, if you allow all four of these, whether resolving symlinks before checking paths helps make the system more secure. Also then, whether this should be done by Docker before presenting the request to the authz plugin, or whether the plugin should do this (which OPA would find difficult architecturally). My feeling is that there are risks with this around TOCTOU, as the user has write access and could replace a normal path with a symlink between the checking and the creation of the container. So I think that this would be impossible to implement securely.

On this basis, I don't think we can fix this in a reliable way, and I think the best recommendation is a tighter more restrictive policy instead.

**Comment by tsandall** [comment]
Thanks for the detailed response @justincormack. With OPA (and possibly other authorization plugins) admins can implement more restrictive policies like you described. Having this set of recommendations will be useful in future.

**Comment by justincormack** [comment]
Going to close this, see explanation above.
