### ISSUE TITLE
the ability to mount a volume in a running container

### ISSUE THREAD

**Issue by xtaraim** [moby/moby#36058]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
Can you please provide more details? This is why we have an issue template. A title with no information is sadly not enough to go on.
I'm going to close this for housekeeping purposes, bit if you can update with all the details of your request we can re-open.

Note that if this is a feature request, it may be better to tell What you are wanting to accomplish as an end goal rather than request that for a very specific thing.

Thanks! 🙇‍♂️

**Comment by xtaraim** [comment]
My issues about not getting running configuration on demand..
When it's runs on other projects

**Comment by cpuguy83** [comment]
@xtaraim I'm sorry, I still don't understand :(

Perhaps an example shell script would help?
