### ISSUE TITLE
Proposal: Automatic local image dependency management

### ISSUE THREAD

**Issue by hgl** [moby/moby#36079]
A about a week ago, I [ask a question on the docker forum](https://forums.docker.com/t/how-to-manage-image-dependencies-for-local-development/44408/2) but got no reply.

I kept thinking about it. Today I came up with something, and would like to make a feature request.

To reiterate the issue:

If this builds to an image tagged `production`
```
FROM: golang:alpine
ADD . /go/src/app
RUN go install app

FROM: alpine
COPY --from=0 /go/bin/app /usr/local/bin
```
```
and this to `development`
FROM: golang:alpine
RUN go get github.com/derekparker/delve/cmd/dlv

FROM: production
COPY --from=0 /go/bin/dlv /usr/local/bin
```

When `production` image is changed, docker won't build `development` automatically. I know it's possible to do that with docker hub. But it's not an option when doing local development: pushing and pulling are too slow, and if I'm not wrong, docker hub doesn't cache middle layers, so it might take a long time to build images.

I think the problem can be solved, if docker can internally store the build location of a locally built image. When an image is rebuilt, and a new flag is specified in the cli, it should check to see if any of it descendants are locally build (usually that's the case), and build them automatically using the stored location (if it's still valid). This location is discarded when the image is about to leave the machine (push to hub, docker save, etc)

What do you think?

**Comment by thaJeztah** [comment]
This won’t be possible; docker uses a client/server design: when you run `docker build`, the docker client on your local machine sends the Dockerfile, and all files in the build context to the daemon, and the daemon performs the actual build.

The Dockerfile, and those files used during build are only stored temporarily, and removed after the build completed.

Now, when an image is rebuilt, the daemon won’t have access to files needed to rebuild other images.

Also take into account that multiple clients may be using the same daemon, so if (for example), one of your colleagues rebuilt an image, the daemon would have to trigger _your_ workstation to start a build again.

On Docker hub, this works because all builds are done from GitHub, and the automated builds perform code checkout and builds.

**Comment by hgl** [comment]
I totally forgot about the c/s model docker uses. Thanks for reminding me.

I understand it won't work on the save scale as Docker Hub does.

I'm thinking about a more lightweight approach:

This all happens at local scale. The docker client should have the the knowledge that if an image was locally built, its build location, and image dependencies. When it asks the daemon to build an image, if all its descendants was locally build and a new flag is specified , it should also send those Dockerfiles and build contexts to ask the daemon to build all of them. And if any descendants wasn't locally built, it should only just build the specified image.

This should solve 90% of the local image management problem. The person probably don't own the whole dependency tree, but very likely to own a branch.

**Comment by thaJeztah** [comment]
I think that would add too much complexity; not only would the client now have to keep track of inter-image-dependencies, there's also quite some risks;

(again, taking multiple users into account); 

- Developer A hasn't worked on "child image B" for a while, so has an outdated copy of the repository for that image
- Developer B just updated a fix in "child image B", and rebuilt that image
- Developer A starts working on "parent image A", and builds a new version
- The CLI on developer A's computer sees that "image A" was updated, and thus starts rebuilding "child image B".
- The newer version of "child image B" is overwritten with the fresh build, but because developer A's repository was out of date; it's built with an old version of the code, and re-introduces the bug that was just fixed by developer B.

Having something similar to Docker Hub automated builds, would _require_ something similar to Docker Hub's automated builds; which is a whole infrastructure that can be triggered by web hooks (or other triggers). While not impossible; this is beyond the scope of the daemon's responsibility.

I don't see this being implemented in this repository, so I'll close this issue, but feel free to continue the conversation.
