### ISSUE TITLE
Can not scale/update/exec into swarm containers after 17.12 (ce) upgrade

### ISSUE THREAD

**Issue by sbrattla** [moby/moby#36088]
We just upgraded to 17.12 (CE). After this, our Docker Swarm has been extremely unstable and we're downgrading to 17.09.

Error logs/dmesg shows nothing, but containers seems to just freeze. They do work (that is, they answer requests) , but any attempt to scale up/down, exec into the containers or update services fail. Again, logs/dmesg shows nothing.

We see this same behavior in both of our production environments as well as the staging environment. 

All environments are fully patched / updated Ubuntu 16.04 servers on Hyper-V.

**Comment by cpuguy83** [comment]
@sbrattla Can you provide some extra details? Please make sure to use the issue template that is provided.

Perhaps a `docker service inspect <bad service>` would also help.
What happens when you try to exec?
What happens when you try to scale? Are tasks killed on scale down?

Even if logs don't seem to be saying much, it would be helpful to see as well.
If you can enable debug mode so we can get debug logging from it while you are experiencing the issue this could also provide some important information.

Thanks!

**Comment by sbrattla** [comment]
@cpuguy83 we had to downgrade due to this issue, so I unfortunately do not have that info available anymore. We downgraded to 17.09, as 17.12 would freeze containers which were under heavy load regularly. We couldn't update services either, so we were pretty busy restarting docker as that was the only thing that fixed it.

Even though the issue has not been resolved for us, you should probably close this one as I can't provide any more details.

**Comment by cpuguy83** [comment]
Ok, I'm going to close this one for now then since we don't have enough details to go on.
Note that there are a few issues with 17.11+ that we are tracking that could be causing some of this.... specifically issues with stopping containers, which I could see causing a "freezing" effect that you mentioned.
Hoping to resolve these in 17.12.1.

Let us know if you start seeing this again.
Thanks! 🙇
