### ISSUE TITLE
Routing mesh and overlay networks stopped working

### ISSUE THREAD

**Issue by luanlmd** [moby/moby#36170]
They worked fine when I first setup the cluster, then I lost the nodes one by one.
Tried to reinit the cluster, no change.
Tried to join the cluster with --advertise-addr on the workers, no change.

Service with exposed port is only accessible by the node IP address.
Services can't communicate between nodes.

Docker version 17.06.2-ol, build d02b7ab

**Comment by cpuguy83** [comment]
Please upgrade docker to a supported release.
The latest "stable" is 17.12, but there are a few known issues which you may want to delay going to 17.12 until we have a patch release.
There is also "17.09" which is the previous stable (and just about to be EOL).

There are many fixes related to routing mesh and overlay networking in these updates.
Closing since this is a dup of other issues and is running against an EOL'd engine version, but happy to answer any questions.

In the future it would be very helpful to have the full issue template filled in to assist with troubleshooting.

Thanks! 🙇 👼
