### ISSUE TITLE
Docker container does not change hostname

### ISSUE THREAD

**Issue by D1abloRUS** [moby/moby#36369]
hi, i have trable
docker container run with --network=host don't update hostname after hostname change in host machine

**Steps to reproduce the issue:**
1. docker run -d -it --network=host --restart=unless-stopped alpine cat
2. docker exec -it alpine_container_id /bin/sh
3. hostname - 888
4. change hostname on host to 999 and reboot
5. docker exec -it alpine_container_id /bin/sh
6. hostname - 888
7. ??? why don't change ???

**Describe the results you received:**
hostname in container don't change

**Describe the results you expected:**
hostname in container update to hostname on host

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:	18.02.0-ce
 API version:	1.36
 Go version:	go1.9.3
 Git commit:	fc4de44
 Built:	Wed Feb  7 21:16:33 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.02.0-ce
  API version:	1.36 (minimum version 1.12)
  Go version:	go1.9.3
  Git commit:	fc4de44
  Built:	Wed Feb  7 21:15:05 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 22
 Running: 7
 Paused: 0
 Stopped: 15
Images: 132
Server Version: 18.02.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-112-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.789GiB
Name: d8cb8ac7ddc2-888000
ID: K4WU:HLTZ:BGKN:CUNT:UUU4:MKYY:GSIF:Y37A:TTYK:UMRB:SJJT:YQYN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
When running in host networking, the container (by default) still runs in its own UTS namespace. This was done so that changing hostname inside the container does not change the host's hostname.

Although the hostname of those containers is set to the same hostname as the host when starting the container, the container's hostname won't be updated if the host's hostname changes (or vice-versa).

To also share the UTS namespace with the host, start the container with `--uts=host`.

For example, start two containers with `--network=host`, one with and one without the `--uts=host` option:


```bash
docker run -dit --name container1 --network=host alpine sh
docker run -dit --name container2 --network=host --uts=host alpine sh
```

Check hostname on the host, and inside both containers:

```bash
$ hostname
this-is-my-hosts-hostname
$ docker exec container1 hostname
this-is-my-hosts-hostname
$ docker exec container2 hostname
this-is-my-hosts-hostname
```

Now change the hostname, and do the same again:

```bash
$ hostname foobar
$ hostname
foobar
$  docker exec container1 hostname
this-is-my-hosts-hostname
$ docker exec container2 hostname
foobar
```


I'm closing this issue because this works as expected, but feel free to continue the conversation :+1:
