### ISSUE TITLE
Dockerfile: standardize artefact paths for intermediate stages

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#36414]
https://github.com/moby/moby/pull/35100 rewrote the Dockerfile to use multi-stage builds. Some review-comments were left.

A minor enhancement/cleanup: see https://github.com/moby/moby/pull/35100#discussion_r170234813

Can we standardise on an output path for artefacts? e.g. make all the build-stages output artefacts in (say) `/output/`, then we can simplify all these to

```Dockerfile
COPY --from=foo /output/ /usr/local/bin/
COPY --from=bar /output/ /usr/local/bin/
COPY --from=baz /output/ /usr/local/bin/
COPY --from=bif /output/ /usr/local/bin/
```

**Comment by j-haj** [comment]
Is there a particular output directory you had in mind? Maybe something like `/var/tmp/docker/output` or `/var/cache/docker/output`?

**Comment by thaJeztah** [comment]
It probably shouldn’t go into tmp; we could either go for a top level directory (`/build/`?)

@vdemeester @cpuguy83 any preferences ?

**Comment by cpuguy83** [comment]
That's fine. No need to follow weird linux rules for this for sure.

**Comment by j-haj** [comment]
I am almost done but have a quick question regarding  the build for `registry` -- there are two commands, one that is conditional on the architecture. 
```Dockerfile
RUN set -x \
	&& export GOPATH="$(mktemp -d)" \
	&& git clone https://github.com/docker/distribution.git "$GOPATH/src/github.com/docker/distribution" \
	&& (cd "$GOPATH/src/github.com/docker/distribution" && git checkout -q "$REGISTRY_COMMIT") \
	&& GOPATH="$GOPATH/src/github.com/docker/distribution/Godeps/_workspace:$GOPATH" \
		go build -buildmode=pie -o /usr/local/bin/registry-v2 github.com/docker/distribution/cmd/registry \
	&& case $(dpkg --print-architecture) in \
		amd64|ppc64*|s390x) \
		(cd "$GOPATH/src/github.com/docker/distribution" && git checkout -q "$REGISTRY_COMMIT_SCHEMA1"); \
		GOPATH="$GOPATH/src/github.com/docker/distribution/Godeps/_workspace:$GOPATH"; \
			go build -buildmode=pie -o /usr/local/bin/registry-v2-schema1 github.com/docker/distribution/cmd/registry; \
		;; \
	   esac \
	&& rm -rf "$GOPATH"
```
The current approach is to create two different build directories. I don't see an obvious way around this without specializing the `COPY` source directory.

One alternative, which seems excessive, is to break this instruction into two separate instructions with the second instruction handling the schema-1 case. If we are on the correct platform (amd64, ppc64, or s390x) the build will complete, otherwise it will essentially be empty. The `COPY` instruction would then be broken into two instructions, eg:

```Dockerfile
COPY --from=registry /build/ /usr/local/bin
COPY --from=registry-schema1 /build/ /usr/local/bin
```

On the other hand, it still seems like the binary names would clash (with the schema 1 binaries overwriting the binaries from `registry`). Is the intended result for the schema1 binaries to overwrite in the event they are built?

Any suggestions/thoughts? @thaJeztah @cpuguy83 

Once this is resolved I should have a PR out today.

**Comment by cpuguy83** [comment]
@j-haj We could put stuff in `/usr/local/<from>/` and add that to $PATH.

**Comment by j-haj** [comment]
@cpuguy83 you mean put stuff in `/usr/local/<from>/` on the `dev` image right? What about handling the issue of the registry builds?

If it is not the intent of the arch specific binaries to overwrite the unconditionally built binaries (which I assume is the case, since a different output directory is specified) we will either need separate instructions or a modification of the `/build/` output dir approach. The more I think about it, it seems the separate build instructions might be the cleanest approach.

**Comment by thaJeztah** [comment]
> The current approach is to create two different build directories. I don't see an obvious way around this without specializing the COPY source directory.

Oh, no need to complicate things: it just creates two binaries: one named `registry-v2` and one named `registry-v2-schema1`, which you can see if you build that stage:

```bash
docker build -t registry-stage --target=registry . 

docker run --rm registry-stage ls -la /usr/local/bin 

total 35224
drwxrwsr-x 1 root staff     4096 Apr 12 23:53 .
drwxrwsr-x 1 root staff     4096 Mar 30 22:14 ..
-rwxrwxr-x 1 root root      2478 Mar 30 22:14 go-wrapper
-rwxr-xr-x 1 root staff 18419800 Apr 12 23:53 registry-v2
-rwxr-xr-x 1 root staff 17631416 Apr 12 23:53 registry-v2-schema1
```


So changing those lines to `-o /build/registry-v2` and `-o /build/registry-v2-schema1` should work; after that, the copy should be just;

```Dockerfile
COPY --from=registry /build/ /usr/local/bin/
```

**Comment by j-haj** [comment]
@thaJeztah This is great! I wish I had a good reason why I didn't think to check that... I just finalized the updates and ran a test build without issue. I'll have a PR shortly

**Comment by j-haj** [comment]
The commit crashed and burned on Jenkins. I will investigate
