### ISSUE TITLE
Constant ID for Docker Demon

### ISSUE THREAD

**Issue by challa** [moby/moby#36463]
**Description**

Currently  ID of docker demon (which is provided in  docker info), i see is stored in "/etc/docker/key.json".
in our current environment /etc is in ephemeral disk.

Incase the node crashes ( in our case bosh restores VM automatically after crash) contents of  ephemeral disk are lost  docker demon gets new ID as  new key.json is created.

Is there a way to specify the "ID" while starting docker demon  so that incase "key.json" is recreated it will still have the same ID.
 (or)
is there a way to tell to docker demon to create key.json in particular location ( in our case we can specify location in persistent disk  so that it will survive node crashes)  

Since Docker Node id changes after bosh resurrection, docker swarm (standalone server)  not recognizing the newly resurrected docker node and marking the node as unhealthy  

**Steps to reproduce the issue:**
1. start docker demon.  run the command "docker info and note the  ID
2. stop docker demon and delete the file "/etc/docker/key.json"
3. Start the docker demon again and run the "docker info" it will have different ID 

**Describe the results you received:**
**Describe the results you expected:**
though the result is expected as we have deleted "/etc/docker/key.json", as mentioned in the descrtion we need a way to have constant ID.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
docker/e8d3d814-9287-40be-a99a-d7548b7856ac:~# docker version
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:48:34 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:54:55 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
docker/e8d3d814-9287-40be-a99a-d7548b7856ac:~# docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 14
Server Version: 17.06.1-ce
Storage Driver: aufs
 Root Dir: /var/vcap/store/docker/docker/aufs
 Backing Filesystem: extfs
 Dirs: 110
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local lvm-volume-driver
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-108-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 6.795GiB
Name: ce682da0-6203-465b-a559-a1d0e106cf69
ID: MEQ6:BHRL:U5CC:RKZK:P26Z:GVFN:SWYJ:5RM7:CYE6:XYHX:CKSC:BMRK
Docker Root Dir: /var/vcap/store/docker/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS & Bosh

**Comment by thaJeztah** [comment]
Yes, there is an option to override the path that's used; `--deprecated-key-path`; https://github.com/moby/moby/blob/a80cd04eb5375f0eb7b648e820f694b45983cf2b/cmd/dockerd/config.go#L74-L79

That option was added in https://github.com/moby/moby/pull/32587, but is hidden, because the `key.json` itself was for a feature that's no longer used, and has been replaced with other functionality.

In future, this file / key may be replaced by an "ID" file (see https://github.com/moby/moby/pull/32587#issuecomment-293743854)

I'm closing this issue, because I think the question is answered, but feel free to continue the discussion.

**Comment by challa** [comment]
thanks thaJeztah, this solution works fine for me and thanks for quick response

**Comment by jayeshjk** [comment]
Hi @thaJeztah ,

I am from the same team and we were using `deprecated-key-path` as described in this issue. However, this flag is not supported anymore since v19.03.0, I think. Can you please help in understanding how we can override the key file path. Main issue for us is that path `/etc/docker/key.json` is ephemeral in our environment.
