### ISSUE TITLE
docker push should support --quiet flag

### ISSUE THREAD

**Issue by nathanleclaire** [moby/moby#36655]
I'm on latest Docker for Mac. It would be quite nice if `docker push` had a quiet mode, similar to how `curl` has `-q` to avoid showing the download-in-progress animations. I like the push output for working directly with `docker` but not for shell scripts.

**Comment by thaJeztah** [comment]
A `--quiet` option for `docker pull` is being worked on in https://github.com/docker/cli/pull/882 (not yet for `push`, but I agree we should probably have it for both.

Meanwhile, to suppress the progress bars, the same trick as for `docker pull` could be used as a workaround (see https://github.com/moby/moby/issues/13588#issuecomment-242694121)

```
docker push <image> | cat
```

@nathanleclaire could you perhaps reopen this in the docker/cli issue tracker (https://github.com/docker/cli/issues), because that's where the change will have to be made

**Comment by nathanleclaire** [comment]
Sure!

**Comment by BarakBD-Globality** [comment]
Wouldn't that swallow errors?

**Comment by thaJeztah** [comment]
For easier discovery; this was implemented in https://github.com/docker/cli/pull/2197, and will be in the next release of docker (no ETA yet, but the release after 19.03)

@BarakBD-Globality Hm.. yes, it _should_ still print errors, but looks like there's a bug/oversight there:


Without `--quiet`

```bash
$ docker push nosuchimage
The push refers to repository [docker.io/library/nosuchimage]
An image does not exist locally with the tag: nosuchimage

echo $?
1

$ docker push busybox
The push refers to repository [docker.io/library/busybox]
195be5f8be1d: Layer already exists
[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the docker.io registry NOW to avoid future disruption. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
errors:
denied: requested access to the resource is denied
unauthorized: authentication required

echo $?
1
```

With `--quiet`:

```bash
$ docker push --quiet nosuchimage
docker.io/library/nosuchimage

$ echo $?
0

$ docker push --quiet busybox
docker.io/library/busybox

$ echo $?
0
```

I'll open a bug-report in docker/cli and post the link here

**Comment by thaJeztah** [comment]
Opened https://github.com/docker/cli/issues/2284
