### ISSUE TITLE
Problem with syntaxic coloring of quotes in a Dockerfile

### ISSUE THREAD

**Issue by aeschli** [moby/moby#36695]
- Open a dockerfile in VSCode (uses the latest textmate grammar from https://github.com/moby/moby/blob/master/contrib/syntax/textmate/Docker.tmbundle/Syntaxes/Dockerfile.tmLanguage)
- Write the following and observe to first escaped quote not being registered thus throwing off the syntaxic coloring of the rest of the document : 

`RUN echo //blep.derp.com:9875/:_authToken=\"er99iWoLDerYl666YRUS134YfEghohhrrrr516LwfM=\" >> ~/.npmrc`

Fun fact, if you write the same line twice, the second time both quotes will be registered correctly

_Copied from original issue: Microsoft/vscode#46419_

**Comment by thaJeztah** [comment]
Thanks for reporting; I labeled this with "beginner" and "expert"; perhaps someone wants to have a go at working on this 😅

**Comment by Myeongjoon** [comment]
@thaJeztah @aeschli 
pull-request :  https://github.com/moby/moby/pull/36766.
I think problem is that parsing an escape character in begin end statement does not catch escape characters outside the begin end statement.
So I added an rule abount escape charcter outside the begin end statement.

**Comment by tcd** [comment]
Shameless plug: [vscode-docker-syntax](https://marketplace.visualstudio.com/items?itemName=dunstontc.vscode-docker-syntax)

**Comment by rcjsuen** [comment]
@tcd I see there is a syntax file in that project that may be of use perhaps?

https://github.com/dunstontc/vscode-docker-syntax/blob/d27f017895e3280389e3ce47fd329e427b592237/syntaxes/dockerfile.tmLanguage

#36766 is still open too I see.

**Comment by tcd** [comment]
@rcjsuen That's the [original textmate syntax file from this repo](https://github.com/moby/moby/blob/master/contrib/syntax/textmate/Docker.tmbundle/Syntaxes/Dockerfile.tmLanguage), I used it as a reference when writing a [syntax definition to use in vscode](https://github.com/dunstontc/vscode-docker-syntax/blob/master/syntaxes/dockerfile.tmLanguage.json). Any new changes would be in that second file (`dockerfile.tmLanguage.json`).

I've just added attribution to the readme, as it took me a minute to even figure out where I'd gotten it from.

**Comment by cpuguy83** [comment]
If people want to help review the other PR it'd be welcome.
I don't think the maintainers really know anything about these files.

**Comment by rcjsuen** [comment]
It seems there is a significantly bigger syntax file by @jeff-hykin and @matter123 as seen in the [Better Dockerfile Syntax](https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-dockerfile-syntax) Visual Studio Code extension.

https://github.com/jeff-hykin/cpp-textmate-grammar/blob/c1504c575a1e3f8a20645b8b6ea5cd8f29b319f2/syntaxes/dockerfile.tmLanguage.json

**Comment by jeff-hykin** [comment]
Hey @rcjsuen thanks for mentioning us 😁. The syntax started inside your link (inside the cpp repo) but its actually moved to its own repo [here](https://github.com/jeff-hykin/better-dockerfile-syntax/blob/master/syntaxes/dockerfile.tmLanguage.json)

On top of general syntax improvements, there's a lot more highlighting because I injected the shell syntax inside of the Dockerfile syntax.

In terms of a PR, the Better Dockerfile Syntax is using a beta version of a library Matter123 and I have been working on. As @cpuguy83 mentioned, its tough for the maintainers (really any TextMate maintainers) to understand changes and the Better Dockerfile syntax has a lot of really complicated changes. Once the library is out of beta, grammars should be significantly easier to maintain, and I'll make a PR against the original. However, it could be 6 months before its finished and documented though.
