### ISSUE TITLE
Error trying to remove dead nodes from swarm: raft message is too large and can't be sent

### ISSUE THREAD

**Issue by nvivo** [moby/moby#36792]
I have a swarm with ~1300 nodes, and some enter and leave all the time (about 10/minute).

Since about a week ago, I'm experiencing an error when trying to remove dead nodes with `docker node rm xxxx` from the swarm:

```
Error response from daemon: rpc error: code = Unknown desc = raft: raft message is too large and can't be sent
```

All I see in the logs is the same:

```
Apr  5 12:35:31 ip-10-0-0-10 dockerd[1239]: time="2018-04-05T12:35:31.686809606Z" level=error msg="Error removing node x2nhsvmnzoaq5hp3xqfl2a7dp: rpc error: code = Unknown desc = raft: raft message is too large and can't be sent"
Apr  5 12:35:31 ip-10-0-0-10 dockerd[1239]: time="2018-04-05T12:35:31.687236652Z" level=error msg="Handler for DELETE /v1.37/nodes/x2nhsvmnzoaq5hp3xqfl2a7dp returned error: rpc error: code = Unknown desc = raft: raft message is too large and can't be sent"
Apr  5 12:35:36 ip-10-0-0-10 dockerd[1239]: time="2018-04-05T12:35:36.289574281Z" level=error msg="Error removing node kdmprxylwjmvutsfb9y1f2o17: rpc error: code = Unknown desc = raft: raft message is too large and can't be sent"
Apr  5 12:35:36 ip-10-0-0-10 dockerd[1239]: time="2018-04-05T12:35:36.289644704Z" level=error msg="Handler for DELETE /v1.37/nodes/kdmprxylwjmvutsfb9y1f2o17 returned error: rpc error: code = Unknown desc = raft: raft message is too large and can't be sent"
```

**Comment by nvivo** [comment]
Just some additional info, running `docker node ls | wc -l` counts 14062 nodes, while only 1300 are active. I'm not sure how to recover from this since I cannot remove these nodes even with `docker node rm -f`.

**Comment by cpuguy83** [comment]
What version is this?

**Comment by nvivo** [comment]
Hi. Sorry, I forgot to include this. It happened on 17.12.0-ce. I tried to upgrade to 18.03.0-ce, but the error persisted.

Being a production problem, I found no other way but to bring down the cluster and recreate the swarm.

**Comment by cpuguy83** [comment]
@nvivo Thanks. Is there any chance you saved the old data?

**Comment by dperny** [comment]
There was an update to swarmkit (which I can find the specifics of if you need me to) that circumvented the raft message size limit by breaking up and streaming raft messages. I'm very surprised to see this happening in the latest version. @anshulpundir would know more but he is on a much-needed vacation.

**Comment by dperny** [comment]
@nvivo this isn't relevant to the fix at all, but me and others are really quite curious... what's your use case for 10 nodes/minute joining and leaving the cluster? Is it something CI related?

**Comment by nvivo** [comment]
@dperny sent you an email with some details. In any case, after this problem, we stopped using docker swarm for this specific task so the cluster should now be stable with a dozen nodes or so.

Still, I guess the problem shouldn't happen that way or at least be fixable by some maintenance command.

**Comment by dperny** [comment]
I think I might know what the root cause of this is:

When a swarm node is removed, we add it to a certificate blacklist, so that node ID cannot be reused until its certificate would expire. Those blacklisted certificates live in the Cluster object. I think that this list has just grown and grown to the point where the Cluster object has grown larger than the maximum message size (roughly 1.5 megabytes). 

Some quick napkin math: The cert blacklist is composed of the node ID (a string) and a Timestamp. Altogether it would be about 37 bytes, roughly. There is other information in the Cluster object as well, but ignoring that, if you got to somewhere in the neighborhood of 42,000 successfully removed nodes over the entire lifetime of the cluster, you might break the upper limit.

I can work on a quick program to verify that this is the problem, if you think there's no way you churned through 42,000 nodes already. If it sounds like you might have already hit that limit though, then that's the likely problem. Unfortunately the only way to get the exact cert blacklist size would be to write a custom client for the swarmkit control api, connect through the swarmkit control socket, and count the blacklist size that way, which is a pain in the butt and why I haven't already given you a program to do this.

The bad news is, assuming this is the case (there's a non-zero chance it's some other cause), we don't have an answer for what to do right now. The default certificate expiry time is 3 months, and after it's exceed, when you try to remove a node, it will also remove any expired blacklist entries and allow the message size to get small enough to go through. Other than waiting, though, there's no way to force nodes off the blacklist.

However, there is a more permanent fix:

Assuming a peak throughput of 10 removed nodes per second, just about 70 hours of peak usage is enough to exceed the magic number of 42000 nodes that we think could be causing this. You probably aren't experiencing maximum throughput at all times, so you'll have to figure out how long it takes you to exceed the capacity. Once you have that duration, you can set the swarmkit certificate expiry time to less than that value with this command:

```
docker swarm-ca --cert-expiry <your duration>
```
(docs: https://docs.docker.com/engine/reference/commandline/swarm_ca/#usage)

Swarm will set the expiry time to this value, and when you do a `docker node rm`, if there are any nodes in the blacklist that would have expired, they'll be removed as part of node removal. This will keep the blacklist under the size at which it would prevent removing more nodes.

The side effect is that your cluster will rotate its certificates much more frequently (typically, rotation is every 3 months). On the other hand, if your whole cluster is churning, then it's like that the vast majority of nodes won't ever even live long enough to see a certificate rotation, so it shouldn't be that impactful. 

Again, this is based off educated speculation, so there's a possibility that this RCA is totally wrong, but this is the most likely cause without getting hands directly on your cluster. WDYT?

**Comment by dperny** [comment]
Sounds perfect. Unfortunately, I think this is the best solution you're going to get; a workaround, not a fix. Your case is a bit too corner to spend much time re-architecting to avoid.

Just shorten the certification rotation time to, like, roughly weeks. When we were first developing swarm many moons ago, the cert rotation time was set to like 15 seconds, in order to hammer the hell out of that routine, so it should be pretty bulletproof.

Would you say this is resolved?

**Comment by nvivo** [comment]
That's fine by me. Just to make sure I understand correctly, in order for the workaround to work, we must change this BEFORE hitting that mark, right? Or would that work after the problem happened?

**Comment by dperny** [comment]
Yeah, before you exceed the limit. Any new nodes you create on a cluster will have the new time though, so if you have a live cluster that hasn't fallen apart yet, you can just reduce the rotation time more than you otherwise would have so that they don't push you over the limit.

If the problem has already happened, the all you can do is wait for like 3 months.

**Comment by nvivo** [comment]
Right. I'll close this then. Thanks!

**Comment by eduardolundgren** [comment]
This error is still happening in both `18.03.1-ce` and `18.05.0-ce`.

When trying to rotate the certificate as suggested by @dperny it says:

`Jun 01 01:05:19 ip-172-16-0-128 dockerd[1284]: time="2018-06-01T01:05:19.252697501Z" level=error msg="store error when trying to batch update 24 nodes to request certificate rotation" error="raft: raft message is too large and can't be sent" method="(*Server).rootRotationReconciler" module=ca node.id=281crvu3eez64rnc93x6b4wja`

Any ideas?

**Comment by eduardolundgren** [comment]
Forgot to mention the same error was trigerred by a different action than the initially reported on this issue, in my case it was when creating 1700 services.

`Jun 01 00:39:52 ip-172-16-0-128 dockerd[1284]: time="2018-06-01T00:39:52.220386603Z" level=error msg="Failed to commit allocation of network resources for node rul9pnxcc2hpj3o7eya1redpk" error="raft: raft message is too large and can't be sent" module=node node.id=281crvu`

**Comment by dperny** [comment]
@eduardolundgren the root cause of your issue is very different, but I know what the problem is. I'm opening an issue on swarmkit, docker/swarmkit#2655

**Comment by bluikko** [comment]
Not sure how #45027 from the year 2023 is closed as duplicate of this one that was closed as completed in 2018?
I keep hitting this problem again and again on some clusters.
