### ISSUE TITLE
Overlay dirs without sticky bit

### ISSUE THREAD

**Issue by pabloalvarezcap** [moby/moby#36855]
Hi folks,

I have a postgresql container (also others) with a volume, if I run:
 `df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d \( -perm -0002 -a ! -perm -1000 \) 2>/dev/null`

Note: This command verify no world writable directories exist without the sticky
bit set. If there are any, print it.

It shows me:

```
/var/lib/docker/overlay2/7bac31e2dc96f9b26f6f8c52865871ffcda7c2df2f66d46a07c7d26516358e5e/diff/var/run/postgresql
/var/lib/docker/overlay2/c4aa3a4db5aec34e5ea99bd656b2265fa4e50d25365447d9cdbd47d1d2ad3b83/diff/var/lib/postgresql/data
/var/lib/docker/overlay2/942dffdbe4272cab4be37344eec8a17058d221586a504071a9e7a30a941db121/diff/run/mysqld
/var/lib/docker/overlay2/723fda65fb3cb26c3de3c55c4abc982e0d613af5fe3d668775aba0b134aa8928/merged/var/lib/postgresql/data
d613af5fe3d668775aba0b134aa8928/merged/var/lib/postgresql/datac3de3c55c4abc982e0d
d613af5fe3d668775aba0b134aa8928/merged/var/lib/postgresql/data -le3c55c4abc982e0d
```

Is it ok to set the sticky bit to that directories?

I tried to do it, with the dir `/var/lib/docker/overlay2/723fda65fb3cb26c3de3c55c4abc982e0d613af5fe3d668775aba0b134aa8928/merged/var/lib/postgresql/data`

Then, restart the docker container. And that seems to work.

It's safe to set sticky bit on docker dirs? Do it makes sense?

**Comment by thaJeztah** [comment]
Could you explain a bit more what you're trying to achieve? Also:

> I have a postgresql container (also others) with a volume

You mention you're using a _volume_ for the postgres container, but you're showing that you're touching the overlay filesystem for the container?

**Comment by pabloalvarezcap** [comment]
My docker-compose.yml (I'm using docker-compose) looks similar to:

```
 postgres-server:
    image: postgres:9.6.5-alpine
    restart: always
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./postgres-data:/var/lib/postgresql/data
```

The dir:
`/var/lib/docker/overlay2/723fda65fb3cb26c3de3c55c4abc982e0d613af5fe3d668775aba0b134aa8928/merged/var/lib/postgresql/data`

Well, that's a bind mount.

My question is why it's world writable, is it needed?
Setting the sticky bit does nothing, inside the container /var/lib/postgresql/data/ have not the sticky bit. Setting the sticky bit to $SOMEPATH/postgres-data causes that the /var/lib/postgresql/data/ container has the sticky bit.

Note: $SOMEPATH is the dir where I have the docker-compose.yml, the dir postgres-data, etc...

I'm confused with `/var/lib/docker/overlay2/723fda65fb3cb26c3de3c55c4abc982e0d613af5fe3d668775aba0b134aa8928/merged/var/lib/postgresql/data`, because if I modify it's permissions, nothing happens inside the container.

You can ignore all about sticky bit, it's not the point. I was sleepy and confused, summarizing:
- Why it's world writable, is it needed?
- Why docker creates that directorie, and what is?

**Comment by thaJeztah** [comment]
> The dir:
`/var/lib/docker/overlay2/723fda65fb3cb26c3de3c55c4abc982e0d613af5fe3d668775aba0b134aa8928/merged/var/lib/postgresql/data`
>
> Well, that's a bind mount.

Right, so the `/var/lib/docker/overlay2/..../` directory is the directory that's defined in the image. However, at runtime, that directory is only used as mountpoint for either an (anonymous) volume, or in your case, a bind-mounted directory. The permissions of that directory itself don't really matter at that point, as it's only the mount-point.


> Why it's world writable, is it needed?

It's world-writable, because that's how it's defined in the image; here's the line in the Dockerfile of the image that sets the permisssions: https://github.com/docker-library/postgres/blob/65ed6d7deebc81377154f1c841b1b156c63dfb19/9.6/alpine/Dockerfile#L141-L143

The reason this was changed to be world-writable is explained in https://github.com/docker-library/postgres/commit/3706d4c4562c284ed070286b9fd516151167a40c (https://github.com/docker-library/postgres/pull/253)


> Why docker creates that directorie, and what is?

When running a container from an image (using the overlay/overlay2 storage driver), each layer of the image is extracted in `/var/lib/docker/overlay2/...`, and mounted using `overlayfs`. All the layers combined form the "read-only" part of the container (which is shared between all containers that run from the same image). On top of those layers, a _writable_ layer is mounted for each container: any change you make in the container's filesystem is written to the _writable_ layer of that container.

In this case (as explained above), that directory is only used as a mount-point for another mount (volume or bind-mount), so that the postgreSQL data is not part of the container itself, and can be persisted after the container itself is destroyed.

**Comment by pabloalvarezcap** [comment]
Thank you @thaJeztah for the explanation!

**Comment by thaJeztah** [comment]
You're welcome!
