### ISSUE TITLE
How can I stop the container if the health check fails?

### ISSUE THREAD

**Issue by yeikel** [moby/moby#36850]
I have a use case where I'd like to run a health check on a container and stop the execution of the container if the health check fails. Is this possible?

For example, let's say that I have the following scenario : 

1 - Start the web server
2 - Serve content
3 - Check if the content is served as expected (custom health check where I run end to end tests) 

How can I stop the container and return an exit code?

**Comment by cpuguy83** [comment]
You'll have to orchestrate this using events. See the `/events` API.

For normal containers, all docker does is report the health status, it is up to you to deal with what to do when the container becomes healthy or not healthy.

For swarm services, swarm automatically kills tasks that are unhealthy and creates new ones.

Closing since this is not really an issue.
