### ISSUE TITLE
LCOW: paths containing / are not accepted anymore

### ISSUE THREAD

**Issue by colthreepv** [moby/moby#36932]
Brought this from [original issue](https://github.com/docker/for-win/issues/1411)

### Expected behavior
Able to execute `docker run --rm -v $(pwd):/data alpine ls /data`

### Actual behavior
```
$ docker run --rm -v $(pwd):/data alpine ls /data
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: invalid volume specification: '/c/projects:/data'.
```

### Information
Windows 1709 Pro x64 (build 16299.64)
Docker 17.11.0-ce-win40 (14328)

### Steps to reproduce the behavior
Specified above, there is no support anymore for "bash for windows" style paths

**Comment by thaJeztah** [comment]
I guess the difference between non-LCOW and LCOW is that in the non-LCOW situation, the host-path is mounted from inside the Linux VM in which the daemon runs. On LCOW, there's no Linux VM, but each Linux container gets its own HyperV VM, and bind-mounts are mounted directly from the Windows host (using a remote-filesystem).

Note that LCOW is still experimental, and far from feature-complete.

/cc @jhowardmsft

**Comment by gitfool** [comment]
I think I just hit a similar issue while trying out LCOW from WSL. The following works when using DfW in Linux containers mode (run via the `MobyLinuxVM` on Hyper-V):
```
git clone https://github.com/devlead/TestCakeDocker.git
docker run --rm -it -v "$(pwd)/src:/src" cakebuild/cake:2.1-sdk Cake
```
... but fails when using DfW in Windows containers mode using LCOW for Linux containers; I needed to change it to use `wslpath` as follows:
```
git clone https://github.com/devlead/TestCakeDocker.git
docker run --rm -it -v "$(wslpath -w $PWD/src):/src" cakebuild/cake:2.1-sdk Cake
```
It would be really helpful if DfW behaved consistently regardless of the container mode used.

Note: I also had to configure `wsl.conf` to mount Windows drives to `/` instead of `/mnt` (as shown in [Setting Up Docker for Windows and WSL to Work Flawlessly](https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly#ensure-volume-mounts-work)).

**Comment by thaJeztah** [comment]
Closing this issue, because the experimental LCOW feature has been deprecated and removed in Docker 23.0 and up;

- https://github.com/docker/cli/pull/2798
- https://github.com/moby/moby/issues/39533
- https://github.com/docker/cli/pull/3223
