### ISSUE TITLE
docker ps hangs for ever

### ISSUE THREAD

**Issue by Vishant0031** [moby/moby#36939]
##docker info 
Containers: 38
 Running: 33
 Paused: 0
 Stopped: 5
Images: 316
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.7.3-coreos-r3
Operating System: CoreOS 1185.5.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 48
Total Memory: 125.9 GiB
Name: node-44a84219d5fa
ID: YPL4:NZIZ:PLNA:FYW2:ZAO5:DUDG:VMSW:22UA:VN3Q:SNQP:CVNE:64U5
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/

docker ps hangs for indefinite time.
The docker journal logs repeats this line:
Apr 20 23:08:19 node-44a84219d5fa dockerd[39090]: time="2018-04-20T23:08:19.217845247Z" level=info msg="Container b7d027f3cc131848f1be31b6eb852574041d354057b8fc272722043ab579920d failed to exit within 20 seconds of signal 15 - using the force"

Attached is the go stuck dump (kill SIGUSR1 <dockerd pid>
[docker.sigusr1.txt](https://github.com/moby/moby/files/1944357/docker.sigusr1.txt)

**Comment by thaJeztah** [comment]
This is a very old version of docker that has reached end of life in July 2016, and hasn't been maintained since. 

I highly encourage you to upgrade to a current version of docker, because that version has known vulnerabilities (including container escapes)

I'm closing this issue because this version of docker is no longer supported, but feel free to open a new issue if you encounter this problem on a current version
