### ISSUE TITLE
data-root in cephfs can not start container

### ISSUE THREAD

**Issue by daixiang0** [moby/moby#37012]
**Description**

**Steps to reproduce the issue:**
1. set data-root as /ceph/docker
2. set storage as overlay2
3. start daemon
4. pull centos

**Describe the results you received:**
Then i want to start centos container but failed:
```
[root@dx-app cephfs]# docker run -d centos 
docker: Error response from daemon: error creating overlay mount to /ceph/docker/overlay2/10e13a6596725fd7f807d7fdbbf5fb00dbfc84dcd6b19d45a7166a1e6abf308c-init/merged: invalid argument.
See 'docker run --help'.
```

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:49 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: <unknown>
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.51GiB
Name: dx-app.novalocal
ID: FYBA:I6CE:SEFC:Z5CE:AIVF:C2TH:T66N:IKE2:MB4W:HCU6:OQ3X:HZUP
Docker Root Dir: /ceph/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://dftbcros.mirror.aliyuncs.com/
Live Restore Enabled: false
```
I test data-root with no-ceph path, it works.
Does it mean docker can not support setting ceph path as data-root?

**Comment by daixiang0** [comment]
Change to 18.03, still failed

**Output of `docker info`:**
```
[root@dx-app cephfs]# docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:20:16 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:58 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by thaJeztah** [comment]
overlay and overlay2 is currently only supported (and tested) on top of `ext4` and `xfs` (see the [prerequisites section](https://docs.docker.com/storage/storagedriver/overlayfs-driver/#prerequisites)); other filesystems _may_ work but are not tested, or guaranteed to work. 

cephfs has some [differences from POSIX](http://docs.ceph.com/docs/jewel/cephfs/posix/), which may well be related, but again; it's not tested or supported currently.


Closing this issue because Cephfs is currently not supported, but feel free to continue the conversation

**Comment by daixiang0** [comment]
Is there any plan about docker on Cephfs?

**Comment by thaJeztah** [comment]
No work has been done to support this; but this repository is open-source, so if a contributor wants to work on it (if possible; if Cephfs is able to support the things that are needed for the storage-drivers to work), such a contribution is always welcome. I would recommend that contribution to be made to the containerd project, because in future, image-management will be delegated to containerd (https://github.com/containerd/containerd)

**Comment by qhaas** [comment]
data-root on ceph with the [`fuse-overlayfs` storage driver](https://docs.docker.com/engine/storage/drivers/select-storage-driver/) seems to be working now
```
$ cat /etc/redhat-release 
Rocky Linux release 9.4 (Blue Onyx)
$ docker version
Client: Docker Engine - Community
 Version:           27.2.1
...
 OS/Arch:           linux/amd64
...
$ ceph --version
ceph version 16.2.15 (618f440892089921c3e944a991122ddc44e60516) pacific (stable)
```
But, it is SLOW
