### ISSUE TITLE
Cannot disable userland-proxy and go with hairpin

### ISSUE THREAD

**Issue by izanagi1995** [moby/moby#37163]
**Description**

**Steps to reproduce the issue:**
1. Edit docker configuration (at /etc/default/docker for me) and add `--userland-proxy=false`
2. Restart docker
3. Launch a container with binded ports
4. Remove the iptables rules for this container

**Describe the results you received:**
The container is still reachable after deleting the iptables rules. Also there is a process "docker" listening on the binded port

**Describe the results you expected:**
Userland proxy should be not running so removing the iptables rules should break the connection to the container.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:57:47 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:57:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 25
 Running: 0
 Paused: 0
 Stopped: 25
Images: 17
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 75
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.5 MiB
Name: konduktor
ID: 4KLU:DPTV:RRDY:HR5M:WZXH:IXC7:CJD4:OA4T:AHJA:ZOWG:CG4F:VJJ2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Cluster Store: consul://HIDEIP
Cluster Advertise: HIDEIP
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by arm64b** [comment]
Yes, bad tag, not `platform/arm` 🦀

**Comment by izanagi1995** [comment]
**Output of iptables-save with rules only targeting my container **
```
*security
*raw
*mangle
*nat
-A POSTROUTING -s 172.18.0.5/32 -d 172.18.0.5/32 -p tcp -m tcp --dport 8080 -j MASQUERADE
-A DOCKER -p tcp -m tcp --dport 8080 -j DNAT --to-destination 172.18.0.5:8080
*filter
-A DOCKER -d 172.18.0.5/32 ! -i docker_gwbridge -o docker_gwbridge -p tcp -m tcp --dport 8080 -j ACCEPT
```
Deleting those rules will not affect the container which stay available from internet

**Comment by izanagi1995** [comment]
I finally found a solution.
* Run container without binding ports but just exposing them
* Apply iptables rules listed in previous post

**Comment by izanagi1995** [comment]
Maybe keep this up for future readers (maybe document this as "Working with iptables and docker manually" ?)

**Comment by izanagi1995** [comment]
Also, is it a bug that with port binding (with `-p`) seems to ignore iptables

**Comment by polarathene** [comment]
Looks like this can be closed?

Not much engagement in the issue over the years and reading through it seems there was a misunderstanding?

There was a [recent `userland-proxy` fix](https://github.com/moby/moby/pull/44803), but it doesn't seem related to the issue described here (_which wanted to disable `userland-proxy`, but also remove the `iptables` rules that are added from doing so?_).

---

> document this as "Working with iptables and docker manually" ?

These docs may not have existed at the time, but probably what you were asking for?:

https://docs.docker.com/network/iptables/

> is it a bug that with port binding (with `-p`) Docker seems to ignore iptables?

Publishing ports bypasses firewall rules due to how Docker manages `iptables`. It would apparently be better if Docker would migrate to `nftables` which is the successor, instead of legacy `iptables`. Not much movement on that front though AFAIK?

Often this seems to be an issue for users with a firewall active such as `ufw` and `firewalld`. The Docker forwarding rules take priority, before any filtering rules applied to allow / deny traffic. [`firewalld` has integration](https://docs.docker.com/network/iptables/#integration-with-firewalld) via zones, but you need to configure that, it's not the default. There is advice for adjusting UFW config, but it often seems to cause other issues.

- For IPv6, it is a bit easier. You can have `ip6tables: false` (default) and add firewall rules to open ports.
- IPv4 is a bit trickier when you're relying on public IPv4 to private IPv4 addresses via NAT. I am not aware of any major issues with publishing ports with `-p`, if you do not want them to be reachable via the public IP address, you can be more explicit and bind to localhost interface `127.0.0.1:80:80` for example.

**Comment by neersighted** [comment]
I do agree that this issue stems from a misunderstanding of how networking is configured; they may be some docs work here, but on the other hand, this issue is quite stale at this point.

I think we'll close this for now, but feel free to continue relevant discussion here/identify anything potentially actionable for a new issue. Networking definitely isn't in the best state right now, but work is actively being done to improve it; better port mapping and firewall multi-tenancy is very much part of the focus.
