### ISSUE TITLE
cannt start docker service when use swarm

### ISSUE THREAD

**Issue by philiahe** [moby/moby#37170]
![image](https://user-images.githubusercontent.com/8486693/40704034-a95bc5a0-6419-11e8-83fc-fc07b489bfd0.png)

**Comment by thaJeztah** [comment]
Yes, looks like the service failed to start for some reason; unfortunately, systemd doesn't print any useful information in that situation, and you'll have to check the logs to see what the reason is it's failing;

Can you check the logs for the `docker` service? For example, to view the last 100 log-entries;

```
journalctl -u docker.service -n 100
```

Also;

- was this a fresh installation, or an existing machine?
- what distro and distro-version are you running?

**Comment by thaJeztah** [comment]
Closing as this went stale
