### ISSUE TITLE
docker run does not forward kill signal when TTY not available

### ISSUE THREAD

**Issue by aalexgabi** [moby/moby#37200]
Real world use-case: running Docker container with tests inside CI with:
```
docker run -ti my-image my-test-script
```

The CI does not support TTY so I get:
```
the input device is not a TTY
stdin: is not a tty
ERROR: Job failed: exit status 1
```
How do I propagate a SIGTERM up to the container entrypoint when I don't have a TTY?

My desired process tree:
```
ci-runner
  bash
    docker run -ti my-image my-test-script
```

CI runner will send a SIGTERM to the bash script that will propagate to the docker run but since there is no TTY support it can't run with -ti.

This works in my terminal.

This subject was broadly discussed here: #2838 but without taking in consideration the lack of TTY in some cases.
Also posted this comment here but I don't think it gets any visibility: https://github.com/moby/moby/issues/2838#issuecomment-381190599

**Comment by Vanuan** [comment]
Don't see how sending signals to processed is related to TTY presence.

Here's a setup which I have:

```
function error {
    ret=$?
    set +e
    echo "Cleaning up..."
    docker-compose stop
    docker-compose down -v
    set -e
    exit $ret
}
trap 'error' EXIT
trap 'error' SIGTERM


cat > docker-compose.yml <<EOF
version: '2.2'
services:
  my-test-service:
    image: my-image
    init: true
EOF

docker-compose run --rm --no-deps my-test-service
```

If your test service is properly setup to properly respond to SIGTERM signal it should work reliably.

**Comment by Vanuan** [comment]
@aalexgabi 
Essentially you are saying docker run does not forward signals when you don't provide `-it` options.
Let's investigate this:

```
#!/bin/sh
catch_signal () {
  echo "Ctrl+C signal catched"
  echo "Exiting"
  exit 0
}

trap 'catch_signal' SIGINT

while true; do
  sleep 1
done

```

If you run it with `-ti` it works as expected:

```
$ docker run -ti -v $(pwd)/myScript.sh:/run.sh alpine sh -c /run.sh
^CCtrl+C signal catched
Exiting
$ 
```

But if you try to run it without `-ti` options and try to send kill signal, it won't work:

```
$ docker run --name test --rm -v $(pwd)/myScript.sh:/run.sh alpine sh -c /run.sh
```
Ctrl+C obviously doesn't work, since docker doesn't forward input from your terminal to docker daemon (that's what these `-it` options are actually doing).

Here's how to send a signal to a container process:

```
$ docker kill -s INT <container_id>
```

What this will do is that it sends SIGINT to a process with pid 1.

Essentially, this is equivalent of this:

```
docker exec test kill -SIGINT 1
```

As you may notice it won't work, but why?
Let's look at process tree:

```
$ docker exec -ti test pstree -p 1
sh(1)---run.sh(7)---sleep(61)
$ docker exec -ti test ps
PID   USER     TIME   COMMAND
    1 root       0:00 sh -c /run.sh
    7 root       0:00 {run.sh} /bin/sh /run.sh
   69 root       0:00 sleep 1
   70 root       0:00 ps
```

Oh, so what happens is that `sh -c /run.sh` will spawn your script in a subshell.
So you're sending signal not to your script, but to outer shell with pid 1. And it will rightfully (according to UNIX spec PID 1 has a special behavior) will not pass received signal to its children.

What you want to do is to run your script directly (make sure you have a proper shebang line included) and it will work as expected even without `-ti`:

```
$ docker run --rm --name test -v $(pwd)/myScript.sh:/run.sh alpine /run.sh  
```
So if you send a signal to it should work:
```
# (in one terminal)
$ docker kill -s INT test

# (in another terminal)
$ docker run --rm --name test -v $(pwd)/myScript.sh:/run.sh alpine /run.sh  
Ctrl+C signal catched
Exiting
```

Notice though that Ctrl+C will not work, as it's just a key combination, doesn't have anything to do with sending a signal. So if jenkins works by typing Ctrl+C to a terminal (which you claim it doesn't have) container won't receive a signal. What jenkins should do is actually send a signal to a process it created:

```
$ ps aux|grep docker
john      6368 11.0  0.2 413516 26968 pts/7    Sl+  20:29   0:00 docker run --rm --name test -v /home/john/myScript.sh:/run.sh alpine /run.sh

$ kill -SIGINT 6368

# (in another terminal)
$ docker run --rm --name test -v $(pwd)/myScript.sh:/run.sh alpine /run.sh  
Ctrl+C signal catched
Exiting
```

As you can see, your claim is wrong. There's no bug in docker. There's a bug in your container image.

**Comment by aalexgabi** [comment]
Basically the reason for this is the un-intuitive way bash forwards signals to child processes. Bash will ignore signals until child processes finish.

Detailed information here:
* https://unix.stackexchange.com/questions/146756/forward-sigterm-to-child-in-bash
* http://veithen.github.io/2014/11/16/sigterm-propagation.html

@Vanuan You can close this. Again sorry for wasting your time.

**Comment by Vanuan** [comment]
Issue can be closed only by owner or reporter.
