### ISSUE TITLE
FTBFS on MIPS: undefined: unix.SIGSTKFLT

### ISSUE THREAD

**Issue by onlyjob** [moby/moby#37300]
17.12.1 FTBFS on _mips_ as follows:

~~~~
# github.com/docker/docker/pkg/signal
src/github.com/docker/docker/pkg/signal/signal_linux.go:35:14: undefined: unix.SIGSTKFLT
~~~~

**Comment by thaJeztah** [comment]
Are you still seeing this on current master? Docker 17.12.x reached EOL in March

**Comment by onlyjob** [comment]
But `signal_linux.go` hasn't change and it is identical in 17.12.1 and 18.05.0.

Even in _master_ `unix.SIGSTKFLT` is still used unconditionally:
 https://github.com/moby/moby/blob/master/pkg/signal/signal_linux.go#L35

History of that file suggests that the problem is still present on _master_:
 https://github.com/moby/moby/commits/master/pkg/signal/signal_linux.go

---

By the way where EOL information is published for "ce" edition?
17.12.1 has been released on Feb 28 and in March it already reached EOL?

 Is there LTS edition? Only one month of support is hardly meaningful...

**Comment by onlyjob** [comment]
This problem exist on 18.03.1 as well.

Look how _runc_ addresses this problem by having two arch-specific files:

https://github.com/opencontainers/runc/blob/master/signalmap.go
https://github.com/opencontainers/runc/blob/master/signalmap_mipsx.go

**Comment by justincormack** [comment]
We don't have any support for MIPS. Due to the weirdnesses of Linux MIPS, this is probably not the only thing that is needed. At one point Imagination expressed an interested in doing a port, but they did not follow up. Feel free to open PRs for master to fix issues, but we don't have CI for MIPS, and I no longer have any MIPS machines so can't help.
