### ISSUE TITLE
docker swarm service scale down, which replica will be terminated?

### ISSUE THREAD

**Issue by bingzhang** [moby/moby#37383]
Hello:

I am curios to know, a swarm service with 5 replica, and 3 of 5 are running jobs, and 2 are idle. If I scale down from 5 to 3, then that 2 idles will be terminated or just random 2 of replica will be terminated?

Regards.

**Comment by cpuguy83** [comment]
It isn't really tracking if a task is idle or not so it will be random.

Note that it sends a shutdown signal to the container process (whatever is defined as part of the image, or SIGTERM by default). It's up to the container process to deal with this correctly to allow running jobs to complete, although there is a timeout that when hit docker will send a SIGKILL.... you can also configure this timeout.

Closing this since it isn't really an issue.
