### ISSUE TITLE
ERROR: Error: Status 400 trying to pull repository netcool-probe-email: "{\n  \"errors\" : [ {\n    \"status\" : 400,\n    \"message\" : \"Unsupported docker v1 repository request for 'hyc-nco-integrations-dev-docker-local'\"\n  } ]\n}"

### ISSUE THREAD

**Issue by maryjomcguinness** [moby/moby#37428]
**Description**
I am seeing the following error when trying to run docker-compose up - 

```
ERROR: Error: Status 400 trying to pull repository netcool-probe-email: "{\n  \"errors\" : [ {\n    \"status\" : 400,\n    \"message\" : \"Unsupported docker v1 repository request for 'hyc-nco-integrations-dev-docker-local'\"\n  } ]\n}"
```

However we are using docker-compose V3, could you please help to resolve this?

**Output of `docker version`:**

```
docker-compose version
docker-compose version 1.22.0-rc2, build 6817b533
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Output of `docker info`:**

```
docker info
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 0
Server Version: 17.05.0-ce
Storage Driver: devicemapper
 Pool Name: docker-253:2-341956418-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 42.95GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 16.79GB
 Data Space Total: 107.4GB
 Data Space Available: 41.67GB
 Metadata Space Used: 9.298MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.138GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /home/docker/devicemapper/devicemapper/data
 Metadata loop file: /home/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.2.3.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 23.39GiB
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
`netcool-probe-email` is not a repository on Docker Hub; https://hub.docker.com/_/netcool-probe-email/; are you trying to pull from a local registry?

This error message

```
Unsupported docker v1 repository request for 'hyc-nco-integrations-dev-docker-local'
```

Also looks like there's possibly some custom registry running (is `hyc-nco-integrations-dev-docker-local` is the name of your computer?).

Finally, note that your version of Compose is up-to-date, but the version of Docker (17.05) reached end of life a long time ago, and hasn't been maintained since (it reached EOL over a year ago)

With the current information in this issue, I don't think there's a lot that can be done here. Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because of the above, but feel free to continue the conversation 👍
