### ISSUE TITLE
does docker support multiple services runs in one container with swarm mode?

### ISSUE THREAD

**Issue by junneyang** [moby/moby#37476]
does docker support multiple services runs in one container with swarm mode?

example:
one container can expose multiple services and can be discovery by docker
is it possible?

thanks!

**Comment by cpuguy83** [comment]
@junneyang Docker starts exactly 1 process. That process could be anything from a single service or it could be as complex as a full init system (please don't run systemd in a container though, there are better alternatives for this use case).
Basically it's up to the PID 1 of the container to manage whatever services you want to start.

I'm going to close this since it's not really an issue.
Thanks!
