### ISSUE TITLE
Docker UCP website can't be reached

### ISSUE THREAD

**Issue by ackris** [moby/moby#37556]
Hi

**The details:**

`uname -r: 3.10.0-693.5.2.el7.x86_64`
`OS: Red hat 7.4 (maipo)`

```
Client: Docker Enterprise Edition (EE) 2.0
 Version:       17.06.2-ee-10
 API version:   1.30
 Go version:    go1.8.7
 Git commit:    66261a0
 Built: Fri Apr 27 00:38:41 2018
 OS/Arch:       linux/amd64

Server: Docker Enterprise Edition (EE) 2.0
 Engine:
  Version:      17.06.2-ee-10
  API version:  1.30 (minimum version 1.12)
  Go version:   go1.8.7
  Git commit:   66261a0
  Built:        Fri Apr 27 00:40:03 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

We have successfully installed Docker EE, and we have also successfully spawned a UCP container. But i'm unable to access UCP via browser. When I tried to do it, all i'm getting is '`The site can't be reached`'. 

**PS**: We are in a corporate environment. Is it related to corporate certificates in browsers?

**Comment by thaJeztah** [comment]
Thanks for reporting; this issue is about Docker Enterprise Edition / UCP, which is not maintained in this repository (this repository is for the open source Moby Engine); I recommend contacting support@docker.com for support questions related to Docker's commercial products.


I'll close the issue here, because this issue tracker is not the correct location for this, but feel free to continue the conversation
