### ISSUE TITLE
Service Task Status should not have exit code when task is running

### ISSUE THREAD

**Issue by johnflavin** [moby/moby#37577]
**Description**

I have noticed that, while a service has a task that is running, that task has a status with `ContainerStatus.ExitCode: 0`. That is a misleading value. 

I believe `0` is being used here as a stand-in for `null` (or `nil`). But those values are distinct. A `null` value (or `nil`, or no value at all) should mean "the container has not yet reported an exit value". Any non-`null` value should mean "the container *has* exited, and its process has reported this exit code". `0` in particular is a special value because it is the only value indicating success.

**Steps to reproduce the issue:**
1. Create a service with a command that will continue running for at least a few seconds.
```
$ docker service create --name service_name busybox:latest sleep 120
eeest5s97viw1qzoy8pvllbkm
overall progress: 1 out of 1 tasks
1/1: running   [==================================================>]
verify: Service converged
```
2. Get the task status. I am not aware of a way to do this with the CLI, so I use the API.
```
$ curl -s --unix-socket /var/run/docker.sock http://localhost/tasks?filters%3D%5B%22service%22%3A%22service_name%22%5D | jq '.[].Status'
{
  "Timestamp": "2018-08-01T15:41:54.007243253Z",
  "State": "running",
  "Message": "started",
  "ContainerStatus": {
    "ContainerID": "a14116edc1b8e8222efde70af7b7531bb71c702b813e5a8d81f848b8dfa1013c",
    "PID": 6947,
    "ExitCode": 0
  },
  "PortStatus": {}
}
```

**Describe the results you received:**
The task is in `"State": "running"` but the `"ContainerStatus.ExitCode"` value is `0`.

**Describe the results you expected:**
Either no `"ExitCode"` property within `"ContainerStatus"`, or one with a `null` value.

**Output of `docker version`:**

```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:11:02 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:09:05 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by thaJeztah** [comment]
Thanks for opening this ticket; I see that both for Swarm services, and for containers, this field is not a pointer, so currently is not nullable;

https://github.com/moby/moby/blob/5a68e2617da4b18ea4bae9fb3205026bb541e8d4/api/types/swarm/task.go#L180-L185


and

https://github.com/moby/moby/blob/53683bd8326b988977650337ee43b281d2830076/container/state.go#L30


While I do agree that setting this field to `nil` would make sense (instead of requiring to look both at the `State` (to be exited) _and_ checking the exitcode), changing that field to be nullable would be likely a dangerous change (could break backward compatibility, and code not expecting `nil` values could panic / null-pointer-exceptions).

I'll discuss this with other maintainers to check their opinion, but it may be too late to change this.

**Comment by thaJeztah** [comment]
We discussed this in the maintainers meeting, and while we agree that having a pointer for this (so that the field could be `nil`) would've been better; changing now would be too much of a breaking change (and risks involved). For that reason, we decided to not change this now. (sorry! 😅 )
