### ISSUE TITLE
Could not mount /dev  with --init flag

### ISSUE THREAD

**Issue by cofyc** [moby/moby#37645]
**Description**

If a program need to mount /dev into container (e.g. used to discovery devices), it cannot work with `dockerd --init` flag.

**Steps to reproduce the issue:**
1. Enable --init flag 
2. Run a container with -v /dev:/dev
3.

**Describe the results you received:**

```
starting container process caused "exec: \"/dev/init\": stat /dev/init: no such file or directory": unknown
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 34
 Running: 7
 Paused: 0
 Stopped: 27
Images: 261
Server Version: 18.03.1-ce
Storage Driver: aufs
 Root Dir: /data/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 425
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-116-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 7.779GiB
Name: dev
ID: X75A:VH7C:4CHW:ZAP7:RFJP:XQ3J:FBTE:FJUD:OGOH:WOYG:37SI:YAWX
Docker Root Dir: /data/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: cofyc
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true

WARNING: No swap limit suppor
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Thanks for reporting! From a "technical" perspective, this is expected, but possibly there's a way to either work around this, or (at least) handle the error-condition more gracefully.

When using the `--init` option, the init binary is bind-mounted into the container at `/dev/init`. However, given that in the situation described `/dev` as a whole is bind-mounted from the host, that bind-mount will mask the `/dev/init` bind-mount, and because of that, the mounted `init` binary cannot be found.

Just thinking out load what options there are;

- detect the conflict situation and refuse to create/start the container (set `--init=false` for that container, and make sure the container/image itself has a proper init if needed)
- as above, but print a warning, and automatically disable `--init` (could be useful in situations where `--init` is enabled on a daemon level, so automatically used for all containers by default
- (detect the situation and) bind-mount the `/dev/init` binary _after_ doing other bind-mounts. This would resolve most situations, but is potentially risky due to nested mounts, and also would mask any `init` binary that's bind-mounted as part of `/dev/`.


ping @kolyshkin @cpuguy83 @crosbymichael any ideas?

**Comment by kolyshkin** [comment]
I remember there is mounts sorting implemented in daemon so that the "deeper" mounts are performed after "shallower" ones. That code is complex and this might be a corner case it fails to handle correctly.

I also remember /dev is a special case for whatever reason; this might be why it's not working.

I'll take a look.

**Comment by kolyshkin** [comment]
Simplest reproducer:
 
> $ docker run -d -v /dev:/dev --init busybox top
> 088c96808c683077f04c4cc2711fddefe1f5970afc085d59e0baae779745a7cf
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"/dev/init\": stat /dev/init: no such file or directory": unknown.

**Comment by kolyshkin** [comment]
This comes from `setMounts` function, and is even documented in the code comments (**check line 466**):
https://github.com/moby/moby/blob/ba5c92f1bf78d884bcca1b8a4443bdf0f09fb0e6/daemon/oci_linux.go#L458-L469

So, two solutions are possible:

1. Reject `--init` and `-v /dev:/dev` combination as non-working
2. Make an exception for `/dev/init`.

**Comment by cpuguy83** [comment]
I don't see how we can do `/dev/init` here outside of making sure that `/dev` is a private mount.

**Comment by kolyshkin** [comment]
Proposed fix: https://github.com/moby/moby/pull/37665

> I don't see how we can do /dev/init here outside of making sure that /dev is a private mount.

Yeah, we should probably check that /dev mount is [r]private and reject this whole thing otherwise.

**Comment by cpuguy83** [comment]
I wonder if we can put init somewhere else that's less common to mount... like `/sbin/dockerinit` or something.

**Comment by thaJeztah** [comment]
Guess that could work yes.

My main concern with the issue reported here is not so much with a user manually setting `--init` on a container (then it's easier to report/resolve),  but for situations where `--init` is set as default on the daemon.

**Comment by cofyc** [comment]
Yes, `--init` is set as default on the daemon in our k8s clusters.

**Comment by cofyc** [comment]
In my scenario, `/dev` is mounted private. I'll try [this fix](https://github.com/moby/moby/pull/37665), thanks!

> I wonder if we can put init somewhere else that's less common to mount... like `/sbin/dockerinit` or something.

I think it's a good idea. Rarely we need to mount anything into `/sbin`, and if users need to mount outside binaries into container. There are many alternative ways to do, mount into `/bin`, `/usr/{bin,sbin}`, `/usr/local/{bin,sbin}` or `/opt`.

**Comment by kolyshkin** [comment]
@cofyc as a side question, why are you mounting the whole `/dev` inside container? I am asking because this is a great security risk; perhaps it makes more sense to mount some specific devices that you need rather than the whole /dev.

**Comment by cofyc** [comment]
@kolyshkin 

hi, in Kubernetes we are developing a [local volume provisioner](https://github.com/kubernetes-incubator/external-storage/tree/master/local-volume) which is used to discover local devices and configure them as local block persistent volumes for later use.

Typical use case: Administrator attaches a disk to a node (e.g. `/dev/sdc1`) and link it to a directory (e.g. `/mnt/disks/sdc1`) to indicate it's ready to use, then local volume provisioner can find and follow the link to access device under `/dev` to get its size and configure it in Kubernetes.

local volume provisioner runs in privileged mode, but new attached devices after container has started [are not reflected at `/dev` path](https://github.com/kubernetes-incubator/external-storage/issues/783), so we need to mount the whole `/dev`.

**Comment by kolyshkin** [comment]
@cofyc thanks for your explanation. I am not quite sure about it but it looks like you'd be bit more secure doing something like this: https://docs.docker.com/edge/engine/reference/commandline/create/#dealing-with-dynamically-created-devices---device-cgroup-rule

**Comment by cofyc** [comment]
Thanks! Didn't know it, I'll take a look!
