### ISSUE TITLE
resize docker volume

### ISSUE THREAD

**Issue by AlaaAttya** [moby/moby#37858]
are there any way to resize a docker volume?

all I can see is that I can create, list, get or delete volumes

**Comment by thaJeztah** [comment]
The default ("local") does not restrict the size of volumes; all it does is create a local directory (somewhere in `/var/lib/docker/volumes`) to be used as storage location, and bind that directory inside containers that use the volume.

Possibly there's other volume driver plugins that allow you to define a size, but I don't know which ones do ☺️

Closing this issue, because this is not a bug, and probably should answer your question, but feel free to continue the conversation
