### ISSUE TITLE
Docker CLI allows same option via -o to be specified multiple times

### ISSUE THREAD

**Issue by imran-ansari** [moby/moby#37917]
**Description**
Docker CLI allows same option via -o to be specified multiple times

**Steps to reproduce the issue:**
Execute the below command which has "TestOption" as repeated option:
docker volume create -d xyz --name TestVolume -o TestOption=TestValue1 -o TestOption=TestValue2

**Describe the results you received:**
In the above case, Docker CLI doesn't complain despite the option "TestOption" being repeated. The driver plugin receives "TestOption=TestValue2" - the last specified option.

**Describe the results you expected:**
Docker CLI should disallow specification of same option multiple times via -o

**Additional information you deem important (e.g. issue happens only occasionally):**
---

**Output of `docker version`:**
```
Docker version 17.06.2-ee-16, build 9ef4f0a
```

**Output of `docker info`:**

```
Containers: 14
 Running: 1
 Paused: 0
 Stopped: 13
Images: 1247
Server Version: 17.06.2-ee-16
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 786
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 462c82662200a17ee39e74692f536067a3576a50
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-21-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 62.79GiB
Name: xxxxxxxxxxxxx
ID: OWR5:HJYY:KAO5:H6GT:2NEU:JHHQ:YZ3G:67GJ:BKRV:SZ4P:Q3WJ:FDXS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: xxxxxxxxx
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical

**Comment by olljanat** [comment]
@imran-ansari can you try if behaviour is still same on Docker 18.09?
It can be that multiple **-o** options are allowed because some drivers might support multiple options.

**Comment by olljanat** [comment]
Derek add label: status/more-info-needed

**Comment by thaJeztah** [comment]
I think this is due to how the CLI framework (https://github.com/spf13/cobra and https://github.com/spf13/pflag) handle these options. (By default) it accepts flags multiple times, and latter values overwrite previous values.

This is indeed somewhat confusing, but given that we had this behaviour for a very long time, changing this would be a breaking change (I know there's users that use this as a feature, where they set default options, and (optionally) override those in scripts).

I'm closing this ticket because of the above, but suggestions are welcome (but probably better opened in the https://github.com/docker/cli repository, which is where the CLI now lives)
