### ISSUE TITLE
Docker run command not working..Some Process id is stopping it to run the container.

### ISSUE THREAD

**Issue by viselvar** [moby/moby#37924]
**Description**

Docker is not able to run the container from images.
Docker run command not working on docker installed on amazon ubuntu EC2 instance.

**Steps to reproduce the issue:**
1. Pull any image such as hello-world
2.run that image using docker run command

**Describe the results you received:**

Error response from daemon: unable to find "pids" in controller set: unknown.
ERRO[0000] error waiting for container: context canceled

**Describe the results you expected:**
hello from the docker(success message)

**Output of `docker version`:**

```
Docker version 18.06.1-ce, build e68fc7a215d7133c34aa18e3b72b4a21fd0c6136

```

**Output of `docker info`:**

```
Containers: 8
 Running: 0
 Paused: 0
 Stopped: 8
Images: 10
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.70-67.55.amzn1.x86_64
Operating System: Amazon Linux AMI 2018.03
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.853GiB
Name: ip-172-31-0-234
ID: AGTD:BUGU:RDRN:CSHC:INSH:HCMG:QFYT:OUNC:NCVZ:UDAM:PJYS:3ZQM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):** running on aws ec2 ubuntu instance

**Comment by thaJeztah** [comment]
Note that Amazon linux is currently not a supported distro (at least, there's no official docker packages for Amazon Linux, and docker is not tested on that distro).

The error is generated by the containerd cgroups package; https://github.com/docker/engine/blob/v18.06.1-ce/vendor/github.com/containerd/cgroups/paths.go#L60-L88

This may be caused by a configuration issue on the machine; could you try running the check-config.sh script to check if anything is missing / misconfigured? The latest version of that script can be found here; https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh

**Comment by thaJeztah** [comment]
closing as this one went stale
