### ISSUE TITLE
[docs] "Best Practices" should mention SHELL instruction

### ISSUE THREAD

**Issue by jhermann** [moby/moby#37995]
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#using-pipes

I think this should mention 

    SHELL ["/bin/bash", "-c"]

as an alternative to make `set -o pipefail` work on Debian base images. Using the exec form, especially when you have the need to add pipefail to an existing long RUN sequence, is intrusive and would incur a lot of rewriting work.

**Comment by thaJeztah** [comment]
Mentioning the `SHELL` Dockerfile instruction to use `bash` (instead of `/bin/sh`) could make sense; care should be taken though, because this instruction will be preserved in the final image, which means that it can affect / change the behavior for other images using your image in their `FROM`.

However, the documentation is not maintained in this repository; could you open a ticket in the documentation repository instead? https://github.com/docker/docker.github.io/issues/new?body=File:%20[develop/develop-images/dockerfile_best-practices.md](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)

Or, if you want to contribute; open a pull-request with the suggested changes, using this link; https://github.com/docker/docker.github.io/edit/master/develop/develop-images/dockerfile_best-practices.md


I'll close the issue here, but feel free to continue the conversation
