### ISSUE TITLE
Error response form daemon: file integrity checksum failed for "etc/default/cacerts"

### ISSUE THREAD

**Issue by silenceper** [moby/moby#38015]
I found that some k8s applications occasionally fail to execute, but the state of the pod is still running, and finally the problem is image. When I save the image with the `docker save` command, I get an error like this : 

```
Error response form daemon: file integrity checksum failed for "etc/default/cacerts"
```
```
Error response form daemon: file integrity checksum failed for "usr/lib/x86_64-linux-gnu/libvorbis.so.0.4.8"
```

docker info

```
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 73
Server Version: 17.03.2-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.11.6.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.639 GiB
Name: HKA-LLZ600195
ID: GBXN:KURJ:3ZNG:WOAZ:7KUP:OF7O:TXP5:FV7P:22LL:N3Y5:XMIG:TKPU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true

WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
         Reformat the filesystem with ftype=1 to enable d_type support.
         Running without d_type support will not be supported in future releases.
```

**Comment by thaJeztah** [comment]
Without more information, and exact steps to reproduce, I don't think we'd be able to investigate this issue.

Note that you're running Docker 17.03, which has reached end of life in June 2017, and has not been maintained since; Docker 17.03 also has some known vulnerabilities, so I highly recommend updating to a current version.

I also notice that (based on the kernel version) you're running an obsolete version of CentOS 7 (CentOS uses a rolling release model, which means that older releases reach EOL when a new version is released).

Finally, pay attention to the warning that is printed in the output of `docker info`:

```
WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
         Reformat the filesystem with ftype=1 to enable d_type support.
         Running without d_type support will not be supported in future releases.
```

Running overlay on a backing filesystem without d_type support can lead to problems, such as files being reported "missing", and could possibly be related.


I'll close this issue because of the above, but feel free to open a new ticket if you're able to reproduce this on a currently maintained version of Docker, and have steps to reproduce the issue.

Also feel free to continue the conversation
