### ISSUE TITLE
internal networks are not  isolated from host network if ports are exposed 

### ISSUE THREAD

**Issue by mrshiva009** [moby/moby#38049]
![image](https://user-images.githubusercontent.com/28566804/46996626-fb58a880-d13a-11e8-9e36-b17d87943d2f.png)

the above image is the docker-compose.yml file that i use to up my project.
although iam using internal_network the internal network is not isolated from external world or internet .
I can still access the containers through the ports 5555 and 9000 through the host ip address .
But as per the documentation it says containers can't be accessed from the external world if it is in an internal network.
If the networks/containers/services are accessible if the ports are exposed then it contradicts with the statements given in the official documentation https://docs.docker.com/compose/compose-file/#ipam

![image](https://user-images.githubusercontent.com/28566804/46996931-dadd1e00-d13b-11e8-88ec-cf49ee00e798.png)

Could you guys provide some clarity on it.

**Comment by olljanat** [comment]
@mrshiva009 so what you except that should happen on this configuration? Should swarm prevent to use this configuration or give warning for user that it not supported combination? Or should it be just clarified to documentation?

From technical point of view publish means that service is exposed outside which looks to have higher priority than *internal: true* setting. That is most probably like that because some users might want to have multiple services on same network and publish just some of them to outside.

**Comment by mrshiva009** [comment]
@olljanat Then i  think use of the internal option has nothing to do , coz  we however can't access the containers from external world if we don't expose the ports and access them if we expose the ports irrespective of the internal condition.
If there is any use of internal option i just wan't to know about that and expecting a bit of clarity on this  documentation

**Comment by olljanat** [comment]
> If there is any use of internal option i just wan't to know about that and expecting a bit of clarity on this in documentation

Internal option means that containers cannot access any resources outside of that network. Without it they can access to any resources where Docker host can (example to internet).

**Comment by mrshiva009** [comment]
ok Thanks @olljanat

**Comment by thaJeztah** [comment]
Looks like this was answered
