### ISSUE TITLE
CI/Testing infra

### ISSUE THREAD

**Issue by cpuguy83** [moby/moby#38100]
Right now CI for this repo is totally managed on a Jenkins instance.
All CI jobs are defined within Jenkins and are difficult to change.

Having CI pipelines defined in the repo enables us to make changes more easily and without this chicken/egg scenario where if we change something related to what CI consumes in the repo, then CI will be broken until the jobs get updated.

This first step opens up the door for some much needed overhaul on the build/testing scripts in the repo which have really grown out of control.

ping @vdemeester @thaJeztah

**Comment by thaJeztah** [comment]
I know @vdemeester at some point opened a PR to have a Jenkinsfile in the repository (could've been in another repo though). There were some concerns about that opening the opportunity for a PR to escalate to the host, but I'm not sure if that was correct (I'm quite a n00b in that respect).

I'd definitely be 💯 to get the CI config more visible / transparent, instead of having to dig in Jenkins "UI"

/cc @seemethere @andrewhsu

**Comment by thaJeztah** [comment]
Let me add @dave-tucker to check what's needed to make this happen

**Comment by thaJeztah** [comment]
Linking;

- https://github.com/moby/moby/pull/36795 ("wip: jenkinsfile")
- https://github.com/moby/moby/issues/36416 CI enhancement and spring cleaning

**Comment by thaJeztah** [comment]
FWIW, I had a call with @dave-tucker, @seemethere  and @andrewhsu yesterday (about "packaging"), and we came to this subject. Moby CI is definitely on their list;

- We agreed that it would make CI a lot more transparent
- There's many things to improve in CI, and with the Jenkinsfile being in the repository, we can get participation from the community to make those improvements (instead of putting that burden on Docker's test-infra team)
- Some things to be discussed around security (as in; don't automatically build PR's that touch the Jenkinsfile)
- @dave-tucker also mentioned open-sourcing the scripts/tools that are used to build the AMI's that are used in CI. There's nothing secretive about those AMI's, so open-sourcing those things would make sense as well (again; we can get community participation, and won't have to wait for Docker's team to work on making changes)

**Comment by thaJeztah** [comment]
> DockerSwarmSuite is slowest one it needs about 40 minutes to run. Other tests finishes before it

I think that one starts a new daemon for each test, which likely adds to the time taken to complete those. Wondering if we can either combine some tests (rewrite them as a table / subtest), and/or if we can re-use the same daemon for multiple tests. Relevant to that;

- https://github.com/moby/moby/issues/36583 Integration tests: don't use names where possible
- https://github.com/moby/moby/issues/36581 Integration tests: Update testenv.ProtectAll() to also cleanup Services

**Comment by thaJeztah** [comment]
> That why I would prefer to multi thread builds.

Yes; the internal Jenkins CI also has some optimisations like that (uses pipelines to run tests in parallel on a couple machines, but also distributes the built image so that that step doesn't have to be performed multiple times).

**Comment by andrewhsu** [comment]
Some old data on the timings...console logs [here](https://jenkins.dockerproject.org/job/Docker-PRs/54457/consoleFull) from PR #39297

```
00:00:35.497 (9 min) docker build --rm --force-rm ... -t docker:$GITCOMMIT .
00:10:49.695 (122 min) hack/ci/janky
00:10:49.695 (3 sec) hack/validate/default
  . ${SCRIPTDIR}/dco
  . ${SCRIPTDIR}/default-seccomp
  . ${SCRIPTDIR}/gometalinter
  . ${SCRIPTDIR}/pkg-imports
  . ${SCRIPTDIR}/swagger
  . ${SCRIPTDIR}/swagger-gen
  . ${SCRIPTDIR}/test-imports
  . ${SCRIPTDIR}/toml
  . ${SCRIPTDIR}/changelog-well-formed
  . ${SCRIPTDIR}/changelog-date-descending
  . ${SCRIPTDIR}/deprecate-integration-cli
00:10:52.055 (6.5 min) hack/test/unit
00:16:23.591 (3 sec) codecov
00:16:26.949 (1 min) hack/make.sh binary-daemon
00:17:34.418 (30 sec) hack/make.sh dynbinary
00:18:02.909 (2 sec) hack/make.sh test-integration-flaky
00:18:04.277 (106 min) hack/make.sh test-integration
02:04:00.811 (1.5 min) hack/make.sh cross
02:05:25.030 (7 min) hack/make.sh test-docker-py
02:12:21.682 (4 min) docker build ... -t moby-e2e-test -f Dockerfile.e2e .
02:16:30.840 Finished: SUCCESS
```

**Comment by cpuguy83** [comment]
Pipelines are now defined in a Jenkinsfile in the repo, so closing this.
