### ISSUE TITLE
docker ps "Ports" colume output is too long to print in one line

### ISSUE THREAD

**Issue by Civarey** [moby/moby#38139]
Is there a better way to show the port column? I mean, like, show in one column, rather than one line?
![dport](https://user-images.githubusercontent.com/44765750/47984157-a512d000-e110-11e8-8634-36f8a408f8a0.png)

Expect:
![dport2](https://user-images.githubusercontent.com/44765750/47984248-033fb300-e111-11e8-9768-62092eac797f.png)

**Comment by thaJeztah** [comment]
No, there's currently no other presentation for many ports. For services, an enhancement was made to show _consecutive_ ranges of ports in a more compact way (done in this PR: https://github.com/docker/cli/pull/581). A similar presentation could be used for containers, but that change would have to be made in the docker/cli repository

Note that that change won't resolve the issue for the example you're showing, because the ports are not _consecutive_ (i.e., in your example the target port increments with 10 at a time, but the "host" port increments with 1 at a time)


For services;

```
docker service create --name example -p 8080-8090:80-90 nginx:alpine  
docker service ls
```
Which shows;

```
ID                  NAME                MODE                REPLICAS            IMAGE               PORTS
mligsius7wd0        example             replicated          1/1                 nginx:alpine        *:8080-8090->80-90/tcp
```


If you think that change would resolve your issue, could you open a feature request in the docker/cli repository? https://github.com/docker/cli/issues

Given that the code to present this on the command line does not live in this repository, I'll close the issue here, but feel free to continue the conversation.
