### ISSUE TITLE
Docker Name Generator 

### ISSUE THREAD

**Issue by xShuden** [moby/moby#38195]
I want the names of Atatürk, Aziz Sancar and Canan Dağdeviren included in the Docker Names Generator.

I would be glad if you help

**Comment by thaJeztah** [comment]
Contributions are always welcome, but make sure that the names fit the general "scope" of names to include; also special characters in names won't work (due to the container names only being allowed to use `a-z0-9`; see https://github.com/moby/moby/blob/ffaa0b7b3fede363135f528fd6ba28749413b2f0/pkg/namesgenerator/names-generator.go#L112-L113

I'll close this issue, but feel free to contribute
