### ISSUE TITLE
Feature request: Multistage build tag intermediate stages

### ISSUE THREAD

**Issue by dhanvi** [moby/moby#38197]
**Description**
Typically in multistage build the build stage linter/test.. reports will be lost with the options currently available. 

Tagging the intermediate stages would be a nice way to save the build reports. We will not be pushing the images to a registry but will be using the images to extract the reports and publish them to Jenkins.

Article with full description and workaround
https://medium.com/@cyril.delmas/how-to-keep-the-build-reports-with-a-docker-multi-stage-build-on-jenkins-507200f4007f

**Comment by thaJeztah** [comment]
Slightly related; https://github.com/moby/moby/issues/38071

I think this was discussed somewhere (but need to dig where this came up)

Perhaps `docker build` should allow specifying multiple `--target`s, and a tag can be specified for each target. Something like

```bash
docker build -t image:finalstage \
  --target stage1=image:stageone \
  --target stage2=image:stagetwo \
 .
```

But, possibly a more advanced syntax would be needed if we want to expose additional BuildKit functionality (e.g. buildkit allows different types of output, other than docker images)


/cc @tonistiigi @AkihiroSuda

**Comment by AkihiroSuda** [comment]
Maybe we should use YAML rather than CLI flags for complex use case?

**Comment by maurei** [comment]
I'm currently using the workaround the OP posted -- it is manageable, but this feature would be nice. What is the status?

**Comment by AkihiroSuda** [comment]
seems implemented as buildx bake https://github.com/docker/buildx (https://github.com/docker/buildx/blob/08b5a52ccd39c608890d9f166558d55ae0b22c1a/bake/bake.go#L255)

**Comment by diclophis** [comment]
@AkihiroSuda is it possible to document how this might work in buildkit directory, or is not not functional at the moment?

**Comment by AkihiroSuda** [comment]
It should work, see https://github.com/docker/buildx#file-definition for the bake file definition.

**Comment by hidai** [comment]
It looks `buildx bake` is not a solution for this issue to me.
For multiple targets, it just spawn multiple build processes without using BuildKit features (e.g., DAG parallelization, sharing build context) across targets. For complex Dockerfilers or huge build context, this is critically inefficient.

For example, a Dockerfile which takes 1GB build context. A user wants to tag 10 intermediate stages as output tagged image. In this setting, a single builtkit process works well -- it just consumes 1GB memory for context and build is parallelized efficiently. However, `buildx bake` runs 10 independent build processes in parallel and 1x10 = 10GB memory is required. (I can't use my 8GB mem Linux PC due to the issue)

**Comment by jschumacher-dexcom** [comment]
For me the fundamental missing thing from Bake that would alleviate the need for tagging intermediate stages is to allow targets to depend on each other and copy files between targets as multi-stage Docker builds can: https://github.com/docker/buildx/issues/141
