### ISSUE TITLE
Issue #9939 needs to be reopened

### ISSUE THREAD

**Issue by naevtamarkus** [moby/moby#38207]
For some reason Issue #9939 is marked as close, but it's not fixed (according to dozens of people) and being ignored (probably because it's closed). 
Could anybody please reopen it?
Thanks!

**Comment by HaoZeke** [comment]
I believe the most reasonable solution [is here](https://github.com/moby/moby/issues/9939#issuecomment-223045683)

Basically:

```
sudo su
cd /var/lib/docker
docker subvolume delete btrfs/subvolumes/*
```

**Comment by ChojinDSL** [comment]
@HaoZeke 
Actually that might break things. Since this way you're basically delete all of the subvolumes. But if any of your containers are depending on some of those subvolumes, then stuff can break. There doesn't seem to be an easy way to differentiate between actively used subvolumes and ones that have been orphaned through one reason or another.

This seems to be a situation where docker itself is no longer aware of these subvolumes, and therefore doesn't remove them when running a prune command.

**Comment by naevtamarkus** [comment]
The reason why I tried to reopen this is because I'm trying to run kubernetes on a NAS like Synology, where the underlying file system is btrfs, and docker can't handle it, apparently because of this issue. I can't try a newer version of docker on that machine, unfortunately... you may have to ask in the main thread if they can give further feedback. There's plenty of people there who are saying this is not solved, my only intention with this thread was to reopen the other thread and, eventually (hopefully before I replace my NAS) have it solved.

**Comment by olljanat** [comment]
@naevtamarkus reason why #9939 is closed looks to be that #15801 provided fix to it and as far I can see it also provided unit tests for it so original issue can be considered to be fixed.

If you can see same _symptoms_ on you environment/configuration then plz update your first message containing all details asked by issue template. Those questions are there on purpose because we cannot help with this issue before we know how to re-produce it.

**Comment by thaJeztah** [comment]
Closing; this one went stale

**Comment by naevtamarkus** [comment]
Yeah good luck, ignoring this is going to help Docker a lot.

**Comment by thaJeztah** [comment]
> If you can see same symptoms on you environment/configuration then plz update your first message containing all details asked by issue template. Those questions are there on purpose because we cannot help with this issue before we know how to re-produce it.
