### ISSUE TITLE
get.docker.com for osmc is wrong

### ISSUE THREAD

**Issue by suconghou** [moby/moby#38273]
code in `check_forked` function is wrong .

OSMC runs Raspbian but does not has a lsb_release command, your code checks it too early.

it should be`armv7l-raspbian-stretch`

but the script got `not supported by this installer script.`

**Comment by thaJeztah** [comment]
Could you open a ticket for this in the https://github.com/docker/docker-install/issues issue tracker (or open a pull request in that repository)? That's the repository where this script is maintained. Note that forked distros are not officially supported, so the script will be on a "best effort" base.

I'll close the issue here, but  feel free to continue the conversation
