### ISSUE TITLE
Proposal: Build stage volumes

### ISSUE THREAD

**Issue by dhanvi** [moby/moby#38366]
It would be great to have build stage volumes so that we can copy data while building the container it's self without having to wait for the image to be build.

Proposal:
```
FROM ubuntu

VOL /mnt/data/ /data/
RUN apt-get install build-essentials
ADD . /src
RUN cd /src && make && cp binary /data/
```

**Comment by thaJeztah** [comment]
Looks related to https://github.com/moby/moby/issues/14080, and https://github.com/moby/moby/issues/32507 which is about the `RUN --mount` feature that is now available as an experimental Dockerfile syntax (also see https://github.com/moby/moby/issues/3056#issuecomment-447300404 and the [Dockerfile frontend experimental syntaxes](https://github.com/moby/buildkit/blob/b3e4cdf0d8ef6367c2dd9497548cca75e453dbf8/frontend/dockerfile/docs/experimental.md))

I don't think this is something we'd want to have in the Dockerfile; the Dockerfile by itself should not be able to write to arbitrary locations on the host. The `Dockerfile` is intended to produce a Docker _image_ as artefact, and not a binary (or files) on the host.

Note that BuildKit itself (which will be used as the next generation backend for `docker build`, and can now be used in Docker 18.06 and up) is able to use a different ["exporter"](https://github.com/moby/buildkit/blob/3926820e3aa481b8ff4539a1187b465cbf8c822f/README.md#exporters) to produce a "local" artefact instead of an image.

For your use-case; it looks like you don't want the image itself as result, but have the binary built inside a container, and the result copied to your host, correct?

Instead of using `docker build` for this, you could consider using `docker run` to build the artefacts, and bind-mount a local directory to get the results?

Create your base image with the build-tools installed;

```
docker build -t mybuildimage -<<EOF
FROM ubuntu:18.04
RUN apt-get update && apt-get -y install build-essentials
EOF
```
Then `docker run` your image, and copy the results to a bind-mounted directory;

```bash
docker run -it --rm \
  -v $(pwd):/src \
  -v /mnt/data/:/data/ \
  --workdir=/src \
  mybuildimage bash -c 'make && cp binary /data/'
```

**Comment by dhanvi** [comment]
I agree with you. 

My use-case was to easily copy files from container to host system at the build time, `RUN --mount` should do the job for me.

I have raised issues for the same solution suggested by you. https://github.com/docker/cli/issues/1568 https://github.com/moby/moby/issues/38197 

Apologies for not doing enough research on already existing issues.
