### ISSUE TITLE
Year on website is 2017.

### ISSUE THREAD

**Issue by sh7dm** [moby/moby#38421]
**Description**

**Steps to reproduce the issue:**
1. Open the Moby [website](https://mobyproject.org/)
2. Scroll down to the bottom
3. See that year in the footer is 2017

**Describe the results you received:**
Year in the footer is 2017

**Describe the results you expected:**
Year in the footer should be 2018 (2019)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
-
```

**Output of `docker info`:**

```
-
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Thanks for reporting; the copyright should mention the year that the content was produced, or substantially modified; in this case, it looks like all content (baring some small changes) was done in 2017; https://github.com/moby/mobywebsite/commits/master, so from that perspective, I think the year 2017 is correct. If substantial changes are made, this could be updated to (e.g.) `2017-2019`, but I don't think that's needed currently; if you do feel this should be updated, feel free to open a pull-request in the website repository, to update the footer; https://github.com/moby/mobywebsite/blob/master/docs/_includes/footer.html

I'll close this ticket because of the above, but feel free to continue the conversation 👍
