### ISSUE TITLE
rule not delete

### ISSUE THREAD

**Issue by timchenxiaoyu** [moby/moby#38444]
docker  1.12.6
docker rm ,but DNAT rule not deleted
lead to  same DNAT
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 10101 -j DNAT --to-destination 10.251.90.31:10101
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 10101 -j DNAT --to-destination 10.251.90.7:10101

**Comment by thaJeztah** [comment]
Docker 1.12 is very old, and reached End Of Life when Docker 1.13 was released (in January 2017; https://github.com/moby/moby/releases/tag/v1.13.0), and has not been maintained since.

I highly recommend updating to a currently supported version of docker, because older versions have unpatched vulnerabilities.

I'll close this issue, because Docker 1.12 is no longer supported, but feel free to open a new issue with details (as requested in the issue template that was shown when you opened this ticket), if you're still able to reproduce this issue on a current version of Docker.
