### ISSUE TITLE
edit deamon.json added  "hosts": ["tcp://0.0.0.0:2375","unix:///var/run/docker.sock"],then start failed

### ISSUE THREAD

**Issue by Struer** [moby/moby#38495]
daemon.json
{
  "registry-mirrors": ["https://registry.docker-cn.com"],
  "bip": "10.0.0.1/16",
  "hosts": ["tcp://0.0.0.0:2375","unix:///var/run/docker.sock"]
}

start result:
[root@mini2 run]# systemctl restart docker
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
[root@mini2 ~]# systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since 六 2019-01-05 01:45:18 CST; 7s ago
     Docs: https://docs.docker.com
  Process: 12262 ExecStart=/usr/bin/dockerd -H unix:// (code=exited, status=1/FAILURE)
 Main PID: 12262 (code=exited, status=1/FAILURE)

1月 05 01:45:16 mini2 systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
1月 05 01:45:16 mini2 systemd[1]: Failed to start Docker Application Container Engine.
1月 05 01:45:16 mini2 systemd[1]: Unit docker.service entered failed state.
1月 05 01:45:16 mini2 systemd[1]: docker.service failed.
1月 05 01:45:18 mini2 systemd[1]: docker.service holdoff time over, scheduling restart.
1月 05 01:45:18 mini2 systemd[1]: start request repeated too quickly for docker.service
1月 05 01:45:18 mini2 systemd[1]: Failed to start Docker Application Container Engine.
1月 05 01:45:18 mini2 systemd[1]: Unit docker.service entered failed state.
1月 05 01:45:18 mini2 systemd[1]: docker.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

why docker start failed?

**Comment by Struer** [comment]
if I delete "hosts": ["tcp://0.0.0.0:2375","unix:///var/run/docker.sock"]

{
"registry-mirrors": ["https://registry.docker-cn.com"],
"bip": "10.0.0.1/16"
}

then docker start success

whats wrong with this config?

**Comment by olljanat** [comment]
@Struer Can you share why you would like enable unencrypted and unsecure TCP port to Docker engine?
There is more secure ways to allow client connect to Docker engine. 

Because that there is already warnings of it #37684 and discussion how to make that configuration even harder #37299

Another similar issue #38310

**Comment by thaJeztah** [comment]
@Struer I suspect the daemon fails to start because there's a "conflicting configuration"; if you set the `hosts` option in `daemon.json` and the systemd unit also specifies a `-H` flag, the daemon will refuse to start because both options are set.

You can find out what's configured in the systemd unit using; `systemctl cat docker.service`

For example;

```bash
systemctl cat docker.service | grep ExecStart
ExecStart=/usr/bin/dockerd -H fd://
```

In the output above, you can see that the systemd-unit has the default `-H fd://` defined (which is used for socket activation).

To change the systemd configuration, create a drop-in/override file (never edit the original systemd unit file). The easiest way is to use `systemctl edit`;

1. create an override file using `systemctl edit docker.service`

    ```
    systemctl edit docker.service
    ```

    This will open a new file in your editor

2. edit the override file; for example to remove the `-H fd://`, it should look something like this:

    ```
    [Service]
    
    # first reset the existing ExecStart
    ExecStart=
    
    # then set the new one
    ExecStart=/usr/bin/dockerd
    ```

3. save the file, and exit your editor
4. reload the systemd configuration

    ```bash
    systemctl daemon-reload
    ```

5. verify that your configuration was loaded

    You'll see the `ExecStart` multiple times; first the original one (in `docker.service`), then the one from your override file (`docker.service.d/override.conf`)

    ```
    systemctl cat docker.service

    # /lib/systemd/system/docker.service

    ...

    ExecStart=/usr/bin/dockerd -H fd://

    ...
   
    # /etc/systemd/system/docker.service.d/override.conf
   ...
    [Service]
    
    # first reset the existing ExecStart
    ExecStart=
    
    # then set the new one
    ExecStart=/usr/bin/dockerd
    ```


6. restart the docker service to use the new configuration

    ```bash
    systemctl restart docker.service
    ```

The systemd unit now no longer specifies a `-H` option, so it will use the default (`unix:///var/run/docker.sock`). You can now edit your `daemon.json` to set other addresses to listen on.

**Comment by olljanat** [comment]
@yuklia no but I mean that I will not give instructions how to create insecure configuration but instead of prefer to get understanding what users try achieve with that configuration and then tell how get same result from secure configuration.

PS. But it looks that @thaJeztah just told that 😇

**Comment by thaJeztah** [comment]
Good to hear @yuklia 

Reading the information above, I don't think there's a bug here, so let me close this issue, but feel free to comment after I closed
