### ISSUE TITLE
LCOW: Cannot bind-mount when starting container in WSL

### ISSUE THREAD

**Issue by codeimpossible** [moby/moby#38539]
**Description**

Unable to bind-mount when using Ubuntu v14.04 via Windows Subsystem for Linux (WSL) with docker setup as a daemon client to Docker for Windows.

**Steps to reproduce the issue:**
1. Setup  Docker for Windows to expose daemon on tcp://localhost:2375 without TLS (via settings/general)
2. Add the following to your `.bashrc`

```
export DOCKER_HOST='tcp://0.0.0.0:2375'
export DOCKER_OPTS='tcp://0.0.0.0:2375'
```

3. Run the commands below in _both_ a WSL terminal and Windows terminal (I used powershell).

```
$ cd ~ && mkdir test && cd test
$ echo "hello world" > testfile
$ docker run -v "$(pwd):/test" --rm ubuntu bash -c "ls -lsa /test && cat /test/testfile"
```

4. Run the commands below in _both_ a WSL terminal and Windows terminal

```
$ docker volume create testfile
$ cd ~/test
$ docker run -v testfile:/data --name helper busybox true
$ docker cp testfile helper:/data
$ docker rm helper
$ docker run -v testfile:/test --rm ubuntu bash -c "ls -lsa /test && cat /test/testfile"
$ docker volume rm testfile
```

**Describe the results you received:**
For the first set of commands, WSL prints:

```
cat: /test/testfile: No such file or directory
total 4
0 drwxr-xr-x 2 root root   40 Jan 11 17:00 .
4 drwxr-xr-x 1 root root 4096 Jan 11 17:01 ..
```

while windows correctly displays:

```
total 12
4 drwxr-xr-x 2 root root 4096 Jan 11 17:17 .
4 drwxr-xr-x 1 root root 4096 Jan 11 17:18 ..
4 -rw-rw-rw- 1 1000 1000   13 Jan 11 16:14 testfile
hello world!
```

For the second set of scripts both terminals correctly print:

```
total 12
4 drwxr-xr-x 2 root root 4096 Jan 11 17:17 .
4 drwxr-xr-x 1 root root 4096 Jan 11 17:18 ..
4 -rw-rw-rw- 1 1000 1000   13 Jan 11 16:14 testfile
hello world!
```

**Describe the results you expected:**

I expected both sets of commands to produce the same results on WSL and Windows native.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:** 
```
Docker version 18.09.0, build 4d60db4 (Docker for Windows)
Docker version 18.06.1-ce, build e68fc7a (WSL, setup as client of Docker for Windows)
```

**Output of `docker info`:**

```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 215
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d014124
ID: F5CC:L5RP:AGVZ:BPJA:UKWI:QKS6:XL76:Z6QS:6DFQ:7RXW:NI2V:M24S
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 47
 System Time: 2019-01-11T19:58:35.1587845Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on a physical Windows 10 machine v1709 (OS Build 16299.125)

**Comment by adammohammed** [comment]
Initially I thought this may just be a permission issue with accessing WSL files from Windows.
This [blog post](https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/), says that this is something not to be done -- although I'm not sure if this is up-to-date.


I reproduced the result as specified, but thought if the files were rooted in the Windows file system, it may work.

1. Setup Docker for Windows as above.
2. Run these commands to create a testfile from the WSL terminal

```sh
$ cd /mnt/c/ && mkdir test && cd test
$ echo "hello world" > testfile
$ docker run -v "$(pwd)":/test --rm ubuntu bash -c "ls -lsa /test && cat /test/testfile"
```

The result is the same as the original attempt.
```sh
total 4
0 drwxr-xr-x 2 root root   40 Feb 11 23:10 .
4 drwxr-xr-x 1 root root 4096 Feb 11 23:10 ..
cat: /test/testfile: No such file or directory
```

3. Alter volume command to provide the path as it would exist from the windows file system. Skipping the file creation since it already exists. This is still being run from within the WSL terminal.
```sh
$ docker run -v "C:\test":/test --rm ubuntu bash -c "ls -lsa /test && cat /test/testfile"
```

This works as expected, yielding this output.

```sh
total 5
0 drwxr-xr-x 2 root root   40 Feb 11 23:10 .
4 drwxr-xr-x 1 root root 4096 Feb 11 23:10 ..
1 -rwxr-xr-x 1 root root   12 Feb 11 23:06 testfile
hello world
```


I'd like to take a look as to why your way doesn't work, but for now, this workaround may suit your needs, and I believe works in the same way that your volume solution does.

The volume is created on the Windows file system so its accessible from both OSs. I haven't specifically confirmed that though.

**Comment by jhowardmsft** [comment]
@benhillis

**Comment by jhowardmsft** [comment]
Can you open an issue under Microsoft/WSL? I don't believe this is a moby issue.
