### ISSUE TITLE
container_linux.go:247: starting container process caused "exec: \"./start.sh\": stat ./start.sh: no such file or directory" kubernetes error

### ISSUE THREAD

**Issue by ankitam23** [moby/moby#38610]
**my deployment.yaml is**
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
  labels:
    io.kompose.service: dm-captchaapi
  name: dm-captchaapi
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: dm-captchaapi
    spec:
      containers:
      - env:
        - name: EMCON_ALPHA
          value: d3c1s10nm1n3s
        image: ####
        name: dm-captchaapi-rel
        ports:
        - containerPort: 8080
status: {}

**my service.yaml is** 

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
  labels:
    io.kompose.service: dm-captchaapi
  name: dm-captchaapi
spec:
  ports:
  - name: "9004"
    #nodePort: 30005
    port: 9004
    targetPort: 9004
  selector:
    io.kompose.service: dm-captchaapi
  #type: NodePort
status:
  loadBalancer: {}

**and having one configmap.**

**kubernetes one master and 2 nodes**

**Comment by cpuguy83** [comment]
The error is pretty specific, the runtime could not find the path specified when trying to start the container.

Since you did not supply any of the details requested in the issue template it is very difficult to help here.

Does the file exist in the image?

Are you on Docker 18.09? Did you modify the docker.service to include MountPropagation? If so this will break things in 18.09 and should be removed.

Closing because there is not enough detail in this report, but feel free to update and we can reopen if needed.

Thanks!
