### ISSUE TITLE
can not use systemd as cgroup driver on ubuntu with docker 18.09.2

### ISSUE THREAD

**Issue by hchenxa** [moby/moby#38753]
**Description**

**Steps to reproduce the issue:**
1. Install the docker-ce 18.09.2 on ubuntu
2. config with systemd driver
3. execute the docker run hello-world

**Describe the results you received:**

```
root@hchenxa-3:~# docker run hello-world
docker: Error response from daemon: OCI runtime create failed: systemd cgroup flag passed, but systemd support for managing cgroups is not available: unknown.
ERRO[0000] error waiting for container: context canceled
```

**Describe the results you expected:**
the container should be started.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
root@hchenxa-3:~# docker version
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:47 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:42:13 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 169
 Running: 0
 Paused: 0
 Stopped: 169
Images: 51
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 209a7fc3e4a32ef71a8c7b50c68fc8398415badf
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-45-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.66GiB
Name: hchenxa-3
ID: 2BSB:VMWA:GC5I:TWHD:QN2Y:HNKL:YMZI:BSNN:2WBP:4JJZ:PIJ4:ZYSI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: http://9.21.61.141:3128
HTTPS Proxy: http://9.21.61.141:3128
No Proxy: localhost,127.0.0.1,mycluster.icp
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
This error comes from runc; https://github.com/opencontainers/runc/blob/69663f0bd4b60df09991c08812a60108003fa340/utils_linux.go#L42-L46

```go
	// We default to cgroupfs, and can only use systemd if the system is a
	// systemd box.
	cgroupManager := libcontainer.Cgroupfs
	if context.GlobalBool("systemd-cgroup") {
		if systemd.UseSystemd() {
			cgroupManager = libcontainer.SystemdCgroups
		} else {
			return nil, fmt.Errorf("systemd cgroup flag passed, but systemd support for managing cgroups is not available")
		}
	}
```

That code triggers the error if the system is not using systemd, or is not able to detect this; https://github.com/opencontainers/runc/blob/69663f0bd4b60df09991c08812a60108003fa340/libcontainer/cgroups/systemd/apply_systemd.go#L88-L195

I did see a pull request recently that removes part of that detection (because it broke on recent systemd kernels, and was not fully working on other versions); https://github.com/opencontainers/runc/pull/1978. That version of runc is not in use by docker yet though.

Another reason could be if you're running a static build of docker (and runc), which does not support systemd cgroups, and in which case `false` is returned at all times; https://github.com/opencontainers/runc/blob/69663f0bd4b60df09991c08812a60108003fa340/libcontainer/cgroups/systemd/apply_nosystemd.go#L17-L19

Did you install docker from a `.deb` package, or did you install a static binary?

**Comment by thaJeztah** [comment]
Curious: is there a specific reason to use the systemd cgroup-driver? (as historically, there's been many bugs in the systemd cgroup implementation, which was the reason for making cgroupfs the default)

**Comment by hchenxa** [comment]
@thaJeztah thanks for checking this issue, I install the docker with `apt` follow the steps https://docs.docker.com/install/linux/docker-ce/ubuntu/, and I know that the cgroupfs was the default and recommend configuration for docker, the reason why I change to use systemd as I was using k8s and k8s have a cgroup leak issue which will make my system crash.

**Comment by thaJeztah** [comment]
thanks for the additional information; what version were you running before (and that still worked?)

Perhaps we can narrow down what caused the change in behavior

**Comment by hchenxa** [comment]
kubernetes 1.12.4 + docker 18.09.2

**Comment by thaJeztah** [comment]
That's the current version; you mentioned that an older version worked; what version did you use _before_ docker 18.09.2 ?

**Comment by hchenxa** [comment]
I was using 17.09 before upgrade

**Comment by thaJeztah** [comment]
Ok, that'll be a big diff between those; runc https://github.com/opencontainers/runc/commit/3f2f8b84a77f73d38244dd690525642a72156c64 was used by [Docker 17.09.1](https://github.com/docker/docker-ce/blob/v17.09.1-ce/components/engine/hack/dockerfile/binaries-commits#L6), compared to https://github.com/opencontainers/runc/commit/96ec2177ae841256168fcf76954f7177af9446eb [used by Docker v18.09.1](https://github.com/docker/docker-ce/blob/v18.09.1/components/engine/hack/dockerfile/install/runc.installer#L7) (I've taken the v18.09.1 version, as the v18.09.2 version has a "hotfix" patch, so that commit won't be found upstream)

full diff of runc between those versions: https://github.com/opencontainers/runc/compare/3f2f8b84a77f73d38244dd690525642a72156c64...96ec2177ae841256168fcf76954f7177af9446eb (and raw diff, because GitHub won't show more than 250 commits: [opencontainers/runc@`3f2f8b8..96ec217`]( https://github.com/opencontainers/runc/compare/3f2f8b84a77f73d38244dd690525642a72156c64..96ec2177ae841256168fcf76954f7177af9446eb))

**Comment by AkihiroSuda** [comment]
should be fixed in the latest releases
