### ISSUE TITLE
Configurable number of event log entries

### ISSUE THREAD

**Issue by chrisdoherty4** [moby/moby#38812]
**Description**
At present the number of event log entries is fixed to 256 (https://github.com/moby/moby/blob/master/daemon/events/events.go#L12). This request is to make the number of entries configurable. 

**Proposal** 
Provide a configuration option to dockerd (as a first stab `--events-limit int`) that default to 256 (current limit). 

**Considerations**

1. Does there need to be an upper limit?

**Comment by chrisdoherty4** [comment]
I'm keen to take this on myself.

**Comment by thaJeztah** [comment]
There's some discussion around this in 
https://github.com/moby/moby/pull/38214#issuecomment-44012918 (and 0https://github.com/moby/moby/pull/37441#issuecomment-404706997)

**Comment by chrisdoherty4** [comment]
I really like the driver idea in https://github.com/moby/moby/pull/38214#issuecomment-449365822 that expands upon the idea albeit I think it would be a separate chunk of work. 

> What about "Event output drivers" where the default behaviour is to use the internal buffering etc. But if you use a driver for this, all events will just be sent at the driver, disregarding any internal limits. For example, a Kafka driver which will just forward all events as JSON to a Kafka cluster.

**Comment by thaJeztah** [comment]
So, I think the problem was that the events are all kept in memory (no file written to disk), so increasing the buffer size could become problematic on systems with a high number of containers. Of course, writing them to disk could work around that, but the events stream was never _designed_ to be used as  "log" of events, or a guarantee that events are delivered / received.

@cpuguy83 @aaronlehmann any thoughts?

**Comment by cpuguy83** [comment]
In general I think events are not reliable in dockerd. It's too easy to miss them.
It's probably better to do a periodic re-sync then to rely on more events being stored.

**Comment by chrisdoherty4** [comment]
Forgive the ignorance: can you elaborate? Thanks.
