### ISSUE TITLE
image: invalid copying in RootFS.Clone

### ISSUE THREAD

**Issue by quasilyte** [moby/moby#38834]
https://github.com/moby/moby/blob/fc01c2b481097a6057bec3cd1ab2d7b4488c50c4/image/rootfs.go#L41

This code does not copy the `r.DiffIDs`.
Should be something like:
```diff
-newRoot.DiffIDs = append(r.DiffIDs)
+newRoot.DiffIDs = append([]layer.DiffID{}, r.DiffIDs...)
```

This is a complete listing of `Clone` for convenience:
```go
// Clone returns a copy of the RootFS
func (r *RootFS) Clone() *RootFS {
	newRoot := NewRootFS()
	newRoot.Type = r.Type
	newRoot.DiffIDs = append(r.DiffIDs)
	return newRoot
}
```

**Comment by thaJeztah** [comment]
looks like this change was made in https://github.com/moby/moby/commit/b50ade0bfb67dae7867f4f5c3da12c1f778b6c7e (https://github.com/moby/moby/pull/34063)

ping @dnephin @tonistiigi @AkihiroSuda PTAL

**Comment by thaJeztah** [comment]
@quasilyte are you interested in opening a PR for this?

**Comment by quasilyte** [comment]
@thaJeztah, I can. :)
As soon as I'll get a few spare minutes.

**Comment by tandr** [comment]
Since it is inside of the Clone, it could be both `newRoot.DiffIDs = make([]int, len(r.DiffIDs)); copy(newRoot.DiffIDs, r.DiffsIDs)` (copy of an array) or `newRoot.DiffIDs = append([]int{}, r.DiffIDs...)` (just a new slice), depending on an original intent.

(originally referenced from https://github.com/golang/go/issues/30040#issuecomment-461303583)
