### ISSUE TITLE
PKCS#11 Registry Authentication

### ISSUE THREAD

**Issue by bernard-wagner** [moby/moby#38849]
A number of organisations have adopted PIV smartcard devices, such as Yubikeys for TLS client authentication. It would be beneficial to allow the use of PKCS#11 interfaces when connecting to a registry. 

Currently Docker allows configuration of the client certificate and key in the `/etc/docker/certs.d/` directory. This requires the certificates and keys to be in PEM format. 

Possible approaches:
1. Specify `MODULE_PATH` and object identifiers in config.json 
2. Support a new file type in `/etc/docker/certs.d/` that contains `MODULE_PATH` and PKCS11 object identifiers
3. Allow setting of `MODULE_PATH` and object identifiers as ENV vars.

Some gotchas 
1. Capturing input for user pin?
2. Ensuring permissions of `MODULE_PATH` are valid to prevent privilege escalation. 

Will have a bash at implementing this, but would appreciate some discussion/guidance on the preferred approach. 

Most of the changes will need to be made to: https://github.com/moby/moby/blob/master/registry/registry.go#L57

**Comment by thaJeztah** [comment]
@justincormack @caervs @manishtomar PTAL

**Comment by manishtomar** [comment]
Registry currently only authenticates at HTTP level. There is no client authentication via TLS certificate. It will be nice if registry can also use same docker client's TLS certificate to authenticate the user. This will require changes in registry to accept TLS authentication and also in daemon to send the same TLS certificate. Since daemon and registry are generally at different machines there is an operational burden to keep the client certificates between daemon and registry in sync. Not sure if syncing the certificates should be left to the operator. Also what should be the source of truth for user certificates? Is it registry or daemon? I would have to say registry and daemon syncing from it.

**Comment by bernard-wagner** [comment]
@manishtomar I might not have given all the context, but think you misunderstood the feature. This should not mean any changes to the `registry` server, but rather that the Docker client can make use of PKCS11 for TLS client authentication, where the registry is behind a reverse proxy that does TLS termination.

**Comment by jeffallen** [comment]
The PR I just pushed solves this problem for me. It has the major drawback that it only works when dockerd is built with `make dynbinary`, which I guess is not the default. So it's likely this will not be merged, but at least people looking for this feature would be able to use my PR if they want.
