### ISSUE TITLE
COPY --from ignored when image layer is from a newer version of docker

### ISSUE THREAD

**Issue by moof2k** [moby/moby#38923]
It appears earlier versions of docker silently ignore cached images if they are created with newer versions of docker. I just spent an hour trying to figure out why one machine was rebuilding its layers every time; turned out the layers were built on 18.09 but this machine was running 17.x.

**Steps to reproduce the issue:**
1. Create a layer with docker 18.09
2. Load a layer with FROM .. AS layer
3. Reference the layer with COPY --from=layer ...

**Describe the results you received:**
The COPY step is performed every time instead of being pulled from cache

**Describe the results you expected:**
The COPY step is pulled from cache

**Additional information you deem important (e.g. issue happens only occasionally):**
Upgrading docker on the machine with the problem resolved the issue.

**Comment by thaJeztah** [comment]
I'm not sure I understand the combination "create a layer with docker 18.09" and "but this machine was running 17.x"; how did you get the 18.09 layer on the 17.x machine?

Note that it's definitely possible there have been bugs in older versions of Docker that have been resolved since (and Docker CE 17.xx has reached EOL, so is no longer maintained)

Could you describe the exact  steps to reproduce, and provide the `docker info` / `docker version` of those installs?

**Comment by thaJeztah** [comment]
Closing as this went stale
