### ISSUE TITLE
Can processes run in same container belong to different cgroups?

### ISSUE THREAD

**Issue by WanLinghao** [moby/moby#39111]
We want to put processes in same container to different cgroups.
Is that possible? 
Please give some hints

**Comment by cpuguy83** [comment]
They could *if* the cgroups dir was writable in the container, and of course you would need to create those cgroups and place your processes in the cgroup you want.

An alternative is to use multiple containers but a single cgroup parent.
This would mean creating the cgroup on the host, then you use `docker run --cgroup-parent <path to cgroup>` for each of the containers.

Closing since this isn't really an issue.
Please check out IRC or the community slack for these types of questions.

Thanks!
