### ISSUE TITLE
Singled quoted CMD’s, ENTRYPOINT’s fail at run time

### ISSUE THREAD

**Issue by mcandre** [moby/moby#39199]
When CMD or ENTRYPOINT strings are single quoted, then containers fail in mysterious ways at run time. Can we please amend the build parser to catch this mistake sooner, at build time?

**Comment by thaJeztah** [comment]
Unfortunately that won't be possible, due to both of these accepting either a JSON notation or shell notation; in shell notation, `['...']` could be a valid command, and thus the builder cannot make assumptions about the validity.

(Yes, it's a bit of a pain, and in hindsight, supporting both forms wasn't the best choice, but unfortunately we're now stuck to it)

I'll close this issue for that reason, but feel free to continue the conversation
