### ISSUE TITLE
Panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by robinwangrubin** [moby/moby#39221]
My OsInfo

```
Linux ubuntu-18-04-template.host.com 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

My Docker-info

```
docker version
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:53:11 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

```
root@ubuntu-18-04-template:/var/lib/docker# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.09.3
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: pending
 NodeID: i55d8vmqbm4a2b6j3rgm2cs3q
 Error: rpc error: code = Unknown desc = The swarm does not have a leader. It's possible that too few managers are online. Make sure more than half of the managers are online.
 Is Manager: true
 Node Address: 192.168.100.100
 Manager Addresses:
  10.10.220.69:2377
  10.10.220.70:2377
  10.10.220.71:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e
runc version: 6635b4f0c6af3810594d2770f662f34ddc15b40d
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-29-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 962MiB
Name: ubuntu-18-04-template.host.com
ID: SBDP:SXFU:WBCK:X7X2:SVCK:ICFG:S6R7:7UAI:WYAV:OM25:VFWW:MCRH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://registry.docker-cn.com/
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support

```
----------

What i did:

* I want to recover my swarm cluster from the disaster cluster.

1. Copy /var/lib/docker/swarm  From a cluster-manager To my current machine.
2. Cover my current /var/lib/docker/swarm dic.
3. start docker
4. docker swarm init --force-new-cluster
-----------

Error Log
```May 15 17:35:41 ubuntu-18-04-template.host.com dockerd[2786]: time="2019-05-15T17:35:41.468074753+08:00" level=error msg="error creating cluster object" error="name conflicts with an existing object" module=node node.id=i55d8vmqbm4a2b6j3rgm2cs3q
May 15 17:35:41 ubuntu-18-04-template.host.com dockerd[2786]: time="2019-05-15T17:35:41.469859137+08:00" level=info msg="leadership changed from not yet part of a raft cluster to i55d8vmqbm4a2b6j3rgm2cs3q" module=node node.id=i55d8vmqbm4a2b6j3rgm2cs3q
May 15 17:35:41 ubuntu-18-04-template.host.com dockerd[2786]: time="2019-05-15T17:35:41.470809320+08:00" level=info msg="dispatcher starting" module=dispatcher node.id=i55d8vmqbm4a2b6j3rgm2cs3q
May 15 17:35:41 ubuntu-18-04-template.host.com dockerd[2786]: time="2019-05-15T17:35:41.736683837+08:00" level=warning msg="election tick value (10s) is different from the one defined in the cluster config (3s), the cluster may be unstable" module=node node.id=i55d8vmqbm4a2b6j3rgm2cs3q
May 15 17:35:42 ubuntu-18-04-template.host.com dockerd[2786]: time="2019-05-15T17:35:42.038499000+08:00" level=info msg="worker i55d8vmqbm4a2b6j3rgm2cs3q was successfully registered" method="(*Dispatcher).register"
May 15 17:35:42 ubuntu-18-04-template.host.com dockerd[2786]: panic: runtime error: invalid memory address or nil pointer dereference
May 15 17:35:42 ubuntu-18-04-template.host.com dockerd[2786]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x55fea00d25ec]
May 15 17:35:42 ubuntu-18-04-template.host.com dockerd[2786]: goroutine 256 [running]:
May 15 17:35:42 ubuntu-18-04-template.host.com dockerd[2786]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).allocateNode(0xc44dfc62c0, 0x55fea0e85a80, 0xc42c4310c0, 0xc45106f900, 0x0, 0xc45112c740, 0x5, 0x8, 0xc4510bf860)
May 15 17:35:42 ubuntu-18-04-template.host.com dockerd[2786]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/network.go:1045 +0x53c
May 15 17:35:42 ubuntu-18-04-template.host.com dockerd[2786]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).allocateNodes(0xc44dfc62c0, 0x55fea0e85a80, 0xc42c4310c0, 0x0, 0x0, 0x0)
May 15 17:35:42 ubuntu-18-04-template.host.com dockerd[2786]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/network.go:477 +0x1c0
May 15 17:35:42 ubuntu-18-04-template.host.com dockerd[2786]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).doNetworkInit(0xc44dfc62c0, 0x55fea0e85a80, 0xc42c4310c0, 0x0, 0x0)
May 15 17:35:42 ubuntu-18-04-template.host.com dockerd[2786]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/network.go:154 +0x4da
May 15 17:35:42 ubuntu-18-04-template.host.com dockerd[2786]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).(github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.doNetworkInit)-fm(0x55fea0e85a80, 0xc42c4310c0, 0xc, 0xc)
May 15 17:35:42 ubuntu-18-04-template.host.com dockerd[2786]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/allocator.go:105 +0x40
May 15 17:35:42 ubuntu-18-04-template.host.com dockerd[2786]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).init(0xc44dfc62c0, 0x55fea0e85a80, 0xc42c4310c0, 0xc43af797e0, 0x0, 0x0, 0xc44dfb8610, 0x0)
May 15 17:35:42 ubuntu-18-04-template.host.com dockerd[2786]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/allocator.go:174 +0x4dd
May 15 17:35:42 ubuntu-18-04-template.host.com dockerd[2786]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).Run.func2(0x0, 0x0)
May 15 17:35:42 ubuntu-18-04-template.host.com dockerd[2786]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/allocator.go:122 +0xbc
May 15 17:35:42 ubuntu-18-04-template.host.com dockerd[2786]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator.(*Allocator).Run(0xc44dfc62c0, 0x55fea0e85a80, 0xc4209dcd80, 0x0, 0x0)
May 15 17:35:42 ubuntu-18-04-template.host.com dockerd[2786]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/allocator/allocator.go:142 +0x4e1
May 15 17:35:42 ubuntu-18-04-template.host.com dockerd[2786]: github.com/docker/docker/vendor/github.com/docker/swarmkit/manager.(*Manager).becomeLeader.func6(0x55fea0e85a80, 0xc4209dcd80, 0xc44dfc62c0)
May 15 17:35:42 ubuntu-18-04-template.host.com dockerd[2786]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/manager.go:1048 +0x45
May 15 17:35:42 ubuntu-18-04-template.host.com dockerd[2786]: created by github.com/docker/docker/vendor/github.com/docker/swarmkit/manager.(*Manager).becomeLeader
May 15 17:35:42 ubuntu-18-04-template.host.com dockerd[2786]:         /go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/manager/manager.go:1047 +0xf34
May 15 17:35:42 ubuntu-18-04-template.host.com systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 15 17:35:42 ubuntu-18-04-template.host.com systemd[1]: docker.service: Failed with result 'exit-code'.
May 15 17:35:42 ubuntu-18-04-template.host.com systemd[1]: Failed to start Docker Application Container Engine.
May 15 17:35:44 ubuntu-18-04-template.host.com systemd[1]: docker.service: Service hold-off time over, scheduling restart.
May 15 17:35:44 ubuntu-18-04-template.host.com systemd[1]: docker.service: Scheduled restart job, restart counter is at 2.
May 15 17:35:44 ubuntu-18-04-template.host.com systemd[1]: Stopped Docker Application Container Engine.
May 15 17:35:44 ubuntu-18-04-template.host.com systemd[1]: Closed Docker Socket for the API.
May 15 17:35:44 ubuntu-18-04-template.host.com systemd[1]: Stopping Docker Socket for the API.```

**Comment by cpuguy83** [comment]
ping @dperny

**Comment by dperny** [comment]
me_irl: https://www.youtube.com/watch?v=bLHL75H_VEM

**Comment by dperny** [comment]
My first thought was docker/swarmkit#2764, but that was backported to 18.09... Give me a sec, I'll provide a more substantial answer than a dumb youtube video.

**Comment by robinwangrubin** [comment]
Hello, guys.
When i try to use 18.06 Version of docker, it works.
Thanks  a lot .
I'll close the issue.

**Comment by Macbeth-byx** [comment]
Hello, Mr
My enviroment are as flows:
18.09.0  Version of docker, three nodes
There are some question about docker swarm.The docker was exit after executed "docker swarm leave -f" cmd,detail log are as follows:
Jun 18 16:50:12 moss-0001 dockerd[4047]: time="2024-06-18T16:50:12.646486713+08:00" level=error msg="error sending message to peer" error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 172.78.78.10:2377: connect: connection refused\""
Jun 18 16:50:13 moss-0001 dockerd[4047]: time="2024-06-18T16:50:13.586876613+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc001896010, CONNECTING" module=grpc
Jun 18 16:50:13 moss-0001 dockerd[4047]: time="2024-06-18T16:50:13.587991196+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc001896010, READY" module=grpc
Jun 18 16:54:04 moss-0001 dockerd[4047]: time="2024-06-18T16:54:04.084206553+08:00" level=info msg="shutting down certificate renewal routine" module=node/tls node.id=n09yo5hghhwxuq1ub26spp1at node.role=swarm-manager
Jun 18 16:54:04 moss-0001 dockerd[4047]: time="2024-06-18T16:54:04.084208854+08:00" level=info msg="Stopping manager" module=node node.id=n09yo5hghhwxuq1ub26spp1at
Jun 18 16:54:04 moss-0001 dockerd[4047]: time="2024-06-18T16:54:04.084273668+08:00" level=info msg="dispatcher stopping" method="(*Dispatcher).Stop" module=dispatcher node.id=n09yo5hghhwxuq1ub26spp1at
Jun 18 16:54:04 moss-0001 dockerd[4047]: time="2024-06-18T16:54:04.084317588+08:00" level=info msg="dispatcher session dropped, marking node q0keq55q291o8trumxbob2lhg down" method="(*Dispatcher).Session" node.id=q0keq55q291o8trumxbob2lhg node.session=cqkmb6ad2cc91yjkxv4qofg6u
Jun 18 16:54:04 moss-0001 dockerd[4047]: time="2024-06-18T16:54:04.084328711+08:00" level=error msg="failed to remove node" error="rpc error: code = Aborted desc = dispatcher is stopped" method="(*Dispatcher).Session" node.id=q0keq55q291o8trumxbob2lhg node.session=cqkmb6ad2cc91yjkxv4qofg6u
Jun 18 16:54:04 moss-0001 dockerd[4047]: time="2024-06-18T16:54:04.084343918+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc000d15500, TRANSIENT_FAILURE" module=grpc
Jun 18 16:54:04 moss-0001 dockerd[4047]: time="2024-06-18T16:54:04.084368139+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc000d15500, CONNECTING" module=grpc
Jun 18 16:54:04 moss-0001 dockerd[4047]: time="2024-06-18T16:54:04.084356930+08:00" level=info msg="dispatcher session dropped, marking node m7p80vzt9krzz9o9tia7972a4 down" method="(*Dispatcher).Session" node.id=m7p80vzt9krzz9o9tia7972a4 node.session=a6ch3h812r23c5wahjw12e4l0
Jun 18 16:54:04 moss-0001 dockerd[4047]: time="2024-06-18T16:54:04.084393572+08:00" level=warning msg="grpc: addrConn.createTransport failed to connect to {/var/run/docker/swarm/control.sock 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial unix /var/run/docker/swarm/control.sock: connect: no such file or directory\". Reconnecting..." module=grpc
Jun 18 16:54:04 moss-0001 dockerd[4047]: time="2024-06-18T16:54:04.084389703+08:00" level=error msg="failed to remove node" error="rpc error: code = Aborted desc = dispatcher is stopped" method="(*Dispatcher).Session" node.id=m7p80vzt9krzz9o9tia7972a4 node.session=a6ch3h812r23c5wahjw12e4l0
Jun 18 16:54:04 moss-0001 dockerd[4047]: time="2024-06-18T16:54:04.084423587+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc000d15500, TRANSIENT_FAILURE" module=grpc
Jun 18 16:54:04 moss-0001 dockerd[4047]: time="2024-06-18T16:54:04.084614208+08:00" level=error msg="failed to receive changes from store watch API" error="rpc error: code = Unknown desc = context canceled"
Jun 18 16:54:04 moss-0001 dockerd[4047]: time="2024-06-18T16:54:04.085089050+08:00" level=info msg="Manager shut down" module=node node.id=n09yo5hghhwxuq1ub26spp1at
Jun 18 16:54:04 moss-0001 dockerd[4047]: time="2024-06-18T16:54:04.085142553+08:00" level=warning msg="grpc: addrConn.transportMonitor exits due to: context canceled" module=grpc
Jun 18 16:54:04 moss-0001 dockerd[4047]: time="2024-06-18T16:54:04.361178552+08:00" level=info msg="Node 9041e40f9e98 change state NodeActive --> NodeLeft"
Jun 18 16:54:04 moss-0001 dockerd[4047]: time="2024-06-18T16:54:04.361226540+08:00" level=info msg="moss-0001(9041e40f9e98): Node leave event for 9041e40f9e98/172.78.78.8"
Jun 18 16:54:04 moss-0001 dockerd[4047]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 18 16:54:04 moss-0001 dockerd[4047]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x56408cb68044]
Jun 18 16:54:04 moss-0001 dockerd[4047]: goroutine 828 [running]:
Jun 18 16:54:04 moss-0001 dockerd[4047]: panic({0x56408d8cf5c0, 0x56408ea6b160})
Jun 18 16:54:04 moss-0001 dockerd[4047]:         /usr/lib/golang/src/runtime/panic.go:1147 +0x3a8 fp=0xc0021d5d60 sp=0xc0021d5ca0 pc=0x56408bfeb208
Jun 18 16:54:04 moss-0001 dockerd[4047]: runtime.panicmem(...)
Jun 18 16:54:04 moss-0001 dockerd[4047]:         /usr/lib/golang/src/runtime/panic.go:221
Jun 18 16:54:04 moss-0001 dockerd[4047]: runtime.sigpanic()
Jun 18 16:54:04 moss-0001 dockerd[4047]:         /usr/lib/golang/src/runtime/signal_unix.go:735 +0x327 fp=0xc0021d5db0 sp=0xc0021d5d60 pc=0x56408c0020e7
Jun 18 16:54:04 moss-0001 dockerd[4047]: github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb.(*NetworkDB).rejoinClusterBootStrap(0xc002116a20)
Jun 18 16:54:04 moss-0001 dockerd[4047]:         /root/rpmbuild/BUILD/components/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb/cluster.go:305 +0x4c4 fp=0xc0021d5f00 sp=0xc0021d5db0 pc=0x56408cb68044
Jun 18 16:54:04 moss-0001 dockerd[4047]: github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb.(*NetworkDB).rejoinClusterBootStrap-fm()
Jun 18 16:54:04 moss-0001 dockerd[4047]:         /root/rpmbuild/BUILD/components/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb/cluster.go:284 +0x26 fp=0xc0021d5f18 sp=0xc0021d5f00 pc=0x56408cb8bb46
Jun 18 16:54:04 moss-0001 dockerd[4047]: github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb.(*NetworkDB).triggerFunc(0xc002116a20, 0xdf8475800, 0xc001513140, 0xc001281460)
Jun 18 16:54:04 moss-0001 dockerd[4047]:         /root/rpmbuild/BUILD/components/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb/cluster.go:256 +0x112 fp=0xc0021d5fb0 sp=0xc0021d5f18 pc=0x56408cb67832
Jun 18 16:54:04 moss-0001 dockerd[4047]: github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb.(*NetworkDB).clusterInit·dwrap·4()
Jun 18 16:54:04 moss-0001 dockerd[4047]:         /root/rpmbuild/BUILD/components/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb/cluster.go:178 +0x32 fp=0xc0021d5fe0 sp=0xc0021d5fb0 pc=0x56408cb67012
Jun 18 16:54:04 moss-0001 dockerd[4047]: runtime.goexit()
Jun 18 16:54:04 moss-0001 dockerd[4047]:         /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0021d5fe8 sp=0xc0021d5fe0 pc=0x56408c01faa1
Jun 18 16:54:04 moss-0001 dockerd[4047]: created by github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb.(*NetworkDB).clusterInit
Jun 18 16:54:04 moss-0001 dockerd[4047]:         /root/rpmbuild/BUILD/components/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb/cluster.go:178 +0x7e5
Jun 18 16:54:04 moss-0001 dockerd[4047]: goroutine 1 [chan receive, 5 minutes]:
Jun 18 16:54:04 moss-0001 dockerd[4047]: runtime.gopark(0xc000f21918, 0x56408bfc1c14, 0x18, 0x0, 0x7fc622c6bd08)
Jun 18 16:54:04 moss-0001 dockerd[4047]:         /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc0022af898 sp=0xc0022af878 pc=0x56408bfee136
Jun 18 16:54:04 moss-0001 dockerd[4047]: runtime.chanrecv(0xc000b9a000, 0xc000f21bf8, 0x1)
Jun 18 16:54:04 moss-0001 dockerd[4047]:         /usr/lib/golang/src/runtime/chan.go:576 +0x56c fp=0xc0022af928 sp=0xc0022af898 pc=0x56408bfbaf2c
Jun 18 16:54:04 moss-0001 dockerd[4047]: runtime.chanrecv1(0xc000b33740, 0xc001481a10)
Jun 18 16:54:04 moss-0001 dockerd[4047]:         /usr/lib/golang/src/runtime/chan.go:439 +0x18 fp=0xc0022af950 sp=0xc0022af928 pc=0x56408bfba958
Jun 18 16:54:04 moss-0001 dockerd[4047]: main.(*DaemonCli).start(0xc000b33740, 0xc0002a3da0)
Jun 18 16:54:04 moss-0001 dockerd[4047]:         src/github.com/docker/docker/cmd/dockerd/daemon.go:338 +0x148b fp=0xc0022afd78 sp=0xc0022af950 pc=0x56408d3f416b
Jun 18 16:54:04 moss-0001 dockerd[4047]: main.runDaemon(...)
Jun 18 16:54:04 moss-0001 dockerd[4047]:         src/github.com/docker/docker/cmd/dockerd/docker_unix.go:7
Jun 18 16:54:04 moss-0001 dockerd[4047]: main.newDaemonCommand.func1(0xc000a9fb80, {0xc000293e00, 0x8, 0x8})
Jun 18 16:54:04 moss-0001 dockerd[4047]:         src/github.com/docker/docker/cmd/dockerd/docker.go:29 +0x5c fp=0xc0022afda0 sp=0xc0022afd78 pc=0x56408d3f8dfc
Jun 18 16:54:04 moss-0001 dockerd[4047]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc000a9fb80, {0xc00013c010, 0x8, 0x8})
Jun 18 16:54:04 moss-0001 dockerd[4047]:         /root/rpmbuild/BUILD/components/engine/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:762 +0x60e fp=0xc0022afe60 sp=0xc0022afda0 pc=0x56408d3e93ce
Jun 18 16:54:04 moss-0001 dockerd[4047]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000a9fb80)
Jun 18 16:54:04 moss-0001 dockerd[4047]:         /root/rpmbuild/BUILD/components/engine/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:852 +0x2dc fp=0xc0022aff18 sp=0xc0022afe60 pc=0x56408d3e98dc
Jun 18 16:54:04 moss-0001 dockerd[4047]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(...)
Jun 18 16:54:04 moss-0001 dockerd[4047]:         /root/rpmbuild/BUILD/components/engine/.gopath/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:800
Jun 18 16:54:04 moss-0001 dockerd[4047]: main.main()
Jun 18 16:54:04 moss-0001 dockerd[4047]:         src/github.com/docker/docker/cmd/dockerd/docker.go:70 +0xca fp=0xc0022aff80 sp=0xc0022aff18 pc=0x56408d3f8f0a
.......
Jun 18 16:54:12 moss-0001 systemd[1]: docker.service: Main process exited, code=killed, status=6/ABRT
Jun 18 16:54:12 moss-0001 systemd[1]: docker.service: Failed with result 'signal'.
Jun 18 16:54:12 moss-0001 systemd[1]: docker.service: Unit process 4070 (containerd) remains running after unit stopped.
Jun 18 16:54:12 moss-0001 systemd[1]: docker.service: Unit process 4401 (containerd-shim) remains running after unit stopped.
Jun 18 16:54:12 moss-0001 systemd[1]: docker.service: Unit process 4466 (containerd-shim) remains running after unit stopped.

at the moment the Linux system message log file print:
 error during connect: Post "http://%2Fvar%2Frun8%2Fdocker.sock/v1.39/swarm/leave?force=1": EOF
