### ISSUE TITLE
implement docker build --name=<own_container_name>

### ISSUE THREAD

**Issue by olivpass** [moby/moby#39256]
**Description**

I implement project falco (see: https://sysdig.com/opensource/falco/) in my swarm. Now i see all activities of my conainer. For example: the normal running container should not do package updates. The build container must do this. Falco can show all package updates and i want to only allow build container updates. This is possible if they have a defined name. So i need the possibility to set the build container name.

**Steps to reproduce the issue:**

docker build -t some/tag:latest .

**Describe the results you received:**

docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
14da52ed2797        1a680164cd6f        "/bin/sh -c 'set -x …"   24 seconds ago      Up 23 seconds                           ecstatic_heisenberg

**Describe the results you expected:**

Please implement:
docker build --name=my_container_name -t some/tag:latest .

I expect:
docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
14da52ed2797        1a680164cd6f        "/bin/sh -c 'set -x …"   24 seconds ago      Up 23 seconds                           my_container_name

**Comment by thaJeztah** [comment]
I don't think this is something we want to implement; with the migration to BuildKit, no temporary containers will be created during build (at least, not visible in `docker ps ` / `docker container ls`). However, given that BuildKit (which can currently be enabled by setting the `DOCKER_BUILDKIT=1` environment variable on the client that starts the build) does not create containers, this could actually address your use-case, because the only containers that are created will be those that are actually started as a regular container (or part of a service).

If you don't want modifications to be made to a container, you might also consider starting your containers with the `--read-only` option, which makes their filesystem read-only (you can set a volume for those paths that should be writable if needed)

**Comment by olivpass** [comment]
You are right, i will give DOCKER_BUILDKIT=1 a try! Thanks

**Comment by thaJeztah** [comment]
Let me close this one for now for housekeeping, but feel free to continue the conversation if there's something that's not resolved by BuildKit for your use-case 👍
