### ISSUE TITLE
Missing OAS (swagger.yaml) for UCP api

### ISSUE THREAD

**Issue by gprossliner** [moby/moby#39260]
After searching all over the web (github, stackoverflow, docker.com and google), I was not able to find the swagger.yaml for the UCP API (Version 3.1).

The Engine API can be downloaded form https://github.com/docker/engine/blob/master/api/swagger.yaml

The UCP API can be browsed from
https://docs.docker.com/datacenter/ucp/3.0/reference/api/

But there is no download link, and I was not able to locate it in github.

Please provide this file, so that proxy code can be generated.
Thank you.

**Comment by thaJeztah** [comment]
UCP is a closed source product, and not maintained in this repository. The Swagger is embedded in the main.js script (https://docs.docker.com/datacenter/ucp/3.0/reference/api/main.js), but it might be worth opening an issue in the documentation repository's issue tracker to inform if it could be added as a downloadable version; https://github.com/docker/docker.github.io/issues

I'll close this issue here, but feel free to continue the conversation

**Comment by gprossliner** [comment]
Hi!

Thank you for the hint of the embedded content in the .js file. I actually did a Network Inspection on the UI, but expected a .yaml file to be fetched.

**Comment by gprossliner** [comment]
A last comment: If you are on a actual UCP instance (also the online demo works), the spec can be fetched from https://<ucpinstance>/apidocs/docs.json.

**Comment by thaJeztah** [comment]
Ah, great; if that's not documented (or not clearly documented), might still be worth opening a ticket for that in the documentation issue tracker 👍
