### ISSUE TITLE
systemctl start docker 

### ISSUE THREAD

**Issue by lb7517** [moby/moby#39314]
systemctl start docker is failing

docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since 二 2019-06-04 14:31:08 CST; 10min ago
     Docs: https://docs.docker.com
  Process: 2184 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=killed, signal=TERM)
 Main PID: 2184 (code=killed, signal=TERM)

6月 04 14:31:08 localhost.localdomain systemd[1]: Starting Docker Application Container Engine...
6月 04 14:31:08 localhost.localdomain systemd[1]: Stopped Docker Application Container Engine.

**Comment by Crazykulou** [comment]
i hava this issues too,did you resolve it?

**Comment by thaJeztah** [comment]
Unfortunately, the output of `systemctl start` usually doesn't provide a lot of information _why_ a service failed to start. I'd recommend using `journalctl` to get the actual logs of the service, for example;

```
journalctl -xu docker.service
```

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

With the current information, this looks like a support question, and there's not enough information to make this actionable (might be a configuration issue, or something specific to your setup).

I'm closing this issue because of the above, but feel free to continue the conversation
