### ISSUE TITLE
apparmor_parser docker-default  unexpected TOK_ID, expecting TOK_END_OF_RULE

### ISSUE THREAD

**Issue by ChenLong2014** [moby/moby#39408]
I need using apparmor file to operate the Docker container, in order to get the permission of /dev/fuse. 

So when I use 
`apparmor_parser -r -W /etc/apparmor.d/containers/docker-default`

the error comes out :`docker-default at line 11: syntax error, unexpected TOK_ID, expecting TOK_END_OF_RULE`

My apparmor file is:

```
#include <tunables/global>

profile docker-default flags=(attach_disconnected,mediate_deleted) {

  #include <abstractions/base>
  network,
  capability,
  file,
  umount,

  deny @{PROC}/{*,**^[0-9*],sys/kernel/shm*} wkx,
  deny @{PROC}/sysrq-trigger rwklx,
  deny @{PROC}/mem rwklx,
  deny @{PROC}/kmem rwklx,
  deny @{PROC}/kcore rwklx,
  deny mount,
  deny /sys/[^f]*/** wklx,
  deny /sys/f[^s]*/** wklx,
  deny /sys/fs/[^c]*/** wklx,
  deny /sys/fs/c[^g]*/** wklx,
  deny /sys/fs/cg[^r]*/** wklx,
  deny /sys/firmware/efi/efivars/** rwklx,
  deny /sys/kernel/security/** rwklx,
}
```

This is a default file, I have no idea what is wrong with it?

**Comment by thaJeztah** [comment]
What version of Docker do you have installed? That profile looks to be a very old version (I see the `/sys/firmware/efi/efivars` line was modified 3 years ago in https://github.com/moby/moby/commit/693b4ac67ad0638be9defbae771f62d860380f31, so the profile must be older than that)

**Comment by thaJeztah** [comment]
Actually, looks like it's even older than https://github.com/moby/moby/commit/2b4f64e59018c21aacbf311d5c774dd5521b5352 (https://github.com/moby/moby/pull/19069)

Looks like that PR fixed the line that's failing, which was reported in https://github.com/moby/moby/issues/19494

I'm gonna close this issue, because this looks to be a very old version of docker that you're running, and I suspect this has been fixed since; feel free to comment after I closed if you're still seeing this on a current version of Docker

**Comment by ChenLong2014** [comment]
Hi thaJeztah,
 Thanks for your response~~~
 My docker version is:
 Version:           18.09.5
 OS/Arch:          linux/amd64

**Comment by ComposerizeAllTheThings** [comment]
I solved the similar error, because I created the AppArmor profile on Windows, so I had to do `dos2unix`

`AppArmor parser error for filearmor in profile filearmor  at line 16: syntax error, unexpected TOK_ID, expecting TOK_END_OF_RULE`
