### ISSUE TITLE
Prepopulating bind mounts

### ISSUE THREAD

**Issue by gotjoshua** [moby/moby#39410]
This is a feature request and/or request for clear rationale for the [current policy to only pre-populate](https://github.com/moby/moby/blob/e511b3be894465d81c21cab35b4f292d9250a4ca/daemon/create_unix.go#L84) named volumes of the type `mounttypes.TypeVolume`.

Why is that the policy?

Will you consider to also pre-populate bind mounts that are empty at container start?

Especially for dev, I prefer to be able to have all volumes as subdirectories where the docker-compose file sits.

**Comment by thaJeztah** [comment]
It's because when bind-mounting a directory from the host, you're giving the container access to the files that exist in the location you're bind-mounting; the host path is "leading" in that case. docker should not touch files on the host by itself.

When using a _volume_, you're asking docker to create a managed storage location to store files from the container's filesystem. In that case, the _container_ is "leading", and files will be copied to initialise the volume on the first run.

Changing that behavior is not something that we'd accept, so I'll close this issue for the reasons outlined above.

Having said the above, you _can_ work around this by defining a volume that uses a custom storage location; see the discussion in https://github.com/moby/moby/issues/19990, and the example in this comment: https://github.com/moby/moby/issues/19990#issuecomment-248955005

first create a "volume" that uses the specified path on the host (this would be the host-path that you're mounting) (I think the host-path must exist before creating the volume);

```
docker volume create --opt type=none --opt device=<host path> --opt o=bind myvolume
```

Then, start your container using that volume;

```
docker run -v myvolume:/container/path myimage
```


closing, but feel free to continue the conversation

**Comment by gotjoshua** [comment]
Thanks for the detailed explanation!

I do understand the logic and accept the current _default behavior_, now that i understand.

However:
1) As I read [the code](https://github.com/moby/moby/blob/e511b3be894465d81c21cab35b4f292d9250a4ca/daemon/create_unix.go#L84):
```go
if mnt.Type != mounttypes.TypeVolume || !mnt.CopyData {
    continue // without populating
}
```
 (and my tests confirm) a bind mount using the syntax you suggest will NOT prepopulate (i guess because it will be of mounttypes.TypeBind).

2) I would seriously love an _option_ to pre-populate an empty volume (if i explicitly set mnt.ForcePopulate='true' it could indicate that i want the default data from the container to be copied into the volume, if it is empty or not-existing - independent of what volume type it is...)

[the line in question](https://github.com/moby/moby/blob/e511b3be894465d81c21cab35b4f292d9250a4ca/daemon/create_unix.go#L84) could be changed to something like:
```go
if !ForcePopulate && ( mnt.Type != mounttypes.TypeVolume || !mnt.CopyData ) {
    continue // without populating
} // else proceed to populate
```

This seems like a very benign request, could you consider an additional volume option?

If so, for me it would be important that it also makes it into a V2 update,
as I am not swarming at all ; -)
