### ISSUE TITLE
How can I relate domain with an external IP in Swarm service

### ISSUE THREAD

**Issue by xq840622** [moby/moby#39472]
In k8s, I can visit an external domain by create an endpoint with external IP;
How can I do it in swarm?

**Comment by thaJeztah** [comment]
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation
