### ISSUE TITLE
error connecting to legacy link graph DB

### ISSUE THREAD

**Issue by timyinshi** [moby/moby#39536]
**Describe the results you received:**
when i start docker,it has the error:
Error starting daemon: error connecting to legacy link graph DB /var/lib/docker/linkgraph.db, container links may be lost: disk I/O error
7月 16 14:49:39 localhost systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE

i want to know how to sovle the error?

**Describe the results you expected:**
i want to start the docker

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7
 Git commit:   ceb9e24-unsupported
 Built:        Mon Sep 25 15:25:16 2017
 OS/Arch:      linux/mips64le

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7
 Git commit:   ceb9e24-unsupported
 Built:        Mon Sep 25 15:25:16 2017
 OS/Arch:      linux/mips64le
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 149
 Running: 83
 Paused: 0
 Stopped: 66
Images: 58
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: false
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6c463891b1ad274d505ae3bb738e530d1df2b3c7
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe-dirty (expected: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe)
init version: 949e6fa
Kernel Version: 3.10.0-862.9.1.ns7_4.37.mips64el
Operating System: NeoKylin Linux Server 7.0 (loongson)
OSType: linux
Architecture: mips64el
CPUs: 8
Total Memory: 31.23 GiB
Name: localhost
ID: QWSA:7ETN:XXAF:QRK3:24H3:KHSI:E6MO:YSGV:3M6U:RF3Y:OFLT:7MJ2
Docker Root Dir: /var/lib/docker-2
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 registry.icp.com:5000
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
kernel:Linux localhost 3.10.0-862.9.1.ns7_4.37.mips64el #1 SMP PREEMPT Tue Feb 26 19:23:39 CST 2019 mips64el mips64el mips64el GNU/Linux

**Comment by thaJeztah** [comment]
That error comes from a migration step that was in Docker 17.03 to migrate from the old SQLite database that was used until docker 1.9 SQLite was removed 4 years ago on https://github.com/moby/moby/pull/16032 

Looks like that database is either corrupted, or a very old version (and not migrated to a more recent schema); https://github.com/moby/moby/blob/v17.03.2-ce/daemon/links_linux.go#L51-L72

If you were running an older version of Docker before this, you can try upgrading incrementally (one version at a time) to see if it's able to migrate the database-schema, but note that;

- Docker 17.03 has reached EOL in june 2016 and hasn't been maintained since. It also has known vulnerabilities that are unpatched, including a container escape
- You look to be running a custom build of docker 17.03 with modifications (`ceb9e24-unsupported`), and on an architecture that isn't tested or supported (`mips64el`)

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because of the above, but feel free to continue the conversation
