### ISSUE TITLE
Rootless Mode supported on OSX? Difference between user?

### ISSUE THREAD

**Issue by dm17** [moby/moby#39619]
1) Does rootless mode work on an OSX host? 
2) What is the actual difference between rootless mode and just building & running as a user that is created in the Dockerfile?
Thanks!

**Comment by cpuguy83** [comment]
DockerForMac kind of is rootless in that it runs unprivileged on OS X inside a vm.
The one caveat is it installs some networking related stuff that does require root to do, but after that no root is required

However, this is very different than the rootless you are thinking of.
Docker itself running in rootless mode means dockerd runs as an unprivileged user. It means that a compromised dockerd is not able to trash the entire system.

Running a container with a non-root user, while good to do, still has issues in regard to how dockerd itself manages that container.
Since dockerd typically does privileged things it can be vulnerable to exploits which have a system wide affect dockerd is itself not running unprivileged. See the recent cve's which can demonstrate that.

So... can Docker for Mac run rootless?
Not the rootless that we've been talking about, but it is essentially rootless as far as MacOS is concerned, as mentioned above.
You could also run docker-in-docker where the inner docker is rootless.
