### ISSUE TITLE
Releases / Tags for this repository and associated repositories

### ISSUE THREAD

**Issue by dims** [moby/moby#39632]
Kubernetes vendors a bunch of repositories from the docker ecosystem. Currently we have "random" SHA(s) since all the following repositories only have tags that are pretty old!

- https://github.com/moby/moby/tags
- https://github.com/docker/distribution/tags
- https://github.com/docker/go-connections/tags
- https://github.com/docker/go-units/tags
- https://github.com/docker/libnetwork/tags

Every time we want update what we use in kubernetes, we do the following dance:
https://github.com/kubernetes/kubernetes/pull/75843#issuecomment-482135433

There must be a better way right? If so, can you please guide us?

cc @estesp @thaJeztah @ddebroy

**Comment by AkihiroSuda** [comment]
Currently the releases are tagged in https://github.com/docker/engine/releases

We have been also discussing having release on this repo as well. https://github.com/moby/moby/pull/38620

**Comment by thaJeztah** [comment]
Thanks @AkihiroSuda - yes, the https://github.com/docker/docker-ce repository is only used for packaging (the components that make up the Docker CE release are collected there, and stitched together for packaging)

When vendoring from the docker/engine repository, you probably still need to pin to the commit that's matching a tag, because the Docker releases don't use SemVer, which go mod doesn't like.

As to the other repositories;

- https://github.com/docker/distribution
  Work for the 2.8.0 release is being tracked in this milestone; https://github.com/docker/distribution/milestone/19
- https://github.com/docker/go-connections
  Docker (and this repository) currently uses the 0.4.0 tag; there's some changes in master, so I can discuss if a new release should be tagged
- https://github.com/docker/go-units
  The 0.4.0 tag corresponds with what's currently in master, and also what's used by the current Docker version; https://github.com/docker/engine/blob/v19.03.0/vendor.conf#L19
- https://github.com/docker/libnetwork
  Please do not use the tags from that repository; they are very old, and not used for the vendored code. If you want to have libnetwork commits that correspond to Docker releases, make sure to vendor by the git commit that's found in the vendor.conf; https://github.com/docker/engine/blob/v19.03.0/vendor.conf#L41-L42
  We maintain branches on the libnetwork repository to which fixes are backported, so for example, the 18.09 version of docker vendors from the `bump_18.09` branch in libnetwork; https://github.com/docker/engine/blob/v18.09.7/vendor.conf#L39-L40
  That said, I don't think the API client requires libnetwork anymore (see https://github.com/docker/cli/commit/44ac80881f1cd9375b21a5ad8a2b8e496d0afa7a / https://github.com/docker/cli/pull/155)

**Comment by dims** [comment]
Lots of great information @thaJeztah ! will go through one more iteration and ask more questions if needed.
