### ISSUE TITLE
Suspicious privilege escalation dialog after update [Docker for Mac]

### ISSUE THREAD

**Issue by henrahmagix** [moby/moby#39648]
**Description**

![Pasted_Image_01_08_2019__17_47](https://user-images.githubusercontent.com/1429026/62311772-7863cd00-b484-11e9-9a98-97dc3c754161.png)

I quit docker and restarted. It asked me if I wanted to update, so I confirmed. The update downloaded and asked me to install and relaunch: I confirmed.

The top dialog appeared, which I have seen before, so I clicked "OK" and the bottom dialog appeared. It immediately stood out to me as not looking quite right, so I chose not to input my user password in case of an attacker gaining access to my computer.

I cannot start Docker.app because the only options are to input my password or click "Exit".

**Steps to reproduce the issue:**
1. Be on a Mac
2. Update Docker for Mac
3. See request for privilege escalation: submit button has no text and is not aligned with the cancel button, which raises alarm.

**Describe the results you received:**
Alarming privilege escalation dialog.

**Describe the results you expected:**
A privilege escalation dialog that does not look suspicious.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:18:17 2019
 OS/Arch:           darwin/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
@thaJeztah Can you route this?

**Comment by thaJeztah** [comment]
ping @mat007 @zappy-shu PTAL

**Comment by thaJeztah** [comment]
(also looks like the buttons aren't aligned vertically)

**Comment by olegburov** [comment]
@henrahmagix what version of macOS are you running on? Is it macOS Catalina `10.15` (preview)?

**Comment by jasonmp85** [comment]
Ok, be honest. Are you using the standard macOS facilities for requesting admin access in order to briefly escalate privileges or install a helper tool? If so, this dialog is standard.

Or, are you trying to _mimic_ said dialog in a way you can get my password and keep it around for later escalations?

Do you want to be the next Dropbox, or zoom?

I'd prefer a fast answer to the first two questions, because right now I can't use Docker and I want to know whether I can proceed or should, I don't know, suggest your binary to my company for blacklisting.

**Comment by henrahmagix** [comment]
@olegburov 	I'm on Mojave 10.14.5

@jasonmp85 My thoughts exactly. Is it likely to be in the source code here? Does anyone know an Apple UI developer who can confirm?

**Comment by gtardif** [comment]
IIRC that is the system dialog you get from SMJobBless. For some reason the button label is sometimes missing (and misaligned!) and I don’t know if there’s anything we can do about it :disappointed: the top dialog is definitely ours and has proper button labels as you would expect :)

**Comment by Drarok** [comment]
@gtardif not sure if this repo is the right place to be looking, but `SMJobBless` doesn't appear in this repo at all?

![Screenshot 2019-08-02 at 10 16 44](https://user-images.githubusercontent.com/55830/62359422-a7bf1c00-b50e-11e9-94c8-ba2b0beeede5.png)

**Comment by thaJeztah** [comment]
@Drarok this repository only contains the code for the Docker Engine. Docker Desktop (Docker for Mac / Docker for Windows) contains many other components (some of which, including the UI components, are closed-source and in a private repository)

**Comment by thaJeztah** [comment]
Oh, and to prevent confusion; `SMJobBless` is part of the Apple SDK; https://developer.apple.com/documentation/servicemanagement/1431078-smjobbless

**Comment by djs55** [comment]
Hi,

Here's my summary of the situation:

As @thaJeztah says, Docker Desktop on Mac contains
- the Docker Engine (from this repository)
- install/uninstall/upgrade logic (in a private repo)
- a UI (in a private repo)
- a hypervisor (https://github.com/moby/hyperkit)
- a networking stack (https://github.com/moby/vpnkit)
- Kubernetes
- LinuxKit (https://github.com/linuxkit/linuxkit)
- ...

The Docker Desktop install is a standard macOS app install i.e. the user has to
- open the Docker.dmg
- drag the application to /Applications (or wherever)

However the installation is not really complete at this point because we still need to create symlinks:
- /var/run/docker.sock -> the socket where the Docker API is exposed
- /usr/local/bin/docker* -> the binary locations, so `docker` is on the `$PATH`

The symlinks are created when the app is launched, via the "privileged helper tool", `com.docker.vmnetd` (the slightly strange name is because this process also used to be the interface to the `vmnetd.framework` which use used to use for VM virtual networking and which required `root`. We now use a userspace networking stack which runs as a regular user so this old `vmnetd.framework` code is gone but the name remains).

To avoid having to handle user credentials, we use the macOS API [SMJobBless](https://developer.apple.com/documentation/servicemanagement/1431078-smjobbless?language=objc) to install `com.docker.vmnetd` and register it with `launchd`. `com.docker.vmnetd` exposes a simple API which we can talk to to request it to install the symlinks. The documentation online for `SMJobBless` is a bit sparse and it's quite a difficult API to use but there are a few blog posts talking about it e.g. http://atnan.com/blog/2012/02/29/modern-privileged-helper-tools-using-smjobbless-plus-xpc/ The `SMJobBless` API triggers the system dialog (somehow internally) which requests the user password and installs the helper tool. Since we don't get any control over how this dialog is presented (for security reasons) we first display an explanatory dialog to tell the user what to expect (after all no-one likes unexplained unsolicited requests for their password!)

![Screenshot 2019-08-05 at 10 32 11](https://user-images.githubusercontent.com/198586/62455743-f5d25a80-b76e-11e9-800d-6ee70552669d.png)

Once the user has been warned what to expect, we call `SMJobBless` and the system asks for the password:

![Screenshot 2019-08-05 at 10 32 52](https://user-images.githubusercontent.com/198586/62455817-18647380-b76f-11e9-9f2d-2e730753cf5e.png)

(On my machine the button + label is also messed up but I'm not sure why since this is a system dialog and not under our control. It's possible this error has become more frequent in Mojave . Or perhaps there's something wrong with the application bundle which is triggering it? )

If all is well the `com.docker.vmnetd` process is installed and we can talk to it. Unfortunately we've experienced lots of bugs in this mechanism over the years we've been using it. Sometimes the helper tool ends up partially-installed and has to be manually removed before the `SMJobBless` API will work again. When this happens we display a dialog telling the user what to type, since we can't do it for them (since we don't have the credentials by design).

For interest, the snippet of Swift code where we call the API looks like this:

```swift
let result = SMJobBless(kSMDomainSystemLaunchd, vmnetdBundleIdentifier as CFString, authRef, &err)
if let error = err?.takeRetainedValue() {
     log.error("cannot register new process: \(error.localizedDescription)")
     switch CFErrorGetCode(error) {
     case kSMErrorJobMustBeEnabled:
         // Display a dialog box showing the user how to perform a manual removal of the privileged helper tool
         // in the hope it will work again after that.
         ...
     default:
         // Some other fatal error
     }
}
```

## Plans for the future

The vast majority of the code in Docker Desktop (the hypervisor, the VM, the Docker engine, the containers) all run unprivileged from the macOS host point of view (compare this with Linux where the Docker engine must run as root on the host). We'd like to remove (or at least only install/use if necessary) the remaining code which requires root (i.e. the `com.docker.vmnetd` helper). For example the latest Docker engine supports easily changing the `/var/run/docker.sock` path via `docker context`, so we can avoid making a symlink there. Also many users have already changed the permissions of `/usr/local/bin` (e.g. by installing homebrew) so we don't often need `root` to do that ourselves.
We also use the `com.docker.vmnetd` to bind privileged ports (< 1024) (e.g. `docker run -p 80:80 nginx`) but on macOS Mojave this is nolonger necessary.

We'll make it so that the `com.docker.vmnetd` helper is only installed when it's actually needed, which on many/most systems will be not at all.

## Summary

- the dialog is a system one, from `SMJobBless`
- the misaligned button and missing label appears to be a macOS bug in `SMJobBless` (although I don't know if it's triggering more often)
- we don't handle macOS credentials in the Docker Desktop app
- we run some small amount of code as `root` (for installing symlinks and binding ports) but we are aiming to reduce that over time (and remove it altogether if possible)

I hope that helps!

**Comment by henrahmagix** [comment]
@djs55 	Thank you very much, that is a _superbly_ clear explanation. I appreciate the transparency and the goal of removing privilege requirements altogether =)

**Comment by dmolesUC** [comment]
For anyone finding this issue who wants further confirmation, here's a [thread on the Apple developer forums](https://forums.developer.apple.com/thread/44873) about this issue, from 2016.

**Comment by cpuguy83** [comment]
I'm going to close this since it doesn't seem to be anything to do here, but feel free to comment.
Thanks all! 😇
