### ISSUE TITLE
`Copy`ing a directory with symlinks does not follow only adds them leading to broken links.

### ISSUE THREAD

**Issue by kairichard** [moby/moby#39810]
**Description**
`Copy`ing a directory with symlinks pointing to another directory *inside* the build context fails to add the actual content of the symlinks when the other directory is not copied. 

**Steps to reproduce the issue:**
Given the following dockerfile
```dockerfile
FROM busybox
COPY dir2 /dir2
```
And following project structure
```bash
├── Dockerfile
├── dir1
│   └── file1.txt
└── dir2
    └── file.txt -> ../dir1/file1.txt
```
Running the following command
```bash
docker build . -t test && docker run -it test cat /dir2/file.txt
cat: can't open '/dir2/file.txt': No such file or directory
```
**Describe the results you expected:**

I am a little surprised why this didn't work. There are very good reasons not to follow symlinks. But given that the path is inside the context I would have expected this to work.
A workaround for this is of course to copy the file explicitly e.g. `COPY dir2/file.txt /dir2/file.txt` which works *and* thus must follow the symlink. 
There seem to be no obvious documents/issues on this behavoir that explain why this choice was made. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
>> docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:18:17 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:17:52 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 256
  Running: 1
  Paused: 0
  Stopped: 255
 Images: 386
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 992.7MiB
 Name: docker-desktop
 ID: VZLD:ARD5:5T5W:PY4V:2E53:PMIS:ZF7D:KBLL:XYLX:UOEW:BQK5:6OXI
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 38
  Goroutines: 52
  System Time: 2019-08-28T10:21:02.2288156Z
  EventsListeners: 2
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by thaJeztah** [comment]
The "symlinks inside a directory" example is expected, and by design; there are many use-cases where that's the desired behavior (otherwise it would not be possible to copy symlinks into the container)

As to your workaround; I'd have to check history on that behavior (resolving the symlink to the file)

@tonistiigi perhaps you recall the reason we do resolve the final target before copying?

**Comment by tonistiigi** [comment]
> perhaps you recall the reason we do resolve the final target before copying?

It is resolved if you are copying a symlink, not if you copy a directory containing a symlink. This is just a common behavior of anything copying/extracting files like cp, rsync, tar etc. If this was not done it would mutate the original files so that some of the previous cases might not work anymore or in a simple case where you have 10 symlink pointing to the same file increase your storage requirement 10x. And if you are thinking about just copying the symlink target to its matching location, it wouldn't be possible in a lot of cases just because the matching path can't be constructed in a different destination root, and it would be a security risk for copy to write anything outside the destination directory specified in the command.

**Comment by thaJeztah** [comment]
Thanks! Let me go ahead and close this one, but feel free to continue the conversation

**Comment by kairichard** [comment]
@thaJeztah @tonistiigi Thanks for clarifying - may this helps others as well.
