### ISSUE TITLE
Dockerd eats too much RAM

### ISSUE THREAD

**Issue by goetas** [moby/moby#39916]
**Description**

Currently the `dockerd` process of a leader node is eating ~11GB of RAM.

On that node there are no scheduled containers, it participates to the cluster only as manager (currently as leader). 

**Output of `docker version`:**

```
root@vim11:/home/goetas# docker version
Client:
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        0dd43dd87f
 Built:             Wed Jul 17 17:41:13 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:20:35 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 46
Server Version: 19.03.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: 27ajn65e9o1zfla8j532wbt5b
 Is Manager: true
 ClusterID: tzm417keomjtxndqclyvsz6fd
 Managers: 3
 Nodes: 13
 Default Address Pool: 10.0.0.0/8  
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 3
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 10 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 172.16.21.231
 Manager Addresses:
  172.16.21.231:2377
  172.16.21.233:2377
  172.16.21.238:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-9-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 3
Total Memory: 15.68GiB
Name: vim11
ID: CU7J:E35G:YUKM:76S7:LYCX:2XJD:Y46P:VBXT:HD5A:UYXT:44AR:UH4Q
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
root@vim11:/home/goetas# uname -a
Linux vim11 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux
```

I saw that there are https://github.com/moby/moby/issues/32728 https://github.com/moby/moby/issues/32711 , but they refer to older versions of docker. This one is pretty recent.

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root     31186 76.5 72.1 24888568 11781872 ?   Ssl  Aug01 46401:24 /usr/bin/dockerd -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock --ip-forward=true --iptables=true 
```

How can I provide you more info to debug this?

**Comment by goetas** [comment]
Thanks for the info! Restarting the dockerd daemon solved the issue, but I expect it to be back! Will try to follow the guide provided by @kolyshkin and provide more info when it will saturate memory again!

**Comment by dperny** [comment]
I know it's a bit of a pain, so I really appreciate you getting that heap dump. If it is a memory leak, the heap dump will show it pretty obviously, and it'll be like a 5 minute fix more than likely.

**Comment by goetas** [comment]
@dperny @cpuguy83 @kolyshkin   Can you tell me if the files obtained following https://success.docker.com/article/how-do-i-gather-engine-heap-information contain sensitive data (docke secrets or env variables?)

**Comment by goetas** [comment]
Ping

**Comment by wadamek65** [comment]
We are experiencing the same issue. Our first swarm manager is using ~11 GB of memory (over 40% of which is used by `dockerd`) while `docker stats` shows not even 1 GB of memory usage. Removing all containers does not free the memory. Only restart of docker helps. This issue happens on two separate swarm environments with a similiar setup. Any updates?

**Comment by goetas** [comment]
[pprof.dockerd.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz](https://github.com/moby/moby/files/3805204/pprof.dockerd.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz)
[pprof.dockerd.alloc_objects.alloc_space.inuse_objects.inuse_space.002.pb.gz](https://github.com/moby/moby/files/3805205/pprof.dockerd.alloc_objects.alloc_space.inuse_objects.inuse_space.002.pb.gz)


Here are the heap information of our clusters, I guess this should help

**Comment by kolyshkin** [comment]
Here's the graph (generated from the 002 profile, they look similar). Unfortunately I don't know this codebase good enough to figure out what is going on, but it is clear from the pic who is using the most memory. Yet, it's about 3.5GB rather than 11GB (I guess the rest is not garbage collected yet?)

![image](https://user-images.githubusercontent.com/4522509/68152217-150c8f80-fef8-11e9-9b30-970a0ffdced2.png)

**Comment by kolyshkin** [comment]
@dperny PTAL ^^^

**Comment by goetas** [comment]
@kolyshkin the dump was done in a different moment, but I guess  3.5GB is still a bit too much for just dockerd, isn't?

**Comment by wadamek65** [comment]
Update for my case: We have resolved the issue. Our problem was a leaking container (we are running a swarm discovery service for prometheus configuration which has a volume bound to docker's socket and was constantly creating new docker clients). It was leaking memory, but for some reason docker did not show it's memory usage and also did not want to free it on container removal. Only docker restarts helped in our case before we resolved the leaking issue. Seems like creating new docker clients (in golang in our case) was problematic for docker.

**Comment by mhemrg** [comment]
In my case, dockerd is using 30GB of memory which is about 50% of the manager's total memory.
Every month, I need to restart the dockerd to temporarily fix the issue.

**Comment by mhemrg** [comment]
![profile002](https://user-images.githubusercontent.com/19375012/72603190-cd5da780-392d-11ea-9da7-404142d1abfd.png)
![profile001](https://user-images.githubusercontent.com/19375012/72603191-cd5da780-392d-11ea-8661-d71e7c67c756.png)

**Comment by thaJeztah** [comment]
@mhemrg what version of docker are you running? could you edit your comment, and:

- add the output of `docker version` and `docker info`
- attach the pprof files used to generate the images?

**Comment by mhemrg** [comment]
@thaJeztah Thank you for your reply. I've just edited my comments.

**Comment by dperny** [comment]
I am not 100% sure how to read a profile graph like this, to be completely honest, but am I seeing _over half a gig_ of _contexts_????

**Comment by dperny** [comment]
Good lord this code doesn't need debugging it needs an exorcism.

**Comment by thaJeztah** [comment]
I do notice that docker,  `containerd.io` (and `runc`) are older versions. 18.09 reached EOL, but there are more current versions (`v18.09.9` is the latest 18.09.x, and containerd.io 1.2.10 is the latest package for the 1.2.x)

**Comment by mhemrg** [comment]
@thaJeztah Do you think in the newer versions the issue might have been resolved?

**Comment by goetas** [comment]
Our set up was 19.03 and had same issue

**Comment by dperny** [comment]
@mhemrg were you using `docker service logs` at the time of taking that profile? If so, how was it being used?

**Comment by mhemrg** [comment]
@dperny I guess so. We have a multi-user set up and usually, multiple concurrent users are watching logs (5 to 10 users at the same time). But we don't use the official Docker CLI for that. We connect to the Docker API directly and we always pass these options to the service logs endpoint:
```
{
      tail: 100,
      stdout: true,
      stderr: true,
      timestamps: true,
      since: 1579623604  // Current timestamp
}
```

And the endpoint usually responds under 20ms.

**Comment by dperny** [comment]
I've been looking at this for a couple of hours. Without the ability to reproduce this, I have to be very thorough in my analysis so that any fix I try is very likely to solve the problem.

It seems that, first off, about 8 gigs of memory in use is a consequence of service logs. Service logs handling is _shockingly_ complex, which makes this a bit difficult to tease out. Additionally, I don't have a super great understanding of gRPC streams anymore. But, from what I can gather, there exists some possibility for a leak if we try to close a gRPC stream without trying to receive any messages, the stream doesn't get properly closed. 

The documentation for `(*grpc.ClientConn).NewStream` says:

>  To ensure resources are not leaked due to the stream returned, one of the following actions must be performed:
> 
> 1. Call Close on the ClientConn.
> 2. Cancel the context provided.
> 3. Call RecvMsg until a non-nil error is returned. A protobuf-generated
>    client-streaming RPC, for instance, might use the helper function
>    CloseAndRecv (note that CloseSend does not Recv, therefore is not
>    guaranteed to release all resources).
> 4. Receive a non-nil, non-io.EOF error from Header or SendMsg.
> 
> If none of the above happen, a goroutine and a context will be leaked, and grpc will not call the optionally-configured stats handler with a stats.End message. 

In the swarmkit agent, we have a function, which is supposed to close the log stream. It does not call Recv, so perhaps this is the root cause of the leak. This function is called when either the agent attempts to send logs when the context has been canceled, or when the agent explicitly cancels the log stream.

https://github.com/moby/moby/blob/063bd4c96ae633a1aa830b7f8a646b689c14e5c8/vendor/github.com/docker/swarmkit/agent/agent.go#L544-L553

However, it _should_ be the case that the context provided _is_ canceled, so I took a deeper look at that.

`Publish` function on the Agent is called from one place: the `(*agent.worker).Subscribe` method, which passes the context provided to it. This context, in turn is passed from the Agent's main run loop, in this block of code:

https://github.com/moby/moby/blob/063bd4c96ae633a1aa830b7f8a646b689c14e5c8/vendor/github.com/docker/swarmkit/agent/agent.go#L297-L314

We can see here that a new sub-context is created for each subscription, and that it should be canceled when the subscription is closed. However, taking a look at the data from the pprof profile, we can see this:

```
    297            .          .           		case sub := <-session.subscriptions: 
    298            .          .           			if sub.Close { 
    299            .          .           				if cancel, ok := subscriptions[sub.ID]; ok { 
    300            .          .           					cancel() 
    301            .          .           				} 
    302            .          .           				delete(subscriptions, sub.ID) 
    303            .          .           				continue 
    304            .          .           			} 
    305            .          .            
    306            .          .           			if _, ok := subscriptions[sub.ID]; ok { 
    307            .          .           				// Duplicate subscription 
    308            .          .           				continue 
    309            .          .           			} 
    310            .          .            
    311            .   500.52MB           			subCtx, subCancel := context.WithCancel(ctx) 
    312        221MB      221MB           			subscriptions[sub.ID] = subCancel 
    313            .          .           			// TODO(dperny) we're tossing the error here, that seems wrong 
    314            .          .           			go a.worker.Subscribe(subCtx, sub) 
```

It seems that the contexts are never getting canceled, which means that subscriptions are never get Close messages. Now the question is why?

The Logs code is complex, and its server-side respresentation is in the package `github.com/docker/swarmkit/manager/logbroker`. The agent connects to the manager, creating a stream through which the manager sends new requests for logs to the agent (the ListenSubscriptions stream). When a user requests logs, the manager creates a new stream to send logs down to the user (the SubscribeLogs stream), and send a message down the ListenSubscriptions stream asking for those logs. The agent then creates a third stream (the PublishLogs stream) through which it sends logs to the manager. The stream, in particular, that we know is not getting closed is the PublishLogs stream on the agent's side. These three streams all exist in separate concurrent routines, and communicate over a complex series of channels.

The problem is, basically, this:

* The ListenSubscriptions stream starts a watch on a queue. It knows a subscription is relevant to it if the subscription contains the NodeID of the agent.
* When a subscription is finished, it is updated to say that it is closed and then published to this queue.
* When the server side of the PublishLogs call receives a close message, it removes the node ID from the subscription.
* Therefore, if the PublishLogs call finishes before the Subscription is closed, the Close message is never sent to the agent.
* The close messages is never sent, because the Close message is only intended to stop a logs call in progress, not to clean up dangling streams.

In order to guard against leaks occurring when the manager never gets the opportunity to send the Close message (like if the manager crashes), we need to be able to cancel the context and remove it from the subscriptions map that it's being held on from. Additionally, in the interest of being Correct, we need to call Recv after we close the PublishLogs stream on the agent side. I'll make those changes and open a PR on swarmkit.

[Whoever's idea it was to take logs out of experimental, they're an idiot.](https://github.com/moby/moby/pull/32462)

**Comment by dperny** [comment]
PR is opened on Swarmkit.

**Comment by peter-slovak** [comment]
An amazing analysis, can't wait to try out the fix when it makes it to a release. Thanks so much!

**Comment by goetas** [comment]
Great work! Thanks a lot!
