### ISSUE TITLE
Add ability to bind mount with specific user,group,permission

### ISSUE THREAD

**Issue by minhtrietbkit** [moby/moby#39937]
**Use Case**
For the purpose of CI/CD, I'd like be able to `bind mount` docker socket from Docker host into container under a different user (other than root) and specific permission. This lets us use docker from inside the Docker container for various CI/CD tasks as a user other than root.

I expect something like running `docker run -v /var/run/docker.sock:/var/run/docker.sock/:<user>:<group>:<perm>`

Related to [#2259](https://github.com/moby/moby/issues/2259) but this one is a more specific case - it only deals with `bind mount` (not volume)

**Comment by AkihiroSuda** [comment]
NOTLGTM. This breaks the host environment.

**Comment by minhtrietbkit** [comment]
@AkihiroSuda Do you mean you're afraid the original file on host will be affected by the container? Are there any workarounds to this? The only solution I see now is to use root user inside container, which I want to avoid.

**Comment by AkihiroSuda** [comment]
W.r.t. `/var/run/docker.sock`, it is almost meaningless to avoid being the root, because you are already fully privileged when you have access to `/var/run/docker.sock`.

Maybe you want to use UNIX socket proxy like `socat` or write your own if you really need to change the permission.

Or maybe you want to try Rootless Docker-in-Docker (`docker:19.03-dind-rootless`)

**Comment by thaJeztah** [comment]
Yes, we can't do this, as @AkihiroSuda explained. I'll close this one, but feel free to comment after
