### ISSUE TITLE
Run docker in Android in chroot (without rooting the Andorid device)

### ISSUE THREAD

**Issue by rajibhasan11** [moby/moby#40121]
I am trying to run the docker instance in Android device with or without [rooting ](https://en.wikipedia.org/wiki/Rooting_(Android)) the device gives me similar kind of results. In different Android device armf, armv7l, aarch64 etc. I have tried.

Android version: Android 5+
Tried in Linux distro: Ubuntu 18.04 LTS arch aarch64

Guideline: https://github.com/moby/moby/blob/master/docs/rootless.md

Connected software:

**Initial try (without root privileges)**
1. Termux Android app
2. AndroNix Android app

**Other try (with root privileges):**
1. Linux deploy

In the second try I have installed the debian/ubuntu following the docker installation guidelines of docker rootlesskit but getting the below error when try to run the rootlesskit

`/home/android/bin/dockerd-rootless.sh --experimental --iptables=false`

[rootlesskit:parent] error: failed to start the child: fork/exec /proc/self/exe: invalid argument

Before that I have exported the env variables explicitly and in .bashrc:

export XDG_RUNTIME_DIR=/tmp/docker-60000
export PATH=/home/android/bin:$PATH
export PATH=$PATH:/sbin
export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock

as well as install all required dependencies in Ubuntu 18.04

Installed tar files from nightly builds:

STATIC_RELEASE_URL="https://download.docker.com/linux/static/nightly/aarch64/docker-0.0.0-20190727010531-15bdbd7.tgz"
STATIC_RELEASE_ROOTLESS_URL="https://download.docker.com/linux/static/nightly/aarch64/docker-rootless-extras-0.0.0-20190727010531-15bdbd7.tg"

**Comment by AkihiroSuda** [comment]
Android kernels are likely to be compiled without support for namespaces

**Comment by rajibhasan11** [comment]
Hi @AkihiroSuda, I have installed Linux on Android first then on that Linux I am trying to run docker instance.

**Comment by AkihiroSuda** [comment]
uname -a and zcat /proc/config.gz?

**Comment by rajibhasan11** [comment]
uname -a && zcat /proc/config.gz

Linux localhost 3.10.49-g42252ea #1 SMP PREEMPT Fri Nov 13 16:30:21 IST 2015 aarch64 aarch64 aarch64 GNU/Linux
gzip: /proc/config.gz: No such file or directory

**Comment by AkihiroSuda** [comment]
So it seems you are using Android kernel, not running real Ubuntu directly on your device.
This cannot be supported unfortunately, because Docker and RootlessKit require namespaces to be compiled in the kernel.

**Comment by FreddieOliveira** [comment]
The truth about docker is that it runs just fine in Android, as seen here:

https://gist.github.com/arno01/ebf570af208e28c1a0cf78da4f63bc9c#gistcomment-3340958

The real problem is not the kernel, since anyone can compile the kernel with the necessary features enabled. The real problem is simply that the Android OS isn't supported by docker. That's it.

When you try to run any container in Android it will complain that `no matching manifest for android/arm64 in the manifest list entries`. If you try to force to pull a Linux container passing the flag `--platform=linux/arm64`, it will complain that `operating system is not supported`. And if you patch docker source code to ignore this error and continue the pull anyway, it will crash with seg fault. This is all shown here:

https://github.com/termux/termux-root-packages/issues/60#issuecomment-636553841

The wise thing to do is to stop opening issues here  asking how to run docker in Android/chroot/qemu. This is no place for tutorial. Go learn how to compile your phone's kernel first, get rid of the fear of rooting your device and then read this discussion:

https://github.com/termux/termux-root-packages/issues/60

There you'll learn from people who already ran docker in Android the steps to take.

The wise thing to do is to ask for docker devs to start supporting Android.

**Comment by SDRausty** [comment]
@rajibhasan11  there is an alternative to docker that runs in Termux PRoot.  It is called udocker: https://www.google.com/search?q=TermuxArch+udocker
