### ISSUE TITLE
Shared image cache for running multiple docker daemons (dind)

### ISSUE THREAD

**Issue by jansmets** [moby/moby#40196]
Hi

Using a DinD on Kubernetes is a popular approach to other containers. I'm using it for CI builds.
The DinD daemon is short-lived and the image cache is empty upon startup, so you'd always have to pull in images from the registry.

This is a feature request to support a shareable 'host' volume with images that can be used RW by multiple docker/dind daemons.

**Comment by thaJeztah** [comment]
Sharing a single image store between multiple daemons (when running simultaneously) is not something that can be supported; the storage is designed to be exclusively accessed by a single daemon.

If you don't run multiple daemons at the same time, but only in sequence, then using a volume should already work.

That said, you may be interested in using BuildKit for this purpose, instead of running docker-in-docker; https://github.com/moby/buildkit some info can be found in this presentation; https://www.slideshare.net/AkihiroSuda/dockercon2019-deploying-rootless-buildkit-on-kubernetes


I'm closing this issue, because this is not something we can support, but feel free to continue the conversation
