### ISSUE TITLE
How to map 127.0.0.1 of container to IP of physical machine

### ISSUE THREAD

**Issue by Ruilkyu** [moby/moby#40216]
Question:
      Now I have a problem. I have run a program in the container that only listens to 127.0.0.1. How to map it so that other machines can access the container

**Comment by cpuguy83** [comment]
The only way to do this is to create a container with `--net=container:<name>`.
Otherwise the only way to access 127.0.0.1 is from inside that container.

I would recommend listening on all addresses, you can choose to allow access using docker networks.
https://docs.docker.com/network/network-tutorial-standalone/

**Comment by thaJeztah** [comment]
Running with `--network=host` would also work, in which case the container runs in the host's network stack; in that case the container does _not_ get it's own IP-address (or networking namespace), so there's no networking isolation. Effectively that's the same as running the process outside of a container (from the networking perspective)
