### ISSUE TITLE
Push 19.03 engine branch to this repo

### ISSUE THREAD

**Issue by cpuguy83** [moby/moby#40235]
I would like to push the 19.03 release branch to this repo.
There is not really a mechanism to create a new branch as a PR in github so I'm opening this issue to get LGTM's from maintainers.

Thanks!

**Comment by AkihiroSuda** [comment]
LGTM, but who are eligible to merge cherrypick PRs?

**Comment by cpuguy83** [comment]
Whether Docker (or Mirantis?) takes it is up to them, but the idea is anyone who can merge on this repo should be able to approve backports.

**Comment by thaJeztah** [comment]
We should probably look at;

- remaining PRs open in https://github.com/docker/engine/pulls (and if possible get those merged before we make this switch)
- bring over the tags as well
- (at least in the immediate future) make sure that https://github.com/docker/engine is (automatically) synced with this repository, so that people using https://github.com/docker/engine for vendoring will get the exact same bits (making docker/engine effectively a mirror)


@moby/moby-maintainers @andrewhsu

**Comment by cpuguy83** [comment]
Getting PR's merged is do-able, but if we keep opening new PR's this is an endless battle, so we'll need some cut-off.

**Comment by thaJeztah** [comment]
> Getting PR's merged is do-able, but if we keep opening new PR's this is an endless battle, so we'll need some cut-off.

After some thought; it would still be good to get existing PR's merged, but it's not a lot of trouble to re-open PR's in this repository for PR's that don't make the cut.

Things to work on when making this change;

- make sure CI/Jenkins runs on the release branch(es)
- (where needed) update/refresh project docs about [patch releases](https://github.com/moby/moby/blob/master/project/PATCH-RELEASES.md) and [branches](https://github.com/moby/moby/blob/master/project/BRANCHES-AND-TAGS.md).
- Set up a sync-script to keep docker/engine up-to-date. @cpuguy83 has a script that would allow doing this ([gist with script](https://gist.github.com/cpuguy83/125404c4d61a9b8c9d5a76cb1832a6b2), but we need to automate that (cron-job, likely). There is an existing Jenkinsfile in a private repository that's currently used for docker/engine, but it would be good to have that in a public repository. Given that we want the sha of the docker/engine to be exactly the same as this repository, we likely cannot commit that Jenkinsfile (or GitHub action if that works) in the repository, so probably those files should live in a separate repository.

We'll be discussing this in tomorrow's maintainers meeting to talk through the details and action-items

**Comment by thaJeztah** [comment]
@moby/moby-maintainers the plan currently is to:

1. Open a https://github.com/docker/engine-sync repository
2. Add sync-script / tooling to that repository
3. Push branches and tags to this repository
4. Enable the sync script and mark the docker/engine repository as "read-only" / "mirror"

Any objections?

**Comment by thaJeztah** [comment]
@cpuguy83 https://github.com/docker/engine-sync was created (empty repo as of now)

**Comment by cpuguy83** [comment]
I went ahead and pushed the existing 19.03 branch from docker/engine to moby/moby.
There are a few (newly opened) PR's in docker/engine for 19.03, we can sync again or re-open those here.
Definitely easier to get the PR's merged here since more people have merge access, but 🤷‍♂.

**Comment by cpuguy83** [comment]
For syncing the docker/engine branch FROM moby/moby we can do this manually for now as needed but there's also a Jenkins job already setup for syncing master (this is in some private Docker repo), this could be extended to whatever branches/tags need to be synced.

**Comment by AkihiroSuda** [comment]
Thanks 🎉 

Can we push tags as well? 

Not having 17.04+ tags may give people false sense that the project was stopped after 17.03.

**Comment by seemethere** [comment]
I agree, I think that the tags should be pushed as well, would make any `go mod` nonsense easier to stomach for this project.

**Comment by thaJeztah** [comment]
Unfortunately won't help with go mod yet (as the tags are not SemVer, and not created from master but from release branches). But at least the tags are easier to find.

@silvin-lubecki is working on a tool/script to extract the tags that only exist in the docker/docker-ce repo as well. Due to the structure of that repo, the commit-sha's won't match, but at least should give the corresponding code of each of those tags

**Comment by cpuguy83** [comment]
Maybe we can delete the year based tags and replace them with tags following the old versioning 😇.

**Comment by AkihiroSuda** [comment]
Push both year tags and semver tags?

**Comment by thaJeztah** [comment]
> Maybe we can delete the year based tags and replace them with tags following the old versioning

The year based (YY.MM) actually aren't the ones that are problematic, because they are ignored by `go mod` (so from `go mod` perspective don't exist). It's the old tags (that _look_ SemVer) that are the problem.

Go mod introduced a change in semantics; where previously `go get ...` meant: "latest version from master", it now means "get the latest SemVer release". Because of that, the old `v1.xx` tags all of a sudden got a different meaning, and `go get` would now consider those tags to be the "latest version", effectively rolling back to a very old code-base.

Perhaps `go mod` should've continued _ignoring_ those tags _unless_ a tag/repository contained a `go.mod` (in other words: this repository provides "old style" packages, but doesn't provide modules, so keep the old semantics).

> and replace them with tags following the old versioning
> Push both year tags and semver tags?

This  has quite some consequences (think I wrote down some of these elsewhere, but just for completeness);

1. Tags in this repository have always referred to the _binary_ releases, not "go packages" / "go modules". In other words; the tags refer to "the code used to build docker release X"
2. The old (`v0.xx`, `v1.xx`) tags have never been SemVer; the _format_ may be parseable as SemVer, but the project never followed SemVer.
3. Given that those tags don't directly apply to the Go API (there definitely have been breaking changes between releases); if we were to follow SemVer for use as  _go modules_, each (existing) tag (or many of them) would thus have to be a _major_ update (SemVer [requires any breaking change to increment the major version](https://semver.org/#spec-item-8))
4. Go modules on their turn require any major version to have a different import path (see [Go Modules: v2 and Beyond](https://blog.golang.org/v2-go-modules): _"By definition, a new major version of a package is not backwards compatible with the previous version. This means a new major version of a module must have a different module path than the previous version_"). **We cannot change that in retrospect**. In addition; if we want the repo to remain compatible with non-go-mod consumers, it likely would mean we'd have to move the code in `/vXX` subdirectories (which is horrible to maintain, also in light of backporting changes).
5. This repo provides a multitude of packages that people could be using individually (e.g. only `pkg/system` or `pkg/truncindex`), not all of those follow the same "stability" (i.e. `pkg/foo` may have a breaking change, but `pkg/bar` may not have: should both `pkg/foo` _and_ `pkg/bar` now become `/vXX/pkg/foo` and `/vXX/pkg/bar` ?)

**Comment by cpuguy83** [comment]
Tags are pushed for 18.06, 18.09, and 19.03!
With that, I'm going to close this.
