### ISSUE TITLE
No space left on device for temp folder

### ISSUE THREAD

**Issue by loretoparisi** [moby/moby#40325]
I get a `No space left on device` due to docker running container temp folder (found with `docker ps --space`). Considering the nature of the `temp` folder, is it possibile to handle this folder like an external volume?
Thank you.

**Comment by thaJeztah** [comment]
> found with `docker ps --space`

`docker ps` does not have a `--space` option; do you mean `--size` ?

It's unclear what you mean with

> is it possibile to handle this folder like an external volume?

Do you mean if it's possible to run the container with `-v somevolume:/tmp` ?


Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Comment by loretoparisi** [comment]
@thaJeztah yes sorry I meant to support the `/tmp` folder as a default external temporary volume with parameters. In my opinion could make sense because temporary folders are defined across all systems, and having a temporary folder's volume could avoid unwanted size growing of the docker a running docker container.
