### ISSUE TITLE
docker stack deploy fails to pull images from docker.pkg.github.com registry

### ISSUE THREAD

**Issue by DrPyser** [moby/moby#40403]
**Description**

`docker stack deploy` never seems to be able to pull images from our private registry at `docker.pkg.github.com`. We always get this error:
```
image docker.pkg.github.com/myorg/myrepo/myimage:mytag could not be accessed on a registry to record
its digest. Each node will access docker.pkg.github.com/myorg/myrepo/myimage:mytag independently,
possibly leading to different nodes running different
versions of the image.
```

* I use the command `docker login docker.pkg.github.com && docker stack deploy --with-registry-auth -c stack.yml mystack`.
* Using `docker pull docker.pkg.github.com/myorg/myrepo/myimage:mytag` works.
* Looking at the `journalctl` logs,  I don't see any related errors.

Thanks!

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:50:12 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:48:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Comment by thaJeztah** [comment]
GitHub's registry unfortunately doesn't comply with the distribution specification, and only partially implements the specification. When deploying a stack, of deploying a swarm service, the image used is resolved to its digest (immutable reference), and the service will use that reference/pull the image. 

That part of the specification is not implemented by the GitHub registry, causing that warning to be produced.

There's other parts that don't work as well, see https://github.com/containerd/containerd/issues/3291


It might be worth opening a support ticket with GitHub to possibly get fixing this  prioritized. Otherwise consider pushing the images to Docker Hub instead?

**Comment by DrPyser** [comment]
Thanks, that's what I expected after reading up on other issues on github's forums.

**Comment by thaJeztah** [comment]
Let me close this one for now, as it's not something under our control, but make sure to subscribe to https://github.com/containerd/containerd/issues/3291 to be updated when things change (work is in progress on GitHub's side)
