### ISSUE TITLE
how to debug moby in windows

### ISSUE THREAD

**Issue by 13567436138** [moby/moby#40612]
how to debug moby in windows

**Comment by thaJeztah** [comment]
Please provide more details on what you're asking; keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation
