### ISSUE TITLE
[Proposal] Some sort of --wait flag on a stack deploy

### ISSUE THREAD

**Issue by ohnotnow** [moby/moby#40762]
Apologies if this has been discussed before - did a search and nothing leapt out at me.

I've been using [@sudo-bmitch 's excellent wait script](https://github.com/sudo-bmitch/docker-stack-wait) and wondered if there would be any possiblity of some similar function being pulled into the core?  I realise the obvious answer is 'just keep using the script' - but it feels like something that would be welcome by a lot of people if it was more 'front and center' as part of the stack deploy command.

Until I was pointed at the script I'd find myself ssh'ing into a swarm manager and sitting running docker ps/docker service/etc commands to see how the deployment was going.  Which was less than ideal.

Anyway - that was all really :-)

**Comment by thaJeztah** [comment]
This is something that would have to be implemented in the CLI, because `docker stack deploy` is a client-side feature. There's an existing discussion in https://github.com/moby/moby/issues/30942, which is for `docker stack rm`, but closely related. An issue was created in the CLI issue tracker here: https://github.com/docker/cli/issues/373

let me close this issue in favour of https://github.com/docker/cli/issues/373 to prevent the discussion from diverging
