### ISSUE TITLE
Docker with bash entrypoint fails to work

### ISSUE THREAD

**Issue by Misiur** [moby/moby#40783]
```
docker -v
Docker version 18.09.7, build 2d0083d
```

```
FROM ubuntu
ENTRYPOINT ["/bin/bash"]
CMD ["/bin/bash"]
```

```
docker run -it docktest bash
/usr/bin/bash: /usr/bin/bash: cannot execute binary file
```

**Comment by thaJeztah** [comment]
This is expected; you've set both the `ENTRYPOINT` and `CMD` to `/bin/bash`. The `CMD` provides arguments for the `ENTRYPOINT`, so in this case the container tries to run:

```
/bin/bash /bin/bash
```

Which means it tries to run `/bin/bash` as a bash script, what will fail (given the error message produced by bash that it won't execute a binary file)

Closing this because this is not a bug, but feel free to continue the conversation
