### ISSUE TITLE
Ambiguous error messages for common launch misconfigurations

### ISSUE THREAD

**Issue by mcandre** [moby/moby#40859]
This is somewhat of a carryover from Linux, but exec errors are simply the worst to debug. If your entrypoint is a shell script whose shebang interpreter is not present in the container, then exec complains but fails to clarify WHICH interpreter is missing. This leads to many lost hours as DevOps scramble to understand the nature of the error.

Similarly, if you make the mistake of trying to run an alt libc (eg musl) binary from a GNU container, then Docker yields a generic exec error. No mention of any particular missing SO file.

Also, many chmod oddities in Docker land. Exec won't tell you when the entrypoint lacks executable bits.

Also, chmod +x <script> sometimes silently fails to mutate the executable bit. Not sure if a Docker thing or a Kubernetes/Alpine thing. Oh well.

**Comment by cpuguy83** [comment]
It's a Linux thing. The errors come from the kernel.

**Comment by cpuguy83** [comment]
I'm not sure there's much of anything we can do here.

**Comment by thaJeztah** [comment]
This is a duplicate (or similar to) https://github.com/moby/moby/issues/29420. These come from Linux itself indeed, and docker won't be able to know what the underlying cause is; as you noticed, either a file missing the `executable bit`, a file having incorrect newlines (Windows line endings instead of Linux), or a missing DLL all produce the same error.

Unfortunately, I don't think there's much we can do to fix that
