### ISSUE TITLE
Will docker natively support CRI ?

### ISSUE THREAD

**Issue by tao12345666333** [moby/moby#40966]
**Description**

Some changes are currently underway in Kubernetes. https://github.com/kubernetes/kubernetes/pull/87746

Docker as a Kubernetes container runtime is supported by in-tree dockershim.

I want to know does Docker consider providing native support for CRI?

xref: 
* https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20200205-build-kubelet-without-docker.md#returning-to-motivation
* https://github.com/kubernetes/enhancements/pull/1546

**Comment by tao12345666333** [comment]
ping @thaJeztah

**Comment by cpuguy83** [comment]
I don't see this as a worthwhile endeavor.

**Comment by AkihiroSuda** [comment]
Closing as unlikely to happen

**Comment by thaJeztah** [comment]
The containerd 1.x project (which was a "reboot" of containerd 0.2, and rewritten from scratch) was designed with kubernetes in mind; taking all the bits that are needed to be useful as a runtime, without the overhead and features that the docker daemon provides (which are useful, but not used when using as a runtime for kubernetes, and as such only "overhead").

So for that reason, we won't implement this in dockerd. We _will_ continue looking at moving parts that are in dockerd to containerd (move image management / storage to containerd), so that there's a more seamless integration with containerd
