### ISSUE TITLE
builds succed for ARG with no default value and no --build-arg

### ISSUE THREAD

**Issue by redbaron** [moby/moby#41012]
**Description**

Not passing `--build-arg` for `ARG` without default value doesn't result in build failure

**Steps to reproduce the issue:**
```
cd $(mktemp -d)
cat >Dockerfile<<"EOF"
FROM busybox
ARG MYARG
RUN echo $MYARG
EOF
docker build .
```

**Describe the results you received:**

Build succeeds

**Describe the results you expected:**

Build failure

**Additional information you deem important (e.g. issue happens only occasionally):**

I am pretty sure it used to fail if you try to build an image without passing `--build-arg` if argument had no default value.

**Output of `docker version`:**

```
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:26:00 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:04:38 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~19.10.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.3.1)

Server:
 Containers: 37
  Running: 1
  Paused: 0
  Stopped: 36
 Images: 222
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-51-generic
 Operating System: Ubuntu 19.10
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.28GiB
 Name: OVO4756L
 ID: KZZS:BKFH:XZA2:6CPI:FM4X:2O7J:U2YM:QUFY:FO55:QINF:RZ7N:7BRX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical

**Comment by thaJeztah** [comment]
Hmm, I think this has always been valid; `ARG FOO`, so without `=` after `FOO` means that `FOO` gets it's default value either from an existing `ENV` var with the same name (if present) or a "global" `ARG` with the same name, and otherwise is 'unset'

Using `ARG FOO=` means that `FOO` is set to an empty string.

I double checked if older versions did show a different result, but that doesn't appear to be the case;

```bash
# start a docker 17.03 "docker-in-docker" container
docker run -d --rm -v /var/lib/docker --privileged --name docker docker:17.03-dind

# open a shell in the container
docker exec -it docker sh

# perform the build
docker build -t foo -<<'EOF'
FROM busybox
ARG MYARG
RUN echo $MYARG
EOF

# Sending build context to Docker daemon 2.048 kB
# Step 1/3 : FROM busybox
# latest: Pulling from library/busybox
# d9cbbca60e5f: Pull complete
# Digest: sha256:836945da1f3afe2cfff376d379852bbb82e0237cb2925d53a13f53d6e8a8c48c
# Status: Downloaded newer image for busybox:latest
#  ---> 78096d0a5478
# Step 2/3 : ARG MYARG
#  ---> Running in 283c8588f858
#  ---> c5790a456dfb
# Removing intermediate container 283c8588f858
# Step 3/3 : RUN echo $MYARG
#  ---> Running in 63747ae20221
# 
#  ---> 209c088b01a1
# Removing intermediate container 63747ae20221
# Successfully built 209c088b01a1
```


That said, you _could_ make your build fail if you want the `ARG` to be required (although, generally, I think it would make sense to set a sensible _default_ in the Dockerfile itself, so that it can be built without providing a `--build-arg`);

Something like this

```Dockerfile
FROM busybox
ARG MYARG
RUN echo "${MYARG?Missing --build-arg MYARG}"
```

In which case you make the shell fail the build;

```
Sending build context to Docker daemon 2.048 kB
Step 1/3 : FROM busybox
 ---> 78096d0a5478
Step 2/3 : ARG MYARG
 ---> Using cache
 ---> c5790a456dfb
Step 3/3 : RUN echo "${MYARG?Missing --build-arg MYARG}"
 ---> Running in 23a8c4124786
/bin/sh: MYARG: Missing --build-arg MYARG
The command '/bin/sh -c echo "${MYARG?Missing --build-arg MYARG}"' returned a non-zero code: 2
```

The next release of BuildKit (to be included in the next Docker release) will also have support for this when doing variable substitution in the Dockerfile itself; see https://github.com/moby/buildkit/pull/1180

**Comment by thaJeztah** [comment]
I don't think there's a bug at hand here, so let me go ahead and close this one. Feel free to continue the conversation though, in case I misunderstood 😅

**Comment by redbaron** [comment]
Somehow I was under impression that at some point docker was failing builds unless all build args have values, whether passed explicitly at build time or have default value specified. It seems it wasn't the case and even 1.12 still builds it.

`${VAR:?}` workaround is probably what I was using back then. Thanks

**Comment by thaJeztah** [comment]
> Somehow I was under impression that at some point docker was failing builds unless all build args have values, whether passed explicitly at build time or have default value specified.

Hm.. I _do_ recall that originally it would fail if you passed a `--build-arg`, but there was not corresponding build-arg in the Dockerfile. This was originally an error, and now only prints a warning;


```bash
docker build --build-arg NO_SUCH_ARCH=foo -<<EOF
FROM busybox
RUN echo "foo"
EOF
```

Which prints a warning;

```
[Warning] One or more build-args [NO_SUCH_ARCH] were not consumed
```


Another case would be if you used the build-arg in a `FROM` line, and because of the missing build-arg it would be an invalid reference;


```bash
docker build -<<EOF
ARG UBUNTU_VERSION

FROM ubuntu:${UBUNTU_VERSION}
RUN echo foo
EOF

Sending build context to Docker daemon  2.048kB
Step 1/3 : ARG UBUNTU_VERSION
Step 2/3 : FROM ubuntu:
invalid reference format
```
