### ISSUE TITLE
Docker Swarm HA has no benefits

### ISSUE THREAD

**Issue by mvasi90** [moby/moby#41047]
I can't find any benefits in Docker Swarm.
(Please read all before leaving a comment or an emoticon; Not only the title).

Docker in swarm mode performs load balancing at the processing level, that is, CPU and RAM usage on different nodes.
A single core of the processor is infinitely faster than the network.

On nodes that have a single network interface that is used for both data and control traffic, each received connection is duplicated degrading the performance: a client accesses the node A and Docker redirect it to node B.
This does not fix the bottleneck, but increases it.

It is often mentioned that Swarm mode allows connection even if there are no services on the node. This only happens if the administrator wants (creating services limited by some nodes).
But natural circumstances dictate that the entire node is no longer available, rather than a single process; Either for server maintenance or network failures. In these cases Docker swarm doesn't help either.

To manage the traffic between nodes from outside the Swarm, reverse proxies appear. That is load balancing at the network level.
But at this point the Docker Swarm is more useless than before using reverse proxy. The ingress network can be skipped by configuring the reverse proxy to manage the load between the nodes. And disabling Swarm mode, traffic is significantly reduced.

Reverse proxy is also not the perfect solution. The client directly accesses the reverse proxy node that may be down or overloaded. Depending on the software used, the next IP could be requested from DNS A or AAAA record. High latency, slow connection, etc.

Do you remember when we lived in the trees? Docker did not exist. We cannot say that there are natural barriers, because nature has not created it. We have designed it all wrong. Even the email protocol. There is no more insecure, inefficient and poorly designed protocol than the email protocol.

Instead of patching one on top of the other to make the wheel square and slow, it would be better to reimplement many things from scratch (especially the e-mail protocol).

**Comment by cpuguy83** [comment]
I have read this multiple times over some long breaks.

1. This starts off inflammatory, making it more difficult to read.
2. It ends with more inflammatory comments making it easy to dismiss.

I cannot see in this post where you are reporting a bug or a feature request... maybe I am missing it due to the points mentioned above.

If a node is down, then swarm will schedule work to another node.
If you need HA, then you should have multiple replicas scheduled using the "spread" strategy (default).
There are is also an option to set the max replicas on a node, but this may not have been released yet.

As far as a particular ingress IP being down, that is not really in the scope of swarm because swarm does not manage the node the nodes themselves.
Maybe you are asking for some way to integrate here?

I would advise you to follow the issue template.
Report the problem you are having and how you might like to see it solved or how you expected it to work.
Anything else just makes it difficult to engage.

**Comment by cpuguy83** [comment]
Closing since there has been no response.
Feel free to update and we can open it back up.

Thanks.
