### ISSUE TITLE
Remove potentially offensive names

### ISSUE THREAD

**Issue by cyborch** [moby/moby#41045]
Consider removing "Clifford Christopher Cocks" from names-generator.

**Description**

Combinations like "hardcore-cocks" can be problematic.

**Steps to reproduce the issue:**

Run names-generator many, many times. Notice that eventually some offensive combinations arise.

**Describe the results you received:**

`hardcore-cocks` was generated as a name.

**Describe the results you expected:**

Safe-for-work docker container names.

**Comment by thaJeztah** [comment]
This was already fixed in https://github.com/moby/moby/pull/38422, and back ported to Docker v18.09.3 in https://github.com/docker/engine/pull/159.

If you're having this issue, please update your version of docker, because Docker 18.09.x reached EOL and may have unpatched vulnerabilities. If you're unable to upgrade to a current (19.03.x) release, at least make sure that you have the latest patch release for v18.09 installed (v18.09.9).
