### ISSUE TITLE
Imports problem in term 1.13 - logrus

### ISSUE THREAD

**Issue by deathtrix** [moby/moby#41087]
Imports in https://github.com/moby/moby/blob/1.13.x/pkg/term/windows/windows.go should be "github.com/sirupsen/logrus" not "github.com/Sirupsen/logrus".

Otherwise I get:
       github.com/golang-migrate/migrate/v4/database/mysql tested by
        github.com/golang-migrate/migrate/v4/database/mysql.test imports
        github.com/dhui/dktest imports
        github.com/docker/docker/pkg/jsonmessage imports
        github.com/docker/docker/pkg/term imports
        github.com/docker/docker/pkg/term/windows imports
        github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.6.0: parsing go.mod:
        module declares its path as: github.com/sirupsen/logrus
                but was required as: github.com/Sirupsen/logrus

**Comment by thaJeztah** [comment]
Docker 1.13 (and the related release branch) is over three years old, reached EOL three years ago, and should not be used.

If you're trying to use docker as a dependency, and using go modules, chances are that you're getting this outdated version because the breaking behavior that go modules introduced; this issue has some more discussion about that, and provides some steps on how to use this repository as a dependency when using go modules; https://github.com/moby/moby/issues/39302#issuecomment-635253855

Let me close this issue because of the above, but feel free to continue the conversation

**Comment by deathtrix** [comment]
Actually it’s the same problem in all versions except the last one.

**Comment by thaJeztah** [comment]
This repository uses CalVer, not SemVer, and  go modules doesn't support those (but it might see some versions, such as 17.12 as SemVer).

Docker 17.09 and up (september 2017) have the new import path for logrus (which was the timeframe it was renamed); https://github.com/moby/moby/blob/v17.09.0-ce/pkg/term/windows/windows.go

**Comment by deathtrix** [comment]
Ok. But what is the harm in changing it to lower case?

**Comment by thaJeztah** [comment]
> Ok. But what is the harm in changing it to lower case?

These are old tagged releases, we cannot update those. Even if we would update the local paths to lowercase, things would break because those old versions use _other_ dependencies that would still attempt to use the `Sirupsen/logrus` dependency.

It's better to have the build fail (so that a user of the "docker/docker" dependency _knows_ something is wrong) than to work around them by updating old releases, as those old releases are EOL, not maintained, and have unpatched vulnerabilities.
