### ISSUE TITLE
system crashes after first Docker container run, how can I debug the source Code ? 

### ISSUE THREAD

**Issue by hessam94** [moby/moby#41257]
Hello, 
I could install and run Docker on Native Android. Hello-world is running(although with lots of manual configurations) . But the problem is Any command after the first run makes the whole system crashes. I mean the first time it works, but any command( even cd ls etc) the system crashes. 
SO how can i debug it more advanced? i need to know which parts and what makes this problem? 
Thanks. please answer me.

**Comment by thaJeztah** [comment]
Make sure the daemon is running in debug more (with the `--debug` flag set, or `{"debug":true}` in the `/etc/docker/daemon.json`, and check if there's anything useful in the daemon logs, and logs for containerd and runc.

Docker is currently not supported on Android though, and afaik, nobody is actively working on that. Contributions are welcome though if changes are not impacting the code base too much.

I'm closing this issue, because Android is not currently supported, but feel free to continue the conversation

**Comment by hessam94** [comment]
Thanks , how can make contribution? Because it is part of my phd thesis, please let me know , we are in the middle if the thesis and need it, thanks again


Sent from Yahoo Mail for iPhone


On Monday, July 27, 2020, 2:48 PM, Sebastiaan van Stijn <notifications@github.com> wrote:




Make sure the daemon is running in debug more (with the --debug flag set, or {"debug":true} in the /etc/docker/daemon.json, and check if there's anything useful in the daemon logs, and logs for containerd and runc.

Docker is currently not supported on Android though, and afaik, nobody is actively working on that. Contributions are welcome though if changes are not impacting the code base too much.

I'm closing this issue, because Android is not currently supported, but feel free to continue the conversation
