### ISSUE TITLE
Error response from daemon: hns failed with error : Access is denied.

### ISSUE THREAD

**Issue by masoudshiri** [moby/moby#41278]
I got " Error response from daemon: hns failed with error : Access is denied. " when i want to create a network by this cmd:

docker network create --driver=transparent --gateway=175.15.10.124 --subnet=175.15.10.0/24 mynetwork

docker 19.0.3
windows server 2016

**Comment by thaJeztah** [comment]
Are you getting the same error if you create a network without passing the custom `--gateway` and `--subnet` options?

**Comment by masoudshiri** [comment]
yes , it‘s same . even in another l2bridge driver. my user is administrator and already i can build images & containers in a nat network . they are working correctly

**Comment by thaJeztah** [comment]
Hmm.. I'm not familiar enough with the Windows network stack to narrow down what the issue is. I _do_ know that Windows Server 2016 has some limitations around networking (and improvements in that area were made in more recent versions), but not sure if that's related here.

@msabansal any ideas/suggestions?
