### ISSUE TITLE
Remove libseccomp cgo dependency

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/moby#41299]
Moby depends on libseccomp cgo (via libseccomp-golang) just for `libseccomp.GetNativeArch()`.

https://github.com/moby/moby/blob/a072d726c753c3b02232e6a7b08d7e7ce79fffa5/profiles/seccomp/seccomp.go#L66

We should remove this dependency.

**Comment by thaJeztah** [comment]
Can we map `runtime.GOARCH` to seccomp arches, or won't that work?

**Comment by AkihiroSuda** [comment]
Probably it works

cc @tonistiigi

**Comment by thaJeztah** [comment]
If we still want to use the list of supported arches from libseccomp, we should probably open a refactor PR upstream to have the type moved to its own package, otherwise we'd still be pulling in the CGO code; https://github.com/seccomp/libseccomp-golang/blob/f1ae5650e34b7a744bd25c9a834f712c164b76bc/seccomp.go#L77-L120

**Comment by AkihiroSuda** [comment]
https://github.com/moby/moby/blob/a072d726c753c3b02232e6a7b08d7e7ce79fffa5/profiles/seccomp/seccomp.go#L32-L40

MIPS entries seem inconsistent with `GOARCH`
https://golang.org/doc/install/source#environment
```
  | linux | 386
  | linux | amd64
  | linux | arm
  | linux | arm64
  | linux | ppc64
  | linux | ppc64le
  | linux | mips
  | linux | mipsle
  | linux | mips64
  | linux | mips64le
  | linux | s390x
```
