### ISSUE TITLE
Does vfs(Storage Driver) support extended attributes(xattr, setcap) on docker 18.16.02-ce ?

### ISSUE THREAD

**Issue by allenzt** [moby/moby#41336]
The point is the command `/sbin/setcap CAP_NET_BIND_SERVICE=+eip /usr/share/dotnet/dotnet` excuted failed in edgeHub docker container? 

This command works on my host, but only failed in container. I find some related discussion [#5650](https://github.com/moby/moby/issues/5650), but it is not involve vsf storage driver.So anyone can give me some suggestion? thanks in advance!

docker info is as fellows:
```
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 18.06.2-ce
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.14.77
Operating System: <unknown>
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 482.5MiB
Name: VG710
ID: ON3O:BN3V:DL35:J2BD:YXBR:UW3H:JWO7:IUEJ:SKBA:ICCM:CZLC:DPWV
Docker Root Dir: /tmp/app/docker/docker_root
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
Yes, that should work on vfs. Here's on a Ubuntu 20.04 machine with the `vfs` storage driver enabled;



<details>
<summary>docker info</summary>

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.12
 Storage Driver: vfs
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-29-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.941GiB
 Name: ubuntu-s-1vcpu-2gb-ams3-01
 ID: H2XZ:BMBB:KM5S:NBTO:ADKG:7HVR:G7F2:2I3Q:HSMF:LXDI:2V4E:Z4Q2
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 21
  Goroutines: 35
  System Time: 2020-08-11T09:09:11.524894298Z
  EventsListeners: 0
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

</details>


```bash
docker run --rm alpine sh -c 'apk add --quiet --no-cache libcap && setcap cap_net_bind_service=+ep /bin/busybox && getcap /bin/busybox'
# /bin/busybox = cap_net_bind_service+ep
```

That said;

- The `vfs` storage driver is mostly intended for debugging purposes and as a "last resort" if none of the other storage drivers are supported. The `vfs` storage driver does not use an overlay or copy-on-write filesystem, which makes it very inefficient / low performant.
- I see you're running docker 18.06.2-ce. Docker 18.06.x reached EOL two years ago and is no longer maintained. That version also has known vulnerabilities, so I'd highly recommend updating to a current version if possible
- You're running on a really old kernel version (3.14.x). If possible, try to have something more current installed; many improvements (including the addition of overlayfs) went into later kernel versions. We mostly still support kernel 3.x to facilitate the CentOS 7 / RHEL 7 kernel (which has many features of more recent kernels back ported, but reports itself as a 3.x kernel)
- What operating system are you running on? `Operating System: <unknown>`


Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Comment by allenzt** [comment]
Thanks very much , I'll try again as you suggest.
