### ISSUE TITLE
Trouble matching running container with Golang Docker SDK

### ISSUE THREAD

**Issue by devinbost** [moby/moby#41343]
I'm listing the containers on my host machine like this:

```
	containers, err := cli.ContainerList(context.Background(), types.ContainerListOptions{})
	if err != nil {
		panic(err)
	}
```

and I'm attempting to find a matching container (to determine if a container with the matching name is already running) like this:

```
isMatch := func(myContainer types.Container) bool {
	for _, containerName := range myContainer.Names {
		log.Print("One of container's detected names is: " + containerName)
		if conf.Name == containerName {
			return true
		}
	}
	return false
}
```

However, it's not working as expected; it returns false, indicating that no match was found, so it tries starting up the container when I'm not expecting it to, resulting in the error:

> The container name "/my-example-container" is already in use by container "3a772417e0b3a2b15c953ca221b58e381e83ad43ca68685140bc7636d4aabf1d". You have to remove (or rename) that container to be able to reuse that name.

How do I determine if a container with the given name has already been started?

**Comment by thaJeztah** [comment]
I think it may not be able to match the name because (for historic reasons) the container names are prefixed with a slash;

```bash
$ docker run -d --name foo nginx:alpine
$ docker container inspect --format '{{.Name}}' foo
/foo
```

However if you're looking for details of a single container, it may be better to use the `ContainerInspect()` function https://github.com/moby/moby/blob/afa8f1b8327f8a99ac38cca26bfb295109228fef/client/container_inspect.go#L13-L14

to check if a container exists with the given name (if not, it should return a "not found" error, which you can check with `errdefs.IsNotFound(); https://github.com/moby/moby/blob/master/errdefs/is.go#L32), and to get the `State` of the container (which should indicate if the container is running); https://docs.docker.com/engine/api/v1.40/#operation/ContainerInspect

**Comment by thaJeztah** [comment]
Let me close this issue, but feel free to continue the conversation
