### ISSUE TITLE
Can not run docker daemon on WSL

### ISSUE THREAD

**Issue by whizsid** [moby/moby#41375]
**Description**

I have installed  docker.io on my debian on WSL. But I can not run `dockerd`. 

**Steps to reproduce the issue:**
1. `sudo apt-get install docker.io`
2. `dockerd`

**Describe the results you received:**
```
Error starting daemon: Error initializing network controller: error obtaining controller instance: failed
 to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables v1.8.2 (legacy): can't 
initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
 (exit status 3)
```

**Describe the results you expected:**
Running docker daemon without errrors.

**Additional information you deem important (e.g. issue happens only occasionally):**

```
uname -a
Linux LAPTOP-JFD40N70 4.4.0-18362-Microsoft #836-Microsoft Mon May 05 16:04:00 PST 2020 x86_64 GNU/Linux
```

**Output of `docker version`:**

```
Docker version 18.09.1, build 4c52b90
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? 
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
WSL2 on Win10 (Debian Distro)

**Comment by thaJeztah** [comment]
Note that the `docker.io` package is a package that's built by debian, and not maintained by us; there's quite some differences in how those packages are built, and if there's a problem with that package, it's best to report with the Debian maintainers. Also note that Docker 18.09.x reached EOL and is no longer maintained.

However, instead of manually trying to install Docker on WSL2, I would highly recommend installing Docker Desktop for Windows instead, which now supports running on WSL2, and takes care of configuring docker to work well with WSL2; https://docs.docker.com/docker-for-windows/wsl/. The Docker Desktop team works closely with the Microsoft WSL2 team to provide the best experience, so definitely give Docker Desktop a try instead.


Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because of the above, but feel free to continue the conversation
