### ISSUE TITLE
docker exec hang and df -h hang 19.03.5

### ISSUE THREAD

**Issue by 370672701** [moby/moby#41387]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:24:18 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CentOS Linux release 7.7.1908 (Core)

**Comment by tao12345666333** [comment]
Please provide more information.

**Comment by tao12345666333** [comment]
Please provide more information.

**Comment by tao12345666333** [comment]
Please provide more information.

**Comment by thaJeztah** [comment]
I'm closing this ticket, because there's not information to make this actionable; I _do_ notice you're running an outdated version of Docker 19.03 (the current patch release is 19.03.12, and the current containerd.io package is at 1.2.13; make sure you have both updated to the latest patch release, because there might be fixes for your problem,

Closing this ticket, but feel free to continue the conversation
