### ISSUE TITLE
Recommend isolated partition for /var/lib/docker?

### ISSUE THREAD

**Issue by dHannasch** [moby/moby#41481]
This is purely about documentation, and the issue template kind of makes it look like this doesn't belong here, but https://github.com/docker/docker.github.io/issues/11364 sent me over here.

File: [config/daemon/index.md](https://docs.docker.com/config/daemon/)

I am running Docker automatically on a server.
A problem I run into is that /var/lib/docker grows to fill the entire disk.
In theory, the solution is trivial: a cron job to docker system prune. In practice, usage is bursty, and the disk tends to fill up between runs of docker system prune. And when the disk is full, nothing works, including docker system prune.
As far as I know, there is no way to configure Docker itself to restrict disk usage. (And I certainly wouldn't know how to make a pull request to do that.) The best solution I know of is to create a separate partition and mount /var/lib/docker there. Then, if a request tries to exceed the storage available, it will simply fail rather than hose the system.

I am thinking of editing the documentation to recommend this as a best practice when running Docker on a server. https://docs.docker.com/config/daemon/ seems like perhaps the natural place to mention it, though it's not exactly tied to Docker's configuration per se (Docker itself doesn't really know about the mount).

Comments? Would there be a better place to address disk usage limitation?

**Comment by olljanat** [comment]
@dHannasch we have used separate partition (and virtual disk) for /var/lib/docker. Not because of this but because of server upgrade automation which let's us drop OS partition and re-create it and whole configuration on Docker including Swarm membership remains. So that at least works.

But this one a bit sounds that you either try optimize disk usage too much and loose advantage provided Docker caching because of that or you have Dockerfiles/docker images which are created against [best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)

Anyway you can also optimize cron process with filter which leaves images which have been lately used yo disk. Our build servers we run command like this on couple of times on day:
docker system prune -af --filter until=8h

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
