### ISSUE TITLE
Ability to set default docker registry in config files

### ISSUE THREAD

**Issue by mooperd** [moby/moby#41627]
Is there a plan to users to change the default docker registry now that docker hub is starting to rate-limit / charge to access?  I would like to be able to use a different registry by default so that I can continue to use ubuntu:this, node:that, python:which.

**Comment by jimlinntu** [comment]
It seems like a good idea.

There is a related question on Stack Overflow: < https://stackoverflow.com/questions/53847122/where-docker-default-registry-url-is-configured>

**Comment by thaJeztah** [comment]
> I would like to be able to use a different registry by default so that I can continue to use ubuntu:this, node:that, python:which.

That should already be possible if you configure a registry mirror https://docs.docker.com/registry/recipes/mirror/

**Comment by johnlaur** [comment]
Registry mirrors are unfortunately currently somewhat crippled because they cannot be located beneath a pathname. It would already be supported in the tools, but there is unfortunately a test which disallows a path component to be configured in the registry-mirror. I would invite everyone here to support PR #46594 which fixes the broken test and is currently receiving positive attention.

**Comment by neersighted** [comment]
For better or for worse, in the ecosystem `docker.io/library` is the default if a registry and namespace (respectively) are not specified: https://github.com/distribution/reference/blob/8507c7fcf0da9f570540c958ea7b972c30eeaeca/normalize.go#L22-L39

In general, you should use fully qualified image names. That is to say, instead of trying to swap something else in to the `docker.io/library` namespace, you should instead use `docker.io/library/python` for the `python` image.

Red Hat forked Docker to add such a mapping in the past (and supported it in their own tools), but as it turns out, the consequences of ambiguous image resolution ended up being too great for them to continue recommending the (anti-)feature: https://www.redhat.com/en/blog/be-careful-when-pulling-images-short-name

Even if we did support this, we'd introduce fragmentation with other tools (e.g. skopeo, regctl), where one may have a different definition of what `python` is from another, and it may not be immediately obvious. I think that the "legacy" name normalization is here to stay, for better or for worse.

Instead, we should focus on solving the related pain-points:
* Syndicating content and separating content identity from location
* Registry mirrors (for Hub) usability and potential expansion to other registries (potentially not required with the above)
* Better systems for signing and trusting container content (related to "identity" and "location")
