### ISSUE TITLE
github.com/containerd/fifo.(*fifo).Read block problem

### ISSUE THREAD

**Issue by yiliaofan** [moby/moby#41765]
**Description**
The phenomenon is: it will cause the business process to print log blocking (a few seconds), which is determined to be a problem caused by the log. But I don't know which component of docker caused it.

**Steps to reproduce the issue:**

[goroutine-stacks-2020-12-09T155503+0800.log](https://github.com/moby/moby/files/5664920/goroutine-stacks-2020-12-09T155503%2B0800.log)

**Describe the results you received:**

**Describe the results you expected:**
 print log normal , not block.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:24:22 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.6.3-ce-tke.1
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       7f659f6724
  Built:            Thu Aug 20 07:10:40 2020
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Output of `docker info`:**

```
Containers: 306
 Running: 234
 Paused: 0
 Stopped: 72
Images: 1532
Server Version: 18.6.3-ce-tke.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)
runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd (expected: a592beb5bc4c4092b1b1bac971afed27687340c5)
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.105-19-0013
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 96
Total Memory: 376.1GiB
Name: cvm-kube_node-maxwell-90
ID: SGEJ:4SSW:LXTR:KN33:G2PG:GN7M:CTLT:ARA6:VPR7:ROO7:JQ7B:F55U
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 1307
 Goroutines: 1032
 System Time: 2020-12-09T21:55:43.38440977+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://mirror.ccs.tencentyun.com/
Live Restore Enabled: true

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

tencent cloud 

[goroutine-stacks-2020-12-09T155503+0800.log](https://github.com/moby/moby/files/5664920/goroutine-stacks-2020-12-09T155503%2B0800.log)

**Comment by thaJeztah** [comment]
Do you have steps to reproduce the issue?

> Additional environment details (AWS, VirtualBox, physical, etc.):
>
> tencent cloud

Can you update your report above, and  post `docker version` and `docker info` from that environment if that's where the problem is? Currently it shows information about your Docker Desktop install, which seems unrelated

**Comment by yiliaofan** [comment]
> Do you have steps to reproduce the issue?
> 
> > Additional environment details (AWS, VirtualBox, physical, etc.):
> > tencent cloud
> 
> Can you update your report above, and post `docker version` and `docker info` from that environment if that's where the problem is? Currently it shows information about your Docker Desktop install, which seems unrelated

thank you ~  

The problem is weird, and there is no stable recurrence step. Occasionally, a problem with the write log card occurred on the node, causing business timeout.

`goroutine 16456540 [IO wait]:
internal/poll.runtime_pollWait(0x7fb7bc21bf98, 0x72, 0xc424f36c10)
    /usr/local/go/src/runtime/netpoll.go:173 +0x59
internal/poll.(*pollDesc).wait(0xc424e92248, 0x72, 0xffffffffffffff01, 0x25c2be0, 0x3163c20)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9d
internal/poll.(*pollDesc).waitRead(0xc424e92248, 0xc431e94001, 0x8000, 0x8000)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3f
internal/poll.(*FD).Read(0xc424e92230, 0xc431e94000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
    /usr/local/go/src/internal/poll/fd_unix.go:157 +0x17f
os.(*File).read(0xc420f6fc38, 0xc431e94000, 0x8000, 0x8000, 0x5, 0xa, 0xc424f36d18)
    /usr/local/go/src/os/file_unix.go:226 +0x50
os.(*File).Read(0xc420f6fc38, 0xc431e94000, 0x8000, 0x8000, 0xc429830e80, 0xc431e97fc0, 0x3a49)
    /usr/local/go/src/os/file.go:107 +0x6c
github.com/docker/docker/vendor/github.com/containerd/fifo.(*fifo).Read(0xc430393e60, 0xc431e94000, 0x8000, 0x8000, 0x7a09, 0x0, 0x0)
    /go/src/github.com/docker/docker/vendor/github.com/containerd/fifo/fifo.go:154 +0x220
io.copyBuffer(0x25bc3a0, 0xc429830e80, 0x7fb7e8379020, 0xc430393e60, 0xc431e94000, 0x8000, 0x8000, 0xc42044b540, 0x2183280, 0xc4239bc420)
    /usr/local/go/src/io/io.go:400 +0x166
io.CopyBuffer(0x25bc3a0, 0xc429830e80, 0x7fb7e8379020, 0xc430393e60, 0xc431e94000, 0x8000, 0x8000, 0xc422d1aaa0, 0xc421ec96c0, 0x1a)
    /usr/local/go/src/io/io.go:373 +0x84
github.com/docker/docker/pkg/pools.Copy(0x25bc3a0, 0xc429830e80, 0x7fb7e8379020, 0xc430393e60, 0xc430393e60, 0xc422ecd900, 0x7fb80803c310)
    /go/src/github.com/docker/docker/pkg/pools/pools.go:81 +0xa6
github.com/docker/docker/container/stream.(*Config).CopyToPipe.func1.1(0x25bc3a0, 0xc429830e80, 0x7fb7f8481000, 0xc430393e60, 0xc4224d2e60)
    /go/src/github.com/docker/docker/container/stream/streams.go:124 +0x73
created by github.com/docker/docker/container/stream.(*Config).CopyToPipe.func1
    /go/src/github.com/docker/docker/container/stream/streams.go:123 +0x86`

**Comment by thaJeztah** [comment]
Sorry for the delay, hmmm...

So at least some things I notice from your `docker info`;

- docker 18.06 reached EOL more than two years ago; that version is no longer maintained
- containerd `v1.2.4` (commit https://github.com/containerd/containerd/commit/e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e) reached EOL and is no longer maintained; that version also has known vulnerabilities.
- it looks like you're running CentOS with a non-standard kernel (`4.14.105-19-0013`). While this _may_ work, those combinations are definitely not tested on our side.
- the daemon you have installed (`18.6.3-ce-tke.1`) doesn't look like an official build of docker; it's also built from a commit (7f659f6724) that doesn't exist in our codebase (checked both the docker-ce repository (https://github.com/docker/docker-ce/commit/7f659f6724), and the moby repository (https://github.com/moby/moby/commit/7f659f6724)

I'd highly recommend updating to a currently supported official build of docker if possible, or otherwise to report the issue with Tencent (if they are the party that built that version of Docker). Unfortunately, without a way to reproduce the issue, and without access to the code that was used to build the daemon, I don't think there's much we can do. It's possible this issue was already fixed in later versions or in updated versions of the containerd "fifo" dependency in which the problem looks to reveal itself.


I'm closing this ticket because of the above, but feel free to continue the conversation
