### ISSUE TITLE
why do we need containerutility.exe?

### ISSUE THREAD

**Issue by rgl** [moby/moby#41776]
When we build the Windows version with `make win` a `bundles/cross/windows/amd64/containerutility.exe` is created. Is this really needed at runtime? Why?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.

**Comment by rgl** [comment]
@thaJeztah, I'm still wondering if we need that binary around at runtime.

**Comment by thaJeztah** [comment]
@rgl The containerutility was added as part of `COPY / ADD --chown`;

- https://github.com/moby/moby/pull/35521

That utility is used to extract user-information from the container / image's context (which is less trivial for Windows images than for Linux (on Linux it's usually just parsing some files, such as `/etc/password` )). Unfortunately, Windows also didn't provide an API to obtain that information from a container, which is why that utility was created.

The source code for that utility can be found here (I need to contact an admin in the docker org, because it was accidentally archived as part of a batch operation); https://github.com/docker-archive/windows-container-utility

**Comment by rgl** [comment]
Ah that's what its for! Thank you!

I had to give it a try, but I'm afraid that something is broken. With an empty container cache, and when there is no `containerutility.exe` file around, `docker build` does not even fail; it just copies the file, and does not error out trying to set its owner. And the file ends-up without the expected owner at the final container image.

FWIW, Here's my Dockerfile:

```dockerfile
# escape=`
#FROM mcr.microsoft.com/windows/nanoserver:ltsc2022
FROM mcr.microsoft.com/powershell:7.2-nanoserver-ltsc2022
ENTRYPOINT ["pwsh.exe", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; $FormatEnumerationLimit = -1; "]
SHELL      ["pwsh.exe", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; $FormatEnumerationLimit = -1; "]
RUN $PSVersionTable
RUN mkdir C:\test
WORKDIR C:\test
COPY *.md ./
COPY test.ps1 ./
COPY --chown=Guests chown-guests.txt ./
COPY --chown=Administrator chown-administrator.txt ./
COPY --chown=ContainerUser chown-container-user.txt ./
CMD ["./test.ps1"]
```

And `test.ps1` file:

```powershell
function Write-Title($title) {
    Write-Output "`n#`n# $title`n#`n"
}

Write-Title "chown-guests.txt"
Get-Acl chown-guests.txt | Format-List

Write-Title "chown-administrator.txt"
Get-Acl chown-administrator.txt | Format-List

Write-Title "chown-container-user.txt"
Get-Acl chown-container-user.txt | Format-List
```

And `docker build` relevant result:

```
...
Step 8/12 : COPY test.ps1 ./
 ---> af3c9e0afab4
Step 9/12 : COPY --chown=Guests chown-guests.txt ./
 ---> 8617d8a218af
Step 10/12 : COPY --chown=Administrator chown-administrator.txt ./
 ---> cfd84c6f25c2
Step 11/12 : COPY --chown=ContainerUser chown-container-user.txt ./
 ---> 4264f5e92e03
Step 12/12 : CMD ["./test.ps1"]
 ---> Running in f418e14bf256
Removing intermediate container f418e14bf256
 ---> c438801fdcc7
Successfully built c438801fdcc7
...
```

And the `docker run` relevant result:

```
#
# chown-guests.txt
#
Path   : Microsoft.PowerShell.Core\FileSystem::C:\test\chown-guests.txt
Owner  : BUILTIN\Administrators
Group  : NT AUTHORITY\SYSTEM
Access : BUILTIN\Administrators Allow  FullControl
NT AUTHORITY\SYSTEM Allow  FullControl
BUILTIN\Users Allow  ReadAndExecute, Synchronize
Audit  : 
Sddl   : O:BAG:SYD:(A;ID;FA;;;BA)(A;ID;FA;;;SY)(A;ID;0x1200a9;;;BU)

#
# chown-administrator.txt
#
Path   : Microsoft.PowerShell.Core\FileSystem::C:\test\chown-administrator.txt
Owner  : BUILTIN\Administrators
Group  : NT AUTHORITY\SYSTEM
Access : BUILTIN\Administrators Allow  FullControl
NT AUTHORITY\SYSTEM Allow  FullControl
BUILTIN\Users Allow  ReadAndExecute, Synchronize
Audit  : 
Sddl   : O:BAG:SYD:(A;ID;FA;;;BA)(A;ID;FA;;;SY)(A;ID;0x1200a9;;;BU)

#
# chown-container-user.txt
#
Path   : Microsoft.PowerShell.Core\FileSystem::C:\test\chown-container-user.txt 
Owner  : BUILTIN\Administrators
Group  : NT AUTHORITY\SYSTEM
Access : BUILTIN\Administrators Allow  FullControl
NT AUTHORITY\SYSTEM Allow  FullControl
BUILTIN\Users Allow  ReadAndExecute, Synchronize
Audit  : 
Sddl   : O:BAG:SYD:(A;ID;FA;;;BA)(A;ID;FA;;;SY)(A;ID;0x1200a9;;;BU)
```

**Comment by thaJeztah** [comment]
Good questions, and I'm not a Windows user, so don't have a direct answer; at least from this comment on the review; the utility is only run for usernames that are not built-in; https://github.com/moby/moby/pull/35521#discussion_r165456050

>> So to parse a chown flag in windows we have to run a container?
>
> yes. In order to determine the security identity in the target.
> This only happens if the account in question is not a built-in account and target specific.

But also (just a quick glance at that code); it looks indeed to (silently) fall back in conditions where the temporary container couldn't be created or the error returned is not a `statusCodeError`;
https://github.com/moby/moby/blob/5d87dc98ea2e0ce4d2042779accc589ac7308a12/builder/dockerfile/internals_windows.go#L84-L100

It's been a while since that was merged, and I don't have all conversations (there were many) in mind; this may have been a deliberate choice (to prevent the whole build from failing, and _possibly_ because there's situations where lookups cannot be supported by the Windows base image / variant).

That said, if it's not possible to make that a "fatal" error condition, I agree it would be good to at least _log_ such cases, and ideally surface them (so that they are visible to the user).

**Comment by thaJeztah** [comment]
maybe @johnstep  (👋 ) knows some of the answers. 

@johnstep as you're back at MS now (and may have more insight) I'm also curious if things has changed in Windows, and if there would be a more elegant API nowadays to get this information (without having to do these tricks)?

**Comment by rgl** [comment]
@thaJeztah thanks for the update! in the meantime are you have to sync with the https://github.com/docker-archive/windows-container-utility maintainers so that tool is moved into this repo, maybe?

@johnstep or maybe you can do that? :-)

**Comment by TBBle** [comment]
Late to the party, but BuildKit has in the mean-time implemented something similar for the same situation: https://github.com/moby/buildkit/blob/master/util/system/getuserinfo/userinfo_windows.go so maybe that could be broken out into a new repo in the moby org? (It's also written in Go and hence _much_ shorter.) Both appear to be trivial wrappers around [`advapi32.LookupAccountName`](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-lookupaccountnamew) so the builder-side changes to use it should be relatively small, comparing [the BuildKit caller](https://github.com/moby/buildkit/blob/master/util/windows/util_windows.go#L74-L116) and [the classic builder caller here](https://github.com/moby/moby/blob/master/builder/dockerfile/internals_windows.go#L59-L107).

Also, was this ticket meant to be left closed?
