### ISSUE TITLE
additional property not allowed error

### ISSUE THREAD

**Issue by mahendrai1** [moby/moby#41823]
version: "3.7"

services:
  mywebappphp:
    image: mahend/mywebappphp:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      ports:
         - "8666:80"
    depends_on:
        - mywebappmysql
    mywebappmysql:
     image: mahend/mywebappmysql:latest
     deploy:
     replicas: 1
     restart_policy:
       condition: on-failure
     ports:
      - "3306:3306"

**Comment by cpuguy83** [comment]
There is no context to the error here or any of the information requested in the issue template.

If I had to guess, it is due to depends_on, which is not supported by the v3 compose format (which is for swarm).


In any case, this needs to go into https://github.com/docker/cli since that is where stacks are handled.
Please make sure to add all details, including full error messages, and what command you used to arrive at that error.

Thanks!
