### ISSUE TITLE
Feature: Remove need for 'version' from compose file parsing with 'docker stack deploy -c compose.yaml'

### ISSUE THREAD

**Issue by thernstig** [moby/moby#41875]
[Since Docker engine 19.03.0+](https://docs.docker.com/compose/compose-file/) the compose file format should support the [The Compose Specification](https://github.com/compose-spec/compose-spec/blob/master/spec.md). It states:

> The Compose file is a YAML file defining version (DEPRECATED), services (REQUIRED), networks, volumes, configs and secrets.

and

> Top-level version property is defined by the specification for backward compatibility but is only informative. A Compose implementation SHOULD NOT use this version to select an exact schema to validate the Compose file, but prefer the most recent schema at the time it has been designed.

But when using Docker engine 20.10.2 with `docker stack deploy` it returns a failure if `version` is removed from the compose file:

```sh
> docker stack deploy -c compose.yaml foo
unsupported Compose file version: 1.0
```

This might be a bug report instead, but I was unsure.

**Comment by a-abella** [comment]
Additionally, I'd like to know if it's intended for `docker stack` to support the new complete Compose Specification. In the past There was compose 2.x and compose 3.x, but `docker stack` only supported a modified subset of 3.x. Is `stack` being aligned with the compose spec or is it continuing to be an modified compose offshoot? I couldn't find any documentation regading compose specification and `docker stack`/swarm mode

**Comment by thaJeztah** [comment]
The version was made optional in https://github.com/docker/cli/pull/3257, which will be part of the upcoming 22.06 release (a first pre-release is available for download; https://github.com/moby/moby/releases/tag/v22.06.0-beta.0).

`docker stack` is still using the compose-spec v3; no work is in progress (yet) to switch it to us the compose-spec implementation. Even if it would switch to that implementation, most supported features would remain the same, as not all of the features that are part of the compose spec (which unifies the v2 and v3 features) can be supported in a distributed system (swarmkit).

I'll close this ticket because the original request was fixed by  https://github.com/docker/cli/pull/3257, but feel free to open a ticket in the https://github.com/docker/cli/issues issue tracker if there's specific features missing.
