### ISSUE TITLE
moby contains GPL-licensed code

### ISSUE THREAD

**Issue by jihoon-seo** [moby/moby#42002]
**Description**

moby is licensed under Apache License 2.0 - https://github.com/moby/moby/blob/master/LICENSE

However, its code contains a file which is licensed under GPL:
https://github.com/moby/moby/blob/master/contrib/init/openrc/docker.initd

**Comment by wilson0x4d** [comment]
While the "source" is made available here, it is not incorporated (or "combined") into a binary distribution. It exists in the `/contrib/` tree for reference purposes only. I do not believe the license identified in the source header implies anything beyond GPLv2's source distribution clause (which requires the license notice to remain, and any changes to the source to be made available.)

Fun facts: OpenRC was BSD-licensed at its inception, a special licensing grant at the time for OpenRC itself. Gentoo removed the `docker.initd` source from its `/app-emulation/` tree in Dec-2013 since it was unused.

**Comment by AkihiroSuda** [comment]
Is this issue closable?

**Comment by jihoon-seo** [comment]
@AkihiroSuda 
If the existence of `docker.initd` file in this repo does not cause any license issue,
then yes, this issue is closable!

**Comment by thaJeztah** [comment]
:wave: yes, these things can be tricky (and more so for scanners to detect automatically). 

I asked some colleagues to have a look as well and (to the best of our knowledge) the comment above https://github.com/moby/moby/issues/42002#issuecomment-775734876 appears to be correct. 

The FOSSA scanner likely isn’t able to detect the situations automatically, so would need an exclusion / ignore rule added to make it not report this file.

Perhaps you’re able to contact them to explain this case (and for them to verify)?
