### ISSUE TITLE
docker 20.10.4 and 20.10.5 have a dependency conflict

### ISSUE THREAD

**Issue by williamh** [moby/moby#42117]
Hello,

I am one of the docker package maintainers on Gentoo.

Based on what I'm seeing in the hack/Dockerfile/install/{containerd,runc}.installer scripts,
docker 20.10.5 requires containerd 1.4.3 and runc 1.0.0_rc93.
On the other hand, the vendor.conf file for containerd v1.4.3 shows that this version of containerd requires runc-1.0.0_rc92.

Your help would be greatly appreciated in knowing how to resolve this dependency conflict so I can package docker 20.10.5 on Gentoo.

Thanks much for your time.

William

**Comment by thaJeztah** [comment]
Are you packaging both dockerd, containerd, and runc in a single package? The version in the `.installer` is currently only used for CI, and to build the static tarballs (https://download.docker.com/linux/static/stable/x86_64/)

For the deb/rpm packages, containerd (which currently includes runc) is packaged separately (as containerd.io packages on download.docker.com),  for those, we match the version from upstream containerd; https://github.com/docker/containerd-packaging/blob/484fe7cdeaeb2711cb0a823bff4d5ee51009f0ff/common/common.mk#L27 

Note that with runc getting closer to a v1.0.0, and containerd being more decoupled from the runc codebase, I opened a proposal in the containerd repository to be more flexible in this area; https://github.com/containerd/containerd/pull/5036

**Comment by williamh** [comment]
@thaJeztah We package all of them separately. We have `docker`, `runc`, and `containerd` packages.
`runc` and `containerd` are listed as runtime dependencies of `docker` for us because `docker` calls the binaries from those packages.
We have been using `hack/install/dockerfile/install/*` to decide which versions of those packages to build, so I guess my question is, since the version of containerd in `hack/dockerfile/install/containerd.installer` is still 1.4.3 which requires an older version of runc, I'm not sure how to move forward.
Does dockerd call both the containerd and runc binaries? If it does, it looks like I may need a new release of containerd.

**Comment by thaJeztah** [comment]
> runc and containerd are listed as runtime dependencies of docker for us because docker calls the binaries from those packages.

I think the `docker` package should only have `containerd` as a dependency, and only have runc "indirectly" as a dependency; the `containerd` package should have `runc` (or `crun`) as dependency. Docker does not depend on `runc` directly, other than to get the installed version (for outputting in `docker version` and `docker info`).

> We have been using hack/install/dockerfile/install/* to decide which versions of those packages to build

We've been discussing adding more notes to those scripts; the _primary_ reason for the version in those files is to be used in CI in this repository, but they're still used as (default) versions for the static `.tar.gz` packages. For those we've been discussing if we should split those packages, and to separate tars for cli, dockerd, and containerd, as that would better reflect reality (containerd + runc _are_ separate packages), but were still somewhat on the fence, because that would make the static tars harder to use. (download and extract 3 or four tars, instead of a single one). 

As to what versions; _technically_, containerd's gRPC API has a stability guarantee, so any API version v1.x, and runtime ship api v1.2 should work (see https://github.com/containerd/containerd/blob/v1.4.4/RELEASES.md#public-api-stability)

That said, for docker 20.10.x, we set the minimum containerd version to v1.4.1 (v1.4.0 had some known issues), as older versions of containerd have now reached EOL;  https://github.com/docker/docker-ce-packaging/blob/cd9edddb5a8d03fecd202d33040f008eceb3f743/deb/common/control#L30

```
Depends: containerd.io (>= 1.4.1),
         docker-ce-cli,
```

For our own `containerd.io` packages, we will be updating the version of runc to rc93, ahead of upstream containerd being on that version, because there's a fix in runc to better handle seccomp profiles when using recent versions of Ubuntu base images (which caused failures because they attempt to use syscalls that may be blocked by seccomp). (see https://github.com/docker/containerd-packaging/pull/221)

**Comment by williamh** [comment]
@thaJeztah It looks like I just figured it out. I can't use runc 1.0.0_rc93 yet because upstream containerd is not on that version.
We also have the containerd dependency pinned to 1.4.3 in our docker package.
Based on what you said, I will change the containerd dependency to >=1.4.1  and drop the runc dependency from our docker package since upstream containerd depends on runc.

**Comment by williamh** [comment]
@thaJeztah I did as you suggested. Our docker 20.10.x packages now depend on >=containerd-1.4.1 and I have dropped their dependency on runc since containerd pulls in runc.
I also just added containerd 1.4.4 to the distro.
Since containerd 1.4.4 still wants runc 1.0.0-rc92, I am curious about the issue you found with these versions and seccomp.
How would I know if Gentoo is affected.

Thanks,

William

**Comment by thaJeztah** [comment]
>  I am curious about the issue you found with these versions and seccomp.

one of the issues was related to seccomp profiles when running more recent alpine images; don
t have a link to that issue at hand (related; https://github.com/opencontainers/runc/pull/2750)

For the issue being discussed here; https://github.com/containerd/containerd/pull/5036 was accepted, and backported to the 1.4 release branch as part of https://github.com/containerd/containerd/pull/5166
