### ISSUE TITLE
Schema of Swagger/OpenAPI specification contains invalid property

### ISSUE THREAD

**Issue by michaelweidmann** [moby/moby#42120]
**Description**
I am currently developing a program which uses the [Swagger spec](https://github.com/moby/moby/blob/master/api/swagger.yaml) and generates classes from the defined schemas. Thereby I noticed a little issue.

In the specification the `Mount` schema is described as follows:
```yaml
ContainerSummary:
  type: "array"
  items:
    type: "object"
    properties:
    # some different irrelevant properties...  
    Mounts:
      type: "array"
      items:
        $ref: "#/definitions/Mount"
Mount:
    type: "object"
    properties:
      Target:
        description: "Container path."
        type: "string"
      Source:
        description: "Mount source (e.g. a volume name, a host path)."
        type: "string"
      # ... some different properties which are irrelevant right now
```

When I'm calling the docker engine API (to get a list of all containers) via `curl --unix-socket /var/run/docker.sock http://docker/containers/json` I am getting the following response:

```json
"Mounts": [
            {
                "Type": "bind",
                "Source": "/src/directory",
                "Destination": "/dest/directory",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/src/directory",
                "Destination": "/dest/directory",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ]
```

As you can see, the name `Target`property in the Swagger spec does not match with the acutal response property `Destination`.

**Steps to reproduce the issue:**
1. Execute the command `curl --unix-socket /var/run/docker.sock http://docker/containers/json` on your local machine with Docker installed.
2. Check whether `Destination` is used in the response. 

**Describe the results you received:**
`Destination` is used in the response.

**Describe the results you expected:**
- Either the Swagger Spec changes `Target` to `Destination` or instead of the `Mount` schema in `ContainerSummary` `MountPoint` is used
or
- the response changes from `Destination` to `Target`.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 1.943GiB
 Name: docker-desktop
 ID: J3OW:BRP6:2CBR:BMU6:2ZX2:6QUS:TRUQ:Y5AY:S3CF:DEXZ:HYYH:2FEC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
MacBook Pro 2019 (BigSur version 11.2)

**Comment by michaelweidmann** [comment]
What do you guys think? Does the API deliver the correct response and the Swagger spec is wrong or is it exactly the opposite?

**Comment by thaJeztah** [comment]
> Does the API deliver the correct response and the Swagger spec is wrong or is it exactly the opposite?

Even if the response is using the wrong name, it would already have been in a release, so in that case we can not change/rename, so we'd have to update the Swagger to match.


I had a quick look and it looks like there's indeed two types; `Mount`, and `MountPoint` in the codebase;

https://github.com/moby/moby/blob/228d800f5c8dbbf921ca0cdcf0aecb68ffd4e8a5/api/types/mount/mount.go#L22-L29

https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/volume/mounts/mounts.go#L23-L29

It's possible the wrong one is referenced in the Swagger, but we need to double-check

I can see that for SwarmKit ContainerSpec, the `Mount` type is used; https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/api/types/swarm/container.go#L65

Same for container.HostConfig; https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/api/types/container/host_config.go#L436-L437

This is where things get "interesting"; the response for `docker inspect` can depend on API version; https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/daemon/inspect.go#L22-L30

For the current API version, it will return `ContainerJSON`, which has a `Mounts` field (using `MountPoint`) https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/api/types/types.go#L368-L374

_However_, it also embeds `ContainerJSONBase`, which in itself embeds `HostConfig`; https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/api/types/types.go#L362


As mentioned above, `HostConfig` also has a `Mounts` field, but that one uses the `Mount` type.

What I think happens is that `HostConfig.Mounts` is masked by `ContainerJSON.Mounts`. I'm wondering if that was intentional or not


Some further digging; the `MountPoint` type was added in https://github.com/moby/moby/commit/1c3cb2d31ea722e2c174bf78eda62fec6949fb8b (https://github.com/moby/moby/pull/13711), and at that time, `HostConfig.Mounts` did not yet have a `Mounts` field; https://github.com/moby/moby/blob/1c3cb2d31ea722e2c174bf78eda62fec6949fb8b/runconfig/hostconfig.go#L223

The `Mounts` field in HostConfig was added later in https://github.com/docker/engine-api/commit/61712aa11e28fff0f8e5cfd2b1175f6a08a6d745 (https://github.com/docker/engine-api/pull/258), related to https://github.com/moby/moby/pull/22373

I see there was some mention of the `Destination` field in https://github.com/docker/engine-api/pull/258#discussion_r73948940
And in https://github.com/moby/moby/pull/22373#discussion_r61338732, where it was suggested to use `Target` instead of `Destination` 🤔

**Comment by thaJeztah** [comment]
@cpuguy83 perhaps you recall what the expectation was for this 🤔

**Comment by cpuguy83** [comment]
I'm not sure what you are asking.
Yes, it's two totally different types.
A `Mountpoint` was added sometime around 1.7, I think when named volumes were added.
It is returned as part of the inspect response related to the actual state of the container.
This is `<resp>.Mounts`

`HostConfig.Mounts` is the configuration used for creating mounts.

**Comment by thaJeztah** [comment]
> HostConfig.Mounts is the configuration used for creating mounts.

~Isn't one masking the other? (because `HostConfig.Mounts` is embedded, wouldn't it also show at the top-level? )~

Arf, I need more coffee, I thought it was directly embedded, but even then it would still show up as `HostConfig.Foo` in JSON (you can _assign_ as `container.Mounts = ...`, which is what my train of thought was)

**Comment by michaelweidmann** [comment]
If I understand this correctly, `HostConfig.Mounts` and `<resp>.Mounts` do not mask each other, do they?
If so, then in my opinion the type in Swagger is wrong:

https://github.com/moby/moby/blob/dbc3365da22ce76367ccaad79248c9a98332d80d/api/swagger.yaml#L4088-L4091

As you can see there, the `ContainerSummary`(or in context of the Go code `ContainerJSON`) uses the type `Mount`.
But in the actual code the `ContainerJSON` (in context of Swagger `ContainerSummary` uses the type `MountPoint`.

https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/api/types/types.go#L368-L374

Or am I missing something?

**Comment by cpuguy83** [comment]
`ContainerSummary` is for the `docker ps` endpoint, not `docker inspect`.

https://github.com/moby/moby/blob/dbc3365da22ce76367ccaad79248c9a98332d80d/api/types/types.go#L59-L77

And indeed the definition used in the swagger is incorrect. It is referring to the type used in `HostConfig`, which is totally different (and no they don't mask each other).

Difference here is `container.Mounts` vs `container.HostConfig.Mounts`

**Comment by michaelweidmann** [comment]
Alright, now I understand it fully. Thanks for the explanation. I opened a PR to correct the Swagger spec: https://github.com/moby/moby/pull/42129
