### ISSUE TITLE
Support other containerd shim v2 runtime implementations

### ISSUE THREAD

**Issue by liubin** [moby/moby#42239]
Now `dockerd` support other OCI runtimes other than `runc` in its config file,
but can't set other containerd shim v2 implementations like `io.containerd.kata.v2`.

If docker can directly set other containerd shim v2 implementations, it will be helpful to other new runtimes that only provide shim v2 interface.

**Comment by nyanpassu** [comment]
We faced the same problem here too. And I think it's the opts is an interface{} in api.types.ShimConfig so that we can't directly unserialize it directly. Maybe we need a plugin mechanism to support the feature, however there is a bug in plugin of Golang(not only in https://github.com/golang/go/issues/43749), so in practise a user has to load moby as a library and compile his/her own plugin, which is very unfortunately.

**Comment by neersighted** [comment]
Implemented in https://github.com/moby/moby/pull/43800, https://github.com/moby/moby/pull/43978
