### ISSUE TITLE
ContainerList inside a container occasionally can't find the container itself 

### ISSUE THREAD

**Issue by mieubrisse** [moby/moby#42354]
**Description**
Using `client.ContainerList` with a `name` filter inside a container to find itself works most of the time, but sometimes returns no results.

**Steps to reproduce the issue:**
(Non-deterministic) Inside a container, run `client.ContainerList` using `name` filter, searching for the container itself.

**Describe the results you received:**
Most of the time, I get back the container. Occasionally though, I get back 0 results.

**Describe the results you expected:**
The container should find itself every time

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue only happens occasionally (most of the time it works)

**Output of `docker version`:**
```
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 235
  Running: 18
  Paused: 0
  Stopped: 217
 Images: 374
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.844GiB
 Name: docker-desktop
 ID: YHEP:CYGH:FGVF:QE6V:AIIW:2S7V:CA7I:2YXP:QXAA:XHOO:BJYJ:Q6A3
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 88
  Goroutines: 84
  System Time: 2021-05-05T17:52:25.53428537Z
  EventsListeners: 4
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by mieubrisse** [comment]
What this looks like in my code:

Logline from the container that's trying to find itself:
```
ERRO[2021-05-05T17:55:09Z] An error occurred getting the initializer container's ID: Expected exactly one container matching execution ID 'B9883303-96C5-490E-A23A-CEBFBBE11751' but got 0
 --- at /build/initializer/main.go:346 (getInitializerContainerId) ---
Error: Testsuite execution failed
```
...but that container definitely exists if I use the UI:

<img width="1062" alt="Screen Shot 2021-05-05 at 12 57 20 PM" src="https://user-images.githubusercontent.com/1142185/117187376-750c1c80-ada1-11eb-808c-20fd5ed7c03a.png">

The only thing I can think of is that I'm running ContainerList pretty immediately after the container is started, so maybe there's a race condition where the container doesn't show up on the network yet?

**Comment by thaJeztah** [comment]
A race condition would be my initial suspect as well.

Basically, your trying to implement an introspection API, and your code is doing the equivalent of the below, correct?

```bash
docker run -it --rm \
    --name=hello \
    -e MYNAME=hello \
    -v /var/run/docker.sock:/var/run/docker.sock \
    docker:20.10 sh -c 'docker ps --filter name=$MYNAME'
```


Some quick thoughts;

I see you're using docker desktop; does the issue reproduce on Docker Desktop only, or are you using the same construct on Linux machines as well, and are you seeing the same issue there?

Docker Desktop uses a proxy for the Docker Engine API. The proxy is used to perform some rewriting of API calls to accommodate how Desktop needs to set up containers inside the VM (translation of IP addresses, paths inside/outside the VM, etc).

It's possible to connect to the API _without_ using the proxy to do so, use `/var/run/docker.sock.raw` instead of `/var/run/docker.sock` to connect with the "raw" socket, so (e.g.)  `-v /var/run/docker.sock.raw:/var/run/docker.sock` to bind-mount.

Are you seeing the same issue when using the raw socket?


What information are you trying to get about the container? You mention using the `client.ContainerList()` API (which returns _all_ containers), but filter it by name (to return a specific container). Does the issue reproduce if instead you would directly access information of the container you're looking for using the API that's used for `docker inspect` (`/v1.41/containers/<container name or id>/json`), which would be the equivalent of;

```bash
docker run -it --rm \
    --name=hello \
    -e MYNAME=hello \
    -v /var/run/docker.sock:/var/run/docker.sock \
    docker sh -c 'docker container inspect $MYNAME'
```

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
