### ISSUE TITLE
Flaky test: libnetwork/iptables TestConcurrencyNoWait

### ISSUE THREAD

**Issue by samuelkarp** [moby/moby#42458]
Looks like this failed a couple times on https://github.com/moby/moby/pull/42409

```
 === FAIL: libnetwork/iptables TestConcurrencyNoWait (0.14s)
     iptables_test.go:217:  (iptables failed: iptables -t nat -A POSTROUTING -p tcp -s 172.17.0.1 -d 172.17.0.1 --dport 4321 -j MASQUERADE: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
          (exit status 4))
```

**Comment by thaJeztah** [comment]
Ah, joy; more flaky tests that were previously in libnetwork 😞 

/cc @cpuguy83 (fyi 🤗)

**Comment by rvolosatovs** [comment]
The cause of the issue is that `gotestsum`, which is used by e.g. `hack/test/unit`, essentially just passes a list of packages to `go test` like `go test <A> <B> ... <Z>` with additional flags. Which means that tests for `<A>` and `<B>` can be run simultaneously, even though parallel testing is not used. What makes matters worse is that in case when packages `A` and `B` are indeed tested in parallel by `go` testing framework, these tests are run as different processes - that means that things like global mutex locking do not guarantee actually mutually exclusive access.

For this particular issue, the issue happens when `github.com/docker/docker/libnetwork/iptables` and `github.com/docker/docker/libnetwork/drivers/bridge` tests are run in parallel, since both tests rely on using `iptables` and locking mechanism utilized in `libnetwork/iptables` as seen here https://github.com/moby/moby/blob/c6dd474a496ee4a0978dd929f4e718d7c2bb892f/libnetwork/iptables/iptables.go#L539-L540 is ineffective, since the two tests are run as different processes and do not share memory (you can verify that by e.g. looking at the PID when the error occurs)

The failure can be reproduced regardless of architecture by e.g.:
```
TESTDIRS='github.com/docker/docker/libnetwork/iptables github.com/docker/docker/libnetwork/drivers/bridge' hack/test/unit
```
from within the dev container.

Note, that `-p=1` flag to `go test` fixes the issue, e.g.:
```
TESTFLAGS='-p=1' TESTDIRS='github.com/docker/docker/libnetwork/iptables github.com/docker/docker/libnetwork/drivers/bridge' hack/test/unit
```

So the simple solution then is to simply add `-p=1` to `TESTFLAGS` by default, which would make all tests be executed sequentially, which will most probably also slow down the tests.

I am not sure there is a simple solution to fix this without significantly complicating the `iptables` package locking implementation (by e.g. using on-disk lock) and I don't think we should go that route for something that can be mitigated with a testing flag.

FWIW, the only test failures locally with `TESTFLAGS='-p=1'` I see are the ones in `TestUserChain` (#42483)

**Comment by rvolosatovs** [comment]
Filed https://github.com/moby/moby/pull/42594 with the suggested fix, let's see what CI says
