### ISSUE TITLE
[Windows Swarm] windowsfilter directory isn't cleaned up - unreferenced layers are used by another process

### ISSUE THREAD

**Issue by lippertmarkus** [moby/moby#42521]
**Description**

We're running a Windows only swarm and are having a problem with the `windowsfilter` directory taking up an increasing amount of space. We found similar a similar issue in https://github.com/docker/for-win/issues/745 which should be fixed by https://github.com/moby/moby/pull/39193 - but that's not the case for us.

We tried using the tool from @olljanat from https://github.com/docker/for-win/issues/745#issuecomment-451441632 to check for unreferenced layers and there are indeed a ton of. When trying to delete them via `hccsshim::DestroyLayer` with that tool it fails because the unreferenced layers are still used by some other process:

```
PS [worker000008]:C:\> .\dlc.exe -folder F:\dockerdata\ -remove
Info: Unreferenced layer in layerDB:  68cc46ffdb1997403f3f9f40c01c6aec2761da72287a5faf694cb78a8bedc80a  removing...
Info: Unreferenced layer in layerDB:  b38cb8e83e6d9b17dcc8f066fa01b319800b0cded38771ea56dd55653e2611fa  removing...
Info: Unreferenced layer in windowsfilter:  69731bf0147dbe37e69e5a510620ef00e5674618bd2fc2bf09bfd569298db3c2  removing...
time="2021-06-14T08:53:39Z" level=error msg="hcsshim::DestroyLayer - failed failed in Win32: The process cannot access the file because it is being used by another process. (0x20)" error="hcsshim::DestroyLayer
- failed failed in Win32: The process cannot access the file because it is being used by another process. (0x20)" path="F:\\dockerdata\\windowsfilter\\69731bf0147dbe37e69e5a510620ef00e5674618bd2fc2bf09bfd569298
db3c2"
hcsshim::DestroyLayer - failed failed in Win32: The process cannot access the file because it is being used by another process. (0x20)
Info: Unreferenced layer in windowsfilter:  d2cffd6c642d4d4ee8667d6c0cf189d9145c059aee37a21251d38d648fddadf7  removing...
time="2021-06-14T08:53:39Z" level=error msg="hcsshim::DestroyLayer - failed failed in Win32: The process cannot access the file because it is being used by another process. (0x20)" error="hcsshim::DestroyLayer
- failed failed in Win32: The process cannot access the file because it is being used by another process. (0x20)" path="F:\\dockerdata\\windowsfilter\\d2cffd6c642d4d4ee8667d6c0cf189d9145c059aee37a21251d38d648fd
dadf7"
hcsshim::DestroyLayer - failed failed in Win32: The process cannot access the file because it is being used by another process. (0x20)
Info: Unreferenced layer in windowsfilter:  df61c379cd4e2c1fcf5da7d08b228c1f6a65e995bbbb515fcebe39691bb72b96  removing...
time="2021-06-14T08:53:39Z" level=error msg="hcsshim::DestroyLayer - failed failed in Win32: The process cannot access the file because it is being used by another process. (0x20)" error="hcsshim::DestroyLayer
- failed failed in Win32: The process cannot access the file because it is being used by another process. (0x20)" path="F:\\dockerdata\\windowsfilter\\df61c379cd4e2c1fcf5da7d08b228c1f6a65e995bbbb515fcebe39691bb
72b96"
hcsshim::DestroyLayer - failed failed in Win32: The process cannot access the file because it is being used by another process. (0x20)
Info: Unreferenced layer in windowsfilter:  f5f949baa668c26157b686ff4b5945b31c9e2c1b0f809be699ad67f037c32214  removing...
time="2021-06-14T08:53:39Z" level=error msg="hcsshim::DestroyLayer - failed failed in Win32: The process cannot access the file because it is being used by another process. (0x20)" error="hcsshim::DestroyLayer
- failed failed in Win32: The process cannot access the file because it is being used by another process. (0x20)" path="F:\\dockerdata\\windowsfilter\\f5f949baa668c26157b686ff4b5945b31c9e2c1b0f809be699ad67f037c
32214"
...
```

After a reboot those layers are not locked anymore but are still not deleted automatically by the Docker daemon. Removing them via the mentioned tool works however. 

This may is similar to https://github.com/moby/moby/issues/41120 and could also be related to https://github.com/microsoft/Windows-Containers/issues/37 ?

**Steps to reproduce the issue:**
1. Actively use docker to create/delete many containers
2. Check the `windowsfilter` directory size and verify with the mentioned tool that there are unreferenced layers which can't be deleted and are not cleaned up automatically

**Describe the results you received:**
Unreferenced layers in `windowsfilter` are not automatically cleaned up.

**Describe the results you expected:**
Unreferenced layers in `windowsfilter` should be automatically cleaned up.

**Additional information you deem important (e.g. issue happens only occasionally):**
Windows Base Image of containers used mainly: servercore, Version 10.0.19041.685

**Output of `docker version`:**

```
Client: Mirantis Container Runtime
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        6ee42dc
 Built:             03/11/2021 13:24:56
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Mirantis Container Runtime
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       1e08f21e79
  Built:            03/11/2021 13:23:32
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  cluster: Manage Mirantis Container Cloud clusters (Mirantis Inc., v1.9.0)
  registry: Manage Docker registries (Docker Inc., 0.1.0)

Server:
 Containers: 26
  Running: 22
  Paused: 0
  Stopped: 4
 Images: 252
 Server Version: 20.10.0
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: active
  NodeID: ln6la6pokb76l0nc2wot8dbcc
  Is Manager: false
  Node Address: 10.0.4.6
  Manager Addresses:
   10.0.3.4:2377
   10.0.3.6:2377
   10.0.3.7:2377
 Default Isolation: process
 Kernel Version: 10.0 19041 (19041.1.amd64fre.vb_release.191206-1406)
 Operating System: Windows Server Datacenter Version 2004 (OS Build 19041.867)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 64GiB
 Name: worker000008
 ID: GANI:XGAO:NZXV:UYRJ:YMHS:HONH:LB6A:W4EE:XTL2:MBPH:EO6H:T2MK
 Docker Root Dir: F:\dockerdata
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMs on Azure

**Comment by olljanat** [comment]
Just to clarify. #39193 primarily fixed #38488 which was far more serious issue as we was not able to trust container images integrity.

To fully resolve this issue at least also #38401 would be needed but unfortunately we was not able to agree what is correct way solve it and I eventually did give up. It is also worth to mention that I actually published [custom version of Docker](https://github.com/olljanat/moby/releases/tag/19.03.5-olljanat2) already a while ago which have also that fix included and we did run it on couple of hundred servers where we was able to see that issue maybe happened less often but was not still fully fixed.

However, because of those and especially because you say that you are using swarm I highly recommend to solve this issue by switching to process where you re-deploy those servers every month from patched image. Look: https://github.com/microsoft/hcsshim/issues/437#issuecomment-853223360

**Comment by lippertmarkus** [comment]
ok then I guess we have no other option. Thanks for the detailed answer!

**Comment by tfenster** [comment]
For anyone following up on this, we now have opened a support case with Microsoft and are waiting for answers

**Comment by lippertmarkus** [comment]
Support case with Microsoft is still open with Mirantis investigating

**Comment by lippertmarkus** [comment]
After 3.5 months of no actionable progress at all, the Mirantis escalation engineers now look into that topic...

**Comment by olljanat** [comment]
@lippertmarkus did you got some solution to this one from Mirantis?

**Comment by lippertmarkus** [comment]
Unfortunately not. After 7 months of continuous business impact for our 16 clusters they still didn't provide a solution, although the problem is so easily reproducible. 

The windowsfilter directory also fills up if there is a Swarm Service which references an image that doesn't exist. Docker then continuously tries to pull the non-existent image and creates new layers in windowsfilter every time. Those layers don't get cleaned up automatically by docker. A restart of the node is needed and only the cleanup tool I mentioned in https://github.com/moby/moby/issues/42521#issue-920453033 helps.

I am really wondering how you can make such a bad impression if you want enterprise customers to get a support plan starting in September 2022 with the transition from Microsoft to Mirantis. Doesn't seem like a good deal to me.

**Comment by olljanat** [comment]
> The windowsfilter directory also fills up if there is a Swarm Service which references an image that doesn't exist. Docker then continuously tries to pull the non-existent image and creates new layers in windowsfilter every time. 

Ah, that was new one for me. However using `--restart-max-attempts` probably helps as it makes Swarm to give up on that situation. Hard part is that it does need to be set to all the services separately.

Anyway, one thing which comes to my mind is that on that situation VHD file is most probably created and mounted. You can see those with PowerShell command `Get-Volume` if that is the case and it should be possible to umount them. Hard part is just figure out which ones are the ones which are not really in use.

> I am really wondering how you can make such a bad impression if you want enterprise customers to [get a support plan starting in September 2022](https://www.mirantis.com/blog/windows-server-container-users-mirantis-is-here-to-support-you/) with the transition from Microsoft to Mirantis. Doesn't seem like a good deal to me.

Yea I also don't see any sense to pay about that service. One interesting thing on that anyway is that now Docker is able to publish CE version of Windows Server binaries once again on https://download.docker.com/win/static/stable/x86_64/ which can be used instead of Mirantis binaries (which code is not completely open source).

**PS.** As Microsoft, Docker or Mirantis have not been able to solve this issue and I'm probably only one who would be able/willing to fix it. I'm working as private entrepreneur nowadays so if you or some other see this as critical issue that you are ready to buy couple of days consulting/development work to get it fixed to Moby you can contact me on Docker community Slack. We can set terms on way that I guarantee to get it fixed or other way that will work will be free of charge (I'm not able to do that contribution as part of my day job/main customer so it would mean evening/weekend work for me).

**Comment by visch** [comment]
Note as a temp fix ` docker system prune` works well for me. Although the docker reported only removing ~2GB of data it actually removed >200GB.  We just run this on a schedule now 🤷

**Comment by lippertmarkus** [comment]
After having similar issues under Kubernetes with containerd and investigating further in https://github.com/kubernetes/kubernetes/issues/116020 we found out that it's likely a Windows Defender issue

**Comment by thaJeztah** [comment]
Ah, yes, we've seen cases where Windows Defender can cause issues (and severely impact performance)

**Comment by thaJeztah** [comment]
Ah! And ISTR that issue was when using a different location for Docker's storage (looks like that may be the case in your situation; I see a mention of `F:\dockerdata\`); ISTR the default locations are excluded by Defender, but for non-standard locations they may have to be manually excluded.

**Comment by TBBle** [comment]
[MS's own advice is to _not_ exclude container storage from virus scanning](https://learn.microsoft.com/en-us/windows-hardware/drivers/ifs/anti-virus-optimization-for-windows-containers#1-package-install). It seems fraught with problems to follow that advice, though, but it's there.

**Comment by olljanat** [comment]
> [MS's own advice is to _not_ exclude container storage from virus scanning](https://learn.microsoft.com/en-us/windows-hardware/drivers/ifs/anti-virus-optimization-for-windows-containers#1-package-install).

I understand that this guide is wrote for other anti-virus vendors. Defender probably does not follow those.

> It seems fraught with problems to follow that advice, though, but it's there.

Afaiu the main challenge is that Docker has build to run with root privileges where it can do what ever it wants to files. On Windows it runs as a system and with those credentials it can only do operations which file system allows.

I added some logic to handle that difference on https://github.com/moby/moby/pull/39193 but much more logic like that will be needed if we want to allow AV scan those Docker folders and lock files when it does so.

**Comment by TBBle** [comment]
I would hope that Windows Defender follows MS's own advice for AV authors. That seems like the prime test for whether the advice is actually valid.

But yeah, I don't really expect Docker or other code to handle "some other process is locking our files", since the nature of the container storage and its interactions with filesystem filters is an OS problem. (In fact, we're calling an OS API to do the deletion, _it_ should probably take care of stuff like this internally).

AV scanning container storage _should_ be done, otherwise it becomes the perfect place for a sufficiently-elevated malware to hide a copy of itself even if it's detected and cleaned from other locations. Once the layer is extracted to disk, it has no protection against modification.

So I don't have a better solution. >_<

I will note that since this is deleting of no-longer-referenced layers, the virus scanner should not be trying to scan those layers unless they were just created, as after initial import there should be no modifications that trigger later scans. The fact that in the original issue, the problem persisted until a reboot suggests an actual bug in Windows Defender or HCS that causes a deadlock on some file or files, rather than an unlucky timing bug.

**Comment by lippertmarkus** [comment]
It was fixed for me with the windows update

**Comment by thaJeztah** [comment]
Thanks! Let me go ahead and close this one, but feel free to comment if there was something left to address 👍
