### ISSUE TITLE
Feature request: Forward docker tag to another when pulling images, equals to a 'lazy tag' operation

### ISSUE THREAD

**Issue by sanzenwin** [moby/moby#42585]
**Description**

When we want to get a image which from slow registry, we need to pull it from faster registry and then tag it to the slow one:
```
docker pull fast-registry/foo:tag
docker tag fast-registry/foo:tag slow-registry/foo:tag
```

**Describe the results you expected:**
```
# Just record a forwarding operation, do not pull or tag immediately.
docker forward slow-registry/foo:tag fast-registry/foo:tag
```
Docker will pull the fast one and then tag it to the slow one when doing `docker pull`.

**Comment by thaJeztah** [comment]
Thanks for opening. I think this is out of scope for the functionality that the docker daemon provides. This would also (currently) not be possible to transfer multi-arch images between registries, because `docker pull` will only pull the image for the operating system and architecture on which the daemon runs.

There are various tools that provide this functionality though. For example @sudo-bmitch's "regclient" allows synchronising images between registries; https://github.com/regclient/regclient#regsync-features

Let me close this ticket because of the above, but feel free to continue the conversation.
