### ISSUE TITLE
cbfs driver causes 'hcsshim::PrepareLayer - failed failed in Win32: Incorrect function. (0x1)'

### ISSUE THREAD

**Issue by nickwesselman** [moby/moby#42807]
**Description**

> *Note*: There is a long two-year old discussion, with lots of "me too" comments on this issue at docker/for-win#3884. Re-opening here based on feedback from @stephen-turner.

Starting with Windows 10 1903, having certain 'drive' software installed with certain versions of CBFS drivers causes Docker builds to fail with Windows containers, even with the most trivial Dockerfile.

```
hcsshim::PrepareLayer - failed failed in Win32: Incorrect function. (0x1)
```

**Steps to reproduce the issue:**
1. Install [Box Drive](https://www.box.com/resources/downloads) (no need to log in, just install)
2. Create a simple Dockerfile
```
FROM mcr.microsoft.com/windows/nanoserver:1809
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
```
3. `docker build .`

**Describe the results you received:**
```
➜  docker build .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM mcr.microsoft.com/windows/nanoserver:1809
 ---> f524b7260f3c
Step 2/2 : SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
 ---> Running in 389b868934e6
hcsshim::PrepareLayer - failed failed in Win32: Incorrect function. (0x1)
```

Uninstalling Box Drive makes the issue go away.

**Describe the results you expected:**
A successful build.

**Additional information you deem important (e.g. issue happens only occasionally):**
The company that makes this [CBFS Connect driver](https://www.callback.com/cbfsconnect/) used by Box and others has apparently released a version with a workaround for this bug. Installing software that contains this updated driver (such as [SFTP Drive v2](https://www.nsoftware.com/sftp/drive/)) actually resolves the issue. However Box has not released a fix, and insists that the issue is a regression in Docker and/or Windows itself.

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:58:50 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:54:29 2021
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 11
  Running: 0
  Paused: 0
  Stopped: 11
 Images: 801
 Server Version: 20.10.8
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 19043 (19041.1.amd64fre.vb_release.191206-1406)
 Operating System: Windows 10 Enterprise Version 2009 (OS Build 19043.985)
 OSType: windows
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.81GiB
 Name: LT-NWE1-T-US
 ID: KJ3K:R3GY:FLRD:BAJT:4KZW:LFB3:KPOO:JMA7:Y5Y7:UYWE:MPYU:2M7U
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 26
  System Time: 2021-08-31T14:21:10.5302762-04:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by emayevski** [comment]
Docker makes a certain request and expects a specific error code to be returned. If there's any other error code reported by the driver, Docker refuses to continue.  So, it's not anyone's bug but something that Docker should definitely improve for better compatibility.

**Comment by thaJeztah** [comment]
Perhaps someone could get a trace for this, as was suggested in https://github.com/moby/moby/issues/42804#issuecomment-910887723

> You could try to get some HCS traces by following https://docs.microsoft.com/en-us/virtualization/windowscontainers/troubleshooting#capturing-hcs-verbose-tracing.

**Comment by Kollgergo** [comment]
Also experienced this issue using pCloud and docker on the same machine.
The issue seams to happen when I try to build a Dockerfile with SHELL instruction as @nickwesselman reported it. In my experience SHELL instruction always fails but other builds not containing SHELL can succeed.

After uninstalling pCloud (and removing the CBFS driver which was left behind...) the issue resolves and the Dockerfile is built.

**Comment by TBBle** [comment]
I can confirm that it replicates just with `wclayer` on my Windows 10 20H2 (19042.1165) desktop box.

Given `32ebba58e25d6508c171d737289fc376095d82d0b026132e903dd32673a88a65` is a Windows container base layer (I happened to have `hello-world:latest` pulled here, so I think this is a nanoserver base, and then working in some temp directory:

```PowerShell
## Box is not installed
> wclayer create tm -l C:\ProgramData\Docker\windowsfilter\32ebba58e25d6508c171d737289fc376095d82d0b026132e903dd32673a88a65
> wclayer mount tm -l C:\ProgramData\Docker\windowsfilter\32ebba58e25d6508c171d737289fc376095d82d0b026132e903dd32673a88a65
\\?\Volume{74a47361-9cf4-4774-8655-a25fb69af17a}
> wclayer unmount tm
```

```PowerShell
## Installed https://e3.boxcdn.net/box-installers/desktop/releases/win/Box-x64.msi here, closed the login window
> wclayer mount tm -l C:\ProgramData\Docker\windowsfilter\32ebba58e25d6508c171d737289fc376095d82d0b026132e903dd32673a88a65
hcsshim::PrepareLayer - failed failed in Win32: Incorrect function. (0x1)
```

The loaded filesystem filters are unchanged by installing or uninstalling Box, so however CBFS works, it's not a [minifilter](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/filter-manager-concepts) as I had assumed, or somehow it's causing problems without being loaded.
```
>fltmc

Filter Name                     Num Instances    Altitude    Frame
------------------------------  -------------  ------------  -----
bindflt                                 1       409800         0
FsDepends                               8       407000         0
WdFilter                                8       328010         0
storqosflt                              1       244000         0
wcifs                                   1       189900         0
gameflt                                 5       189850         0
CldFlt                                  1       180451         0
FileCrypt                               0       141100         0
luafv                                   1       135000         0
npsvctrig                               1        46000         0
Wof                                     6        40700         0
FileInfo                                8        40500         0
```

I do see it's a kernel mode driver.
```
A service was installed in the system.

Service Name:  cbfsconnect2017
Service File Name:  C:\WINDOWS\system32\drivers\cbfsconnect2017.sys
Service Type:  kernel mode driver
Service Start Type:  system start
Service Account:  
```

```
> sc query cbfsconnect2017

SERVICE_NAME: cbfsconnect2017
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 4  RUNNING
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```

So I'm assuming it's a [legacy filesytem filter driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/about-file-system-legacy-filter-drivers). However, the docs for that say it should appear in the above `fltmc` output. I _suspect_ that's because the driver installation is being done with the [Service Control Manager (pre-XP) approach](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/installing-a-file-system-filter-driver).

I uninstalled Box, and installed SFTP Drive V2 Personal Edition, and confirmed that it looks the same (i.e. not in `fltmc` output) and the repro case passes. So the difference must be in the driver implementation itself.

So I can confirm that the 2019 release of cbfsconnect bundled with Box shows this problem, and the 2020 release of cbfsconnect bundled with SFTP Drive V2 does not.

And it's nothing to do with Docker, it's a conflict between the device driver and the Windows container filesystem support.

Windows 10 1903 [introduced some driver model changes](https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/creating-a-primitive-driver), so it's not unbelievable to me that this is what introduced the incompatibility, and since the fix is apparently obvious to the CBFS driver developers in their closed-source product, I can't see any useful way forward except either:
* CBFS driver developers acknowledge it was a bug or legacy issue in their code and the Box developers upgrade their integration
* CBFS driver developers useful document the Windows bug they are working around to Microsoft (perhaps raise it on the HCSSHIM bug tracker, since there's a simple repro case there), and MS fixes it as appropriate.

**Comment by thaJeztah** [comment]
Wow, thanks for the deep-dive into this, @TBBle. Looks like there's not a lot that can be done in this repository.

Does someone on this thread have a subscription for Box Drive or is in contact with the  CBFS Connect driver people to get the missing information?

**Comment by nickwesselman** [comment]
I don't have a direct relationship but I've reached out to Callback Technologies via some public mailboxes, and asked them to respond here.

**Comment by thaJeztah** [comment]
Thanks! Hopefully someone from them is able to respond so that we are able to find a solution to this problem.

**Comment by nickwesselman** [comment]
Hey all. Here is what I got back from Callback Technologies. Since I am not familiar with the technical details here and can't discern what's relevant/important, I am re-posting as is.

> CBFS Connect is a full filesystem driver, not a filter driver or minifilter. To help with this issue I will first provide some background then talk more about our investigation into the issue.
>
>It is incredibly important when talking about issues involving driver technologies to start from a low-level concrete test case. In this case since we are testing the issue using Docker’s interface to build an image, this is too high-level and does not tell us much about the operations happening underneath the covers. Since our filesystem driver will receive IRPs from the system, from the perspective of the driver it is not always clear the specific sequence of events which cause an IRP to be sent to us from the I/O manager. In order to comprehend the sequence of events which leads to an IRP being generated by I/O manager, it is necessary to know all the user-mode operations involved.
>
>Setting that aside for the time-being, in this case, we were able to analyze the test case and saw the same behavior as others: when building an image, the parameter is incorrect error is reported when older version of cbfsconnect2017 driver is installed and does not get reported when a newer version of cbfsconnect2017 is installed. At this point what we can say is some specific sequence of events triggers the Windows I/O Manager to send us an  IRP_MN_MOUNT_VOLUME request. In the older version of the driver we complete the IRP by failing it with NTSTAUS STATUS_FWP_INVALID_PARAMETER. Our understanding is this is a perfectly valid error code to return when the operation does not make sense. 
>
>One thing is for certain, that the MS documentation for this IRP is not entirely clear. It states “if a file system driver receives this IRP for a volume whose format does not match that of the file system the file system driver should return STATUS_UNRECOGNIZED_VOLUME” (https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/irp-mj-file-system-control ). It stands to reason that other errors are also possible (including invalid parameter). Therefore, it is our understanding nothing strange happening and it seems like either Docker or Windows does not like it when a different error is returned. We haven’t talked about the newer build of the 2017 driver yet.
>
>After the point we return this status, either Windows or Docker must be checking the code and reporting the error to the higher layers. The reason the issue goes away when installing a newer build of cbfsconnect2017 is not due to a bug or problem on our side, but we indeed made a change to workaround this side-effect reported a year ago. External logic which checks the error codes being returned is not something we control. We will now return the STATUS_UNRECOGNIZED_VOLUME value all the time. This change is present in the driver version used by SFTP Drive V2 going forward (even though we feel the “parameter is incorrect” status more accurately fits the bill). It is worth noting that in 15 years, the return codes have not caused problems for others and Docker seems to be the only one failing on it. 
>
>In short, there are two necessary steps to move forward from here. First, Box developers really should contact us and request an update to alleviate the problem for their users. This will come with drawbacks for them, as Microsoft changed signing requirements which will impact the application’s compatibility with older versions of Windows and non-updated versions of Windows. Second, Microsoft should clarify whether completing the IRP_MN_MOUNT_VOLUME request with a failure via invalid parameter status is okay. If the error is fine, which we suspect it is, the onus is on Docker or Windows to provide the logic that handles this case. To reiterate, our code just returns the error code coming from below, which is a perfectly valid strategy. We indeed made a change between the two versions being tested here; however, the observations with respect to the error going away do not demonstrate a problem exists in our code, as it is really the upper caller’s job to determine what to do with the error code that gets returned. 
>
>I hope this helps! Feel free to repost what you feel necessary to Docker’s issue tracking system.

**Comment by TBBle** [comment]
Interesting. My reading of that doc:
> Indicates a volume mount request. If a file system driver receives this IRP for a volume whose format does not match that of the file system, the file system driver should return STATUS_UNRECOGNIZED_VOLUME.

is different to the CBFS developers, my take would be that the _only_ valid response to `IRP_MN_MOUNT_VOLUME` in the case of "That's not my volume" is `STATUS_UNRECOGNIZED_VOLUME`, and that any other error code indicates "That _is_ my volume, and something else is wrong".

So the apparent behaviour in HCS or below (*not Docker* this is happening in a Windows-internal component as I demonstrated with `wclayer` earlier) seems reasonable to me based on the docs:
```
for each filesystem driver:
 result = ioctl(driver, IRP_MN_MOUNT_VOLUME, ...)
 if result == `STATUS_UNRECOGNIZED_VOLUME`: continue # Wrong driver, keep trying
 if result != SUCCESS: raise Exception("Driver said volume was faulty or parameter to mount were invalid")
 return driver
```

That seems to be the behaviour described in the [How the Volume is Recognized](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/how-the-volume-is-recognized) IFS docs, which suggests this routine is actually happening even lower-level than HCS, as a core Windows response to "a request to open a file on a logical volume (that is, a partition or dynamic volume)".

In that case, I'm not sure why the old CBFS driver didn't cause similar problems elsewhere. Maybe something HCS is doing was causing ordering differences in the filesystem driver search, or normally an earlier driver in the list (NTFS) recognises the volume and so CBFS wasn't being called in the general user case. Perhaps we'd see the same problem if I installed Box and then tried to mount an extfs2 volume for which there is no valid filesystem driver installed, getting "invalid parameter" instead of "no filesystem found".

It's also possible that _this_ volume mount is not supposed to find a driver, because HCS is going to apply the WCIFS minifilter before the volume can be mounted by the NTFS driver, but the error from CBFS is aborting that process with a response of "Actually, it's a CBFS device but it's faulty" and HCS aborts so it doesn't corrupt someone else's volume data.

The "How the Volume is Recognized" docs don't mention precisely how the driver is to signal "format does not match", but `STATUS_UNRECOGNIZED_VOLUME` is what the `IRP_MJ_FILE_SYSTEM_CONTROL` docs say for "a volume whose format does not match that of the file system", which _I_ read as being the same thing.

So yeah, this looks like possibly a documentation ambiguity, and I'd suggest that when implementing an API, it be implemented by the strictest-possible reading where multiple readings exist, as the updated version of CBFS now does.

**Comment by emayevski** [comment]
> is different to the CBFS developers, my take would be that the only valid response to IRP_MN_MOUNT_VOLUME in the case of "That's not my volume" is STATUS_UNRECOGNIZED_VOLUME, and that any other error code indicates "That is my volume, and something else is wrong".

That's the problem - someone in MS was trying to fit multiple different pieces of information into one variable. It would be more logical to have a separate parameter for an indicator of the volume recognition and reserve the result code for possible errors. 

But that's a different story.

**Comment by thaJeztah** [comment]
> In that case, I'm not sure why the old CBFS driver didn't cause similar problems elsewhere. 

Yes, curious about that as well; from the description it _seems_ like there's a chance it may fail / cause errors in different scenarios as well.


> referencing the same IRP_MN_MOUNT_VOLUME documentation, so perhaps it is HCS that got narrower in what it expects to receive from the mount call, and what it considers a failure, or perhaps a larger logic change in how HCS mounts volumes.

perhaps @katiewasnothere or @kevpar can help shine a light on this (or know who would be able to); and/or help improving the Windows documentation if it's ambiguous.

> That's the problem - someone in MS was trying to fit multiple different pieces of information into one variable. It would be more logical to have a separate parameter for an indicator of the volume recognition and reserve the result code for possible errors.

I'm not familiar with the overall Windows APIs in this respect, but it's a quite common pattern to use sentinel errors to control flows. In this case, (deducting from the above), I think the intent is;

- "no error": the driver successfully handled the request, so no need to continue with other drivers
-  `STATUS_UNRECOGNIZED_VOLUME`: (sentinel error): the driver did not handle the request, continue with next driver
- any other (non-sentinel) error: the driver was able to handle the request, but something failed. the error returned may be specific to this driver.

**Comment by nickwesselman** [comment]
Last email from Callback on this:

> Thanks for the update. It sounds like the direction is good and we don’t have anything further to add. The return status in newer builds does align with TBBle’s more strict interpretation. Let us know however we can assist. 

It seems there is nothing to fix in Windows/moby/Docker but rather this is now on Box to incorporate the updated driver. Thanks all for the thorough investigation, I'll close and continue my year+ effort to get Box to incorporate the fix. 😬

**Comment by thaJeztah** [comment]
Thank you!
