### ISSUE TITLE
host.docker.internal cannot be resolved when adding dns entries to daemon.json

### ISSUE THREAD

**Issue by op-euga** [moby/moby#42827]
When some DNS servers are defined in the daemon.json (internal dns of the company to resolve internal domains) the host.docker.internal is not accessible any in any container. If the dns section in the daemon.json is not set at all, the host.docker.internal can be resolved. I use Docker for Mac without any special config except for the dns.
I tried to add the docker network host 192.168.65.1 as well as my local ip from the network adapter as a dns entry, but this did not help to solve the issue. Can I add another IP so that the host.docker.internal will get solved again using some dns entries in the daemon.json?

**Output of `docker version`:**
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Output of `docker info`:**

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.2)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 74
  Running: 0
  Paused: 0
  Stopped: 74
 Images: 21
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 7.773GiB
 Name: docker-desktop
 ID: PPHS:YHG4:TDBW:K6YZ:MNV6:2YEA:3HWQ:ZZHW:JRXW:B2RC:PLM6:ITSB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by thaJeztah** [comment]
Thanks for reporting; I don't think this is something that can be resolved in this repository (at least not the "direct" issue here).

The reason this fails is because Docker Desktop implemented the `host.docker.internal` resolution through a DNS, which is accessible within the VM that runs for Docker Desktop. I _think_ for this to work, that DNS would need to be aware of the DNS that's configured, and acts as a forwarder (still performing resolution of the special `host.docker.internal` host, but forward other requests to the DNS server that's configured). Perhaps this already works if you configure the DNS on your _host_ (and have Docker Desktop inherit that configuration), instead of setting it as DNS in the `daemon.json`.

Overall, I think Docker Desktop may need to stop using the DNS for this purpose, as the `host.docker.internal` domain currently does not work (by default) on other setups. A similar (DNS based) solution would not be possible for installations other than Docker Desktop (e.g. docker running on a plain Linux host), because in those setups docker has no control over the DNS server.

To implement the `host.docker.com` functionality in a more portable approach (also taking into account hosted docker engines (e.g. ran by a cloud provider) where one doesn't have control over the daemon configuration), https://github.com/moby/moby/pull/40007 was implemented, which allows adding the `host.docker.internal` as an "extra host" inside the container. For example, here's on a Linux host;

```bash
docker run -it --rm --add-host host.docker.internal:host-gateway alpine ping host.docker.internal
PING host.docker.internal (172.17.0.1): 56 data bytes
64 bytes from 172.17.0.1: seq=0 ttl=64 time=0.120 ms
64 bytes from 172.17.0.1: seq=1 ttl=64 time=0.103 ms
64 bytes from 172.17.0.1: seq=2 ttl=64 time=0.093 ms
^C
--- host.docker.internal ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.093/0.105/0.120 ms
```

However, this option currently requires it to be set manually. There's a ticket to allow configuring it as a default on the client side; https://github.com/docker/cli/issues/2290, but this has not yet been implemented.

**Comment by thaJeztah** [comment]
I just chatted with someone more familiar with the DNS setup in Docker Desktop; if you configure your company's DNS as DNS server for your host (macOS), then Docker Desktop should automatically inherit that configuration, which means that Docker Desktop's internal DNS should resolve `host.docker.internal` and forward other DNS queries to the DNS server you configured on your machine.

That _does_ mean that the `daemon.json` should _not_ be modified to configure a custom DNS (as that would override using the Docker Desktop "internal" DNS).

Can you try if it works with the above?

**Comment by op-euga** [comment]
I tried to configure the DNS on the host as you mentioned and removed the dns config from the daemon.json but that did not work. the internal hosts could not be resolved. Seems the DNS setting were not inherited.

**Comment by thaJeztah** [comment]
> Seems the DNS setting were not inherited. 

Hmm.. interesting. I'd have to check if there's some debug-logs available somewhere to verify it's using the configured DNS (and if things failed, what the reason was for those).

Out of interest; are your "internal" domains also using `.internal` as domain? (wondering if something like that could cause it to not perform the lookup).

> would the "--add-host host.docker.internal:host-gateway" also work with docker-compose in the extra_hosts section?

Yes, the same should work for `extra_hosts`

**Comment by op-euga** [comment]
where can i get the debug logs?

the internal domains are _somehost_.local

Yes. the docker-compose worked.

**Comment by thaJeztah** [comment]
> where can i get the debug logs?

Not sure if there are debug logs, but perhaps @djs55 knows

> the internal domains are somehost.local

Do you know if it's using mDNS ([multicast DNS](https://en.wikipedia.org/wiki/Multicast_DNS)) for these hosts?

**Comment by djs55** [comment]
The DNS queries and responses should be visible in `~/Library/Containers/com.docker.docker/Data/log/host/com.docker.backend.log` e.g.
```
time="2021-09-08T14:47:50+01:00" level=info msg="UDP DNS <- ;; opcode: QUERY, status: NOERROR, id: 6703\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;www.docker.com.\tIN\t A\n"
...
time="2021-09-08T14:47:50+01:00" level=info msg="UDP DNS -> ;; opcode: QUERY, status: NOERROR, id: 6703\n;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;www.docker.com.\tIN\t A\n\n;; ANSWER SECTION:\nwww.docker.com.\t355\tIN\tCNAME..."
```
If the resolution is not working, another possibility is to edit `/etc/hosts` on the Mac and add some entries in there.

**Comment by devantoine** [comment]
🆙 

I faced the exact same issue.

@op-euga fix works like a charm though.

Used it in docker-compose:

```
services:
    app:
        image: nginx
        dns:
            - 8.8.8.8
        extra_hosts:
            - host.docker.internal:host-gateway
```
