### ISSUE TITLE
I'm not able to pull device stats using docker API.

### ISSUE THREAD

**Issue by cober2019** [moby/moby#43216]
I'm not able to pull device stats using docker API . When I try to get stats for a container using the following URI the API appears to combine the container ID with the next path in the API string,

appdev@Lab01:~/management-console/src$ curl http://localhost:5010/containers/8bedc871c465a26f0386720cef7e344a490d6837d75915ab309349945eeee196/stats/json

--> {"message":"No such container: 8bedc871c465a26f0386720cef7e344a490d6837d75915ab309349945eeee196/stats"}

Docker Version:

appdev@Lab01:~/management-console/src$ docker --version
Docker version 20.10.12, build e91ed57

System: Ubuntu 20.04, Azure

**Comment by thaJeztah** [comment]
:warning: First of all, I see your daemon is accessible over a http connection without being protected by TLS client authentication; please be _VERY_ careful with that, because access to the docker remote API is equivalent to `root` access on your host. Even when only allowing `localhost` connections, doing so means that in most cases a container would be able to access the API (so a compromised container will now have `root` access to your host). See https://docs.docker.com/go/attack-surface/ for more details

As to the issue you're reporting, it looks like you're using the wrong endpoint; The [stats endpoint](https://docs.docker.com/engine/api/v1.41/#operation/ContainerStats) is `/containers/{id}/stats`

However, you're using an URL ending with `/json`, so it will be handled by the [Container Inspect](https://docs.docker.com/engine/api/v1.41/#operation/ContainerInspect) endpoint (`/containers/{id}/json`), with `8bedc871c465a26f0386720cef7e344a490d6837d75915ab309349945eeee196/stats` used as `{id}`.

If you try `http://localhost:5010/containers/8bedc871c465a26f0386720cef7e344a490d6837d75915ab309349945eeee196/stats` or `http://localhost:5010/v1.41/containers/8bedc871c465a26f0386720cef7e344a490d6837d75915ab309349945eeee196/stats` (versioned API v1.41), things should work.


I'll close this issue, because this doesn't look like a bug, but feel free to continue the conversation

**Comment by cober2019** [comment]
Thanks for the solution. I actually did try this without json from my web app. Since I didn't have the one-shot and the disable streaming filters it wasn't working. Thanks again
