### ISSUE TITLE
Can the moby development team put more energy into the development of Swarm mode in the future?  

### ISSUE THREAD

**Issue by DavidSche** [moby/moby#43393]
**Description**
 
Whether the moby development team can devote more energy to the development of Swarm mode in the future, there are too many problems accumulated in Swarm mode. After all, Swarm is also a part of moby. In the past few years, although moby only made containers according to the requirements of Kubernetes, Kubernetes finally discarded it.
 
**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
It's an open source project; there's no "development team" - there's maintainers and contributors, some of which may be paid by companies to help development, but anyone is welcome to [contribute changes or fixes](https://github.com/moby/moby/blob/master/CONTRIBUTING.md).

If you have discovered a bug, or have a feature request, feel free to open a ticket (if none exists for it yet), and possibly a contributor may work on resolving it.

I'm closing this ticket because of the above, but feel free to continue the conversation.
