### ISSUE TITLE
Moby Linux 1903 AMI Removed from AWS last week. How can we get a copy or rebuild it?

### ISSUE THREAD

**Issue by webologics** [moby/moby#43469]
Here are the AMI IDs of community AMIs that were deleted. This is causing us a huge headache:
            "us-east-1": {
                "HVM64": "ami-05e6851734ba6f512"
            },
            "us-east-2": {
                "HVM64": "ami-0a427aae447c60a4e"
            },
            "us-west-1": {
                "HVM64": "ami-07269a9d9b90ca6e3"
            },
            "us-west-2": {
                "HVM64": "ami-055e0fe7520677870",
            }
These were used by a cloudformation template

**Comment by justincormack** [comment]
Hi, these have not received security updates for some years (since around 2018 I believe), and have been unsupported since then. The source code was not released, but it was based on an early version of LinuxKit, so that was released in the git history of https://github.com/linuxkit/linuxkit, although the AMI build scripts were not in that repo. I would recommend you use something else, but if you want to discuss you can email me justin at docker dot com

**Comment by thaJeztah** [comment]
Thanks @justincormack !

@webologics I'm closing this ticket, as it's unrelated to the open source project in this repository, but feel free to continue the conversation (or to contact Justin as mentioned in his reply), thanks!
