### ISSUE TITLE
Rootless Docker Service doesn't use native overlayfs (` Native Overlay Diff: false`)

### ISSUE THREAD

**Issue by sighoya** [moby/moby#43626]
**Rootless Docker Service doesn't use native overlayfs**

Rootless Docker Service doesn't use native overlayfs despite modprobe options:
```options overlay metacopy=off redirect_dir=off```
whereas, the root Docker service works as expected.

**Steps to reproduce the issue:**
1. export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock
2. systemctl --user start docker.service
3. docker info | grep Native

**Describe the results you received:**
  Native Overlay Diff: false

**Describe the results you expected:**
  Native Overlay Diff: true

**Output of `docker version`:**

```
Docker version 20.10.16, build aa7e414fdc
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., 2.5.1)

Server:
 Containers: 6
  Running: 2
  Paused: 0
  Stopped: 4
 Images: 4
 Server Version: 20.10.16
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: none
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
  cgroupns
 Kernel Version: 5.15.40-1-lts
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 62.47GiB
 Name: phantom
 ID: SMDW:PBEU:YHFR:NAVA:5WGK:ELUL:YRF3:SIHN:JEZB:FV52:LQZD:GUSE
 Docker Root Dir: /home/sighoya/vm/docker
 Debug Mode: true
  File Descriptors: 40
  Goroutines: 59
  System Time: 2022-05-21T16:02:20.585738277+02:00
  EventsListeners: 0
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: Running in rootless-mode without cgroups. Systemd is required to enable cgroups in rootless-mode.

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
ArchLinux Linux phantom 5.15.40-1-lts #1 SMP Sun, 15 May 2022 19:07:59 +0000 x86_64 GNU/Linux

See also: https://github.com/moby/moby/issues/41802

**Comment by john-jam** [comment]
We also hit this with `rootless-mode` docker on `Ubuntu 18.04 4.15.0-196-generic` and `overlay2` storage. This causes some renamed/moved files/folders to exists from previous layers (afaik).

Any workaround or fixes? Thanks!

**Comment by jonasgeiler** [comment]
Unfortunately this problem still exists for me.
It seems like that the Native Overlay Diff detection is always forced to be `false` when in user namespace, since there is an early return in the detection function: https://github.com/moby/moby/blob/8b79278316b532d396048bc8c2fa015a85d53a53/daemon/graphdriver/overlay2/check.go#L28
Which then directly results in a warning message and the disabling of native overlay diff here: https://github.com/moby/moby/blob/8b79278316b532d396048bc8c2fa015a85d53a53/daemon/graphdriver/overlay2/overlay.go#L250

I think a fix would be: 
- Remove this user namespace check at https://github.com/moby/moby/blob/8b79278316b532d396048bc8c2fa015a85d53a53/daemon/graphdriver/overlay2/check.go#L28
- When rootless, use `user.overlay.opaque` instead of `trusted.overlay.opaque` at https://github.com/moby/moby/blob/8b79278316b532d396048bc8c2fa015a85d53a53/daemon/graphdriver/overlay2/check.go#L63 and at https://github.com/moby/moby/blob/8b79278316b532d396048bc8c2fa015a85d53a53/daemon/graphdriver/overlay2/check.go#L83
- When rootless, use `user.overlay.redirect` instead of `trusted.overlay.redirect` at https://github.com/moby/moby/blob/8b79278316b532d396048bc8c2fa015a85d53a53/daemon/graphdriver/overlay2/check.go#L100
- When rootless, add `userxattr` to the mount options at https://github.com/moby/moby/blob/8b79278316b532d396048bc8c2fa015a85d53a53/daemon/graphdriver/overlay2/check.go#L67

I might attempt a PR but I'm an absolute beginner in Go and also don't know anything about this code or overlayfs, except from what I've learned from looking at the [podman](https://github.com/containers/storage/blob/b0c3d9650bfb3b32a312640ae581f9fc7811bb87/drivers/overlay/check.go#L29) equivalent code.

**Comment by jonasgeiler** [comment]
Unfortunately this problem still exists for me.
It seems like the Native Overlay Diff detection is always forced to be `false` when in user namespace, since there is an early return in the detection function: https://github.com/moby/moby/blob/8b79278316b532d396048bc8c2fa015a85d53a53/daemon/graphdriver/overlay2/check.go#L28
Which then directly results in a warning message and the disabling of native overlay diff here: https://github.com/moby/moby/blob/8b79278316b532d396048bc8c2fa015a85d53a53/daemon/graphdriver/overlay2/overlay.go#L250

I think a fix would be: 
- Remove this user namespace check at https://github.com/moby/moby/blob/8b79278316b532d396048bc8c2fa015a85d53a53/daemon/graphdriver/overlay2/check.go#L28
- When rootless, use `user.overlay.opaque` instead of `trusted.overlay.opaque` at https://github.com/moby/moby/blob/8b79278316b532d396048bc8c2fa015a85d53a53/daemon/graphdriver/overlay2/check.go#L63 and at https://github.com/moby/moby/blob/8b79278316b532d396048bc8c2fa015a85d53a53/daemon/graphdriver/overlay2/check.go#L83
- When rootless, use `user.overlay.redirect` instead of `trusted.overlay.redirect` at https://github.com/moby/moby/blob/8b79278316b532d396048bc8c2fa015a85d53a53/daemon/graphdriver/overlay2/check.go#L100
- When rootless, add `userxattr` to the mount options at https://github.com/moby/moby/blob/8b79278316b532d396048bc8c2fa015a85d53a53/daemon/graphdriver/overlay2/check.go#L67

I might attempt a PR but I'm an absolute beginner in Go and also don't know anything about this code or overlayfs, except from what I've learned from looking at the [podman equivalent code](https://github.com/containers/storage/blob/b0c3d9650bfb3b32a312640ae581f9fc7811bb87/drivers/overlay/check.go#L29).

If I may, I will also mention a few people that were involved in earlier related issues/PRs (#41802 and #42235) for feedback on my little proposal above: @AkihiroSuda, @thaJeztah and @tiborvass

**Comment by AkihiroSuda** [comment]
Yes, and in addition the kernel version has to be checked to use userxattr

**Comment by jonasgeiler** [comment]
> @AkihiroSuda wrote: Yes, and in addition the kernel version has to be checked to use userxattr

Okay, so I guess it needs a `if kernel.CheckKernelVersion(5, 11, 0) {...}` somewhere (not sure if 5.11 is the right version). Should I attempt a PR or are you already looking into this?

**Comment by AkihiroSuda** [comment]
Hard to me to craft a PR during KubeCon, so submitting a PR would be much appreciated 🙏

**Comment by thaJeztah** [comment]
@AkihiroSuda do you know if there's properties we can detect if it can be used instead of kernel version? (curious if we can avoid kernel version for this, in cases where kernel versions "lie" and the distro is carrying patches). If not, that's fine, mostly curious ☺️

**Comment by jonasgeiler** [comment]
> @thaJeztah wrote: (at)AkihiroSuda do you know if there's properties we can detect if it can be used instead of kernel version? (curious if we can avoid kernel version for this, in cases where kernel versions "lie" and the distro is carrying patches). If not, that's fine, mostly curious ☺️

I just noticed that the `usingMetacopy` function already has a whether userxattr is supported or not. I will try to adapt it for the `doesSupportNativeDiff` function 🤔 
https://github.com/moby/moby/blob/8b79278316b532d396048bc8c2fa015a85d53a53/daemon/graphdriver/overlay2/check.go#L129-L138

**Comment by jonasgeiler** [comment]
Right, PR is out - let's see if we can get this fixed!
