### ISSUE TITLE
port ranges: docker picks a host port used by process other than itself

### ISSUE THREAD

**Issue by singholt** [moby/moby#44136]
### Description

Hello,

If I use a container port and map it to a range of host ports, docker picks one port from the specified host port range. 

When doing so, docker picks a port in-use by a non-docker started process, when there are other ports in the range that are available.

For example,
```
docker run -itd -p 21-23:100 busybox 
```
Above, docker would pick one of 21-23 host port and map it to container port 100.

In the same example above, lets say host port 21 is in-use by a running container, host port 22 is for ssh, host port 23 is available. Docker skips 21, but picks 22 and fails while trying to map it to container port 100. whereas, it should determine that both port 21 and 22 are in-use, and then pick port 23.

It seems to only know of ports used by itself (process called `docker-proxy`)

### Reproduce

1. check host ports in use, for example port 22 for SSH, etc.

(output below is just an example, not the entire list of ports on my host)

```
sudo netstat -tulpn | grep LISTEN

tcp        0      0 127.0.0.1:39097         0.0.0.0:*               LISTEN      4824/containerd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      3479/sshd
```

2. run a container `ctr1` with 1 container port mapped to a range of host ports
```
docker run -itd -p 21-23:100 busybox 
```

port 21 is free, docker maps it to container port 100.

3. check in-use ports on the host

```
sudo netstat -tulpn | grep LISTEN
tcp        0      0 127.0.0.1:39097         0.0.0.0:*               LISTEN      4824/containerd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      3479/sshd
tcp        0      0 0.0.0.0:21              0.0.0.0:*               LISTEN      6105/docker-proxy   
```

4. run another container `ctr2`. 
```
docker run -itd -p 21-23:100 busybox 
```

this fails with reason:
`docker: Error response from daemon: driver failed programming external connectivity on endpoint X: Error starting userland proxy: listen tcp4 0.0.0.0:22: bind: address already in use.`

### Expected behavior

Docker should pick a host port that's not in-use, even if its used by processes other than `docker-proxy`

### docker version

```bash
Client:
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.18.3
 Git commit:        100c701
 Built:             Thu Jun 16 20:08:47 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.3
  Git commit:       a89b842
  Built:            Thu Jun 16 20:09:24 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.3
  GitCommit:        1e7bb5b773162b57333d57f612fd72e3f8612d94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 80
  Running: 2
  Paused: 0
  Stopped: 78
 Images: 7
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: 1e7bb5b773162b57333d57f612fd72e3f8612d94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.290-217.505.amzn2.x86_64
 Operating System: Amazon Linux 2
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.582GiB
 Name: ip-10-0-30-217.ec2.internal
 ID: KSG3:W7JG:IKW7:HZZC:BMVO:WRTF:6CKK:ZHXU:4UV3:TVRV:4GSN:RV2X
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 57
  Goroutines: 65
  System Time: 2022-09-12T21:33:22.945918853Z
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by akerouanton** [comment]
I started looking into this issue, but I'd like to gather insights from some maintainers to come up with a good way to fix it.

---

Port allocation starts here: https://github.com/moby/moby/blob/9052e33a10685a1f2188371624a08be2069889aa/libnetwork/drivers/bridge/port_mapping.go#L156-L167

Currently, if a port range (to pick from) is specified, then the loop early exits. This can be easily fixed (`if bnd.HostPort != 0 && bnd.HostPortEnd > bnd.HostPort {`) but I'm not sure about the whole design of portallocator & portmapper pkgs:

* The portallocator only iterates over the specified port range and checks if the chosen port is not already used by dockerd. It actually allocates nothing from the system.
* Then, the portmapper pkg starts either the userland proxy, or a dummy proxy. Both are the real thing allocating the port from the system.

I feel like the portallocator is wrongly named as it allocates nothing from the system. I'm considering changing that: portallocator would do the bind syscall and return the opened fd to the portmapper, so it can pass it to the proxy (if any). If the bind fails because the specified port is already used, it'd try the next port, and so on until it finds a port available. If we go along with this, I'd also remove the loop above as the portallocator would already implement the retry logic.

@neersighted and @corhere: What do you think about that? There seems to be an equivalent to SCM_RIGHTS on Windows, have you ever used it before? Have you other plans in mind about those two packages?

**Comment by ishaan1091** [comment]
Hey, is this issue solved or is there any workaround to it?

**Comment by akerouanton** [comment]
Hi @ishaan1091, this issue is not solved yet and there's no workaround. However, I'm going to make important changes in the way the port allocator and port mapper work in the near future. Hopefully, it'll be fixed in v25.

**Comment by idiazcir** [comment]
Hi,
I believe I am having the same issue. What is the status of it?
Today I have updated Docker to v25, although from the [release notes](https://docs.docker.com/engine/release-notes/25.0/), it seems this hasn't been fixed yet. If this is right, any idea of when it may be fixed?

**Comment by corhere** [comment]
> I feel like the portallocator is wrongly named as it allocates nothing from the system. I'm considering changing that: portallocator would do the bind syscall and return the opened fd to the portmapper, so it can pass it to the proxy (if any). If the bind fails because the specified port is already used, it'd try the next port, and so on until it finds a port available.

Genius, I love it! And it gets even better: we can ask the kernel to allocate a random ephemeral port for us by bind()ing to port 0! We'd only have to loop through ports if a user wants a different range for "container-ephemeral" ports than the kernel ephemeral range [and is not running Linux 6.3+.](https://man7.org/linux/man-pages/man7/ip.7.html#:~:text=IP_LOCAL_PORT_RANGE%20\(since%20Linux,the%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20lower%20bound.) The portallocator could become practically stateless! Although when it has to fall back to looping, the allocator should probably remember the most recent ephemeral port it probed [so it doesn't waste cycles always starting from the bottom of the range.](https://en.wikichip.org/wiki/schlemiel_the_painter%27s_algorithm) The portmapper (or userland proxy) would also need to keep a mapping of ip:port -> socket so it could release allocations, but that's about it.
