### ISSUE TITLE
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by Dorfeuheinz** [moby/moby#44263]
### Description

```bash
$ sudo systemctl restart docker.service
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xeu docker.service" for details.

$ systemctl status docker.service
× docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2022-10-07 16:27:24 IST; 31s ago
TriggeredBy: × docker.socket
       Docs: https://docs.docker.com
    Process: 954799 ExecStart=/usr/sbin/dockerd -H fd:// $DOCKER_OPTS (code=exited, status=1/FAILURE)
   Main PID: 954799 (code=exited, status=1/FAILURE)
```

### Reproduce

```
E: Unable to locate package docker-compose-plugin



$ sudo rm -rf /var/lib/docker
rm: cannot remove '/var/lib/docker/runtimes': Bad message
```

### Expected behavior

Idk why docker is not starting please help

### docker version

```bash
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.11.6
 Git commit:        4c52b90
 Built:             Sun, 23 Jun 2019 01:25:10 +0800
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

### docker info

```bash
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by Dorfeuheinz** [comment]
i went in the /etc/docker dir & created a file daemon.json & pasted this inside-
{
"exec-root": "/path/to/docker/run",
"storage-driver": "overlay",
"graph": "/path/to/docker/lib"
}

Then when i did : $service docker start , it worked miraculously. 
Thanku and lemme know if u find what was the issue

**Comment by thaJeztah** [comment]
Very difficult to tell what the issue was; unfortunately `systemctl status docker.service` usually isn't very informative. The actual logs of the daemon may be more useful (`journalctl -xu docker.service`).

However as you removed `/var/lib/docker` (which deletes all data used by docker by default), I guess we'll never know.

Some things I noticed:

The `"graph"` configuration option on `daemon.json` is deprecated, and replaced by `"data-root"`; if you need custom locations for storage, I would recommend changing that option.

I also see that you're running Docker 18.09, which reached EOL 4 Years ago, is no longer maintained, and has various unpatched vulnerabilities. If possible, I'd highly recommend upgrading to a currently supported version of Docker (but make sure to test upgrades in a test environment before rolling out to production)


As there's nothing really actionable in this ticket, I'll close it, but feel free to continue the conversation

**Comment by Dorfeuheinz** [comment]
Thanks for looking into it. Tbh just to clarify i didnt delete /var/lib/docker. Or shud i say, i couldnt becoz of this weird error, but now things r working fine so yep.......thnx fr the info, ill upgrade the version
