### ISSUE TITLE
Crash in netutils.GenerateRandomName

### ISSUE THREAD

**Issue by secsys-go** [moby/moby#44362]
### Description

We used the Fuzz engine to modify some Test(TestGenerateRandomName) data, and then the following crash appeared. We hope to get the help of the developer to confirm whether it is a real bug.

### Reproduce

Part of the modified Test Code

```go
name1, err := GenerateRandomName("veth", 7902739824647)
```

Crash Log

```
panic: runtime error: slice bounds out of range [:7902739824647] with length 64 [recovered]
	panic: runtime error: slice bounds out of range [:7902739824647] with length 64

goroutine 77 [running]:
testing.tRunner.func1.2({0x5a2080, 0xc00001a558})
	/home/gogen/.local/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/home/gogen/.local/go/src/testing/testing.go:1212 +0x218
panic({0x5a2080, 0xc00001a558})
	/home/gogen/.local/go/src/runtime/panic.go:1038 +0x215
github.com/docker/docker/libnetwork/netutils.GenerateRandomName({0x5b3d96, 0x4}, 0x73000000007)
	/home/gogen/workspace/gowork/src/topproj/moby/libnetwork/netutils/utils.go:131 +0x107
```

### Expected behavior

-

### docker version

```bash
-
```

### docker info

```bash
-
```

### Additional Info

Implemented only with go test

**Comment by vvoland** [comment]
`GenerateRandomName` is only called by `GenerateIfaceName` which always calls it with a constant `size=vethLen=7` argument. 
There's no real bug here. Although the function could have an explicit check if size is bigger than 64 and then panic with some more descriptive messages. However, since currently all calls use a constant value here, it's very low priority.
