### ISSUE TITLE
Support REUSEPORT for the proxy

### ISSUE THREAD

**Issue by hydrargyrum** [moby/moby#44577]
### Description

Docker is notorious for its very poor IPv6 support. In the default dockerd config, publishing ports of a container with `docker run` or through docker-compose does not listen on IPv6 address. And when attempting to configure dockerd for IPv6, well, it's actually pretty bad.

So I tried a workaround:
- let the container publish port on IPv4 (binding on 0.0.0.0)
- have a socat process outside containers that will proxy requests (binding on [::]) to 127.0.0.1 so the container gets the request

But socat hits a "Address already in use" error because docker-proxy doesn't pass REUSEPORT (after a quick test, it seems REUSEADDR wouldn't be enough). Making docker-proxy able to pass REUSEPORT would let the socat proxy work fine.

**Comment by akerouanton** [comment]
Hi @hydrargyrum,

I think the right thing to do here is to fix dockerd such that IPv6 become a first-class citizen. Hopefully, we'll have the chance to work on that in the upcoming months.

Also, adding `REUSEPORT` to the userland-proxy would open the doors to more bugs & edge-cases, as this make it even more difficult (and racy) for the daemon to know for sure whether a port is legitimately in-use by another process. Since dockerd picks ports in the ephemeral port range when publishing ports without host port specified, we'd also have to make this behavior conditional. This introduces the question of what UX we want, and I think we don't want to give users control over how the proxy works.

In the end, I think implementing this feature is not only the wrong thing to do, but would actually draw on us time & energy that would be better invested in fixing IPv6 among other things.

So let me close this.

**Comment by hydrargyrum** [comment]
> Also, adding REUSEPORT to the userland-proxy would open the doors to more bugs & edge-cases, as this make it even more difficult (and racy) for the daemon to know for sure whether a port is legitimately in-use by another process. Since dockerd picks ports in the ephemeral port range when publishing ports without host port specified, we'd also have to make this behavior conditional.

It's not a question of opening the door to bugs. If docker could listen on ipv6 properly, blocking other apps from listening would be more acceptable. Currently, docker is very bad at ipv6 (to say the least), and preventing other apps from listening on ipv6, while docker can't do it itself, is just being a bad citizen.

I understand it might improve at it in a few months/years, but in the meantime it's a sad situation. Just adding a new flag could be a temporary situation until one docker handles ipv6 properly.
