### ISSUE TITLE
non-standard vendor/ approach breaks building with Buildroot

### ISSUE THREAD

**Issue by paralin** [moby/moby#44618]
### Description

https://github.com/moby/moby/pull/44615#issuecomment-1343519928
https://github.com/moby/moby/issues/44614

The old releases pre-v23.x worked correctly with GO111MODULE=on.

The new releases which use a custom approach to managing vendor/ do not:

```
$ go build -mod=vendor github.com/docker/docker/cmd/dockerd

go: inconsistent vendoring in docker-engine-:
  cloud.google.com/go@v0.102.1: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
  cloud.google.com/go/compute@v1.7.0: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
  cloud.google.com/go/logging@v1.4.2: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
  code.cloudfoundry.org/clock@v1.0.0: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
  [snip]

  To ignore the vendor directory, use -mod=readonly or -mod=mod.
  To sync the vendor directory, run:
  go mod vendor
```

Disabling go modules with GO111MODULE=off doesn't fix it either:

After applying the following changes to buildroot:

 - Set GO111MODULE=off
 - Remove -modcacherw flag
 - Change path passed to `go build` from the module path to `./cmd/dockerd`.

It still doesn't work, since Go doesn't recognize vendor/ anymore:

```
$ cd ./path/to/docker-engine
$ GO111MODULE=off go build -v ./cmd/dockerd
cmd/dockerd/daemon_unix.go:22:2: cannot find package "golang.org/x/sys/unix" in any of:
        /lib/go/src/golang.org/x/sys/unix (from $GOROOT)
        /host/share/go-path/src/golang.org/x/sys/unix (from $GOPATH)
```

The buildroot build infrastructure is here:

 - https://github.com/buildroot/buildroot/blob/master/package/pkg-golang.mk#L43
 - https://github.com/buildroot/buildroot/blob/master/package/docker-engine/docker-engine.mk

My request is to please play nice with the Go modules system and either go back to the way this worked before (which worked perfectly) or provide some solution for us which doesn't involve completely changing the Go package infrastructure in Buildroot for a single package.

### Reproduce

1. Try to build with `GO111MODULE=off`

### docker version

```bash
N/A
```

### docker info

```bash
N/A
```

**Comment by paralin** [comment]
Thanks to @thaJeztah who has found a workaround in https://github.com/moby/moby/pull/44615#issuecomment-1343543897

Delete `vendor/modules.txt` before running `go`.

**Comment by thaJeztah** [comment]
Would this work for your setup?

```bash
# create a stub go.mod
echo "module github.com/docker/docker" > go.mod 

# build, specifying the vendor.mod as module file
go build -mod=vendor -modfile=vendor.mod ./cmd/dockerd
```

**Comment by thaJeztah** [comment]
> Delete vendor/modules.txt before running go.

To some extend this feels like a bug in go; I wonder why it would look at a `modules.txt` file in a project that doesn't define a `go.mod` (so isn't a module).

**Comment by thaJeztah** [comment]
> Would this work for your setup?
> 
> ```shell
> # create a stub go.mod
> echo "module github.com/docker/docker" > go.mod 
> 
> # build, specifying the vendor.mod as module file
> go build -mod=vendor -modfile=vendor.mod ./cmd/dockerd
> ```

Advantage of this approach would be that the `go.mod` is in our `.gitignore` (on purpose), so the git status won't show up as "dirty"

**Comment by paralin** [comment]
@thaJeztah We create a module file with `go mod init` if one doesn't exist. So that's why the Go tool is looking at `vendor/modules.txt`.

We could possibly add the workaround to use `-modfile` but I don't think its necessary since after deleting `vendor/modules.txt`, it will just use whatever's in vendor/ and checked into Git.

See here: https://github.com/skiffos/buildroot/pull/24/commits/5ce3f9687b4574846be26acec65f2c90abfca144#diff-b9133fa03d6aae3ff1af7fe8bebeb76cfcef1de2c2db6b0f5bc6b54191488781R71

Thanks again for your help.

**Comment by neersighted** [comment]
I think the real issue here is that you can't naively treat GOPATH projects as if they can build in module mode; it would still be better to build out of module mode if at all possible. I'm glad you found a workaround, but you are working around the intended semantics of the `go` (specifically `go mod`) tooling, and this may break again, as we only test/support GOPATH builds.

Hopefully this will solve itself as we make incremental progress toward a real Go module.

**Comment by paralin** [comment]
@neersighted you can, by creating a go.mod for the module and deleting vendor/modules.txt then using `go build -mod=vendor`

This uses the vendor/ tree and behaves the same as if the project was located in gopath at the correct location.

I don't see how it would break with any gopath-compatible changes.

It'd be great if it just used go modules properly though.

**Comment by thaJeztah** [comment]
When using your current approach, I wonder if Go correctly validates the checksums; perhaps a better approach would be to _copy_ `vendor.mod` and `vendor.sum` to `go.mod` and `go.sum`. That way you're using the actual files that we used during vendoring to verify that the vendoring is correct.

@neersighted we should probably add `go.sum` to `.gitignore` as well to allow that, WDYT? https://github.com/moby/moby/blob/77f9c550bdad89aa9d8f6a49ad1a90c6dd553dfe/.gitignore#L16-L17

**Comment by neersighted** [comment]
I would argue the opposite; my PRs remove `go.mod` from the `.gitignore` so that the locally created files are conspicuous for investigation when they are created and alter the behavior of the Go tooling.

**Comment by paralin** [comment]
> That is exactly what I am saying -- projects may do things that are perfectly legal in GOPATH mode, but not legal in go mod mode

Note that we are only using the vendor tree and none of the other go module features like downloading and checksumming. 

There are no gopath compatible changes that would not be compatible with this as well. 

Maybe I'm mistaken and if so please give me some examples of how you see this could be broken.

We don't care about validating the checksums because we checksum the source archive tar.gz which contains the vendor tree checked into git.

**Comment by neersighted** [comment]
> Maybe I'm mistaken and if so please give me some examples of how you see this could be broken.

Obviously, the current case is one (the presence of modules.txt). What I am trying to explain is that Moby is only designed and tested to build in GOPATH mode. We are explicitly **not** a Go module, and do not validate changes for Go module compatibility. You've found a workaround, deleting the single file that `go mod` objects to, which works for you, and that's fine. 

However, if another change made in Moby or the `go` tool itself breaks your workaround/workflow, I don't expect that anything but trivial fixes will be accepted in Moby -- it's simply not a build configuration we support.

In the short-medium term, we intend to become a Go module (and then obviously `go mod` mode will be supported, and indeed, the only build method we support); but there is a lot of work implied by that, and it won't happen overnight/without a lot of careful review.

**Comment by paralin** [comment]
That sounds fine as we test builds and add workarounds as needed in buildroot (as was done here).

I'd wonder what the big deal is about moving to go modules since everything seems to work fine if I follow the steps above to rename vendor.mod to go.mod and build using go.mod, but I digress. Perhaps you're needing to audit the changes in vendor/ each update.

**Comment by thaJeztah** [comment]
go modules solved "some" issues, but in doing so effectively broke backward compatibility. We still have a _LOT_ of work to do to make this happen (including a rename); we also need to refactor and restructure many of our packages to reduce dependency hell for consumers of the repository (before go modules, it was easier to ignore dependencies that you didn't need, with go modules, all of our dependencies (versions) are enforces on users, which can complicate things as we also have some circular dependencies).
But we want to make that transition, as without being a go modules, users of our code as a dependency must jump through a lot of hoops to be able to use it.

But yeah, go modules cause many breaking changes (they're not considered "breaking change" as it's outside of Go's v1 compatiblity promise);

- before go modules, `go get <some project>` always meant "latest from the default branch"
- while some users used vendoring tools to "pin" to specific versions, Go itself had no versioning for dependencies (implicit convention was that "main" / "master" should always be backward compatible)
- some projects started tagging releases to provide users a more convenient / semantic way to pin to a specific version, but that was not a requirement.
- other projects (such as docker (now "moby")) tagged _binary_ releases; tags on this repository are for binary releases of docker / moby.

When go modules were introduced, this all changed:

- Go took ownership of tags of all Go projects on GitHub (and elsewhere)
- It enforces the uses of SemVer versioning, and assumes that any tag that "looks" like SemVer _is_ SemVer
- Tags that do _not_ look like SemVer are ignored
- _Actually_ valid SemVer tags (SemVer does not officially allow `v` in versions) are considered invalid.
- Release branches  / long term release branches are _not_ supported (versions may be rolled back to older versions that are found on the main/master branch).
- `go get <some project>` no longer defaults to "latest from main / master", but "latest tag that looks like SemVer"; which in some case means: dependencies get rolled back to a tag from _years_ ago.
- Any tag that is v2.0.0 or up is considered "incompatible", and requires the project / import paths to be renamed. (in our case, requires all import paths to be renamed to "github.com/docker/docker/v20")

go modules allow for "invalid" versions, as long as there's no `go.mod` file in the repository; the moment that file is added, it is no longer importable (which is why we're using `vendor.mod`).
