### ISSUE TITLE
Incorrect detection of lack of Apparmor installed

### ISSUE THREAD

**Issue by XANi** [moby/moby#44970]
### Description

Package `23.0.1-1~debian.11~bullseye` on fresh install gives:

    AppArmor enabled on system but the docker-default profile could not be loaded:

the app armor is not installed nor enabled

The bug happened after we installed 23 on new node, previous ones on 20 didn't had the problem

### Reproduce

Install docker on fresh debian install

### docker version

```bash
Client: Docker Engine - Community
 Version:           23.0.0
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        e92dd87
 Built:             Wed Feb  1 17:43:17 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:46:54 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 53
  Running: 4
  Paused: 0
  Stopped: 49
 Images: 7
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.10.0-21-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 29.39GiB
 Name: d1-fw-kube20
 ID: 91ef61ab-0b63-4f4b-9f6c-6cfb41903247
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by wenzhuoz** [comment]
After being upgraded on an Armbian system to 23.0.1 a couple of hours ago, docker-ce could no longer start containers. The error message was:

```
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container
 process: error during container init: unable to apply apparmor profile: apparmor failed to apply profile: write /proc/self/attr
/apparmor/exec: no such file or directory: unknown
```

Installing the apparmor package didn't help. I had to downgrade it to 20.10.23.

**Comment by thaJeztah** [comment]
If you're running into this issue, what do the following commands show on your system?

```bash
ls /sys/kernel/security/apparmor
```

```bash
cat /sys/module/apparmor/parameters/enabled
```

```bash
apparmor_parser --version
```

**Comment by pavelvodrazka** [comment]
I have the same problem as @wenzhuoz on my Debian system without AppArmor installed, resulting in:
```
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: unable to apply apparmor profile: apparmor failed to apply profile: write /proc/self/attr/apparmor/exec: no such file or directory: unknown
```

 Here's my output:
```
$ ls -l /sys/kernel/security/apparmor
total 0
drwxr-xr-x 15 root root 0 Feb  1 20:17 features
lr--r--r--  1 root root 0 Feb  1 20:17 policy -> 'apparmorfs:[2154]'
-r--r--r--  1 root root 0 Feb  1 20:17 profiles
-r--r--r--  1 root root 0 Feb  1 20:17 revision
```
```
$ cat /sys/module/apparmor/parameters/enabled
Y
```
```
$ apparmor_parser --version
-bash: apparmor_parser: command not found
```

**Comment by nergdron** [comment]
we're seeing the same on all our hosts that've upgraded to `v23.0.x`, they all break on apparmor even though we definitely don't have the apparmor daemon installed or running. also, installing apparmor doesn't resolve the issue, it seems like the apparmor code in docker is broken with this release. we're on a mix of Ubuntu 20.04 and 22.04, all running from the official docker apt repo.

```
root@host-0:~# ls /sys/kernel/security/apparmor
features  policy  profiles  revision
root@host-0:~# cat /sys/module/apparmor/parameters/enabled
Y
root@host-0:~# dpkg -l | rg apparmor
pi  libapparmor1:amd64             2.13.6-10                      amd64        changehat AppArmor library
root@linksharing-0:~# cd /opt/service/
root@linksharing-0:/opt/service# docker compose restart
[+] Running 0/0
 ⠋ Container service-service-1  Restarting                                                                                             0.1s
Error response from daemon: Cannot restart container 00584aa5c7f75ada259a10d0ff951cce6eeaef921497b798aa30e2f57b68c34b: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: unable to apply apparmor profile: apparmor failed to apply profile: write /proc/self/attr/apparmor/exec: no such file or directory: unknown
```

we're going to roll back our packages for the time being, but this feels like a critical bug, at least to us.

**Comment by neersighted** [comment]
It's possible this is a duplicate of https://github.com/moby/moby/issues/44900 and not a new/worse regression -- right now I am thinking that the attempted fix was incomplete and didn't actually fix the original regression in 23.0.0.

If you could test that this also occurred on 23.0.0, that would be very helpful. It would also be helpful to make sure to provide `docker info`, `docker version` and the additional information @thaJeztah mentioned if you are affected. Thanks!

**Comment by pavelvodrazka** [comment]
@neersighted I can confirm that I had the problem described in #44900 when I upgraded to 23.0.0 few days ago. I had to rollback to 20.10.23. I was keen to try upgrade to 23.0.1 again when I saw its changelog, but unfortunatelly the fix is not complete.

**Comment by neersighted** [comment]
Is the issue you see the same across 23.0.0, or is there any change in the error message? I think I am spotting an incomplete fix, but as I am unable to reproduce any of the actual errors here, I am trying to extrapolate from incomplete reports & a code walk.

**Comment by neersighted** [comment]
Okay, that is quite helpful. Was this a crash, or just a failure to start a container?

**Comment by pavelvodrazka** [comment]
Failure to start a container.

**Comment by pavelvodrazka** [comment]
Sure, I can try later tonight.

**Comment by nergdron** [comment]
> Okay, are you able to install `apparmor_parser` (package `apparmor`), restart the daemon, and confirm you are able to start containers? The only thing that changed since 20.10 is that a check we used for `/sbin/apparmor_parser` was unintentionally removed.

oh, yeah, when I checked before I didn't restart docker after installing apparmor. if I do the following, then my containers keep working:

```
apt install -y apparmor && systemctl restart docker && cd /opt/service && docker compose restart
```

would definitely love confirmation from @pavelvodrazka, but I think you've found it, @neersighted!

**Comment by neersighted** [comment]
Okay, the root cause is understood, and the mitigation is the same: if you're not in some nested containerization scenario, install `apparmor`. It is a `Reccomends:` dependency of the daemon; that means that is technically possible to live without it, but it:
* is not the happy path
* may require manual intervention
* will reduce the security profile of your contianers

The only question is whether we wait for containerd to accept a revert of the problematic change, or if we spread our in-tree check further. Given that there is a workaround (to not go out of your way to avoid apparmor), and we have not regressed further 23.0.0 (but rather failed to fix a regression), I am inclined to wait for containerd to accept/decline the fix, and to not hurry this.

**Comment by pavelvodrazka** [comment]
@nergdron I can confirm that installing `apparmor` package and restarting docker service fixed the problem on my system.

**Comment by pavelvodrazka** [comment]
Unfortunately AppArmor broke some of my containers, so I have to go back to 20.10.23 until I figure out how to fix it with a less restrictive profile.

**Comment by neersighted** [comment]
You can set `--security-opt apparmor=unconfined` on the affected containers instead of taking a shotgun approach.

**Comment by wenzhuoz** [comment]
I can confirm too that installing apparmor prior to upgrading to 23.01 work around the issue.

**Comment by zmyjs** [comment]
I have the same problem
```
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: unable to apply apparmor profile: apparmor failed to apply profile: write /proc/self/attr/apparmor/exec: no such file or directory: unknown.
ERRO[0002] error waiting for container:
```
docker 23.0.1
Armbian 22.08.1 Jammy

**Comment by neersighted** [comment]
Please refrain from "me too," which is unhelpful (sends needless notifications) and unnecessary (there is a :+1: button, and there is a mitigation).

You can `apt install apparmor` as already discussed in this thread (and then restart `docker`, e.g. `systemctl restart docker.service`), or simply set `apparmor=0` on the kernel command line.

**Comment by spdfnet** [comment]
This also happens without Docker installed but with containerd.io from the Docker repo.
Same fix, just install apparmor and restart containerd...

**Comment by neersighted** [comment]
Yes, containerd also regressed (or rather, Moby was where people noticed, and containerd was also the root cause). The PRs in containerd point that out and will resolve the regression.

**Comment by frankyw** [comment]
> if you're not in some nested containerization scenario, install `apparmor`.

@neersighted and if you are, any thoughts on how to work around this?

**Comment by kiorky** [comment]
> > if you're not in some nested containerization scenario, install `apparmor`.
> 
> @neersighted and if you are, any thoughts on how to work around this? Thanks

downgrade.

**Comment by x-yuri** [comment]
From what I can see...

When the kernel is built with `apparmor` (`/sys/kernel/security/apparmor`), and `apparmor`'s enabled (`/sys/module/apparmor/parameters/enabled`), and the `docker`'s profile (`docker-default`) is not loaded, and `apparmor_parser` is not available (not installed), and `containerd >= 1.6.0` (`< 1.7.0`), `docker-23.x` fails to start containers, because it needs `apparmor_parser` to load its profile, e.g.:

```
$ docker run --rm -it alpine:3.17
docker: Error response from daemon: failed to create shim task: OCI \
runtime create failed: runc create failed: unable to start container \
process: error during container init: unable to apply apparmor profile: \
apparmor failed to apply profile: write /proc/self/attr/apparmor/exec: \
no such file or directory: unknown.
```

This is caused by `containerd` having stopped checking if `apparmor_parser` is available (which `docker` needs to load its `apparmor` profile, if not already loaded).

`docker` relies on `containerd` to check if `apparmor` is available [sinse `23.0.0`][a].

Before `containerd-1.6.0` that involved checking `/sys/kernel/security/apparmor`, `/sbin/apparmor_parser` and `/sys/module/apparmor/parameters/enabled`. But in `1.6.0` the `/sbin/apparmor_parser` check was [dropped][b]. The change was [reverted][c] in `1.7.0`.

`docker` added a [temporary fix][d], but it doesn't seem to [ever be released][e], since `containerd` reverted the change.

The workarounds:

* `apt install apparmor` (and restart the `docker` daemon)
* downgrade `containerd` to `< 1.6.0`
* downgrade `docker` to `< 22`
* `docker run --rm -it --security-opt apparmor=unconfined alpine:3.17`

[a]: https://github.com/moby/moby/commit/2834f842ee
[b]: https://github.com/containerd/containerd/commit/1acca8bba
[c]: https://github.com/containerd/containerd/commit/a3265102d
[d]: https://github.com/moby/moby/commit/ab3fa46502
[e]: https://github.com/moby/moby/commit/c4c54683a9

**Comment by Codelica** [comment]
I believe the "final" [fix](https://github.com/moby/moby/pull/45043) is pending in release 23.0.2 which appears to be [complete](https://github.com/moby/moby/milestone/114?closed=1).

**Comment by x-yuri** [comment]
Again from what I can see the final fix basically comes down to [switching to `containerd-1.6.18`][b], which [reverted][a] the behavior. The interesting thing is that with `docker-23.0.1` and `containerd-1.6.18` and no `apparmor` package installed it still says, "unable to apply apparmor profile." I'm running Debian 11 and installed docker from https://download.docker.com/linux/debian.

[a]: https://github.com/containerd/containerd/pull/8087
[b]: https://github.com/moby/moby/pull/45043/files#diff-3cf15fd4671254ae18dff1505434826e26a59cdc6e0d945dd4da1e0d63819602L22-R22

**Comment by capriciousduck** [comment]
This is bit confusing. So did containerd accept the change made by docker? Or did contained fix it - by not trying to load AppArmor on a non-Debian based machine?

@x-yuri I think you need to have AppArmor installed if your distribution supports it, security wise it's a bad idea not to have AppArmor installed.

**Comment by neersighted** [comment]
To be clear as to what happened here:

* containerd made a bad change that incorrectly removed the check for apparmor_parser in the **library interface**
* Moby picked this up during a revendor
* Moby attempted to work around it in 23.0.1, but the fix was incomplete
* Moby maintainers determined that the change in contianerd represented a bug/regression and got a revert accepted
* containerd made a release with the fix, which solves the issue for `cri-containerd` and Kubernetes
* Moby re-vendored the containerd **library code**
* This re-vendor will be released in Moby 23.0.2, which solves the issue for Moby/Docker CE/Mirantis Container Runtime

**Comment by x-yuri** [comment]
> containerd made a bad change that incorrectly removed the check for apparmor_parser in the library code as well as cri-containerd

In other words, the error occurs inside the `dockerd`'s binary (`23.0.1`) which has the `HostSupports()` function from `containerd` `v1.6.16`? And `docker version` says `1.6.18` because it reports the `containerd`'s binary version, not the version from which `HostSupports` was taken into the `dockerd`'s binary? And `dockerd` fails because it has `HostSupports()` from `1.6.16`?

> Moby attempted to work around it in 23.0.1, but the fix was incomplete

Oh, I probably see, [this commit][a] seems to have made it into `23.0.1` (not according to GitHub though). At first glance it seems like it should fix the issue though.

[a]: https://github.com/moby/moby/commit/38b70ebc3b

**Comment by ffdybuster** [comment]
23.0.2 is out now, and the problem is gone for me. Thanks a lot to everyone involved in fixing it!

**Comment by pavelvodrazka** [comment]
Version 23.0.2 fixed the problem on my machine as well. I'm again able to run docker containers without having apparmor installed. Thanks a lot!

**Comment by neersighted** [comment]
Thanks everyone! I'm going to go ahead and lock this issue to prevent unnecessary notifications -- the issue is definitively solved, as confirmed by developer testing, formal QA, and end user reports.

For future users: please note that this behavior will **likely change in the future**. While it will likely always be possible to run Moby without AppArmor installed on an AppArmor-enabled kernel (e.g. to support a mixed userland/kernel situation), there is a strong likelihood that we will require an explicit opt-out in the future, as such configurations are the exception and not the rule.
