### ISSUE TITLE
Speed up Docker service by changing service type

### ISSUE THREAD

**Issue by KonradHoeffner** [moby/moby#45150]
### Description

Docker seems to delay the boot process on Arch Linux because of the following entry in docker.service:

```
[Service]
Type=notify
```

According to <https://www.freedesktop.org/software/systemd/man/systemd.service.html>:
> 
> If set to simple (the default if ExecStart= is specified but neither Type= nor BusName= are), the service manager will consider the unit started **immediately** after the main service process has been forked off. [...]
> 
> The exec type is similar to simple, but the service manager will consider the unit started immediately **after the main service binary has been executed**. [...]
> 
> Behavior of notify is similar to exec; however, it is expected that the service sends a "READY=1" notification message [...]
> 

After changing the type to "simple", I do not encounter slowdowns anymore:

```
[Service]
Type=simple
```

I did not encounter any drawbacks of this type, thus I propose to change it in <https://github.com/moby/moby/edit/master/contrib/init/systemd/docker.service> if there isn't another reason for it. I can also make a pull request but I first wanted to ask if there is some reason against that, which I don't know about.

## docker version

```
Client:
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.20
 Git commit:        a5ee5b1dfc
 Built:             Sat Feb 11 13:58:04 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.20
  Git commit:       bc3805a0a0
  Built:            Sat Feb 11 13:58:04 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.19
  GitCommit:        1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f.m
 runc:
  Version:          1.1.4
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

## docker info

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  0.10.3
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  2.16.0
    Path:     /usr/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 72
 Server Version: 23.0.1
 Storage Driver: btrfs
  Btrfs: 
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.2.5-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 31.13GiB
 Name: archlinux
 ID: NGPK:B5EF:6NZF:KEJ6:W3BJ:J75T:6BDG:TAY6:XT7X:KLXS:ONTJ:ZLUI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by bsousaa** [comment]
possibly related with https://github.com/moby/moby/issues/45143

**Comment by KonradHoeffner** [comment]
Thank you for the link, that is also relevant to my slowdown problem.
However I think it is worth continuing both approaches, #45143 seems to be about speeding up the startup of docker directly (which would also be great), however what I propose here is to execute the startup in the background, so that the users doesn't have to wait unless they do something with docker.

**Comment by rulatir** [comment]
I am the reporter of #45143.

I'm no systemd expert, but my intuition is that `notify` is there for a reason: it is to ensure proper synchronization when the service is started via socket rather than enabled on startup. I switched to only enabling docker.socket in order to avoid the bootup slowdown, and the result is that now I wait those 40s+ when I first do anything with docker rather than on bootup; I suspect that changing `notify` to `simple` will cause socket activation to falsely assume that the service is ready, and whatever I am trying to do with docker will initially fail with "daemon not running blah blah" until those 40s+ pass. Also, "upping the compose" in dev environment is quite often the first thing I do in the morning, so even if I enable docker.service with `Type=simple`, I will still be occasionally bitten by #45143 (the "daemon not running" flavor), which is the real underlying issue.

**Comment by thaJeztah** [comment]
I definitely think we should look closely at this before making changes. In the  meantime, you should probably be able to override this with a systemd override or drop-in file.

Related (for sd_notify);

- https://github.com/moby/moby/issues/2322
- https://github.com/moby/moby/pull/3060
- https://github.com/moby/moby/pull/41832

**Comment by neersighted** [comment]
Naively changing to a simple service instead of a `sd_notify` service is not a real solution; it's better to determine what is misbehaving on your system (if anything indeed is). Socket activation is not dependent on proper notification that the API is ready, but dependent units are (see https://github.com/moby/moby/issues/2322).

**Comment by rulatir** [comment]
@neersighted What are the "dependent units" in this case? Are these logs even sufficient to determine _what_ is waiting 40s+ for _what_?

**Comment by cpuguy83** [comment]
Agree with @neersighted here.
Changing away from `notify` does not actually change anything except now systemd assumes the service is ready immediately, which it is not.

It may be possible that we are notifying later than we need to, or there is some problem on the system delaying notification, but `simple` is not "faster" than `notify` strictly speaking.
You may want to disable socket activation, to ensure docker is started with the system instead of with a request.

**Comment by thaJeztah** [comment]
From the discussion, it looks like we can close  this ticket. Feel free to continue the conversation though, in case there's something we overlooked 👍

**Comment by rulatir** [comment]
I don't see any dependent units:
```
$ systemctl list-dependencies docker.service --all --reverse
docker.service
```

**Comment by KonradHoeffner** [comment]
On my system it shows two:

~$ systemctl list-dependencies docker.service --all --reverse docker.service

```
docker.service
● └─multi-user.target
●   └─graphical.target

docker.service
● └─multi-user.target
●   └─graphical.target
```

**Comment by neersighted** [comment]
The output here appears consistent with what is expected -- @rulatir's issue is not related to/affected by systemd or the unit type, while @KonradHoeffner's machine delays boot while it waits for dockerd to start.

The proper way to fix the slow startup is to let systemd know that it should not wait for dockerd (i.e. remove it as a dependency for `multi-user.target`).

**Comment by rulatir** [comment]
No. The proper way to fix the slow startup is to fix the slowness. For all I could ascertain, it is the `/usr/bin/dockerd` process that spends 40s+ apparently doing nothing apart from also blocking any process that tries to communicate with it. Absent extraordinary evidence to the contrary, `/usr/bin/dockerd` is the culprit, and `/usr/bin/dockerd` should be fixed.

**Comment by neersighted** [comment]
You misapprehend me -- I am asserting that the issue you are seeing is not related to the service type, but to a slow startup. That is to say, your issue is a manifestation of #45143 and requires that issue to be fixed.

The slow startup @KonradHoeffner is observing is possibly a function of something similar, but also a function of blocking the startup of the GUI on the Docker API being ready, which is not necessary. The solution is to not block the GUI on dockerd's startup, as that doesn't make much sense, and then to identify if there is anything else slowing startup.

In any case, changing the dockerd unit type does not solve any real issues; it just masks the problem.

**Comment by rulatir** [comment]
Ah, OK, sorry! No disagreement here. Socket activation should be the way to go, and it should be fast. Explicitly enabling docker.service on desktop is itself a workaround to avoid waiting 40s e.g. for output from `docker ps` the first time it's used.
