### ISSUE TITLE
cannot find module providing package github.com/docker/docker/pkg/term

### ISSUE THREAD

**Issue by alexellis** [moby/moby#45707]
### Description

When I upgrade [github.com/openfaas/faas-cli](https://github.com/openfaas/faas-cli) to point at the latest Docker version required by another package, the `github.com/docker/docker/pkg/term` package can no longer be found.

Do you have any suggestions on what could be going wrong here?

Previous version: `github.com/docker/docker v20.10.20+incompatible`

I've also tried changing docker/docker to moby/moby, but then get the same error.

### Reproduce

Check out https://github.com/openfaas/faas-cli/blob/master/go.mod

Run the update for github.com/google/go-containerregistry or arkade and then you'll see the Docker dependency change to: `github.com/docker/docker v23.0.5+incompatible` and the build will fail with:

```
go get
github.com/openfaas/faas-cli imports
        github.com/openfaas/faas-cli/commands imports
        github.com/docker/docker/pkg/term: cannot find module providing package github.com/docker/docker/pkg/term
```

### docker version

```bash
n/A
```

### docker info

```bash
n/A
```

**Comment by alexellis** [comment]
@thaJeztah @AkihiroSuda we seem to hit this error quite often when updating Docker for the OpenFaaS CLI, and don't upgrade because of it. It'd be nice to be able to upgrade the various other components due to CVEs that were reported in earlier versions of Docker.

Do you know where the package has moved to?

**Comment by AkihiroSuda** [comment]
> Do you know where the package has moved to?

https://github.com/moby/term

**Comment by thaJeztah** [comment]
Yes that package was moved to a separate module (as an ongoing effort to ultimately move this repository to Go modules). Generally, we provide aliases for the old location, and mark those as deprecated for at least 1 release-cycle, so that linters and IDEs should pick up the deprecation (which the deprecation message including where the new location can be found).

- For this one, that was done in https://github.com/moby/moby/pull/40825


Wondering though; that was already part of Docker 20.10; did none of your linters pick up the deprecation? (Asking, because if there's something that prevents linters from picking that up, I wonder if we need to make changes to that procedure somewhere).
