### ISSUE TITLE
Pushing blobs doesn't send content-type

### ISSUE THREAD

**Issue by makkes** [moby/moby#46006]
### Description

Trying to push an image to a conformant registry yields an error:

```
$ docker push localhost:8080/alpine/alpine:latest
The push refers to repository [localhost:8080/alpine/alpine]
78a822fe2a2d: Pushing [==================================================>]  7.327MB/7.327MB
error parsing HTTP 400 response body: invalid character 'c' looking for beginning of value: "content-type must be 'application/octet-stream' but is \"\""
```

The distribution spec [mandates blob pushes](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#pushing-blobs) to send a `content-type: application/octet-stream` header when pushing blobs.

### Reproduce

1. `docker run -it --rm -p 8080:8080 ghcr.io/makkes/garage@sha256:07db64a5f721c4a99ba108e3fd62dd21a68ad1e0630eee7f5a8a3a58ef8f9e61` (this is an OCI-conformant registry)
2. `docker pull alpine@sha256:25fad2a32ad1f6f510e528448ae1ec69a28ef81916a004d3629874104f8a7f70`
3. `docker tag alpine@sha256:25fad2a32ad1f6f510e528448ae1ec69a28ef81916a004d3629874104f8a7f70 localhost:8080/alpine/alpine:latest`
4. `docker push localhost:8080/alpine/alpine:latest`

### Expected behavior

`docker push` should successfully push the image.

### docker version

```bash
Client:
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfcd85
 Built:             Mon May 29 15:50:06 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f9ee
  Built:            Mon May 29 15:50:06 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.2
  GitCommit:        0cae528dd6cb557f7201036e9f43420650207b58.m
 runc:
  Version:          1.1.7
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  0.11.0
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  2.20.0
    Path:     /usr/lib/docker/cli-plugins/docker-compose
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.1
    Path:     /home/max/.docker/cli-plugins/docker-sbom

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 28
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 0cae528dd6cb557f7201036e9f43420650207b58.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.3.9-arch1-1
[... redacted ...]
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by rumpl** [comment]
What is the registry you are using? It doesn't seem conformant to the spec wrt to returning error messages https://github.com/opencontainers/distribution-spec/blob/main/spec.md#error-codes

**Comment by makkes** [comment]
> What is the registry you are using? It doesn't seem conformant to the spec wrt to returning error messages https://github.com/opencontainers/distribution-spec/blob/main/spec.md#error-codes

It is conformant:

> A 4XX response code from the registry MAY return a body in any format.

**Comment by corhere** [comment]
I've opened https://github.com/distribution/distribution/issues/3962 for our mishandling of (spec compliant) non-JSON error responses from registries.

I'm pretty sure that we do send the content-type header when pushing blobs.
https://github.com/moby/moby/blob/454b6a7cf5187d1153159e5fe07f4b25c7a95e7f/vendor/github.com/docker/distribution/registry/client/blob_writer.go#L72-L83

And even if we don't, we'd still arguably be compliant with the distribution spec as the spec does not mandate that the `PATCH` requests MUST include the header. [RFC 9110: HTTP Semantics](https://www.rfc-editor.org/rfc/rfc9110.html#section-8.3-5) only says that the header SHOULD be sent, so we are HTTP-compliant either way. It also says that the recipient MAY assume `application/octet-stream` if not present. You may want to consider [removing the strict content-type check from your registry implementation](https://github.com/makkes/garage/blob/abdcd3a79957e507b1a01730518807d2a3925651/pkg/registry/blob_session.go#L60C40-L65) to be more compatible with the ecosystem. Keep in mind that Moby is the original registry client, predating the OCI, let alone distribution-spec. If your implementation is incompatible with it, the issue is probably with your implementation or the distribution-spec. The distribution-spec conformance suite is not exhaustive and does not test all edge cases.

**Comment by makkes** [comment]
Thanks for your feedback @corhere, much appreciated and thanks for opening the issue over in d/d.

As for the Content-type, I might have misinterpreted [this part of the spec](https://github.com/opencontainers/distribution-spec/blob/f641ac67a4208e2078ee0ab3736f3e9f8fff5f06/spec.md?plain=1#L331-L337) as a strict requirement:

> To upload a chunk, issue a `PATCH` request to a URL path in the following format, and with the following headers and body:
>
>URL path: `<location>` <sup>[end-5](#endpoints)</sup>
>```
>Content-Type: application/octet-stream
>Content-Range: <range>
>Content-Length: <length>

I'll remove the constraint so that the assumption is the content-type is `application/octet-stream` in case the header is absent.

**Comment by corhere** [comment]
> I think where the CLI doesn't send the "Content-Type" header is here:

Good catch! That's a really insidious bug, behaving slightly differently depending on whether it's used as an `io.Writer` or an `io.ReaderFrom`.
