### ISSUE TITLE
rebuild image when base FROM image is updated

### ISSUE THREAD

**Issue by brianjmurrell** [moby/moby#46280]
### Description

If I have a `Dockerfile` to describe an image based on (I.e. `FROM`) say `centos:latest`, when I rebuild (`docker build`) that image again with no other changes to the Dockerfile the image is built out of the existing cache layers resulting in an image identical to the previous one.  Good so far. 
 Where this seems to be a problem is that it appears to be the case even when `centos:latest` has been updated since the last time I build the image.

It seems to me that `FROM` would be more useful if it would notice when the source of what it's specifying has been updated and the image is rebuilt from that updated source.

Thoughts?

**Comment by thaJeztah** [comment]
This is by design, as it allows you to build from local images, which can be either because the `FROM` image is an image that's built locally, so not (yet) available in any registry, for offline situations (base-image loaded into a daemon), or for situations where the base image should not be updated, unless explicitly asked for.

If you want the Docker Engine to check if a newer version of the image is available before building, you can use the `--pull` option when running `docker build`;


To illustrate; I'm pulling the `ubuntu:20.04`, and tag it as `ubuntu:latest` (to illustrate "I have an older version of `ubuntu:latest` on my machine);

```bash
docker pull ubuntu:20.04
20.04: Pulling from library/ubuntu
edaedc954fb5: Pull complete
Digest: sha256:33a5cc25d22c45900796a1aca487ad7a7cb09f09ea00b779e3b2026b4fc2faba
Status: Downloaded newer image for ubuntu:20.04
docker.io/library/ubuntu:20.04

docker tag ubuntu:20.04 ubuntu:latest
```

Running a `docker build` using `FROM ubuntu:latest` will use the locally cached image as default;

```bash
echo -e 'FROM ubuntu:latest\nRUN cat /etc/lsb-release' | docker build --no-cache --progress=plain -

# ....
#5 [2/2] RUN cat /etc/lsb-release
#5 0.536 DISTRIB_ID=Ubuntu
#5 0.536 DISTRIB_RELEASE=20.04
#5 0.536 DISTRIB_CODENAME=focal
#5 0.536 DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
#5 DONE 0.7s
```

When running the build with the `--pull` option set, it will check if the image is up-to-date ("load metadata for docker.io/library/ubuntu:latest"), and check what the current version is. If needed, it will pull the updated image;

```bash
echo -e 'FROM ubuntu:latest\nRUN cat /etc/lsb-release' | docker build --pull --no-cache --progress=plain -

#3 [internal] load metadata for docker.io/library/ubuntu:latest
#3 DONE 1.3s

#4 [1/2] FROM docker.io/library/ubuntu:latest@sha256:ec050c32e4a6085b423d36ecd025c0d3ff00c38ab93a3d71a460ff1c44fa6d77
#4 resolve docker.io/library/ubuntu:latest@sha256:ec050c32e4a6085b423d36ecd025c0d3ff00c38ab93a3d71a460ff1c44fa6d77 0.0s done
#4 sha256:ec050c32e4a6085b423d36ecd025c0d3ff00c38ab93a3d71a460ff1c44fa6d77 1.13kB / 1.13kB done
#4 sha256:56887c5194fddd8db7e36ced1c16b3569d89f74c801dc8a5adbf48236fb34564 424B / 424B done
#4 sha256:01f29b872827fa6f9aed0ea0b2ede53aea4ad9d66c7920e81a8db6d1fd9ab7f9 2.30kB / 2.30kB done
#4 sha256:b237fe92c4173e4dfb3ba82e76e5fed4b16186a6161e07af15814cb40eb9069d 0B / 29.54MB 0.1s
#4 sha256:b237fe92c4173e4dfb3ba82e76e5fed4b16186a6161e07af15814cb40eb9069d 6.29MB / 29.54MB 0.2s
#4 sha256:b237fe92c4173e4dfb3ba82e76e5fed4b16186a6161e07af15814cb40eb9069d 22.02MB / 29.54MB 0.3s
#4 sha256:b237fe92c4173e4dfb3ba82e76e5fed4b16186a6161e07af15814cb40eb9069d 29.54MB / 29.54MB 0.4s
#4 sha256:b237fe92c4173e4dfb3ba82e76e5fed4b16186a6161e07af15814cb40eb9069d 29.54MB / 29.54MB 0.4s done
#4 extracting sha256:b237fe92c4173e4dfb3ba82e76e5fed4b16186a6161e07af15814cb40eb9069d
#4 extracting sha256:b237fe92c4173e4dfb3ba82e76e5fed4b16186a6161e07af15814cb40eb9069d 2.4s done
#4 DONE 3.0s
```

And then build:

```
``#5 [2/2] RUN cat /etc/lsb-release
#5 0.641 DISTRIB_ID=Ubuntu
#5 0.641 DISTRIB_RELEASE=22.04
#5 0.641 DISTRIB_CODENAME=jammy
#5 0.641 DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
#5 DONE 0.8s
```

:warning: note that when using BuildKit as builder (which is now the default), the pulled image will not be _tagged_, i.e., it will pull the image, but your local `ubuntu:latest` image will still be pointing to the old version;

```
docker run --rm ubuntu:latest cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
```

**Comment by brianjmurrell** [comment]
That all seems fair enough.
