### ISSUE TITLE
Prune should always list items to be deleted before asking to confirm.

### ISSUE THREAD

**Issue by minecraftchest1** [moby/moby#46678]
### Description

When running a prune command, no matter what for, a list of items that will be deleted should be listed before asking the user to confirm the action.

### Reproduce

Run `docker volume prune` or similar

### Expected behavior

```
WARNING! This will remove all local volumes not used by at least one container.

Volumes to be Deleted:
f6d6dc53efb25c1a9e8950d65d954ad4ade54deefc95a261ff3daef7cde59232
matrix_synapse-data

Are you sure you want to continue? [y/N] y
Deleted Volumes:
f6d6dc53efb25c1a9e8950d65d954ad4ade54deefc95a261ff3daef7cde59232
matrix_synapse-data

Total reclaimed space: 1kB
```

### docker version

```bash
Client:
 Version:           20.10.5+dfsg1
 API version:       1.41
 Go version:        go1.15.15
 Git commit:        55c4c88
 Built:             Mon May 30 18:34:49 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.5+dfsg1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.15.15
  Git commit:       363e9a8
  Built:            Mon May 30 18:34:49 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.13~ds1
  GitCommit:        1.4.13~ds1-1~deb11u4
 runc:
  Version:          1.0.0~rc93+ds1
  GitCommit:        1.0.0~rc93+ds1-5+deb11u2
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 16
  Running: 16
  Paused: 0
  Stopped: 0
 Images: 41
 Server Version: 20.10.5+dfsg1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1.4.13~ds1-1~deb11u4
 runc version: 1.0.0~rc93+ds1-5+deb11u2
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-25-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.925GiB
 Name: ARS1
 ID: 26IO:IA5N:FTYX:NTHG:U5YR:BOZR:JUHG:5GQN:CMLO:MPOE:V36N:KZGE
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: Support for cgroup v2 is experimental
```

### Additional Info

This has burned me a few times. I shouldn't have to make sure each and every container is running before deleting an unrelated type. EXPESICALLY WHEN BACKUPS ARE IMPOSSIBDLE TO MAKE!

**Comment by mushrowan** [comment]
i'm a bit confused as to why this was closed. what's described is definitely not a duplicate of dry-run, as dry-run *does* present an issue of a race condition between when dry run is used, and the wet run.

The obvious solution that seems to be presented by OP is that you initialise the list of things to be deleted when the prune command is used, and then present it to the user. when the user confirms, you don't re-initialise the list (as obviously this introduces the race condition), you just attempt to remove all that was listed in what you already presented to the user.

You could argue that there's a race condition here in that things could become eligible for pruning *after* the list has been initialised (or could already have been removed), and therefore would be missed when the user confirms. But this race condition feels *far* less catastrophic than removing things that shouldn't be removed. 

At the very least, there should be a documented, easy way to list volumes/images/etc that are unused (and would be removed by a prune), even if it's not a prune --dry-run command. Obviously there's `docker volume ls --filter dangling=true`, but it would be nice if there were a system-level version of this (maybe there is and I'm just not aware of it, in which case it should be [more] visibly documented).

Am I missing something here? It seems like a pretty obvious solution, which is why I'm assuming that there's some fatal flaw I've overlooked. Else, I'm happy to work on it if nobody else has the time for it, as it'd be extremely useful for me.
