### ISSUE TITLE
External DNS forwarding is broken on Windows container NAT networks

### ISSUE THREAD

**Issue by MikeZappa87** [moby/moby#46792]
### Description

A 'feature' was implemented back in 2016 that sets the default gateway as the primary DNS server for Windows containers. This is currently a bool 'DisableGatewayDNS' and the issue is that no DNS servers are at the address thus resulting in the primary failing and then making use of the secondary DNS server. This being the default behavior causes issues if the user does not have a DNS server listening on the node itself. 

Link to DisableGatewayDNS property: https://github.com/moby/moby/blob/7e66d9900c81e872e5ecc89aa0bb03e52901447f/libnetwork/drivers/windows/windows.go#L49C2-L49C19

Original Commit:
https://github.com/moby/moby/commit/5a5b7fee330867bc313a7b33a2e9611ffeea6328

We have several options here and I am willing to do the work to resolve this. 

1. Remove the feature entirely
2. Change the name of property to EnableGatewayDNS
3. If the option is not set, default to true
4. Fix issue with DNS

For option 3:
https://github.com/moby/moby/blob/5a5b7fee330867bc313a7b33a2e9611ffeea6328/libnetwork/drivers/windows/windows_store.go#L154

The user still has the ability to set custom DNS servers via the "com.docker.network.windowsshim.dnsservers" option as a comma separated string on network creation or by using the --dns flag on docker run. Note that when using these options, the default gateway is still used as the primary however the fail behavior goes to the additional DNS servers. 

Issues: 
https://forums.docker.com/t/dns-broken-on-docker-desktop-for-windows/130121
https://github.com/microsoft/Windows-Containers/issues/216

More issues exist. It does seem that most people are setting "com.docker.network.windowsshim.disable_gatewaydns=true" as the default behavior of false is not applicable to 99% of users. 

In this comment, I propose a work around: 
https://github.com/microsoft/Windows-Containers/issues/216#issuecomment-1775709793

**Comment by MikeZappa87** [comment]
Hello @corhere @akerouanton I was told by @neersighted to ping you. If you have any thoughts on which direction you want me to head I am open to it!

**Comment by corhere** [comment]
[There is supposed to be a DNS resolver listening on the default gateway.](https://github.com/moby/libnetwork/pull/1412) That resolver is a requirement for [automatic service discovery.](https://docs.docker.com/network/network-tutorial-standalone/#:~:text=On%20user%2Ddefined,service%20discovery.) Disabling gateway DNS by default will break that functionality, which when it works as intended, _is_ applicable to the majority of users. It would be analogous to disabling kube-dns by default on Windows k8s clusters.

If the DNS resolver on the default gateway is not resolving queries, that is a bug which needs to be addressed. And given the totality of evidence, with users on v20.10 daemon versions complaining about issues starting after a Windows Update, it seems to me that a bug in the [Host Networking Service](https://learn.microsoft.com/en-us/virtualization/windowscontainers/container-networking/architecture) is the most likely root cause.

What you have proposed is a backwards-incompatible change. If we were to do that as a workaround, either everyone would have to deal with automatic service discovery being disabled by default on Windows forever or we'd have to introduce a second backwards-incompatible change to revert back to the original defaults once gateway DNS is fixed.

As of v24.0.0, default network options can be set in daemon.json.

- #43197

Impacted users can therefore work around the issue by configuring their daemon like so:
```go
{
    "default-network-opts": {
        "nat": { "com.docker.network.windowsshim.disable_gatewaydns": "true" }
    }
}
```

**Comment by MikeZappa87** [comment]
I have asked internally about this however this being 7 years ago I doubt anyone remembers. I have disabled it and have experienced no issues. My guess that this is no longer needed however I will sync with the dev lead on the HNS team. It seems that most people are disabling this. If the requirement has changed I will move forward with removing this.

**Comment by thaJeztah** [comment]
Thanks! Yes, some of these areas are deep, dark corners, so any guidance from the team is appreciated (also if there's documented changes around this that may be Windows version related)

**Comment by corhere** [comment]
> I have disabled it and have experienced no issues. My guess that this is no longer needed

I doubt it. The DNS resolver I mentioned earlier [is part of dockerd.exe](https://github.com/moby/moby/blob/63b2a2138dacd5d141fabc5bc132e403f577ed38/libnetwork/network_windows.go). Unless DNS queries are routed to it, containers attached to the network will be unable to resolve each other by name. For example, if you have two containers named `mycontainer1` and `mycontainer2` connected to the same nat network, you should be able to successfully run `ping mycontainer2` from mycontainer1.

**Comment by MikeZappa87** [comment]
Hmm. So with the value set to true we can ping outside domains such as Microsoft 
.com hovever cannot use the container names to resolve. With the value set to false we can resolve container names however cannot resolve anything outside. This could be using nslookup or just pinging Microsoft.com. Something is definitely wrong here though. I'm going to create a chart of working and non working scenarios. I would expect if the value is false that all scenarios to work here.

**Comment by corhere** [comment]
> With the value set to false we can resolve container names however cannot resolve anything outside.

That's actually good news: DNS queries are being received and replied to by Moby's (libnetwork's) DNS resolver. It's just not successfully forwarding queries to upstream DNS servers that it can't resolve on its own. As far as I can tell, that never would have worked on Windows as the resolver is instantiated with that functionality disabled (`proxyDNS=false`).
https://github.com/moby/moby/blob/63b2a2138dacd5d141fabc5bc132e403f577ed38/libnetwork/network_windows.go#L51C23-L51C23

I can think of a few possible explanations for public DNS resolution could have not been broken for containers attached to NAT networks in the past:
- HNS used to have some magic sitting in front of Moby's DNS resolver to resolve queries itself when Moby's replied NXDOMAIN?
- HNS used to configure DNS inside the container compartment to only query the gateway DNS resolver for "local" names (no dots) and query other servers for everything else?
- Windows' DNS resolver behaviour used to be such that it would try secondary servers after the first replied NXDOMAIN?
- Moby's DNS resolver used to handle queries it could not resolve locally in such a way that would make Windows' DNS resolver try querying secondary DNS servers, but now behaves differently?
- DNS forwarding for NAT networks never worked on Windows (Mandela Effect)?

Regardless, I still think that the best path forward for all users is to fix DNS forwarding on Windows so that both container names and public DNS can be resolved by default. I see [a Win32 API function `DnsQueryRaw`](https://learn.microsoft.com/en-us/windows/win32/api/windns/nf-windns-dnsqueryraw) which would do exactly what we need, but it doesn't look to be in any released Windows versions yet. We already have a DNS forwarder implemented in userspace that we use on Linux; all we'd have to do to also use it on Windows is set `proxyDNS=true` and [configure the list of external DNS servers to forward to](https://github.com/moby/moby/blob/cff4f20c44a3a7c882ed73934dec6a77246c6323/libnetwork/resolver.go#L185-L187). Thankfully [that looks easy enough to query from the system](https://learn.microsoft.com/en-us/windows/win32/api/windns/nf-windns-dnsqueryconfig), at least for IPv4 servers. Do you know of a way to query the list of configured IPv6 DNS servers on the system?

**Comment by MikeZappa87** [comment]
I am now able to see the issue with the internal DNS resolution is broken now. Thanks for pointing that out! Since the list of DNS Servers is accurate, are you saying the work involved is setting the proxyDNS bool to true?

**Comment by corhere** [comment]
> Since the list of DNS Servers is accurate, are you saying the work involved is setting the proxyDNS bool to true? 

Not quite.  Merely setting proxyDNS to true is not going to be sufficient as the list of external DNS servers is _empty_. The `SetExtServers` method also needs to be called for DNS forwarding to be functional.

**Comment by TBBle** [comment]
History clarification: The `DisableGatewayDNS` network-creation flag was added in 2017 (via https://github.com/moby/libnetwork/pull/2021) to support _disabling_ the gateway being the default DNS, [relying on a new HNS API in Windows Server 1709](https://github.com/moby/libnetwork/pull/2021#issuecomment-350166832). As noted at https://github.com/docker/for-win/issues/397#issuecomment-273646131, the flow of "SRV_FAIL from dockerd-internal-DNS, then fallback to secondary DNS" was [the original design state](https://github.com/moby/libnetwork/pull/1412) for NAT networks.

As noted in that PR, there was already an option (`DisableDNS` added as part of [overlay network default gateway support](https://github.com/moby/libnetwork/pull/1541)) which could be set when creating an individual endpoint for the same effect. One of `DisableGatewayDNS`'s effects was to set `DisableDNS` on all subsequent endpoints created on that network. This leads to the actual HNS option, [`EnableInternalDNS` which was originally set `true` for NAT networks](https://github.com/moby/libnetwork/pull/1412/files#diff-1517f737a45c2b49399bc0206cedef10bc4ce3d9b165d8f16ba6fa9deaef707fR484-R486), and `false` for others, and then when `DisableDNS` was introduced, [setting it forced `EnableInternalDNS` to false on `nat` networks](https://github.com/moby/libnetwork/pull/1541/files#diff-1517f737a45c2b49399bc0206cedef10bc4ce3d9b165d8f16ba6fa9deaef707fL485-R520). So I'm _guessing_ that overlay networks required the network creator to provide a DNS server for that network, e.g. kube-and hence ignored 

Per https://github.com/docker/for-win/issues/397#issuecomment-311475521, it seems both [`nslookup`](https://github.com/microsoft/Windows-Containers/issues/216#issuecomment-1086211615) and [the .NET resolver (of some vintage)](https://github.com/docker/for-win/issues/397#issuecomment-310760523) did not fall-over to the secondary DNS server when the primary sent back SRV_FAIL. Although when .NET's `System.Net.Dns.GetHostAddresses` was [called through PowerShell](https://github.com/moby/moby/issues/30260#issuecomment-277027799), it worked, so maybe there was a specific third-party .NET resolver that had this issue, there's not enough detail in the failure report to know for sure. Ironically, the proxy DNS client in moby/libnetwork didn't fail-over on SRV_FAIL from an upstream DNS server at the time, but [does now](https://github.com/moby/libnetwork/pull/2121).

However, if `ping` (or [`Resolve-DNS`](https://github.com/microsoft/Windows-Containers/issues/216#issuecomment-1419601968)) is showing the same results as `nslookup`, then the problem is probably not the DNS resolver as it was back when the flag was added, but something else has gone wrong.

I do wonder, I don't see in any of the current bugs an `ipconfig /all` for the problematic case... Is the _secondary_ DNS address being set? Perhaps _that_ is what broke, and why dockerd DNS server results work, but the fail-over doesn't?

----

All that said, making the dockerd DNS service able to proxy on Windows and _only_ using that from inside a container by default seems like a reasonable, and better-isolated result to me.

I'm not sure why that wasn't done in the first place, but some questions leap out to me:
* Can we stop HCN from setting up the secondary DNS server address, and _only_ use the dockerd proxy?
* _Which_ DNS server or servers do we proxy to?
  * DNS Server config in Windows is per-adapter, do we need to replicate [this process](https://serverfault.com/a/84293/148812) ([Modulo changes in Windows 10](https://serverfault.com/a/805455/148812)) so people see the expected DNS resolution results from the proxy when using VPN or otherwise multihoming?
    * I haven't looked, can the Docker DNS proxy dynamically update as adapters are connected/removed?
  * Does ICS (or whatever supports NAT on Windows these days) by any chance provide a DNS server that already takes care of that, and we can just proxy to it?

**Comment by corhere** [comment]
The Docker DNS proxy could be easily extended to support dynamic updates to the server list by making `SetExtServers` safe to call concurrently.

**Comment by MikeZappa87** [comment]
> > Since the list of DNS Servers is accurate, are you saying the work involved is setting the proxyDNS bool to true?
> 
> Not quite. Merely setting proxyDNS to true is not going to be sufficient as the list of external DNS servers is _empty_. The `SetExtServers` method also needs to be called for DNS forwarding to be functional.

We do have a list of DNS servers though. Should the SetExtServers that the current list of DNS Servers passed into it (Excluding the default gateway).

**Comment by corhere** [comment]
> > > Since the list of DNS Servers is accurate, are you saying the work involved is setting the proxyDNS bool to true?
> > 
> > Not quite. Merely setting proxyDNS to true is not going to be sufficient as the list of external DNS servers is _empty_. The `SetExtServers` method also needs to be called for DNS forwarding to be functional.
> 
> We do have a list of DNS servers though. Should the SetExtServers that the current list of DNS Servers passed into it (Excluding the default gateway). 

Which list, the user-supplied one? That's the easy answer for which servers `libnetwork.Resolver` should forward to. But what about when the user does not go out of their way to configure any DNS servers on the container network? DNS forwarding Just Works on Linux containers attached to a bridge network with no configuration. It should work on Windows containers attached to a nat network (the closest analogue), too.

**Comment by akerouanton** [comment]
@florianehmke As you discovered, these options don't apply to the default networks. You need to create a custom network.

**Comment by doctorpangloss** [comment]
this should be reopened, since the bug is back on 10.0.20348.3932 hosts

**Comment by robmry** [comment]
> this should be reopened, since the bug is back on 10.0.20348.3932 hosts

Hi! Please could you raise a new issue describing what you've tried, what went wrong or what error message you got, Docker version numbers, and so on.

(Is 10.0.20348.3932 the version of your Windows Server container? Did an older version behave better? With the same version of Docker and Windows host?)
