### ISSUE TITLE
Cannot change ipv6-cidr in daemon.json anymore - dockerd fails to start

### ISSUE THREAD

**Issue by h1ght** [moby/moby#46829]
### Description

hello,

i try to reconfigure my docker default bridge, but after i used
```
{
  "ipv6": true,
  "fixed-cidr-v6": "fe80::/64",
  "ip6tables": true,
  "experimental": true
}
```
in daemon.json, its created ipv6 addres on docker0, but when i want to change the cidr in daemon.json, i cannot restart via systemctl restart docker. it fails with
```
Nov 17 17:36:05 gbc dockerd[8448]: time="2023-11-17T17:36:05.968731732+01:00" level=info msg="Loading containers: start."
Nov 17 17:36:06 gbc dockerd[8448]: time="2023-11-17T17:36:06.381431577+01:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Nov 17 17:36:06 gbc dockerd[8448]: time="2023-11-17T17:36:06.382374332+01:00" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
Nov 17 17:36:06 gbc dockerd[8448]: failed to start daemon: Error initializing network controller: error creating default "bridge" network: failed to add IPv6 address fe80::1/80 to bridge: file exists
Nov 17 17:36:06 gbc systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
```
i tried to forcefully remove via "sudo rm /var/lib/docker/network/files/local-kv.db", the folder is empty, but dockerd --debug still spits out the same error that the file exists.
after reediting the daemon.json to the old /64 cidr, restarting works again.

regards

### Reproduce

1. edit daemon.json to 
```
{
  "ipv6": true,
  "fixed-cidr-v6": "fe80::/64",
  "ip6tables": true,
  "experimental": true
}
```
2. restart docker
3. reedit daemon.json, change cidr like /80
4. try to restart via systemctl restart docker

### docker version

```bash
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:02 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:02 2023
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 11
  Running: 11
  Paused: 0
  Stopped: 0
 Images: 24
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-13-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.08GiB
 Name: gbc
 ID: a13438fe-d85c-4149-886b-05d2850e11e4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

on my older local machine with debian 12 repo docker, i can change the cidr as-i-wish and restart wihtout a problme.

```
Client:
 Version:           20.10.24+dfsg1
 API version:       1.41
 Go version:        go1.19.8
 Git commit:        297e128
 Built:             Thu May 18 08:38:34 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.24+dfsg1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       5d6db84
  Built:            Thu May 18 08:38:34 2023
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.20~ds1
  GitCommit:        1.6.20~ds1-1+b1
 runc:
  Version:          1.1.5+ds1
  GitCommit:        1.1.5+ds1-1+b1
 docker-init:
  Version:          0.19.0
  GitCommit:
```
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.11.2)
  compose: Docker Compose (Docker Inc., v2.21.0)

Server:
 Containers: 20
  Running: 18
  Paused: 0
  Stopped: 2
 Images: 44
 Server Version: 20.10.24+dfsg1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1.6.20~ds1-1+b1
 runc version: 1.1.5+ds1-1+b1
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 6.1.0-13-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 14.47GiB
 Name: debian-svr
 ID: NYSZ:IIV3:YFGV:N4P6:HDDA:ZUES:WA7W:UVKX:TAVP:3INY:X7QQ:7UFQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by robmry** [comment]
The link-local addresses used in the example are a special case. But, the same applies to any address, for example - start the daemon with `fixed-cidr-v6` of `fec0::/64`, change the config to `fec0::/80` and the daemon fails to start.

The problem is the daemon adds required addresses before looking for unwanted addresses to remove. I'll create an initial PR to deal with that.

For link-local addresses - I'm not yet sure what's happening. The existing code always assigns the default `fe80::1/64`, regardless of the configured address. The PR I'll create in a minute allows that subnet to be overridden, but it doesn't make things work properly for a network that only has link-local addresses - which I think would be the intention.

With only link-local addresses, the problem may be link-local addresses being treated as a normal address pool, and management of that pool not working properly. In any case, here's the behaviour I see so far ...

As reported, when `fixed-cidr-v6` is an overlapping link-local address, the daemon doesn't start. When `fixed-cidr-v6` is the default link local address, `fe80::1/64`, the daemon does start (what actually happens is the default address is assigned, so when the daemon comes to assign the configured address it sees it's already there and does nothing).

It's possible to run a container on that network, the container ends up with two link local addresses. The same happens for subsequent containers added to that bridge - until a container is deleted. After that, it's not possible to add any new containers. For example:

```
# dockerd [...] --fixed-cidr-v6=fe80::/64

# docker run -ti alpine sh
/ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
3: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN qlen 1000
    link/tunnel6 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00 brd 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
126: eth0@if127: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether 02:42:ac:12:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.2/16 brd 172.18.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe12:2/64 scope link
       valid_lft forever preferred_lft forever
    inet6 fe80::42:242:ac12:2/64 scope link flags 02
       valid_lft forever preferred_lft forever
/ # exit

# docker run -ti alpine sh
docker: Error response from daemon: Address already in use.
ERRO[0000] error waiting for container:
#
```

It is possible to start the daemon with a non-overlapping link-local subnet, for example `--fixed-cidr-v6=fe80:1234::/42`. But, this also results in two link local networks because the default `fe80::/64` is still assigned first, which probably isn't what was expected:

```
155: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:dc:22:60:2d brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 brd 172.18.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80:1234::1/42 scope link tentative
       valid_lft forever preferred_lft forever
    inet6 fe80::1/64 scope link tentative
       valid_lft forever preferred_lft forever
```

For `docker network create`d bridge networks, things are a little different.

When the daemon has a non-link-local `fixed-cidr-v6`, `docker network create --subnet=fe80::/64` works.

Similar to the `docker0` case, the container gets two link local addresses. In this case, rather than containers failing to start after one has exited, the pool-assigned addresses leak - each new container gets a new link local address (probably not a problem in itself, because the pool is huge, but something's wrong)...

```
# docker run -ti --network testnet alpine sh
/ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
3: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN qlen 1000
    link/tunnel6 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00 brd 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
132: eth0@if133: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether 02:42:ac:13:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.19.0.2/16 brd 172.19.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe13:2/64 scope link
       valid_lft forever preferred_lft forever
    inet6 fe80::2/64 scope link flags 02
       valid_lft forever preferred_lft forever
/ # exit

# docker run -ti --network testnet alpine sh
/ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
3: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN qlen 1000
    link/tunnel6 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00 brd 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
134: eth0@if135: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether 02:42:ac:13:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.19.0.2/16 brd 172.19.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe13:2/64 scope link
       valid_lft forever preferred_lft forever
    inet6 fe80::3/64 scope link flags 02
       valid_lft forever preferred_lft forever
/ #
```

It's not possible to change the size of the link local subnet with `docker network create --subnet`, but it is possible to add a second (non-overlapping) link local network:

```
# docker network create --ipv6 --subnet=fe80::/42 testnet
Error response from daemon: failed to add IPv6 address fe80::1/42 to bridge: file exists

# docker network create --ipv6 --subnet=fe80:1234::/50 testnet
a53c53289f89709f48a73ac74dd3e438540edaf329e1cbfc7165470ae84c0a71
```

**Comment by h1ght** [comment]
maybe i didnt pointed that out, somehow i broke my docker installation, even if i put a valid ula cidr in there like fd00::/64 it breaks in that point, maybe i should'nt put a link local range in the first place there. since then its broken and cant put any new cidr in there. i went over to just create new bridges with ula ranges for ipv6 to enable ipv6 in a container. 
btw. is it possible to set a flag when creating a bridge for ip6tables to allow e.g. icmp6? it opens the ports according to the compose-file/cli but blocks icmp by default, was a bit tricky to find it out. i was playing with my router and prefix delegation. this works so far.
```
For link-local addresses - I'm not yet sure what's happening. The existing code always assigns the default fe80::1/64, regardless of the configured address.
```
when creating a ipv6 bridge, gateway always assigns to ::1 and all other containerns joining get ipv6 counted upwards e.g. ::2 ::3 ff. didnt found it how to enable randomized ipv6 token (ula or assigned pd)

**Comment by robmry** [comment]
> maybe i didnt pointed that out, somehow i broke my docker installation, even if i put a valid ula cidr in there like fd00::/64 it breaks in that point, maybe i should'nt put a link local range in the first place there. since then its broken and cant put any new cidr in there.

Thank you for the update. What error message are you getting now?

> i went over to just create new bridges with ula ranges for ipv6 to enable ipv6 in a container.

> when creating a ipv6 bridge, gateway always assigns to ::1 and all other containerns joining get ipv6 counted upwards e.g. ::2 ::3 ff. didnt found it how to enable randomized ipv6 token (ula or assigned pd)

Those addresses are assigned for a bridge network created via `docker network create` or the docker-compose equivalent, rather than the default bridge. If you're not using the default bridge, you don't need the `fixed-cidr-v6` or `ipv6` options in your `daemon.json` file ... if they're still there, could you try removing them to see if dockerd will start? (If `fixed-cidr-v6` overlaps with any other networks you've created, the daemon won't start.) Also, with dockerd stopped, deleting the default bridge won't hurt and might clean things up, `ip link del docker0`.

> btw. is it possible to set a flag when creating a bridge for ip6tables to allow e.g. icmp6? it opens the ports according to the compose-file/cli but blocks icmp by default, was a bit tricky to find it out. i was playing with my router and prefix delegation. this works so far.

I think it should be ok - perhaps we could get the networking sorted out and dockerd running, then come back to that as a separate question? (But, depending on the OS in the container you're running, to make pings work you may need to add `--cap-add=NET_ADMIN` to your `docker run` command, or the equivalent in your compose config?)

**Comment by robmry** [comment]
For link-local addresses ...

The only problem seems to be that they're aren't released back into the pool, because of an explicit check in the endpoint code. I'll update the PR to deal with that.

The difference in behaviour I saw between docker0 and other networks was simply because, for the default network, container addresses are assigned based on the container's MAC address (to preserve some legacy behaviour). That IP address isn't returned to the pool when the container's deleted so, once a MAC address is recycled, the container won't start - because the same calculated IP address is needed.

For other non-default networks, pool addresses leak, so each container gets a new address.

Linux always assumes the default `fe80::/64` and assigns addresses to interfaces based on that. So, when using a different link-local subnet, interfaces will get two LL addresses - one from docker, one from Linux.
