### ISSUE TITLE
Old image lost on image pull

### ISSUE THREAD

**Issue by rumpl** [moby/moby#46866]
### Description

When a `docker pull` updates an image we are losing the old image.

### Reproduce

```console
$ docker pull debian:oldstable-20200514
$ docker tag debian:oldstable-20200514 debian:stable
$ docker image rm -f debian:oldstable-20200514
$ docker pull debian:stable
$ docker images
```

With graph drivers the last command shows
```console
REPOSITORY   TAG       IMAGE ID       CREATED       SIZE
debian       stable    c505deff3653   8 days ago    139MB
debian       <none>    476d4a705c2f   3 years ago   95.8MB
```

And with containerd we end up with 
```console
REPOSITORY   TAG       IMAGE ID       CREATED      SIZE
debian       stable    ed69ce2733ba   8 days ago   205MB
```

The old image was lost.

### Expected behavior

After the second pull the old image should still be present

### docker version

```bash
master
```

### docker info

```bash
master
```

**Comment by thaJeztah** [comment]
This sounds related to the discussion we had on "always creating a `dangling` image" to keep a reference (with digest). In that case, removing the tag from the image would keep the dangling image (`<none>`)

**Comment by rumpl** [comment]
I asked myself the same, if there is a container already using the image that will be updated after a `pull` then yeah, we want to keep that image a little while longer. But once the container is removed, is there really a need to keep the old image?...

But then again, you could imaging someone pulling a new version of the image, test it out and decide they want to rollback, if we remove the image they would need to re-pull the old image, if it's still there then a `tag` is enough.

I'm not sure how useful keeping the old image is useful... Removing the old image if a pull updates it would help in the most painful point people have with docker: images taking too much space.

**Comment by thaJeztah** [comment]
Yes; this needs some thinking;

- restarting container should not update image (IIRC, we resolve digest, and persist that, to prevent that happening; in that case we refer to the image by digest once the tag is gone)
- for rollback; that's indeed the tricky one: it may be unexpected for the image to be fully gone _immediately_, but perhaps "less unexpected" for it to be garbage-collected _eventually_ 
- similarly: `docker build` multiple times; do we want to keep the "previous build" (but untagged)? To some extent we have build-cache to build the image again (but the source material to build it may no longer be present)
- ☝️ both are also cases where it would be beneficial to distinguish "pulled" images from "locally built" (pulled images can be pulled again, so usually "no harm done" if the image is removed from the cache) 
- ☝️ I think eventually, we want to make managing the image cache easier, and less "manual" (`docker system prune`), so that we can more depend on automatic garbage-collecting unused content


But finding the right balance is hard (and may differ between use-cases), so perhaps some amount of "tweak-ability" (config) may be needed. As well as (possibly) more polished UX to manage content ready for garbage collection (separate `trash` namespace that keeps X versions of an image, and a way to "empty the trash"?)
