### ISSUE TITLE
[27.0 regression] Docker Pull Fails in Rootless "failed to register layer: failed to Lchown "/dev/console"

### ISSUE THREAD

**Issue by drcapulet** [moby/moby#48064]
### Description

With the release of v27, we're unable to pull a certain image from Docker Hub:

```
failed to register layer: failed to Lchown "/dev/console" for UID 0, GID 0: lchown /dev/console: no such file or directory
```

In addition, when trying to use a registry mirror, we get the following error even though the mirror isn't listening on `443` (it is on localhost however):

```
Get "https://registry-1.docker.io/v2/": dial tcp 127.0.0.1:443: connect: connection refused
```

### Reproduce

1. Install `docker-ce:5:27.0.1-1~debian.12~bookworm` in a rootless mode (I haven't tested normal mode)
2. `docker pull mysql:8.0.33-oracle`

### Expected behavior

The image should be able to pulled.

### docker version

```bash
Client: Docker Engine - Community
 Version:           27.0.1
 API version:       1.46
 Go version:        go1.21.11
 Git commit:        7fafd33
 Built:             Mon Jun 24 14:58:05 2024
 OS/Arch:           linux/amd64
 Context:           rootless

Server: Docker Engine - Community
 Engine:
  Version:          27.0.1
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       ff1e2c0
  Built:            Mon Jun 24 14:58:05 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.18
  GitCommit:        ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc:
  Version:          1.7.18
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 rootlesskit:
  Version:          2.0.2
  ApiVersion:       1.1.1
  NetworkDriver:    slirp4netns
  PortDriver:       builtin
  StateDir:         /run/user/999/dockerd-rootless
 slirp4netns:
  Version:          1.2.0
  GitCommit:        656041d45cfca7a4176f6b7eed9e4fe6c11e8383
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    27.0.1
 Context:    rootless
WARNING: No cpuset support
WARNING: No io.weight support
 Debug Mode: false
WARNING: No io.weight (per device) support
WARNING: No io.max (rbps) support
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.15.1
WARNING: No io.max (wbps) support
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
WARNING: No io.max (riops) support
  compose: Docker Compose (Docker Inc.)
WARNING: No io.max (wiops) support
    Version:  v2.28.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 8
 Server Version: 27.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  rootless
  cgroupns
 Kernel Version: 6.1.0-21-cloud-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.63GiB
 Name: packer
 ID: bbe714f9-4b00-4010-9c93-0cabbbe25a84
 Docker Root Dir: /var/lib/buildkite-agent/.local/share/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
Looks like the error itself originates from the containerd dependency code; https://github.com/moby/moby/blob/ff1e2c0de72a1bbbe4cdbe1558da57d327899df5/vendor/github.com/containerd/containerd/archive/tar.go#L395-L403

I'm somewhat curious though why it's trying to chown `/dev/console` here, which probably wouldn't be present in the image layer, but is mounted at runtime;

```
devpts on /dev/console type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
```

If present in the tar-headers, I would somewhat expect it to have a different type; https://github.com/moby/moby/blob/v27.0.1/vendor/github.com/containerd/containerd/archive/tar.go#L335-L387

**Comment by thaJeztah** [comment]
I see it's reported here as well; also for the same image, so wondering if there's something wrong with that image, but not sure what changed in the code (I need to check the containerd code to see if anything changed there);

- https://github.com/docker/for-linux/issues/1497

**Comment by thaJeztah** [comment]
Docker 26.1.4 is using the same module version of containerd as 27.0.1, so no change in that area 🤔 https://github.com/moby/moby/blob/v26.1.4/vendor.mod#L28

**Comment by vvoland** [comment]
I think this is coming from here: https://github.com/moby/moby/blob/c083aae0f3d5114cd59f501300a0c724dcac2b0d/pkg/archive/archive.go#L767

**Comment by thaJeztah** [comment]
Oh! I may be looking at the wrong package; containerd partially forked the code from pkg/archive in this repository, so the actual error would likely be from here; https://github.com/moby/moby/blob/ff1e2c0de72a1bbbe4cdbe1558da57d327899df5/pkg/archive/archive.go#L763-L772

**Comment by thaJeztah** [comment]
Oh! Beat me to it; I was copy/pasting the right location 😂

**Comment by thaJeztah** [comment]
Could it be related to https://github.com/moby/moby/commit/838047a1f5bf47aa65eb6901a20abdb5ab9b640a;

- https://github.com/moby/moby/pull/47605

**Comment by thaJeztah** [comment]
Actually; that _could_ be related; the error is that the file wasn't found; `lchown /dev/console: no such file or directory`. Could it be that it's masked by a whiteout file, and older versions of docker didn't see that file (so it wasn't masked?)

**Comment by thaJeztah** [comment]
@drcapulet could you open a separate ticket for the registry mirror issue?

> In addition, when trying to use a registry mirror, we get the following error even though the mirror isn't listening on 443 (it is on localhost however):

**Comment by drcapulet** [comment]
@thaJeztah Appreciate the super fast response! Given the mirror issue only happens for the same image, want me to hold off on opening it as a separate issue?

**Comment by thaJeztah** [comment]
The mirror issue seems to be in a very different area; you mean that the same configuration doesn't produce the error when pulling any other image? That's ... curious 🤔

**Comment by thaJeztah** [comment]
Copying from a conversation on Slack; the image seems to have a `/dev/console`, but it should be a character-device type, so it's odd that we're hitting this code (which should not be run for non-regular files), and even more surprising that it give as `no such file or directory` error.

https://oci.dag.dev/layers/oraclelinux@sha256:32cb74696955b7a2e12d3fc6f2e1160551abd6cc4360b5c14fbf53c8ea38a7ae/dev/

<img width="1036" alt="Screenshot 2024-06-27 at 01 01 11" src="https://github.com/moby/moby/assets/1804568/dc79e2c6-372d-447b-923e-14148bba60e5">

As the  PR I mentioned above https://github.com/moby/moby/issues/48064#issuecomment-2192683197 also relates to setting xattrs, wondering if any of the discussion in https://github.com/moby/moby/issues/47962 might be relevant as well.

**Comment by drcapulet** [comment]
@thaJeztah Correct - with or without a mirror, that image is the first one with an error (we pull `elasticsearch:7.17.3` and `mongo:7.0` just fine before that among some other internal images).

**Comment by mdelapenya** [comment]
We are seeing a similar behaviour in testcontainers-go repo, where the Docker version installed in the GH workers was updated yesterday to v27. Since then, we see this error in a consistent manner:

```
Error response from daemon: No such image: mysql:8.0.36: failed to create container
```

**Comment by thaJeztah** [comment]
We discussed this regression in Yesterday's maintainers call, and (to be bisected) we suspect the regression point is in https://github.com/moby/moby/commit/b2fd67de77be8692ff343d26a9819a3c42ef8c2f and https://github.com/moby/moby/commit/f6b80253b8bfc04b9a6ef0e6bd73e44d36778046 (https://github.com/moby/moby/pull/47605), which enabled the "native" differ for overlayfs for rootless (if supported), but this resulted in code-paths being used that still needed to take special conditions for rootless into account that were not configured for that.

- In the "fuse-overlay" case, this option would be set in `Driver.ApplyDiff`; https://github.com/moby/moby/blob/47eebd718f332f29a38455b61ee879ced5bc219b/daemon/graphdriver/fuse-overlayfs/fuseoverlayfs.go#L456-L462
- But not with the "overlay2" case, where `Driver.ApplyDiff` does not set the `InUserNS` option: https://github.com/moby/moby/blob/47eebd718f332f29a38455b61ee879ced5bc219b/daemon/graphdriver/overlay2/overlay.go#L684-L689

Before  https://github.com/moby/moby/commit/b2fd67de77be8692ff343d26a9819a3c42ef8c2f and https://github.com/moby/moby/commit/f6b80253b8bfc04b9a6ef0e6bd73e44d36778046, both would return early because `useNaiveDiff()` would be true; https://github.com/moby/moby/blob/47eebd718f332f29a38455b61ee879ced5bc219b/daemon/graphdriver/overlay2/overlay.go#L248-L250

With that option not being set, this code-path would not return early;
https://github.com/moby/moby/blob/ff1e2c0de72a1bbbe4cdbe1558da57d327899df5/pkg/archive/archive.go#L713-L720


Therefore trying to execute `handleTarTypeBlockCharFifo`, which ignores `syscall.EPERM` errors when running with user-namepaces enabled;
https://github.com/moby/moby/blob/47eebd718f332f29a38455b61ee879ced5bc219b/pkg/archive/archive_unix.go#L110-L114

And with that error being ignored, won't return here; https://github.com/moby/moby/blob/ff1e2c0de72a1bbbe4cdbe1558da57d327899df5/pkg/archive/archive.go#L718-L720

Ultimately hitting the `LChown` code, which fails because the `handleTarTypeBlockCharFifo` didn't succeed, so the file is not found; https://github.com/moby/moby/blob/ff1e2c0de72a1bbbe4cdbe1558da57d327899df5/pkg/archive/archive.go#L762-L773

**Comment by thaJeztah** [comment]
- opened a pull request https://github.com/moby/moby/pull/48083

**Comment by adamiBs** [comment]
We still managed to reproduce this issue with the latest version of docker (`v27.0.3`) while using rootless docker.
How was the fix tested?

**Comment by thaJeztah** [comment]
🤔 I ran the reproducer with and without the patch, and didn't get the error with the patch

**Comment by drcapulet** [comment]
@thaJeztah Can confirm our issues have been fixed, thanks for such a quick turnaround!

**Comment by thaJeztah** [comment]
Thanks @drcapulet good to hear!
