### ISSUE TITLE
Using http(s) proxy always see error: Get "https://registry-1.docker.io/v2/": proxyconnect tcp: EOF

### ISSUE THREAD

**Issue by shaojun** [moby/moby#48131]
### Description

I've run a `http` and `https` proxy on local host `port 7890`, and set shell env as well:
```
root@iot-message-2002:~# printenv | grep http
https_proxy=https://127.0.0.1:7890
http_proxy=http://127.0.0.1:7890
```
can test through:
```
wget https://google.com
--2024-07-05 11:11:50--  https://google.com/
Connecting to 127.0.0.1:7890... connected.
Proxy request sent, awaiting response... 301 Moved Permanently
Location: https://www.google.com/ [following]
--2024-07-05 11:11:50--  https://www.google.com/
Connecting to 127.0.0.1:7890... connected.
Proxy request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html’

index.html                                             [ <=>                                                                                                             ]  20.05K  --.-KB/s    in 0.02s

2024-07-05 11:11:50 (1.19 MB/s) - ‘index.html’ saved [20531]

```
and same with `wget https://hub.docker.com/ `, both can be successfully get.     
I've set the `Enviroment` in `docker.service`:
```
root@iot-message-2002:~# cat /lib/systemd/system/docker.service
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network-online.target docker.socket firewalld.service containerd.service time-set.target
Wants=network-online.target containerd.service
Requires=docker.socket

[Service]
Environment="HTTP_PROXY=http://127.0.0.1:7890"
Environment="HTTPS_PROXY=https://127.0.0.1:7890"
Type=notify
# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
ExecStart=/usr/bin/dockerd --data-root /data/docker -H fd:// --containerd=/run/containerd/containerd.sock
ExecReload=/bin/kill -s HUP $MAINPID
...
...
...
```
also , the above `Enviroment` can be checked at below my `docker info`.    

The problem is I always get error with `docker run`:
```
docker run hello-world
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": proxyconnect tcp: EOF.
See 'docker run --help'.
```
I manully open `https://registry-1.docker.io/v2/` at my **browser**, also get:
```
"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
```
so I tried `docker login` with a **valid** user name and password which can be done a real successful login at **browser**:    
![image](https://github.com/moby/moby/assets/3241829/b2284097-8f32-43fe-9b3f-3dd8bb5fb187)

but still same error:
```
 docker login
Log in with your Docker ID or email address to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com/ to create one.
You can log in with your password or a Personal Access Token (PAT). Using a limited-scope PAT grants better security and is required for organizations using SSO. Learn more at https://docs.docker.com/go/access-tokens/

Username: xxxxxxx@gmail.com
Password:
Error response from daemon: Get "https://registry-1.docker.io/v2/": proxyconnect tcp: EOF
```

Could you help to check?

### Reproduce

already listed.

### Expected behavior

Should pull down images successfully.

### docker version

```bash
Client: Docker Engine - Community
 Version:           26.1.3
 API version:       1.45
 Go version:        go1.21.10
 Git commit:        b72abbb
 Built:             Thu May 16 08:33:49 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.1.3
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.10
  Git commit:       8e96db1
  Built:            Thu May 16 08:33:49 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.31
  GitCommit:        e377cd56a71523140ca6ae87e30244719194a521
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    26.1.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 17
  Running: 16
  Paused: 0
  Stopped: 1
 Images: 10
 Server Version: 26.1.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e377cd56a71523140ca6ae87e30244719194a521
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-77-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.45GiB
 Name: iot-message-2002
 ID: b706fc7c-452d-4a6c-ade8-34798523d9e3
 Docker Root Dir: /data/docker
 Debug Mode: false
 HTTP Proxy: http://127.0.0.1:7890
 HTTPS Proxy: https://127.0.0.1:7890
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

### Additional Info

os info:
```
 cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```

**Comment by thaJeztah** [comment]
Your CLI environment has `http://....` (non-TLS) for your proxy, which is what I would expect for a localhost address;

> ```console
> root@iot-message-2002:~# printenv | grep http
> https_proxy=http://127.0.0.1:7890
> http_proxy=http://127.0.0.1:7890
> ```

However for the daemon, it looks like you configured `https://...`;

> ```console
> HTTP Proxy: http://127.0.0.1:7890
> HTTPS Proxy: https://127.0.0.1:7890
> Experimental: false
> ```


Which likely will fail; does it work if you configure it with `http://...` for both?

**Comment by shaojun** [comment]
@thaJeztah sorry my mistake to miss-configed the `https_proxy` to `http://127.0.0.1:7890` in CLI environment, I've corrected it and now is:
```
 printenv | grep http
https_proxy=https://127.0.0.1:7890
http_proxy=http://127.0.0.1:7890
```
and the `wget https://google.com` works well.    
I'm using the `clash` as the proxy application, it'll proxy `http, https, socks` protocols.

**Comment by thaJeztah** [comment]
> sorry my mistake to miss-configed the `https_proxy` to `http://127.0.0.1:7890` in CLI environment, I've corrected it and now is:

That output looks the same as before :sweat_smile:

Can you configure the CLI (`printenv`) to have `http` for both; also make sure that you set _both_ lowercase and uppercase variants (proxy env-vars are not a formal definition, and some tools use lowercase, other use uppercase, some understand "both" but in different order), so that it looks like;

```bash
printenv | grep -i http | sort -rf

http_proxy=http://127.0.0.1:7890
HTTP_PROXY=http://127.0.0.1:7890
https_proxy=http://127.0.0.1:7890
HTTPS_PROXY=http://127.0.0.1:7890
```

And the same for the daemon, so that the `docker info` output shows non-TLS proxy for both;

```console
 HTTP Proxy: http://127.0.0.1:7890
 HTTPS Proxy: http://127.0.0.1:7890
```


Both `http` and `https` proxies in your example output show the same port, and I doubt it's running with TLS; if it is, then it cannot be running _both_ TLS and non-TLS on the same port. My suspicion is that `wget` is silently some things (tries the `https_proxy`, detects that's not accepting TLS connections, then continues with the `http_proxy` or vice-versa). 

However, the Go runtime (docker is written in Go) will no longer use `HTTP_PROXY` for TLS hosts since Go 1.16; see https://docs.docker.com/engine/release-notes/20.10/#20108

> **IMPORTANT**
>
> Due to [net/http changes](https://github.com/golang/go/issues/40909) in [Go 1.16](https://golang.org/doc/go1.16#net/http), HTTP proxies configured through the `$HTTP_PROXY` environment variable are no longer used for TLS (`https://`) connections. Make sure you also set an `$HTTPS_PROXY` environment variable for handling requests to `https://` URLs.


The `docker` CLI doesn't need the proxy for connecting to the docker daemon if the daemon is running on the same machine (in which cases it uses the `/var/run/docker.sock` unix socket for the API), but the docker daemon will use the `HTTPS_PROXY` for communication with registries, which likely fails, and now resulting in the cryptic `eof` error.

FWIW: instead of the systemd unit, you can also use a `daemon.json` configuration file; you can also use that to put the daemon in debug-mode to get it to produce (verbose!) logs that can help you debugging;


On the daemon host; make sure docker's config directory (`/etc/docker`) exist if it doesn't exist yet, otherwise create it.

Create a `daemon.json` file if it doesn't exist (or edit your existing one to add the new options);

```json
{
  "debug": true,
  "proxies": {
    "http-proxy": "http://127.0.0.1:7890",
    "https-proxy": "http://127.0.0.1:7890"
  }
}
```

You must restart the daemon for the new settings to be used.

:warning: Also note that these proxy settings only apply to the daemon itself (so used for pushing/pulling images), but are _NOT_ inherited by containers that are created. If your containers must be able to make networking connections and need a proxy for that, you need to configure the CLI to set these proxy variables as default for containers you create; https://docs.docker.com/network/proxy/#configure-the-docker-client

**Comment by shaojun** [comment]
@thaJeztah thanks.
it works after I set both `HTTP_PROXY` and `HTTPS_PROXY` to point to same url `http://127.0.0.1:7890`:
```
# nano /lib/systemd/system/docker.service
...
[Service]
Environment="HTTP_PROXY=http://127.0.0.1:7890"
Environment="HTTPS_PROXY=http://127.0.0.1:7890"
...
```
and as you suggested, the `CLI` (the ubuntu terminal, or shell?) is actually no need to set proxy, as the purpose here is to makes `docker engine`  pull images via proxy.
