### ISSUE TITLE
dose docker build image related to the disk of the local machine? 

### ISSUE THREAD

**Issue by z7658329** [moby/moby#48229]
### Description

it takes about 10 mins to execute step 1 to step 8, why costs so much time? I want to ask if the docker build image is related to the disk of the local machine?

<img width="427" alt="image" src="https://github.com/user-attachments/assets/b6277654-bbdc-424e-b6ea-fd6e749938ce">

### Reproduce

docker build image，but takes long time to exec.

### docker version

```bash
Client: Docker Engine - Community
 Version:           19.03.10
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9424aeaee9
 Built:             Thu May 28 22:16:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.10-HUYA-20221012
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.11
  Git commit:       69fce8a796
  Built:            Tue Nov  1 03:59:20 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

### docker info

```bash
Client:
 Debug Mode: false

Server:
 Containers: 22
  Running: 16
  Paused: 0
  Stopped: 6
 Images: 9
 Server Version: 19.03.10-HUYA-20221012
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: fec3683
 Security Options:
  apparmor
 Kernel Version: 5.4.0-48-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 123.1GiB
 Name: iv-yd4zwwfpq8nr7giarqm7
 ID: QB65:D5YP:EFLM:HN3E:Y2UX:RW6O:5ITU:CVF3:CURM:TS33:DQ7Z:UO5R
 Docker Root Dir: /k8s/kubernetes/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
```

**Comment by vvoland** [comment]
With the legacy builder, each build step needs to spawn a new container and commit it which comes with writing the new layers to the disk.

Also, please note that you're using an outdated version of Docker Engine. These versions use the legacy/classic builder which is deprecated. Recent releases use Buildkit as a builder backend by default, which comes with better performance and more features.

**Comment by thaJeztah** [comment]
Yes, I'd definitely recommend (if possible) to use a current version.

I do notice that the version of docker you're running is not an official build (`19.03.10-HUYA-20221012`) and not a package that's built or maintained by us, so it's also possible it's built from source-code with patches that are not in upstream.

If possible, and if you have an environment to test in, it's worth trying the current version of docker from docker's official packages (https://docs.docker.com/engine/install/ubuntu/), or otherwise reporting this issue with the maintainers of the package you're using.

I'm closing this ticket, because this is an issue with a version of docker that reached EOL, and a package that's not maintained by this project.
