### ISSUE TITLE
networking: investigate `EINTR` regression after updating github.com/vishvananda/netlink to v1.3.0

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#48400]
### Description

- relates to https://github.com/moby/moby/pull/48368
- relates to https://github.com/moby/moby/pull/46982#issuecomment-2315840500
- relates to https://github.com/vishvananda/netlink/pull/793#issuecomment-2315879136

github.com/vishvananda/netlink was updated to v1.3.0 in https://github.com/moby/moby/pull/46982, but resulted in flakiness in CI;

```
Error initializing network controller: list bridge addresses failed: interrupted system call
```   

Upon first look, it was suggested that this was due to a missing condition for handling `EINTR`;  https://github.com/moby/moby/pull/46982#issuecomment-2315840500

> EINTR on netlink sockets is a new one. I suspect it has more to do with the netlink dependency bump you pulled in when rebasing than on the Go toolchain bump. I think the bug is here: https://github.com/vishvananda/netlink/blob/92645823f36c7ed03faf4baa566078d9d5e06fda/nl/nl_linux.go#L821-L824 It retries on `EWOULDBLOCK` (a.k.a. `EAGAIN`) but neglects to retry on `EINTR `.

However, it may be because of our use of `SetSocketTimeout `; see https://github.com/vishvananda/netlink/pull/793#issuecomment-2316612423

> IO calls on non-blocking sockets will never return `-EINTR`. The problem here is that Moby calls `SetSocketTimeout`, which sets `SO_SNDTIMEO` and `SO_RCVTIMEO`. These socket options are only useful for sockets in blocking mode. Setting these probably places the socket back into blocking mode.
> 
> https://github.com/moby/moby/blob/92a05cf4148adc26054a5b52b191e0b4d13112cd/libnetwork/ns/init_linux.go#L25-L40
> 
> https://github.com/vishvananda/netlink/blob/92645823f36c7ed03faf4baa566078d9d5e06fda/nl/nl_linux.go#L848-L860
> 
> I'm not very familiar with this project, but it seems to me that before this PR, only blocking IO is used. This PR adds calls to set the socket as non-blocking, but still allows setting the timeout socket options.

Those `SetSocketTimeout` uses were added in https://github.com/moby/libnetwork/commit/f459afbcfc5f1cb09051f7843c5766d2c1a6776c

- https://github.com/moby/libnetwork/pull/1557
- (moby PR: https://github.com/moby/moby/pull/29004)

to address 

- https://github.com/moby/libnetwork/issues/1474
- https://github.com/moby/libnetwork/issues/2208

Also related:

- https://github.com/vishvananda/netlink/pull/170

**Comment by thaJeztah** [comment]
cc @robmry @akerouanton @corhere @cpuguy83

**Comment by robmry** [comment]
A fix for timeouts, related to the non-blocking socket change mentioned above, has been merged:
- https://github.com/vishvananda/netlink/pull/1012

But the `EINTR` problem turned out to be unrelated. It's due to https://github.com/vishvananda/netlink/pull/925, exposing an `NLM_F_DUMP_INTR` (reported in the netlink response) as an EINTR ...
https://github.com/vishvananda/netlink/blob/92645823f36c7ed03faf4baa566078d9d5e06fda/nl/nl_linux.go#L582-L584

An `NLM_F_DUMP_INTR` indicates that results from a dump (of addresses, interfaces etc) may be inconsistent. Entries may be missing or duplicated. There may be unmodified and modified versions of objects.

Repeating the request doesn't guarantee success but, on a host that's not churning a large amount of config quickly, it's very likely. So, I don't think there's safe way to just-retry in the netlink package to avoid returning the EINTR - it'll have to be up to the caller to decide what to do.

So, retrying some small number of times in moby seems like the best/only option.

At present, when `EINTR` is returned, the partial/inconsistent results are not included. I'll prepare a PR to change that, so the caller has the option of using those results without a retry. (If, for example, the dump was to find an object with some property, and that object is included in the results, that might be fine. Only the caller can decide.)

If that change is accepted, we'll have to look at what moby does case-by-case.
