### ISSUE TITLE
Seeing too many undefined error with moby client

### ISSUE THREAD

**Issue by digambarpat** [moby/moby#48535]
### Description

I changed from docker to moby client and after updating using go mod tidy, I see too many below errors.

# github.com/moby/moby/client
../go/pkg/mod/github.com/moby/moby@v27.0.2-0.20240919110402-dfbc3a89a564+incompatible/client/interface.go:59:69: undefined: container.InspectResponse
../go/pkg/mod/github.com/moby/moby@v27.0.2-0.20240919110402-dfbc3a89a564+incompatible/client/interface.go:60:90: undefined: container.InspectResponse
../go/pkg/mod/github.com/moby/moby@v27.0.2-0.20240919110402-dfbc3a89a564+incompatible/client/interface.go:62:81: undefined: container.Summary
../go/pkg/mod/github.com/moby/moby@v27.0.2-0.20240919110402-dfbc3a89a564+incompatible/client/interface.go:94:61: undefined: image.HistoryOptions
../go/pkg/mod/github.com/moby/moby@v27.0.2-0.20240919110402-dfbc3a89a564+incompatible/client/interface.go:96:64: undefined: image.InspectResponse
../go/pkg/mod/github.com/moby/moby@v27.0.2-0.20240919110402-dfbc3a89a564+incompatible/client/interface.go:98:61: undefined: image.LoadOptions
../go/pkg/mod/github.com/moby/moby@v27.0.2-0.20240919110402-dfbc3a89a564+incompatible/client/interface.go:102:61: undefined: image.SaveOptions
../go/pkg/mod/github.com/moby/moby@v27.0.2-0.20240919110402-dfbc3a89a564+incompatible/client/container_inspect.go:14:89: undefined: container.InspectResponse
../go/pkg/mod/github.com/moby/moby@v27.0.2-0.20240919110402-dfbc3a89a564+incompatible/client/container_inspect.go:30:110: undefined: container.InspectResponse
../go/pkg/mod/github.com/moby/moby@v27.0.2-0.20240919110402-dfbc3a89a564+incompatible/client/container_list.go:14:99: undefined: container.Summary
../go/pkg/mod/github.com/moby/moby@v27.0.2-0.20240919110402-dfbc3a89a564+incompatible/client/container_list.go:14:99: too many errors

I believe people are also seeing same errors

### Reproduce

It's mostly related to moby/client update error

### docker version

```bash
github.com/docker/docker v27.3.0+incompatible
```

### docker info

```bash
this is more of code level error
```

### Additional Info

../go/pkg/mod/github.com/moby/moby@v27.0.2-0.20240919110402-dfbc3a89a564+incompatible/client/container_inspect.go:30:110: undefined: container.InspectResponse
../go/pkg/mod/github.com/moby/moby@v27.0.2-0.20240919110402-dfbc3a89a564+incompatible/client/container_list.go:14:99: undefined: container.Summary
../go/pkg/mod/github.com/moby/moby@v27.0.2-0.20240919110402-dfbc3a89a564+incompatible/client/container_list.go:14:99: too many errors

**Comment by thaJeztah** [comment]
This is expected currently; while the repository name is `moby/moby`, the module name is still `docker/docker`; https://github.com/moby/moby/blob/dfbc3a89a56415f8826d192555f0859df5b8577a/vendor.mod#L1-L6

We do have special `//import` comments in place (which Go can use to produce an error when using the wrong name for imports), but unfortunately those are ignored by Go when building in Go modules mode, so they don't always work; https://github.com/moby/moby/blob/dfbc3a89a56415f8826d192555f0859df5b8577a/client/client.go#L42


To fix this, make sure to (at least for now) use `github.com/docker/docker` as import. We'll eventually rename the imports once all work is completed to migrate the code to an actual _module_ (and having a `go.mod`), but there's still some (non-trivial) work to be done before we can make that transition.



I'll close this ticket because of the above, but feel free to continue the conversation.

**Comment by digambarpat** [comment]
Is it okay to contribute to fixes which is going on ? I would be happy to do that.

**Comment by thaJeztah** [comment]
Contributions are always welcome, but it depends what they are 😅. We won't be renaming the module to moby/moby yet, as there's still parts to change; some are listed in these ticket (there's some other tickets as well);

- https://github.com/moby/moby/issues/32989
- https://github.com/moby/moby/issues/21700

But there's also some complex dependency cycles to address, which span multiple projects; see some (very short) summary of some of the complexity; https://github.com/docker/cli/pull/4116#issuecomment-1492980108

**Comment by digambarpat** [comment]
I will look at the dependency stuff, will go through it.
