### ISSUE TITLE
Make a container's gateway network configurable

### ISSUE THREAD

**Issue by robmry** [moby/moby#48868]
### Description

- moved from https://github.com/docker/compose/issues/12170

When a container is connected to multiple networks, one of them (or, from 28.0, one per address family) will be selected as the gateway endpoint (the container's default route).

At the moment, there's no way to control selection of the gateway endpoint - it should be possible (although far from ideal) to control it by adjusting network names (see below). But, in https://github.com/docker/compose/issues/12170 there are reports of that not working.

From https://github.com/docker/compose/issues/12170, use-cases are around containers with `bridge` and `ipvlan` endpoints, and wanting to control which network gets the default route for Internet traffic.

---

From https://github.com/docker/compose/issues/12170#issuecomment-2465409983:

Every time a container is connected to a network, Docker Engine looks at the container's whole set of endpoints and picks one to use as the gateway. (And, the same after a network disconnect.)

The gateway endpoint it picks is the first in [this ordering](https://github.com/moby/moby/blob/c14efb8deeb2cf5a716ab874c707f9a69228926c/libnetwork/sandbox.go#L677-L683).

I don't think that function's comment is quite right... but, endpoints are sorted by priority, then the dedicated docker_gwbridge network is preferred (for swarm), then non-internal networks, then dual-stack over IPv4-only. Finally, if the networks are equal according to those criteria, they're sorted lexicographically by network name.

That means the order in which networks are connected shouldn't make any difference to the end result:
- Compose's priority only affects the order in which networks are added, the value isn't passed to the engine.
- The epPriority used in the engine's ordering of endpoints is unrelated and, weirdly, there's no way to configure it via the engine's API. (So, it's completely useless.)

But, in the two examples in https://github.com/docker/compose/issues/12170 - the networks are all equal (user-defined, non-internal, and IPv4-only). So, they should be sorted by network name ... I've tried to repro the problem, but haven't been able to. For me, the selected gateway is always based on the network name - including with dockerd 24.0, I don't think this logic has changed since before that release anyway.

**Comment by mrpops2ko** [comment]
did some more testing using a firefox container and looking at various ips and can confirm everything functions as described, meaning that as long as the naming is done correctly then the default eth0 will function based upon that. my claim that it wasn't working is incorrect and likely me getting lost in the networking of traefik, docker, regular networking and the priority fields. 

this still falls short of being a solution that is ideal though, and i'm not entirely sure how multiple ipvlan networks would function and their requirements due to overlapping networks... but i guess this becomes more of a **feature request** rather than a bug (although others in my thread also mentioned to having the same issue)

specifically what would be helpful for me and others like me, is some kind of method to define the `eth0` network inside the container. this could manifest as something like `docker run --network-default db`  or whatever other means, just something that can be explicitly defined rather than a function of sorting

its easy enough to set up the networking and network security based upon A > B but sometimes theres scenarios where explicit A < B is required. i'd even take an inversion flag if thats easier, so its just reversed sorting `docker run --network db --networking-sorting reversed`

**Comment by robmry** [comment]
@mrpops2ko - that's great, thank you for the update.

I think an explicit gateway-priority property for the network endpoint will make most sense, particularly as there's already at-least placeholder logic to handle it in the engine.

**Comment by mrpops2ko** [comment]
https://github.com/docker/compose/issues/4645
https://github.com/moby/moby/pull/43518
https://github.com/docker/compose/issues/11229
https://github.com/docker/compose/issues/8561

just throwing these in here because its the same issue that people are having and should an implementation come about, they'd probably like to know

**Comment by thaJeztah** [comment]
- fixed by https://github.com/moby/moby/pull/48936 (which will be part of v28.0)
