### ISSUE TITLE
API docs incorrectly suggest the api version header is not canonicalised: `API-Version`

### ISSUE THREAD

**Issue by maggie44** [moby/moby#49046]
### Description

The `ping` endpoint docs suggest the api version response header is:

`API-Version`

It is in fact canonical:

```
curl --unix-socket /var/run/docker.sock -i http://localhost/_ping
HTTP/1.1 200 OK
Api-Version: 1.44
```

`Api-Version` is the correct canonical format that headers should use and the docs could be updated to reflect this.

https://docs.docker.com/reference/api/engine/version/v1.44/#tag/System/operation/SystemVersion

### Reproduce

Check the docs 

### docker version

```bash
1.44
```

### docker info

```bash
N/a
```

**Comment by thaJeztah** [comment]
Hm, nice catch; yes, it looks like it's set as `API-Version`, but it's using go's stdlib header functionality which does the normalizing;
https://github.com/moby/moby/blob/68dbb8b3859eed92ad3c52c25ca5bc2f7be181b9/api/server/middleware/version.go#L69-L71

Technically, this should not directly impact users, as these [must be handled case-insensitive](https://datatracker.ietf.org/doc/html/rfc822#section-3.4.7), but  I had a quick peek if this was changed recently, because if that was the case we may have wanted to revert that to use non-canonical format in case there were implementations considering it to be case-sensitive.

Looks like the same applies to the `OSType` header, but I see that one waa added in https://github.com/moby/moby/commit/7199522ea2e77c77bf931474eca92aa502ce0031, but never documented (looks like that should be corrected as well).

Contributions welcome though if someone's interested to work on this;

- swagger can be found here; https://github.com/moby/moby/tree/master/api
- and versioned copies (used for documentation); https://github.com/moby/moby/tree/master/docs/api

But if we change, it would probably be good to also reference those in the correct format in code to prevent confusion, e.g. places like https://github.com/moby/moby/blob/68dbb8b3859eed92ad3c52c25ca5bc2f7be181b9/api/server/middleware/version_test.go#L143-L144
