### ISSUE TITLE
Merge docker info & docker version

### ISSUE THREAD

**Issue by vieux** [moby/moby#5856]
I think we could merge them into one command, or at least docker info should display docker version information

WDYT ?

**Comment by jfrazelle** [comment]
was there a consensus

**Comment by jfrazelle** [comment]
ping @vieux

**Comment by ibuildthecloud** [comment]
I still think this should be done

**Comment by thaJeztah** [comment]
I think it would be good to have a single command that outputs all relevant information we need for tracking issues. Currently we're asking users to add the output of three different things when reporting issues (`docker version`, `docker info` and `uname -a`). Unfortunately, I think we're stuck with that because of older versions still in use, but it'd be nice to simplify that process at some point.

**Comment by vdemeester** [comment]
Given the activity level on this issue, I'm going to close it as it's either fixed, a duplicate or not a request anymore. If you think I'm mistaken, feel free to discuss it there 😉

**Comment by vdemeester** [comment]
Also, if this is still a feature request, it should be in `docker/cli` 😉
