### ISSUE TITLE
Allow to `rebase` firewall rules.

### ISSUE THREAD

**Issue by omeid** [moby/moby#6574]
Sometimes you need to drop all firewall rules to block out attacks or simply reconfigure, doing so overrides the docker containers port forwarding, please provide a mechanism to reapply relevant rules. In Git terms, to rebase the rules. :)

**Comment by stevenboyd** [comment]
+1

**Comment by dqminh** [comment]
+1

We have a set of global iptables rules that is updated and then restored with iptables-restore, and it's not possible to reapply the docker's iptables rules at that time. It would be nice if docker support something like `docker reset-iptables` which reapplies all iptables rules for currently running containers in the system, blocking new changes to iptables while it's in progress.

**Comment by gdm85** [comment]
@dqminh it's not possible to block iptables updates while it's in progress as there is no API to do that. I have peeked into libiptc and it's theoretically possible to leverage same locks that such library uses, but since it's not a published API I would not rely on it, nor make it part of a supported feature in Docker/

**Comment by dqminh** [comment]
@gdm85 i didnt meant to block iptables update entirely ( that would be way too hard ) I meant that docker should not allow its own iptables rules to be changed why we are reapplying docker iptables rules.

**Comment by gdm85** [comment]
@dqminh ah yes, that would be entirely possible to achieve and reasonable

**Comment by zerthimon** [comment]
+1
I'd even like docker to enforce it's firewall rules on every change to running firewall configuration.
In other words: priodically monitor the firewall's configuration and restore any rules (relevant to docker's current state) that may have been removed or changed by other users/process activity.

**Comment by Muty** [comment]
+1

We agree that a "reset-iptables" command would be great. We use ferm with ansible, which flushes the rules sometimes and readds everything based on configuration. Currently we would have to restart everything from docker to get the appropriate docker iptables rules added to the chains.

**Comment by cpuguy83** [comment]
Maybe we could do this on `SIGHUP`, which already reloads other bits of the daemon.

**Comment by dqminh** [comment]
@cpuguy83 yep, SIGHUP or any other form of reloading would be great.

afaik the problem is that the current libnetwork's design doesnt expose any knob for bridge-networking to be able to do such thing. We discuss in https://github.com/docker/docker/issues/15829 but it doesnt reach any solution and it fell off my radar for a while.

**Comment by LK4D4** [comment]
ping @mavenugo @sanimej @aboch

**Comment by gdm85** [comment]
@dqminh meanwhile, I got a bit further at a Go libiptc binding: https://github.com/gdm85/go-libiptc it's not as high-quality as I would like it to be, but it's a start. Its integration would allow to hold the iptables lock (it's a socket really) while applying rules in a sort of "transaction".

**Comment by omeid** [comment]
I no longer use Docker, and give that this has been open for some 8 years, it is unlikely to be fixed considering the change in landscape. Closing as _accepted limitation_.
