### ISSUE TITLE
It would be nice if docker certs could come from the OS cert store

### ISSUE THREAD

**Issue by SvenDowideit** [moby/moby#6685]
The client (and server) could use any cert, including ones loaded into the system by the network admins - thus allowing the browser to access a secured docker daemon.

I was talking to @erikh and he's somewhat sure its not too problematic a change

**Comment by termie** [comment]
-subscribe-

**Comment by justincormack** [comment]
This is now done in Docker for Mac and Docker for Windows.

**Comment by vdemeester** [comment]
@thaJeztah @andrewhsu what is the status here ? (for linux)

**Comment by thaJeztah** [comment]
@n4ss @dmcgowan may be able to give more input, I seem to recall there also was a Golang issue related to this?

**Comment by Jeb135** [comment]
Bumping this thread, has any updates been made around this? 

I'm working with an app in a windows image that needs the ability to perform TLS to APIs whose SSL certs are signed by private CAs, and would like the ability to mount or import the windows host's Trusted Root cert store into the container at runtime, instead of having to build these certs into the image at build time.

**Comment by neersighted** [comment]
I'm not sure I understand the value in this issue; `--tlsverify` using the OS trust store seems like a somewhat niche case. If you can demonstrate a use case where this is necessary (keeping in mind that the TLS flags are mostly intended for mTLS), please feel free to ask for a reopen or open a new issue and link back here.

Some people in this thread are talking about sharing the OS trust store; that is not what the original issue discusses/is out of scope. Please open another issue for that if necessary.
