### ISSUE TITLE
Proposal: Provide public IP and/or domain name to the container via env var

### ISSUE THREAD

**Issue by capoferro** [moby/moby#7472]
(Extracted from thread in #7421)

For apps that register themselves with service discovery (such as [Eureka](https://github.com/Netflix/eureka)), containers need to know what their publicly accessible IP or domain name is in order for the contained apps to register themselves correctly.

**Comment by flaviostutz** [comment]
+1
I really need this for registering container services on etcd from inside the container!
For example, if I have a bunch of NodeJS containers serving my Application (with elastic resizing) and I have a bunch of NGinx containers on its front balancing requests, I would like to have NGinx instances to lookup at etcd for available NodeJS containers (along with IP:port) so that NGinx instances could automatically reconfigure themselves for added/removed NodeJS containers during operations.

**Comment by thaJeztah** [comment]
@flaviostutz I wonder if that should be done by the container *itself*, or by a *separate* container, making use of [docker events](https://docs.docker.com/reference/api/docker_remote_api_v1.16/#monitor-dockers-events); ie, when a container is started, docker fires a "start" event. The separate container listens for these events and registers the container in etcd.

A nice blog post (using [docker-gen](https://github.com/jwilder/docker-gen)), can be found here: [Docker Service Discovery Using Etcd and Haproxy](http://jasonwilder.com/blog/2014/07/15/docker-service-discovery/). If you just need to configure NGINX, also have a look at [nginx-proxy](https://github.com/jwilder/nginx-proxy)

I'm not sure if those example cover your needs, but they may give you some ideas.

HTH!

**Comment by cpuguy83** [comment]
Or you can even have nginx use etcd as a source of routing... this would require some LUA stuff, though I wouldn't be surprised if someone has done this.
There is also hipache (and nginx-hipache) which uses redis as a backend.

**Comment by vdemeester** [comment]
Given the activity level on this issue, I'm going to close it as it's either fixed, a duplicate or not a request anymore. If you think I'm mistaken, feel free to discuss it there 😉

**Comment by capoferro** [comment]
@dmick It's honestly reasonable to close an issue that hasn't seen activity in almost 4 years.
