### ISSUE TITLE
Can't bind to privileged ports as non-root

### ISSUE THREAD

**Issue by tianon** [moby/moby#8460]
The simplest way to reproduce this is:

``` console
$ docker run --rm -u 1000 php:apache
...
(13)Permission denied: AH00072: make_sock: could not bind to address [::]:80
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
...
```

So, that led me to try this, but with the same result:

``` console
$ docker run --rm -u 1000 --cap-add NET_BIND_SERVICE php:apache
...
(13)Permission denied: AH00072: make_sock: could not bind to address [::]:80
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
...
```

IMO, it seems reasonable to allow non-root to bind to privileged ports inside the container, especially since they have a private net namespace, so I was actually surprised this wasn't already taken care of.  I'm also confused as to why the `--cap-add` didn't work, but maybe that's because it adds the cap to the whitelist of things to not remove, not necessarily adds it if it isn't there?  I'm grasping at straws here.

**Comment by allingeek** [comment]
An even more simple example:

```
$sudo docker run --rm -u nobody --cap-add net_bind_service ubuntu:latest nc -l 0.0.0.0 80
nc: Permission denied
```
Further capsh indicates that cap_net_bind_service is included:
```
$ docker run --rm -u nobody --cap-add net_bind_service ubuntu:latest capsh --print
Current: = cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap+i
Bounding set =cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap,37
Securebits: 00/0x0/1'b0
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
uid=65534(nobody)
gid=65534(nogroup)
groups=
```
Running on boot2docker:
```
$ uname -a
Linux boot2docker 3.16.7-tinycore64 #1 SMP Tue Dec 16 23:03:39 UTC 2014 x86_64 GNU/Linux
```
Versions:
```
$ docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): darwin/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```
What is the guidance? Is this supposed to work?

**Comment by cpuguy83** [comment]
This fails with --privileged as well, fyi.

**Comment by mrunalp** [comment]
The issue here is that the process's effective capabilities don't have
cap_net_bind_service when the user is not root unless the file you are
trying to execute has those capabilities bits set.

Example to get it working for nc:
```
[root@localhost ~]# docker run -it --rm -u 1000 ubuntu /bin/nc.openbsd -l 0.0.0.0 80
nc.openbsd: Permission denied

# Run an image as root, setcap the necessary file and commit it.
[root@localhost ~]# docker run -it --rm ubuntu bash
root@caa42897b59c:/#
root@caa42897b59c:/# setcap 'cap_net_bind_service=+ep' /bin/nc.openbsd
root@caa42897b59c:/# getcap  /bin/nc.openbsd
/bin/nc.openbsd = cap_net_bind_service+ep
root@caa42897b59c:/# exit
exit

# Run the new image as non-root
[root@localhost ~]# docker run -it --rm -u 1000 ubuntu-user-nc /bin/nc.openbsd -l 0.0.0.0 80

works!
```

**Comment by tianon** [comment]
@mrunalp don't we have Docker backends that don't properly support those cap bits though?

**Comment by mrunalp** [comment]
@tianon There is really no other option here besides using user namespaces or setting caps on files :(

**Comment by eparis** [comment]
so setting the executables as suid root (even worse)

**Comment by tianon** [comment]
@mrunalp you've got me intrigued with mention of user namespaces -- do you just mean mapping the non-root user to be host root, or is there some other feature of user namespaces that makes privileged port mapping possible as non-root without setting caps on files? :smile:

**Comment by mrunalp** [comment]
@tianon In case of user namespaces, the container process uid is 0 inside (and non-zero outside). When a process with uid 0 execs a binary (irrespective of which user namespace it belongs to), the rules for capabilities for root apply and it gains all the capabilities in its permitted and effective sets except those masked by the bounding set. So, from a capabilities perspective it will behave just like regular root and since we have CAP_NET_BIND_SERVICE in the default template, it will work :)

**Comment by tianon** [comment]
Ah, but we'd still have the issue where `USER` and `-u` make this not work; shucks.

Looks like it's time to document that setting capabilities on files is the solution going forward.

**Comment by mrunalp** [comment]
@tianon Yep, this should be documented.

**Comment by thaJeztah** [comment]
@tianon @mrunalp apparently you both have a clear understanding what has to be documented. Would one of you be willing to create a PR for adding a description (and example) to the documentation?

Also, is documentation the only actionable item here? Or should this stay open after that (in hope of a better solution)?

**Comment by mrunalp** [comment]
I can add the documentation changes. I don't think there is any fix short of a kernel change if it ever happens.

**Comment by thaJeztah** [comment]
@mrunalp That would be great! In that case, I think you should add a `closes #8460` to that PR

@tianon can you agree with that? (as it's your issue)

**Comment by tianon** [comment]
Yeah, documentation would be good for sure.

I think https://github.com/docker/docker/issues/1070#issuecomment-22206125 from @jpetazzo is also important to note, because `setcap 'cap_net_bind_service=+ep' /some/executable` _will_ round-trip through BTRFS just fine, but not AUFS. :cry:

**Comment by bacongobbler** [comment]
> I think #1070 (comment) from @jpetazzo is also important to note, because setcap 'cap_net_bind_service=+ep' /some/executable will round-trip through BTRFS just fine, but not AUFS. :cry:

+1. I was just burned by this. :cry: :panda_face:

**Comment by justincormack** [comment]
There was a kernel change for this: since kernel 4.3 there are ambient capabilities which are kept across an `execve` when not root. So we could now support this, but I am not sure what the best way to do this is given that many users will not be able to take advantage of it a they are running older kernels, will have a think about it.

**Comment by justincormack** [comment]
Note though that this is fixed in recent aufs, and now on Docker Hub see https://github.com/docker/hub-feedback/issues/461 so it is easier to set file capabilities on more systems.

I am still somewhat inclined to add ambient capability support, for recent kernels only, it would have to be something like `docker run --user=1000 --cap-add-ambient NET_BIND_SERVICE nginx` I think. But that would only work for some users and the rest would have to set the fs capabilities or run as root. Setting filesystem capabilities assumes in advance that you know which capabilities you (might) need which is usually the case for something like opening ports, but not necessarily the case for more generic code.

**Comment by nfnty** [comment]
@justincormack Any progress on ambient capabilities?

**Comment by justincormack** [comment]
@nfnty have discussed it with various people. The main issue is that it is 4.3 kernel only so not very many people are going to be able to use it which makes it a difficult thing to document. It is on the TODO list though, will have a look at doing a PR soon.

**Comment by justincormack** [comment]
Ok, I have a working version with support for ambient caps, let me see about upstreaming it.

**Comment by mrunalp** [comment]
@justincormack Nice :) I was just beginning to look into runc changes for it today. Will wait for your patch now :)

**Comment by mrunalp** [comment]
Will probably need changes to the go-capability package first.

**Comment by justincormack** [comment]
Already submitted a PR there...

**Comment by justincormack** [comment]
ok that just got merged https://github.com/syndtr/gocapability/pull/11#event-805044468 can do the runc PR now and the docs PR for here.

**Comment by justincormack** [comment]
Runc PR https://github.com/opencontainers/runc/pull/1086

**Comment by justincormack** [comment]
PR in https://github.com/docker/docker/pull/26979

**Comment by justincormack** [comment]
This is now merged in master, #26979 is now just a docs and tests PR, so I am closing this issue!

**Comment by jcberthon** [comment]
I just want to make sure my current issue is covered by this one or not.

I'm running Docker with user namespace activated (`--userns-remap=default`). In the container I only run ntpd as "root" on port 123/udp. The container is ran with option `--add-cap NET_BIND_SERVICE`.

However ntpd fails to bind to port 123. As it's running as root inside the container within its own network namespace I'm totally surprised. I understand that root inside the container is mapped to a non-root user outside. I understand also that the ntpd binary does not have the capability set on the file. But because it's running inside its own user and network namespace and that I explicitly specify the capability when running the container I don't understand why it fails. 

And as I don't get it, I'm not sure if my issue is covered here or not. In addition it's cool if the ambiant capability can solve this issue (and I do have a newer kernel) but then it greatly limits how I can share my Dockerfile or image with others.

**Comment by thaJeztah** [comment]
reopening because we reverted this change for now, see https://github.com/docker/docker/pull/27737

**Comment by justincormack** [comment]
Hoping to fix for 1.14 instead...

**Comment by justincormack** [comment]
Ok, opened a new PR for `runc` https://github.com/opencontainers/runc/pull/1286 and will open an updated one here soon.

**Comment by vishvananda** [comment]
Just an fyi, for people that don't want to deal with CAP_NET_BIND_SERVICE but would like to bind low ports; as of kernel 4.11, you there is a sysctl that you can set in the network namesace will allow you to bind low ports[1]. If you are using a user namespace and you don't have privileges in the network namespace, you will have to set it on the network namespace before hand, but for everyone else you can actually set it as part of docker run:
```
docker run -it --sysctl net.ipv4.ip_unprivileged_port_start=0 hello
```

[1] http://elixir.free-electrons.com/linux/v4.11.8/source/Documentation/networking/ip-sysctl.txt#L832

**Comment by vdemeester** [comment]
Seems like this can be closed 👼

**Comment by jcberthon** [comment]
Hi @vdemeester 

As far as I can see the runc spec now defines how to set ambient capabilities which could solve this problem (see https://github.com/opencontainers/runtime-spec/pull/675). But as far as I can tell, this is not yet implemented in Docker (or Moby), at least on the command line or in compose files.

Therefore I would expect this issue to be kept opened as long as this is not implemented. But I could be misguided.

**Comment by thaJeztah** [comment]
Yes, I think @justincormack was looking at that a while back

**Comment by justincormack** [comment]
There is a Kubernetes proposal to support ambient capabilities in CRI https://github.com/kubernetes/community/pull/2285 we will probably implement something in Docker to support that when it happens.

**Comment by irsl** [comment]
I couldn't find this documented anywhere, so adding here. This is how to switch user to a non-privileged one while keeping a certain capability (net_bind_service in this example). Busybox/alpine based images need bash to be installed first next to libcap.

`capsh --caps="cap_net_bind_service+eip cap_setgid,cap_setuid+ep" --gid=1000 --uid=1000 --print  -- -c "exec /my/favourity/webserver"
`

**Comment by mjameswh** [comment]
Is there any actual risk to set `--sysctl net.ipv4.ip_unprivileged_port_start=0` on a container when that container is attached only to bridge networks (or actually, pretty much )? After all, even if a process open an extra low port from inside the container, it wont be accessible unless the port is actually exposed and mapped to an external port, from the host.

What I mean by this is that setting `net.ipv4.ip_unprivileged_port_start` to 0 by default (that is, unless  the container is attached directly to a network of type host) would appears to be a possible and reasonable solution. Of course, this is arguably a patch, and yes this could be simply be highlighted in documentation. However, from the large number of outside tickets pointing to this one, it seems to be a very common issue, and it appears that many people, if not most, ends up lowering their security (by running their container as root) because they failed to find documentation on how to fix the issue by themselves.
