### ISSUE TITLE
Proposal: exposing SCTP ports for container

### ISSUE THREAD

**Issue by rickhofstede** [moby/moby#9689]
While trying to expose an incoming SCTP port for my container, I found out that something like `-p x:y/sctp` is not yet supported. It would be great to have the flexibility of exposing ports for any protocol for a container, although SCTP currently has the highest priority on my wish list.

**Comment by duglin** [comment]
ping @crosbymichael @mavenugo is there any reason, aside from trying to fail fast, that we don't just let the protocol string be passed all the way down to the iptables call and let unknown/invalid protocols be detected at that point? Then we don't need to check in docker itself and just let the underlying OS decide.

**Comment by thaJeztah** [comment]
ping @mavenugo could you answer this?

**Comment by mavenugo** [comment]
With CNM (Container Networking Model), container connectivity across multiple hosts can be achieved through various drivers/plugins. Some of the drivers such as the in-built overlay, supports these container connectivity without the need to port mapping. Hence SCTP or other protocols can just work without the need to map or expose ports.

But, in order to expose the service provided by a container to external networks not managed under CNM, we may have to do port-mapping and hence this request must be addressed. Also, the concept of external connectivity varies under different deployment scenario. This enhancement request should be included in that context when making design decisions.

**Comment by LK4D4** [comment]
@mavenugo @mrjana @sanimej @aboch still need to be addressed?

**Comment by razaborg** [comment]
What is the actual status of this feature ? 
I'm currently facing the problem to expose a sctp port on the host, and that still seems to be unsupported

**Comment by AkihiroSuda** [comment]
@razaborg 

@ishidawataru opened PR #33922

**Comment by AkihiroSuda** [comment]
libnetwork-side PR has been opened as https://github.com/docker/libnetwork/pull/1825

Anyone please look into the PR?

**Comment by Peter-eid** [comment]
@mavenugo What is the current status of this feature ?

**Comment by rkbug** [comment]
@mavenugo (Madhu), Can you please update the current status of this feature?

**Comment by verizonold** [comment]
hi  can you please provide details on how SCTP is now supported? Any examples that you can share?

**Comment by thaJeztah** [comment]
I think all PR's are merged now, and will be included in Docker 18.03 (release candidates are available); see 

- https://github.com/docker/libnetwork/pull/1825
- https://github.com/docker/swarmkit/pull/2298
- https://github.com/docker/go-connections/pull/41
- https://github.com/docker/cli/pull/278
- https://github.com/docker/cli/pull/900
- https://github.com/docker/docker.github.io/pull/6078

Closing this issue, because it looks like we're done, but feel free to comment in case I missed something

**Comment by verizonold** [comment]
do you know if Kubernetes supports SCTP?

**Comment by verizonold** [comment]
@thaJeztah  Can you please provide me a pointer to Docker 18.03? Should I see this in Edge releases?

**Comment by thaJeztah** [comment]
It's not released yet; release candidates are available in the "test" channel, or through the install script at https://test.docker.com

**Comment by verizonold** [comment]
@thaJeztah thanks...so I just run this script on my CentOS VM? Also, I would like to try the support for SCTP. Can you please provide some doc/info on how to use this feature in docker?

**Comment by thaJeztah** [comment]
@verizonold from docker's perspective it's mainly allowing you to specify `sctp` in addition to `tcp` or `udp` when publishing container ports. What to use it for / how you use it for things running in your container is a bit out of scope.

**Comment by verizonold** [comment]
@thaJeztah thanks...so what is the link to the release candidates in the "test" channel?

**Comment by AkihiroSuda** [comment]
@verizonold you just need to do 
```
# For test builds (ie. release candidates):
#   $ curl -fsSL test.docker.com -o test-docker.sh
#   $ sh test-docker.sh
```

Kubernetes-part hasn't been worked out yet.

**Comment by teknoraver** [comment]
Hi all.

Are memory cgroups limits enforced for SCTP kernel buffers?
I hope I'm wrong, but looking at the code it seems not.
Please do proper testing before enabling SCTP by default.

**Comment by thaJeztah** [comment]
@AkihiroSuda ^^ think you may have more insight into that

**Comment by teknoraver** [comment]
@AkihiroSuda exactly that one. One to avoid that a process will waste all the system memory?

**Comment by AkihiroSuda** [comment]
Although not specific to SCTP buffer, does `docker run --kernel-memory`  (which sets `memory.kmem.limit_in_bytes`) works for you?

**Comment by Jacob-E** [comment]
Is there a way to run userspace sctp stack in the container?

**Comment by teknoraver** [comment]
I don't think so.
Running an userspace layer 4 protocol requires you to have RAW socket permissions, which is unlikely in containers.

**Comment by teknoraver** [comment]
Hi,

I recently discovered this, which is strictly related to this issue:

https://access.redhat.com/security/cve/cve-2019-3874
